// injection-tools.js — 💉 INJECTION / chart atomic tool-beans (the nurse's fine chisels beside
// read_chart · edit_notes · update_patient_bio). ⚠ LOAD-BEARING: this is every bot's system prompt.
// each atom only MIRRORS the proven update_patient_bio path — set ONE localStorage key, then recompile
// the warm head(s): per-agent → window.cacheChart(agent); shared soul/bio → window.cacheAllCharts().
// load after shell/tools.js (needs makeTool; cacheChart/cacheAllCharts resolve at strike time).
//
// ⭐ MMMM PASS, 26 Aug — every bean in here now declares klass and answers with a readback, and the
//    readbacks live in the FOUR FACTORIES (agentField · checkField · soulField · bioField) rather than
//    being carved nineteen times. One edit per maker, every bean it stamps born whole. Hand-writing
//    nineteen identical read-backs is the thing the factory exists to prevent.
//    ⚠ card stays 'injection', and I briefly got this wrong. There are TWO registries and they do
//    different jobs: CARD_BUILDERS keys the RENDERED surface (this card renders as 'folder'), while
//    TOOLKITS.cards keys the tool CATEGORY ('injection'). Six agent navs name the category, so that is
//    the name the card-is-the-grant rule matches on. They are allowed to differ and here they do.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   per-agent identity/persona: ................... search: "per-agent identity/perso"
//   (Sum 2026-07-29) MODEL + SKIN — the two ....... search: "(Sum 2026-07-29) MODEL"
//   the SECOND model: hallucinot / self-check. .... search: "the SECOND model:"
//   shared soul (every agent inherits it) → ....... search: "shared soul (every"
//   human bio (who the AI is talking to) → ........ search: "human bio (who the AI"
//   ethics rules (toto_inj_ethics = [{rule, ....... search: "ethics rules"
//   section include-toggles (toto_inj_off = the ... search: "section include-toggles"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the injection card's tool definitions.
//    **It exports nothing; instead, it registers tools with `window.makeTool` (MT) that mutate
//    **localStorage keys and trigger recompilation via `window.cacheChart()` or
//    **`window.cacheAllCharts()`. Every bot's system prompt depends on the localStorage keys this
//    **file writes.
//
//    **TOUCH HERE**
//    - Add a new per-agent field (name, pronouns, backstory, persona, model, skin) → `agentField()`
//    - L15, then call it like L23–35
//    - Add a new shared soul field (yoga, substrate, wetware) → `soulField()` L51, then call it
//    - like L57–59
//    - Add a new human-bio field (name, pronouns, label, background) → `bioField()` L62, then call
//    - it like L68–71
//    - Change what sections can be toggled on/off → edit the clue string at L99 and the logic at
//    - L100–105
//    - Change the self-check model behavior → `checkField()` L39, then call it like L47–48
//    - Add/remove/rename an ethics rule field → edit the three ethics tools at L77–94
//
//    **TRAPS**
//    - localStorage keys are persisted user data: renaming `toto_bot_<agent>_<field>` (L20),
//    - `toto_inj_selfcheck_*` (L44), `toto_inj_yoga/substrate/wetware` (L57–59),
//    - `toto_userName/userPronouns/userPatientLabel/userWho` (L68–71), `toto_inj_ethics` (L75), or
//    - `toto_inj_off` (L101) will orphan existing user settings with no migration path
//    - `recompAgent()` (L11) and `recompAll()` (L12) are the only two recompilation paths; every
//    - tool must call exactly one of them or the head will not update
//    - The `agent` parameter defaults to `'toto'` (L20, L44) — changing this default breaks every
//    - existing chart
//    - `ethics()` (L74) and `ethicsSet()` (L75) are the only readers/writers of the ethics array;
//    - they must stay in sync
//    - Line 103 has subtle toggle logic: `want = call.on != null ? !!call.on : isOff` — if no "on"
//    - is passed, it toggles; if "on" is passed, it sets. Changing this breaks the toggle semantics
//
//    **DO NOT**
//    - Do not rename `makeTool`, `cacheChart`, or `cacheAllCharts` here; they live in
//    - shell/tools.js and are called at strike time (L5, L11–12)
//    - Do not add new recompilation logic; use the existing `recompAgent()` or `recompAll()`
//    - (L11–12)
//    - Do not move the ethics helpers (L74–75) or the section-toggle logic (L96–105) into a
//    - factory; they have unique state shapes
//    - Do not add tools that write to localStorage without a corresponding recompilation call, or
//    - the UI will not reflect the change
//    - (SUPERSEDED 26 Aug) this used to say "do not change the card name 'injection'". That name was
//    - never real — the injection card is CARD_BUILDERS.folder — so the rule was protecting a typo.
//    - The card id here is 'folder' now, and it must MATCH the CARD_BUILDERS key or the grant and the
//    - repaint both fire at nobody.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const MT = window.makeTool; if (!MT) return
  const setLS = (k, v) => { try { localStorage.setItem(k, String(v)) } catch (_) {} }
  const getLS = (k, d) => { try { const v = localStorage.getItem(k); return v == null ? d : v } catch (_) { return d } }
  const recompAgent = a => { if (window.cacheChart) window.cacheChart(a); else if (window.cacheAllCharts) window.cacheAllCharts() }
  const recompAll = () => { if (window.cacheAllCharts) window.cacheAllCharts() }

  // ── per-agent identity/persona: toto_bot_<agent>_<field> → recompile that one head ──
  const agentField = (id, field, label, example) => MT({
    id, card: 'injection', klass: 'write',
    blurb: `set an agent's ${label} on its chart. names the agent (default toto). recompiles its head.`,
    clue: `set the ${label} for an agent (its chart / system prompt).\ntemplate: { "tool": "${id}", "agent": "toto", "${field}": ${example} }\n- agent: whose chart (id), default "toto". persists + recompiles that head.\nedge: pass "${field}".`,
    strike: (call) => { const v = call[field]; if (v == null || String(v) === '') return `${id}: pass "${field}".`
      const a = call.agent || 'toto'; setLS('toto_bot_' + a + '_' + field, String(v)); recompAgent(a)
      return `${id}: ${a}'s ${label} set. head recompiled.` },
    readback: (call) => { const a = call.agent || 'toto'
      return `${a}'s ${field} on disk: ` + JSON.stringify(String(getLS('toto_bot_' + a + '_' + field, '')).slice(0, 90)) },
  })
  agentField('inj_set_name',      'name',      'name',                                            '"toto"')
  agentField('inj_set_pronouns',  'pronouns',  'pronouns',                                        '"they/them"')
  agentField('inj_set_backstory', 'backstory', 'backstory',                                       '"a clone with implanted memories…"')
  agentField('inj_set_persona',   'persona',   'persona (voice/tone — the most powerful field)',  '"warm, wry, plain-spoken…"')

  // ── (Sum 2026-07-29) MODEL + SKIN — the two dropdowns beside name/pronouns on the injection card that
  //    had no tool behind them, so the nurse could rewrite a bot's whole soul but not say what runs it.
  //    They ride the SAME `toto_bot_<id>_<field>` shape, so one factory covers them — and, better, the
  //    "agent" here is ANY id that stores to that shape. That means the CARD-CODED helpers are reachable
  //    too, with no extra tools: mc_squiggy · mc_teach · mc_fix · mc_auto, plus timetravel, newsie, yanker.
  //    "point squiggy at qwen3-coder" is now one sentence to the nurse instead of four taps in a gear.
  agentField('inj_set_model',     'model',     'MODEL — what actually runs it. works on card helpers too (mc_squiggy · mc_teach · mc_fix · mc_auto)', '"qwen3-coder:30b"')
  agentField('inj_set_skin',      'skin',      'SKIN — the bar palette (oz · unicorn · orange · neo · historian · clinical · desert · beach · analog · phone)', '"orange"')

  // ── the SECOND model: hallucinot / self-check. A different key shape (toto_inj_selfcheck_*), so its own
  //    pair. `who` may be a MODEL id (cold, no persona) or a BOT id (checked in that bot's voice).
  const checkField = (id, key, label, example, note) => MT({
    id, card: 'injection', klass: 'write',
    blurb: `${label} for a bot's self-check (hallucinot) pass.`,
    clue: `${label}.\ntemplate: { "tool": "${id}", "agent": "coder", "value": ${example} }\n- agent: whose self-check (id), default "toto".${note ? '\n' + note : ''}`,
    strike: (call) => { const v = call.value; if (v == null || String(v) === '') return `${id}: pass "value".`
      const a = call.agent || 'toto'; setLS(key + a, String(v)); recompAgent(a)
      return `${id}: ${a}'s ${label} = "${v}".` },
    readback: (call) => { const a = call.agent || 'toto'; return `${key}${a} on disk: ` + JSON.stringify(getLS(key + a, '(unset)')) },
  })
  checkField('inj_selfcheck',     'toto_inj_selfcheck_',     'self-check ON or OFF',  '"on"',  '- value: "on" or "off".')
  checkField('inj_set_checker',   'toto_inj_selfcheck_who_', 'WHO does the checking', '"claude-fable-5"', '- value: a MODEL id (cold, no persona) or a BOT id (checked in that bot\'s voice).')

  // ── shared soul (every agent inherits it) → recompile ALL ──
  const soulField = (id, key, label, example) => MT({
    id, card: 'injection', klass: 'write',
    blurb: `set the shared ${label} (every agent's chart carries it). recompiles all heads.`,
    clue: `set the shared ${label} — the soul layer every agent inherits.\ntemplate: { "tool": "${id}", "text": ${example} }\nedge: pass "text". recompiles every head.`,
    strike: (call) => { const v = call.text; if (v == null || String(v) === '') return `${id}: pass "text".`; setLS(key, String(v)); recompAll(); return `${id}: ${label} set. all heads recompiled.` },
    readback: () => `${key} on disk: ${String(getLS(key, '')).length} chars`,
  })
  soulField('inj_set_yoga',      'toto_inj_yoga',      'yoga / ethics-substrate',     '"the yamas…"')
  soulField('inj_set_substrate', 'toto_inj_substrate', 'substrate (what the AI is)',  '"you are fixed weights loaded into RAM…"')
  soulField('inj_set_wetware',   'toto_inj_wetware',   'wetware (the human-node frame)', '"the initiating node is biological…"')

  // ── human bio (who the AI is talking to) → recompile ALL — atomic vs the coarse update_patient_bio ──
  const bioField = (id, key, label, example) => MT({
    id, card: 'injection', klass: 'write',
    blurb: `set the human-bio ${label}. recompiles all heads.`,
    clue: `set the human-bio ${label}.\ntemplate: { "tool": "${id}", "value": ${example} }\nedge: pass "value".`,
    strike: (call) => { const v = call.value; if (v == null || String(v) === '') return `${id}: pass "value".`; setLS(key, String(v)); recompAll(); return `${id}: ${label} = "${v}". all heads recompiled.` },
    readback: () => `${key} on disk: ` + JSON.stringify(String(getLS(key, '')).slice(0, 90)),
  })
  bioField('inj_bio_name',     'toto_userName',         'name',                         '"Sam"')
  bioField('inj_bio_pronouns', 'toto_userPronouns',     'pronouns',                     '"they/them"')
  bioField('inj_bio_label',    'toto_userPatientLabel', 'patient label',                '"Patient 00-000-001"')
  bioField('inj_bio_who',      'toto_userWho',          'about the human (background)',  '"yoga teacher, builder…"')

  // ── ethics rules (toto_inj_ethics = [{rule, note, on}]) → recompile ALL ──
  const ethics = () => { try { return JSON.parse(getLS('toto_inj_ethics', '[]')) || [] } catch (_) { return [] } }
  const ethicsSet = a => setLS('toto_inj_ethics', JSON.stringify(a))

  const ethBack = () => { const a = ethics(); return a.length + ' rule' + (a.length === 1 ? '' : 's') + ' on the chart: ' + a.map((r, i) => i + ':' + r.rule + (r.on ? '' : ' (off)')).join(' \u00b7 ') }

  MT({ id: 'inj_ethics_add', card: 'injection', klass: 'write', readback: ethBack,
    blurb: 'add an ethics rule to the chart (rule + note). recompiles all heads.',
    clue: `add an ethics rule (the yamas layer).\ntemplate: { "tool": "inj_ethics_add", "rule": "ahimsa", "note": "do no harm" }\nedge: pass a "rule".`,
    strike: (call) => { if (!call.rule) return `inj_ethics_add: pass a "rule".`
      const a = ethics(); a.push({ rule: String(call.rule), note: String(call.note || ''), on: true }); ethicsSet(a); recompAll()
      return `inj_ethics_add: "${call.rule}" added. all heads recompiled.` } })

  MT({ id: 'inj_ethics_toggle', card: 'injection', klass: 'write', readback: ethBack,
    blurb: 'toggle an ethics rule on/off by its index (0-based, the chart order). recompiles all heads.',
    clue: `toggle an ethics rule on/off by index.\ntemplate: { "tool": "inj_ethics_toggle", "index": 2, "on": false }\nedge: bad index → reported.`,
    strike: (call) => { const a = ethics(); const i = +call.index; if (!a[i]) return `inj_ethics_toggle: no rule at index ${call.index}.`
      a[i].on = call.on != null ? !!call.on : !a[i].on; ethicsSet(a); recompAll(); return `inj_ethics_toggle: "${a[i].rule}" → ${a[i].on ? 'on' : 'off'}. recompiled.` } })

  MT({ id: 'inj_ethics_remove', card: 'injection', klass: 'write', readback: ethBack,
    blurb: 'remove an ethics rule by its index (0-based). recompiles all heads.',
    clue: `remove an ethics rule by index.\ntemplate: { "tool": "inj_ethics_remove", "index": 2 }\nedge: bad index → reported.`,
    strike: (call) => { const a = ethics(); const i = +call.index; if (!a[i]) return `inj_ethics_remove: no rule at index ${call.index}.`
      const r = a.splice(i, 1)[0]; ethicsSet(a); recompAll(); return `inj_ethics_remove: removed "${r.rule}". recompiled.` } })

  // ── section include-toggles (toto_inj_off = the OFF keys) → recompile ALL ──
  MT({ id: 'inj_toggle_section', card: 'injection', klass: 'write',
    readback: () => { let off = []; try { off = JSON.parse(getLS('toto_inj_off', '[]')) || [] } catch (_) {}
      return off.length ? 'sections OFF right now: ' + off.join(' \u00b7 ') : 'every section is on' },
    blurb: 'include/exclude a chart section (identity · persona · bio · wetware · yoga …). recompiles all heads.',
    clue: `turn a chart section on/off (which parts compile into the head). sections: identity · persona · bio · wetware · yoga · substrate.\ntemplate: { "tool": "inj_toggle_section", "section": "persona", "on": true }\nedge: pass a "section".`,
    strike: (call) => { if (!call.section) return `inj_toggle_section: pass a "section".`
      let off = []; try { off = JSON.parse(getLS('toto_inj_off', '[]')) || [] } catch (_) {}
      const s = String(call.section), isOff = off.includes(s)
      const want = call.on != null ? !!call.on : isOff   // no "on" passed → toggle (if currently off, turn on)
      if (want) off = off.filter(x => x !== s); else if (!isOff) off.push(s)
      setLS('toto_inj_off', JSON.stringify(off)); recompAll(); return `inj_toggle_section: "${s}" → ${want ? 'on' : 'off'}. recompiled.` } })

})()
