// build.js — sync the Monaco TEMPLATE FOLDERS → cards/monaco/templates.gen.js. THE FOLDER IS THE SOURCE.
//
// why this exists: at file:// the browser refuses to let JS READ a local file (fetch is blocked) — so a
// folder template can't be slurped into the editor at runtime. this bakes each folder into a bundle the
// browser CAN load: text files as strings (editable in Monaco), binary assets as a root-relative PATH (the
// preview resolves them via bundleSandbox → an absolute file:// url; NO base64). mirror of agents/build.js.
// Tauri skips this (Rust reads the folder off disk). the bundle is the file:// shim, nothing more.
//
//   node cards/monaco/templates/build.js          one sync (re-run after editing any template folder)

const fs = require('fs'), path = require('path')
const TPL  = __dirname                                  // cards/monaco/templates
const ROOT = path.resolve(TPL, '..', '..', '..')        // toto2 root (paths are stored relative to here)
const TEXT = new Set(['html', 'htm', 'js', 'mjs', 'css', 'json', 'md', 'txt', 'svg'])
// binary → a data: URI so it renders INSIDE the srcdoc run (a null-origin page can't reach file://; a data:
// URI lives in the page and survives). this is what Webpack/Vite do — inline assets. mime by extension.
const MIME = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp',
  ico: 'image/x-icon', bmp: 'image/bmp', woff: 'font/woff', woff2: 'font/woff2', ttf: 'font/ttf', otf: 'font/otf',
  mp3: 'audio/mpeg', wav: 'audio/wav', ogg: 'audio/ogg' }
// each folder template + its ENTRY file (the page that RUNS in the preview)
const ENTRY = { snake: 'index.html', toto: 'index.html', jenga: 'jenga.html', pong: 'pong.html', colonialism: 'colonialism.html', jenga2: 'jenga2.html', snek: 'snek.html', butcher: 'butcher.html' }

function collect(dir, base, out) {
  for (const name of fs.readdirSync(dir).sort()) {
    const fp = path.join(dir, name)
    if (fs.statSync(fp).isDirectory()) { collect(fp, base, out); continue }
    const rel = path.relative(base, fp).split(path.sep).join('/')
    const ext = (name.split('.').pop() || '').toLowerCase()
    if (TEXT.has(ext)) { out.push({ name: rel, kind: 'code', data: fs.readFileSync(fp, 'utf8') }); continue }
    const mime = MIME[ext] || 'application/octet-stream'
    const data = `data:${mime};base64,${fs.readFileSync(fp).toString('base64')}`
    out.push({ name: rel, kind: /^image\//.test(mime) ? 'image' : 'asset', mime, data })
  }
}

const data = {}
for (const [key, entry] of Object.entries(ENTRY)) {
  const dir = path.join(TPL, key)
  if (!fs.existsSync(dir)) { console.warn('  skip (no folder): ' + key); continue }
  const files = []; collect(dir, dir, files)
  data[key] = { entry, files }
}
const banner =
  '// templates.gen.js — GENERATED by cards/monaco/templates/build.js. DO NOT EDIT BY HAND.\n' +
  '// source of truth = cards/monaco/templates/<key>/. re-run `node cards/monaco/templates/build.js` after editing a template.\n'
fs.writeFileSync(path.join(TPL, '..', 'templates.gen.js'),
  banner + 'window.MONACO_TEMPLATE_FILES = ' + JSON.stringify(data) + '\n')
console.log('✓ built templates.gen.js — ' + Object.entries(data).map(([k, v]) => k + ' (' + v.files.length + ' files)').join(' · '))
