// build.js — sync the agent FOLDER → the browser bundle. THE FOLDER IS THE SOURCE OF TRUTH.
//
// reads  agents/agents.json (the roster index)
//   then agents/<id>/<id>.json      (identity: icon · nav · also · tools)
//   then agents/<id>/injection.json (custom injection: pronouns · persona · backstory · baked)
// writes shell/agents.gen.js — window.AGENT_DATA = { <id>: {merged record}, … }
//
// usage:  node agents/build.js            one sync
//         node agents/build.js --watch     sync, then re-sync on every folder change (the wristwatch)
//
// the browser loads the bundle (it can't fetch the folder at file://). Tauri SKIPS this entirely —
// Rust reads the folder json straight off disk. the bundle is the file:// shim, nothing more.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   watch — the wristwatch. edit any agent ... search: "watch — the wristwatch."
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for `window.AGENT_DATA`, a merged object
//    **written to `shell/agents.gen.js` (line 35). The bundle contains one record per agent ID,
//    **combining identity metadata from `agents/<id>/<id>.json` with custom injection from
//    **`agents/<id>/injection.json`. Tauri bypasses this entirely; the browser uses it only as a
//    **file:// shim (line 11–12).
//
//    **TOUCH HERE**
//    - Add a new field to every agent record → modify the merge at `data[id] = …` (line 29)
//    - Change which JSON files are read → edit `readJSON()` calls at lines 27–28
//    - Change the output filename or location → edit `path.join(SHELL, 'agents.gen.js')` (line 35)
//    - Change the output format (JSON structure, banner, etc.) → edit lines 31–35
//    - Add a new agent → add its ID to `agents/agents.json`; this file reads it automatically (line
//    - 23)
//    - Adjust watch debounce timing → change `120` at line 52
//
//    **TRAPS**
//    - The roster is read from `agents/agents.json` (line 23), not by scanning the folder. An agent
//    - folder that exists but is not listed there will be silently ignored.
//    - The merge at line 29 gives `injection` fields priority over `identity` fields (`{
//    - ...identity, ...injection }`). Renaming a field in one file but not the other will not
//    - error; it will just shadow silently.
//    - The banner at lines 31–34 is hardcoded text; if you change the output path (line 35), update
//    - the banner to match, or developers will look in the wrong place.
//    - The `_` field (comment field) is stripped by `stripDoc()` (line 19) before merge. If you
//    - need comments in the bundle, you must change this function and the merge logic together.
//    - The watch mode (line 43) only triggers on `.json` file changes (line 47). Renaming or moving
//    - a file will not trigger a rebuild.
//
//    **DO NOT**
//    - Rename `window.AGENT_DATA` without updating the browser code that reads it (that lives
//    - elsewhere).
//    - Change the shape of the merged record without checking what the browser expects from
//    - `window.AGENT_DATA[id]`.
//    - Add logic to validate agent records here; that belongs in a separate linter or schema
//    - checker.
//    - Hardcode agent IDs or metadata in this file; it is a pure reader and merger.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


const fs = require('fs')
const path = require('path')
const AGENTS = __dirname
const SHELL = path.join(__dirname, '..', 'shell')

const stripDoc = o => { const c = { ...o }; delete c._; return c }   // drop the "_" comment field
const readJSON = p => { try { return JSON.parse(fs.readFileSync(p, 'utf8')) } catch (_) { return {} } }


// ── THE FOUR-ORGAN CHECK (Sum 2026-08-16: "the bot builder bean seems to be nailing the top bar
//    buttons, but not handling tools and cards as seamlessly as I would like"). The builder was a pure
//    reader and merger — it validated NOTHING, so a bot could ship with a card that does not exist or a
//    tool that is not a bean and the only symptom was the bot quietly not doing the thing. The bars felt
//    solid only because they are seeded by hand in workspace.js; the tools and cards had no such net.
//    Reads the other files and compares. Still no hardcoded agent ids — the DO NOT above stands.
function lint(data) {
  const slurp = p => { try { return fs.readFileSync(p, 'utf8') } catch (_) { return '' } }
  const all = f => { let out = ''; try { for (const d of fs.readdirSync(f)) { const q = path.join(f, d)
    if (fs.statSync(q).isDirectory()) { for (const g of fs.readdirSync(q)) if (g.endsWith('.js')) out += slurp(path.join(q, g)) }
    else if (d.endsWith('.js')) out += slurp(q) } } catch (_) {} ; return out }
  const src = all(SHELL) + all(path.join(AGENTS, '..', 'cards'))
  const grab = (re, s) => { const o = new Set(); let m; while ((m = re.exec(s))) o.add(m[1]); return o }

  // BEANS: `makeTool({` / `MT({` put id and card on SEPARATE lines, so scan a window after each
  //   opener rather than demanding they be adjacent (the first cut demanded adjacency and cried wolf on
  //   ~140 real tools).
  const beanCard = {}
  { let m; const re = /(?:makeTool|MT)\(\s*\{/g
    while ((m = re.exec(src))) { const w = src.slice(m.index, m.index + 400)
      const i = /id:\s*'([a-z_0-9]+)'/.exec(w); if (!i) continue
      const c = /card:\s*(?:'([a-z0-9-]+)'|null)/.exec(w)
      beanCard[i[1]] = c ? (c[1] || null) : null } }
  // CARDS: same lesson as tools. Registration has three forms — CARD_BUILDERS.x, ['x'], and a DYNAMIC
  //   [id] no regex resolves — and the folder layout does not match either (food/sleep/exercise are
  //   registered from a shared file, with no cards/food/ dir). Both guesses cried wolf. The running app
  //   is the only honest source, so cards come from the boot report too, or the check is skipped.

  const barsSrc = slurp(path.join(SHELL, 'workspace.js')).split('AGENT_BARS = {')[1] || ''
  const bars    = grab(/^  ([a-z0-9_-]+):\s*\{/gm, barsSrc)
  const reg     = grab(/\{\s*id:\s*'([a-z0-9_-]+)',\s*label:/g, slurp(path.join(SHELL, 'registry.js')))

  // a scan that found nothing is a BROKEN SCAN, not 24 broken bots — say so and check nothing.
  const dead = []
  if (!Object.keys(beanCard).length) dead.push('tool beans')
  if (!bars.size) dead.push('AGENT_BARS'); if (!reg.size) dead.push('registry')
  if (dead.length) { console.log('  ⚠ lint skipped — could not scan: ' + dead.join(', ') + ' (a pattern moved; fix the regex in build.js lint())'); return }

  // TOOL TRUTH comes from the RUNNING app, not this scan: cal_in_*, email_in_*, sleep_in_* and friends
  // are registered in LOOPS, so a regex over the source reports ~40 live tools as missing. The black box
  // publishes the real ids at boot; if it has not run since the last rename, skip the check rather than
  // guess (a linter that cries wolf gets ignored, and then it protects nothing).
  let live = new Set(), cards = new Set()
  try { const bp = path.join(require('os').homedir(), 'totoII/sandbox/port/boot-report.json')
        const rep = JSON.parse(fs.readFileSync(bp, 'utf8'))
        live  = new Set(rep.TOOL_IDS || [])
        cards = new Set(rep.CARD_BUILDERS || []) } catch (_) {}
  // ⚠ EVERY single-source card check was wrong, each differently: a regex misses three registration
  //   forms, the folder layout misses cards registered from a shared file (food/sleep/exercise have no
  //   dir), and the boot report snapshots at load+3s so it misses lazily-registered ones (injection).
  //   So: UNION. A card is real if EITHER source knows it. Recall over precision — a linter that flags
  //   a live card teaches the reader to skip the whole report.
  try { for (const d of fs.readdirSync(path.join(AGENTS, '..', 'cards')))
    if (fs.statSync(path.join(AGENTS, '..', 'cards', d)).isDirectory()) cards.add(d) } catch (_) {}
  // ── ⭐ THE FENCE CLASS (26 Aug, third pass — and this line is why the rule exists) ─────────────
  //  This used to be one hand-kept name:
  //        live.add('web_search')   // NOT a bean on purpose — it rides the ```search fence
  //  True, and true of THREE MORE tools it did not name. `route` is the ```cards fence, `create_queue`
  //  is the ```que fence, `confer` is window.confer() — all taught and caught in conductor.js, none of
  //  them beans, all of them live. This check called them typos every build, and on the second pass I
  //  believed it and stripped route + create_queue off toto — which are TOTO'S ONLY TWO TOOLS and the
  //  reason it exists. Sum caught it: "I think I might want those back on, recon further."
  //  An exception list of one is not an exception, it is a rule with a sample size of one. The rule was
  //  already written down where the tools live: TOOLKITS.tools marks every one of them `card: null`,
  //  with the note "they act on AGENTS + the QUEUE, not a card ... the queue layer runs them."
  //  So READ THAT, and the special case disappears. Same doctrine as the whole day's pass: the fact goes
  //  where the thing itself can carry it.
  const TK = path.join(SHELL, 'toolkits.js')
  const tkSrc = slurp(TK)
  const fence = new Set(grab(/(\w+):\s*\{\s*card:\s*null/g, tkSrc))
  fence.forEach(t => live.add(t))
  if (!fence.size) live.add('web_search')   // toolkits.js unreadable → keep the one name that predates the rule

  const say = []
  for (const [id, a] of Object.entries(data)) {
    const nav = (a.nav || []).filter(Boolean), granted = a.tools || []
    if (!reg.has(id))  say.push(`${id}: no line in registry.js — it will show as a "coming soon" placeholder`)
    // a bot may declare that it does not dock — the learner never chats, it builds one lesson section
    // per call through engineRaw slim. That is a real shape, not a missing organ, and the bot says so
    // ("docks": false) rather than this file keeping a name-list of exceptions. Silence still means yes:
    // a bot that has simply not been given a bar must keep getting flagged, which is the common case.
    if (!bars.has(id) && a.docks !== false) say.push(`${id}: no AGENT_BARS seed in workspace.js — it cannot dock`)
    for (const c of nav) if (cards.size && !cards.has(c)) say.push(`${id}: nav card "${c}" has no CARD_BUILDER — that desk does not exist`)
    // 2 Sep 2026 — THE SECOND MAP. A nav card can exist as a CARD_BUILDER (the desk is real) and still be missing from
    //    shell/toolkits.js's `cards` map — and cardsFor() filters a bot's nav through THAT map. Vogel's vault was exactly this:
    //    a real card, four manicured beans, and every cards fence naming it resolved to nothing, so the turn ended as "just
    //    chat" after one engine call with no recorder. The drift organ compared chart vs menu, never nav vs map. This does.
    try {
      const tkSrc = fs.readFileSync(path.join(SHELL, 'toolkits.js'), 'utf8')
      const open = tkSrc.search(/\bcards\s*:\s*\{/)
      const body = open > -1 ? tkSrc.slice(open, tkSrc.indexOf('\n  }', open) > -1 ? tkSrc.indexOf('\n  }', open) : undefined) : ''
      const tkCards = new Set([...body.matchAll(/^\s{4}([a-z_][\w-]*)\s*:/gm)].map(x => x[1]))
      if (tkCards.size) for (const c of nav) if (!tkCards.has(c)) say.push(`${id}: nav card "${c}" is not on TOOLKITS.cards (shell/toolkits.js) — cardsFor() drops it, so a cards fence naming it ends the turn as "just chat"`)
    } catch (_) {}
    for (const t of granted) if (live.size && !live.has(t)) say.push(`${id}: tool "${t}" is not a registered bean — typo, or it was renamed`)
    // since "the card is the grant" (conductor.js toolLines), a tool on a nav card needs no listing
    const spare = granted.filter(t => beanCard[t] && nav.includes(beanCard[t]))
    if (spare.length) say.push(`${id}: ${spare.length} tool(s) listed that its own card already grants — harmless, droppable: ${spare.join(', ')}`)
  }

  // ── ⭐ THE FIFTH ORGAN — profile.js (26 Aug). A bot can have DATA, a REGISTRY LINE and a BAR and still
  //    be invisible: the green-room cast is built from P.agents directly, and settings.js filters its BOT
  //    list against the same array. Dria had all four organs on 25 Aug and could not be found. Absence is
  //    never neutral in that file; every key has per-consumer semantics.
  const prof = new Set(grab(/'([a-z0-9-]+)'/g, (slurp(path.join(AGENTS, '..', 'profile.js')).split('agents: [')[1] || '').split(']')[0]))
  if (prof.size) for (const id of Object.keys(data)) if (!prof.has(id)) say.push(`${id}: not in profile.js agents[] — it has data, a roster line and a bar, and the green room still cannot show it`)

  // ── ⭐ THE TAUGHT PHANTOM (26 Aug) — the fence-class fix turned this one up on the way past.
  //    Every check above asks whether a BOT names something that does not exist. This asks it of the
  //    CATALOG, and the catalog reaches further than any roster: conductor.js toolLines() prints a
  //    TOOLKITS entry to EVERY bot holding that entry's card — `own.includes(card) || granted.includes(t)`
  //    — so a blurb with a real card and no bean behind it is taught to bots that never listed it.
  //    `read_profiles` (card 'food') was being taught to the nurse AND to wellness on that road; neither
  //    could fire it. A tool a bot is TOLD it has is worse than one it merely lists: it will reach.
  //    card: null entries are the fence class and are skipped — those are real, they just are not beans.
  try {
    const tk = grab(/(\w+):\s*\{\s*card:\s*(?:'[a-z0-9-]+'|null)/g, tkSrc)
    const carded = grab(/(\w+):\s*\{\s*card:\s*'[a-z0-9-]+'/g, tkSrc)
    //  ⚠ AND A STUB IS NOT A PHANTOM. read_room is catalogued on card 'room' — "read/control the lights
    //  — STUBBED (hardware pending). say what you would do." That is not an oversight; it is a placeholder
    //  for hardware that does not exist yet (toolkits.js: "the physical room (lights) — coming, spec 10"),
    //  and it is HONEST — the blurb tells the bot to say what it would do rather than pretend. A tool that
    //  announces its own emptiness cannot mislead the bot holding it, which is the whole harm this organ
    //  exists to catch. So the blurb declares it, the same way "docks": false declares a bot with no bar:
    //  the fact goes where the thing itself carries it, and no name lives in this file.
    const STUB = new RegExp("\\bSTUBBED\\b")
    const blurbOf = t => { const m = new RegExp(t + "\\s*:\\s*\\{[^}]*blurb:\\s*'([^']*)'").exec(tkSrc); return m ? m[1] : '' }
    if (live.size) for (const t of carded) if (!live.has(t) && !STUB.test(blurbOf(t)))
      say.push(`TOOLKITS.${t}: a TAUGHT PHANTOM — catalogued with a card but no bean answers to it. toolLines() prints its blurb to every bot holding that card, so bots are told they have it. Build it, or cut the entry.`)
  } catch (_) {}

  // ── ⭐ THE EMPTY CHAIR — the four organs check bot→world ("does what this bot names exist?"). This is
  //    the reverse: world→bot. A bar with no bot behind it draws a grey bullet and docks nothing. jem left
  //    one on 26 Aug and asterix left another an hour later; neither threw, and neither was found by any
  //    check that existed. A chair is only real if somebody can sit in it.
  for (const b of bars) if (!data[b]) say.push(`AGENT_BARS.${b}: an EMPTY CHAIR — a bar spec for a bot with no data. Cut it, or give the bot a folder.`)

  // ── ⭐⭐ THE LEAK — the one that catches the whole class (Sum 26 Aug: "bots should all be pretty much
  //    identical with different tools and permissions and persona and rules").
  //    A bot-maker can only validate what is IN a bot. Every leak found on 26 Aug was the opposite
  //    direction: a bot's difference living OUTSIDE its record, hardcoded into chrome every bot shares.
  //    The worst of them said "▸ the newsie, at work" in the function that draws EVERY bot's history, so a
  //    fenced turn to the coder was filed under the newsie's name, in the transcript, permanently.
  //    ⚠ IT ONLY FLAGS BEHAVIOUR, NEVER DECLARATION. `id: 'newsie'` and `name: 'newsie'` and
  //    `agents/newsie/…` are how a roster names a bot and are correct. What is not correct is a COMPARISON
  //    or a MEMBERSHIP TEST — === 'newsie', includes('newsie'), ['toto','pa','coder','newsie'] — because
  //    that is a capability or a behaviour, and those belong in the bot's record where the bot can carry
  //    them. Narrow on purpose: build.js's own rule is that a check which cries wolf gets ignored, and
  //    then it protects nothing.
  //  ⚠ NARROWED after the first run cried wolf on half its hits (build.js's own law: "a linter that cries
  //  wolf gets ignored, and then it protects nothing"). A SUITE declaring its own cast — agents: ['coder'],
  //  cards: [...], order: [...] — is the roster naming a bot, which is exactly where a name belongs. Those
  //  lines are dropped before the scan. What survives is a genuine comparison or membership test.
  //  ⚠ GENERATED FILES ARE SKIPPED, and this correction matters more than it looks. shell/engine.js is
  //  BUILT — build.sh cats engine-parts/*.js into it — so every leak in a part was counted twice, and
  //  the first two numbers I reported (70, then 67) were inflated by the whole size of the engine.
  //  A debt number that double-counts is worse than no number: it is a number someone will act on.
  //  (My first attempt at this subtracted the generated TEXT and silently did nothing, because the
  //   concatenation is not a contiguous substring of the scan. Skip by FILENAME; verify the count moved.)
  const GENERATED = new Set(['engine.js', 'agents.gen.js', 'templates.gen.js'])
  //  ⚠ TESTS ARE NOT CHROME (added 26 Aug, after the count went to zero and this was the last hit).
  //  cards/myview/fill-sort.test.js scored a leak for the word 'alpha' — in ['alpha','bravo','charlie',
  //  'delta'], the NATO alphabet, used as fixture headline words. A fixture is not a bot reference, and
  //  a linter that reports it teaches the reader to skip the whole report. Same law as the two narrowings
  //  above; this is the third.
  const skip = f => GENERATED.has(f) || f.endsWith('.test.js')
  const allReal = f => { let out = ''
    try { for (const d of fs.readdirSync(f)) { const q = path.join(f, d)
      if (fs.statSync(q).isDirectory()) { for (const g of fs.readdirSync(q)) if (g.endsWith('.js') && !skip(g)) out += slurp(path.join(q, g)) }
      else if (d.endsWith('.js') && !skip(d)) out += slurp(q) } } catch (_) {}
    return out }
  const codeOnly = (allReal(SHELL) + allReal(path.join(AGENTS, '..', 'cards'))).split('\n')
    .filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l))          // comments are history, not behaviour
    .filter(l => !/\b(agents|cards|order)\s*:\s*\[/.test(l))  // a suite's own cast is a declaration
    //  THE WAIVER, and it is deliberately ugly to type. Some strings that look exactly like a bot id are
    //  not one — a DOM data-widget key, a CSS class, a fixture word. The linter cannot tell, and neither
    //  narrowing above catches it, so the CODE says so out loud: put `not-a-bot` in a comment on that
    //  line with the reason. It is visible in review, it is greppable, and it costs a sentence — which is
    //  the point. Anything cheaper becomes a way to make the number go down without the debt going down.
    .filter(l => !/not-a-bot/.test(l))
    .join('\n')
  for (const id of Object.keys(data)) {
    const q = id.replace(/[-]/g, '\\$&')
    const hits = (codeOnly.match(new RegExp(`(?:[=!]==\\s*'${q}'|'${q}'\\s*[=!]==|includes\\('${q}'\\)|indexOf\\('${q}'\\)|\\[\\s*'${q}'|,\\s*'${q}'\\s*[,\\]])`, 'g')) || []).length
    if (hits) say.push(`${id}: LEAK — its id is used ${hits}× as a comparison or list-membership in shared code. A capability or a behaviour belongs in the bot's record, not in chrome every bot shares.`)
  }
  if (!cards.size) console.log('  · card check skipped — no CARD_BUILDERS in the boot report (launch the app once, then re-run)')
  if (live.size < 2) console.log('  · tool-name check skipped — no TOOL_IDS in the boot report (launch the app once, then re-run)')
  if (!say.length) { console.log('  ✓ four organs check out on every agent (registry · bar · cards · tools)'); return }
  console.log('  ── builder check ' + '─'.repeat(52))
  for (const line of say) console.log('  ' + (/harmless/.test(line) ? '·' : '⚠') + ' ' + line)
}

// ⭐ THE FORGED SEAT (2026-08-25) — the tail of every generated bundle.
//    forge_agent hires a bot at RUNTIME; a folder only exists at BUILD time. Before this, a forged bot was
//    HALF-BORN: on the roster (registry.js absorbs toto_custom_agents into `agents`) with a persona and a
//    bench — and no AGENT_DATA record at all. So write_stack said "no agent", it was granted no tools, and
//    it drew the fallback bullet instead of an icon. Two seats, one bot, which is the yanker ghost again.
//    THIS IS THE ONLY PLACE IT CAN LIVE: the line where AGENT_DATA is born, after the folder is read and
//    before a single consumer has looked. registry.js loads BEFORE this file, so it cannot do it; anything
//    later has already missed the boot grants in tools.js.
//    THE FOLDER ALWAYS WINS — a forged record may ADD a bot, never overwrite one. Promote a keeper by
//    giving it a real agents/<id>/ folder; the forged record then falls silent on its own.
const ABSORB = `
// ── the forged seat: runtime-hired bots (toto_custom_agents) join AGENT_DATA here. folder wins. ──
;(function () {
  try {
    var custom = JSON.parse(localStorage.getItem('toto_custom_agents') || '[]')
    for (var i = 0; i < custom.length; i++) {
      var a = custom[i]
      if (!a || !a.id || window.AGENT_DATA[a.id]) continue      // a folder bot is never overwritten
      window.AGENT_DATA[a.id] = {
        id: a.id, name: a.label || a.id, forged: true,
        icon: a.icon || { emoji: '\\u{1F9E9}' },
        nav: Array.isArray(a.nav) ? a.nav : [],
        also: a.also || [],
        tools: Array.isArray(a.tools) ? a.tools : [],
        role: Array.isArray(a.role) ? a.role : (a.role ? [a.role] : []),
        pronouns: a.pronouns || 'they/them',
        persona: a.persona || '',                                 // toto_bot_<id>_persona overrides this
        backstory: a.backstory || '',
        baked: a.baked || null
      }
    }
  } catch (_) {}
})()
`

function build() {
  const roster = readJSON(path.join(AGENTS, 'agents.json')).agents || []
  // ⭐ THE GUARD (Sum 2026-08-26: "add one line check"). readJSON SWALLOWS a parse error and returns {},
  //    so a malformed agents.json made `roster` an empty array and this function cheerfully wrote an
  //    EMPTY BUNDLE over a good one. It happened for real today: removing entries left a trailing comma,
  //    this ran, and "✓ synced 0 agents" scrolled past looking like success. Nothing threw. The app boots
  //    fine with zero agents — it just has no bots, which you notice a while later.
  //    An empty roster is never a legitimate build, so refuse instead of shipping it.
  if (!roster.length) { console.error('✗ REFUSED — agents/agents.json gave 0 agents (missing, empty, or malformed JSON). shell/agents.gen.js was NOT touched. Fix the roster and re-run.'); process.exit(1) }
  const data = {}
  for (const id of roster) {
    const dir = path.join(AGENTS, id)
    const identity  = stripDoc(readJSON(path.join(dir, id + '.json')))
    const injection = stripDoc(readJSON(path.join(dir, 'injection.json')))
    data[id] = { ...identity, ...injection }   // identity + custom injection = the full agent record
  }
  const banner =
    '// agents.gen.js — GENERATED by agents/build.js. DO NOT EDIT BY HAND.\n' +
    '// source of truth = agents/<id>/<id>.json + agents/<id>/injection.json\n' +
    '// re-run `node agents/build.js` to refresh after editing any agent folder.\n'
  const roles = stripDoc(readJSON(path.join(AGENTS, 'roles.json')))   // shared role sheets — see roles.json
  fs.writeFileSync(path.join(SHELL, 'agents.gen.js'), banner + 'window.AGENT_DATA = ' + JSON.stringify(data, null, 2) + '\n'
    + 'window.ROLE_SHEETS = ' + JSON.stringify(roles, null, 2) + '\n' + ABSORB)
  try { lint(data) } catch (e) { console.log('  ⚠ lint stumbled: ' + e.message) }   // a bad check must never block a good build
  return roster
}

const roster = build()
console.log('✓ synced ' + roster.length + ' agents (' + roster.join(' · ') + ') → shell/agents.gen.js')

// --watch — the wristwatch. edit any agent folder file, the bundle refreshes itself (debounced).
// ⭐ 2026-09-01 — refresh the WHERE-TO-LOOK index on every build (Sum: "the one part of this you can
//    hand to a script and stop thinking about"). It reads the source for goalie call sites, fence tags
//    and flight-recorder paths, so the countable half of the notes can never go stale again. Chained
//    here rather than left as a command to remember: a rule nobody is stopped by scored 6 of 159.
try { require('./where-to-look.js') } catch (err) { console.log('  ⚠ where-to-look: ' + err.message) }

if (process.argv.includes('--watch')) {
  console.log('⌚ watching agents/ — edit a folder file, the bundle resyncs on its own. ctrl-c to stop.')
  let timer = null
  fs.watch(AGENTS, { recursive: true }, (_evt, file) => {
    if (!file || !file.endsWith('.json')) return          // only agent json matters
    clearTimeout(timer)
    timer = setTimeout(() => {
      try { build(); console.log('  ↻ ' + new Date().toLocaleTimeString() + '  resynced (' + file + ')') }
      catch (err) { console.log('  ⚠ ' + err.message) }
    }, 120)
  })
}
