#!/usr/bin/env node
// where-to-look.js — GENERATES shell/where-to-look.gen.js → window.OZ_WHERE (a markdown string).
// black-box.js writes that string to port/where-to-look.md on every boot, so it lands next to the
// flight recorders it names.
//
// ⭐ WHY THIS EXISTS (Sum 2026-09-01, after a day where every answer was already written down and I
//    reasoned instead of reading): "the downside of six-figure hand rolls, need really really good notes."
//    The notes were not the problem — the SUMMARY LAYER was. His comments at the site of a problem have
//    held true since July. What went stale was the countable half: "3 goalies" (five), "198 tools" (174),
//    a ```que fence the grep could not see, a flight recorder nothing on earth named.
//
//    THE SPLIT THIS FILE ENFORCES:
//      WHY  — prose, hand-written, attached at the site, corrections never deleted. Decays slowly.
//      WHAT — counts, names, paths, call sites. Decays EVERY COMMIT. Never hand-write one again.
//    Same lever as TOOL_DEBT in the boot report, and it is his: put the number where the app already
//    looks. A checklist nobody is stopped by scored 6 of 159.
//
// run: node agents/where-to-look.js   (agents/build.js runs it too, so a normal build refreshes it)
const fs = require('fs'), path = require('path')
const OZ = path.join(__dirname, '..')
const SHELL = path.join(OZ, 'shell')

// every .js under shell/ and cards/ — the places a call site can live
function tree(dir, out) {
  out = out || []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) { if (!/^(_|node_modules)/.test(e.name)) tree(p, out) }
    else if (e.name.endsWith('.js') && !e.name.endsWith('.gen.js')) out.push(p)
  }
  return out
}
const FILES = tree(SHELL).concat(fs.existsSync(path.join(OZ, 'cards')) ? tree(path.join(OZ, 'cards')) : [])
const rel = f => path.relative(OZ, f)
const read = f => fs.readFileSync(f, 'utf8')

// ⚠ STRIP COMMENTS BEFORE YOU COUNT. In a repo where corrections attach and nothing is deleted, the
//    tree is dense with commented-out code and prose quoting real names — by design. Every naive grep
//    here over-reports, always in the same direction. (CLAUDE.md, 31 Aug: "6.10 MB" was 3.43.)
function code(src) {
  return src.replace(/\/\*[\s\S]*?\*\//g, '').split('\n')
    .map(l => l.replace(/^\s*\/\/.*$/, '')).join('\n')
}

// ── the goalies: what OZ_LANE exports, and WHERE each is actually called from ──
const LANE = read(path.join(SHELL, 'lane-gofai.js'))
const apiBlock = (LANE.match(/var API = \{([\s\S]*?)\n  \}/) || [])[1] || ''
const EXPORTS = [...apiBlock.matchAll(/^\s{4}(\w+):/gm)].map(m => m[1]).filter(n => !n.startsWith('_') && n !== 'MAP')
// a goalie JUDGES or REPAIRS. the rest are helpers it leans on — named so nobody re-derives the list.
const GOALIE = { sniff: 'the HIL door — what did the human just hand over', kickJson: 'REPAIRS a call before it is judged (the tap-in)', lintJson: 'JUDGES a call on the JSON lane', lintCli: 'JUDGES a command on the CLI lane', lintReads: 'JUDGES the finished prose — proof of read', offTrack: 'THE HAND BACK — stuck? take the other lane' }
const goalies = EXPORTS.filter(n => GOALIE[n]).map(name => {
  const sites = []
  for (const f of FILES) {
    if (path.basename(f) === 'lane-gofai.js') continue
    const src = code(read(f))
    const re = new RegExp('OZ_LANE(?:\\s*&&\\s*window\\.OZ_LANE)?\\s*\\.\\s*' + name + '\\b|OZ_LANE\\.' + name + '\\b', 'g')
    let n = 0; while (re.exec(src)) n++
    if (n) sites.push(rel(f) + '×' + n)
  }
  return { name, does: GOALIE[name], sites }
})

// ── the fence tags: every tag that routes through parseFence ──
const COND = read(path.join(SHELL, 'conductor.js'))
const tags = [...new Set([...code(COND).matchAll(/parseFence\([^,]+,\s*'([a-z]+)'/g)].map(m => m[1]))].sort()

// ── the flight recorders: anything written into the port/ folder ──
const recorders = []
for (const f of FILES) {
  for (const m of code(read(f)).matchAll(/name:\s*'(port\/[\w.-]+)'/g)) {
    if (!recorders.some(r => r.file === m[1])) recorders.push({ file: m[1], from: rel(f) })
  }
}

const bar = a => a.length ? a.join(' · ') : '⚠ NOWHERE — defined and never called'
const md = `# where to look — 0z flight recorders and goalies

GENERATED by \`agents/where-to-look.js\`. **Do not hand-edit.** Re-run a build to refresh.
Written to \`port/where-to-look.md\` on every boot, next to the recorders it names.

## exec sum

The app writes down what it did. Read the recorder before reasoning about the bug.
Five of five wrong turns on 1 Sep 2026 were answers already sitting in one of these files.

| you want to know | open |
|---|---|
| why a tool did not fire | \`port/last-que.txt\` — the plan the bot wrote, AND the tool menu it was handed |
| **where a tool's CONTENT came from** | **\`port/last-call.txt\` — the data + tutorial the clone read, its raw reply, and the parsed call BEFORE the goalie touched it** |
| what the chat phase actually said | \`port/last-reply.txt\` |
| what is registered / what is missing / the tool debt | \`port/boot-report.json\` |
| which goalie guards what, and whether it is wired | the table below |

⚠ **The port \`say\` road returns the CHAT reply only.** The que · read · run · check phases print to the
**bar**, not to that channel. Diagnosing tools from the port reply is reading a pipe that cannot see them.
Turn on ESP for the bot (\`toto_esp_<id>\` = \`'1'\`) to stream the real plan instead of the calm 🪵.

## the goalies — ${goalies.length} of them

| goalie | what it guards | wired at |
|---|---|---|
${goalies.map(g => `| \`${g.name}\` | ${g.does} | ${bar(g.sites)} |`).join('\n')}

⚠ **A goalie wired in ONE place, in a system with three lanes (chat · que · run), is suspicious by
arithmetic.** That is exactly how \`kickJson\` sat from 25 Aug to 1 Sep: built to repair a near-miss name,
pointed only at the JSON lane, while the QUE lane — the one every carded bot walks on every tool turn —
hand-rolled a weaker exact-match lookup fifteen lines away. Count the sites before you read the code.

## the fence tags — ${tags.length}

${tags.map(t => '`' + t + '`').join(' · ')}

\`parseFence()\` in \`shell/conductor.js\` is the ONLY fence parser; every tag above routes through it, so a
change there moves all ${tags.length} at once. It **collects every block of a tag and joins them** —
Sum 2026-09-01: *"if unsure append don't overwrite, de-duping is easier than retrieving."* A doubled note is
a nuisance you can see and delete; a dropped step is gone and looks like success.

## the code MMMM points at

| file | lines | what is in it |
|---|---|---|
| \`shell/tools.js\` | ${read(path.join(SHELL, 'tools.js')).split('\n').length} | \`makeTool\` — the factory. id · card · blurb · clue · klass · readback · strike. The refusal is LIVE: no klass or no readback → the bean returns null and the tool does not exist. |
| \`shell/lane-gofai.js\` | ${LANE.split('\n').length} | the goalies above, plus \`nearTool\` (the shared near-miss matcher) and the CLI/JSON lane picks. |
| \`shell/conductor.js\` | ${COND.split('\n').length} | the five phases: ① chat names cards → ② read → ③ que names \`<card> <tool> <what>\` → ④ run (JS builds known shapes; a FRESH clone formats anything needing judgment) → ⑤ check. |

⭐ **The chat bot never formats a call.** It names a card. The que names a tool. Only the slim clone —
no persona, no history, one tutorial — writes a call, which is why a dull model can drive this at all.
If a bot "fails", ask what tool it was missing before you ask what it got wrong.
`

fs.writeFileSync(path.join(SHELL, 'where-to-look.gen.js'),
  '// where-to-look.gen.js — GENERATED by agents/where-to-look.js. DO NOT EDIT BY HAND.\n' +
  'window.OZ_WHERE = ' + JSON.stringify(md) + '\n')
const orphans = goalies.filter(g => !g.sites.length).map(g => g.name)
console.log('✓ where-to-look: ' + goalies.length + ' goalies · ' + tags.length + ' tags · ' + recorders.length + ' recorders → shell/where-to-look.gen.js')
if (orphans.length) console.log('  ⚠ goalie defined and never called: ' + orphans.join(', '))
goalies.filter(g => g.sites.length === 1).forEach(g => console.log('  · ' + g.name + ' is wired in ONE file — ' + g.sites[0]))
