// cli-card.js — 🖥️ the clioz TERMINAL card. A sandboxed shell the USER drives DIRECTLY (standalone + in the
// coder suite), no bot required. Same double-guarded path as the bot loop: classify → gate → run_cli → output.
// Everything runs in ~/totoII/sandbox, OS-caged; reads run, writes ask first, sharp/denied are walled. In a
// browser (no rust bridge) OZ_CLI stays dry-run. Classic JS · window.* · CARD_BUILDERS.cli (opened via toggleCard).
//
// TABS (Sum 2026-07-11): each tab is its OWN shell buffer + history + lastCmd. the tab BAR rides in the HEAD
// (like monaco's) so it survives collapse — click a tab on a collapsed bar → expand + switch. ＋ = new tab.
// × on a tab = KILL + CLOSE (no ghost servers: when the CLI runs a real long process, kill it here on close).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the tabs ..................................... search: "the tabs"
//   output (routes to the ACTIVE tab's buffer) ... search: "output (routes to the"
//   the SUGGESTOR (Sum TNG-16, the "syntax ....... search: "the SUGGESTOR (Sum"
//   ⌘ commands ▾ — the NO-TYPE menu: click a ..... search: "⌘ commands ▾ — the"
//   the TYPO-FREE ⌘K palette (Sum 2026-07-11) .... search: "the TYPO-FREE ⌘K"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for `window.CARD_BUILDERS.cli`, a sandboxed
//    **terminal card that runs in the browser. It exports one function: `buildCli()`, which returns
//    **a card DOM element with tabs, command history, a suggestor, and a command palette. The card
//    **reads `window.OZ_CLI` (the harness), `window.OZ_CASCADE` (the predictor),
//    **`window.OZ_APP_CLI` (app commands), `window.OZ_PALETTE` (fuzzy picker), and `window.SANDBOX`
//    **(file list). It writes to `localStorage` under the key `toto_cli_fontsize` (line 246).
//
//    **TOUCH HERE** —
//    - Add a new tab button or change its label → `newTab()` L59
//    - Change the shell built-ins list (ls, pwd, cat, etc.) → `cliPalette()` L218
//    - Alter the initial hint text shown on first tab → `newTab()` L64
//    - Change text size persistence key → `SZKEY` L246, then `applySize()` L247
//    - Add a new top-bar button (gear, plus, monkey, cmds, sugBtn) → lines 27–32, then wire its
//    - click handler (see gear at L253, plus at L263, monkey at L264)
//    - Modify the suggestor's max chip count → `renderSug()` L164 (currently 9)
//    - Change the command history navigation (↑/↓) → `input.addEventListener('keydown', …)` L138
//    - Alter the gear menu UI or add size options → `gearMenu` node L242, then `applySize()` L247
//
//    **TRAPS** —
//    - `active` (L16) and `tabs` (L16) are the state that persists across tab switches. Renaming
//    - either breaks all tab logic silently.
//    - `seq` (L16) is the tab ID counter; it only increments (L60), never resets. Changing this
//    - breaks tab identity.
//    - `SZKEY` (L246) is the localStorage key. Changing it orphans saved font sizes for all users.
//    - `activeTab()` (L50) is called in 10+ places (L100, L105, L112, L139, L215, etc.). Renaming
//    - it requires a global find-replace.
//    - The `go` button (L35) is inserted into the card head *outside* `.card-ctrls` (L41). Moving
//    - this insertion or the button definition breaks the restart UI.
//    - `renderSug()` (L161) is called on input (L191), keydown (L140, L142), and sugBtn toggle
//    - (L197). Removing any call silences the suggestor.
//    - `window.OZ_CLI.classify()` (L119) must be called *before* `window.OZ_CLI.run()` (L124).
//    - Swapping them breaks the gate logic.
//    - The tab bar (L33) rides in the card head and survives collapse (L91–95). If moved into the
//    - body, the expand-on-click behavior breaks.
//    - `input.value` is read by `cliSuggest()` (L153) and `renderSug()` (L164). If input is
//    - replaced with a different element, both break.
//
//    **DO NOT** —
//    - Do not rename `window.CARD_BUILDERS` or `window.CARD_BUILDERS.cli`; the card opener depends
//    - on this exact path.
//    - Do not move the tab bar out of the topbar array (L38); it must be in the head to survive
//    - collapse.
//    - Do not change the class names (`.cli-wrap`, `.cli-in`, `.cli-buffers`, `.cli-scroll`,
//    - `.cli-tab`, etc.) without updating the CSS file that styles them.
//    - Do not add new global state (like `var x = …` at L16) without documenting it; the closure is
//    - already complex.
//    - Do not add new event listeners to `document` (like L239, L259) without a corresponding
//    - cleanup; they will leak across card rebuilds.
//    - Do not change the `run()` function's signature (L110) or the shape of the record it expects
//    - from `window.OZ_CLI.run()` (L124–134); the harness depends on this contract.
//    - Do not add new localStorage keys without a migration plan; users' old data will be orphaned.
//    - Do not move the suggestor DOM (L150–151) or change its parent; it must be inserted before
//    - `.cli-line` to render above the input.
//    - Do not change the tab close logic (L75–83) without understanding that it must kill
//    - long-running processes (comment at L76).
//    - Do not add features that require a bot or server; this is a standalone, sandboxed shell —
//    - keep it dry-run in the browser.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'
  window.CARD_BUILDERS = window.CARD_BUILDERS || {}
  function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
  function node(h) { var d = document.createElement('div'); d.innerHTML = h.trim(); return d.firstElementChild }

  window.CARD_BUILDERS.cli = function buildCli() {
    var tabs = [], active = null, seq = 0

    var body =
      '<div class="cli-wrap">' +
        '<div class="cli-buffers"></div>' +               // holds one .cli-scroll per tab; only the active shows
        '<div class="cli-line"><span class="cli-ps">$</span>' +
        '<input class="cli-in" type="text" autocomplete="off" autocapitalize="off" spellcheck="false" ' +
        'placeholder="type a command — runs sandboxed in ~/totoII/sandbox"></div>' +
      '</div>'

    var GEAR_SVG = window.OZ_GEAR_SVG || '<svg viewBox="0 0 24 24" width="17" height="17" fill="currentColor" aria-hidden="true"><path d="M12 15.5A3.5 3.5 0 1 1 12 8.5a3.5 3.5 0 0 1 0 7zm7.43-2.53c.04-.32.07-.65.07-.97s-.03-.65-.07-.97l2.11-1.65a.5.5 0 0 0 .12-.64l-2-3.46a.5.5 0 0 0-.61-.22l-2.49 1a7.3 7.3 0 0 0-1.69-.98l-.38-2.65A.49.49 0 0 0 14 2h-4a.49.49 0 0 0-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1a.5.5 0 0 0-.61.22l-2 3.46a.5.5 0 0 0 .12.64L4.57 11c-.04.32-.07.65-.07.97s.03.65.07.97l-2.11 1.65a.5.5 0 0 0-.12.64l2 3.46c.14.24.44.32.68.22l2.49-1c.52.39 1.08.73 1.69.98l.38 2.65c.05.24.26.42.49.42h4c.24 0 .44-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.24.1.54.02.68-.22l2-3.46a.5.5 0 0 0-.12-.64l-2.11-1.65z"/></svg>'
    var gear   = node('<button class="cli-gear" data-cli="gear" title="cli settings — text size · your own buttons · sandbox commands · web search">' + GEAR_SVG + '</button>')
    var plus   = node('<button class="cli-plus" data-cli="plus" title="new tab — a fresh shell">＋</button>')   // (Sum 2026-07-11) ＋ = new tab
    var monkey = node('<button class="cli-monkey" data-cli="monkey" title="permission — you\'re in the sandbox, safe. click to climb out."><img src="shell/monkeys/cage.png" alt="in the sandbox"></button>')
    var cmds   = node('<button class="cli-btn cli-cmds" data-cli="cmds" title="commands — pick one, we type the name for you">⌘&nbsp;<span>commands</span>&nbsp;▾</button>')
    // ∿ SUGGESTOR toggle (Sum TNG-16) — turns on the live next-token strip that reads the line as you type
    var sugBtn = node('<button class="cli-btn cli-sug-toggle" data-cli="sug" title="suggestor — live next-token suggestions as you type · TAB into the strip · ← → to move · ↵ to pick">∿</button>')
    var tabsBar = node('<div class="cli-tabs"></div>')   // in the HEAD → survives collapse (like monaco's tabs)
    // ▶ GREEN GO — launch / restart the active tab's LAST command; glows when there's one. rides OUTSIDE .card-ctrls.
    var go = node('<button class="cli-go" data-cli="go" title="run / restart the last command"></button>')

    var card = window.makeCard({ id: 'cli', icon: 'cards/cli/cli.png', title: 'cli', skin: 'p-cli',
      topbar: [plus, monkey, cmds, sugBtn, tabsBar], gear: gear, jewels: true,   // (2026-08-28) gear out of ctrls — far-right seat
      stop: function () { var t = activeTab(); if (t && t.lastCmd) go.classList.add('on') },   // red stopped it → green lights (restart possible)
      body: body, bottom: true })
    ;(function () { var hd = card.querySelector('.card-head'), jw = hd && hd.querySelector('.card-jewels'); if (hd) hd.insertBefore(go, jw || null) })()
    go.addEventListener('mousedown', function (e) { e.stopPropagation() })
    go.addEventListener('click', function (e) { e.stopPropagation(); var t = activeTab(); if (t && t.lastCmd) run(t.lastCmd) })

    var buffers = card.querySelector('.cli-buffers')
    var input   = card.querySelector('.cli-in')
    var wrap    = card.querySelector('.cli-wrap')

    // ── the tabs ──────────────────────────────────────────────────────────
    function activeTab() { for (var i = 0; i < tabs.length; i++) if (tabs[i].id === active) return tabs[i]; return null }
    function renderTabs() {
      tabsBar.innerHTML = tabs.map(function (t) {
        return '<span class="cli-tab' + (t.id === active ? ' active' : '') + '" data-tab="' + t.id + '">' +
          '<span class="cli-tab-name">' + esc(t.name) + '</span>' +
          '<button class="cli-tab-x" data-close="' + t.id + '" title="kill + close this tab">×</button>' +
        '</span>'
      }).join('')
    }
    function newTab() {
      var id = 'c' + (++seq)
      var el = node('<div class="cli-scroll"></div>'); buffers.appendChild(el)
      var t = { id: id, name: 'sh ' + seq, el: el, hist: [], hi: 0, lastCmd: '' }
      tabs.push(t); switchTab(id)
      put('cli-hint', 'clioz — a sandboxed shell (~/totoII/sandbox). reads run · writes ask first · sharp stuff is walled. ↑/↓ for history.')
      return t
    }
    function switchTab(id) {
      active = id
      for (var i = 0; i < tabs.length; i++) tabs[i].el.style.display = tabs[i].id === id ? '' : 'none'
      renderTabs()
      var t = activeTab(); if (t) t.el.scrollTop = t.el.scrollHeight
      go.classList.toggle('on', !!(t && t.lastCmd))   // green reflects THIS tab's relaunchable command
      try { input.focus() } catch (_) {}
    }
    function closeTab(id) {
      // KILL + CLOSE — no ghost servers: when a tab owns a real long-running process, kill it HERE before removing.
      var i = -1; for (var k = 0; k < tabs.length; k++) if (tabs[k].id === id) { i = k; break }
      if (i < 0) return
      tabs[i].el.remove(); tabs.splice(i, 1)
      if (tabs.length === 0) { newTab(); return }        // never leave zero tabs
      if (active === id) switchTab(tabs[Math.max(0, i - 1)].id)
      else renderTabs()
    }
    // (Sum 2026-07-11) only a REAL tab blocks the head drag/collapse — the EMPTY tab-bar space is a handle:
    //   mousedown/click on it bubbles to the card head → collapse/expand + drag, like any open top-bar space.
    tabsBar.addEventListener('mousedown', function (e) { if (e.target.closest('.cli-tab')) e.stopPropagation() })
    tabsBar.addEventListener('click', function (e) {
      var x = e.target.closest('[data-close]'); if (x) { e.stopPropagation(); closeTab(x.dataset.close); return }
      var t = e.target.closest('[data-tab]'); if (!t) return   // empty space → let it bubble → collapse/expand the card
      e.stopPropagation()
      if (card.classList.contains('collapsed')) {   // collapsed → expand to the tab you clicked (like monaco)
        (window.expandCard || function (c) { c.classList.remove('collapsed') })(card)
        if (window.syncSolo) window.syncSolo()
      }
      switchTab(t.dataset.tab)
    })

    // ── output (routes to the ACTIVE tab's buffer) ─────────────────────────
    function put(cls, text) {
      var t = activeTab(); if (!t) return null
      var d = document.createElement('div'); d.className = 'cli-out' + (cls ? ' ' + cls : ''); d.textContent = text
      t.el.appendChild(d); t.el.scrollTop = t.el.scrollHeight; return d
    }
    function echo(cmd) {
      var t = activeTab(); if (!t) return
      var d = document.createElement('div'); d.className = 'cli-echo'; d.innerHTML = '<span class="cli-ps">$</span> ' + esc(cmd)
      t.el.appendChild(d); t.el.scrollTop = t.el.scrollHeight
    }

    function run(cmd) {
      cmd = (cmd || '').trim(); if (!cmd) return
      var t = activeTab(); if (t) t.lastCmd = cmd
      go.classList.add('on')   // there's now a last command → green can relaunch it
      echo(cmd)
      // the app-CLI lane — `ozprep …` runs IN the page (app state), not the sandboxed shell. no rust, no gate.
      if (window.OZ_APP_CLI && window.OZ_APP_CLI.has(cmd)) { put('cli-app', window.OZ_APP_CLI.run(cmd)); return }
      if (!window.OZ_CLI) { put('cli-warn', '(clioz harness not loaded)'); return }
      var klass
      try { klass = window.OZ_CLI.classify(cmd) } catch (_) { klass = 'sharp' }
      if (klass === 'denied') { put('cli-deny', '⛔ blocked — denylist / sandbox escape'); return }
      var opts = { klass: klass }
      if (klass === 'read') { opts.confirmed = true; opts.confirmedCmd = cmd }   // reads run; write/sharp → the harness "super sure?"
      var busy = put('cli-busy', '…')
      Promise.resolve(window.OZ_CLI.run(cmd, opts)).then(function (rec) {
        if (busy) busy.remove()
        if (rec && rec.blocked) { put('cli-deny', '⛔ ' + (rec.reason || 'blocked')); return }
        if (rec && rec.refusedByHuman) { put('cli-warn', '↩ cancelled'); return }
        var out = rec && rec.stdout != null ? rec.stdout : ''
        var err = rec && rec.stderr
        if (out) put('', out)
        if (err) put('cli-err', err)
        if (rec && !out && !err && rec.exit != null && rec.exit !== 0) put('cli-err', 'exit ' + rec.exit)
        if (rec && rec.dryRun) put('cli-dry', '(dry-run — no rust executor here)')
      }, function (e) { if (busy) busy.remove(); put('cli-err', 'run failed: ' + ((e && e.message) || e)) })
    }

    // command history — PER TAB, ↑/↓ like a real shell
    input.addEventListener('keydown', function (e) {
      var t = activeTab(); if (!t) return
      if (e.key === 'Enter') { e.preventDefault(); var v = input.value; if (v.trim()) { t.hist.push(v); t.hi = t.hist.length } input.value = ''; run(v); renderSug() }
      else if (e.key === 'ArrowUp') { if (t.hist.length) { t.hi = Math.max(0, t.hi - 1); input.value = t.hist[t.hi] || ''; e.preventDefault(); renderSug() } }
      else if (e.key === 'ArrowDown') { if (t.hist.length) { t.hi = Math.min(t.hist.length, t.hi + 1); input.value = t.hist[t.hi] || ''; e.preventDefault(); renderSug() } }
    })

    // ── the SUGGESTOR (Sum TNG-16, the "syntax pad") — a sub-drawer that READS the line and shows the most-likely
    //    NEXT tokens up top as you type. it has no input of its own. TAB hops from the line into the strip · ← →
    //    to move · ↵ picks (drops the token into the line) · esc back. shares OZ_CASCADE's brain — one predictor,
    //    two faces (this ports to Monaco next). tie-in: Squiggy becomes this dial on the editor side. ──
    var sugOn = false, sugSel = -1
    var sug = node('<div class="cli-sug"><span class="cli-sug-tag">next ▸</span><div class="cli-sug-row"></div></div>')
    wrap.insertBefore(sug, card.querySelector('.cli-line'))
    var sugRow = sug.querySelector('.cli-sug-row')
    function cliSuggest(text) {
      var endsSpace = /\s$/.test(text), toks = text.trim().split(/\s+/).filter(Boolean), built, partial
      if (endsSpace || !toks.length) { built = text.trim(); partial = '' }
      else { partial = toks[toks.length - 1]; built = toks.slice(0, -1).join(' ') }
      var opts = (window.OZ_CASCADE && window.OZ_CASCADE.suggest) ? window.OZ_CASCADE.suggest('cli', built) : []
      if (partial) opts = opts.filter(function (o) { return o.toLowerCase().indexOf(partial.toLowerCase()) === 0 })
      return { built: built, partial: partial, opts: opts }
    }
    function renderSug() {
      if (!sugOn) { sug.style.display = 'none'; return }
      sug.style.display = 'flex'
      var text = input.value, res = cliSuggest(text), opts = res.opts.slice(0, 9)
      var macs = (text.trim() === '' && window.OZ_CASCADE && window.OZ_CASCADE.macros) ? window.OZ_CASCADE.macros('cli') : []
      sugSel = -1
      var html = opts.map(function (o) { return '<button class="cli-sug-chip" tabindex="-1" data-sug="' + esc(o) + '">' + esc(o) + '</button>' }).join('')
      html += macs.map(function (m) { return '<button class="cli-sug-chip cli-sug-mac" tabindex="-1" data-mac="' + esc(m[1]) + '">' + esc(m[0]) + '</button>' }).join('')
      sugRow.innerHTML = html || '<span class="cli-sug-none">— keep typing · shell built-ins live under ⌘ —</span>'
    }
    function sugChips() { return sugRow.querySelectorAll('.cli-sug-chip') }
    function focusChip(chips) { for (var i = 0; i < chips.length; i++) chips[i].classList.toggle('on', i === sugSel); if (chips[sugSel]) chips[sugSel].focus() }
    function applySug(tok) {
      var text = input.value, res = cliSuggest(text)
      var base = res.partial ? res.built : text.replace(/\s+$/, '')
      input.value = (base ? base + ' ' : '') + tok + ' '
      sugSel = -1; input.focus(); renderSug()
    }
    sugRow.addEventListener('mousedown', function (e) { e.stopPropagation() })
    sugRow.addEventListener('click', function (e) {
      var s = e.target.closest('[data-sug]'); if (s) { e.stopPropagation(); applySug(s.dataset.sug); return }
      var m = e.target.closest('[data-mac]'); if (m) { e.stopPropagation(); input.value = m.dataset.mac + ' '; input.focus(); renderSug() }
    })
    sugRow.addEventListener('keydown', function (e) {
      var chips = sugChips(); if (!chips.length) return
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') { sugSel = Math.min(chips.length - 1, sugSel + 1); focusChip(chips); e.preventDefault() }
      else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { sugSel = Math.max(0, sugSel - 1); focusChip(chips); e.preventDefault() }
      else if (e.key === 'Enter') { if (chips[sugSel]) chips[sugSel].click(); e.preventDefault() }
      else if (e.key === 'Escape' || e.key === 'Tab') { input.focus(); e.preventDefault() }
    })
    input.addEventListener('input', renderSug)
    input.addEventListener('keydown', function (e) {   // TAB hops from the line INTO the strip (Sum's tab→arrow→enter)
      if (e.key === 'Tab' && sugOn) { var chips = sugChips(); if (chips.length) { e.preventDefault(); sugSel = 0; focusChip(chips) } }
    })
    sugBtn.addEventListener('mousedown', function (e) { e.stopPropagation() })
    sugBtn.addEventListener('click', function (e) {
      e.stopPropagation(); sugOn = !sugOn; sugBtn.classList.toggle('on', sugOn); renderSug()
      if (sugOn) { input.focus(); put('cli-hint', 'suggestor ON — type, then TAB into the strip · ← → to move · ↵ to pick. it reads the line and predicts the next token.') }
    })
    renderSug()   // hidden until toggled on

    // ── ⌘ commands ▾ — the NO-TYPE menu: click a command → we drop its NAME into the box + print its help. ──
    var menu = node('<div class="cli-cmd-menu"></div>'); document.body.appendChild(menu)
    function closeMenu() { menu.classList.remove('open') }
    function fillMenu() {
      var names = (window.OZ_APP_CLI && window.OZ_APP_CLI.names && window.OZ_APP_CLI.names()) || []
      menu.innerHTML = names.length
        ? names.map(function (n) { return '<button class="cli-cmd-item" data-cmd="' + n + '">' + n + '</button>' }).join('')
        : '<div class="cli-cmd-empty">no app commands loaded</div>'
    }
    // ── the TYPO-FREE ⌘K palette (Sum 2026-07-11) — ONE fuzzy surface: commands + your recent history +
    //    insert-a-file. forgiving match (a typo still lands it), arrow/click, never have to type a name. ──
    function cliPalette() {
      if (!window.OZ_PALETTE) { fillMenu(); var r = cmds.getBoundingClientRect(); menu.style.left = r.left + 'px'; menu.style.top = (r.bottom + 5) + 'px'; menu.classList.add('open'); return }
      var itms = [], t = activeTab()
      // (Sum 2026-07-11) the SHELL built-ins — "you have all these custom commands but no ls?" now you do.
      //   [cmd, runsNow] — no-arg commands (ls · pwd) FIRE on pick (true no-typo); arg commands drop into the line.
      var SHELL = [['ls', 1], ['ls -la', 1], ['pwd', 1], ['cat ', 0], ['head ', 0], ['tail ', 0], ['grep ', 0], ['find . -name ', 0], ['mkdir ', 0], ['touch ', 0], ['cp ', 0], ['mv ', 0], ['rm ', 0], ['echo ', 0], ['wc -l ', 0], ['diff ', 0], ['which ', 0], ['file ', 0]]
      SHELL.forEach(function (s) { itms.push({ group: 'shell', label: s[0].trim(), hint: s[1] ? 'sandboxed shell — runs' : 'sandboxed shell — add a target', run: s[1] ? function () { run(s[0].trim()) } : function () { input.value = s[0]; input.focus() } }) })
      var names = (window.OZ_APP_CLI && window.OZ_APP_CLI.names && window.OZ_APP_CLI.names()) || []
      names.forEach(function (n) { itms.push({ group: 'commands', label: n, hint: 'app command', run: function () { input.value = n + ' '; input.focus(); run(n + ' help') } }) })
      if (t) t.hist.slice().reverse().forEach(function (h) { itms.push({ group: 'recent', label: '↑  ' + h, run: function () { input.value = h; run(h) } }) })
      var sb = window.SANDBOX || {}
      Object.keys(sb).forEach(function (n) { var f = sb[n]; if (f && typeof f.data === 'string' && f.kind !== 'url') itms.push({ group: 'insert a file', label: n, hint: '→ append to the line', run: function () { input.value = (input.value + ' ' + n).replace(/\s+/g, ' ').trim() + ' '; input.focus() } }) })
      window.OZ_PALETTE.open(itms)
    }
    cmds.addEventListener('click', function (e) {
      e.stopPropagation()
      if (window.OZ_CASCADE) window.OZ_CASCADE.cli(function (s) { input.value = s + ' '; input.focus() })   // ⚡ the Hawking predictor → builds the command into the line (Enter to run)
      else cliPalette()
    })
    menu.addEventListener('click', function (e) {
      var b = e.target.closest('[data-cmd]'); if (!b) return
      e.stopPropagation(); closeMenu()
      var c = b.dataset.cmd
      input.value = c + ' '; input.focus()
      run(c + ' help')
    })
    document.addEventListener('click', closeMenu)

    // ⚙ gear — settings. text size (persisted, via --cli-fs so it hits every tab + future tabs). rest stubbed.
    var gearMenu = node('<div class="cli-cmd-menu cli-gear-menu">' +
        '<div class="cli-gear-soon">the gear is where you TAILOR the ⚡ predictor · soon: learn from your history · your own macros · the danger list</div>' +
      '</div>')
    document.body.appendChild(gearMenu)
    var SZKEY = 'toto_cli_fontsize'
    function applySize(px) {
      if (wrap) wrap.style.setProperty('--cli-fs', px + 'px'); input.style.fontSize = px + 'px'
      try { localStorage.setItem(SZKEY, px) } catch (_) {}
      gearMenu.querySelectorAll('[data-sz]').forEach(function (b) { b.classList.toggle('on', +b.dataset.sz === +px) })
    }
    try { var _sz = localStorage.getItem(SZKEY); if (_sz) applySize(+_sz) } catch (_) {}
    gear.addEventListener('click', function (e) {
      e.stopPropagation(); closeMenu()
      if (gearMenu.classList.contains('open')) { gearMenu.classList.remove('open'); return }
      var r = gear.getBoundingClientRect(); gearMenu.style.left = r.left + 'px'; gearMenu.style.top = (r.bottom + 5) + 'px'; gearMenu.classList.add('open')
    })
    gearMenu.addEventListener('click', function (e) { var b = e.target.closest('[data-sz]'); if (b) { e.stopPropagation(); applySize(+b.dataset.sz) } })
    document.addEventListener('click', function () { gearMenu.classList.remove('open') })

    // ＋ plus → new tab · 🐒 monkey — honest stub for now
    plus.addEventListener('mousedown',   function (e) { e.stopPropagation() })
    plus.addEventListener('click',   function (e) { e.stopPropagation(); newTab() })
    monkey.addEventListener('click', function (e) { e.stopPropagation(); put('cli-hint', "🐒 you're in the sandbox — safe. the climb-out (ladder → over-the-lava) is coming.") })

    newTab()   // seed the first shell tab
    if (window.OZ_APP_CLI && window.OZ_APP_CLI.names && window.OZ_APP_CLI.names().length) {
      put('cli-app', 'app commands: click ⌘ commands ▾ up top — no need to remember the name, just pick it.')
    }
    setTimeout(function () { try { input.focus() } catch (_) {} }, 60)
    return card
  }
})()
