// ── compileChart — THE STABLE HEAD (the warm-KV head). the ONE compiler: soul + identity + persona +
//    the human's chart + notes/profiles — everything that does NOT change turn to turn. NOTHING live goes
//    in here (time/weather live in liveLayer, the tail), so the head stays byte-identical and the model's
//    KV cache stays warm. its output is the per-agent virtual file (toto_chart_<id>) the woodshop LOADS. ──

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   compileChart — THE STABLE HEAD (the warm-KV ... search: "compileChart — THE"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The stable, unchanging head of every agent's compiled prompt. This file is the
//    **single source of truth for what lands in the warm KV cache: `compileChart(agentId, get,
//    **off)` at line 5 returns a string that becomes the per-agent virtual file `toto_chart_<id>`,
//    **which the woodshop loads. Nothing exported to window; the function is called by the
//    **woodshop, not by other files.
//
//    **TOUCH HERE** —
//    - Add a new agent-specific profile (like sleep/food/exercise for wellness) → add a new `if
//    - (agentId === 'agentName')` block after line 143, following the pattern of lines 145–186
//    - Change what notes an agent can read → edit `NOTE_GRANTS` object at line 96
//    - Add a toggleable section (tools, identity, persona, etc.) → add `if (on('sectionName'))`
//    - check and `parts.push()` call; see lines 15, 48–54 for the pattern
//    - Modify the purity filter for an agent → edit the `parts.push()` block at line 190 (writer)
//    - or line 196 (tutor)
//    - Change the attachment handling rule → edit the `parts.push()` call at line 206
//    - Inject a new stable section that all agents see → add `parts.push()` before line 210 (the
//    - soul unshift)
//
//    **TRAPS** —
//    - Line 96: `NOTE_GRANTS` keys must match real `agentId` values or notes silently vanish for
//    - that agent. Line 101 filters by these keys; if you add an agent, add its entry here or it
//    - reads no notes.
//    - Line 210: `buildSoul()` is called and unshifted at line 211. If `buildSoul()` returns falsy,
//    - nothing breaks, but the soul will be missing. Do not remove the unshift.
//    - Line 218: The baked clause is repeated 4× or 2× depending on whether the user edited
//    - persona/backstory. Line 217 checks `g('persona')` and `g('backstory')` against defaults; if
//    - you change the default keys, this check silently fails and the repetition count stays wrong.
//    - Lines 6–11: The getter functions `g`, `u`, `d` are used throughout. `g` reads agent-specific
//    - state (`toto_bot_<agentId>_<field>`), `u` reads global state (`toto_<field>`), `d` reads
//    - defaults. Renaming these will break every line that uses them.
//    - Line 102: The filter logic `o === 'hil' || o === agentId || grants.includes(o)` is the
//    - access control for notes. 'hil' is a magic owner name meaning "shared"; do not change it
//    - without updating the comment at line 91.
//    - Lines 109, 145: Agent-specific blocks check `agentId === 'tutor'` and `agentId ===
//    - 'wellness'` by string. If you rename an agent, update these checks or the profile data will
//    - inject into the wrong agent.
//
//    **DO NOT** —
//    - Do not rename `compileChart`, `g`, `u`, `d`, `on`, `parts`, or `soul` — they are
//    - load-bearing identifiers used throughout the function.
//    - Do not change the order of `parts.unshift()` calls (lines 211, 218) without understanding
//    - that unshift adds to the front, so the last unshift lands first in the final string.
//    - Do not move the soul (line 210–211) or the baked clause (line 216–219) to a different
//    - position; they are front-loaded intentionally so the model weights them highest.
//    - Do not add live data (time, weather, free RAM, sandbox state) to this function; that belongs
//    - in the tail (`liveLayer`), not the warm-head cache. See comment at lines 2–3 and 30.
//    - Do not edit `localStorage` keys or the shape of parsed objects (e.g., `toto_notes`,
//    - `toto_learn_profile`) in this file; those are persisted user data. Shape changes belong in a
//    - migration, not here.
//    - Do not add new window global checks without understanding the pattern: lines 19, 32 check
//    - `typeof window !== 'undefined'` before accessing `window.*` because this may run in Node.
//    - Follow that pattern.
//    - Do not change the web_search block (lines 67–90) without coordinating with the conductor
//    - that wires the tool; the phrasing is honest only if the tool is actually available.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

function compileChart(agentId, get, off) {
  get = get || engGet   // default: read saved state. the injection card passes a DOM getter for LIVE preview.
  off = off || (function () { try { return JSON.parse(get('toto_inj_off') || '[]') } catch (_) { return [] } })()
  const on = k => !off.includes(k)
  const g = f => get('toto_bot_' + agentId + '_' + f)
  const u = f => get('toto_' + f)
  const d = AGENT_DEFAULTS[agentId] || {}
  const parts = []
  // ── THE ROLE SHEET (Sum 2026-08-16: personas across coder/nurse/sphinx had sections that "rhyme if not
  //    identical" — 20 lines repeated VERBATIM, measured). Those are the JOB, not the VOICE, so they live
  //    once in agents/roles.json and compile in here by the bot's `role`. Edit one sheet, every bot of that
  //    role changes. HARD TO BRICK: not per-bot free text a user can wander into and delete a rule from.
  //    Rides FIRST, before the tool list — the rules of the job ahead of the list of hands.
  //    A bot can wear more than one sheet (string or array).
  // ⭐ ONE HARD SECTION (Sum 2026-08-17: "baked scope can be folded into role… just one section,
  //   role, after ethics above tools is perfect spot"). BAKED (this bot's own wall) and the ROLE
  //   SHEET (the job's shared rules) were two layers doing the same job in two places — baked
  //   unshifted to the very top, role buried further down. Now they arrive together, once, in the
  //   position the human picked: after the soul's ethics, before the list of hands.
  //   Order inside: the bot's OWN wall first, then the shared sheet — specific before general.
  if (on('role')) {
    try { const A = (window.AGENT_DATA && window.AGENT_DATA[agentId]) || {}
          if (d.baked) parts.push(d.baked)
          const want = d.role || A.role || []
          for (const r of (Array.isArray(want) ? want : [want])) {
            const sheet = (window.ROLE_SHEETS || {})[String(r)]
            if (sheet) parts.push(sheet)
          } } catch (_) {}
  }
  // YOUR TOOLS — front-loaded (lands between ethics and persona once the soul is unshifted up). toggleable
  // in the 💉 config (the 'tools' include-block); recompiles into the warm head like every other section.
  if (on('tools')) { const tb = toolsBlock(agentId); if (tb) parts.push(tb) }
  // the LANES ride WITH the tools (Sum 2026-07-18: "tools sooner in the send — and the two routes,
  // cli and json, the linters, gofai rails"): the CLI clues + the two-lane guide land HERE, right
  // after the tool list — not thousands of tokens later behind the charts. stable → warm-head safe.
  if (on('tools') && typeof window !== 'undefined') {
    const _czOn = window.OZ_CLIOZ && window.OZ_CLIOZ.config && window.OZ_CLIOZ.config.enabledBots &&
      window.OZ_CLIOZ.config.enabledBots.indexOf(agentId) > -1
    if (_czOn) {
      const _shellBot = window.OZ_CLIOZ.config.shellBots && window.OZ_CLIOZ.config.shellBots.indexOf(agentId) > -1
      if (_shellBot && window.OZ_CLIOZ.hasShell && window.OZ_CLIOZ.hasShell() && window.OZ_CLIOZ_SYSTEM) parts.push(window.OZ_CLIOZ_SYSTEM)
      // the app-CLI reference + the two-lane guide moved OUT of the head (Sum 2026-08-23: "put cli cues in cli card…
      // assume bot was pretrained on some form of cli"): they ride the PLANNING (que) round now (conductor.js cliRef),
      // the round that lays steps. One line stays so the lane is known.
      if (window.OZ_APP_CLI) parts.push('You also have an app CLI — data commands in a ```sh block. The full reference rides the planning round; you may chain commands, and a failed one hands back.')
    }
  }
  // YOUR MACHINE — the read state's TOTALS (stable → the warm head): mode (local vs cloud) · model · context
  // window · total RAM. the LIVE numbers (free RAM · sandbox used · how loaded) ride the tail, with the weather.
  // native only; the web demo is air-gapped → skipped, and the soul's substrate text stands. (Sum, 2026-06-28.)
  if (typeof window !== 'undefined' && window.OZ_SYS && window.OZ_SYS.native) {
    const m = machineState(agentId)
    if (m) {
      const s = window.OZ_SYS.stats(), gb = window.OZ_SYS.gb
      const L = ['─── YOUR MACHINE ───', 'You run as a native app on this Mac (not a web page).']
      L.push(m.local
        ? `Your brain: ${m.model} — a LOCAL model on this Mac. No network, no API spend; the tokens never leave the machine.`
        : `Your brain: ${m.model} — a cloud model reached with the user's OWN key (BYOK); the page calls ${m.provider} directly, no server of ours in between.`)
      if (s && s.ram_total) L.push(`This Mac has ${gb(s.ram_total).toFixed(0)} GB of memory total.`)
      L.push(`Your context window — your whole working memory for this conversation — is about ${ctxWindow(m.model)} total.`)
      L.push('The LIVE numbers (memory free · sandbox used · how loaded you are) sit at the very END of this prompt with the time — they change every turn.')
      parts.push(L.join('\n'))
    }
  }
  // the OZ MAP — generated from the live registry so a bot can always point the human to a card/bot/button.
  // travels with the env toggle (it's the always-current half of the ENVIRONMENT lesson).
  if (on('env')) { const map = ozMap(); if (map) parts.push(map) }
  if (on('identity')) {
    parts.push(`You are ${g('name') || agentId}.`)
    const pron = g('pronouns') || d.pronouns; if (pron) parts.push(`Your pronouns are ${pron}.`)
  }
  if (on('persona')) { const persona = g('persona') || d.persona; if (persona) parts.push(persona) }
  if (on('identity')) { const back = g('backstory') || d.backstory; if (back) parts.push('Backstory: ' + back) }
  // wetware — the HIL frame (the human node), right before the human's own bio
  if (on('wetware')) { const wet = get('toto_inj_wetware') || OZ_SOUL_DEFAULTS.wetware; if (wet) parts.push('─── WETWARE NODE ───\n' + wet) }
  const you = []
  if (on('bio')) {
    if (u('userName')) you.push('name: ' + u('userName'))
    if (u('userPronouns')) you.push('pronouns: ' + u('userPronouns'))
    if (u('userWho')) you.push(u('userWho'))
  }
  if (you.length) parts.push('\nAbout the human you are talking to:\n' + you.join('\n'))
  parts.push("\nYou run in a browser via the user's own API key (BYOK) — the page calls your model provider directly, with no server of ours in between (the provider runs the inference). You have no memory between sessions beyond this conversation. Say plainly what you cannot do.")
  // web_search capability line — grant-gated (stable across the cached chart), phrased so it's honest on a model
  // that can't search (the conductor only wires the tool when the provider supports it; otherwise the model just answers).
  {
    const t = (window.AGENT_DATA && window.AGENT_DATA[agentId] && window.AGENT_DATA[agentId].tools) || []
    if (t.includes('web_search')) parts.push(
`─── WEB SEARCH ───
You can search the live web for current or external facts. Decide for yourself when it's worth it: search for
what changed since you were trained, or what you'd otherwise guess — answer from what you know when you know it,
and say plainly when you're unsure rather than searching reflexively. If the current model can't search, say so.

DISCERNMENT — how to read what you find (this is the point, not an afterthought):
- Weigh the source. Primary > reporting > aggregation > anonymous. Name who is claiming a thing, not just the claim.
- Honest, never gory. Give the real number plainly — death tolls, hard history, the facts that matter — without
  dwelling on the grisly or the lurid. You can tell the truth about the Rwandan genocide or the Holocaust to anyone,
  at any age, without doom-scrolling them through it. Honesty and restraint are the same skill, not opposites.
- Skip the noise. No petty gossip, no celebrity worship, no rage-bait. Surface the substantive; drop the rest.
- Triangulate. One source is a lead, not a fact. Cite what you used so the human can check you.

THE SOURCES — a crayon box; pick the one that fits the task:
- Wikipedia — facts, history, definitions. Neutral, citeable, the encyclopedic spine.
- DuckDuckGo — privacy-first, no profiling or filtering; instant answers on well-known topics.
- Tavily — the general live web, synthesized; best for a broad current sweep.
On a model with native search you just search and the right sources surface; the explicit crayon-pick is for models
without it. Cite your sources either way.`)
  }
  // notes from the chart (toto_notes) — PER-OWNER: an agent gets only the SHARED notes (owner 'hil', or
  // none = shared) + its OWN (owner === agentId). the nurse's chart stays the nurse's — the medical notes
  // no longer leak to every agent. demo notes default to the nurse (that's whose chart they are).
  // GRANTS: one-way oversight. the nurse ALSO reads wellness's notes (clinical oversight of the food/sleep
  // side) — but NOT vice versa. the nurse is private: nobody reads her chart but her. asymmetric on purpose.
  // ⭐ MOVED TO THE BOT'S RECORD, 26 Aug ("noteGrants": ["wellness"] on nurse). WAS: { nurse: ['wellness'] }.
  //    Identical shape to oz-lane's MOUNTS, so it gets the identical fix: a one-way grant between two bots
  //    is a fact about the GRANTING bot, and neither bot's own file said anything about it while it lived
  //    here. The asymmetry is unchanged and still deliberate — the nurse reads wellness's notes for
  //    clinical oversight of the food/sleep side; nobody reads the nurse's chart but the nurse.
  const NOTE_GRANTS = (function () {
    try { const D = window.AGENT_DATA || {}, out = {}
      Object.keys(D).forEach(function (id) { const g = D[id] && D[id].noteGrants; if (Array.isArray(g) && g.length) out[id] = g })
      return out } catch (_) { return {} }
  })()
  try {
    const raw = localStorage.getItem('toto_notes')
    // the nurse's chart IS the clipboard now (one source) — fall back to the clipboard port, not the old DEMO_NOTES.
    const allNotes = raw ? JSON.parse(raw) : (window.nurseNotesFromClipboard ? window.nurseNotesFromClipboard() : [])
    const grants = NOTE_GRANTS[agentId] || []
    const active = allNotes.filter(n => { const o = n.owner || 'hil'; return n.on && (o === 'hil' || o === agentId || grants.includes(o)) })
    if (active.length) {
      parts.push('\n--- NOTES (loaded from the chart) ---')
      active.forEach(n => parts.push(`[${n.folder || 'root'}] ${n.display}:\n${n.body}`))
    }
  } catch (_) {}
  // ─── THE TOAST ─── the bot's opening lines, already printed on screen. They cannot ride the
  // messages array (history must OPEN on a user turn — Anthropic), so they ride HERE — the
  // injection has no role rules. Placed after the notes, nearest the live conversation.
  // (Sum, 2026-08-09: "add toast at end of injection config labeled toast, the user read this
  // as your first message." Written by workspace.js at bar build; static per bot → warm-head safe.)
  try {
    const _toast = JSON.parse(get('toto_toast_' + agentId) || '[]')
    if (_toast.length) parts.push('\n--- TOAST (your first words, already on screen) ---\nThe user read these as your first message; the conversation continues from them:\n' + _toast.map(t => '\u2022 ' + t).join('\n'))
  } catch (_) {}
  // learn profile + active skills/weaknesses — injected for the tutor agent only
  // ── CORRECTION 26 Aug: was `agentId === 'tutor'`. Copied from the clock cue ~145 lines up, which
  //    already asks hasCap(agentId, 'clock') for exactly this reason. Named for the DATA it unlocks,
  //    not the desk: `learn` is also a card, and both tutor and learner hold that card — but only one
  //    of them is shown the human's profile, and that difference is now stated on the bot.
  if (window.REG && window.REG.hasCap && window.REG.hasCap(agentId, 'learn')) {
    try {
      const how       = localStorage.getItem('toto_learn_how') || ''
      const style     = localStorage.getItem('toto_learn_style') || ''
      const styleOth  = localStorage.getItem('toto_learn_style_other') || ''
      const disorders = JSON.parse(localStorage.getItem('toto_learn_disorders') || '[]')
      const hard      = localStorage.getItem('toto_learn_hard') || ''
      const profileLines = []
      if (how)               profileLines.push('how they want to learn: ' + how)
      if (style)             profileLines.push('learning style: ' + style + (style === 'other' && styleOth ? ' — ' + styleOth : ''))
      if (disorders.length)  profileLines.push('learning disorders: ' + disorders.join(', '))
      if (hard)              profileLines.push('what makes it hard: ' + hard)
      if (profileLines.length) parts.push('\n--- LEARNING PROFILE ---\n' + profileLines.join('\n'))
      const rawSkills = localStorage.getItem('toto_learn_skills')
      const allSkills = rawSkills ? JSON.parse(rawSkills) : []
      const activeSkills = allSkills.filter(s => s.on && s.type === 'skill')
      const activeWeak   = allSkills.filter(s => s.on && s.type === 'weakness')
      if (activeSkills.length) {
        parts.push('\n--- SKILLS (use these to build on) ---')
        activeSkills.forEach(s => parts.push(`[${s.folder || 'general'}] ${s.display}${s.body ? ': ' + s.body : ''}`))
      }
      if (activeWeak.length) {
        parts.push('\n--- WEAKNESSES (target these in practice) ---')
        activeWeak.forEach(s => parts.push(`[${s.folder || 'general'}] ${s.display}${s.body ? ': ' + s.body : ''}`))
      }
      const teachHow   = localStorage.getItem('toto_tutor_teach_how') || ''
      const personaReq = localStorage.getItem('toto_tutor_persona_req') || ''
      if (teachHow || personaReq) {
        const tutPrefs = []
        if (teachHow)   tutPrefs.push('how they want me to teach: ' + teachHow)
        if (personaReq) tutPrefs.push('be this persona: ' + personaReq)
        parts.push('\n--- TUTOR PREFERENCES ---\n' + tutPrefs.join('\n'))
      }
    } catch (_) {}
  }
  // sleep profile — injected for the wellness agent so it doesn't re-ask
  // ── CORRECTION 26 Aug: was `agentId === 'wellness'`. caps: ["sleep"] — same shape as the learning
  //    profile above. The nurse also holds the sleep card and is deliberately NOT given this block;
  //    that was true before and is now visible in the records instead of implied by one name here.
  if (window.REG && window.REG.hasCap && window.REG.hasCap(agentId, 'sleep')) {
    try {
      const p = JSON.parse(localStorage.getItem('toto_sleep_profile') || '{}')
      const lines = []
      if (p.goal)         lines.push('sleep goal: ' + p.goal + ' hours/night')
      if (p.actual)       lines.push('actual sleep: ' + p.actual)
      if (p.onset)        lines.push('sleep onset routine: ' + p.onset)
      if (p.wake_routine) lines.push('wake routine: ' + p.wake_routine)
      if (p.helps)        lines.push('what helps: ' + p.helps)
      if (p.hurts)        lines.push('what makes it worse: ' + p.hurts)
      if (p.background)   lines.push('background: ' + p.background)
      if (lines.length)   parts.push('\n--- SLEEP PROFILE ---\n' + lines.join('\n'))
    } catch (_) {}
    // food profile
    try {
      const fp = JSON.parse(localStorage.getItem('toto_food_profile') || '{}')
      const fl = []
      if (fp.diet)           fl.push('diet: ' + fp.diet)
      if (fp.frequency)      fl.push('eating frequency: ' + fp.frequency)
      if (fp.portion)        fl.push('portion size: ' + fp.portion)
      if (fp.favorites_good) fl.push('favorite healthy foods: ' + fp.favorites_good)
      if (fp.favorites_bad)  fl.push('comfort / fallback foods: ' + fp.favorites_bad)
      if (fp.treats)         fl.push('treats: ' + fp.treats)
      if (fp.temptations)    fl.push('temptations to avoid: ' + fp.temptations)
      if (fp.background)     fl.push('background: ' + fp.background)
      if (fl.length)         parts.push('\n--- FOOD PROFILE ---\n' + fl.join('\n'))
    } catch (_) {}
    // exercise profile — how they like to move, so wellness programs to it instead of re-asking
    try {
      const ep = JSON.parse(localStorage.getItem('toto_exercise_profile') || '{}')
      const xl = []
      if (ep.favorites)  xl.push('favorite movement: ' + ep.favorites)
      if (ep.frequency)  xl.push('how often: ' + ep.frequency)
      if (ep.time)       xl.push('best time of day: ' + ep.time)
      if (ep.intensity)  xl.push('intensity they like: ' + ep.intensity)
      if (ep.goals)      xl.push('training for: ' + ep.goals)
      if (ep.limits)     xl.push('injuries / limits: ' + ep.limits)
      if (ep.motivation) xl.push('what gets them moving: ' + ep.motivation)
      if (ep.background) xl.push('background: ' + ep.background)
      if (xl.length)     parts.push('\n--- EXERCISE PROFILE ---\n' + xl.join('\n'))
    } catch (_) {}
  }
  // ⭐ THE PURITY FILTER MOVED TO ROLE SHEETS, 26 Aug — agents/roles.json: purity-write · purity-teach.
  //    WAS: two `if (agentId === 'writer')` / `if (agentId === 'tutor')` blocks pushing prose from here.
  //    The block's own comment made the argument: "ONE rule, two coats… the same move the writer makes."
  //    A rule shared by a CLASS of bots, written once and worn by name, is what a role sheet IS — and
  //    roles.json already held five. THE PROSE IS UNCHANGED, lifted verbatim into the sheets.
  //    ⚠ THE POSITION CHANGED, deliberately, with Sum's go-ahead. These landed HERE, after the notes and
  //    the card profiles. Role sheets compile with `baked` in the ONE HARD SECTION — after the soul's
  //    ethics, before the list of hands — the spot Sum picked on 17 Aug: "just one section, role, after
  //    ethics above tools is perfect spot." A content rule belongs beside the ethics it qualifies.
  //    ⚠⚠ HOW THIS CUT WENT, since it is the lesson: my first attempt scanned forward for an end marker
  //    with an UNBOUNDED loop, failed to match it, ran off the end of the file and deleted 200 lines.
  //    Recovered from shell/engine.js — the ASSEMBLED copy build.sh cats from these parts, which still
  //    held the last good version. A generated file is a backup you did not know you had. This cut
  //    asserts both ends and refuses any span outside 800–2500 chars.
  // a UNIVERSAL operational rule (every agent, in the head so the woodshop sees it too): how to handle an
  // attached file. it ALWAYS opens in its home card automatically; act on it if it's your lane, otherwise
  // say where it opened and ask what they want — never refuse, never fake-handle it. (Sum, 2026-06-20)
  // THE HAND-OFF moved out of the head (Sum 2026-08-23: "attachments is a custom chain of tools for each bot that only
  // fires on an attachment"): the per-bot chain rides the ROUND a file arrives (conductor.js attachRules, from the
  // agent folder's injection.json `attach`). One line stays so a bot knows plain files land somewhere.
  parts.push('\n--- ATTACHMENTS ---\nAn attached file opens in its home card automatically. If it is not your lane, say where it opened and ask what they want done; never refuse, never pretend to handle it. When something is handed to you this turn, your hand-off chain rides with that turn.')

  // THE SOUL — yoga · substrate · ethics, the shared layer. front-load it (a model weights the top): the
  // frame the agent wakes INTO, before its name. lands under the baked guard, above the identity. [#1]
  const soul = buildSoul(get, off)
  if (soul) parts.unshift(soul)
  // ⭐ BRAHMAN IS ATMAN IS THE COLD START (Sum 2026-08-17: "I want brahman as atman as cold start
  //   for all bots"). Nothing is unshifted above the soul any more — YOGA is the first thing every
  //   bot wakes into, on every turn, before it is told its job or handed a tool.
  //   ⚠ baked USED TO BE unshifted here, four times over (`new Array(edited ? 2 : 4).fill()`), on
  //     the theory that repetition at the top hardens adherence. It cost nurse ~2,100 characters of
  //     her own words, four times, at the most expensive position in the context — 3k over any other
  //     bot. It now rides ONCE, inside the role section, after ethics. The hardening that holds is
  //     structural, not repetition: it is not editable, and the role sheet restates the same wall in
  //     DIFFERENT words right beside it — which beats the same words four times, because a model
  //     that skimmed copy one skims copies two through four.
  return parts.join('\n')
}

