// food-tools.js — the 🥗 food card's ATOMIC tool-beans. one input = one bean (the jenga grain:
// "input food, input time, input servings, save — all separate"). each is one makeTool: one micro-
// tutorial (clue), one strike. a small local model sinks ONE known shot clean while it fumbles a combo;
// we burn the calls because they're cheap (local · solar · MLX). the COARSE edit_food_doc still exists —
// these are the fine chisels beside it. loads AFTER shell/tools.js (needs window.makeTool).
//
// the DRAFT model: the food_in_* atoms build ONE in-progress meal in localStorage.toto_food_draft
// (invisible to the card, like filling a form); food_save commits it to food-plan.json's meal log.
// pantry_* + meal_* atoms mutate the published doc directly, by key / id (from read_food_doc).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the draft store — one in-progress meal, ....... search: "the draft store — one"
//   the published doc (food-plan.json) — the ...... search: "the published doc"
//   pantry atoms — immediate, by key (from ........ search: "pantry atoms"
//   meal atoms — edit a logged meal by id (from ... search: "meal atoms — edit a"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the food card's atomic tools:
//    **`food_in_*` (draft meal input), `food_save` (commit to log), `food_draft_*` (draft
//    **management), `pantry_*` (pantry mutations), and `meal_*` (logged meal mutations). It
//    **registers these with `window.makeTool` (line 12) and depends on
//    **`localStorage.toto_food_draft` and the `food-plan.json` document shape.
//
//    **TOUCH HERE** —
//    - Add a new draft input field → `inputAtom()` call, lines 44–50 (follow the pattern; add field
//    - to the object destructured in `food_save` strike at line 98–99)
//    - Change what `food_save` writes to a meal → the object literal at lines 98–99 (keys: `id`,
//    - `d`, `t`, `n`, `meal`, `kcal`, `p`, `f`, `c`, `status`, `sv`, `note`)
//    - Add a pantry mutation (count/state/icon/rename pattern) → `pantryAtom()` call, lines 124–127
//    - (or add a new `MT()` block like `pantry_remove` at lines 129–135)
//    - Change pantry item shape → the object pushed at line 113 (keys: `k`, `icon`, `n`, `u`, `ct`,
//    - `mx`, `st`, `note`)
//    - Change meal status/removal logic → `meal_status` strike at lines 141–143 or `meal_remove`
//    - strike at lines 148–151
//    - Adjust draft field names → change the field key in `inputAtom()` calls (e.g., `'n'` at line
//    - 44) AND update the destructure in `food_save` at lines 98–99
//
//    **TRAPS** —
//    - `localStorage.toto_food_draft` is the persisted draft key (line 7, 16–18). Renaming it
//    - orphans in-progress meals.
//    - The meal object shape at lines 98–99 is written to `food-plan.json` and read by the card.
//    - Removing or renaming a key silently loses that data for existing meals.
//    - The pantry item shape at line 113 (keys `k`, `n`, `u`, `ct`, `mx`, `st`, `note`) is
//    - persisted. Shape changes break existing pantry reads.
//    - `draftGet()` / `draftSet()` / `draftClear()` (lines 16–18) are called by every input atom
//    - and `food_save`. Changing their contract breaks all draft operations.
//    - `loadDoc()` and `saveDoc()` (lines 21–23) are the only places the `food-plan.json` doc is
//    - loaded and written. Both must stay in sync with the card's watcher.
//    - The `uid()` function at line 24 generates meal IDs (`'m'` prefix) and pantry keys (`'x'`
//    - prefix). Changing the prefix breaks existing lookups in `meal_status` (line 142) and
//    - `pantry_*` atoms (line 121).
//    - `inputAtom()` at line 27 is a factory; the `parse` parameter (e.g., line 48) is optional.
//    - Forgetting it on numeric fields silently coerces to NaN.
//
//    **DO NOT** —
//    - Do not rename `draftGet`, `draftSet`, `draftClear`, `loadDoc`, `saveDoc`, `uid`,
//    - `inputAtom`, or `pantryAtom` — they are internal helpers, not exported, but their names are
//    - load-bearing within this file.
//    - Do not add new draft fields without also updating the `food_save` strike (lines 98–99) to
//    - include them in the saved meal object.
//    - Do not change the `food-plan.json` document structure (the `d.meals`, `d.pantry`, `d.day`
//    - shape) here — that belongs in the card's `read_food_doc` or `edit_food_doc` (referenced in
//    - comments but not in this file).
//    - Do not add validation logic here beyond what `inputAtom` parse functions do — the card owns
//    - the UI validation and error display.
//    - Do not move or rename the IIFE wrapper (lines 11, 153) or the `window.makeTool` guard (lines
//    - 12–13).
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const MT = window.makeTool
  if (!MT) return   // tools.js must load first

  // ── the draft store — one in-progress meal, built field by field until food_save commits it ──
  const draftGet   = () => { try { return JSON.parse(localStorage.getItem('toto_food_draft') || '{}') } catch (_) { return {} } }
  const draftSet   = d  => { try { localStorage.setItem('toto_food_draft', JSON.stringify(d)) } catch (_) {} }
  const draftClear = () => { try { localStorage.removeItem('toto_food_draft') } catch (_) {} }

  // ── the published doc (food-plan.json) — the food card watches it + re-renders on mutation ──
  const loadDoc = ctx => { const doc = ctx.sb('food-plan.json'); if (!doc || typeof doc.data !== 'string') return null
    try { return { doc, d: JSON.parse(doc.data) } } catch (_) { return null } }
  const saveDoc = (doc, d) => { doc.data = JSON.stringify(d, null, 2) }   // mirror edit_food_doc → triggers the watcher
  const uid = p => p + Date.now().toString(36) + Math.floor(Math.random() * 999).toString(36)

  // ⭐ MMMM READ-BACKS (26 Aug) — every one of these goes to the SURFACE, never through the strike's own
  //    helper. loadDoc() takes the tool ctx and a readback is handed (call, out) with no ctx, which is a
  //    happy accident: reading window.SANDBOX raw is the more honest check anyway. If the doc the card
  //    renders and the doc the tool wrote ever disagree, this is the line that says so.
  const rawDoc = () => { try { const f = (window.SANDBOX || {})['food-plan.json']; return f ? JSON.parse(f.data || 'null') : null } catch (_) { return null } }
  const draftBack = () => { const dr = draftGet(); const ks = Object.keys(dr)
    return ks.length ? 'the draft holds: ' + ks.map(k => k + '=' + (typeof dr[k] === 'object' ? JSON.stringify(dr[k]) : dr[k])).join(' \u00b7 ') : 'the draft is empty' }
  const pantryBack = (call) => { const d = rawDoc(); if (!d) return 'no food doc on the surface'
    const p = d.pantry || []; const i = p.find(x => x.k === (call && call.key))
    return p.length + ' item' + (p.length === 1 ? '' : 's') + ' in the pantry' + (i ? ' \u00b7 ' + i.n + ': ' + i.ct + '/' + i.mx + ' [' + i.st + ']' : (call && call.key ? ' \u00b7 "' + call.key + '" is NOT among them' : '')) }
  const mealsBack = (call) => { const d = rawDoc(); if (!d) return 'no food doc on the surface'
    const m = d.meals || []; const one = m.find(x => x.id === (call && call.id))
    return m.length + ' meal' + (m.length === 1 ? '' : 's') + ' in the log' + (one ? ' \u00b7 ' + one.n + ' [' + one.status + ']' : (call && call.id ? ' \u00b7 "' + call.id + '" is NOT among them' : (m.length ? ' \u00b7 last: ' + m[m.length - 1].n : ''))) }

  // one "input X" atom, generated — sets one field on the draft. DRY: every input bean is this shape.
  const inputAtom = (id, field, label, example, parse) => MT({
    id, card: 'food', klass: 'write', readback: draftBack,
    blurb: `set the draft meal's ${label} — one field of the meal you're logging. food_save commits it.`,
    clue:
`set the ${label} on the in-progress meal (the draft). build a meal field by field, then food_save commits it
to the log. the draft stays invisible until saved — like filling a form, then hitting save.
template: { "tool": "${id}", "${field}": ${example} }
edge: nothing started → this begins a new draft. food_draft_show to review · food_save to commit.`,
    strike: (call) => {
      const v = parse ? parse(call) : call[field]
      if (v == null || v === '') return `${id}: no ${label} given — pass "${field}".`
      const dr = draftGet(); dr[field] = v; draftSet(dr)
      return `${id}: draft ${label} = ${typeof v === 'object' ? JSON.stringify(v) : v}. (food_save to commit · food_draft_show to review)`
    },
  })

  // the input atoms — one bean per field
  inputAtom('food_in_name',   'n',      'name (the food)',                          '"Caesar salad"')
  inputAtom('food_in_time',   't',      'time',                                     '"18:00"')
  inputAtom('food_in_date',   'd',      'date',                                     '"2026-03-27"')
  inputAtom('food_in_meal',   'meal',   'meal type (breakfast/lunch/dinner/snack)', '"dinner"')
  inputAtom('food_in_kcal',   'kcal',   'calories',                                 '650', c => +c.kcal || 0)
  inputAtom('food_in_status', 'status', 'status (planned or eaten)',                '"eaten"')
  inputAtom('food_in_note',   'note',   'note (mood · why · how it felt)',          '"felt great, post-yoga"')

  // macros — three numbers, one bean
  MT({ id: 'food_in_macros', card: 'food', klass: 'write', readback: draftBack,
    blurb: "set the draft meal's macros — protein/fat/carb in grams. food_save commits it.",
    clue:
`set the macros (grams) on the in-progress meal draft.
template: { "tool": "food_in_macros", "p": 30, "f": 40, "c": 35 }
edge: pass any subset; missing ones stay 0. always confirm an estimate AS an estimate first.`,
    strike: (call) => { const dr = draftGet()
      if (call.p != null) dr.p = +call.p || 0; if (call.f != null) dr.f = +call.f || 0; if (call.c != null) dr.c = +call.c || 0
      draftSet(dr); return `food_in_macros: draft P${dr.p || 0}/F${dr.f || 0}/C${dr.c || 0}. (food_save to commit)` } })

  // servings — the food-group taxonomy
  MT({ id: 'food_in_servings', card: 'food', klass: 'write', readback: draftBack,
    blurb: "set the draft meal's food-group servings — fr🍎 vg🥦 cb🍞 pr🍗 al🍺 sw🍰. food_save commits it.",
    clue:
`set the food-group servings on the meal draft. keys: fr (fruit🍎) · vg (veg🥦) · cb (carb🍞) · pr (protein🍗) · al (alcohol🍺) · sw (sweets🍰).
template: { "tool": "food_in_servings", "sv": { "vg": 2, "pr": 1 } }
edge: pass only the groups present. food_save to commit.`,
    strike: (call) => { const dr = draftGet(); dr.sv = { ...(dr.sv || {}), ...(call.sv || {}) }; draftSet(dr)
      return `food_in_servings: draft servings ${JSON.stringify(dr.sv)}. (food_save to commit)` } })

  // show / clear the draft
  MT({ id: 'food_draft_show', card: 'food', klass: 'read', readback: draftBack,
    blurb: "show the in-progress meal draft — what you've input so far, before food_save.",
    clue: `show the current meal draft (the fields input so far).\ntemplate: { "tool": "food_draft_show" }`,
    strike: () => { const dr = draftGet(); const ks = Object.keys(dr)
      return ks.length ? `draft meal: ${ks.map(k => `${k}=${typeof dr[k] === 'object' ? JSON.stringify(dr[k]) : dr[k]}`).join(' · ')}`
                       : `draft is empty — start with food_in_name.` } })

  MT({ id: 'food_draft_clear', card: 'food', klass: 'write', readback: draftBack,
    blurb: 'discard the in-progress meal draft without saving.',
    clue: `discard the current meal draft.\ntemplate: { "tool": "food_draft_clear" }`,
    strike: () => { draftClear(); return `food_draft_clear: draft discarded.` } })

  // SAVE — commit the draft to the log
  MT({ id: 'food_save', card: 'food', klass: 'write', readback: mealsBack,
    blurb: 'SAVE — commit the in-progress meal draft to the food log (food-plan.json). the card re-renders.',
    clue:
`commit the meal draft (built with the food_in_* atoms) to the log. needs at least a name (food_in_name).
template: { "tool": "food_save" }
edge: empty draft → nothing to save. no food doc → open the 🥗 food card first.`,
    strike: (call, ctx) => {
      const dr = draftGet()
      if (!dr.n) return `food_save: the draft has no food yet — food_in_name first.`
      const L = loadDoc(ctx); if (!L) return `food_save: no food doc — open the 🥗 food card first.`
      L.d.meals = L.d.meals || []
      L.d.meals.push({ id: uid('m'), d: dr.d || L.d.day || '', t: dr.t || 'now', n: dr.n, meal: dr.meal || '',
        kcal: +dr.kcal || 0, p: +dr.p || 0, f: +dr.f || 0, c: +dr.c || 0, status: dr.status || 'eaten', sv: dr.sv || {}, note: dr.note || '' })
      saveDoc(L.doc, L.d); draftClear()
      return `food_save: logged "${dr.n}"${dr.kcal ? ' · ' + dr.kcal + 'kcal' : ''}${dr.t ? ' @ ' + dr.t : ''}. draft cleared — the food card will update.`
    } })

  // ── pantry atoms — immediate, by key (from read_food_doc) ──
  MT({ id: 'pantry_add', card: 'food', klass: 'write', readback: pantryBack,
    blurb: 'add a pantry item — name + state (buy/stocked/prepped/ready). returns its key.',
    clue:
`add an item to the pantry. states: buy → stocked → prepped → ready (ready = the prep push).
template: { "tool": "pantry_add", "name": "avocado", "state": "buy", "icon": "🥑", "count": 0, "max": 4 }
edge: no food doc → open the food card first.`,
    strike: (call, ctx) => { const L = loadDoc(ctx); if (!L) return `pantry_add: no food doc — open the food card first.`
      L.d.pantry = L.d.pantry || []; const k = uid('x')
      L.d.pantry.push({ k, icon: call.icon || '🍴', n: String(call.name || 'item'), u: call.unit || '', ct: +call.count || 0, mx: +call.max || 4, st: call.state || 'stocked', note: call.note || '' })
      saveDoc(L.doc, L.d); return `pantry_add: "${call.name}" added [${call.state || 'stocked'}], key "${k}".` } })

  const pantryAtom = (id, label, apply, tmpl) => MT({
    id, card: 'food', klass: 'write', readback: pantryBack,
    blurb: `pantry: ${label}. names the item by its key (from read_food_doc).`,
    clue: `${label} on a pantry item, by its key.\ntemplate: ${tmpl}\nedge: unknown key → reported back. read_food_doc for the keys.`,
    strike: (call, ctx) => { const L = loadDoc(ctx); if (!L) return `${id}: no food doc.`
      const i = (L.d.pantry || []).find(x => x.k === call.key); if (!i) return `${id}: no item with key "${call.key}" — read_food_doc for the keys.`
      const msg = apply(i, call); saveDoc(L.doc, L.d); return `${id}: ${msg}` } })

  pantryAtom('pantry_count',  'set the count',                          (i, c) => { i.ct = Math.max(0, Math.min(i.mx == null ? 99 : i.mx, +c.count || 0)); return `${i.n} → ${i.ct}` }, '{ "tool": "pantry_count", "key": "chicken", "count": 3 }')
  pantryAtom('pantry_state',  'set the state (buy/stocked/prepped/ready)', (i, c) => { i.st = c.state; return `${i.n} → ${c.state}` }, '{ "tool": "pantry_state", "key": "chicken", "state": "ready" }')
  pantryAtom('pantry_icon',   'set the icon',                           (i, c) => { i.icon = [...String(c.icon || '')].slice(0, 3).join(''); return `${i.n} icon ${i.icon}` }, '{ "tool": "pantry_icon", "key": "chicken", "icon": "🍗" }')
  pantryAtom('pantry_rename', 'rename the item',                        (i, c) => { i.n = String(c.name || i.n); return `renamed → ${i.n}` }, '{ "tool": "pantry_rename", "key": "chicken", "name": "roast chicken" }')

  MT({ id: 'pantry_remove', card: 'food', klass: 'sharp', readback: pantryBack,
    blurb: 'remove a pantry item by its key.',
    clue: `remove a pantry item.\ntemplate: { "tool": "pantry_remove", "key": "chicken" }\nedge: unknown key → reported back.`,
    strike: (call, ctx) => { const L = loadDoc(ctx); if (!L) return `pantry_remove: no food doc.`
      const before = (L.d.pantry || []).length; L.d.pantry = (L.d.pantry || []).filter(x => x.k !== call.key)
      if (L.d.pantry.length === before) return `pantry_remove: no item with key "${call.key}".`
      saveDoc(L.doc, L.d); return `pantry_remove: removed "${call.key}".` } })

  // ── meal atoms — edit a logged meal by id (from read_food_doc) ──
  MT({ id: 'meal_status', card: 'food', klass: 'write', readback: mealsBack,
    blurb: "set a logged meal's status — planned or eaten (by id).",
    clue: `flip a logged meal between planned and eaten.\ntemplate: { "tool": "meal_status", "id": "m3", "status": "eaten" }\nedge: unknown id → reported back. read_food_doc for ids.`,
    strike: (call, ctx) => { const L = loadDoc(ctx); if (!L) return `meal_status: no food doc.`
      const m = (L.d.meals || []).find(x => x.id === call.id); if (!m) return `meal_status: no meal "${call.id}".`
      m.status = call.status || m.status; saveDoc(L.doc, L.d); return `meal_status: ${m.n} → ${m.status}.` } })

  MT({ id: 'meal_remove', card: 'food', klass: 'sharp', readback: mealsBack,
    blurb: 'delete a logged meal by its id.',
    clue: `delete a logged meal.\ntemplate: { "tool": "meal_remove", "id": "m3" }\nedge: unknown id → reported back.`,
    strike: (call, ctx) => { const L = loadDoc(ctx); if (!L) return `meal_remove: no food doc.`
      const before = (L.d.meals || []).length; L.d.meals = (L.d.meals || []).filter(x => x.id !== call.id)
      if (L.d.meals.length === before) return `meal_remove: no meal "${call.id}".`
      saveDoc(L.doc, L.d); return `meal_remove: removed "${call.id}".` } })

})()
