// wellness-tools.js — SLEEP + EXERCISE atomic tool-beans (beside food-tools.js). same jenga grain:
// one input = one bean. covers the CLEAN localStorage surfaces — the sleep PROFILE (toto_sleep_profile),
// the exercise LOG (toto_exercise_log) + profile (toto_exercise_profile).
//
// ⚠ sleep NIGHTS are NOT built here: the card holds them in-memory (`current.nights`, from a Google-Fit
// import + manual adds) with no clean headless persistence — building night-atoms blind would risk
// silent data loss. flagged in docs/jenga-build-log.md. loads after shell/tools.js.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   a profile-field setter: sets ONE field of a ... search: "a profile-field setter:"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the atomic tool-beans that build sleep
//    **profiles, exercise profiles, exercise logs, and sleep night drafts. It exports nothing;
//    **instead it calls `window.makeTool` (line 10) to register tools on the window that the
//    **wellness card agents invoke. The tools read/write these localStorage keys:
//    **`toto_sleep_profile`, `toto_exercise_profile`, `toto_exercise_log`, `toto_exercise_draft`,
//    **`toto_sleep_night_draft`, and `toto_sleep_nights`.
//
//    **TOUCH HERE** —
//    - Add a new sleep profile field → `profileAtom()` L17, add a call like L27–33
//    - Add a new exercise profile field → `profileAtom()` L17, add a call like L37–38
//    - Add a new exercise draft input → `exInput()` L45, add a call like L52–56
//    - Add a new sleep night draft input → `snInput()` L79, add a call like L86–96
//    - Change a localStorage key name → update the string in `lsGet`/`lsSet` calls (e.g., L26, L36,
//    - L41–43, L62, L75–77)
//    - Change the kcal formula → `exercise_save` strike function L65
//    - Change the validation rule for exercise_save → L61
//    - Change the validation rule for sleep_night_save → L101
//
//    **TRAPS** —
//    - The localStorage keys (`toto_sleep_profile`, `toto_exercise_profile`, `toto_exercise_log`,
//    - `toto_exercise_draft`, `toto_sleep_night_draft`) are persisted user data; renaming them
//    - orphans existing records. They are also read by other files (dashboards.js, food-tools.js);
//    - search the codebase before changing.
//    - `profileAtom()` L17 auto-selects the card based on the key name (line 18: `'exercise'` if
//    - key is `toto_exercise_profile`, else `'sleep'`). If you add a third profile type, this logic
//    - breaks.
//    - `exercise_save` L58–66 and `sleep_night_save` L98–103 both call `exClear()` / `snClear()`
//    - after commit (L64, L103). If you add a new field to the draft, ensure it is either saved to
//    - the log or explicitly cleared.
//    - `sleep_night_save` L102 depends on `window.sleepAddNight` being loaded; `sleep_read` L113
//    - depends on `window.sleepNights`. These are defined elsewhere (dashboards.js refactor, per
//    - line 73). If they are not present, the tools fail silently.
//    - The card assignment on line 18 must match the agent's nav (line 18 comment). Mismatches will
//    - cause tools to be invisible to the wrong card.
//
//    **DO NOT** —
//    - Do not build sleep night atoms here (line 5–7 explains why: in-memory `current.nights` from
//    - Google Fit has no clean headless persistence).
//    - Do not rename `MT`, `lsGet`, `lsSet` without checking shell/tools.js (line 10 comment: loads
//    - after it).
//    - Do not move the IIFE wrapper (line 9, 117) or the early return on line 11; they guard
//    - against missing `window.makeTool`.
//    - Do not change the shape of objects pushed to `toto_exercise_log` (line 63) or passed to
//    - `window.sleepAddNight` (line 103) without coordinating with the code that reads them
//    - (dashboards.js).
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const MT = window.makeTool
  if (!MT) return

  const lsGet = (k, d) => { try { return JSON.parse(localStorage.getItem(k) || d) } catch (_) { return JSON.parse(d) } }
  const lsSet = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }

  // ⭐ MMMM READ-BACKS (26 Aug) — each one re-reads the STORE, never the draft the strike just held in
  //    its hand. A draft atom that says "set" and a store that never took it is the whole class of bug
  //    these exist to catch, and the only way to catch it is to go back and look.
  const profBack = key => () => { const p = lsGet(key, '{}'); const ks = Object.keys(p)
    return ks.length ? key.replace('toto_', '').replace('_profile', '') + ' profile on disk: ' + ks.map(k => k + '=' + JSON.stringify(String(p[k]).slice(0, 40))).join(' \u00b7 ') : 'that profile is empty on disk' }
  const exBack = () => { const dr = lsGet('toto_exercise_draft', '{}'); const ks = Object.keys(dr)
    const log = lsGet('toto_exercise_log', '[]')
    return (ks.length ? 'draft: ' + ks.map(k => k + '=' + dr[k]).join(' \u00b7 ') : 'draft empty')
      + ' \u00b7 ' + log.length + ' session' + (log.length === 1 ? '' : 's') + ' in the log'
      + (log.length ? ' \u00b7 last: ' + log[log.length - 1].date + ' ' + log[log.length - 1].type : '') }
  const snBack = () => { const dr = lsGet('toto_sleep_night_draft', '{}'); const ks = Object.keys(dr)
    let n = 0; try { n = (window.sleepNights ? window.sleepNights() : []).length } catch (_) {}
    return (ks.length ? 'draft: ' + ks.map(k => k + '=' + dr[k]).join(' \u00b7 ') : 'draft empty')
      + ' \u00b7 ' + n + ' night' + (n === 1 ? '' : 's') + ' in the store' }

  // ── a profile-field setter: sets ONE field of a {field:value} localStorage object ──
  const profileAtom = (id, key, field, label, example) => MT({
    id, card: key === 'toto_exercise_profile' ? 'exercise' : 'sleep',   // card must match the agent's nav (food/sleep/exercise)
    klass: 'write', readback: profBack(key),
    blurb: `set the ${label} — one field of the profile. the wellness gear reads it.`,
    clue: `set the ${label} on the profile (overwrites that one field).\ntemplate: { "tool": "${id}", "value": ${example} }\nedge: pass "value".`,
    strike: (call) => { const v = call.value; if (v == null || v === '') return `${id}: pass "value".`
      const p = lsGet(key, '{}'); p[field] = String(v); lsSet(key, p); return `${id}: ${label} = "${v}".` },
  })

  // 🛏️ SLEEP profile (toto_sleep_profile)
  const SP = 'toto_sleep_profile'
  profileAtom('sleep_set_goal',       SP, 'goal',         'sleep goal (hours/night)',        '"8"')
  profileAtom('sleep_set_actual',     SP, 'actual',       'how much sleep you actually get', '"5–6 hours most nights"')
  profileAtom('sleep_set_routine',    SP, 'onset',        'how you get to sleep (routine)',  '"warm bath · dim lights by 9pm · no screens"')
  profileAtom('sleep_set_wake',       SP, 'wake_routine', 'wake routine',                    '"no alarm when possible · keep dark until ready"')
  profileAtom('sleep_set_helps',      SP, 'helps',        'what helps your sleep',           '"hard yoga the day before, blackout curtains"')
  profileAtom('sleep_set_hurts',      SP, 'hurts',        'what makes sleep worse',          '"eating after 8pm, any alcohol"')
  profileAtom('sleep_set_background', SP, 'background',   'background wellness should know',  '"clinical insomniac, migraines, ADHD"')

  // 💪 EXERCISE profile (toto_exercise_profile)
  const EP = 'toto_exercise_profile'
  profileAtom('exercise_set_favorites', EP, 'favorites', 'movement you actually keep doing', '"teaching yoga, long walks, garden beds by hand"')
  profileAtom('exercise_set_frequency', EP, 'frequency', 'how often you aim to move',        '"something most days · yoga 5×/wk"')

  // 💪 EXERCISE log — draft model (build a session field-by-field, then exercise_save commits it)
  const exGet   = () => lsGet('toto_exercise_draft', '{}')
  const exSet   = d  => lsSet('toto_exercise_draft', d)
  const exClear = () => { try { localStorage.removeItem('toto_exercise_draft') } catch (_) {} }

  const exInput = (id, field, label, example, parse) => MT({
    id, card: 'exercise', klass: 'write', readback: exBack,
    blurb: `set the draft workout's ${label}. exercise_save commits it to the log.`,
    clue: `set the ${label} on the in-progress workout draft. build it field by field, then exercise_save.\ntemplate: { "tool": "${id}", "${field}": ${example} }\nedge: exercise_save needs at least a type + duration.`,
    strike: (call) => { const v = parse ? parse(call) : call[field]; if (v == null || v === '') return `${id}: pass "${field}".`
      const dr = exGet(); dr[field] = v; exSet(dr); return `${id}: draft ${label} = ${v}. (exercise_save to commit)` },
  })
  exInput('exercise_in_type',      'type',         'activity (yoga · walk · run · …)',           '"vinyasa yoga"')
  exInput('exercise_in_duration',  'duration_min', 'duration (minutes)',                          '45',  c => +c.duration_min || 0)
  exInput('exercise_in_intensity', 'met',          'intensity (MET — walk≈3 · yoga≈3 · run≈8)',   '3.5', c => +c.met || 0)
  exInput('exercise_in_date',      'date',         'date',                                        '"2026-03-27"')
  exInput('exercise_in_start',     'start',        'start time',                                  '"10:00 AM"')

  MT({ id: 'exercise_save', card: 'exercise', klass: 'write', readback: exBack,
    blurb: 'SAVE — commit the in-progress workout draft to the exercise log. the card re-renders.',
    clue: `commit the workout draft (built with exercise_in_*) to toto_exercise_log. needs a type + duration.\ntemplate: { "tool": "exercise_save" }\nedge: empty/incomplete draft → nothing saved.`,
    strike: () => { const dr = exGet(); if (!dr.type || !dr.duration_min) return `exercise_save: needs a type (exercise_in_type) + duration (exercise_in_duration).`
      const log = lsGet('toto_exercise_log', '[]')
      log.push({ date: dr.date || new Date().toISOString().slice(0, 10), type: dr.type, start: dr.start || '10:00 AM', duration_min: +dr.duration_min || 0, met: +dr.met || 3.5 })
      lsSet('toto_exercise_log', log); exClear()
      const kcal = Math.round((+dr.met || 3.5) * 132 * ((+dr.duration_min || 0) / 60))
      return `exercise_save: logged ${dr.duration_min}min ${dr.type} — ~${kcal} kcal. draft cleared.` } })

  MT({ id: 'exercise_draft_clear', card: 'exercise', klass: 'write', readback: exBack,
    blurb: 'discard the in-progress workout draft.',
    clue: `discard the workout draft.\ntemplate: { "tool": "exercise_draft_clear" }`,
    strike: () => { exClear(); return `exercise_draft_clear: draft discarded.` } })

  // 🛏️ SLEEP NIGHTS — draft model → window.sleepAddNight (dashboards.js refactor: persists to toto_sleep_nights,
  // the SAME store the human's manual form + Fit-import write to. one shape, one store; reopen the card to see it).
  const snGet   = () => lsGet('toto_sleep_night_draft', '{}')
  const snSet   = d  => lsSet('toto_sleep_night_draft', d)
  const snClear = () => { try { localStorage.removeItem('toto_sleep_night_draft') } catch (_) {} }

  const snInput = (id, field, label, example, parse) => MT({
    id, card: 'sleep', klass: 'write', readback: snBack,
    blurb: `set the draft night's ${label}. sleep_night_save commits it.`,
    clue: `set the ${label} on the in-progress night draft. build it field by field, then sleep_night_save.\ntemplate: { "tool": "${id}", "${field}": ${example} }\nedge: only the date is required; fill what you know — the staging numbers (deep/rem/eff) come from a watch/Fit import.`,
    strike: (call) => { const v = parse ? parse(call) : call[field]; if (v == null || v === '') return `${id}: pass "${field}".`
      const dr = snGet(); dr[field] = v; snSet(dr); return `${id}: draft night ${label} = ${v}. (sleep_night_save to commit)` },
  })
  snInput('sleep_in_date',      'date',      'date (the night — required)',  '"2026-03-27"')
  snInput('sleep_in_inbed',     'inbed',     'in-bed time',                  '"22:30"')
  snInput('sleep_in_lightsoff', 'lightsoff', 'lights-off time',             '"23:00"')
  snInput('sleep_in_out',       'outbed',    'out-of-bed time',             '"06:30"')
  snInput('sleep_in_awake',     'awake',     'minutes awake in the night',  '20',  c => +c.awake || 0)
  snInput('sleep_in_onset',     'onset',     'sleep-onset latency (min)',   '15',  c => +c.onset || 0)
  snInput('sleep_in_deep',      'deep',      'deep sleep (min)',            '90',  c => +c.deep || 0)
  snInput('sleep_in_rem',       'rem',       'REM sleep (min)',             '110', c => +c.rem || 0)
  snInput('sleep_in_light',     'light',     'light sleep (min)',           '240', c => +c.light || 0)
  snInput('sleep_in_eff',       'eff',       'sleep efficiency (%)',        '88',  c => +c.eff || 0)
  snInput('sleep_in_note',      'note',      'note / dream',                '"vivid dream"')

  MT({ id: 'sleep_night_save', card: 'sleep', klass: 'write', readback: snBack,
    blurb: 'SAVE — commit the in-progress night draft to the sleep log (persists). reopen the sleep card to see it.',
    clue: `commit the night draft (the sleep_in_* atoms) to the sleep log via the shared store. needs a date.\ntemplate: { "tool": "sleep_night_save" }\nedge: no date → nothing saved.`,
    strike: () => { const dr = snGet(); if (!dr.date) return `sleep_night_save: needs a date (sleep_in_date).`
      if (!window.sleepAddNight) return `sleep_night_save: the sleep store isn't loaded yet.`
      const msg = window.sleepAddNight(dr); snClear(); return `sleep_night_save: ${msg}` } })

  MT({ id: 'sleep_night_clear', card: 'sleep', klass: 'write', readback: snBack,
    blurb: 'discard the in-progress night draft.',
    clue: `discard the night draft.\ntemplate: { "tool": "sleep_night_clear" }`,
    strike: () => { snClear(); return `sleep_night_clear: discarded.` } })

  MT({ id: 'sleep_read', card: 'sleep', klass: 'read', readback: snBack,
    blurb: 'read the sleep nights — the log (date · efficiency · deep/rem · times). read before you edit.',
    clue: `list the sleep nights (most recent first).\ntemplate: { "tool": "sleep_read" }\nedge: store not loaded → say so.`,
    strike: () => { if (!window.sleepNights) return `sleep_read: the sleep store isn't loaded yet.`
      const ns = window.sleepNights(); if (!ns.length) return `sleep_read: no nights logged.`
      return `sleep nights (recent):\n` + ns.slice(-30).reverse().map(n => `· ${n.iso} eff${n.eff}% deep${n.deep}m rem${n.rem}m awake${n.awake}m${n.note ? ' — ' + n.note : ''}`).join('\n') } })

  // ── ⭐ read_profiles — THE ONE THAT WAS CATALOGUED FOR MONTHS AND NEVER BUILT (26 Aug) ──────────
  //  It has sat in TOOLKITS since long before this file, card 'food', blurb "read the sleep + food +
  //  exercise profiles so you do not re-ask." Nothing answered to it — and because toolLines() prints a
  //  TOOLKITS entry to every bot holding that card, the NURSE and WELLNESS were both being TOLD they
  //  had it, every turn, with nothing behind it. A tool a bot is told it has is worse than one it merely
  //  lists: it will reach. (Sum, 26 Aug: "look like good tools to build and disperse.")
  //  ⚠ NOT A LOG READER. sleep_read walks the NIGHTS and read_food_doc walks the pantry and the meals;
  //  those are records. This walks the three PROFILES — the standing facts the human already typed once,
  //  which is the whole point of the blurb's "so you do not re-ask." Overlap here would be the tool
  //  earning its keep twice and answering neither question well.
  //  ⚠ THE EMPTY PROFILE IS THE ANSWER, NOT A FAILURE. An unfilled profile is real information: it means
  //  the bot MAY ask. So a blank one reports blank and names the atom that fills it, rather than refusing.
  //  Card 'food' because that is where the catalogue filed it — his shelf, not mine to re-file.
  const SLEEP_FIELDS = [['goal', 'sleep goal (hrs/night)'], ['actual', 'actually gets'], ['onset', 'how they get to sleep'],
    ['wake_routine', 'wake routine'], ['helps', 'what helps'], ['hurts', 'what hurts'], ['background', 'background']]
  const EX_FIELDS = [['favorites', 'movement they keep doing'], ['frequency', 'how often they aim to move']]
  const profLines = (key, fields) => { const p = lsGet(key, '{}') || {}
    const said = fields.filter(([f]) => p[f] != null && String(p[f]).trim() !== '')
    return said.length ? said.map(([f, lbl]) => `  · ${lbl}: ${p[f]}`).join('\n') : null }
  const profCount = () => { const s = lsGet('toto_sleep_profile', '{}') || {}, e = lsGet('toto_exercise_profile', '{}') || {}
    const n = o => Object.keys(o).filter(k => String(o[k] || '').trim() !== '').length
    return n(s) + n(e) }

  MT({ id: 'read_profiles', card: 'food', klass: 'read',
    readback: () => { const n = profCount()
      let goal = null; try { const f = (window.SANDBOX || {})['food-plan.json']; if (f && f.data) goal = (JSON.parse(f.data) || {}).goal } catch (_) {}
      return n + ' standing profile field(s) filled across sleep + exercise' + (goal ? ' \u00b7 food goal ' + goal + ' kcal' : ' \u00b7 no food goal set') },
    blurb: 'read the sleep + food + exercise profiles so you do not re-ask.',
    clue:
`read the human's three STANDING profiles in one call — the facts they already typed, so you never
re-ask for them. Do this BEFORE your first question about sleep, food or movement.
template: { "tool": "read_profiles" }
- sleep + exercise come from the profile atoms (sleep_set_*, exercise_set_*); food from the 🥗 card's goal.
- a BLANK profile is an answer: it means nothing was told to you, so you MAY ask — and the reply names
  the atom that stores it, so you can offer to write it down once they say it.
- the LOGS are elsewhere and are a different question: sleep_read (nights) · read_food_doc (pantry + meals).`,
    strike: () => {
      const out = []
      const sl = profLines('toto_sleep_profile', SLEEP_FIELDS)
      out.push('\ud83d\udecf SLEEP profile:\n' + (sl || '  (blank — nothing told to you; ask, then sleep_set_goal / _actual / _routine / _wake / _helps / _hurts / _background)'))
      const ex = profLines('toto_exercise_profile', EX_FIELDS)
      out.push('\ud83d\udcaa EXERCISE profile:\n' + (ex || '  (blank — ask, then exercise_set_favorites / exercise_set_frequency)'))
      let food = null
      try { const f = (window.SANDBOX || {})['food-plan.json']
        if (f && f.data) { const d = JSON.parse(f.data) || {}
          const pantry = (d.pantry || []).length, meals = (d.meals || []).length
          food = `  · daily goal: ${d.goal != null ? d.goal + ' kcal' : '(not set)'}\n  · ${pantry} pantry item(s) \u00b7 ${meals} meal(s) logged (read_food_doc for the detail)` } } catch (_) {}
      out.push('\ud83e\udd57 FOOD profile:\n' + (food || '  (no food doc yet \u2014 the \ud83e\udd57 food card has not been opened; nothing to re-ask about)'))
      return out.join('\n') } })

})()
