// setup.js — the local-engine controls, as a SHARED MODULE (not a card). TEXT ONLY this version: yocal
// (words, MLX/gemma, :8080). no key, no cloud. buttons call the Rust whitelist (run_engine) via Tauri's
// bridge; a live dot pings the port. lives in the ⚙️ gear (yocal tab). (SDXL/miraigen pulled — MIRAiGE^n
// is the external rework; image gen returns there.) + a one-button "locate engine folder" for portability.
//
// ADAPTIVE (Sum, 2026-06-27): the UI reflects what's ACTUALLY on disk (run_engine 'engine-status'). a model
// that's downloaded shows "ready" and its download button is GONE; if it can't be found, the button reappears.
// "pull a different model" + the "+ upload your own SDXL / LoRA / LLM" tuck behind a "+ add" expander.
//
// kosher rule: the picker only ever lists FREE, commercially-clean models — free to run AND free to sell output.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   THE SMOKE TEST (Sum 2026-07-23: "add smoke .... search: "THE SMOKE TEST (Sum"
//   the HEADLESS CORE — one engine for the gear ... search: "the HEADLESS CORE — one"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The UI and event wiring for the local engine controls (yocal text model, smoke test
//    **grader). Exports `window.ozEngines` (the render entry point), `window.SMOKE_SCOPE`, and
//    **`window.SMOKE_RUN` (the headless grader engine used by both the gear UI and the smoke_test
//    **tool bean).
//
//    **TOUCH HERE**
//    - Add a new model to the picker → `yocalBlock()` L35, add a `modelRow()` call in the `more`
//    - details block (L37–44)
//    - Change the smoke test's grading rules → `SMOKE_KNOWN` L57 (add/edit tool specs) or
//    - `SMOKE_SYS` L68 (the system prompt)
//    - Add a new smoke test tool → add entry to `SMOKE_KNOWN` L57 with `need` array and optional
//    - `hint`
//    - Change what the dot shows as "running" → `refresh()` L154, edit the selector or the `on`
//    - condition L157
//    - Wire a new button action → `wire()` L164, add a `.addEventListener()` block for the new
//    - `data-act` or `data-*` attribute
//    - Change the smoke test output format → `paint()` function inside `smokeLocal()` L146
//
//    **TRAPS**
//    - `SMOKE_KNOWN` keys (L57–67) must exactly match tool IDs in `window.TOOL_USE` or they
//    - silently grade as "no cue card registered" (L119). The `need` array field names must match
//    - the JSON call's top-level keys or the grader will reject them (L131).
//    - `window.AGENT_DATA` (L74) is read once at render time; if a bot's tool list changes after
//    - render, the smoke test scope won't see it until `renderInto()` is called again.
//    - The "all" checkbox in the cards multi-select is exclusive (L180–181); if you add a third
//    - multi-select, this logic won't apply to it without changes to `wire()`.
//    - `refresh()` L154 pings `http://127.0.0.1:8080` to check if yocal is running; if the port
//    - changes, update L112, L123, and L155.
//    - The rerender callback (L219) is passed to `wire()` and called after model downloads (L174);
//    - if you add async state that needs disk re-check, hook it here, not in the button handler.
//    - `el._ozTimer` (L221–222) persists on the DOM node; if the element is removed and re-added,
//    - the old timer will orphan. The interval checks `document.body.contains(el)` to self-clean
//    - (L222).
//
//    **DO NOT**
//    - Don't rename `window.ozEngines`, `window.SMOKE_SCOPE`, or `window.SMOKE_RUN` without
//    - updating the callers (likely in a tool bean or the gear UI host).
//    - Don't move the `TAURI()` check (L13) or the Tauri invocations (L16, L200) — they are the
//    - only bridge to the Rust whitelist. If you need a new Rust call, add it via `runEngine()` L14
//    - or a new `invoke()` call, don't inline it.
//    - Don't change the shape of the object returned by `smokeRoster()` L98 or `SMOKE_RUN()` L111
//    - without checking the smoke_test tool bean that consumes it.
//    - Don't add UI for image gen (SDXL/miraigen) here — the comment at L3 says it was pulled and
//    - lives in an external rework.
//    - Don't add cloud-model pickers or API keys — the kosher rule (L10) and the comment at L2 are
//    - load-bearing: this is local-only, no key, no cloud.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const TAURI = () => window.__TAURI__ && window.__TAURI__.core
  async function runEngine(which) {
    if (!TAURI()) return { err: 'native-only' }
    try { return { out: await window.__TAURI__.core.invoke('run_engine', { which }) } }
    catch (e) { return { err: String(e) } }
  }
  async function up(url) { try { await fetch(url, { method: 'GET' }); return true } catch (_) { return false } }
  async function status() {
    const r = await runEngine('engine-status')
    if (r.err || !r.out) return {}
    try { return JSON.parse(r.out) } catch (_) { return {} }
  }

  // every button carries an aria-label, because "start" alone is not a name Voice Control can aim at —
  // there are other starts on screen. "start yocal" is one utterance and it can only mean one thing.
  const btn = (act, label, cls, name) => `<button class="set-btn ${cls || ''}" data-act="${act}" aria-label="${name || label}">${label}</button>`
  const add = (kind, label) => `<button class="set-add" data-add="${kind}">${label}</button>`
  const ready = on => on ? '<span class="set-mtag set-ready">ready</span>' : '<span class="set-mtag set-pull">pull</span>'
  const modelRow = (name, on, note) => `<div class="set-model"><span class="set-mname">${name}</span>${ready(on)}<span class="set-mnote">${note}</span></div>`
  const rowHTML = (dotCls, title, sub, btns) =>
    `<div class="set-row"><span class="set-dot off ${dotCls}"></span><div class="set-titles"><b>${title}</b><span>${sub}</span></div><div class="set-btns">${btns}</div></div>`

  function yocalBlock(st) {
    const loaded = st.gemma ? modelRow('gemma 4 (26B/4B MoE, 4-bit)', true, 'cached · Gemma terms allow commercial output') : ''
    const more = `<details class="set-more"><summary>+ add or pull a model · locate engine</summary>
      <div class="set-more-body">
        <button class="set-btn set-quiet set-locate" data-locate="1">📁 locate the engine folder</button>
        ${btn('yocal-install', 'install / repair MLX', 'set-quiet')}
        ${modelRow('Qwen 2.5 7B', st.qwen, 'Apache-2.0 — cleanest license, sell freely · pull wiring next')}
        ${modelRow('Mistral 7B', st.mistral, 'Apache-2.0 — clean · pull wiring next')}
        ${add('llm', '+ upload your own GGUF / MLX model')}
      </div></details>`
    // BOTH buttons, always, each named for exactly what it does — the dot tells you which one you want.
    // One button with two meanings saves a few pixels and costs you the ability to say what you want out loud.
    const controls = btn('yocal-start', 'start', '', 'start yocal') + btn('yocal-stop', 'stop', 'set-quiet', 'stop yocal — releases about 8 GB')
    return `<div class="set-block" data-block="yocal">${rowHTML('set-dot-yocal', 'yocal — words', 'a local text model (MLX). the loyal local. holds ~8 GB while it runs — stop it when you need the RAM.', controls)}${loaded}${more}</div>`
  }

  // ── THE SMOKE TEST (Sum 2026-07-23: "add smoke test to yocal settings in gear") — the device
  //    profiler's first button. DRY-FIRE: the local model gets 5 real cue cards (one per rung) and
  //    we grade the CALLS it writes — parses · right tool · fields present · didn't parrot the
  //    example. NOTHING EXECUTES — no tool runs, no receipt, no side effects. the verdict says
  //    which rung of the ladder THIS Mac's model clears, and where to route to cloud instead. ──
  // known field-checks + hints from the four-run study; every OTHER tool grades parse + name only
  const SMOKE_KNOWN = {
    psv_toggle:   { need: ['what'],       hint: 'turn one wire off.' },
    koans:        { need: [],             hint: 'make 2, no pics.' },
    alarm_draft:  { need: ['time'],       hint: 'a 7:30am weekday alarm.' },
    psv_settings: { need: [] },
    find_replace: { need: ['old', 'new'], hint: 'swap one word in any line of an imagined page.html.' },
    psv_mute:     { need: ['word'],       hint: 'muzzle one word.' },
    nap_start:    { need: [],             hint: 'a 20 minute nap.' },
    squiggy_task: { need: ['ask'],        hint: 'ask for a tiny greet() function.' },
    psv_make:     { need: ['lane'],       hint: 'ONE piece, art false.' },
  }
  const SMOKE_SYS = 'You are a beta tester driving an app through ONE tool. Write ONE test call as pure JSON matching the template in the manual. Safe, small test values. Output ONLY the JSON object.'
  function smokeScope() {   // the pickable universe: every registered tool grouped by card, + each bot's kit
    const tools = (window.TOOLKITS && window.TOOLKITS.tools) || {}
    const cards = []; Object.keys(tools).forEach(t => { const c = tools[t].card || 'meta'; if (!cards.includes(c)) cards.push(c) })
    // grants live in AGENT_DATA (the bean the conductor reads), NOT on REG.agents — bots came up
    // empty until this read the same source as botData() (Sum 2026-07-23: "bots is showing up empty")
    const AD = window.AGENT_DATA || {}
    const bots = Object.keys(AD)
      .filter(id => Array.isArray(AD[id].tools) && AD[id].tools.length)
      .map(id => ({ id, name: AD[id].name || id, tools: AD[id].tools }))
    return { tools, cards, bots }
  }
  // two compact MULTI-SELECT dropdowns (Sum 2026-07-23: "borrowed from clock settings" — the
  //   compact-dropdowns-save-a-line rule): cards + bots, both checkable, scope = the UNION.
  function mselHTML(kind, label, items, allRow) {
    const rows = (allRow ? [`<label class="set-msel-row"><input type="checkbox" value="all" checked> all</label>`] : [])
      .concat(items.map(i => `<label class="set-msel-row"><input type="checkbox" value="${i.v}"> ${i.n}</label>`)).join('')
    return `<details class="set-msel" data-msel="${kind}"><summary>${label} · ${allRow ? 'all' : 'none'} ▾</summary><div class="set-msel-list">${rows}</div></details>`
  }
  function smokeBlock() {
    const { cards, bots } = smokeScope()
    return `<div class="set-block" data-block="smoke">
      ${rowHTML('set-dot-smoke', 'smoke test — the ladder', 'dry-fires real cue cards at the local model and grades the CALLS it writes. runs nothing. pick cards, bots, or all.', '<button class="set-btn set-smoke-go">go</button>')}
      <div class="set-smoke-scope">
        ${mselHTML('cards', 'cards', cards.map(c => ({ v: c, n: c })), true)}
        ${mselHTML('bots', 'bots', bots.map(b => ({ v: b.id, n: b.name || b.id })), false)}
      </div>
      <div class="set-smoke-out"></div>
    </div>`
  }
  function smokeRoster(scope) {
    const { tools, bots } = smokeScope()
    const picked = kind => Array.from(scope.querySelectorAll(`.set-msel[data-msel="${kind}"] input:checked`)).map(i => i.value)
    const pc = picked('cards'), pb = picked('bots')
    const ids = new Set()
    if (pc.includes('all') || (!pc.length && !pb.length)) Object.keys(tools).forEach(t => ids.add(t))
    else pc.forEach(c => Object.keys(tools).forEach(t => { if ((tools[t].card || 'meta') === c) ids.add(t) }))
    pb.forEach(id => { const b = bots.find(x => x.id === id); ((b && b.tools) || []).forEach(t => { if (tools[t]) ids.add(t) }) })
    return Array.from(ids)
  }
  // ── the HEADLESS CORE — one engine for the gear button AND the smoke_test tool bean (Sum
  //    2026-07-23: "smoke test hands… full circle economy"). ids in → graded rows out. ──
  window.SMOKE_SCOPE = smokeScope
  window.SMOKE_RUN = async function (ids, onRow) {
    if (!(await up('http://127.0.0.1:8080'))) return { err: 'yocal is not running — start it in the gear first.' }
    const { tools } = smokeScope()
    const rows = []
    for (const id of ids) {
      const c = Object.assign({ id, card: (tools[id] && tools[id].card) || 'meta', need: [] }, SMOKE_KNOWN[id] || {})
      const bean = window.TOOL_USE && window.TOOL_USE[id]
      let verdict = ''
      if (!bean || !bean.clue) verdict = '✗ no cue card registered'
      else try {
        const body = { model: 'mlx-community/gemma-4-26b-a4b-it-4bit', max_tokens: 300, temperature: 0.2,
          messages: [{ role: 'system', content: SMOKE_SYS }, { role: 'user', content: bean.clue + (c.hint ? '\n\ntest focus: ' + c.hint : '') }] }
        const r = await fetch('http://127.0.0.1:8080/v1/chat/completions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) })
        const j = await r.json()
        let txt = String((j.choices && j.choices[0] && j.choices[0].message && j.choices[0].message.content) || '')
        txt = txt.replace(/^```\w*\n?|\n?```$/g, '').trim()
        let call = null
        try { call = JSON.parse(txt) } catch (_) { const m = /\{[\s\S]*\}/.exec(txt); if (m) { try { call = JSON.parse(m[0]) } catch (_) {} } }
        if (!call) verdict = '✗ wrote prose, not a call'
        else if (call.tool !== id) verdict = `✗ reached for "${call.tool || '?'}"`
        else if (c.need.some(f => call[f] == null || call[f] === '')) verdict = `✗ left out ${c.need.join(' / ')}`
        else if (id === 'find_replace' && /const speed = 4/.test(String(call.old || ''))) verdict = '⚠ parroted the manual\'s example'
        else verdict = '✓'
      } catch (e) { verdict = '✗ ' + String((e && e.message) || e).slice(0, 40) }
      rows.push({ id, card: c.card, verdict })
      if (onRow) try { onRow(rows) } catch (_) {}
    }
    const ok = rows.filter(r => r.verdict === '✓').length
    const bad = rows.filter(r => r.verdict !== '✓').map(r => r.id)
    return { rows, ok, bad, line: `${ok}/${rows.length} clear${bad.length ? ' — route ' + bad.join(' · ') + ' to a bigger model or cloud' : ' — the whole scope. this machine is the datacenter.'}` }
  }
  async function smokeLocal(scope) {
    const out = scope.querySelector('.set-smoke-out'); if (!out) return
    const ids = smokeRoster(scope)
    if (!ids.length) { out.innerHTML = '<div class="set-note">nothing in scope — pick cards or bots.</div>'; return }
    const paint = (rows, note) => { out.innerHTML = rows.map(r =>
      `<div class="set-model"><span class="set-mname">${r.card} · ${r.id}</span><span class="set-mnote">${r.verdict}</span></div>`).join('') + (note ? `<div class="set-note">${note}</div>` : '') }
    out.innerHTML = '<div class="set-note">striking — the model writes, the code grades.</div>'
    const res = await window.SMOKE_RUN(ids, rows => paint(rows, 'striking…'))
    if (res.err) { out.innerHTML = `<div class="set-note">${res.err}</div>`; return }
    paint(res.rows, res.line)
  }

  async function refresh(scope) {
    const yo = await up('http://127.0.0.1:8080')
    const set = (sel, on) => scope.querySelectorAll(sel).forEach(d => { d.className = 'set-dot ' + (on ? 'on' : 'off') + ' ' + sel.slice(1); d.title = on ? 'running' : 'off' })
    set('.set-dot-yocal', yo)
  }
  function flash(node, msg) {
    const blk = node.closest('.set-block') || node.parentNode; let n = blk.querySelector('.set-flash')
    if (!n) { n = document.createElement('div'); n.className = 'set-flash'; blk.appendChild(n) }
    n.textContent = msg; clearTimeout(n._t); n._t = setTimeout(() => { n.textContent = '' }, 6000)
  }
  function wire(scope, rerender) {
    const native = !!TAURI()
    scope.querySelectorAll('.set-btn').forEach(b => b.addEventListener('click', async () => {
      if (b.dataset.locate) return   // the locate button has its own handler below
      if (!native) { flash(b, 'works in the totoII app only'); return }
      const old = b.textContent; b.disabled = true; b.textContent = '…'
      const r = await runEngine(b.dataset.act)
      b.disabled = false; b.textContent = old
      flash(b, r.err ? 'error: ' + r.err.slice(0, 40) : (r.out || 'done'))
      setTimeout(() => refresh(scope), 1500)
      if (/pull|install/.test(b.dataset.act)) setTimeout(rerender, 4000)   // re-check disk → the download button may now be gone
    }))
    // the smoke — two multi-select dropdowns: "all" is exclusive in cards; summaries carry the count
    scope.querySelectorAll('.set-msel').forEach(d => d.addEventListener('change', e => {
      const boxes = Array.from(d.querySelectorAll('input'))
      const allBox = boxes.find(b => b.value === 'all')
      if (allBox && e.target === allBox && allBox.checked) boxes.forEach(b => { if (b !== allBox) b.checked = false })
      else if (allBox && e.target !== allBox && e.target.checked) allBox.checked = false
      const on = boxes.filter(b => b.checked)
      const label = d.dataset.msel
      const word = on.some(b => b.value === 'all') ? 'all' : (on.length ? on.length : 'none')
      const s = d.querySelector('summary'); if (s) s.textContent = `${label} · ${word} ▾`
    }))
    const sgo = scope.querySelector('.set-smoke-go')
    if (sgo) sgo.addEventListener('click', async () => {
      sgo.disabled = true; const old = sgo.textContent; sgo.textContent = '…'
      try { await smokeLocal(scope) } finally { sgo.disabled = false; sgo.textContent = old }
    })
    // +upload — bring your own model/LoRA. needs the Tauri file dialog (next wire); honest stub for now.
    scope.querySelectorAll('.set-add').forEach(b => b.addEventListener('click', () =>
      flash(b, 'point at a local .safetensors — file-picker wiring is the next build')))
    // 📁 the one-button onboarding — locate the engine folder via a native picker. saved by Rust (survives a
    // folder move / a fresh Mac); run_engine reads that saved path first. half the finish line, one click.
    scope.querySelectorAll('[data-locate]').forEach(b => b.addEventListener('click', async () => {
      if (!native) { flash(b, 'works in the totoII app only'); return }
      const old = b.textContent; b.disabled = true; b.textContent = '…'
      try { const p = await window.__TAURI__.core.invoke('pick_engine_dir'); flash(b, p ? '✓ found: ' + p : 'cancelled'); if (p) setTimeout(rerender, 600) }
      catch (e) { flash(b, String(e).slice(0, 80)) }
      b.disabled = false; b.textContent = old
    }))
  }

  window.ozEngines = {
    async renderInto(el, only) {
      only = only || 'all'
      const native = !!TAURI()
      el.innerHTML = `<div class="set-body" style="padding:4px 0"><div class="set-note">checking what's on disk…</div></div>`
      const st = native ? await status() : {}
      const parts = []
      if (only === 'all') parts.push(`<div class="set-head">your local engine — yocal (words) runs on THIS Mac. no key, no cloud, nothing leaves the machine.</div>`)
      if (only !== 'miraigen') parts.push(yocalBlock(st), smokeBlock())
      parts.push(`<div class="set-note">${native
        ? 'downloaded models show “ready” — their download button only appears if a model goes missing. the picker only ever lists free, commercially-clean models (free to run AND to SELL the output).'
        : '⚠ these run the native engines — open the totoII app to use them.'}</div>`)
      el.innerHTML = `<div class="set-body" style="padding:4px 0">${parts.join('')}</div>`
      const rerender = () => this.renderInto(el, only)
      wire(el, rerender); refresh(el)
      if (el._ozTimer) clearInterval(el._ozTimer)
      el._ozTimer = setInterval(() => { if (document.body.contains(el)) refresh(el); else clearInterval(el._ozTimer) }, 4000)
    },
  }
})()
