// clock-main.js — the clock card's inline boot script, lifted verbatim out of clock.html
//   (IC chunk pass, Sum 2026-07-20). loads at the SAME spot it was inline (after the layout
//   markup, before the lb-*.js modules) so the DOM + load order are unchanged.
// ── flip clock ────────────────────────────────────────────

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   flip clock .................................... search: "flip clock"
//   split-flap for date row ....................... search: "split-flap for date row"
//   geolocation — one chain, lifted to geo.js ..... search: "geolocation — one"
//   weather ....................................... search: "weather"
//   solar rise/set ................................ search: "solar rise/set"
//   lunar rise/set ................................ search: "lunar rise/set"
//   air quality ................................... search: "air quality"
//   BIC state — reads from light bar .............. search: "BIC state — reads from"
//   BIC — seconds precision, 1s tick .............. search: "BIC — seconds"
//   widget visibility — reads clock-widgets ....... search: "widget visibility"
//   widget order — reads clock-widget-order ....... search: "widget order — reads"
//   center bar order — reads clock-widget-order ... search: "center bar order"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the clock card's real-time display
//    **logic and data fetching. It owns the window exports: `window.clockBars` (weather/solar/air
//    **data for hero bars), `window._sunRise`, `window._sunSet` (solar times),
//    **`window.applyTheme()` (theme switching), and the localStorage keys `clock-widgets`,
//    **`clock-widget-order`, `clock-theme`, `clock-solar`.
//
//    **TOUCH HERE** —
//    - Change flip-clock digit display format → `tick()` L27
//    - Change date row text (day/month names) → `DAYS_FULL` L45, `MONTHS_FULL` L46
//    - Change weather API fields or units → `fetchWeather()` L135 (URL construction L139–148)
//    - Change solar/lunar/air quality fetch intervals → `setInterval()` calls L356, L357, L380,
//    - L434
//    - Change BIC state names or timing logic → `updateBic()` L469, `states` array L487–492
//    - Change widget visibility defaults → `applyWidgetState()` L517
//    - Change theme options → `clockTheme` L586, `window.applyTheme()` L589
//    - Change moon phase calculation → `daysSince` L156, `moonIdx` L157
//    - Change rain/UV/snow display thresholds → `setW()` calls L191–239, L271–275
//
//    **TRAPS** —
//    - `window._ttLock` (L101) is set by `lb-timejump.js`; removing this check breaks time-jump
//    - pause.
//    - `window.clockBars` shape (L246–265, L333–334, L375–376, L423–430) is read by
//    - `renderClockBars()` (L266, L335, L377, L431); changing keys silently breaks hero bars.
//    - `localStorage` keys `clock-widgets`, `clock-widget-order`, `clock-theme`, `clock-solar` are
//    - persisted user state; renaming orphans saved settings.
//    - `window.WX_ICON`, `window.WX_DESC`, `window.WX_IMG`, `window.WX_GLYPH`, `window.WX_IMG_BASE`
//    - (L120–121, L158, L165, L285–286) are injected by `wx-icons.js`; missing them silently falls
//    - back to emoji.
//    - `window.wxDerive` methods (L212, L228, L245, L312, L369, L417) are injected by
//    - `wx-derive.js`; calling undefined methods crashes.
//    - `window.geo.coords()` (L114) is injected by `geo.js`; missing it crashes `_getGeo()`.
//    - `_sfVal` property (L59, L83–86) is stored on DOM elements; do not rename or the split-flap
//    - flip detection breaks.
//    - `tick()` and `updateDate()` run on 1s and 60s intervals (L42, L108); changing interval
//    - timing affects display responsiveness.
//    - `fetchWeather()` must complete before `setW()` is called (L179); `setW` is defined inside
//    - `fetchWeather()` (L179–189) and reused for air quality (L392–402) — two separate
//    - implementations.
//
//    **DO NOT** —
//    - Do not rename `digits`, `prev`, `sfDay`, `sfMon`, `sfD`, `sfYr` — they are referenced across
//    - multiple functions.
//    - Do not change the 600ms flip animation duration (L25, L78) without updating CSS.
//    - Do not move the `Promise.all()` call (L436) earlier; it must run after all fetch functions
//    - are defined.
//    - Do not add new localStorage keys without documenting them in the settings page.
//    - Do not change the `_toSec()` / `_fmtSec()` format (L456–467) without updating BIC display
//    - expectations.
//    - Do not move geolocation, weather, solar, lunar, or air quality logic to this file — they
//    - belong in separate modules if they grow.
//    - Do not add DOM queries for elements that may not exist without null checks (see L180–181,
//    - L393–394 pattern).
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

const digits = {
  h0: document.getElementById('h0'),
  h1: document.getElementById('h1'),
  m0: document.getElementById('m0'),
  m1: document.getElementById('m1'),
}
let prev = { h0: null, h1: null, m0: null, m1: null }

function buildStatic(el, n) {
  el.innerHTML = `<div class="card-top"><div class="face">${n}</div></div>
                  <div class="card-bot"><div class="face">${n}</div></div>`
}
function flip(el, oldN, newN) {
  el.innerHTML = `<div class="card-top"><div class="face">${newN}</div></div>
                  <div class="card-bot"><div class="face">${newN}</div></div>`
  const ft = document.createElement('div'); ft.className = 'flap-top'
  ft.innerHTML = `<div class="face">${oldN}</div>`
  const fb = document.createElement('div'); fb.className = 'flap-bot'
  fb.innerHTML = `<div class="face">${newN}</div>`
  el.appendChild(ft); el.appendChild(fb)
  setTimeout(() => { ft.remove(); fb.remove() }, 600)
}
function tick() {
  const now = new Date()
  let h = now.getHours() % 12 || 12
  const cur = {
    h0: String(Math.floor(h / 10)),
    h1: String(h % 10),
    m0: String(Math.floor(now.getMinutes() / 10)),
    m1: String(now.getMinutes() % 10),
  }
  Object.keys(cur).forEach(k => {
    if (prev[k] === null) buildStatic(digits[k], cur[k])
    else if (cur[k] !== prev[k]) flip(digits[k], prev[k], cur[k])
  })
  prev = { ...cur }
}
tick(); setInterval(tick, 1000)

// ── split-flap for date row ───────────────────────────────
const DAYS_FULL   = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
const MONTHS_FULL = ['January','February','March','April','May','June',
                     'July','August','September','October','November','December']

const SF_H     = 72
const SF_WORD  = 46
const SF_DIGIT = 52
const SF_WIDTHS = { day: 269, month: 292, d: 135, yr: 247 }

function _sfMake(w, fontSize) {
  const el = document.createElement('div')
  el.className = 'sf'
  el.style.width = w + 'px'
  el.style.height = SF_H + 'px'
  el._sfVal    = null
  el._sfFontSz = fontSize
  return el
}

function _sfDraw(el, val) {
  el.innerHTML = `
    <div class="sf-top"><div class="sf-face" style="font-size:${el._sfFontSz}px">${val}</div></div>
    <div class="sf-bot"><div class="sf-face" style="font-size:${el._sfFontSz}px">${val}</div></div>
  `
}

function _sfFlip(el, oldVal, newVal) {
  _sfDraw(el, newVal)
  const ft = document.createElement('div'); ft.className = 'sf-flap-top'
  ft.innerHTML = `<div class="sf-face" style="font-size:${el._sfFontSz}px">${oldVal}</div>`
  const fb = document.createElement('div'); fb.className = 'sf-flap-bot'
  fb.innerHTML = `<div class="sf-face" style="font-size:${el._sfFontSz}px">${newVal}</div>`
  el.appendChild(ft); el.appendChild(fb)
  setTimeout(() => { ft.remove(); fb.remove() }, 600)
}

function _sfSet(el, val) {
  const v = String(val)
  if (el._sfVal === null) { _sfDraw(el, v); el._sfVal = v; return }
  if (el._sfVal === v) return
  _sfFlip(el, el._sfVal, v)
  el._sfVal = v
}

const dateRow = document.getElementById('date-row')
const sfDay = _sfMake(SF_WIDTHS.day,   SF_WORD)
const sfMon = _sfMake(SF_WIDTHS.month, SF_WORD)
const sfD   = _sfMake(SF_WIDTHS.d,     SF_DIGIT)
const sfYr  = _sfMake(SF_WIDTHS.yr,    SF_DIGIT)

dateRow.appendChild(sfDay)
dateRow.appendChild(sfMon)
dateRow.appendChild(sfD)
dateRow.appendChild(sfYr)

function updateDate() {
  if (window._ttLock) return   // the traveler holds the date while jumped (lb-timejump.js)
  const now = new Date()
  _sfSet(sfDay, DAYS_FULL[now.getDay()])
  _sfSet(sfMon, MONTHS_FULL[now.getMonth()])
  _sfSet(sfD,   String(now.getDate()))
  _sfSet(sfYr,  String(now.getFullYear()))
}
updateDate(); setInterval(updateDate, 60000)

// ── geolocation — one chain, lifted to geo.js ────────────
// _getGeo keeps its {lat,lon} shape for the four callers below.
// the IP chain + 24h cache now live once, in geo.js.
function _getGeo() {
  const [lat, lon] = window.geo.coords()
  return Promise.resolve({ lat, lon })
}

// ── weather ───────────────────────────────────────────────
// weather-code tables → wx-icons.js (one source, complete WMO set)
const WX_ICON = window.WX_ICON
const WX_DESC = window.WX_DESC

const overlay = document.getElementById('detail-overlay')
document.getElementById('d-close').addEventListener('click', () => overlay.classList.remove('open'))
overlay.addEventListener('click', e => { if (e.target === overlay) overlay.classList.remove('open') })

function showDetail(label, icon, temp, desc) {
  document.getElementById('d-day').textContent  = label
  document.getElementById('d-icon').innerHTML = icon   // WX_IMG png html (emoji fallback still renders)
  document.getElementById('d-temp').textContent = temp
  document.getElementById('d-desc').textContent = desc
  overlay.classList.add('open')
}

async function fetchWeather() {
  try {
    const { lat, lon } = await _getGeo()

    const url = `https://api.open-meteo.com/v1/forecast`
      + `?latitude=${lat}&longitude=${lon}`
      + `&current=temperature_2m,weathercode,relative_humidity_2m,apparent_temperature`
      + `,windspeed_10m,winddirection_10m,windgusts_10m,dewpoint_2m`
      + `,cloudcover,visibility,surface_pressure,precipitation,is_day`
      + `&minutely_15=precipitation,precipitation_probability`   // 15-min resolution — "rain in the next hour", finer than hourly
      + `&hourly=precipitation_probability,uv_index,snow_depth`
      + `&daily=weathercode,temperature_2m_max,temperature_2m_min`
      + `,precipitation_probability_max,precipitation_sum`
      + `&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=8`

    const d   = await fetch(url).then(r => r.json())
    const row = document.getElementById('forecast-row')
    row.innerHTML = ''

    const MOON_PNGS  = ['moon-new.png','moon-waxcres.png','moon-firstq.png','moon-waxgib.png',
                        'moon-full.png','moon-wangib.png','moon-lastq.png','moon-wancres.png']
    const daysSince  = (Date.now() - new Date('2000-01-06').getTime()) / 86400000
    const moonIdx    = Math.round((daysSince % 29.53) / 29.53 * 8) % 8
    const WXB = window.WX_IMG_BASE || '../../shell/icons/'
    document.getElementById('moon-icon').src = WXB + MOON_PNGS[moonIdx]

    const curTemp = Math.round(d.current.temperature_2m)
    const curCode = d.current.weathercode
    const curRain = d.daily?.precipitation_probability_max?.[0]
    document.getElementById('wx-icon').innerHTML =
      (window.WX_IMG && window.WX_IMG(curCode, curRain)) || (window.WX_GLYPH ? window.WX_GLYPH(curCode) : (WX_ICON[curCode] || '⛅'))
    document.getElementById('wx-temp').textContent = curTemp + '°'
    // defer to setW after it's defined below

    const c = d.current
    const el = id => document.getElementById(id)
    const rt = v => Math.round(v)
    // set value + show/hide the parent aq-box
    // respects clock-widgets settings — never un-hides a disabled widget
    let _cwCache = null
    const cwEnabled = w => {
      if (!_cwCache) try { _cwCache = JSON.parse(localStorage.getItem('clock-widgets')||'{}') } catch { _cwCache = {} }
      return _cwCache[w] !== false
    }
    const setW = (id, val) => {
      const node = el(id)
      if (!node) return
      node.textContent = val ?? '—'
      const box = node.closest('[data-widget]')
      if (!box) return
      const widget = box.dataset.widget
      const hasData = val != null && val !== ''
      const enabled = cwEnabled(widget)
      box.style.display = (hasData && enabled) ? '' : 'none'
    }

    setW('aq-hum',  c?.relative_humidity_2m != null ? Math.round(c.relative_humidity_2m) + '%'  : null)
    setW('aq-feel', c?.apparent_temperature != null ? Math.round(c.apparent_temperature) + '°'   : null)
    setW('aq-wind', c?.windspeed_10m        != null ? Math.round(c.windspeed_10m) + ' mph'       : null)
    setW('aq-rain', d.daily?.precipitation_probability_max?.[0] != null ? d.daily.precipitation_probability_max[0] + '%' : null)
    setW('aq-dp',   c?.dewpoint_2m      != null ? rt(c.dewpoint_2m) + '°'                   : null)
    setW('aq-gust', c?.windgusts_10m    != null ? rt(c.windgusts_10m) + ' mph'               : null)
    setW('aq-cld',  c?.cloudcover       != null ? rt(c.cloudcover) + '%'                     : null)
    setW('aq-vis',  c?.visibility       != null ? Math.round(c.visibility / 1609) + ' mi'    : null)
    setW('aq-hpa',  c?.surface_pressure != null ? rt(c.surface_pressure)                     : null)

    const precipSum = d.daily?.precipitation_sum?.[0]
    setW('aq-prcp', precipSum != null ? (precipSum > 0 ? precipSum.toFixed(1) + 'mm' : null) : null)

    // hourly: rain windows + uv peak + snow depth — math in wx-derive.js
    // ⚠ this fetch is 8 DAYS of hourly (192 entries, hour 0 = midnight today) —
    //   absolute hour labels overflow ("49PM" bug); RELATIVE time is honest
    //   at any distance, so rain timing scans the whole range (Sum 2026-07-15)
    if (d.hourly) {
      const nowH = new Date().getHours()

      // rain timing — next window ≥ 30%, as "in 3h for 2h" / "now for 2h"
      const wins = window.wxDerive.rainWindows(d.hourly.precipitation_probability, nowH)
      if (wins.length) {
        const [start, end] = wins[0]
        const nowMin = nowH * 60 + new Date().getMinutes()
        if (start * 60 <= nowMin) {
          setW('aq-hrrain', `now for ${end + 1 - nowH}h`)
        } else {
          const dm = start * 60 - nowMin
          const lead = dm < 100 ? dm + 'm' : dm < 36 * 60 ? Math.round(dm / 60) + 'h' : Math.round(dm / 1440) + 'd'
          setW('aq-hrrain', `in ${lead} for ${end - start + 1}h`)
        }
      } else {
        setW('aq-hrrain', null)  // no rain in the whole forecast — hide widget
      }

      // uv peak — today's, on the 24h clock
      const { idx: peakI, val: peakV } = window.wxDerive.uvPeak((d.hourly.uv_index || []).slice(0, 24))
      if (peakV != null) {
        setW('aq-uvpeak', rt(peakV))
        setW('aq-uvtime', String(peakI % 24).padStart(2, '0') + ':00')
      } else {
        setW('aq-uvpeak', null)
        setW('aq-uvtime', null)
      }

      // snow depth — hide when 0
      const snow = d.hourly.snow_depth?.[nowH] ?? 0
      setW('aq-snow', snow > 0 ? Math.round(window.wxDerive.snowInches(snow)) + '″' : null)
    }

    // expose for the tiles/overlay (window.WX bridge)
    window.clockBars = window.clockBars || {}
    const nowH2  = new Date().getHours()
    const { idx: pkI, val: pkV } = window.wxDerive.uvPeak((d.hourly?.uv_index || []).slice(0, 24))
    window.clockBars.weather = {
      temp:       curTemp,
      code:       curCode,
      feels:      c?.apparent_temperature != null ? Math.round(c.apparent_temperature) : null,
      humidity:   c?.relative_humidity_2m != null ? Math.round(c.relative_humidity_2m) : null,
      dewpoint:   c?.dewpoint_2m          != null ? Math.round(c.dewpoint_2m)           : null,
      wind:       c?.windspeed_10m        != null ? Math.round(c.windspeed_10m)         : null,
      windDir:    c?.winddirection_10m    ?? null,
      windGusts:  c?.windgusts_10m        != null ? Math.round(c.windgusts_10m)         : null,
      pressure:   c?.surface_pressure     != null ? Math.round(c.surface_pressure)      : null,
      rain:       d.daily?.precipitation_probability_max?.[0] ?? null,
      precipSum:  d.daily?.precipitation_sum?.[0] ?? null,
      isDay:      c?.is_day,
      cloudcover: c?.cloudcover           != null ? Math.round(c.cloudcover)            : null,
      visibility: c?.visibility           != null ? c.visibility                        : null,
      uv:         d.hourly?.uv_index?.[nowH2]     ?? null,
      uvPeakVal:  pkV,
      uvPeakHour: pkV != null ? String(pkI % 24).padStart(2, '0') + ':00' : null,   // military — the face is 24h
      snowNow:    d.hourly?.snow_depth?.[nowH2] > 0 ? Math.round(window.wxDerive.snowInches(d.hourly.snow_depth[nowH2])) : null,
    }
    if (typeof renderClockBars === 'function') renderClockBars()

    // live tile icons — decile-true rain, barometer by pressure, sky by cloud cover
    const _ico = (id, f) => { const n = document.getElementById(id); if (n && f) n.src = WXB + f }
    const _dec = p => Math.max(10, Math.min(100, Math.round(p / 10) * 10))
    if (curRain != null) _ico('aq-rain-ico', curRain > 0 ? 'wx/overcast-rain-' + _dec(curRain) + '.png' : 'wx/overcast.png')
    const _hpa = c?.surface_pressure
    if (_hpa != null) _ico('aq-hpa-ico', _hpa > 1020 ? 'wx/pressure-high.png' : _hpa < 1000 ? 'wx/pressure-low.png' : 'wx/pressure-mid.png')
    const _cc = c?.cloudcover
    if (_cc != null) _ico('aq-cld-ico', _cc < 10 ? 'wx/mainly-clear.png' : _cc < 30 ? 'wx/partly.png' : _cc < 70 ? 'wx/mostly-cloudy.png' : 'wx/overcast.png')

    const days  = d.daily.time
    const hi    = d.daily.temperature_2m_max
    const lo    = d.daily.temperature_2m_min
    const codes = d.daily.weathercode

    days.forEach((iso, i) => {
      const date  = new Date(iso + 'T12:00:00')
      const label = DAYS_FULL[date.getDay()]
      const icon  = (window.WX_IMG && window.WX_IMG(codes[i], d.daily?.precipitation_probability_max?.[i]))
                    || (window.WX_GLYPH ? window.WX_GLYPH(codes[i]) : (WX_ICON[codes[i]] || '?'))
      const desc  = WX_DESC[codes[i]]  || ''
      const hiN   = Math.round(hi[i])
      const loN   = Math.round(lo[i])
      const card  = document.createElement('div')
      card.className = 'fc-card'
      card.innerHTML = `<div class="fc-top">
                          <div class="fc-day">${label.slice(0,3)}</div>
                          <div class="fc-icon">${icon}</div>
                        </div>
                        <div class="fc-temp">${hiN}° / ${loN}°</div>`
      card.addEventListener('click', () => showDetail(label, icon, `${hiN}° / ${loN}°`, desc))
      row.appendChild(card)
    })
  } catch (err) { console.warn('weather failed', err) }
}
setInterval(fetchWeather, 10 * 60 * 1000)

// ── solar rise/set ────────────────────────────────────────
async function fetchSolar() {
  try {
    const { lat, lon } = await _getGeo()
    const url = `https://api.open-meteo.com/v1/forecast`
      + `?latitude=${lat}&longitude=${lon}`
      + `&daily=sunrise,sunset&timezone=auto&forecast_days=1`
    const d   = await fetch(url).then(r => r.json())
    const fmt = window.wxDerive.fmtClock
    if (d.daily?.sunrise?.[0]) {
      document.getElementById('sol-rise').textContent = fmt(d.daily.sunrise[0])
      window._sunRise = new Date(d.daily.sunrise[0])
    }
    if (d.daily?.sunset?.[0]) {
      document.getElementById('sol-set').textContent = fmt(d.daily.sunset[0])
      window._sunSet = new Date(d.daily.sunset[0])
    }
    // share with light bar (same origin — iframe shares localStorage)
    if (window._sunRise && window._sunSet) {
      const _toHHMM = d => `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`
      localStorage.setItem('clock-solar', JSON.stringify({
        rise: _toHHMM(window._sunRise),
        set:  _toHHMM(window._sunSet),
        ts:   Date.now(),
      }))
    }
    // expose for hero bars
    window.clockBars = window.clockBars || {}
    window.clockBars.sky = window.clockBars.sky || {}
    window.clockBars.sky.sunrise = d.daily?.sunrise?.[0] ? fmt(d.daily.sunrise[0]) : null
    window.clockBars.sky.sunset  = d.daily?.sunset?.[0]  ? fmt(d.daily.sunset[0])  : null
    if (typeof renderClockBars === 'function') renderClockBars()

    updateSunArc()
  } catch(e) { console.warn('solar fetch failed', e) }
}

function updateSunArc() {
  const fill = document.getElementById('sun-fill')
  const dot  = document.getElementById('sun-dot')
  if (!fill || !dot || !window._sunRise || !window._sunSet) return
  const now  = Date.now()
  const rise = window._sunRise.getTime()
  const set  = window._sunSet.getTime()
  const span = set - rise
  if (span <= 0) return
  const pct = Math.max(0, Math.min(100, (now - rise) / span * 100))
  fill.style.width = pct + '%'
  dot.style.left   = pct + '%'   // dot is sibling — tracks correctly
}


setInterval(fetchSolar,   60 * 60 * 1000)
setInterval(updateSunArc, 60 * 1000)


// ── lunar rise/set ────────────────────────────────────────
async function fetchLunar() {
  try {
    const { lat, lon } = await _getGeo()
    const now  = new Date()
    const date = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`
    const tz   = -(now.getTimezoneOffset() / 60)
    const url  = `https://aa.usno.navy.mil/api/rstt/oneday?date=${date}&coords=${lat},${lon}&tz=${tz}`
    const d    = await fetch(url).then(r => r.json())
    const { rise, set } = window.wxDerive.usnoRiseSet(d.properties?.data?.moondata)
    if (rise) document.getElementById('lun-rise').textContent = rise
    if (set)  document.getElementById('lun-set').textContent  = set
    // expose for sky hero bar
    window.clockBars = window.clockBars || {}
    window.clockBars.sky = window.clockBars.sky || {}
    window.clockBars.sky.moonRise = rise
    window.clockBars.sky.moonSet  = set
    if (typeof renderClockBars === 'function') renderClockBars()
  } catch(e) { console.warn('lunar fetch failed', e) }
}
setInterval(fetchLunar, 60 * 60 * 1000)

// ── air quality ───────────────────────────────────────────
async function fetchAirQuality() {
  try {
    const { lat, lon } = await _getGeo()
    const url = `https://air-quality-api.open-meteo.com/v1/air-quality`
      + `?latitude=${lat}&longitude=${lon}`
      + `&current=uv_index,us_aqi,pm2_5,pm10,ozone,dust&timezone=auto`
    const d = await fetch(url).then(r => r.json())
    const c = d.current
    const rt = v => Math.round(v)
    const setW = (id, val) => {
      const node = document.getElementById(id)
      if (!node) return
      node.textContent = val ?? '—'
      const box = node.closest('[data-widget]')
      if (!box) return
      let cw = {}
      try { cw = JSON.parse(localStorage.getItem('clock-widgets')||'{}') } catch {}
      const enabled = cw[box.dataset.widget] !== false
      box.style.display = (val != null && val !== '' && enabled) ? '' : 'none'
    }
    setW('aq-uv', c?.uv_index != null ? rt(c.uv_index) : null)
    if (c?.us_aqi != null) {
      setW('aq-aqi', rt(c.us_aqi))
      const aqi = c.us_aqi
      const color = aqi<=50?'#22c55e':aqi<=100?'#eab308':aqi<=150?'#f97316':aqi<=200?'#ef4444':'#7c3aed'
      const dot = document.getElementById('aq-aqi-dot')
      if (dot) { dot.style.background = color; dot.style.boxShadow = `0 0 6px ${color}` }
    } else { setW('aq-aqi', null) }
    setW('aq-pm',   c?.pm2_5  != null ? rt(c.pm2_5)  : null)
    setW('aq-pm10', c?.pm10   != null ? rt(c.pm10)   : null)
    setW('aq-o3',   c?.ozone  != null ? rt(c.ozone)  : null)
    setW('aq-dust', c?.dust   != null ? rt(c.dust)   : null)

    // live dust grades — tile png by µg density (same ladder as the overlay)
    const _icoA = (id, f) => { const n = document.getElementById(id); if (n && f) n.src = (window.WX_IMG_BASE || '../../shell/icons/') + f }
    if (c?.pm2_5 != null) _icoA('aq-pm-ico',   c.pm2_5 < 12 ? 'wx/pm25-light.png' : c.pm2_5 < 35 ? 'wx/pm25-low.png' : c.pm2_5 < 55 ? 'wx/pm25-med.png' : c.pm2_5 < 150 ? 'wx/pm25-high.png' : 'wx/pm25-heavy.png')
    if (c?.pm10  != null) _icoA('aq-pm10-ico', c.pm10 < 54 ? 'wx/pm10-light.png' : c.pm10 < 154 ? 'wx/pm10-low.png' : c.pm10 < 254 ? 'wx/pm10-med.png' : c.pm10 < 354 ? 'wx/pm10-high.png' : 'wx/pm10-heavy.png')

    // expose for hero bars
    window.clockBars = window.clockBars || {}
    window.clockBars.air = {
      uv:    c?.uv_index != null ? rt(c.uv_index) : null,
      aqi:   c?.us_aqi   != null ? rt(c.us_aqi)   : null,
      pm25:  c?.pm2_5    != null ? rt(c.pm2_5)    : null,
      pm10:  c?.pm10     != null ? rt(c.pm10)     : null,
      ozone: c?.ozone    != null ? rt(c.ozone)    : null,
      dust:  c?.dust     != null ? rt(c.dust)     : null,
    }
    if (typeof renderClockBars === 'function') renderClockBars()
  } catch(e) { console.warn('air quality fetch failed', e) }
}
setInterval(fetchAirQuality, 30 * 60 * 1000)

Promise.all([fetchWeather(), fetchSolar(), fetchLunar(), fetchAirQuality()])

// ── BIC state — reads from light bar localStorage ────────
// scans for any lb-grp-*-bic key — works regardless of group ID



// ── widget visibility — reads clock-widgets from localStorage ─
// settings page writes: { "uv": true, "aqi": false, ... }
// clock reads on load + listens for storage events (live preview)

function applyWidgetState() {
  let state = {}
  try { state = JSON.parse(localStorage.getItem('clock-widgets') || '{}') } catch {}
  document.querySelectorAll('[data-widget]').forEach(el => {
    const id  = el.dataset.widget
    const on  = state[id] !== false   // default true if not in state
    el.style.display = on ? '' : 'none'
  })
}

// ── widget order — reads clock-widget-order from localStorage ─
// left + right zones are flex columns — DOM order = visual order
// append in saved order → items stack top-to-bottom as dragged

function applyWidgetOrder() {
  let order = {}
  try { order = JSON.parse(localStorage.getItem('clock-widget-order') || '{}') } catch {}

  const LEFT  = document.querySelector('[data-zone="left"]')
  const RIGHT = document.querySelector('[data-zone="right"]')

  // bars: all three map to top / clock / bot in drag order
  if (order['order-bars']) {
    const barSlots = ['top', 'clock', 'bot']
    order['order-bars'].forEach((id, i) => {
      const el = document.querySelector(`[data-widget="${id}"]`)
      if (el && barSlots[i]) el.style.gridArea = barSlots[i]
    })
  }

  // search whole document — widget may have crossed zones
  if (order['order-left'] && LEFT) {
    order['order-left'].forEach(id => {
      const el = document.querySelector(`[data-widget="${id}"]`)
      if (el) LEFT.appendChild(el)
    })
  }
  if (order['order-right'] && RIGHT) {
    order['order-right'].forEach(id => {
      const el = document.querySelector(`[data-widget="${id}"]`)
      if (el) RIGHT.appendChild(el)
    })
  }
}

applyWidgetOrder()
applyWidgetState()

// live update when settings page changes state
window.addEventListener('storage', e => {
  if (e.key === 'clock-widgets')      applyWidgetState()
  if (e.key === 'clock-widget-order') applyWidgetOrder()
})

// ── center bar order — reads clock-widget-order from settings ─
;(function applyCenterOrder() {
  let order = {}
  try { order = JSON.parse(localStorage.getItem('clock-widget-order') || '{}') } catch {}
  const ids = order['order-bars']
  if (!ids || !ids.length) return
  const center = document.querySelector('[data-zone="center"]')
  if (!center) return
  ids.forEach(id => {
    const el = center.querySelector(`[data-widget="${id}"]`)
    if (el) center.appendChild(el)   // moves to end in saved order
  })
})()

// expose applyTheme globally so clock-controls.js can call it
let clockTheme = (['flip','mod'].includes(localStorage.getItem('clock-theme'))
  ? localStorage.getItem('clock-theme') : null) || 'flip'

window.applyTheme = function(t) {
  clockTheme = t
  document.documentElement.setAttribute('data-theme', t)
  localStorage.setItem('clock-theme', t)
}

// restore theme on load
window.applyTheme(clockTheme)
