// cs-time.js — THE TIME-TOOLS STUDIO (Sum 2026-07-20). Build the alarms/countdowns/timers;
//   lb-time.js shows them, lb-alarm.js fires them. Now on the csChipGroups BEAN — toggle a
//   kind's chip off and its group leaves the page (Sum: "toggle off timers, customs toggle off").
// FOR AI: state in localStorage — clock-time-on · clock-alarms · clock-countdowns · clock-timers.
//   ALARM model: { time, date, days, start, end, sound, plays:'once'|'repeat',
//                  snoozeMin, snoozeMax, dismiss:'circle'|'hold'|'tap3'|'say'|'math' }
//   TIMER model: { seq:[{n,d}], unit, loop, shuffle, tone }

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   ALARMS (E = the alarm being edited, or {} ..... search: "ALARMS (E = the alarm"
//   COUNTDOWNS to a date + TIME, shown in ......... search: "COUNTDOWNS to a date +"
//   TIMERS one phase per ROW: ＋ · name · number ... search: "TIMERS one phase per"
//   STOPWATCH REBUILT 2026-07-21 as its own ....... search: "STOPWATCH REBUILT"
//   the stopwatch DISPLAY settings (Sum ........... search: "the stopwatch DISPLAY"
//   THE MASTER SWITCH, first (Sum 2026-07-21): .... search: "THE MASTER SWITCH,"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the UI that builds and edits alarms,
//    **countdowns, timers, and stopwatch settings. It owns the data models (ALARM, TIMER, COUNTDOWN
//    **shapes), persists them to localStorage keys `clock-alarms`, `clock-countdowns`,
//    **`clock-timers`, and `clock-sw-*`, and exports nothing to the window — it runs as a
//    **self-contained IIFE (line 9) that populates `#time-lists` (line 10) via the `csChipGroups`
//    **bean (line 436).
//
//    **TOUCH HERE** —
//    - Add a new field to the ALARM model → `drawAlarm()` L96; update the base object L116 and the
//    - record assembly L185–189
//    - Add a new field to the TIMER model → `drawTimer()` L245; update the record assembly L324
//    - Add a new field to the COUNTDOWN model → `drawCountdown()` L212; update the record assembly
//    - L236
//    - Change a localStorage key name → search the file for the old key (e.g., `'clock-alarms'`
//    - L117, L191, L196, L203) and update all occurrences together
//    - Add a new dismiss method → `DISMISS` array L50, then add its UI to the dismiss toggleDrop
//    - L169
//    - Change the sound picker's groups → `soundPick()` L35 reads from `TUNE().GROUPS`; change what
//    - `keep` filters L39
//    - Add a new timer phase field → `addRow()` L275; update `row._val()` L303 and the commit logic
//    - L320–324
//    - Reorder the alarm sound row → the flat flex container `ctl` L174 and its append order L176
//    - control layout; change `bar.append()` L175 to move the tone picker
//    - Change stopwatch display options → `drawStopwatch()` L379; edit the `pickStrip()` and
//    - `flagStrip()` calls L405–420
//
//    **TRAPS** —
//    - `editing` (L23) and `editingTm` (L22) are global state; navigating away without saving
//    - leaves them set, so the next edit loads the stale object back. This is intentional (L23–24
//    - comment) but means unsaved edits persist across redraw calls.
//    - localStorage keys are load-bearing: `'clock-alarms'`, `'clock-countdowns'`, `'clock-timers'`
//    - (L117, L191, L236, L327, L331) are read and written by lb-time.js and lb-alarm.js. Renaming
//    - one orphans all user data.
//    - The ALARM base object L116 must include all fields or partial drafts from the traveler
//    - (L104) will lack defaults; missing `snoozeMax: 0` breaks the snooze UI (L157).
//    - `uid()` L15 is called once per new item; if you add a second call in the same save path,
//    - duplicates will have different IDs and both will persist.
//    - The `repBox` display toggle L138 is tied to the repeat checkbox L145; hiding one without the
//    - other leaves orphaned UI.
//    - `toggleDrop()` L68 is used three ways (sound, dismiss, countdown units) with different
//    - `ordered` flags (L150, L169, L234); changing one call's flag affects only that dropdown.
//    - The timer's `curPP` L273 tracks which row's preview is playing; if you add a new preview
//    - button, you must call `stopPP()` L287 before starting a new one, or multiple sounds play at
//    - once.
//    - Line 332 computes the timer display string from `p.unit` and `t.unit` with a fallback; if
//    - you add a new unit, update both the select options L280 and this fallback logic.
//    - The draft keys (`'clock-alarm-draft'`, `'clock-countdown-draft'`, `'clock-timer-draft'`) are
//    - removed after save (L118, L223, L261); if you change the key name, old drafts will never be
//    - cleared.
//
//    **DO NOT** —
//    - Do not rename `bean` (L21, L25, L436) or the `csChipGroups` call (L436–441); that is the
//    - contract with the chip-group system that toggles tools on/off.
//    - Do not move the `redraw()` function (L25) or change its signature; it is called from event
//    - listeners throughout and must trigger a full re-render.
//    - Do not change the `host` element ID (L10); it is hardcoded in the HTML that loads this
//    - script.
//    - Do not add new localStorage reads/writes outside the three main draw functions; state that
//    - is not persisted in one of the `clock-*` keys will be lost on reload.
//    - Do not edit the sound preview logic (L42–43, L152–153, L287–292) without testing in both
//    - Chrome and WKWebView; the TUNE() API is injected by the parent frame.
//    - Do not move the flat flex layout of the alarm control row (L174–176); nested wrappers cause
//    - WebKit to stretch and misalign (L161–164 comment).
//    - Do not add new fields to the ALARM, TIMER, or COUNTDOWN models without updating lb-time.js
//    - and lb-alarm.js, which read and fire these objects.
//    - Do not change the order of the three draw functions (drawAlarm, drawCountdown, drawTimer,
//    - drawStopwatch) or the chip IDs (L439); they are matched by the `draw` map L426.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const host = document.getElementById('time-lists')
  if (!host) return
  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const S = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }
  const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 6)
  const el = (t, cls, html) => { const e = document.createElement(t); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e }
  const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  const TUNE = () => { try { return parent.CHIPTUNE || window.CHIPTUNE } catch (_) { return window.CHIPTUNE } }
  const opts = (arr, sel) => arr.map(([v, l]) => `<option value="${v}"${v === sel ? ' selected' : ''}>${l}</option>`).join('')

  let bean = null
  let editingTm = null   // the TIMER being edited — same rules as the alarm below
  let editing = null   // the alarm being edited (Sum 2026-07-20): edit loads it back into the
  //                      chooser; SAVE replaces by id; navigating away leaves the original.
  const redraw = () => bean && bean.redraw()

  function listRow(text, onDel) {
    const w = el('label', 'wg-cell lane-row', `<span class="lane-txt">${text}</span>`)
    const del = el('button', 'lane-del', 'remove')
    del.addEventListener('click', e => { e.preventDefault(); onDel(); redraw() })
    w.appendChild(del)
    return w
  }
  // a sound picker widget (▶ preview loops, ■ stops) — returns { row, value() }
  function soundPick(cur, groups) {
    const row = el('div', 'lane-genbar')
    const sel = el('select', 'loc-input lane-sel')
    const G = (TUNE() && TUNE().GROUPS) || {}
    const keep = groups || Object.keys(G)
    sel.innerHTML = keep.map(grp => `<optgroup label="${grp}">${(G[grp] || []).map(([v, l]) => `<option value="${v}"${v === cur ? ' selected' : ''}>${l}</option>`).join('')}</optgroup>`).join('')
    const play = el('button', 'loc-btn', '▶'), stop = el('button', 'loc-btn', '■')
    play.addEventListener('click', e => { e.preventDefault(); const t = TUNE(); if (t) t.play(sel.value, { loop: true }) })
    stop.addEventListener('click', e => { e.preventDefault(); const t = TUNE(); if (t) t.stop() })
    row.append(sel, play, stop)
    return { row, value: () => sel.value }
  }
  const allSounds = () => { const G = (TUNE() && TUNE().GROUPS) || {}; return Object.values(G).flat() }
  // a visible label — the dark settings theme washes out plain text, so use --muted (headers do)
  const lab = (t, bold) => { const s = el('span', 'lane-txt', t); s.style.cssText = 'flex:0 0 auto;color:var(--muted)' + (bold ? ';font-weight:bold' : ''); return s }
  const DISMISS = [['tap', 'one tap'], ['circle', 'circle the light'], ['hold', 'press & hold'], ['tap3', 'tap 3 corners'], ['math', 'solve a sum'], ['clap', 'clap'], ['repeat3', 'repeat 3 words']]
  // a compact inline on/off toggle (ramp · snooze share a line)
  const inlineToggle = (t, checked) => { const l = el('label'); l.style.cssText = 'display:inline-flex;align-items:center;gap:6px;flex:0 0 auto;color:var(--muted);font-weight:bold'; l.innerHTML = `<input type="checkbox" class="wg-check"${checked ? ' checked' : ''}> ${t}`; return l }
  // an ICON toggle — same checkbox, an inline SVG glyph instead of a word (Sum 2026-07-20:
  // "when I say draw I mean svg/css, no gen"). the svg themes, scales, animates — no asset to ship.
  const iconToggle = (svg, checked, title) => { const l = el('label'); l.title = title || ''; l.style.cssText = 'display:inline-flex;align-items:center;gap:5px;flex:0 0 auto;cursor:pointer'; l.innerHTML = `<input type="checkbox" class="wg-check"${checked ? ' checked' : ''}>${svg}`; return l }
  // the volume-SWELL glyph — THREE little emitters side by side: 1 arc, then 2, then 3, for "ramp up
  // sound" (Sum 2026-07-20: "just show 3 little icons next to each other, no animation"). same arc =
  // same colour across the three, so the outer/deep arc only appears on the loudest.
  const SWELL_SVG = `<svg class="sw-ico" viewBox="0 0 28 18" aria-hidden="true" fill="none" stroke-linecap="round" style="height:1.5em;width:auto;vertical-align:middle"><circle cx="1.5" cy="9" r="1.2" fill="#7e57c2"/><path d="M3.51 6.77 A3 3 0 0 1 3.51 11.23" stroke="#b39ddb" stroke-width="1.3"/><circle cx="10.5" cy="9" r="1.2" fill="#7e57c2"/><path d="M12.51 6.77 A3 3 0 0 1 12.51 11.23" stroke="#b39ddb" stroke-width="1.3"/><path d="M13.85 5.28 A5 5 0 0 1 13.85 12.72" stroke="#9575cd" stroke-width="1.4"/><circle cx="19.5" cy="9" r="1.2" fill="#7e57c2"/><path d="M21.51 6.77 A3 3 0 0 1 21.51 11.23" stroke="#b39ddb" stroke-width="1.3"/><path d="M22.85 5.28 A5 5 0 0 1 22.85 12.72" stroke="#9575cd" stroke-width="1.4"/><path d="M24.18 3.80 A7 7 0 0 1 24.18 14.20" stroke="#7e57c2" stroke-width="1.5"/></svg>`

  // THE TOGGLE-DROPDOWN (Sum 2026-07-20, spec'd together): a dropdown that opens to a checklist
  // you flip on/off, STAYING open while you toggle. closed it shows the ONE choice, or a COUNT
  // when more than one. ORDERED (sound · dismiss escalation) numbers picks in turn-on order; a
  // SET (countdown units) just checks them (natural order lives in the breakdown). one widget,
  // three uses — the "reformat drop downs" ask.
  // onChange (optional, 6th) fires after EVERY toggle — add or remove — for live settings that save
  // themselves (the stopwatch units). onPick stays add-only, so existing callers don't change.
  function toggleDrop(options, cur, ordered, noun, onPick, onChange) {
    const wrap = el('div'); wrap.style.cssText = 'flex:0 1 9.5em;min-width:7em;position:relative'
    const chosen = [...(cur || [])]
    const btn = el('button', 'loc-input lane-sel'); btn.style.cssText = 'width:100%;text-align:left;cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:8px'
    // the panel is a real cream MENU (contrast fix — a transparent panel left unchosen rows dark
    // on dark; Sum 2026-07-20). dark text on cream reads for chosen AND unchosen; the chosen row
    // gets a lavender wash + the number/✓.
    const panel = el('div'); panel.style.cssText = 'display:none;position:absolute;left:0;top:100%;z-index:50;margin-top:4px;min-width:100%;width:15em;border-radius:8px;padding:4px;max-height:16em;overflow:auto;background:var(--card);color:var(--text);box-shadow:0 8px 24px rgba(0,0,0,.4)'
    const labelOf = v => (options.find(o => o[0] === v) || [v, v])[1]
    const paintBtn = () => { btn.innerHTML = ''; const s = el('span'); s.style.cssText = 'flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis'; s.textContent = !chosen.length ? 'pick…' : chosen.length === 1 ? labelOf(chosen[0]) : `${chosen.length} ${noun}s`; const car = el('span'); car.textContent = '▾'; car.style.cssText = 'flex:0 0 auto;color:var(--muted)'; btn.append(s, car) }
    const paintPanel = () => {
      panel.innerHTML = ''
      options.forEach(([v, l]) => {
        const i = chosen.indexOf(v)
        const row = el('div'); row.style.cssText = 'display:flex;align-items:center;gap:8px;padding:6px 8px;cursor:pointer;border-radius:6px;color:var(--text)' + (i >= 0 ? ';background:rgba(120,90,200,.18);font-weight:bold' : '')
        const mk = el('span'); mk.style.cssText = 'width:1.5em;font-weight:bold;color:' + (i >= 0 ? 'var(--text)' : 'var(--muted)'); mk.textContent = ordered ? (i >= 0 ? (i + 1) + '.' : '○') : (i >= 0 ? '✓' : '○')
        const tx = el('span'); tx.textContent = l; row.append(mk, tx)
        row.addEventListener('click', e => { e.stopPropagation(); const j = chosen.indexOf(v); if (j >= 0) chosen.splice(j, 1); else { chosen.push(v); if (onPick) onPick(v) } paintBtn(); paintPanel(); if (onChange) onChange(chosen.slice()) })
        panel.appendChild(row)
      })
    }
    btn.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); const open = panel.style.display !== 'none'; document.querySelectorAll('.td-open').forEach(p => { p.style.display = 'none'; p.classList.remove('td-open') }); if (!open) { paintPanel(); panel.style.display = 'block'; panel.classList.add('td-open') } })
    document.addEventListener('click', () => { panel.style.display = 'none'; panel.classList.remove('td-open') })
    paintBtn(); wrap.append(btn, panel)
    return { wrap, value: () => chosen.slice() }
  }

  // ── ALARMS ── (E = the alarm being edited, or {} for a fresh one; every field pre-fills from E)
  function drawAlarm() {
    const g = el('div'); const E = editing || {}; g.dataset.tool = 'alarm'
    const repeatOn = editing ? (E.repeat || (E.days && E.days.length > 0)) : false
    g.appendChild(el('div', 'lane-group', editing ? 'EDITING ALARM' : 'ALARMS'))
    // DRAFT FROM THE TRAVELER (Sum 2026-07-21: "traveler sets an alarm and displays it in settings
    // for the user to double check and save"). The bot NEVER arms an alarm — it drafts one here; you
    // review and press save. HIL by design: bot control ends at the draft (Sum: "where bots' controls
    // end without god mode"). Saving merges the draft over a full default, so a partial draft is valid.
    const draft = J('clock-alarm-draft', 'null')
    if (draft && !editing) {
      const dv = el('div', 'tt-alarm-draft')
      const when = draft.repeat ? ((draft.days && draft.days.length) ? draft.days.map(d => DAYS[d]).join('·') : 'daily') : (draft.date || 'next ' + (draft.time || '07:00'))
      const snds = Array.isArray(draft.sound) ? draft.sound.join('→') : (draft.sound || 'tone432')
      dv.appendChild(el('div', 'tt-draft-head', '⏳ the traveler drafted an alarm — check it, then save'))
      dv.appendChild(el('div', 'tt-draft-body', `<b>${draft.time || '07:00'}</b> · ${when}${draft.label ? ' — ' + draft.label : ''} · ${snds}`))
      const row = el('div', 'lane-genbar')
      const save = el('button', 'loc-btn', '✓ save & arm')
      const disc = el('button', 'loc-btn', '✕ discard')
      save.addEventListener('click', e => {
        e.preventDefault()
        const base = { label: '', time: '07:00', repeat: false, date: '', days: [], start: '', end: '', sound: ['tone432'], ramp: true, plays: 'repeat', dismiss: ['circle'], voice: 'none', snoozeMin: 9, snoozeMax: 3 }
        const list = J('clock-alarms', '[]'); list.push(Object.assign(base, draft, { id: uid(), on: true }))
        S('clock-alarms', list); localStorage.removeItem('clock-alarm-draft'); redraw()
      })
      disc.addEventListener('click', e => { e.preventDefault(); localStorage.removeItem('clock-alarm-draft'); redraw() })
      row.append(save, disc); dv.appendChild(row); g.appendChild(dv)
    }
    const bar = el('div', 'lane-genbar')
    const label = el('input', 'loc-input'); label.placeholder = 'label (optional)'; label.value = E.label || ''
    const date = el('input', 'loc-input'); date.type = 'date'; date.style.flex = '0 0 auto'; date.value = (repeatOn ? (E.start ? '' : E.date) : E.date) || ''
    const time = el('input', 'loc-input'); time.type = 'time'; time.style.flex = '0 0 auto'; time.value = E.time || '07:00'
    const add = el('button', 'loc-btn', editing ? 'save changes' : 'add alarm')
    // Row 1 = label · date · time · TONE · play. The tone + its play toggle are built further down
    // (they share the picker's state) and appended up into this same bar afterwards.
    bar.append(label, date, time)
    g.appendChild(bar)
    // REPEAT toggle — on shows the day chips + window; off hides them.
    const repRow = el('div', 'lane-genbar'); const rep = inlineToggle('repeat on set days', repeatOn); repRow.appendChild(rep)
    repRow.appendChild(add)   // ADD ALARM lives here now (Sum 2026-07-21)
    if (editing) { const cancel = el('button', 'loc-btn', 'cancel'); cancel.addEventListener('click', e => { e.preventDefault(); editing = null; redraw() }); repRow.appendChild(cancel) }
    // NOTE: repRow + repBox are appended AFTER the control line below (Sum 2026-07-21:
    // "move repeat and add below that line of buttons that are no longer sound").
    const repBox = el('div'); repBox.style.display = repeatOn ? '' : 'none'
    const dayRow = el('div', 'lane-chips'); const daySel = new Set(repeatOn ? (E.days || []) : [])
    DAYS.forEach((d, i) => { const c = el('button', 'lane-chip' + (daySel.has(i) ? ' on' : ''), d); c.addEventListener('click', () => { daySel.has(i) ? daySel.delete(i) : daySel.add(i); c.className = 'lane-chip' + (daySel.has(i) ? ' on' : '') }); dayRow.appendChild(c) })
    const span = el('div', 'lane-genbar')
    const start = el('input', 'loc-input'); start.type = 'date'; start.style.flex = '1'; start.value = E.start || ''
    const end = el('input', 'loc-input'); end.type = 'date'; end.style.flex = '1'; end.value = E.end || ''
    span.append(lab('from', 1), start, lab('to', 1), end); repBox.append(dayRow, span)
    rep.querySelector('input').addEventListener('change', e => repBox.style.display = e.target.checked ? '' : 'none')
    // SOUND — REWRITTEN fresh (Sum 2026-07-20: the old row was fundamentally broken — WKWebView's
    // flex-wrap kept flinging dismiss to the far edge; don't salvage). ONE non-wrapping line, no
    // wrap = no phantom gap: sound · play/stop toggle · plays · voice · ramp · snooze · "N min M
    // times then" · dismiss. the "then" reads straight into the dismiss dropdown.
    const snd = toggleDrop(allSounds(), Array.isArray(E.sound) ? E.sound : (E.sound ? [E.sound] : ['tone432']), true, 'sound')
    // ONE button — play the current sound (looping), or stop whatever's playing (Sum: "one button")
    const pp = el('button', 'loc-btn', '▶ play'); let pePlaying = false
    pp.addEventListener('click', e => { e.preventDefault(); const t = TUNE(); if (!t) return; if (pePlaying) { t.stop(); pp.textContent = '▶ play'; pePlaying = false; return } t.stop(); const v = snd.value(); t.play(v[v.length - 1] || 'tone432', { loop: true }); pp.textContent = '■ stop'; pePlaying = true })
    const plays = el('select', 'loc-input lane-sel'); plays.innerHTML = opts([['once', 'plays once'], ['repeat', 'till dismissed']], E.plays || 'repeat')
    const voice = el('select', 'loc-input lane-sel'); voice.innerHTML = opts([['none', 'voice off'], ['off', 'say "off"'], ['snooze', 'say "snooze"']], E.voice || 'none')
    const ramp = iconToggle(SWELL_SVG, E.ramp !== false, 'volume swell — starts soft, rises')
    const snze0 = editing ? (E.snoozeMax > 0) : true
    const snzOn = inlineToggle('snooze', snze0)
    const snzMin = el('input', 'loc-input'); snzMin.type = 'number'; snzMin.value = E.snoozeMin || 9; snzMin.min = '1'; snzMin.style.flex = '0 0 3em'; snzMin.title = 'minutes per snooze'
    const snzMax = el('input', 'loc-input'); snzMax.type = 'number'; snzMax.value = E.snoozeMax || 3; snzMax.min = '1'; snzMax.style.flex = '0 0 3em'; snzMax.title = 'snoozes before it makes you dismiss'
    // THE SNOOZE FIELDS RIDE DIRECTLY ON THE ROW — never inside a wrapper span. a nested inline-flex
    // here STRETCHES in WKWebView (WebKit) and flings dismiss to the far edge — THE gap Sum kept
    // seeing. verified: Chrome renders it fine, qlmanage (WebKit) reproduced the stretch, flattening
    // cures it (Sum 2026-07-20: rebuilt in isolation in a browser I can inspect, THEN ported).
    const minLab = lab('min', 1), timesLab = lab('times then', 1), dismLead = lab('dismiss', 1)
    const snzEls = [snzMin, minLab, snzMax, timesLab]   // "N min M times then" → reads into dismiss
    const setSnz = on => { snzEls.forEach(x => x.style.display = on ? '' : 'none'); dismLead.style.display = on ? 'none' : '' }
    snzOn.querySelector('input').addEventListener('change', e => setSnz(e.target.checked))
    const dismiss = toggleDrop(DISMISS, Array.isArray(E.dismiss) ? E.dismiss : (E.dismiss ? [E.dismiss] : ['circle']), true, 'puzzle')
    snd.wrap.style.flex = '0 1 11em'; snd.wrap.style.minWidth = '9em'
    dismiss.wrap.style.flex = '0 1 11em'; dismiss.wrap.style.minWidth = '9em'
    // the ROW — flat flex (NO nested wrappers = WebKit-safe), and now it WRAPS to a second line when
    // the window collapses (Sum 2026-07-20). verified in qlmanage: flat + wrap = clean, no gap.
    const ctl = el('div'); ctl.style.cssText = 'display:flex;flex-wrap:wrap;align-items:center;gap:8px'
    bar.append(snd.wrap, pp)   // ← the tone rides ROW 1, in the slot add alarm vacated
    ctl.append(plays, voice, ramp, snzOn, snzMin, minLab, snzMax, timesLab, dismLead, dismiss.wrap)
    setSnz(snze0); g.appendChild(ctl)
    g.append(repRow, repBox)   // repeat + ADD ALARM sit under the control line
    add.addEventListener('click', () => {
      if (!time.value) return
      const repeat = rep.querySelector('input').checked
      let oneDate = date.value || ''
      if (!repeat && !oneDate) { const now = new Date(); const [h, m] = time.value.split(':').map(Number); const d = new Date(now); d.setHours(h, m, 0, 0); if (d <= now) d.setDate(d.getDate() + 1); oneDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
      const snds = snd.value(); const dis = dismiss.value(); const snze = snzOn.querySelector('input').checked
      const rec = { id: editing ? editing.id : uid(), label: label.value.trim(), date: repeat ? (date.value || '') : oneDate, time: time.value, repeat,
        days: repeat ? [...daySel] : [], start: repeat ? (start.value || '') : '', end: repeat ? (end.value || '') : '',
        sound: snds.length ? snds : ['tone432'], ramp: ramp.querySelector('input').checked,
        plays: plays.value, dismiss: dis.length ? dis : ['circle'], voice: voice.value,
        snoozeMin: Math.max(1, +snzMin.value || 9), snoozeMax: snze ? Math.max(1, +snzMax.value || 3) : 0, on: true }
      // EDIT replaces by id (in place); ADD appends — nav-away without saving leaves the original
      let list = J('clock-alarms', '[]')
      if (editing) list = list.map(x => x.id === editing.id ? rec : x); else list.push(rec)
      editing = null; S('clock-alarms', list); redraw()
    })
    // the saved list — each row gets EDIT + remove (Sum 2026-07-20)
    J('clock-alarms', '[]').forEach(a => {
      const when = a.date ? a.date : (a.days && a.days.length ? a.days.map(d => DAYS[d]).join('·') : 'daily')
      const snds = Array.isArray(a.sound) ? a.sound.join('→') : a.sound
      const dis = Array.isArray(a.dismiss) ? a.dismiss.join('+') : a.dismiss
      const tail = `${a.plays === 'once' ? ' · once' : ''} · ${snds} · ${dis}${a.snoozeMax ? ` · snz ${a.snoozeMin}×${a.snoozeMax}` : ' · no-snz'}`
      const w = el('label', 'wg-cell lane-row' + (editing && editing.id === a.id ? ' lane-editing' : ''), `<span class="lane-txt">${a.on === false ? '<span style="opacity:.5">off · </span>' : ''}<b>${a.time}</b> · ${when}${a.label ? ' — ' + a.label : ''}${tail}</span>`)
      const ed = el('button', 'lane-del', 'edit'); ed.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); editing = a; redraw() })
      const del = el('button', 'lane-del', 'remove'); del.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); S('clock-alarms', J('clock-alarms', '[]').filter(x => x.id !== a.id)); redraw() })
      w.append(ed, del); g.appendChild(w)
    })
    return g
  }

  // ── COUNTDOWNS ── to a date + TIME, shown in whichever units you toggle on (Sum 2026-07-20:
  //    "needs a time and date; toggle the units — just seconds, or seconds and years").
  const CD_UNITS = ['years', 'months', 'weeks', 'days', 'hours', 'minutes', 'seconds']
  function drawCountdown() {
    const g = el('div')
    g.dataset.tool = 'countdown'; g.appendChild(el('div', 'lane-group', 'COUNTDOWNS'))
    // DRAFT FROM THE TRAVELER (Sum 2026-07-21) — the bot fills it, you save it. HIL, same as the alarm.
    ;(function () {
      const draft = J('clock-countdown-draft', 'null'); if (!draft) return
      const dv = el('div', 'tt-alarm-draft')
      dv.appendChild(el('div', 'tt-draft-head', '⏳ the traveler drafted a countdown — check it, then save'))
      dv.appendChild(el('div', 'tt-draft-body', `<b>${draft.target}${draft.time && draft.time !== '00:00' ? ' ' + draft.time : ''}</b>${draft.label ? ' — ' + draft.label : ''}`))
      const row = el('div', 'lane-genbar')
      const save = el('button', 'loc-btn', '✓ save'); const disc = el('button', 'loc-btn', '✕ discard')
      save.addEventListener('click', e => { e.preventDefault(); const l = J('clock-countdowns', '[]'); l.push({ id: uid(), label: draft.label || '', target: draft.target, time: draft.time || '00:00', units: draft.units || [] }); S('clock-countdowns', l); localStorage.removeItem('clock-countdown-draft'); redraw() })
      disc.addEventListener('click', e => { e.preventDefault(); localStorage.removeItem('clock-countdown-draft'); redraw() })
      row.append(save, disc); dv.appendChild(row); g.appendChild(dv)
    })()
    const bar = el('div', 'lane-genbar')
    const label = el('input', 'loc-input'); label.placeholder = 'what you\'re counting to'
    const date = el('input', 'loc-input'); date.type = 'date'; date.style.flex = '0 0 auto'
    const time = el('input', 'loc-input'); time.type = 'time'; time.style.flex = '0 0 auto'; time.value = '00:00'
    const add = el('button', 'loc-btn', 'add countdown')
    // ONE ROW (Sum 2026-07-21: "units should fit on same row as countdown name") — name · date ·
    // time · show-it-in units · add. .lane-genbar wraps, so a narrow card folds it gracefully.
    const uSel = toggleDrop(CD_UNITS.map(u => [u, u]), ['days'], false, 'unit')
    bar.append(label, date, time, lab('show it in', 1), uSel.wrap, add); g.appendChild(bar)
    add.addEventListener('click', () => { if (!date.value) return; const l = J('clock-countdowns', '[]'); l.push({ id: uid(), label: label.value.trim(), target: date.value, time: time.value || '00:00', units: uSel.value() }); S('clock-countdowns', l); redraw() })
    J('clock-countdowns', '[]').forEach(c => g.appendChild(listRow(`<b>${c.target}${c.time && c.time !== '00:00' ? ' ' + c.time : ''}</b> · ${(c.units && c.units.length ? c.units.join('·') : c.unit || 'auto')}${c.label ? ' — ' + c.label : ''}`, () => S('clock-countdowns', J('clock-countdowns', '[]').filter(x => x.id !== c.id)))))
    return g
  }

  // ── TIMERS ── one phase per ROW: ＋ · name · number · units · sound · play/stop (Sum 2026-07-20).
  //    hit ＋ and the whole row repeats. a bottom dropdown sets repeat / shuffle / single. ONE row =
  //    poach an egg; MANY = a circuit. each phase carries its OWN unit + sound. loop & shuffle derive
  //    from the mode so lb-time.js just reads {loop, shuffle}.
  function drawTimer() {
    const g = el('div')
    // the heading carries the timer's NAME once it becomes a sequence (Sum 2026-07-21: "if more
    // than one, once plus is hit, pop open a name, above phase, right of timers word. if just
    // one, phase is its name.")
    const head = el('div', 'lane-genbar'); head.style.margin = '0'
    g.dataset.tool = 'timer'; head.appendChild(el('div', 'lane-group', 'TIMERS'))
    // DRAFT FROM THE TRAVELER (Sum 2026-07-21) — the bot fills the phases, you save it. HIL.
    ;(function () {
      const draft = J('clock-timer-draft', 'null'); if (!draft || !Array.isArray(draft.seq)) return
      const dv = el('div', 'tt-alarm-draft')
      dv.appendChild(el('div', 'tt-draft-head', '⏳ the traveler drafted a timer — check it, then save'))
      const secs = draft.seq.reduce((a, p) => a + (+p.d || 0), 0)
      dv.appendChild(el('div', 'tt-draft-body', `<b>${draft.label || 'timer'}</b> · ${draft.seq.length} phase${draft.seq.length === 1 ? '' : 's'} · ${Math.round(secs / 60 * 10) / 10} min total`))
      const row = el('div', 'lane-genbar')
      const save = el('button', 'loc-btn', '✓ save'); const disc = el('button', 'loc-btn', '✕ discard')
      save.addEventListener('click', e => { e.preventDefault(); const l = J('clock-timers', '[]'); l.push({ id: uid(), label: draft.label || '', seq: draft.seq, unit: draft.unit || 'sec', loop: !!draft.loop, shuffle: !!draft.shuffle, tone: draft.tone || 'chime' }); S('clock-timers', l); localStorage.removeItem('clock-timer-draft'); redraw() })
      disc.addEventListener('click', e => { e.preventDefault(); localStorage.removeItem('clock-timer-draft'); redraw() })
      row.append(save, disc); dv.appendChild(row); head.appendChild(dv)
    })()
    const tname = el('input', 'loc-input'); tname.placeholder = 'name this circuit'
    tname.style.cssText = 'flex:1 1 12em;display:none'
    head.appendChild(tname); g.appendChild(head)
    const syncName = () => { tname.style.display = phases.querySelectorAll('.tm-phase').length > 1 ? '' : 'none' }
    if (editingTm && editingTm.label) tname.value = editingTm.label
    const G = (TUNE() && TUNE().GROUPS) || {}
    const soundOpts = cur => ['alerts', 'holds'].map(grp => `<optgroup label="${grp}">${(G[grp] || []).map(([v, l]) => `<option value="${v}"${v === cur ? ' selected' : ''}>${l}</option>`).join('')}</optgroup>`).join('')
    const phases = el('div')
    let curPP = null   // only one preview plays at a time — the row whose ▶ is lit
    // a phase ROW: ＋ · name · number · unit · sound · play/stop-in-one-button
    const addRow = (P = {}) => {
      const row = el('div', 'lane-genbar tm-phase'); row.style.gap = '6px'
      const plus = el('button', 'loc-btn', '＋'); plus.title = 'add another phase — build a circuit'; plus.style.flex = '0 0 auto'; plus.addEventListener('click', e => { e.preventDefault(); addRow() })
      const name = el('input', 'loc-input'); name.placeholder = 'phase (optional)'; name.value = P.n || ''; name.style.flex = '1 1 7em'
      const num = el('input', 'loc-input'); num.type = 'number'; num.min = '1'; num.placeholder = 'time'; num.value = P.d || ''; num.style.flex = '0 0 4.5em'
      const unit = el('select', 'loc-input lane-sel'); unit.innerHTML = opts([['sec', 'sec'], ['min', 'min']], P.unit || 'sec'); unit.style.flex = '0 0 auto'
      // the alarm's ORDERED multi-tone picker (Sum 2026-07-21: "toggle on off for more than one
      // tone from alarms") — pick several and they play in turn at the phase end.
      const snd = toggleDrop(allSounds(), Array.isArray(P.tone) ? P.tone : (P.tone ? [P.tone] : ['beeps']), true, 'sound')
      snd.wrap.style.flex = '0 1 8.5em'; snd.wrap.style.minWidth = '7em'
      // PLAY/STOP is ONE button — click previews this row's sound (looping), click again stops
      const pp = el('button', 'loc-btn', '▶'); pp.style.flex = '0 0 auto'; pp.title = 'preview this sound'
      const stopPP = () => { const t = TUNE(); if (t) t.stop(); pp.textContent = '▶'; if (curPP === pp) curPP = null }
      pp.addEventListener('click', e => {
        e.preventDefault(); const t = TUNE(); if (!t) return
        if (curPP === pp) { stopPP(); return }
        if (curPP) { curPP.textContent = '▶' }
        t.stop(); const v = snd.value(); t.play(v[v.length - 1] || 'beeps', { loop: true }); pp.textContent = '■'; curPP = pp
      })
      // THE FIRST ROW carries SAVE (you can't remove the only interval, so that slot was dead —
      // Sum 2026-07-21: "move add timer up one row, where remove is"). Added rows carry remove.
      const first = phases.querySelectorAll('.tm-phase').length === 0
      let tail
      if (first) { tail = el('button', 'loc-btn', editingTm ? 'save timer' : 'add timer'); tail.addEventListener('click', e => { e.preventDefault(); commit() }) }
      else { tail = el('button', 'lane-del', 'remove'); tail.addEventListener('click', e => { e.preventDefault(); stopPP(); row.remove(); syncName() }) }
      const plays = el('select', 'loc-input lane-sel'); plays.style.flex = '0 0 auto'
      plays.innerHTML = opts([['once', 'plays once'], ['repeat', 'till dismissed']], P.plays || 'once')
      row.append(plus, name, num, unit, snd.wrap, pp, plays, tail)
      row._val = () => ({ n: name.value.trim(), d: parseInt(num.value, 10) || 0, unit: unit.value, tone: snd.value(), plays: plays.value })
      phases.appendChild(row); try { syncName() } catch (_) {} ; return row
    }
    if (editingTm && (editingTm.seq || []).length) editingTm.seq.forEach(p => addRow(p)); else addRow()
    g.appendChild(phases)
    // the bottom line — how the sequence runs (single at the end of the list, per Sum) + save
    const foot = el('div', 'lane-genbar')
    const curMode = editingTm ? (editingTm.shuffle ? 'shuffle' : editingTm.loop ? 'repeat' : 'single') : 'single'
    const mode = el('select', 'loc-input lane-sel'); mode.innerHTML = opts([['repeat', 'repeat'], ['shuffle', 'shuffle'], ['single', 'single']], curMode); mode.style.flex = '0 0 auto'
    // what the CARD shows while it runs — one dropdown on this same line (Sum 2026-07-21)
    const disp = el('select', 'loc-input lane-sel')
    disp.innerHTML = opts([['current', 'current'], ['next', 'current and next'], ['all', 'all']], J('clock-tm-disp', '"next"'))
    disp.addEventListener('change', () => S('clock-tm-disp', disp.value))
    foot.append(lab('run', 1), mode, lab('show', 1), disp)
    if (editingTm) { const cx = el('button', 'lane-del', 'cancel edit'); cx.addEventListener('click', e => { e.preventDefault(); editingTm = null; redraw() }); foot.appendChild(cx) }
    g.appendChild(foot)
    function commit() {
      const seq = [...phases.querySelectorAll('.tm-phase')].map(r => r._val()).filter(p => p.d > 0)
      if (!seq.length) return
      const m = mode.value
      const label = seq.length > 1 ? tname.value.trim() : (seq[0].n || '')
      const rec = { id: editingTm ? editingTm.id : uid(), label, seq, loop: m !== 'single', shuffle: m === 'shuffle' }
      // EDIT replaces by id (in place) — ADD appends. Navigating away without saving leaves the
      // original untouched. Same rule as the alarms, so there's never a duplicate.
      let list = J('clock-timers', '[]')
      if (editingTm) list = list.map(x => x.id === editingTm.id ? rec : x); else list.push(rec)
      editingTm = null; S('clock-timers', list); redraw()
    }
    J('clock-timers', '[]').forEach(t => {
      const show = (t.seq || []).map(p => (p.n ? p.n + ':' : '') + p.d + (p.unit === 'min' ? 'm' : (p.unit === 'sec' ? 's' : (t.unit === 'min' ? 'm' : 's')))).join(' · ')
      const modeTxt = t.shuffle ? ' · shuffle' : t.loop ? ' · repeat' : ''
      const w = el('label', 'wg-cell lane-row' + (editingTm && editingTm.id === t.id ? ' lane-editing' : ''),
        `<span class="lane-txt">${t.label ? '<b>' + t.label + '</b> — ' : ''}${show}${modeTxt}</span>`)
      const ed = el('button', 'lane-del', 'edit'); ed.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); editingTm = t; redraw() })
      const del = el('button', 'lane-del', 'remove'); del.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); S('clock-timers', J('clock-timers', '[]').filter(x => x.id !== t.id)); if (editingTm && editingTm.id === t.id) editingTm = null; redraw() })
      w.append(ed, del); g.appendChild(w)
    })
    return g
  }

  // ── STOPWATCH ── REBUILT 2026-07-21 as its own SEALED card (analog dial / digital face + interval
  //    mode). here we own only what the BAR shows: which units the readout uses. start/stop/lap and
  //    the faces live on the card — tap the bar readout to open it.
  // ── the stopwatch DISPLAY settings (Sum 2026-07-21). The card is fixed-size: the laps sit in a
  //    box that shows 4 and scrolls, so nothing ever pushes and the card never resizes. ──
  //    clock-sw-main: 'total' | 'lap' | 'both'   ·   clock-sw-show: [fastest average laps]
  //    clock-sw-lapcols: [split vsavg vsbest]
  function swRow(title, note) { const r = el('div'); r.appendChild(lab(title, 1)); if (note) { const n = el('div', 'loc-status', note); n.style.margin = '2px 0 6px'; r.appendChild(n) } return r }
  // a radio strip — exactly one on
  function pickStrip(key, def, opts) {
    const row = el('div', 'lane-genbar')
    const cur = () => { try { return JSON.parse(localStorage.getItem(key)) || def } catch (_) { return def } }
    opts.forEach(([v, l]) => {
      const b = el('button', 'loc-btn', l)
      const paint = () => b.style.opacity = cur() === v ? '1' : '.45'
      b.addEventListener('click', e => { e.preventDefault(); S(key, v); row.querySelectorAll('button').forEach(x => x._paint && x._paint()) })
      b._paint = paint; paint(); row.appendChild(b)
    })
    return row
  }
  // a multi-toggle strip — any number on
  function flagStrip(key, def, opts) {
    const row = el('div', 'lane-genbar')
    const cur = () => { try { const v = JSON.parse(localStorage.getItem(key)); return Array.isArray(v) ? v : def } catch (_) { return def } }
    opts.forEach(([v, l]) => {
      const b = el('button', 'loc-btn', l)
      const paint = () => b.style.opacity = cur().includes(v) ? '1' : '.45'
      b.addEventListener('click', e => {
        e.preventDefault()
        const c = cur(); S(key, c.includes(v) ? c.filter(x => x !== v) : c.concat(v))
        row.querySelectorAll('button').forEach(x => x._paint && x._paint())
      })
      b._paint = paint; paint(); row.appendChild(b)
    })
    return row
  }
  function drawStopwatch() {
    const g = el('div')
    g.dataset.tool = 'stopwatch'; g.appendChild(el('div', 'lane-group', 'STOPWATCH'))
    g.appendChild(el('div', 'loc-status', 'tap the stopwatch on the time-tools bar to open its card.'))

    // ── THE MASTER SWITCH, first (Sum 2026-07-21): laps OFF = a plain big stopwatch,
    //    start/stop/clear, no lap button, no stats, and none of the settings below. ──
    const on = J('clock-sw-laps', 'true') !== false
    const mbtn2 = () => {
      const b = el('button', 'loc-btn', on ? 'laps ON' : 'laps OFF')
      b.style.opacity = on ? '1' : '.45'
      b.addEventListener('click', e => { e.preventDefault(); S('clock-sw-laps', !on); redraw() })
      return b
    }
    if (!on) {
      const mrow = el('div', 'lane-genbar'); mrow.append(mbtn2()); g.appendChild(mrow)
      g.appendChild(el('div', 'loc-status', 'a plain big stopwatch — start, stop, clear. nothing else on screen.'))
      return g
    }

    // ONE LINE (Sum 2026-07-21): every stopwatch display choice as a dropdown on a single row.
    // .lane-genbar wraps, so a narrow card folds it instead of overflowing.
    const bar = el('div', 'lane-genbar')
    bar.append(mbtn2())
    // the big number — one choice
    bar.append(lab('big number', 1))
    const bigSel = el('select', 'loc-input lane-sel')
    bigSel.innerHTML = opts([['total', 'total time'], ['lap', 'this lap'], ['both', 'both']], J('clock-sw-main', '"total"'))
    bigSel.addEventListener('change', () => S('clock-sw-main', bigSel.value))
    bar.appendChild(bigSel)

    // the stats — any, all, or none
    bar.append(lab('show', 1))
    const showSel = toggleDrop([['laps', 'lap list'], ['fastest', 'fastest'], ['average', 'average'], ['count', 'lap counter']],
      J('clock-sw-show', '["laps","fastest","average","count"]'), false, 'stat', null, v => { S('clock-sw-show', v); redraw() })
    bar.appendChild(showSel.wrap)
    // what rides on each lap ROW — only meaningful when the lap list is actually shown (Sum 2026-07-21)
    if (J('clock-sw-show', '["laps","fastest","average","count"]').includes('laps')) {
      bar.append(lab('each lap', 1))
      const colSel = toggleDrop([['split', 'split'], ['vsavg', '± average'], ['vsbest', '± fastest']],
        J('clock-sw-lapcols', '["split","vsavg"]'), false, 'column', null, v => S('clock-sw-lapcols', v))
      bar.appendChild(colSel.wrap)
    }
    g.appendChild(bar)
    return g
  }

  const draw = id => ({ alarm: drawAlarm, countdown: drawCountdown, timer: drawTimer, stopwatch: drawStopwatch })[id]()
  // how often the time-tools bar rotates — same control the custom bars use (Sum 2026-07-21:
  // "a drop down in settings for how often the bar cycles like we have in custom bars, on the
  // same line as tools"). Rides the chip row beside alarm/countdown/timer/stopwatch.
  const cycle = el('label'); cycle.style.cssText = 'font-size:var(--fs-ui);color:var(--muted);margin-left:auto;display:inline-flex;align-items:center;gap:6px'
  cycle.innerHTML = 'every <select class="loc-input lane-sel tt-every" style="flex:0 0 auto">' +
    [[8, '8s'], [12, '12s'], [20, '20s'], [30, '30s'], [60, '1m'], [120, '2m'], [300, '5m']]
      .map(([v, l]) => `<option value="${v}"${v === J('clock-time-every', '8') ? ' selected' : ''}>${l}</option>`).join('') + '</select>'
  cycle.querySelector('select').addEventListener('change', e => S('clock-time-every', parseInt(e.target.value, 10) || 8))

  bean = window.csChipGroups({
    extra: cycle,
    host,
    chips: [{ id: 'alarm', label: 'alarm' }, { id: 'countdown', label: 'countdown' }, { id: 'timer', label: 'timer' }, { id: 'stopwatch', label: 'stopwatch' }],
    key: 'clock-time-on', draw,
  })

  // arriving from a card's "＋ add" button — scroll that tool's section into view and flash it, so
  // the hand-off lands somewhere obvious instead of at the top of a long settings page.
  // Consumed once: the hint must not re-fire when settings is opened normally with the gear.
  try {
    const focus = localStorage.getItem('clock-settings-focus')
    if (focus) {
      localStorage.removeItem('clock-settings-focus')
      setTimeout(() => {
        const g = document.querySelector(`[data-tool="${focus}"]`)
        if (!g) return
        g.scrollIntoView({ block: 'center', behavior: 'smooth' })
        g.classList.add('tt-landed')
        setTimeout(() => g.classList.remove('tt-landed'), 1600)
      }, 120)
    }
  } catch (_) {}
})()
