// geo.js — one IP-based location chain (the default "where am I")
// FOR HUMANS:
//   roughly where is this device, by its IP? this is the starting
//   location when the user hasn't pinned one. free, keyless, and it
//   never makes the clock wait. ipapi.co → ipwho.is → Salt Lake City.
//   (the precise "detect my location" button is a different thing —
//    lb-location.js, which asks the browser for GPS permission.)
// FOR AI:
//   1. window.geo.coords() → [lat, lon], returned SYNC, always.
//      fresh cache → real coords. no cache → SLC now, refresh in the
//      background for next call. the weather never blocks on a geo API.
//   2. cache: localStorage 'geo-cache' { lat, lon, ts }, 24h.
//   3. all providers are HTTPS — ip-api.com's free tier 403s on https,
//      and http would be mixed-content once this deploys.
//   4. replaced 3 copies of this (clock.html, clock-retro, here). june 2026.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   background refresh — never awaited by a ....... search: "background refresh"
//   coords() → [lat, lon] now. cached if fresh, ... search: "coords() → [lat, lon]"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — `window.geo.coords()`, the single source of truth for "where is this device by IP".
//    **Returns `[lat, lon]` synchronously, always. Cached in localStorage under key `'geo-cache'`
//    **with 24-hour TTL.
//
//    **TOUCH HERE**
//    - Change the fallback location → `SLC` L19
//    - Change cache duration → `TTL` L21
//    - Add or remove a geolocation provider → `PROVIDERS` L22
//    - Change the fetch timeout → `_refresh()` L33
//    - Add fields to the cached object (e.g., city, timezone) → `_refresh()` L38
//
//    **TRAPS**
//    - `KEY` at L20 is the localStorage key name. Changing it orphans all cached coords in the
//    - wild; users will re-detect on next visit.
//    - The cache shape at L38 includes `city` for `lb-headlines.js` — do not remove without
//    - checking that file.
//    - `_pending` at L24 prevents concurrent fetches. If you add async state elsewhere, this
//    - pattern must hold or multiple providers will fire at once.
//    - `coords()` at L47 returns `SLC` immediately if cache is stale (L54), then fires `_refresh()`
//    - in the background. The weather clock never blocks; do not make this await.
//    - Line 36 checks `if (g.latitude)` — the provider response shape must have this field, or the
//    - cache will not update. Both providers at L22 use this name.
//
//    **DO NOT**
//    - Do not make `coords()` async or awaited by callers — the whole point is synchronous return.
//    - Do not move the city field (L38) without updating `lb-headlines.js`.
//    - Do not change the HTTPS-only requirement (L22 comment at L13–14 explains why).
//    - Do not add user-facing location detection here — that is `lb-location.js` (GPS permission).
//
//
//
//    ---
//
// END IC SHIP PASS


window.geo = (function () {

  const SLC = [40.76, -111.89]          // the honest default
  const KEY = 'geo-cache'
  const TTL = 24 * 60 * 60 * 1000
  const PROVIDERS = ['https://ipapi.co/json/', 'https://ipwho.is/']

  let _pending = null

  // ── background refresh — never awaited by a caller ──
  function _refresh() {
    if (_pending) return
    _pending = (async () => {
      for (const url of PROVIDERS) {
        try {
          const ctrl = new AbortController()
          const tid  = setTimeout(() => ctrl.abort(), 3000)
          const g    = await fetch(url, { signal: ctrl.signal }).then(r => r.json())
          clearTimeout(tid)
          if (g.latitude) {
            localStorage.setItem(KEY, JSON.stringify(
              { lat: g.latitude, lon: g.longitude, city: g.city || '', ts: Date.now() }))   // city → regional headlines (lb-headlines.js)
            return
          }
        } catch {}
      }
    })().finally(() => { _pending = null })
  }

  // ── coords() → [lat, lon] now. cached if fresh, else SLC + refresh ──
  function coords() {
    try {
      const c = JSON.parse(localStorage.getItem(KEY) || 'null')
      if (c && Date.now() - c.ts < TTL) return [c.lat, c.lon]
    } catch {}

    _refresh()
    return SLC
  }

  return { coords }

})()
