// wx-derive.js — the weather math, in one place
// FOR HUMANS: clock.html and weather.html were each deriving the same
//   numbers from the same raw API data — rain windows, UV peak, snow
//   inches, moon rise/set, clock formatting. two copies. they drifted:
//   one file multiplied snow by 39.37, the other by 39.3701. same
//   conversion, two answers. that's a bug with a fuse on it.
//   so the math became a module. the FETCH still differs per page
//   (different screens, different plumbing) — only the math is shared.
// FOR AI:
//   1. window.wxDerive — pure functions, no DOM, no network, no deps.
//   2. callers resolve their own geo + raw fetch, then pass arrays here.
//   3. loaded in <head> before clock.html's inline block and before
//      lb-weather-data.js, so it exists by the time either fetch resolves.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   time formatting ... search: "time formatting"
//   derived values .... search: "derived values"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for weather math shared between clock.html
//    **and weather.html. It exports `window.wxDerive`, an object containing six pure functions:
//    **`fmtHour`, `fmtClock`, `snowInches`, `rainWindows`, `uvPeak`, `usnoRiseSet`.
//
//    **TOUCH HERE** —
//    - Change snow conversion factor → `snowInches()` L37 (edit `M_TO_IN` at L17)
//    - Change rain probability threshold (currently 30%) → `rainWindows()` L42
//    - Change 12-hour clock format → `fmtHour()` L22–26
//    - Change 24-hour clock format → `fmtClock()` L29–32
//    - Change UV peak logic → `uvPeak()` L53–58
//    - Change USNO rise/set parsing → `usnoRiseSet()` L61–65
//
//    **TRAPS** —
//    - `window.wxDerive` (L67) is the public API name; renaming it breaks both clock.html and
//    - weather.html.
//    - `M_TO_IN` (L17) is a load-bearing constant; the drift between 39.37 and 39.3701 was the
//    - original bug that created this file (L5).
//    - `rainWindows()` filters by `nowHour` (L42); callers must pass the correct current hour or
//    - rain windows will be wrong.
//    - `usnoRiseSet()` expects USNO data shape with `phen` and `time` fields (L63); API schema
//    - changes will silently return null.
//
//    **DO NOT** —
//    - Add network calls or DOM access; this is pure math only (L10).
//    - Add state or memory between calls; each function must be stateless (L10).
//    - Move the load order; this must load in `<head>` before clock.html's inline block and before
//    - lb-weather-data.js (L12–13).
//    - Change the fetch logic or per-page plumbing; that stays in clock.html and weather.html
//    - (L7–8).
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {

  const M_TO_IN = 39.3701   // open-meteo snow_depth is METERS; we show inches

  // ── time formatting ───────────────────────────────────────

  // hour → "9AM" / "11PM"; pass minutes to get "09:30" instead
  function fmtHour(h, m) {
    if (m != null && m > 0) return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`
    const ap = h < 12 ? 'AM' : 'PM'
    return `${h === 0 ? 12 : h > 12 ? h - 12 : h}${ap}`
  }

  // ISO datetime → "H:MM" on a 24-hour clock
  function fmtClock(iso) {
    try { const t = new Date(iso); return `${t.getHours()}:${String(t.getMinutes()).padStart(2,'0')}` }
    catch { return '—' }
  }

  // ── derived values ────────────────────────────────────────

  // snow_depth meters → inches (raw; caller rounds). null-safe.
  function snowInches(m) { return m != null ? m * M_TO_IN : null }

  // hourly precip-probability → contiguous [[startHr,endHr],…] windows,
  // from nowHour onward, where probability ≥ 30%.
  function rainWindows(probs, nowHour) {
    const hits = (probs || []).map((p, i) => ({ h: i, p })).filter(x => x.h >= nowHour && x.p >= 30)
    if (!hits.length) return []
    const out = []; let start = hits[0].h, prev = hits[0].h
    for (let i = 1; i < hits.length; i++) {
      if (hits[i].h > prev + 1) { out.push([start, prev]); start = hits[i].h }
      prev = hits[i].h
    }
    out.push([start, prev]); return out
  }

  // hourly uv array → { idx, val } of the peak (val null if no data)
  function uvPeak(uv) {
    const a = uv || []
    if (!a.length) return { idx: 0, val: null }
    const idx = a.reduce((best, v, i) => v > (a[best] || 0) ? i : best, 0)
    return { idx, val: a[idx] ?? null }
  }

  // USNO oneday dataset (moondata | sundata array) → { rise, set } "HH:MM" or null
  function usnoRiseSet(data) {
    const arr = data || []
    const at = phen => arr.find(e => e.phen === phen)?.time?.slice(0, 5) || null
    return { rise: at('Rise'), set: at('Set') }
  }

  window.wxDerive = { fmtHour, fmtClock, snowInches, rainWindows, uvPeak, usnoRiseSet }

})()
