// wx-icons.js — one weather-code → icon + words table
// FOR HUMANS:
//   WMO weather codes (0 = clear, 95 = thunderstorm …) → an emoji and a
//   phrase. one table, shared by flip/mod and the weather screen, so they
//   never disagree about what code 71 is. they used to: flip had an older,
//   short list (no freezing rain, no snow grains) and called code 1
//   "Mostly Clear" while weather called it "Mainly clear". now: one source.
//   retro keeps its own short list on purpose — it's the experiment.
// FOR AI:
//   1. window.WX_ICON[code] → emoji.  window.WX_DESC[code] → text.
//   2. complete WMO set. consumers alias it: const WX_ICON = window.WX_ICON.
//   3. load FIRST — before clock.html's inline script reads the tables.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   WX_IMG (Sum 2026-07-14, "upgrade 1") — the ... search: "WX_IMG (Sum 2026-07-14,"
//   window.WX_SVG / WX_GLYPH — the DRAWN ......... search: "window.WX_SVG /"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for WMO weather code → icon mappings. It
//    **exports four window globals: `WX_ICON` (code → emoji), `WX_DESC` (code → text description),
//    **`WX_IMG` (code + probability → PNG `<img>` tag or null), and `WX_SVG` (code → SVG shape).
//    **flip/mod and the weather screen depend on these names and must never disagree about what a
//    **code means.
//
//    **TOUCH HERE** —
//    - Add or change a WMO code's emoji → `window.WX_ICON` L14–23
//    - Add or change a WMO code's text description → `window.WX_DESC` L25–36
//    - Add or change PNG filename or probability bucketing logic → `WX_IMG()` L43–60
//    - Add or change an SVG shape's markup → `window.WX_SVG_SHAPES` L67–75
//    - Add or change which WMO codes map to which SVG shape → `K()` L77–84
//
//    **TRAPS** —
//    - `WX_ICON` and `WX_DESC` must have identical code keys (L14–36), or consumers will read
//    - undefined. They are the contract.
//    - `WX_IMG_BASE` (L42) is a fallback path; it can be overridden before this script loads, so do
//    - not hardcode paths into the function itself.
//    - `K()` (L77–84) must cover all codes in `WX_DESC`, or `WX_GLYPH()` will silently return the
//    - cloud fallback (L85).
//    - `WX_SVG_SHAPES` keys (L67–75) must match the strings returned by `K()` (L77–84), or
//    - `WX_GLYPH()` will silently fall back to cloud.
//    - The `dec()` helper (L44) rounds probability to deciles (10, 20, …, 100); changing its bounds
//    - will orphan cached filenames in user data.
//    - Line 42 checks `window.WX_IMG_BASE || '../../shell/icons/'`; if you move this file, update
//    - the fallback path.
//
//    **DO NOT** —
//    - Rename `WX_ICON`, `WX_DESC`, `WX_IMG`, `WX_GLYPH`, or `WX_SVG` without updating every
//    - consumer (flip, mod, weather screen, almanac).
//    - Move the PNG files without updating the paths in `WX_IMG()` (L46–57) and the fallback base
//    - path (L42).
//    - Change the emoji in `WX_ICON` without checking if almanac's cached icon (which stays emoji
//    - on purpose, per L65) needs a migration.
//    - Add new WMO codes to only one of `WX_ICON` or `WX_DESC`; they must stay in sync.
//    - Edit retro's icon list; it keeps its own short list on purpose (L8).
//
//
//
//    ---
//
// END IC SHIP PASS


window.WX_ICON = {
  0:'☀️', 1:'🌤️', 2:'⛅', 3:'☁️',
  45:'🌫️', 48:'🌫️',
  51:'🌦️', 53:'🌦️', 55:'🌧️', 56:'🌨️', 57:'🌨️',
  61:'🌧️', 63:'🌧️', 65:'🌧️', 66:'🌨️', 67:'🌨️',
  71:'❄️', 73:'❄️', 75:'❄️', 77:'🌨️',
  80:'🌦️', 81:'🌧️', 82:'⛈️',
  85:'❄️', 86:'❄️',
  95:'⛈️', 96:'⛈️', 99:'⛈️',
}

window.WX_DESC = {
  0:'Clear sky', 1:'Mainly clear', 2:'Partly cloudy', 3:'Overcast',
  45:'Fog', 48:'Icy fog',
  51:'Light drizzle', 53:'Drizzle', 55:'Heavy drizzle',
  56:'Freezing drizzle', 57:'Freezing drizzle',
  61:'Light rain', 63:'Rain', 65:'Heavy rain',
  66:'Freezing rain', 67:'Freezing rain',
  71:'Light snow', 73:'Snow', 75:'Heavy snow', 77:'Snow grains',
  80:'Rain showers', 81:'Rain showers', 82:'Heavy showers',
  85:'Snow showers', 86:'Snow showers',
  95:'Thunderstorm', 96:'Thunderstorm', 99:'Thunderstorm',
}

// ── WX_IMG (Sum 2026-07-14, "upgrade 1") — the SAME chart, returning Sum's DERIVED PNGs with
//    DECILE PRECISION: 1 drop = 10% chance (the icon IS the forecast), 50 drops = raining now,
//    salt-shaker snow on the same grammar, white-out = snowing now. falls back to null → the
//    caller keeps its emoji (so a missing png can never blank a widget). one source, still. ──
window.WX_IMG_BASE = window.WX_IMG_BASE || '../../shell/icons/'
window.WX_IMG = function (code, prob) {
  const dec = (p, lo, hi) => Math.max(lo, Math.min(hi, Math.round((p == null ? 30 : p) / 10) * 10))
  let f = null
  if (code === 0) f = 'uv.png'
  else if (code === 1) f = 'wx/mainly-clear.png'
  else if (code === 2) f = 'wx/partly.png'
  else if (code === 3) f = 'wx/overcast.png'
  else if (code === 45 || code === 48) f = 'wx/fog.png'
  else if (code === 51 || code === 53 || code === 80) f = 'wx/partly-rain-' + dec(prob, 10, 50) + '.png'
  else if (code === 55 || code === 61 || code === 63 || code === 81) f = 'wx/overcast-rain-' + dec(prob, 10, 100) + '.png'
  else if (code === 65 || code === 82) f = 'wx/raining-now.png'
  else if (code === 75 || code === 86) f = 'wx/snowing-now.png'
  else if ([56, 57, 66, 67, 71, 73, 77, 85].indexOf(code) > -1) f = 'wx/snow-' + dec(prob, 10, 100) + '.png'
  else if (code === 95) f = 'wx/storm.png'
  else if (code === 96 || code === 99) f = 'wx/storm-rain.png'
  if (!f) return null
  return '<img class="wx-img" src="' + window.WX_IMG_BASE + f + '" alt="" style="height:1.15em;width:auto;vertical-align:-0.18em">'
}

// ── window.WX_SVG / WX_GLYPH — the DRAWN fallback (Sum 2026-07-22: "replace emoticon fallback with
//    svg or css, your call"). when WX_IMG has no PNG, render a SELF-SIZING glyph (height:1.15em, same
//    as the PNG, in ANY container — no CSS needed) instead of an emoji. currentColor → theme. 7 shapes,
//    keyed across the full WMO set. NOTE: almanac's cached icon stays emoji on purpose — bots read it as
//    text; retro keeps its own. this is the innerHTML fallback for flip/mod + the weather screen. ──
window.WX_SVG_SHAPES = {
  sun:    '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" aria-hidden="true"><circle cx="12" cy="12" r="5" fill="currentColor"/><g fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><path d="M12 1.5v3M12 19.5v3M1.5 12h3M19.5 12h3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M19.8 4.2l-2.1 2.1M6.3 17.7l-2.1 2.1"/></g></svg>',
  partly: '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" aria-hidden="true"><circle cx="8.5" cy="7.8" r="3.2" fill="currentColor"/><g fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"><path d="M8.5 1.6v1.9M1.6 7.8h1.9M3.7 3l1.3 1.3M13.3 3l-1.3 1.3"/></g><path fill="currentColor" d="M8.9 20.4a4.2 4.2 0 0 1-.5-8.36A5.5 5.5 0 0 1 18.8 11.3 3.7 3.7 0 0 1 18.4 20.4H8.9z"/></svg>',
  cloud:  '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" fill="currentColor" aria-hidden="true"><path d="M6.6 19a4.6 4.6 0 0 1-.5-9.17A6.1 6.1 0 0 1 17.9 8.4 4.1 4.1 0 0 1 17.6 19H6.6z"/></svg>',
  fog:    '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="M4 8.5h13M3 12.5h18M6 16.5h13M4 20.5h9"/></svg>',
  rain:   '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" aria-hidden="true"><path fill="currentColor" d="M6.6 15.2a4.6 4.6 0 0 1-.5-9.17A6.1 6.1 0 0 1 17.9 4.6 4.1 4.1 0 0 1 17.6 15.2H6.6z"/><g fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"><path d="M8 17.8l-1.2 3M12 17.8l-1.2 3M16 17.8l-1.2 3"/></g></svg>',
  snow:   '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" fill="currentColor" aria-hidden="true"><path d="M6.6 15.2a4.6 4.6 0 0 1-.5-9.17A6.1 6.1 0 0 1 17.9 4.6 4.1 4.1 0 0 1 17.6 15.2H6.6z"/><circle cx="8" cy="19.4" r="1.15"/><circle cx="12" cy="20.9" r="1.15"/><circle cx="16" cy="19.4" r="1.15"/></svg>',
  storm:  '<svg viewBox="0 0 24 24" style="height:1.15em;width:1.15em;vertical-align:-.18em" fill="currentColor" aria-hidden="true"><path d="M6.6 14.8a4.6 4.6 0 0 1-.5-9.17A6.1 6.1 0 0 1 17.9 4.2 4.1 4.1 0 0 1 17.6 14.8H6.6z"/><path d="M12.7 15.2l-3.4 4.4H12l-1 3.4 4.4-5.2H12.5l1.1-2.4z"/></svg>',
}
;(function () {
  var K = function (c) {
    c = +c
    return (c === 0 || c === 1) ? 'sun' : c === 2 ? 'partly' : c === 3 ? 'cloud'
      : (c === 45 || c === 48) ? 'fog'
      : ((c >= 71 && c <= 77) || c === 85 || c === 86) ? 'snow'
      : (c >= 95) ? 'storm'
      : ((c >= 51 && c <= 67) || (c >= 80 && c <= 82)) ? 'rain' : 'cloud'
  }
  window.WX_GLYPH = function (c) { return window.WX_SVG_SHAPES[K(c)] || window.WX_SVG_SHAPES.cloud }
  var m = {}; Object.keys(window.WX_DESC || {}).forEach(function (c) { m[c] = window.WX_GLYPH(c) })
  window.WX_SVG = m
})()
