// chiptune.js — THE SOUND PALETTE (Sum 2026-07-20). Two families, one player:
//   ALERTS (one-shot — a beep or a "get ready" that fires and stops; interval ticks, reminders)
//   HOLDS (loop till stopped — the real alarm: chiptunes, klaxon, 432/solfeggio, pulsing tones)
// FOR HUMANS: window.CHIPTUNE.play('beeps' | 'klaxon' | 'tone432' | 'korobeiniki' | …). ALERTS
//   stop themselves; HOLDS ring until CHIPTUNE.stop(). No audio files — pure WebAudio tones.
// FOR AI: SYNTH sounds are param-built (freq · optional amplitude pulse LFO · optional 2-tone
//   sweep); MELODIES are [note/beats] pairs on a square wave. every melody is public domain
//   (Korobeiniki 19th-c folk — NEVER 'Tetris' · Canon in D Pachelbel · Shchedryk/Carol melody).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   MELODIES — real arrangements now (Sum ........ search: "MELODIES — real"
//   SYNTHS param sounds. oneShot alerts have a ... search: "SYNTHS param sounds."
//   SINGING BOWLS (Sum 2026-07-21: "multiple ..... search: "SINGING BOWLS (Sum"
//   the BOWL — one gain per mode, fed by TWO ..... search: "the BOWL — one gain per"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for all sound generation in the clock. It
//    **exports `window.CHIPTUNE.play(name, opts)` and `window.CHIPTUNE.stop()`, plus
//    **`window.CHIPTUNE.GROUPS` — the menu structure that lists every available sound by category.
//
//    **TOUCH HERE**
//    - Add a new alert sound → `SYN` object L47, add a new key with `oneShot: true` and a `pat` or
//    - `seq` property
//    - Add a new looping tone → `SYN` object L47, add a new key without `oneShot`
//    - Add a new melody → `MEL` object L21, add a new key with `bpm`, `voices` (each with `wave`
//    - and `line`), and `build` array
//    - Change a melody's tempo → the `bpm` field in `MEL[name]` (e.g., L24 for canon)
//    - Change default volume → `setVol()` L102, the `0.22` constant
//    - Add sound to the menu → `window.CHIPTUNE.GROUPS` L181–185, add entry to the appropriate
//    - array
//    - Adjust singing bowl timbre → `partials` array in `bowl` or `bowlrise` entries L68–74, tweak
//    - `r` (ratio), `g` (gain), or `beat` (Hz detuning)
//
//    **TRAPS**
//    - `live` array L11 is the only record of active nodes; every node created must be pushed to it
//    - (see L96, L135, L175) or it will not stop cleanly
//    - `stop()` L77 is called at the start of `play()` L157 — if you add state that should survive
//    - a new play, it will be wiped
//    - The `build` array in melodies (e.g., L29) controls which voices play on each loop pass; its
//    - length and order matter for escalation
//    - Voice names in `build` must exactly match keys in `voices` (e.g., 'lead' on L29 must exist
//    - in L27) or they will silently not play
//    - The `sustain` parameter in `note1()` L147 is hardcoded to check voice name against `'lead'`
//    - and `'motif'` on L170 — renaming those voices breaks envelope behavior
//    - `freq()` L15 parses note names like `'E5'` and `'-'` (silence); the regex and SEMI table L14
//    - are load-bearing for all melody lines
//    - `parseLine()` L145 splits on whitespace and `/` — melody lines must use that exact format or
//    - notes will not parse
//
//    **DO NOT**
//    - Do not rename `AC`, `ctx`, `live`, or `master` without checking all references — they are
//    - wired through multiple functions
//    - Do not move the IIFE wrapper (L10, L187) or change how `window.CHIPTUNE` is assigned (L179)
//    - Do not add UI, settings persistence, or analytics here — that belongs in the clock's main
//    - file
//    - Do not add new audio files or fetch external sounds — this file generates all sound from
//    - scratch
//    - Do not change the WebAudio node graph structure (oscillator → gain → destination) without
//    - understanding that `live` tracking depends on it
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  let AC = null, live = []   // every active node, torn down on stop()
  const ctx = () => (AC = AC || new (window.AudioContext || window.webkitAudioContext)())

  const SEMI = { C: -9, 'C#': -8, D: -7, 'D#': -6, E: -5, F: -4, 'F#': -3, G: -2, 'G#': -1, A: 0, 'A#': 1, B: 2 }
  const freq = n => { if (n === '-') return 0; const m = /^([A-G]#?)(\d)$/.exec(n); return m ? 440 * Math.pow(2, (SEMI[m[1]] + (+m[2] - 4) * 12) / 12) : 0 }

  // ── MELODIES — real arrangements now (Sum 2026-07-20: "you're stuck in quarter notes and
  //    single tones"). each has VOICES (chord = notes joined by +, token = notes/beats) and a
  //    BUILD: which voices play on each pass, so an alarm ESCALATES by layering — chords once
  //    through, then the right-hand melody, then the running variation. ──
  const MEL = {
    // Pachelbel's ground bass — sustained triads build, the descant descends, then the
    // eighth-note "second verse" right hand comes in. D A Bm F#m G D G A, 2 beats a chord.
    canon: { bpm: 96, sustain: true, voices: {
        bass:   { wave: 'sine',     line: 'D2/2 A2/2 B2/2 F#2/2 G2/2 D2/2 G2/2 A2/2' },
        chords: { wave: 'triangle', line: 'D3+F#3+A3/2 A2+C#3+E3/2 B2+D3+F#3/2 F#2+A2+C#3/2 G2+B2+D3/2 D3+F#3+A3/2 G2+B2+D3/2 A2+C#3+E3/2' },
        lead:   { wave: 'square',   line: 'F#5/1 E5/1 D5/1 C#5/1 B4/1 A4/1 B4/1 C#5/1 D5/1 C#5/1 B4/1 A4/1 G4/1 F#4/1 G4/1 E4/1' },
        run:    { wave: 'square',   line: 'F#5/.5 A5/.5 F#5/.5 D5/.5 E5/.5 A5/.5 E5/.5 C#5/.5 D5/.5 F#5/.5 D5/.5 B4/.5 C#5/.5 F#5/.5 C#5/.5 A4/.5 B4/.5 D5/.5 B4/.5 G4/.5 A4/.5 D5/.5 A4/.5 F#4/.5 B4/.5 D5/.5 G4/.5 B4/.5 C#5/.5 E5/.5 A4/.5 C#5/.5' },
      }, build: [['bass', 'chords'], ['bass', 'chords', 'lead'], ['bass', 'chords', 'run'], ['bass', 'chords', 'lead', 'run']] },
    // Shchedryk — fast, syncopated 3/4, the four-note bell motif driving over a moving bass.
    carol: { bpm: 168, voices: {
        motif:  { wave: 'square',   line: 'E5/.5 D5/.5 E5/.5 C5/.5 E5/.5 D5/.5 E5/.5 C5/.5 E5/.5 D5/.5 E5/.5 C5/.5 D5/.5 C5/.5 B4/.5 A4/.5' },
        bass:   { wave: 'sine',     line: 'A2/2 A2/2 F2/2 G2/2' },
        chords: { wave: 'triangle', line: 'A3+C4+E4/2 A3+C4+E4/2 F3+A3+C4/2 G3+B3+D4/2' },
        high:   { wave: 'square',   line: 'A5/2 G5/2 F5/2 E5/1 D5/1' },
      }, build: [['motif', 'bass'], ['motif', 'bass', 'chords'], ['motif', 'bass', 'chords', 'high']] },
    // Korobeiniki — the A phrase syncopated, an octave bass under it, the B phrase as pass two.
    korobeiniki: { bpm: 150, voices: {
        lead: { wave: 'square', line: 'E5/1 B4/.5 C5/.5 D5/1 C5/.5 B4/.5 A4/1 A4/.5 C5/.5 E5/1 D5/.5 C5/.5 B4/1.5 C5/.5 D5/1 E5/1 C5/1 A4/1 A4/1 -/1' },
        bass: { wave: 'sine',   line: 'E2/1 E3/1 A2/1 A3/1 A2/1 A3/1 E2/1 E3/1 E2/1 E3/1 A2/1 A3/1 A2/1 A3/1 E2/2 -/2' },
        harm: { wave: 'triangle', line: 'E4+G4/1 -/.5 -/.5 D4+F#4/1 -/.5 -/.5 C4+E4/1 -/.5 -/.5 -/1 -/.5 -/.5 B3+D4/1 -/.5 -/1 E4+G4/1 -/1 -/1 -/1 -/1' },
      }, build: [['lead'], ['lead', 'bass'], ['lead', 'bass', 'harm']] },
  }

  // ── SYNTHS ── param sounds. oneShot alerts have a `pat` (on/off ms pairs); holds sustain.
  //   freq2 + sweep = a slow glide between two pitches (the 440↔432 pulse); lfo = amplitude breath.
  const SYN = {
    beep:      { wave: 'square', freq: 880, oneShot: true, pat: [110] },
    beeps:     { wave: 'square', freq: 880, oneShot: true, pat: [90, 90, 90, 90, 90] },   // beep beep beep
    ready:     { wave: 'sine',   seq: [[660, 140], [880, 260]], oneShot: true },           // a gentle "get ready" lift
    ding:      { wave: 'sine',   freq: 1046, oneShot: true, pat: [420] },
    klaxon:    { wave: 'sawtooth', freq: 620, freq2: 840, sweep: 1.6 },                     // the classic two-tone wail
    tone432:   { wave: 'sine',   freq: 432 },                                               // steady, calm
    solf528:   { wave: 'sine',   freq: 528 },                                               // steady solfeggio
    solf396:   { wave: 'sine',   freq: 396 },
    pulse432:  { wave: 'sine',   freq: 432, lfo: 0.5 },                                      // 432, breathing
    pulse528:  { wave: 'sine',   freq: 528, lfo: 0.7 },

    // ── ⭐ THE WORLD SOUNDS (Sum, 31 Aug, for /etex) — noise, not tone. No files, no API, no key.
    //    Each is one filtered-noise one-shot; `rumble` adds mass where the thing is heavy.
    grind:     { noise: { type: 'lowpass',  f0: 1400, f1: 180,  q: 1,  dur: 2.4, attack: 0.35, rumble: 42 } },  // stone on stone, the sphinx rising
    thud:      { noise: { type: 'lowpass',  f0: 500,  f1: 60,   q: 1,  dur: 0.6, attack: 0.01, rumble: 55 } },  // the plinth landing
    hiss:      { noise: { type: 'highpass', f0: 1800, f1: 4200, q: 2,  dur: 1.5, attack: 0.25 } },              // a snake, Angkor
    splash:    { noise: { type: 'bandpass', f0: 2600, f1: 400,  q: 1.2, dur: 0.9, attack: 0.008 } },            // water, the cenote
    sand:      { noise: { type: 'bandpass', f0: 900,  f1: 300,  q: 0.7, dur: 3.0, attack: 0.8 } },              // wind over dunes, the desert death
    crumble:   { noise: { type: 'highpass', f0: 900,  f1: 2600, q: 1.5, dur: 1.1, attack: 0.02 } },             // the relic going to dust
    // ── the LIVING world. `seq` blips a pitch list on one wave — a crude pitch envelope, which is
    //    all a bray is: up, down, up, down, and a wheeze. Cheap and slightly awful, which suits.
    bray:      { wave: 'sawtooth', oneShot: true, seq: [[300, 90], [520, 200], [470, 160], [250, 320], [180, 260]] },  // donkey · and the camels, recycled
    engine:    { noise: { type: 'lowpass',  f0: 260,  f1: 120,  q: 4,  dur: 1.6, attack: 0.05, rumble: 34 } },         // a motor idling
    crowd:     { noise: { type: 'bandpass', f0: 700,  f1: 500,  q: 0.5, dur: 2.6, attack: 1.1 } },                     // a market, heard from across it
    coin:      { wave: 'triangle', oneShot: true, seq: [[1900, 60], [2600, 50], [2100, 90]] },                          // something small into an empty bowl

    // ── MORE VARIETY (Sum, 31 Aug: "we only have two sounds, a chirp and a wave, lets add a few
    //    more varieties"). He was right — every noise entry was reading as one wave and every
    //    seq as one chirp. These differ by CONSTRUCTION, not just by numbers: a struck bell decays
    //    on a long tail, a river breathes on an LFO, birds are a scatter of short high blips, a
    //    footfall is almost pure attack, and high wind is thin and unfiltered where sand is thick.
    bell:      { wave: 'triangle', oneShot: true, seq: [[1320, 900], [1980, 700]] },                                     // struck once, left to ring
    river:     { noise: { type: 'bandpass', f0: 1500, f1: 1100, q: 0.9, dur: 3.4, attack: 1.4 } },                       // moving water, not a wave
    birds:     { wave: 'sine', oneShot: true, seq: [[3100, 45], [3600, 35], [2800, 55], [3900, 30], [3200, 60]] },        // a scatter, high and dry
    footfall:  { noise: { type: 'lowpass',  f0: 900,  f1: 140,  q: 2,  dur: 0.22, attack: 0.004, rumble: 70 } },          // almost all attack
    highwind:  { noise: { type: 'highpass', f0: 2200, f1: 3400, q: 0.6, dur: 3.2, attack: 1.2 } },                        // thin, cold, altitude
    creak:     { wave: 'sawtooth', oneShot: true, seq: [[190, 220], [150, 300], [205, 180], [140, 380]] },                                      // solfeggio, pulsing
    sweep432:  { wave: 'sine',   freq: 432, freq2: 440, sweep: 0.25, lfo: 0.4 },             // 440↔432 and back
    // ── SINGING BOWLS (Sum 2026-07-21: "multiple oscillating freq? can we make one that ramps
    //    naturally?"). Three things make metal sound like metal, and only the first is obvious:
    //    1. INHARMONIC partials. A string rings 1:2:3:4 (integers) and sounds like an organ. A
    //       bowl's modes land near 1 : 2.7 : 5.4 : 8.9 — NOT integers. That ratio IS the "metal".
    //    2. BEATING. A real bowl isn't perfectly round, so every mode is actually a close PAIR
    //       of frequencies a few Hz apart. The pair beats, and that slow warble is the shimmer
    //       you recognise. We build it honestly — two detuned oscillators per mode, not an LFO.
    //    3. The upper modes bloom LATER and sit quieter than the fundamental.
    //    base 216 Hz = 432/2, so a bowl sits in the same family as the tones already here.
    bowl:      { bowl: true, base: 216, swell: 1.2, partials: [
                  { r: 1.00, g: 1.00, beat: 1.4 }, { r: 2.71, g: 0.40, beat: 2.7 },
                  { r: 5.43, g: 0.17, beat: 4.1 }, { r: 8.91, g: 0.06, beat: 6.3 }] },
    // the RUBBED rim — you circle it and the tone climbs out of nothing. That's the natural ramp.
    bowlrise:  { bowl: true, base: 216, swell: 9, partials: [
                  { r: 1.00, g: 1.00, beat: 1.2 }, { r: 2.71, g: 0.44, beat: 2.4 },
                  { r: 5.43, g: 0.20, beat: 3.8 }, { r: 8.91, g: 0.08, beat: 5.9 }] },
  }

  function stop() { const a = ctx(); live.forEach(n => { try { n.stop ? n.stop() : (n.gain && n.gain.setTargetAtTime(0.0001, a.currentTime, 0.05)) } catch (_) {} }); live = [] }

  // one sustained/oscillating oscillator into the master gain
  function voice(a, master, s) {
    const o = a.createOscillator(); o.type = s.wave || 'sine'; o.frequency.value = s.freq || 440
    const g = a.createGain(); g.gain.value = 1
    o.connect(g); g.connect(master)
    if (s.freq2 && s.sweep) {   // slow glide between two pitches — LFO on frequency
      const lfo = a.createOscillator(), la = a.createGain()
      lfo.frequency.value = s.sweep; la.gain.value = Math.abs(s.freq2 - s.freq) / 2
      o.frequency.value = (s.freq + s.freq2) / 2
      lfo.connect(la); la.connect(o.frequency); lfo.start(); live.push(lfo)
    }
    if (s.lfo) {   // amplitude breath
      const lfo = a.createOscillator(), la = a.createGain()
      lfo.frequency.value = s.lfo; la.gain.value = 0.45
      g.gain.value = 0.55
      lfo.connect(la); la.connect(g.gain); lfo.start(); live.push(lfo)
    }
    o.start(); live.push(o); return { o, g }
  }

  // set master volume — steady, or RAMP from a whisper to the target over opts.ramp seconds
  // (Sum 2026-07-20: "volume ramp on any sustained, or on repeat of short").
  function setVol(a, master, opts) {
    const vol = opts.volume == null ? 0.22 : opts.volume
    if (opts.ramp) { master.gain.setValueAtTime(Math.min(0.03, vol), a.currentTime); master.gain.linearRampToValueAtTime(vol, a.currentTime + opts.ramp) }
    else master.gain.value = vol
  }
  function playSynth(name, opts) {
    const s = SYN[name] || SYN.beep, a = ctx(); if (a.state === 'suspended') a.resume()
    const master = a.createGain(); setVol(a, master, opts); master.connect(a.destination); live.push(master)
    if (s.oneShot) {   // a short alert — a pat[] of beeps, or a tiny seq; LOOPS (repeats) if asked
      const fire = () => {
        let t = a.currentTime + 0.02
        const blip = (f, dur) => { const o = a.createOscillator(), g = a.createGain(); o.type = s.wave; o.frequency.value = f; o.connect(g); g.connect(master); g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(1, t + 0.008); g.gain.exponentialRampToValueAtTime(0.0001, t + dur / 1000); o.start(t); o.stop(t + dur / 1000 + 0.02); t += dur / 1000 }
        if (s.seq) s.seq.forEach(([f, d]) => { blip(f, d); t += 0.04 })
        else s.pat.forEach((d, i) => { blip(s.freq, d); if (i < s.pat.length - 1) t += d / 1000 })
        return (t - a.currentTime) * 1000
      }
      const dur = fire()
      if (opts.loop) { const iv = setInterval(() => { if (a.state !== 'closed') fire() }, dur + 900); live.push({ stop: () => clearInterval(iv) }) }
      return
    }
    if (s.noise) return playNoise(a, master, s)   // ⭐ filtered-noise one-shot
    if (s.bowl) return playBowl(a, master, s)
    voice(a, master, s)   // a HOLD — sustains until stop()
  }

  // ── ⭐ NOISE — THE ONE PRIMITIVE THIS FILE DID NOT HAVE (Sum, 31 Aug 2026, for /etex).
  //    Every voice above is an OSCILLATOR, and an oscillator cannot make a hiss, a splash or
  //    stone grinding on stone — those are filtered white noise with an envelope. So: one cached
  //    noise buffer, a biquad whose cutoff SWEEPS, and a gain envelope. Same construction grammar
  //    as playBowl (build, connect, push to `live`), so stop() reaches it like everything else.
  //    ⚠ The buffer is cached per context — regenerating 2s of Math.random() per press is audible
  //      as a hitch on a phone.
  let NOISEBUF = null, NOISECTX = null
  function noiseBuf(a) {
    if (NOISEBUF && NOISECTX === a) return NOISEBUF
    const n = a.sampleRate * 2, b = a.createBuffer(1, n, a.sampleRate), d = b.getChannelData(0)
    for (let i = 0; i < n; i++) d[i] = Math.random() * 2 - 1
    NOISEBUF = b; NOISECTX = a; return b
  }
  //    s.noise = { type, f0, f1, q, dur, attack, rumble }
  //      type   biquad kind — 'lowpass' grinding, 'highpass' hiss, 'bandpass' splash
  //      f0→f1  the cutoff SWEEP over dur. Falling = something settling; rising = something opening
  //      rumble optional sub-oscillator underneath, for mass. Stone needs it; a snake does not.
  function playNoise(a, master, s) {
    const c = s.noise, dur = c.dur || 1.2, t0 = a.currentTime + 0.02
    const src = a.createBufferSource(); src.buffer = noiseBuf(a); src.loop = true
    const bq = a.createBiquadFilter(); bq.type = c.type || 'lowpass'
    bq.frequency.setValueAtTime(c.f0 || 800, t0)
    bq.frequency.exponentialRampToValueAtTime(Math.max(40, c.f1 || c.f0 || 800), t0 + dur)
    if (c.q) bq.Q.value = c.q
    const g = a.createGain()
    const atk = c.attack == null ? 0.06 : c.attack
    g.gain.setValueAtTime(0.0001, t0)
    g.gain.exponentialRampToValueAtTime(1, t0 + atk)
    g.gain.exponentialRampToValueAtTime(0.0001, t0 + dur)
    src.connect(bq); bq.connect(g); g.connect(master)
    src.start(t0); src.stop(t0 + dur + 0.05); live.push(src)
    if (c.rumble) {   // mass under the texture — a tonne of rock, not a handful of gravel
      const o = a.createOscillator(); o.type = 'sine'; o.frequency.value = c.rumble
      const rg = a.createGain()
      rg.gain.setValueAtTime(0.0001, t0)
      rg.gain.exponentialRampToValueAtTime(0.7, t0 + 0.12)
      rg.gain.exponentialRampToValueAtTime(0.0001, t0 + dur)
      o.connect(rg); rg.connect(master); o.start(t0); o.stop(t0 + dur + 0.05); live.push(o)
    }
  }

  // ── the BOWL — one gain per mode, fed by TWO oscillators detuned by `beat` Hz. Their sum
  //    interferes and swells in and out on its own; no LFO can fake that texture honestly.
  //    Upper modes enter progressively later, which is what a rubbed rim actually does.
  function playBowl(a, master, s) {
    const base = s.base || 216, swell = s.swell || 1
    s.partials.forEach((p, i) => {
      const pg = a.createGain(); pg.gain.value = 0.0001; pg.connect(master); live.push(pg)
      const f = base * p.r
      ;[-p.beat / 2, p.beat / 2].forEach(d => {
        const o = a.createOscillator(); o.type = 'sine'; o.frequency.value = f + d
        o.connect(pg); o.start(); live.push(o)
      })
      const t0 = a.currentTime + i * swell * 0.16          // the highs bloom after the fundamental
      const rise = Math.max(0.4, swell * (1 - i * 0.1))
      pg.gain.setValueAtTime(0.0001, t0)
      pg.gain.linearRampToValueAtTime(p.g * 0.5, t0 + rise)
    })
  }

  // parse a voice line into events: each token "note[+note]/beats" → { freqs:[…], dur }
  const parseLine = line => line.trim().split(/\s+/).map(tok => { const [ns, b] = tok.split('/'); return { freqs: ns.split('+').map(freq), dur: parseFloat(b) || 1 } })
  // one note with an attack/sustain/release envelope (sustain=true → it rings the whole beat)
  function note1(a, master, wave, f, t, dur, sustain) {
    const o = a.createOscillator(), g = a.createGain(); o.type = wave; o.frequency.value = f; o.connect(g); g.connect(master)
    g.gain.setValueAtTime(0.0001, t)
    g.gain.exponentialRampToValueAtTime(0.4, t + 0.015)                                   // attack
    g.gain.exponentialRampToValueAtTime(sustain ? 0.32 : 0.16, t + dur * (sustain ? 0.85 : 0.5))   // sustain — chords ring
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur * 0.99)                           // release
    o.start(t); o.stop(t + dur + 0.02)
  }

  function play(name, opts) {
    opts = opts || {}; stop()
    if (SYN[name]) return playSynth(name, opts)
    // a LAYERED MELODY — voices + a build ladder (chords → +lead → +run), escalating on loop
    const tune = MEL[name] || MEL.canon, beat = 60 / (tune.bpm || 100)
    const a = ctx(); if (a.state === 'suspended') a.resume()
    const master = a.createGain(); setVol(a, master, opts); master.connect(a.destination); live.push(master)
    const voices = {}; Object.keys(tune.voices).forEach(k => voices[k] = { wave: tune.voices[k].wave, evs: parseLine(tune.voices[k].line) })
    const build = tune.build || [Object.keys(tune.voices)]
    const cycle = Math.max.apply(null, Object.keys(voices).map(k => voices[k].evs.reduce((s, e) => s + e.dur, 0))) * beat
    let pass = 0
    const schedule = start => {
      (build[Math.min(pass, build.length - 1)]).forEach(k => {
        const v = voices[k]; let t = start
        v.evs.forEach(e => { e.freqs.forEach(f => { if (f > 0) note1(a, master, v.wave, f, t, e.dur * beat, k !== 'lead' && k !== 'motif' && (tune.sustain || k === 'chords' || k === 'harm')) }); t += e.dur * beat })
      })
    }
    let t0 = a.currentTime + 0.06
    schedule(t0)
    if (opts.loop) { const iv = setInterval(() => { if (a.state === 'closed') return; if (a.currentTime > t0 + cycle - 0.35) { t0 += cycle; pass++; schedule(t0) } }, 90); live.push({ stop: () => clearInterval(iv) }) }
  }

  // the menu, grouped, for the settings picker
  window.CHIPTUNE = {
    play, stop,
    GROUPS: {
      alerts:   [['beep', 'single beep'], ['beeps', 'beep beep beep'], ['ready', 'get-ready lift'], ['ding', 'ding']],
      holds:    [['klaxon', 'klaxon'], ['tone432', '432 Hz steady'], ['solf528', '528 Hz (solfeggio)'], ['solf396', '396 Hz (solfeggio)'], ['pulse432', '432 pulsing'], ['pulse528', '528 pulsing'], ['sweep432', '440↔432 wave'], ['bowl', 'singing bowl'], ['bowlrise', 'singing bowl (slow rise)']],
      melodies: [['korobeiniki', 'russian folk (8-bit)'], ['canon', 'canon in D'], ['carol', 'carol of the bells']],
      // ⭐ world — filtered noise, not tone. Added 31 Aug for /etex; useful anywhere.
      world:    [['grind', 'stone on stone'], ['thud', 'heavy landing'], ['hiss', 'snake'], ['splash', 'water'], ['sand', 'wind over dunes'], ['crumble', 'crumbling to dust'],
                 ['bray', 'donkey'], ['engine', 'motor idling'], ['crowd', 'a market'], ['coin', 'coin in a bowl'],
                 ['bell', 'a struck bell'], ['river', 'moving water'], ['birds', 'birds'], ['footfall', 'a footfall'], ['highwind', 'high thin wind'], ['creak', 'old timber']],
    },
  }
})()
