// lb-alarm.js — THE ALARM ENGINE + WAKE SCREEN (Sum 2026-07-20, tasks #16 + #18)
// FOR HUMANS: watches your alarms; when one is due it either plays a sound ONCE (a get-ready
//   nudge) or rings till you dismiss it (the wake screen takes the whole card). Snooze re-arms
//   it. The light is seizure-safe: a slow warm sunrise that BREATHES, never flashes.
// FOR AI:
//   1. checks clock-alarms every 5s; fires once per matching minute (fired[id] = minute-key).
//   2. plays:'once' → CHIPTUNE.play(sound), no takeover. plays:'repeat' → loop + wake screen.
//   3. dismiss methods: circle · hold · tap3 · math · say (speech, else falls back to hold).
//   4. snooze: snoozeMin minutes, up to snoozeMax times — a big separate target (never the
//      dismiss zone; that touchy swipe was the #1 gripe). the native "push to screen / open
//      app" summon is #16's launchd/focus bolt — this is the in-card takeover.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the seizure-safe pulse, injected once ......... search: "the seizure-safe pulse,"
//   the dismiss methods — MULTIPLE, in sequence ... search: "the dismiss methods"
//   the TRUST BUTTON's engine half (wishlist r2 ... search: "the TRUST BUTTON's"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the alarm engine: checking when alarms
//    **are due (every 5s), firing them with an escalating sound ladder, and displaying the wake
//    **screen with multiple dismiss puzzles. It exports `window.ALARM_TEST(a)` (line 264) to fire a
//    **test alarm, and `window.ALARM_DISMISS` (line 271) to dismiss it. It also calls
//    **`reschedule()` (line 37) to sync with launchd so alarms survive app quit.
//
//    **TOUCH HERE** —
//    - change alarm check interval → `check()` L49, called L273 with `setInterval(check, 5000)`
//    - change sound escalation timing or volume curve → `ringLadder()` L59, specifically the
//    - `setInterval` at L65 (22000ms per stage) and volume formula at L62
//    - change wake screen colors or animation → CSS in `s.textContent` L90–106
//    - change snooze duration or max count → `snooze()` L113 (snoozeMin/snoozeMax read from alarm
//    - object `a`)
//    - add or modify a dismiss puzzle → add to `METHODS` object L154, then write the function (e.g.
//    - `tapDismiss` L168)
//    - change the seizure-safe breath timing → `@keyframes wakeBreath` L94 (currently 5.5s)
//    - change voice commands → `listenVoice()` L133, regex patterns at L143–144
//
//    **TRAPS** —
//    - `fired` object (L38) is keyed by alarm ID and minute-string to prevent double-firing;
//    - renaming or clearing it breaks the once-per-minute guarantee.
//    - `active` flag (L38) gates the check loop; if not set to `true` in `showWake()` L116 and
//    - `false` in `closeWake()` L111, alarms can fire while one is already ringing.
//    - The dismiss methods are called in sequence via `METHODS[list[i]]` (L163); if you add a
//    - method, it must be in the `METHODS` object (L154) or it silently falls back to
//    - `circleDismiss`.
//    - `launchEntries()` (L26) must match the shape that launchd expects; the `reschedule()` call
//    - (L37) sends this to the native layer, and a shape mismatch silently fails to arm native
//    - alarms.
//    - The wake screen is identified by `id="wake"` (L118); many functions check
//    - `document.getElementById('wake')` to detect if it's still open (L65, L146, L181, L195, L252,
//    - L256, L266). Changing this ID breaks all those checks.
//    - `iso()` format (L17) is used as a key in `fired` and in `due()` date comparisons (L43–45);
//    - changing the format orphans old fired records and breaks date-range logic.
//    - The snooze button is only shown if `a.snoozeMax && count < a.snoozeMax` (L123); if you
//    - change this condition, users may snooze past the limit or lose the button unexpectedly.
//
//    **DO NOT** —
//    - Do not rename `window.ALARM_TEST` or `window.ALARM_DISMISS`; external code (the trust
//    - button, test harness) calls these by name.
//    - Do not change the `clock-alarms` localStorage key (L28, L52, L275); it is the contract with
//    - the settings UI.
//    - Do not move the CSS injection (L88–108) into a separate file; it must inject once on first
//    - load, before any wake screen is shown.
//    - Do not change the `__TAURI__` invoke path (L22) or the command names `'win_wake'` /
//    - `'win_release'` (L117, L111); these are the native layer contract.
//    - Do not add new state to `fired` or `active` without documenting the invariant; they are the
//    - only two module-level mutable variables and their consistency is load-bearing.
//    - Do not move alarm scheduling logic to a different file; `launchEntries()` and `reschedule()`
//    - must stay here because they are called on storage change (L275) and boot (L274).
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const pad = n => String(n).padStart(2, '0')
  const iso = d => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
  const TUNE = () => { try { return parent.CHIPTUNE || window.CHIPTUNE } catch (_) { return window.CHIPTUNE } }
  // the NATIVE SUMMON (Sum 2026-07-20: "push it to screen") — win_wake raises oz above other
  // apps + focuses when a wake alarm rings; win_release drops always-on-top on dismiss. no-op
  // in a browser (the invoke bolt only exists in the wry build).
  const inv = (cmd, args) => { try { const P = parent, c = P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__); if (c && c.invoke) return c.invoke(cmd, args) } catch (_) {} }
  const win = cmd => inv(cmd)
  // THE LAUNCHD WAKER (Sum 2026-07-20) — hand the alarm times to launchd so oz fires even when
  // it's fully QUIT (a setTimeout dies with the process; launchd survives reboot + sleep).
  function launchEntries() {
    const out = []
    J('clock-alarms', '[]').filter(a => a.on !== false).forEach(a => {
      const [h, m] = String(a.time || '').split(':').map(Number)
      if (isNaN(h) || isNaN(m)) return
      if (a.date) { const d = new Date(a.date + 'T00:00'); out.push({ month: d.getMonth() + 1, day: d.getDate(), hour: h, minute: m }) }
      else if (a.days && a.days.length) a.days.forEach(wd => out.push({ weekday: wd, hour: h, minute: m }))
      else out.push({ hour: h, minute: m })
    })
    return out
  }
  const reschedule = () => { const p = inv('schedule_alarms', { entries: launchEntries() }); if (p && p.catch) p.catch(() => {}) }
  let fired = {}, active = false

  function due(a, now) {
    const [h, m] = String(a.time || '').split(':').map(Number)
    if (now.getHours() !== h || now.getMinutes() !== m) return false
    if (a.date) return a.date === iso(now)
    if (a.start && iso(now) < a.start) return false
    if (a.end && iso(now) > a.end) return false
    if (a.days && a.days.length) return a.days.includes(now.getDay())
    return true   // a plain daily
  }
  function check() {
    if (active) return
    const now = new Date(), key = iso(now) + ' ' + pad(now.getHours()) + ':' + pad(now.getMinutes())
    J('clock-alarms', '[]').filter(a => a.on !== false).forEach(a => { if (fired[a.id] !== key && due(a, now)) { fired[a.id] = key; fire(a, 0) } })
  }
  // THE ESCALATION LADDER (Sum 2026-07-20: "a ranker — click a bowl, a song, a gong, a klaxon
  //   in order"). sound is an ORDERED list; the alarm climbs it, each stage louder, holding at
  //   the loudest. stage 0 ramps up from a whisper (volume ramp); the rest snap in escalating.
  let escTimer = null
  const ladderOf = a => (Array.isArray(a.sound) ? a.sound.filter(Boolean) : [a.sound || 'beeps'])
  function ringLadder(a) {
    const t = TUNE(); if (!t) return
    const ladder = ladderOf(a); let stage = 0
    const playStage = () => { const vol = Math.min(0.8, 0.14 + stage * 0.17); t.play(ladder[Math.min(stage, ladder.length - 1)], { loop: true, volume: vol, ramp: stage === 0 && a.ramp !== false ? 12 : 2 }) }
    playStage()
    clearInterval(escTimer)
    escTimer = setInterval(() => { if (!document.getElementById('wake')) { clearInterval(escTimer); return } if (stage < ladder.length - 1) { stage++; playStage() } }, 22000)
  }
  function fire(a, snoozeCount) {
    const t = TUNE(), ladder = ladderOf(a)
    if (a.plays === 'once') { if (t) t.play(ladder[0], { ramp: a.ramp !== false ? 3 : 0 }); return }   // a nudge, no takeover
    ringLadder(a)
    showWake(a, snoozeCount)
  }

  // ── the seizure-safe pulse, injected once ──
  // ⚠️ THE SAFETY RATIONALE — lifted here from wake-proto.html when that prototype was archived
  // (2026-07-21), because it was the ONLY copy and the numbers below are not arbitrary. Sum
  // 2026-07-20: "no seizures, just light. white screen, pulsing not flashing."
  //   · photosensitive epilepsy triggers on FAST flashing 3–30 Hz (worst ~15–20), high contrast,
  //     and saturated RED. this screen does NONE of that.
  //   · the light pulses on a slow sine — one breath every ~5s (0.2 Hz), FAR under the 3 Hz floor,
  //     and it EASES (never snaps on/off). a breath, not a strobe. see wakeBreath below: 5.5s.
  //   · colour is warm amber→white (a sunrise). never red, never an alternating high-contrast pattern.
  //   · the sun rises SLOWLY — the gold-standard sunrise-alarm approach; gradual brightening wakes
  //     the body without startling the brain. all motion is slow and smooth.
  // DO NOT speed up the breath, raise the contrast, or introduce red. Those are safety limits,
  // not taste. Dismiss deliberately requires intent + executive function so it can't be killed
  // while asleep.
  if (!document.getElementById('wake-css')) {
    const s = document.createElement('style'); s.id = 'wake-css'
    s.textContent = `
      #wake { position: fixed; inset: 0; z-index: 9999; overflow: hidden; touch-action: none;
        background: radial-gradient(130% 100% at 50% 118%, hsl(38,95%,72%) 0%, hsl(28,88%,56%) 20%, hsl(280,40%,20%) 58%, hsl(258,45%,9%) 100%);
        animation: wakeBreath 5.5s ease-in-out infinite; }
      @keyframes wakeBreath { 0%,100%{filter:brightness(.86)} 50%{filter:brightness(1.12)} }
      #wake .wk-time { position:absolute; top:12%; left:0; right:0; text-align:center; color:#fff2e0; font-size:14vw; font-weight:800; text-shadow:0 2px 14px rgba(60,20,0,.4) }
      #wake .wk-msg { position:absolute; top:30%; left:0; right:0; text-align:center; color:#fff2e0; font-size:3.4vw; font-weight:600 }
      #wake .wk-dot { position:absolute; width:78px; height:78px; border-radius:50%; transform:translate(-50%,-50%);
        background:radial-gradient(circle,#fff 0%,hsl(34,90%,62%) 55%,transparent 72%); box-shadow:0 0 44px 12px hsla(34,90%,62%,.7) }
      #wake .wk-hold { position:absolute; left:50%; top:56%; transform:translate(-50%,-50%); min-width:56vw; min-height:14vh;
        border:none; border-radius:20px; background:#f0e8d8; color:#1a1a2e; font-size:5vw; font-weight:800; box-shadow:0 6px 0 rgba(0,0,0,.5) }
      #wake .wk-corner { position:absolute; width:22vw; height:22vw; border-radius:16px; background:hsla(34,90%,62%,.25); border:3px solid #fff2e0 }
      #wake .wk-corner.lit { background:hsla(120,60%,55%,.5) }
      #wake .wk-mathbox { position:absolute; left:50%; top:52%; transform:translate(-50%,-50%); text-align:center; color:#fff2e0 }
      #wake .wk-mathbox input { font-size:8vw; width:4em; text-align:center; border-radius:12px; border:none; padding:.1em .2em; margin-top:.3em }
      #wake .wk-snooze { position:absolute; left:0; right:0; bottom:5vh; text-align:center }
      #wake .wk-snooze button { min-width:44vw; min-height:9vh; border:none; border-radius:18px; background:#3a3450; color:#fff2e0; font-size:4.2vw; font-weight:700 }`
    document.head.appendChild(s)
  }

  function stopSound() { clearInterval(escTimer); const t = TUNE(); if (t) t.stop() }
  function closeWake() { const w = document.getElementById('wake'); if (w) w.remove(); active = false; win('win_release') }
  function dismiss() { stopSound(); closeWake() }
  function snooze(a, count) { stopSound(); closeWake(); setTimeout(() => { if (!active) fire(a, count + 1) }, Math.max(1, a.snoozeMin || 9) * 60000) }

  function showWake(a, count) {
    active = true
    win('win_wake')   // bring oz to the front so the wake screen is actually seen
    const w = document.createElement('div'); w.id = 'wake'
    const now = new Date()
    w.innerHTML = `<div class="wk-time">${now.getHours() % 12 || 12}:${pad(now.getMinutes())}</div><div class="wk-msg">${a.label || 'alarm'}</div>`
    document.body.appendChild(w)
    mountDismiss(w, a)
    const canSnooze = a.snoozeMax && count < a.snoozeMax
    if (canSnooze) {
      const sn = document.createElement('div'); sn.className = 'wk-snooze'
      const b = document.createElement('button'); b.textContent = `snooze ${a.snoozeMin}m  (${a.snoozeMax - count} left)`
      b.addEventListener('click', () => snooze(a, count)); sn.appendChild(b); w.appendChild(sn)
    }
    // the VOICE layer — 'off' dismisses; 'snooze' only snoozes, and ONLY while snoozes remain,
    // so the last wake-up needs the physical dismiss (Sum: "run out of snoozes, hit the button").
    if (a.voice && a.voice !== 'none') listenVoice(w, a, count, canSnooze)
  }
  function listenVoice(w, a, count, canSnooze) {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SR) return
    const msg = w.querySelector('.wk-msg')
    if (a.voice === 'off') msg.textContent += ' · or say "off"'
    else if (canSnooze) msg.textContent += ' · or say "snooze"'
    try {
      const r = new SR(); r.continuous = true; r.interimResults = true
      r.onresult = e => {
        const said = String(e.results[e.results.length - 1][0].transcript).toLowerCase()
        if (a.voice === 'off' && /\boff\b|alarm off|stop/.test(said)) { r.stop(); dismiss() }
        else if (a.voice === 'snooze' && canSnooze && /\bsnooze\b|five more|more sleep/.test(said)) { r.stop(); snooze(a, count) }
      }
      r.onend = () => { if (document.getElementById('wake')) { try { r.start() } catch (_) {} } }   // keep listening till dismissed
      r.start()
    } catch (_) {}
  }

  // ── the dismiss methods — MULTIPLE, in sequence (Sum 2026-07-20: "add multiple puzzles to
  //    turn off"). a.dismiss is one method or an ordered list; you clear each to advance, and
  //    only the LAST one dismisses. every method calls done() when its puzzle is solved. ──
  const METHODS = { tap: tapDismiss, circle: circleDismiss, hold: holdDismiss, tap3: tapCorners, math: mathDismiss, clap: clapDismiss, say: sayDismiss, repeat3: repeat3Dismiss }
  function mountDismiss(w, a) {
    const list = (Array.isArray(a.dismiss) ? a.dismiss.filter(Boolean) : [a.dismiss || 'circle'])
    const base = w.querySelector('.wk-msg').textContent
    let i = 0
    const step = () => {
      w.querySelectorAll('.wk-dot,.wk-hold,.wk-corner,.wk-mathbox').forEach(e => e.remove())   // clear the last puzzle
      w.querySelector('.wk-msg').textContent = base + (list.length > 1 ? ` · puzzle ${i + 1} of ${list.length}` : '')
      const done = () => { i++; if (i >= list.length) dismiss(); else step() }
      ;(METHODS[list[i]] || circleDismiss)(w, done)
    }
    step()
  }
  // one tap anywhere — low-stakes, perfect for an interval-timer chime (Sum)
  function tapDismiss(w, done) {
    w.querySelector('.wk-msg').textContent += ' — tap to stop'
    w.addEventListener('pointerdown', function h() { w.removeEventListener('pointerdown', h); done() })
  }
  // a CLAP — a sharp mic amplitude spike (Sum: "a clap to turn off"). needs mic; else falls to tap.
  function clapDismiss(w, done) {
    w.querySelector('.wk-msg').textContent += ' — clap to stop'
    if (!(navigator.mediaDevices && navigator.mediaDevices.getUserMedia)) return tapDismiss(w, done)
    navigator.mediaDevices.getUserMedia({ audio: true }).then(stream => {
      const ac = new (window.AudioContext || window.webkitAudioContext)(), src = ac.createMediaStreamSource(stream)
      const an = ac.createAnalyser(); an.fftSize = 512; src.connect(an)
      const buf = new Uint8Array(an.fftSize); let quiet = true
      const tick = () => {
        if (!document.getElementById('wake')) { stream.getTracks().forEach(t => t.stop()); ac.close(); return }
        an.getByteTimeDomainData(buf); let peak = 0
        for (let i = 0; i < buf.length; i++) peak = Math.max(peak, Math.abs(buf[i] - 128))
        if (peak > 55 && quiet) { stream.getTracks().forEach(t => t.stop()); ac.close(); done(); return }   // a clap = a sharp spike from quiet
        if (peak < 20) quiet = true
        requestAnimationFrame(tick)
      }
      requestAnimationFrame(tick)
    }).catch(() => tapDismiss(w, done))   // mic denied → tap is the honest fallback
  }
  function circleDismiss(w, done) {
    w.querySelector('.wk-msg').textContent += ' — circle the light to wake'
    const dot = document.createElement('div'); dot.className = 'wk-dot'; w.appendChild(dot)
    let cx = innerWidth / 2, cy = innerHeight * 0.62
    const drift = t => { if (!document.getElementById('wake') || !dot.isConnected) return; const s = t / 1000; cx = innerWidth / 2 + Math.sin(s * 0.23) * innerWidth * 0.26; cy = innerHeight * 0.6 + Math.cos(s * 0.31) * innerHeight * 0.16; dot.style.left = cx + 'px'; dot.style.top = cy + 'px'; requestAnimationFrame(drift) }
    requestAnimationFrame(drift)
    let drawing = false, ang = 0, last = null
    const P = e => e.touches ? e.touches[0] : e
    const md = () => { drawing = true; ang = 0; last = null }, mu = () => { drawing = false }
    const mm = e => { if (!drawing) return; const p = P(e); const a2 = Math.atan2(p.clientY - cy, p.clientX - cx); if (last !== null) { let d = a2 - last; while (d > Math.PI) d -= 2 * Math.PI; while (d < -Math.PI) d += 2 * Math.PI; ang += d } last = a2; if (Math.abs(ang) > Math.PI * 1.8) { w.removeEventListener('pointerdown', md); w.removeEventListener('pointerup', mu); w.removeEventListener('pointermove', mm); done() } }
    w.addEventListener('pointerdown', md); w.addEventListener('pointerup', mu); w.addEventListener('pointermove', mm)
  }
  function holdDismiss(w, done) {
    const b = document.createElement('button'); b.className = 'wk-hold'; b.textContent = 'hold to wake'; w.appendChild(b)
    let timer = null, t0 = 0
    const start = () => { t0 = Date.now(); b.textContent = 'keep holding…'; timer = setInterval(() => { if (Date.now() - t0 > 3000) { clearInterval(timer); done() } }, 100) }
    const stop = () => { clearInterval(timer); b.textContent = 'hold to wake' }
    b.addEventListener('pointerdown', start); b.addEventListener('pointerup', stop); b.addEventListener('pointerleave', stop)
  }
  function tapCorners(w, done) {
    w.querySelector('.wk-msg').textContent += ' — tap the three lit corners in order'
    const spots = [[4, 18], [78, 18], [4, 70]]; let i = 0
    spots.forEach(([x, y], k) => { const c = document.createElement('div'); c.className = 'wk-corner'; c.style.left = x + 'vw'; c.style.top = y + 'vh'; if (k === 0) c.classList.add('lit'); c.dataset.k = k
      c.addEventListener('click', () => { if (+c.dataset.k === i) { c.classList.remove('lit'); i++; if (i >= spots.length) return done(); w.querySelectorAll('.wk-corner')[i].classList.add('lit') } else { i = 0; w.querySelectorAll('.wk-corner').forEach((e, j) => e.classList.toggle('lit', j === 0)) } }); w.appendChild(c) })
  }
  function mathDismiss(w, done) {
    const x = 3 + Math.floor(Math.random() * 7), y = 4 + Math.floor(Math.random() * 8)
    const box = document.createElement('div'); box.className = 'wk-mathbox'; box.innerHTML = `<div style="font-size:7vw;font-weight:800">${x} + ${y} = ?</div><input inputmode="numeric" autofocus>`
    w.appendChild(box); const inp = box.querySelector('input'); inp.focus()
    inp.addEventListener('input', () => { if (+inp.value === x + y) done() })
  }
  function sayDismiss(w, done) {
    const word = 'good morning'
    w.querySelector('.wk-msg').textContent += ` — say "${word}"`
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SR) return holdDismiss(w, done)
    try { const r = new SR(); r.continuous = true; r.interimResults = true; r.onresult = e => { if (String(e.results[e.results.length - 1][0].transcript).toLowerCase().includes(word)) { r.stop(); done() } }; r.onend = () => { if (document.getElementById('wake')) { try { r.start() } catch (_) {} } }; r.start() } catch (_) { holdDismiss(w, done) }
  }
  // THE 3-WORD REPEAT-BACK (Sum 2026-07-20: "3 word repeat back — needs to repeat words if
  //   asked, in case you slept through the first part"). it SAYS three words (TTS), you say
  //   them back (speech); "say again" replays. no speech → shows the words + a hold, so it
  //   never traps you. this is the wake mechanic nobody ships.
  function repeat3Dismiss(w, done) {
    const WORDS = ['river', 'copper', 'lantern', 'meadow', 'signal', 'velvet', 'anchor', 'pinecone', 'marble', 'thunder', 'saffron', 'harbor', 'willow', 'ember', 'compass', 'ribbon']
    const three = [0, 0, 0].map(() => WORDS[Math.floor(Math.random() * WORDS.length)])
    const box = document.createElement('div'); box.className = 'wk-mathbox'
    box.innerHTML = `<div style="font-size:4.6vw;font-weight:800">repeat the three words</div><div class="wk-words" style="font-size:6vw;letter-spacing:.05em"></div><button style="border:none;border-radius:14px;background:#f0e8d8;color:#1a1a2e;font-size:4vw;font-weight:700;padding:.35em 1.1em;margin-top:.5em">say again</button>`
    w.appendChild(box)
    const wordsEl = box.querySelector('.wk-words')
    // prefer the shell's ONE voice service (Sum 2026-07-21) so the alarm rides a future native voice;
    // fall back to this frame's own speechSynthesis if the parent service isn't reachable (the clock is
    // an iframe — cross-frame, so this is the honest seam, not a hard dependency).
    const speak = () => {
      const txt = three.join('.  ')
      const V = window.parent && window.parent.OZ_VOICE
      if (V && V.speak) V.speak(txt, { force: true, rate: 0.85 })
      else { const S = window.speechSynthesis; if (S) { const u = new SpeechSynthesisUtterance(txt); u.rate = 0.85; S.cancel(); S.speak(u) } }
      wordsEl.textContent = '• • •'
    }
    speak(); box.querySelector('button').addEventListener('click', e => { e.stopPropagation(); speak() })
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SR) { wordsEl.textContent = three.join('  ·  '); return }   // no mic-speech → show them; the hold in a paired puzzle covers dismiss
    try {
      const r = new SR(); r.continuous = true; r.interimResults = true
      r.onresult = e => { const said = String(e.results[e.results.length - 1][0].transcript).toLowerCase(); if (three.every(word => said.includes(word))) { r.stop(); done() } }
      r.onend = () => { if (document.getElementById('wake') && box.isConnected) { try { r.start() } catch (_) {} } }
      r.start()
    } catch (_) { wordsEl.textContent = three.join('  ·  ') }
  }

  // ── the TRUST BUTTON's engine half (wishlist r2 2026-07-23: the #1 alarm gripe industry-wide
  //    is "it didn't ring" — so let anyone PROVE theirs does). fires the REAL path in 10s: the
  //    alarm's own ladder, the real wake screen, the real dismiss — nothing mocked. ──
  window.ALARM_TEST = function (a) {
    setTimeout(() => {
      if (document.getElementById('wake')) return   // one wake at a time
      try { fire(a || { label: 'test', sound: ['beeps'] }, 0) } catch (_) {}
    }, 10000)
  }
  // the hush half — so a bot that pressed the trust button can also clean up after itself
  window.ALARM_DISMISS = dismiss

  setInterval(check, 5000); check()
  reschedule()   // sync launchd with the current alarms on every boot (settings closed → we re-arm)
  window.addEventListener('storage', e => { if (e.key === 'clock-alarms') reschedule() })
  document.addEventListener('visibilitychange', () => { if (!document.hidden) check() })
})()
