// lb-sw-card.js — THE STOPWATCH CARD, inside the clock (Sum 2026-07-21).
// FOR HUMANS: tap the stopwatch on the time-tools bar → a big card opens over the clock. The
//   running time FILLS the width — it shrinks if the card shrinks or you add units, so no space
//   is ever wasted. Buttons sit right under it. Laps live in a fixed box with 4 ruled slots, so
//   the card never resizes and nothing shifts while you run.
// FOR AI:
//   1. ONE source of truth with the bar: localStorage clock-stopwatch
//      { running, since, banked, laps[] } — elapsed = banked + (running ? Date.now()-since : 0).
//      Wall-clock, never a tick accumulator, so nothing drifts or freezes when throttled.
//   2. ⚠️ THE DROPPED-CLICK RULE: this renders 25×/sec. NEVER write to the DOM unless the value
//      changed — assigning .textContent replaces the text node and swallows clicks mid-press.
//      Every write goes through set(). (Sum hit this twice; see the memory note.)
//   3. Type is SIZED IN JS to fill the width (CSS can't fit-text-to-box). Recomputed only when
//      the width or the character count changes.
//   4. LAPS OFF (clock-sw-laps = false) → no lap button, no stats, no list. Just a big stopwatch.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   settings .................................... search: "settings"
//   AUTO UNITS (Sum 2026-07-21: "remove units ... search: "AUTO UNITS (Sum"
//   controls .................................... search: "controls"
//   FIT THE TYPE TO THE BOX (Sum: "make all ..... search: "FIT THE TYPE TO THE BOX"
//   paint ....................................... search: "paint"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The stopwatch card UI and state machine. Exports `window.SW_CARD = { open, close }`
//    **to launch/close the overlay, and `window.SW_FIT = { measure, pxFor }` for the timer card to
//    **reuse the text-fitting math. Single source of truth is `localStorage['clock-stopwatch']` —
//    **the shape `{ running, since, banked, laps[] }` is load-bearing and shared with nothing else
//    **in this codebase.
//
//    **TOUCH HERE**
//    - Change what time format displays (MM:SS.CS vs H:MM:SS vs D:HH:MM) → `fmt()` L38
//    - Change which stats appear (fastest, average, count) → `show()` L29 reads the setting;
//    - `paintStats()` L224 renders them
//    - Change lap columns (split, vsavg, vsbest) → `lapCols()` L30 reads the setting; `paintLaps()`
//    - L236 renders them
//    - Change the main display mode (total, lap, or both) → `mainMode()` L28 reads the setting;
//    - `paint()` L191 applies it
//    - Change button labels or add buttons → edit the HTML in `build()` L57, then add listeners in
//    - the same function
//    - Change the lap counter size or position → `fit()` L139 computes `countRes` at L146; adjust
//    - the 0.10 multiplier or the 22px margin
//    - Change how fast the display updates → `setInterval(paint, 40)` L261
//    - Disable laps entirely → `lapsOn()` L27 is the master switch; it gates lap button, stats, and
//    - list visibility in `paint()` L193+
//
//    **TRAPS**
//    - `localStorage['clock-stopwatch']` shape is persisted. Changing `{ running, since, banked,
//    - laps[] }` will orphan old sessions. `read()` L22 has a fallback, but the shape itself is a
//    - contract.
//    - The `was` object L54 caches previous values to prevent DOM writes on unchanged data — this
//    - is the only thing stopping clicks from being swallowed mid-press (see comment L10–12). Never
//    - skip the `set()` call L55.
//    - `fit()` L139 measures text at 100px reference and scales linearly. The signature key L151
//    - guards against re-running on every frame. If you add a new variable that affects sizing, add
//    - it to the key or `was.fit` will cache stale results.
//    - `elapsedOf()` L24 uses `Date.now()` wall-clock math, not a tick counter. If you add a pause
//    - feature, you must update both `since` and `banked` together or elapsed will jump.
//    - `splitsOf()` L221 computes lap splits (time since previous lap) on demand. It is called in
//    - both `paintStats()` L225 and `paintLaps()` L238 — if you change the lap data shape, both
//    - must change.
//    - The lap list renders newest-first (line L244: `laps.length - 1 - i`). If you reverse this,
//    - the "best" and "worst" highlighting will point to the wrong rows.
//    - `measure()` L126 creates a hidden ruler div once and reuses it. If you add a new time format
//    - or stat, you must call `measure()` with the right HTML and class name, or the fit will be
//    - wrong.
//
//    **DO NOT**
//    - Change the localStorage key names (`'clock-stopwatch'`, `'clock-sw-laps'`,
//    - `'clock-sw-main'`, `'clock-sw-show'`, `'clock-sw-lapcols'`) — they are read by settings UI
//    - elsewhere.
//    - Move the `setInterval(paint, 40)` L261 into a conditional or throttle it further without
//    - understanding that `paint()` L191 returns early if the card is not open.
//    - Add a tick accumulator or animation frame loop — the wall-clock design in `elapsedOf()` L24
//    - is intentional and prevents drift when the browser throttles.
//    - Rename `J()` L17 or `S()` L19 — they are the only localStorage read/write helpers and are
//    - used throughout.
//    - Change the HTML structure in `build()` L57 without updating the `el` object L81–84 — every
//    - selector must match.
//    - Add settings UI here — settings live in a different file and write to localStorage; this
//    - file only reads them.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const S = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }
  const pad = n => String(n).padStart(2, '0')

  const read = () => { const s = J('clock-stopwatch', null); return s && typeof s === 'object' ? s : { running: false, since: 0, banked: 0, laps: [] } }
  const write = s => S('clock-stopwatch', s)
  const elapsedOf = s => (s.banked || 0) + (s.running ? Date.now() - s.since : 0)

  // ── settings ──
  const lapsOn = () => J('clock-sw-laps', true) !== false        // the master switch (first in settings)
  const mainMode = () => J('clock-sw-main', 'total')             // 'total' | 'lap' | 'both'
  const show = () => { const v = J('clock-sw-show', null); return Array.isArray(v) ? v : ['laps', 'fastest', 'average', 'count'] }
  const lapCols = () => { const v = J('clock-sw-lapcols', null); return Array.isArray(v) ? v : ['split', 'vsavg'] }

  // ── AUTO UNITS (Sum 2026-07-21: "remove units from stopwatch, not worth it — stopwatch can auto,
  //    start with hundredths, drop them at hours, drop seconds at days"). A LADDER, no setting:
  //      under an hour  →  MM:SS.CS   (hundredths, because they matter at this scale)
  //      an hour or more →  H:MM:SS    (hundredths are noise once you're counting hours)
  //      a day or more   →  D:HH:MM    (seconds are noise once you're counting days)
  //    The fit MEASURES, so each rung automatically resizes the number to fill the card.
  const fmt = ms => {
    ms = Math.max(0, ms)
    const total = Math.floor(ms / 1000)
    const d = Math.floor(total / 86400)
    const h = Math.floor((total % 86400) / 3600)
    const m = Math.floor((total % 3600) / 60)
    const sec = total % 60
    if (d >= 1) return { main: `${d}d ${pad(h)}:${pad(m)}`, frac: '' }   // 'd' or a day reads exactly like an hour
    if (h >= 1) return { main: `${h}:${pad(m)}:${pad(sec)}`, frac: '' }
    return { main: `${pad(m)}:${pad(sec)}`, frac: '.' + pad(Math.floor(ms / 10) % 100) }
  }
  const flat = ms => { const f = fmt(ms); return f.main + f.frac }
  const zeros = () => fmt(0)
  const signed = ms => (ms >= 0 ? '+' : '−') + flat(Math.abs(ms))

  let ov = null, el = {}
  const was = {}
  const set = (k, node, prop, v) => { if (was[k] !== v) { node[prop] = v; was[k] = v } }

  function build() {
    if (ov) return ov
    ov = document.createElement('div'); ov.className = 'sw-ov'
    ov.innerHTML = `<div class="sw-ov-card" role="dialog" aria-modal="true" aria-label="stopwatch" tabindex="-1">
      <button class="sw-ov-x" aria-label="close">✕</button>
      <div class="sw-top">
        <div class="sw-heads" id="sw-heads">
          <div class="sw-head" id="sw-h-total"><small>total</small><div class="sw-num" id="sw-n-t"><span id="sw-mm">00:00</span><span class="cs" id="sw-cs">.00</span></div></div>
          <div class="sw-head" id="sw-h-lap"><small>this lap</small><div class="sw-num" id="sw-n-l"><span id="sw-lmm">00:00</span><span class="cs" id="sw-lcs">.00</span></div></div>
        </div>
        <div class="sw-count" id="sw-count" hidden>0</div>
      </div>
      <div class="sw-btns">
        <button class="sw-btn go" id="sw-go">start</button>
        <button class="sw-btn" id="sw-lap">lap</button>
        <button class="sw-btn" id="sw-reset">clear</button>
      </div>
      <div class="sw-stats" id="sw-stats"></div>
      <div class="sw-laps" id="sw-laps"></div>
      <button class="sw-export" id="sw-export">👟 export to exercise</button>
    </div>`
    document.body.appendChild(ov)
    try { window.TT_NAV.mount(ov, 'stopwatch') } catch (_) {}
    const q = s => ov.querySelector(s)
    el = { card: q('.sw-ov-card'), heads: q('#sw-heads'), hTotal: q('#sw-h-total'), hLap: q('#sw-h-lap'),
           nT: q('#sw-n-t'), nL: q('#sw-n-l'), mm: q('#sw-mm'), csEl: q('#sw-cs'), lmm: q('#sw-lmm'), lcs: q('#sw-lcs'),
           count: q('#sw-count'), stats: q('#sw-stats'), laps: q('#sw-laps'),
           lap: q('#sw-lap'), go: q('#sw-go'), reset: q('#sw-reset'), exp: q('#sw-export') }
    q('.sw-ov-x').addEventListener('click', close)
    ov.addEventListener('mousedown', e => { if (e.target === ov) close() })
    document.addEventListener('keydown', e => { if (e.key === 'Escape' && ov.classList.contains('open')) close() })
    el.go.addEventListener('click', toggle)
    el.lap.addEventListener('click', lap)
    el.reset.addEventListener('click', reset)
    // ⏱ → 💪 hand the session to the exercise log; the laps ride along so wellness can ask
    // what you were doing and help you pick a MET (Sum 2026-07-21).
    el.exp.addEventListener('click', () => {
      const st = read(), E = elapsedOf(st)
      if (E <= 0) return
      try {
        parent.OZ_EXPORT_EXERCISE({ min: E / 60000, startISO: new Date(Date.now() - E).toISOString(),
          laps: (st.laps || []).slice(), source: 'stopwatch' })
      } catch (_) {}
      close()
    })
    // debounce the resize: a drag fires this continuously, and refitting mid-drag is what lets a
    // measure→layout→measure loop build up momentum. Settle first, then fit once.
    let rt = null
    window.addEventListener('resize', () => { clearTimeout(rt); rt = setTimeout(() => { was.fit = null; paint() }, 90) })
    return ov
  }

  // ── controls ──
  function toggle() {
    const s = read()
    if (s.running) { s.banked = elapsedOf(s); s.running = false; s.since = 0 }
    else { s.since = Date.now() - (s.banked || 0); s.banked = 0; s.running = true }
    write(s); paint()
  }
  function lap() { const s = read(); if (!s.running) return; s.laps = (s.laps || []).concat(elapsedOf(s)); write(s); paintLaps(s); paint() }
  function reset() { write({ running: false, since: 0, banked: 0, laps: [] }); paintLaps(read()); paint() }

  // ── FIT THE TYPE TO THE BOX (Sum: "make all time numbers fill x on their rows, then get
  //    smaller for more info on that row. if just one time, should fill x").
  //    ⚠️ MEASURE, don't model. An earlier version estimated width as chars × 0.6em and came out
  //    ~25% small — the centiseconds are .5em and the colon is narrow. Text width scales LINEARLY
  //    with font-size, so: render the real markup at a 100px reference, measure it, scale to fit.
  //    Exact for any content and any column count. Guarded by a signature so it only runs on change.
  let ruler = null
  function measure(html, cls) {
    if (!ruler) {
      ruler = document.createElement('div')
      ruler.style.cssText = 'position:absolute;left:-9999px;top:0;visibility:hidden;white-space:nowrap;width:max-content;display:flex;align-items:center'
      document.body.appendChild(ruler)
    }
    ruler.className = cls || ''
    ruler.style.fontSize = '100px'
    ruler.innerHTML = html
    return ruler.scrollWidth || ruler.offsetWidth || 0
  }
  const pxFor = (natural, boxW) => (natural > 0 ? Math.floor(100 * (boxW / natural)) : 0)

  function fit(mode, s) {
    // Base the maths on the CARD, not on .sw-heads: heads is flex:1 beside the lap counter, whose
    // own size we set from this very result — measuring it would feed back on itself and oscillate.
    // Reserve a fixed column for the counter instead.
    const cardW = el.card.clientWidth
    if (!cardW) return
    const on0 = show()
    const countRes = (lapsOn() && on0.includes('count')) ? Math.round(cardW * 0.10) : 0
    const W = cardW - 40 - 96 - (countRes ? countRes + 22 : 0)
    const Wq = Math.round(W / 12) * 12   // quantise: a few px of jitter must not restart the fit
    if (W <= 0) return
    const cols = lapCols(), laps = s.laps || [], on = show()
    const key = [mode, Wq, cols.join(), laps.length, on.join(), lapsOn(), zeros().main.length + zeros().frac.length].join('|')
    if (was.fit === key) return
    was.fit = key

    // (1) THE BIG TIME — fills its share of the row (half each when both are up)
    const per = mode === 'both' ? (Wq - 26) / 2 : Wq
    const z = zeros()
    const natural = measure(`<span>${z.main}</span><span class="cs">${z.frac}</span>`, 'sw-num')
    // No height cap: the CARD scrolls now (Sum 2026-07-21 — "card can scroll, all that has to fit
    // in view is like two rows"), so width-fill simply wins. Only a sane absolute ceiling remains.
    const px = Math.max(28, Math.min(pxFor(natural, per), 340))
    el.nT.style.fontSize = px + 'px'
    el.nL.style.fontSize = px + 'px'
    // /1.9 so three characters actually FIT the box (they were overflowing it)
    if (countRes) { el.count.style.width = countRes + 'px'; el.count.style.fontSize = Math.min(Math.round(px * 0.34), Math.round(countRes / 1.9)) + 'px' }

    // (2) THE STATS — each FILLS its share: one takes the whole row, two go half each.
    //     ⚠️ The ceiling must come from a FULL-WIDTH headline, not from `px`. In 'both' mode px is
    //     already halved (two times share the row), so a px-based cap collapsed and the stat never
    //     grew — Sum: "on both, fastest isn't growing on its row."
    const nStats = ['fastest', 'average'].filter(k => on.includes(k)).length
    if (nStats) {
      const pxFull = pxFor(natural, Wq)          // what a single time would be at full width
      const share = (Wq - 14 * (nStats - 1)) / nStats
      const sNat = measure(flat(0), 'sw-statnum')
      el.stats.style.setProperty('--sw-stat-fs', Math.max(22, Math.min(pxFor(sNat, share * 0.94), pxFull)) + 'px')
    }

    // (3) THE LAP ROWS — the whole row fills the width; more columns => smaller type, automatically
    let rowHTML = `<span class="n">00</span><span class="t">${flat(0)}</span>`
    if (cols.includes('vsavg')) rowHTML += `<span class="d">+${flat(0)}</span>`
    if (cols.includes('vsbest')) rowHTML += `<span class="d">+${flat(0)}</span>`
    const rNat = measure(rowHTML, 'sw-lap sw-lap-measure')
    // The row fills the width; laps below the fold are reached by scrolling the card.
    const lapPx = Math.max(18, Math.min(pxFor(rNat, Wq), Math.round(px * 0.62)))
    el.laps.style.setProperty('--sw-lap-fs', lapPx + 'px')
    el.laps.style.setProperty('--sw-lap-h', Math.round(lapPx * 1.45) + 'px')
  }

  // ── paint ──
  function paint() {
    if (!ov || !ov.classList.contains('open')) return
    const s = read(), E = elapsedOf(s), f = fmt(E), on = show(), mode = mainMode(), useLaps = lapsOn()
    const laps = s.laps || [], last = laps.length ? laps[laps.length - 1] : 0
    const lf = fmt(E - last)
    // laps off → the card collapses to a plain big stopwatch
    const m = useLaps ? mode : 'total'
    set('mode', el.heads, 'className', 'sw-heads' + (m === 'both' ? ' both' : ''))
    set('hT', el.hTotal, 'hidden', m === 'lap')
    set('hL', el.hLap, 'hidden', m === 'total')
    if (m !== 'lap') { set('mm', el.mm, 'textContent', f.main); set('cs', el.csEl, 'textContent', f.frac) }
    if (m !== 'total') { set('lmm', el.lmm, 'textContent', lf.main); set('lcs', el.lcs, 'textContent', lf.frac) }
    fit(m, s)
    // the lap COUNT — far right of the main line, just a number, its own toggle
    const countOn = useLaps && on.includes('count')
    set('cntH', el.count, 'hidden', !countOn)
    if (countOn) set('cntV', el.count, 'textContent', String(laps.length))
    // buttons
    set('lapBH', el.lap, 'hidden', !useLaps)
    set('go', el.go, 'textContent', s.running ? 'stop' : (E > 0 ? 'resume' : 'start'))
    if (was.run !== s.running) { el.go.classList.toggle('on', s.running); was.run = s.running }
    set('lapD', el.lap, 'disabled', !s.running)
    set('resD', el.reset, 'disabled', s.running || E === 0)
    set('expD', el.exp, 'disabled', E === 0)
    // the lap LIST is its own toggle inside `show` (Sum 2026-07-21: "one more toggle to turn off
    // lap view, and just show fastest and this one"). The master switch still governs whether laps
    // exist at all — you can keep recording them with the list hidden.
    set('lapsH', el.laps, 'hidden', !(useLaps && on.includes('laps')))
    paintStats(s, useLaps)
  }
  const splitsOf = s => { const l = s.laps || []; return l.map((t, i) => t - (l[i - 1] || 0)) }

  // stats FILL the row — one chosen = full width, two = half each (Sum)
  function paintStats(s, useLaps) {
    const on = show(), sp = splitsOf(s)
    const bits = []
    if (useLaps && sp.length) {
      if (on.includes('fastest')) bits.push(`<span><i>fastest</i>${flat(Math.min.apply(null, sp))}</span>`)
      if (on.includes('average')) bits.push(`<span><i>average</i>${flat(sp.reduce((a, b) => a + b, 0) / sp.length)}</span>`)
    }
    const html = bits.join('')
    if (was.stats !== html) { el.stats.innerHTML = html; was.stats = html }
    set('statsD', el.stats.style, 'display', bits.length ? '' : 'none')
  }

  function paintLaps(s) {
    if (!ov) return
    const cols = lapCols(), sp = splitsOf(s), laps = s.laps || []
    const best = sp.length ? Math.min.apply(null, sp) : 0, worst = sp.length ? Math.max.apply(null, sp) : 0
    const avg = sp.length ? sp.reduce((a, b) => a + b, 0) / sp.length : 0
    const cell = v => `<span class="d ${v > 0 ? 'up' : 'down'}">${signed(v)}</span>`
    let html = ''
    laps.forEach((_, i) => {
      const j = laps.length - 1 - i               // newest on top
      const split = sp[j]
      const cls = 'sw-lap' + (sp.length > 1 && split === best ? ' best' : '') + (sp.length > 1 && split === worst ? ' worst' : '')
      let cells = `<span class="n">${j + 1}</span>`
      cells += `<span class="t">${flat(cols.includes('split') ? split : laps[j])}</span>`
      if (cols.includes('vsavg')) cells += sp.length > 1 ? cell(split - avg) : '<span class="d"></span>'
      if (cols.includes('vsbest')) cells += sp.length > 1 ? cell(split - best) : '<span class="d"></span>'
      html += `<div class="${cls}">${cells}</div>`
    })
    if (was.laps !== html) { el.laps.innerHTML = html; was.laps = html }
  }

  function open() { build(); ov.classList.add('open'); try { window.TT_NAV_PLACE && window.TT_NAV_PLACE(ov) } catch (_) {}; was.fit = null; paintLaps(read()); paint(); el.card.focus() }
  function close() { if (ov) ov.classList.remove('open') }
  window.SW_CARD = { open, close }
  window.SW_FIT = { measure, pxFor }   // the timer card fits its type the same way

  setInterval(paint, 40)
})()
