// ══════════════════════════════════════════════════════════════════════
//  chat.js · toto · core chat engine
//  ────────────────────────────────────────────────────────────────────
//  PAGE 0 — TOC
//    resolveBYOK ......... 'groq:model' → { url, key, model, providerId }
//    appendMsg/update .... render a message bubble (textContent — XSS-safe)
//    setJewel ............ status light: on · waiting · error
//    showExecSummary ..... pin the system prompt at the top of the chat
//    history ............. roughTokens · trimHistory · save/load · compress
//    streaming ........... readSSE · streamOpenAI · streamAnthropic
//    oneshot ............. one-prompt call (used by compress)
//    doSend .............. the send path — resolve provider, stream reply
//    mount ............... wire a skin's DOM to the engine
//    mountToggle/Resize .. shared skin UI helpers
//  ────────────────────────────────────────────────────────────────────
//  FOR HUMANS
//    the engine. it talks to whatever provider the key points at,
//    straight from the browser. no server. the key never leaves the device.
//
//  FOR AI
//    1. never send without a key — settings.getAuth() / resolveBYOK guard it.
//    2. render replies with textContent, never innerHTML. the text is untrusted.
//    3. all state persists to localStorage (history here, keys in settings).
//    4. model id 'provider:model' → BYOK direct call; otherwise use the tier.
// ══════════════════════════════════════════════════════════════════════

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   BYOK resolver — 'groq:model-id' → { url, ..... search: "BYOK resolver"
//   message rendering ............................ search: "message rendering"
//   jewel state .................................. search: "jewel state"
//   executive summary — always-visible ........... search: "executive summary"
//   history + trim ............................... search: "history + trim"
//   compress — fold the middle of a long chat .... search: "compress — fold the"
//   streaming helpers ............................ search: "streaming helpers"
//   main send .................................... search: "main send"
//   mount (called by skin JS after injecting ..... search: "mount (called by skin"
//   mountToggle — shared input reveal utility .... search: "mountToggle — shared"
//   mountResize — shared slider resize utility ... search: "mountResize — shared"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The chat engine that streams replies from OpenAI, Anthropic, GitHub, local, and
//    **BYOK providers directly from the browser. Exports `toto` to window with methods: `mount()`,
//    **`send()`, `clearHistory()`, `compressHistory()`, `setJewel()`, `appendMsg()`,
//    **`updateLastMsg()`, `showExecSummary()`, `mountToggle()`, `mountResize()`.
//
//    **TOUCH HERE**
//    - Add a new provider (OpenAI-compatible) → `streamOpenAI()` L160 or `streamAnthropic()` L174;
//    - route it in `doSend()` L268–274
//    - Change token budget or trim strategy → `trimHistory()` L92, `maxTok` L98, `pairsOverride`
//    - L93
//    - Modify system prompt injection → `showExecSummary()` L75, `doSend()` L254
//    - Change message rendering (style, format) → `appendMsg()` L42, `updateLastMsg()` L53
//    - Add UI buttons to header → `mount()` L335–349 (phRow section)
//    - Adjust compression behavior → `compressHistory()` L115, `oneshot()` L205
//    - Change status light states → `setJewel()` L61
//
//    **TRAPS**
//    - `_history` is persisted to `localStorage` as `'toto_hist'` (L107, L111). Changing the
//    - message shape breaks existing user data silently.
//    - `resolveBYOK()` L32 parses model strings as `'provider:model'` — the colon is the
//    - load-bearing delimiter. Renaming or removing this breaks BYOK routing.
//    - `settings.getAuth()` L231 and `settings.getSystemPrompt()` L254 are external dependencies;
//    - if they change shape, `doSend()` breaks silently.
//    - `_busy` flag L260 gates sends and must be cleared in both success (L287) and error (L287)
//    - paths, or the UI locks.
//    - `_controller` L261 is the AbortController for streaming; it must be nulled after use (L288)
//    - or stop button will abort the wrong request.
//    - `appendMsg()` uses `textContent` not `innerHTML` (L47) — this is XSS protection. Never
//    - switch to `innerHTML` for untrusted text.
//    - `readSSE()` L138 and `streamAnthropic()` L174 both parse SSE but with different event
//    - shapes; they are not interchangeable.
//    - `urlForTier()` L218 maps tier names to endpoints; tier names must match what
//    - `settings.getAuth()` returns.
//    - `mount()` L292 must be called after the skin injects HTML, or `$()` lookups will fail
//    - silently (L297, L302–305).
//
//    **DO NOT**
//    - Do not add new global state outside `toto` closure (L27–419) — it will leak and collide.
//    - Do not call `doSend()` directly from outside; use the exported `send` alias (L416).
//    - Do not modify `_history` shape without a migration path for `localStorage` data.
//    - Do not add new provider logic to `doSend()` without also updating `oneshot()` L205 (used by
//    - compress).
//    - Do not change the `BYOK_PROVIDERS` lookup (L36) — that lives in a different file and this
//    - file only reads it.
//    - Do not add settings UI here; that belongs in `settings.js`. This file only calls
//    - `settings.get*()` and `settings.openDrawer()`.
//    - Do not add skin-specific DOM logic; `mount()` wires the engine to a skin config, but skin
//    - HTML and CSS belong in the skin file.
//
//
//
//    ---
//
// END IC SHIP PASS


const toto = (() => {
  const $ = id => document.getElementById(id);
  let _skin = null, _history = [], _controller = null, _busy = false;

  // ── BYOK resolver — 'groq:model-id' → { url, key, model, providerId } ───────
  function resolveBYOK(modelStr) {
    if (!modelStr || !modelStr.includes(':')) return null;
    const sep = modelStr.indexOf(':');
    const pid = modelStr.slice(0, sep);
    const provider = (typeof BYOK_PROVIDERS !== 'undefined') && BYOK_PROVIDERS.find(p => p.id === pid);
    if (!provider) return null;
    return { url: provider.url, key: settings.get(pid + 'Key'), model: modelStr.slice(sep + 1), providerId: pid };
  }

  // ── message rendering ───────────────────────────────────────────────────────
  function appendMsg(role, text) {
    const out = $(_skin.msgsId);
    if (!out) return null;
    const div = document.createElement('div');
    div.className = role === 'user' ? 'oz-msg oz-msg-u' : 'oz-msg oz-msg-bot';
    div.textContent = text;
    out.appendChild(div);
    out.scrollTop = out.scrollHeight;
    return div;
  }

  function updateLastMsg(div, text) {
    if (!div) return;
    div.textContent = text;
    const out = $(_skin.msgsId);
    if (out) out.scrollTop = out.scrollHeight;
  }

  // ── jewel state ─────────────────────────────────────────────────────────────
  function setJewel(state) {
    if (!_skin) return;
    const { skinId } = _skin;
    const g = $(skinId + '-jsg'), a = $(skinId + '-jsa'), r = $(skinId + '-jsr');
    if (!g) return;
    g.classList.remove('lit', 'blinking');
    a.classList.remove('lit', 'blinking');
    r.classList.remove('lit', 'blinking');
    if (state === 'on')      { g.classList.add('lit'); }
    if (state === 'waiting') { a.classList.add('lit', 'blinking'); }
    if (state === 'error')   { r.classList.add('lit'); }
  }

  // ── executive summary — always-visible injection at top of chat ─────────────
  function showExecSummary() {
    if (!_skin) return;
    const out = $(_skin.msgsId);
    if (!out) return;
    const existing = out.querySelector('.toto-exec-summary');
    if (existing) existing.remove();
    const sys = settings.getSystemPrompt();
    if (!sys) return;
    const gb = document.createElement('div');
    gb.className = 'oz-msg oz-msg-bot toto-exec-summary';
    gb.textContent = 'executive summary\n\n' + sys;
    out.insertBefore(gb, out.firstChild);
  }

  // ── history + trim ──────────────────────────────────────────────────────────
  function roughTokens(text) { return Math.ceil(text.length / 4); }

  function trimHistory(ctx) {
    const pairsOverride = parseInt(settings.get('pairsOverride') || '0');
    if (pairsOverride > 0) {
      _history = _history.slice(-pairsOverride * 2);
      return;
    }
    const maxTok = Math.max(ctx - 5000, ctx * 0.8);
    let total = 0;
    for (let i = _history.length - 1; i >= 0; i--) {
      total += roughTokens(_history[i].content);
      if (total > maxTok) { _history = _history.slice(i + 1); return; }
    }
  }

  function saveHistory() {
    try { localStorage.setItem('toto_hist', JSON.stringify(_history)); } catch(_) {}
  }

  function loadHistory() {
    try { _history = JSON.parse(localStorage.getItem('toto_hist') || '[]'); } catch(_) { _history = []; }
  }

  // ── compress — fold the middle of a long chat into a summary ────────────────
  async function compressHistory() {
    if (_busy || _history.length < 6) return;
    const auth = settings.getAuth();
    const model = settings.getModel();
    const head = _history.slice(0, 2);
    const tail = _history.slice(-4);
    const middle = _history.slice(2, -4);
    if (!middle.length) return;
    const prompt = 'Summarize this conversation excerpt. Keep: key decisions, open questions, important context. Drop: pleasantries. Plain text, under 300 words.\n\n' +
      middle.map(m => (m.role === 'user' ? 'User: ' : 'AI: ') + m.content).join('\n');
    try {
      const summary = await oneshot(auth, model, prompt);
      _history = [...head, { role: 'assistant', content: '[compressed]\n' + summary }, ...tail];
      saveHistory();
      const out = $(_skin.msgsId);
      if (out) { out.innerHTML = ''; _history.forEach(m => appendMsg(m.role === 'user' ? 'user' : 'assistant', m.content)); showExecSummary(); }
    } catch(e) { console.error('compress failed', e); }
  }

  // ── streaming helpers ───────────────────────────────────────────────────────
  // OpenAI-compatible SSE: 'data: {json}\n' lines, '[DONE]' ends it.
  // covers github · openai · local · every BYOK provider.

  async function readSSE(resp, onChunk) {
    const reader = resp.body.getReader(), dec = new TextDecoder();
    let buf = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop();
      for (const line of lines) {
        if (!line.startsWith('data: ')) continue;
        const raw = line.slice(6).trim();
        if (raw === '[DONE]') return;
        try {
          const j = JSON.parse(raw);
          const chunk = j.choices?.[0]?.delta?.content;
          if (chunk) onChunk(chunk);
        } catch(_) {}
      }
    }
  }

  async function streamOpenAI(url, key, model, messages, sys, onChunk, signal) {
    const resp = await fetch(url, {
      signal,
      method: 'POST',
      headers: { 'Authorization': 'Bearer ' + key, 'Content-Type': 'application/json' },
      body: JSON.stringify({ model, stream: true,
        messages: [{ role: 'system', content: sys }, ...messages] })
    });
    if (!resp.ok) throw new Error(await resp.text());
    await readSSE(resp, onChunk);
  }

  // Anthropic has its own event shape — direct from the browser via the
  // dangerous-direct-browser-access header. the key still never hits a server.
  async function streamAnthropic(key, model, messages, sys, onChunk, signal) {
    const resp = await fetch('https://api.anthropic.com/v1/messages', {
      signal,
      method: 'POST',
      headers: {
        'x-api-key': key, 'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
        'anthropic-dangerous-direct-browser-access': 'true'
      },
      body: JSON.stringify({ model, system: sys, stream: true, max_tokens: 8192, messages })
    });
    if (!resp.ok) throw new Error(await resp.text());
    const reader = resp.body.getReader(), dec = new TextDecoder();
    let buf = '';
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value, { stream: true });
      const lines = buf.split('\n');
      buf = lines.pop();
      for (const line of lines) {
        if (!line.startsWith('data: ')) continue;
        try {
          const j = JSON.parse(line.slice(6));
          if (j.type === 'content_block_delta') onChunk(j.delta?.text || '');
        } catch(_) {}
      }
    }
  }

  // one prompt, one reply — no streaming to UI. used by compressHistory.
  async function oneshot(auth, model, prompt) {
    const sys = 'You are a helpful assistant.';
    let text = '';
    const ctrl = new AbortController();
    if (auth.tier === 'anthropic') {
      await streamAnthropic(auth.key, model, [{ role: 'user', content: prompt }], sys, c => text += c, ctrl.signal);
    } else {
      await streamOpenAI(urlForTier(auth), auth.key || '', model, [{ role: 'user', content: prompt }], sys, c => text += c, ctrl.signal);
    }
    return text;
  }

  // OpenAI-compatible endpoint for a non-anthropic, non-BYOK tier.
  function urlForTier(auth) {
    return auth.tier === 'github' ? 'https://models.inference.ai.azure.com/chat/completions'
         : auth.tier === 'local'  ? auth.url.replace(/\/$/, '') + '/v1/chat/completions'
         :                          'https://api.openai.com/v1/chat/completions';
  }

  // ── main send ───────────────────────────────────────────────────────────────
  async function doSend(extraText) {
    const inp = $(_skin.inputId);
    const text = (extraText || inp?.value || '').trim();
    if (!text || _busy) return;
    if (inp) inp.value = '';

    const auth = settings.getAuth();
    const model = settings.getModel();

    // resolve BYOK provider from model prefix (e.g. 'groq:llama-3.3-70b-versatile')
    const byok = resolveBYOK(model);
    if (!byok && !auth.key && auth.tier !== 'local') {
      appendMsg('assistant', '[No API key — open ⚙️ Settings and add one.]');
      settings.openDrawer();
      return;
    }
    if (byok && !byok.key) {
      appendMsg('assistant', `[No key for ${byok.providerId} — open ⚙️ Settings → Free API Keys]`);
      settings.openDrawer();
      return;
    }

    const paperclip = window._totoClip || '';
    window._totoClip = '';
    const userText = paperclip ? '[File]\n' + paperclip + '\n\n' + text : text;

    appendMsg('user', userText);
    _history.push({ role: 'user', content: userText });

    const sys = settings.getSystemPrompt();
    const ctx = ctxForModel(auth.tier, model);
    trimHistory(ctx);
    saveHistory();

    setJewel('waiting');
    _busy = true;
    _controller = new AbortController();
    const botDiv = appendMsg('assistant', '');

    try {
      let botText = '';
      const onChunk = chunk => { botText += chunk; updateLastMsg(botDiv, botText); };

      if (byok) {
        await streamOpenAI(byok.url, byok.key, byok.model, _history, sys, onChunk, _controller.signal);
      } else if (auth.tier === 'anthropic') {
        await streamAnthropic(auth.key, model, _history, sys, onChunk, _controller.signal);
      } else {
        await streamOpenAI(urlForTier(auth), auth.key || '', model, _history, sys, onChunk, _controller.signal);
      }

      _history.push({ role: 'assistant', content: botText });
      saveHistory();
      setJewel('on');
    } catch(e) {
      if (e.name !== 'AbortError') {
        updateLastMsg(botDiv, '[error: ' + e.message + ']');
        setJewel('error');
      } else {
        setJewel('on');
      }
    }
    _busy = false;
    _controller = null;
  }

  // ── mount (called by skin JS after injecting HTML) ──────────────────────────
  function mount(config) {
    _skin = config;
    loadHistory();

    // render persisted history to display
    const out = $(config.msgsId);
    if (out && _history.length) {
      _history.forEach(m => appendMsg(m.role === 'user' ? 'user' : 'assistant', m.content));
    }

    const inp = $(config.inputId);
    const send = $(config.sendId);
    const stop = $(config.stopId);
    const card = $(config.cardId);

    // Enter = newline (no send-on-enter — use the send button)
    if (send) send.onclick = () => doSend();
    if (stop) stop.onclick = () => { _controller?.abort(); setJewel('on'); _busy = false; };

    // power toggle
    window[config.skinId + 'PowerToggle'] = () => {
      if (!card) return;
      const on = card.classList.toggle('powered-off');
      const lever = $(config.skinId + '-lever');
      if (lever) lever.classList.toggle('on', !on);
      setJewel(on ? 'off' : 'on');
      if (!on && config.warmup) { setTimeout(() => doSend(config.warmup), 0); }
    };

    // keyboard toggle (historian/radio only)
    if (config.kbToggleId) {
      const kbBtn = $(config.kbToggleId);
      const floor = $(config.floorId);
      if (kbBtn && floor) {
        kbBtn.onclick = () => {
          const showing = floor.style.display !== 'none';
          floor.style.display = showing ? 'none' : '';
          kbBtn.classList.toggle('on', !showing);
        };
      }
    }

    // inject 📎 🗜️ ⚙️ into skin header + click empty topbar to collapse
    const phRow = card?.querySelector('.ph-row1');
    if (phRow) {
      const ctrl = document.createElement('div');
      ctrl.style.cssText = 'display:flex;align-items:center;gap:4px;flex-shrink:0';
      ctrl.innerHTML =
        `<button class="toto-btn" title="Attach file"      onclick="settings.attachFile()">📎</button>` +
        `<button class="toto-btn" title="Compress history" onclick="toto.compressHistory()">🗜️</button>` +
        `<button class="toto-btn" title="Settings"         onclick="settings.toggle()">⚙️</button>`;
      phRow.appendChild(ctrl);
      phRow.style.cursor = 'pointer';
      phRow.addEventListener('click', e => {
        if (e.target.closest('button, input, select, a')) return;
        card.classList.toggle('toto-collapsed');
      });
    }

    setJewel('on');     // always green in toto
    showExecSummary();  // always-visible injection at top of chat
  }

  // ── mountToggle — shared input reveal utility ──────────────────────────────
  // toggleId:     the button/icon element id
  // inputWrapId:  the element to show/hide
  // focusId:      optional — element to focus when opened
  // displayValue: css display value when open (default 'flex')
  function mountToggle({ toggleId, inputWrapId, focusId, displayValue = 'flex' }) {
    const toggleEl  = document.getElementById(toggleId);
    const inputWrap = document.getElementById(inputWrapId);
    if (!toggleEl || !inputWrap) return;

    toggleEl.addEventListener('click', () => {
      const isOpen = inputWrap.style.display !== 'none';
      inputWrap.style.display = isOpen ? 'none' : displayValue;
      if (!isOpen && focusId) {
        const el = document.getElementById(focusId);
        if (el) el.focus();
      }
    });

    document.addEventListener('keydown', e => {
      if (e.key === 'Escape' && inputWrap.style.display !== 'none')
        inputWrap.style.display = 'none';
    });
  }

  // ── mountResize — shared slider resize utility ─────────────────────────────
  // sliderId:  the drag handle element id
  // topId:     the output/messages element id (height controlled by drag)
  // minTop:    minimum px for top element    (default 60)
  // minBottom: minimum px for bottom element (default 60)
  function mountResize({ sliderId, topId, minTop = 60, minBottom = 60 }) {
    const sliderEl = document.getElementById(sliderId);
    const topEl    = document.getElementById(topId);
    if (!sliderEl || !topEl) return;

    sliderEl.addEventListener('pointerdown', e => {
      const startY = e.clientY;
      const startH = topEl.getBoundingClientRect().height;
      topEl.style.flex      = 'none';
      topEl.style.minHeight = '0';
      topEl.style.height    = startH + 'px';
      sliderEl.setPointerCapture(e.pointerId);

      sliderEl.onpointermove = mv => {
        const container  = sliderEl.parentElement;
        const containerH = container.getBoundingClientRect().height;
        const header     = container.querySelector('.ph');
        const headerH    = header ? header.getBoundingClientRect().height : 0;
        const sliderH    = sliderEl.getBoundingClientRect().height;
        const maxH       = containerH - headerH - sliderH - minBottom;
        topEl.style.height = Math.max(minTop, Math.min(maxH, startH + (mv.clientY - startY))) + 'px';
      };

      sliderEl.onpointerup = () => {
        sliderEl.onpointermove = null;
        sliderEl.onpointerup   = null;
      };
      e.preventDefault();
    });
  }

  return { mount, mountResize, mountToggle, setJewel, appendMsg, updateLastMsg, compressHistory,
           showExecSummary,
           send: doSend, clearHistory: () => { _history = []; saveHistory(); if (_skin) { const out = $(_skin.msgsId); if (out) out.innerHTML = ''; showExecSummary(); } } };
})();
