// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   WHY THERE ARE NO VECTORS HERE, AND WHY THAT .... search: "WHY THERE ARE NO"
//   WHAT IT SEARCHES — THE GLOSSES, NOT THE CODE ... search: "WHAT IT SEARCHES — THE"
//   NO BROKEN DEPENDENCY (the sync doctrine) ....... search: "NO BROKEN DEPENDENCY"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the BM25 search algorithm over the map
//    **index. It exposes `window.MC_MAP` with methods `ask()`, `search()`, `load()`, and properties
//    **`meta` and `size`. Monaco's shell uses this to offer map search as a tool; nothing else in
//    **Monaco depends on it.
//
//    **TOUCH HERE** —
//    - Change which stopwords are filtered from queries → `MAP_STOP` L57
//    - Change BM25 constants (k1, b) or scoring logic → `mapSearch()` L75, specifically L81 and L98
//    - Change how tokens are extracted (regex, compound splitting) → `mapTokens()` L60,
//    - specifically L61 and L68
//    - Change result limit or format of output lines → `mapFormat()` L107, L108
//    - Change which row fields are searched → `mapSearch()` L82 (currently searches `r.f`, `r.t`,
//    - `r.k`)
//    - Change fetch URLs or retry logic for the index → `mapLoad()` L39, specifically L42
//
//    **TRAPS** —
//    - `MAP_ROWS`, `MAP_META`, `MAP_TRIED` (L36) are module-level state. Renaming them breaks
//    - `window.MC_MAP.meta` and `window.MC_MAP.size` (L125–126).
//    - The index shape is a contract with the host: rows must have fields `f` (file), `a` and `b`
//    - (line range), `t` (title), `k` (keywords array). Changing these breaks any existing
//    - `map-index.json` (L47, L82, L100, L108).
//    - `mapTokens()` is called three times in `mapSearch()` (L78–79, L82) with different `drop`
//    - flags. The fallback on L79 is load-bearing: a query of all stopwords still gets results.
//    - Prefix matching (L93) is intentional and documented in the comment above it. Removing it
//    - silently breaks "burn" → "burned" behavior.
//    - The `hits` array (L89, L95, L100, L108) is the explanation layer. Removing it makes results
//    - unexplainable.
//
//    **DO NOT** —
//    - Do not add a retry loop to `mapLoad()` (L39–51). The sync doctrine (L29) forbids it: one
//    - fetch, one flag, honest failure.
//    - Do not move the index data into this file or fetch from a different card. The index is
//    - host-supplied data; this file is generic code.
//    - Do not add memory or caching beyond `MAP_TRIED`. The index is small and fetched once.
//    - Do not change the `window.MC_MAP` API shape without updating the shell that calls it.
//
//
//
//    ---
//
// END IC SHIP PASS

  // ═══════════════════════════════════════════════════════════════════════════════════════════════
  //  THE MAP — ask the codebase a question in English, get file:line back.
  //  Sum 2026-07-30: "the vector thingy — I have wanted that but didn't understand it… sounds like
  //  a .5 layer to me. am I wrong? any reason not to do that? isn't squiggy begging for that tool?"
  //
  //  He was right that squiggy is begging for it, and right that it is half a layer. He was also
  //  right, without knowing it, to be suspicious of vectors.
  //
  //  ── WHY THERE ARE NO VECTORS HERE, AND WHY THAT IS THE STRONGER BUILD ─────────────────────────
  //  An embedding buys you ONE thing: ranking that generalises across strangers. That is a
  //  million-user problem. This is a user of one, over 349 files he wrote himself, in his own
  //  vocabulary. For that, BM25 over his own words wins outright:
  //
  //    exact          "burned" finds burned.js. an embedding might rank "disabled" higher.
  //    instant        no model at query time. no server. no 400MB of weights. no cold start.
  //    explainable    it shows WHICH words matched, so a wrong hit teaches you the right word.
  //    honest         it cannot hallucinate a file. it can only fail to find one, and say so.
  //
  //  Sum's own frame: "everything but the million-user ranking, tuned to a user of one, using js
  //  and determinism." This is that, exactly. Vectors stay available as a later addition for the
  //  day the corpus stops being his — they are not a prerequisite, they are an upgrade.
  //
  //  ── WHAT IT SEARCHES — THE GLOSSES, NOT THE CODE ─────────────────────────────────────────────
  //  grep already searches the code, and grep is better at it than anything here would be. This
  //  searches LAYER 3 of the map: one row per section, carrying THE AUTHOR'S OWN DIVIDER TEXT and
  //  a real line range. So it answers the question grep cannot — not "where does this string
  //  appear" but "where does this CONCERN live" — and it answers with an address.
  //
  //  ── NO BROKEN DEPENDENCY (the sync doctrine) ─────────────────────────────────────────────────
  //  Monaco ships standalone and is sold standalone. So the CODE here is generic — a searcher over
  //  whatever index it finds — and the INDEX is data the host supplies. No index, no error: the
  //  feature reports itself missing in one honest sentence and everything else still works. It
  //  never reaches for another card, another agent, or window.parent.
  // ═══════════════════════════════════════════════════════════════════════════════════════════════

  let MAP_ROWS = null, MAP_META = null, MAP_TRIED = false

  // the index is DATA, and data is allowed to be absent. one fetch, one flag, never a retry storm.
  async function mapLoad() {
    if (MAP_TRIED) return MAP_ROWS
    MAP_TRIED = true
    for (const url of ['map-index.json', '../map-index.json', '../../map-index.json']) {
      try {
        const r = await fetch(url)
        if (!r.ok) continue
        const j = await r.json()
        if (j && Array.isArray(j.rows)) { MAP_ROWS = j.rows; MAP_META = j; break }
      } catch (_) {}
    }
    return MAP_ROWS
  }

  // Stopped words are dropped from the QUERY only, never from the rows. BM25's idf already makes
  // them nearly worthless to the score — but they still show up in the `hits` list, and the hits
  // list is the explanation. "matched: the, for, does" teaches the reader nothing and makes a good
  // answer look like a coincidence. An explainable searcher has to keep its explanation clean.
  const MAP_STOP = new Set(('the a an and or of to in for on is it be with that this from at by as ' +
    'not new if else how does do can what where when why i my we you it its'). split(' '))

  function mapTokens(s, drop) {
    const raw = String(s || '').toLowerCase().match(/[a-z0-9_$-]{2,}/g) || []
    // A compound is indexed BOTH ways. `format-blind` must answer to "format", to "blind", and to
    // itself — searching for one half of a name the author hyphenated is the normal case, not the
    // edge case, and prefix credit alone cannot reach the second half.
    const t = []
    for (const w of raw) {
      t.push(w)
      if (/[-_]/.test(w)) for (const p of w.split(/[-_]+/)) if (p.length > 1) t.push(p)
    }
    return drop ? t.filter(w => !MAP_STOP.has(w)) : t
  }

  // BM25. k1 damps a word repeated in one row; b damps a row that is simply longer than the rest.
  // The constants are the standard ones — they are tuned for prose and these rows ARE prose.
  function mapSearch(query, limit) {
    const rows = MAP_ROWS
    if (!rows || !rows.length) return []
    let q = mapTokens(query, true)
    if (!q.length) q = mapTokens(query)      // a query that is ALL stopwords still deserves an answer
    if (!q.length) return []
    const N = rows.length, k1 = 1.5, b = 0.75
    const docs = rows.map(r => mapTokens(r.f + ' ' + r.t + ' ' + (r.k || []).join(' ')))
    const avg = docs.reduce((a, d) => a + d.length, 0) / N
    const df = {}
    for (const d of docs) for (const w of new Set(d)) df[w] = (df[w] || 0) + 1
    const out = []
    for (let i = 0; i < N; i++) {
      let score = 0
      const hits = []
      for (const t of new Set(q)) {
        // a prefix counts: "burn" should find "burned". an exact hit is still worth more.
        let tf = 0
        for (const w of docs[i]) if (w === t) tf += 1; else if (w.startsWith(t) || t.startsWith(w)) tf += 0.5
        if (!tf) continue
        hits.push(t)
        const n = df[t] || 0.5
        const idf = Math.log(1 + (N - n + 0.5) / (n + 0.5))
        score += idf * (tf * (k1 + 1)) / (tf + k1 * (1 - b + b * docs[i].length / avg))
      }
      if (score > 0) out.push({ ...rows[i], score, hits })
    }
    out.sort((a, c) => c.score - a.score)
    return out.slice(0, limit || 8)
  }

  // one line per hit, and it MUST carry the address — an answer without a file:line is a rumour.
  function mapFormat(res) {
    return res.map(r => `${r.f}:${r.a}-${r.b}  ${r.t}   [${r.hits.join(' ')}]`).join('\n')
  }

  async function mapAsk(query, limit) {
    await mapLoad()
    if (!MAP_ROWS) return { ok: false, text: 'no map in this build — cards/monaco needs map-index.json beside it. everything else still works.' }
    const res = mapSearch(query, limit)
    if (!res.length) return { ok: true, hits: [], text: `nothing in the map matches "${query}". try one of the author's own words — the index is built from his dividers, not from a taxonomy.` }
    return { ok: true, hits: res, text: mapFormat(res) }
  }

  // exposed so the shell can offer it as a TOOL. additive: nothing in Monaco requires this to exist,
  // and nothing outside Monaco is required for it to work.
  window.MC_MAP = {
    ask: mapAsk,
    search: mapSearch,
    load: mapLoad,
    get meta() { return MAP_META },
    get size() { return MAP_ROWS ? MAP_ROWS.length : 0 },
  }
