// stopwatch.js — the SEALED engine. the robust pattern the last build never got:
// time is derived from a START TIMESTAMP + an accumulator, never counted up tick by
// tick — so a throttled/background setInterval can't freeze or drift it (the render
// just reads elapsed()). one always-visible page, no injection into the clock's
// shared DOM. two faces (analog SVG / digital), plus interval mode with beeps.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   build the analog tick ring + numerals (once) ... search: "build the analog tick"
//   state — time is a function of these, never ..... search: "state — time is a"
//   face analog vs digital (settings); default ..... search: "face analog vs digital"
//   PUBLISH to the clock's time-tools bar (Sum ..... search: "PUBLISH to the clock's"
//   beep (WebAudio, sealed — no asset) ............. search: "beep (WebAudio, sealed"
//   format ......................................... search: "format"
//   interval config + phase machine (derived ....... search: "interval config + phase"
//   render ......................................... search: "render"
//   the loop — top level, reads live state ......... search: "the loop — top level,"
//   controls ....................................... search: "controls"
//   laps ........................................... search: "laps"
//   mode + face wiring ............................. search: "mode + face wiring"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the stopwatch engine: state management
//    **(running/stopped, elapsed time, laps), two interval modes (watch and interval timer), and
//    **rendering to DOM elements with IDs `sw-*`. It exports nothing; it seals itself in an IIFE
//    **and owns all behavior via event listeners on buttons with class `sw-mode` and IDs `sw-go`,
//    **`sw-lap`, `sw-reset`.
//
//    **TOUCH HERE** —
//    - Change interval phase timings (prep/work/rest/rounds defaults) → `cfg()` L80
//    - Change beep sounds or frequencies → `beep()` L57, `beeps()` L68, or the calls at L118–120,
//    - L124
//    - Change time display format (MM:SS.CS) → `fmt()` L71 or `fmtClock()` L75
//    - Change which DOM elements render to → the `$()` calls at L92–93 and L158
//    - Change the render loop speed (33ms) → `setInterval(render, 33)` L129
//    - Add or remove lap tracking logic → `renderLaps()` L159, the laps array mutation at L155, or
//    - `reset()` L148
//    - Switch between analog/digital faces → `face()` L41 (currently hardcoded to 'digital'; analog
//    - code path exists at L103, L179–182)
//
//    **TRAPS** —
//    - `elapsed()` at L38 is the load-bearing time source: it derives time from `t0` (start
//    - timestamp) and `acc` (banked ms), never counts ticks. Changing this breaks drift-proofing.
//    - `publish()` at L48 writes to `localStorage` key `'clock-stopwatch'` with a specific shape
//    - (L51). The bar iframe reads this; shape changes orphan the bar's display.
//    - `phaseAt()` L81 computes phase transitions; its `key` field (L82, L87–88) is compared at
//    - L117 to trigger beeps. Changing key format silently breaks transition detection.
//    - `lastKey` and `lastTick` at L94 are state flags for beep deduplication; they must be reset
//    - together at L148.
//    - `mode` at L32 gates behavior: 'watch' vs 'interval' control which UI elements show (L138,
//    - L144, L160, L179–182, L187–188). Changing mode names requires updates in at least 6 places.
//    - `cfg()` reads from `localStorage` keys `'sw-work'`, `'sw-rest'`, `'sw-rounds'`, `'sw-prep'`
//    - (L80). User settings are persisted there; renaming breaks existing configs.
//    - `face()` at L41 is hardcoded to return `'digital'`; the analog path (L103, L179–182) is dead
//    - code but still wired. Uncommenting analog requires CSS and SVG elements to exist.
//
//    **DO NOT** —
//    - Do not rename the DOM element IDs (`sw-*`); they are the contract with HTML.
//    - Do not change the `localStorage` key names (`'clock-stopwatch'`, `'sw-work'`, etc.) without
//    - a migration.
//    - Do not move the `setInterval(render, 33)` call or the event listener setup (L153–155, L191,
//    - L194–195); they are the engine's heartbeat and boot sequence.
//    - Do not add accumulator-style time counting (e.g., `elapsed++` in the loop); the whole design
//    - avoids it.
//    - Do not add new state variables that aren't derived from `t0`, `acc`, `running`, `mode`, or
//    - `laps`; they will drift or desync.
//    - Styling, HTML structure, and the clock bar integration belong in separate files; do not add
//    - CSS or change element hierarchy here.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  const $ = id => document.getElementById(id)
  const pad = (n, w) => String(n).padStart(w || 2, '0')
  const num = (k, d) => { const v = localStorage.getItem(k); return v == null || v === '' ? d : (isNaN(+v) ? d : +v) }

  // ── build the analog tick ring + numerals (once) ──
  const ticks = $('sw-ticks')
  for (let i = 0; i < 60; i++) {
    const a = (i * 6 - 90) * Math.PI / 180, major = i % 5 === 0
    const r1 = 88, r2 = major ? 76 : 82
    const ln = document.createElementNS('http://www.w3.org/2000/svg', 'line')
    ln.setAttribute('class', 'tick' + (major ? ' major' : ''))
    ln.setAttribute('x1', (100 + Math.cos(a) * r1).toFixed(1)); ln.setAttribute('y1', (100 + Math.sin(a) * r1).toFixed(1))
    ln.setAttribute('x2', (100 + Math.cos(a) * r2).toFixed(1)); ln.setAttribute('y2', (100 + Math.sin(a) * r2).toFixed(1))
    ticks.appendChild(ln)
  }
  ;[[0, 0], [15, 90], [30, 180], [45, 270]].forEach(([n, deg]) => {
    const a = (deg - 90) * Math.PI / 180, r = 66
    const t = document.createElementNS('http://www.w3.org/2000/svg', 'text')
    t.setAttribute('class', 'num'); t.setAttribute('x', (100 + Math.cos(a) * r).toFixed(1))
    t.setAttribute('y', (100 + Math.sin(a) * r + 4).toFixed(1)); t.textContent = n
    ticks.appendChild(t)
  })

  // ── state — time is a function of these, never an accumulator loop ──
  let mode = 'watch'          // 'watch' | 'interval'
  let running = false
  let t0 = 0                  // performance.now() at last start
  let acc = 0                 // ms banked before the current run
  let laps = []               // total-ms at each lap
  const now = () => performance.now()
  const elapsed = () => acc + (running ? now() - t0 : 0)

  // ── face ── analog vs digital (settings); default digital ("a clock looks like a clock")
  const face = () => 'digital'   // ANALOG KILLED (Sum 2026-07-21). digital only.

  // ── PUBLISH to the clock's time-tools bar (Sum 2026-07-21: "stopwatch isn't showing up on bar").
  //    the bar lives in another iframe, so the handoff is localStorage — and it must be wall-clock
  //    (Date.now), not performance.now, to mean anything over there. shape: elapsed = banked +
  //    (running ? Date.now()-since : 0) — the same drift-proof trick, portable. written on STATE
  //    CHANGES only (never per frame); the bar derives the ticking readout itself. ──
  function publish() {
    if (mode !== 'watch') return                       // interval mode doesn't own the stopwatch readout
    const e = elapsed()
    const rec = running ? { running: true, banked: 0, since: Date.now() - e } : { running: false, banked: e, since: 0 }
    try { localStorage.setItem('clock-stopwatch', JSON.stringify(rec)) } catch (_) {}
  }

  // ── beep (WebAudio, sealed — no asset) ──
  let ac
  function beep(freq, dur, vol) {
    try {
      ac = ac || new (window.AudioContext || window.webkitAudioContext)()
      const o = ac.createOscillator(), g = ac.createGain()
      o.type = 'sine'; o.frequency.value = freq; o.connect(g); g.connect(ac.destination)
      const t = ac.currentTime
      g.gain.setValueAtTime(0, t); g.gain.linearRampToValueAtTime(vol || 0.3, t + 0.01)
      g.gain.exponentialRampToValueAtTime(0.0001, t + (dur || 0.15))
      o.start(t); o.stop(t + (dur || 0.15) + 0.02)
    } catch (_) {}
  }
  const beeps = (n, freq, gap) => { for (let i = 0; i < n; i++) setTimeout(() => beep(freq, 0.12), i * (gap || 160)) }

  // ── format ──
  function fmt(ms) {   // MM:SS.CS
    const cs = Math.floor(ms / 10), s = Math.floor(cs / 100), m = Math.floor(s / 60)
    return { m: pad(m), s: pad(s % 60), cs: pad(cs % 100) }
  }
  function fmtClock(secs) {   // for countdowns: M:SS
    secs = Math.max(0, Math.ceil(secs)); return pad(Math.floor(secs / 60)) + ':' + pad(secs % 60)
  }

  // ── interval config + phase machine (derived from elapsed) ──
  const cfg = () => ({ work: num('sw-work', 30), rest: num('sw-rest', 15), rounds: num('sw-rounds', 8), prep: num('sw-prep', 5) })
  function phaseAt(E, c) {   // E = elapsed seconds
    if (E < c.prep) return { phase: 'prep', round: 0, left: c.prep - E, key: 'prep' }
    let e = E - c.prep, cyc = c.work + c.rest, ri = Math.floor(e / cyc)
    if (ri >= c.rounds) return { phase: 'done', round: c.rounds, left: 0, key: 'done' }
    const within = e - ri * cyc
    return within < c.work
      ? { phase: 'work', round: ri + 1, left: c.work - within, key: 'w' + ri }
      : { phase: 'rest', round: ri + 1, left: cyc - within, key: 'r' + ri }
  }

  // ── render ──
  const svg = $('sw-analog'), digBox = $('sw-digital-box'), dig = $('sw-digital'), subTime = $('sw-analog-time')
  const roundEl = $('sw-round'), phaseEl = $('sw-phase'), stats = $('sw-stats')
  let lastKey = null, lastTick = -1
  function setHands(ms) {
    const totS = ms / 1000
    $('sw-sweep').setAttribute('transform', `rotate(${(totS % 60) * 6} 100 100)`)
    $('sw-min').setAttribute('transform', `rotate(${(Math.floor(totS / 60) % 30) * 12} 100 62)`)
  }
  function render() {
    if (mode === 'watch') {
      const E = elapsed(), f = fmt(E)
      if (face() === 'analog') { setHands(E); subTime.textContent = `${f.m}:${f.s}.${f.cs}` }
      else dig.innerHTML = `${f.m}:${f.s}<span class="cs">.${f.cs}</span>`
      return
    }
    // interval
    const c = cfg(), E = elapsed() / 1000, st = phaseAt(E, c)
    document.body.className = st.phase === 'work' ? 'phase-work' : st.phase === 'rest' ? 'phase-rest' : ''
    roundEl.textContent = st.phase === 'done' ? 'complete' : st.phase === 'prep' ? 'get ready' : `round ${st.round} / ${c.rounds}`
    phaseEl.textContent = st.phase === 'done' ? '✔ done' : st.phase
    phaseEl.className = 'sw-phase ' + st.phase
    const f = fmt(st.left * 1000)
    dig.innerHTML = st.phase === 'done' ? 'DONE' : `${f.s}<span class="cs">.${f.cs}</span>`
    // transitions → beep; countdown ticks in the last 3 s
    if (running) {
      if (st.key !== lastKey) {
        if (st.phase === 'work') beeps(2, 880, 130)
        else if (st.phase === 'rest') beep(440, 0.22, 0.3)
        else if (st.phase === 'done') { beeps(3, 660, 200); stop() }
        lastKey = st.key
      }
      const sl = Math.ceil(st.left)
      if (st.phase !== 'done' && sl <= 3 && sl >= 1 && sl !== lastTick) { beep(1100, 0.06, 0.22); lastTick = sl }
    }
  }

  // ── the loop — top level, reads live state ──
  setInterval(render, 33)

  // ── controls ──
  const go = $('sw-go'), lapBtn = $('sw-lap'), resetBtn = $('sw-reset')
  function start() {
    if (mode === 'interval' && phaseAt(elapsed() / 1000, cfg()).phase === 'done') reset()
    running = true; t0 = now()
    if (ac && ac.state === 'suspended') ac.resume()
    go.textContent = 'stop'; go.classList.add('stop')
    lapBtn.disabled = mode !== 'watch'; resetBtn.disabled = false
    publish()
  }
  function stop() {
    if (running) { acc = elapsed(); running = false }
    go.textContent = mode === 'interval' ? 'resume' : (acc > 0 ? 'resume' : 'start'); go.classList.remove('stop')
    lapBtn.disabled = true
    publish()
  }
  function reset() {
    running = false; acc = 0; laps = []; lastKey = null; lastTick = -1
    go.textContent = 'start'; go.classList.remove('stop'); lapBtn.disabled = true; resetBtn.disabled = true
    document.body.className = ''
    renderLaps(); render(); publish()
  }
  go.addEventListener('click', () => running ? stop() : start())
  resetBtn.addEventListener('click', reset)
  lapBtn.addEventListener('click', () => { if (mode === 'watch' && running) { laps.push(elapsed()); renderLaps() } })

  // ── laps ──
  const lapsEl = $('sw-laps')
  function renderLaps() {
    if (mode !== 'watch' || !laps.length) { lapsEl.classList.remove('show'); lapsEl.innerHTML = ''; stats.hidden = true; return }
    const splits = laps.map((t, i) => t - (laps[i - 1] || 0))
    const best = Math.min(...splits), worst = Math.max(...splits)
    lapsEl.innerHTML = ''
    laps.forEach((t, i) => {
      const sp = splits[i], f = fmt(t), sf = fmt(sp)
      const row = document.createElement('div')
      row.className = 'sw-lap' + (splits.length > 1 && sp === best ? ' best' : '') + (splits.length > 1 && sp === worst ? ' worst' : '')
      row.innerHTML = `<span class="n">lap ${i + 1}</span><span class="split">+${sf.m}:${sf.s}.${sf.cs}</span><span class="tot">${f.m}:${f.s}.${f.cs}</span>`
      lapsEl.insertBefore(row, lapsEl.firstChild)
    })
    lapsEl.classList.add('show')
    const avg = splits.reduce((a, b) => a + b, 0) / splits.length, bf = fmt(best), af = fmt(avg)
    stats.hidden = false
    stats.innerHTML = `<span>fastest <b>${bf.m}:${bf.s}.${bf.cs}</b></span><span>average <b>${af.m}:${af.s}.${af.cs}</b></span><span>laps <b>${laps.length}</b></span>`
  }

  // ── mode + face wiring ──
  function applyFace() {
    const analog = mode === 'watch' && face() === 'analog'
    svg.hidden = !analog; subTime.hidden = !analog
    digBox.hidden = analog   // digital box hides only when the analog face is up
    if (mode === 'interval') { digBox.hidden = false; svg.hidden = true; subTime.hidden = true }
  }
  function setMode(m) {
    mode = m; reset()
    document.querySelectorAll('.sw-mode').forEach(b => b.classList.toggle('on', b.dataset.mode === m))
    roundEl.hidden = phaseEl.hidden = m !== 'interval'
    lapBtn.style.display = m === 'watch' ? '' : 'none'
    applyFace()
  }
  document.querySelectorAll('.sw-mode').forEach(b => b.addEventListener('click', () => setMode(b.dataset.mode)))

  // settings changed in the other iframe page → re-read on return
  document.addEventListener('visibilitychange', () => { if (!document.hidden) applyFace() })
  window.addEventListener('storage', e => { if (e.key === 'sw-face') applyFace() })

  // boot
  setMode('watch')
})()
