// scroll-news.js — the WIRE for the Port Side View. real news, ported clean.
//
// EXTRACT don't copy (IC): the source list is the clock's — published to
// localStorage 'clock-taxonomy' by lb-headlines.publishTaxonomy() (feedUrls +
// names + packs), so there is ONE source of truth and this can never drift from
// the clock's chips. Only the RSS/Atom PARSER lives here (small; the clock keeps
// its own copy until someone unifies them — noted). A shipped FALLBACK set means
// the paper is populated with zero network and before the clock has ever run.
//
// The picture rides IN the feed (media:thumbnail · media:content widest-wins ·
// enclosure · an <img> in the description) — no article scraping, the bouncer
// never sees us. That is the whole "port real feeds with metadata" ask.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   VIDEO-NEWS (Sum 2026-07-22) — a YouTube ...... search: "VIDEO-NEWS (Sum"
//   THE DRAFTING TABLE (Sum 2026-07-25: "good .... search: "THE DRAFTING TABLE (Sum"
//   COMICS (Sum 2026-07-22): the GENEROUS ........ search: "COMICS (Sum"
//   WEIRD (Sum 2026-07-22) — News of the Weird ... search: "WEIRD (Sum 2026-07-22)"
//   HOROSCOPE (Sum 2026-07-22) — the user's ...... search: "HOROSCOPE (Sum"
//   SCRIPTURE — the LONGER PASSAGES (Sum ......... search: "SCRIPTURE — the LONGER"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for RSS/Atom parsing, feed fetching (via
//    **MIRROR/MIRROR2/metal fallback ladder), and the shape of
//    **news/comics/weird/horoscope/scripture items. It exports `window.SF_NEWS` with methods
//    **`load`, `sources`, `loadComics`, `loadWeird`, `loadHoroscope`, `loadScripture`.
//
//    **TOUCH HERE** —
//    - Add or remove a news source → edit `FALLBACK` object L72–106, then update `DEFAULT_ON` L107
//    - if it should ship on by default.
//    - Change which news feeds load by default → `DEFAULT_ON` L107 (must match settings
//    - `NEWS_DEFAULT` or the UI chip will lie).
//    - Add a comic, weird source, or scripture text → add entry to `COMICS` L176–183, `WEIRD`
//    - L207–211, or `SCRIPTURE` L258–269, then the loader will pick it up.
//    - Adjust how many items per feed → change `.slice(0, N)` in `parse()` L43, `loadComics()`
//    - L195, `loadWeird()` L221, or `ytChannel()` L140.
//    - Change the fetch strategy (MIRROR/MIRROR2/metal order) → `grab()` L26–31.
//    - Alter item shape (title/desc/img/link/ts fields) → `parse()` L39–69 for RSS/Atom,
//    - `ytChannel()` L133–143 for YouTube, or the `get` functions in `SCRIPTURE` L258–269.
//
//    **TRAPS** —
//    - `DEFAULT_ON` L107 must match the `NEWS_DEFAULT` array in settings, or the UI will show feeds
//    - as off while they print. Comment L107 warns this.
//    - `localStorage` keys are load-bearing: `'scroll-feeds'` L118, `'scroll-comics'` L189,
//    - `'scroll-weird'` L216, `'scroll-scripture'` L271, `'scroll-custom-sources'` L111,
//    - `'clock-taxonomy'` L113, `'scroll-view'` L148, `'oz-videos-off'` L147. Renaming orphans user
//    - toggles.
//    - The empty-array trap: `null` means "never set, use default"; `[]` means "user explicitly
//    - turned all off, show nothing." This is enforced at L119–120, L189–191, L216–218, L271–272.
//    - Changing this logic breaks the off switch.
//    - `parse()` L39 returns items with fields `title`, `link`, `desc`, `img`, `hero`, `ts`.
//    - Callers at L165, L195, L221 expect this shape and add `src` and `section`. Changing the
//    - shape breaks the wall.
//    - YouTube RSS is dead as of 2026-07-25 L159–161; `ytChannel()` L133 scrapes the channel page
//    - instead. The regex at L162 detects YouTube URLs and routes to `ytChannel()`. If YouTube
//    - markup changes, this breaks silently.
//    - `picOf()` L34 is called by `parse()` L47–50 to extract images from media:thumbnail/content.
//    - It checks width to pick the widest; if you change the width logic, narrow images may be
//    - chosen.
//    - `seasonSign()` L228 uses the `Z` array L227 to map dates to zodiac signs. The array has 13
//    - entries (capricorn twice, for year-wrap); do not shorten it.
//    - `loadHoroscope()` L238 uses `day % s.refs.length` L276 to pick a daily reference. This is
//    - deterministic per calendar day, so the same passage repeats daily. Changing the modulo
//    - breaks the daily rotation.
//
//    **DO NOT** —
//    - Rename `window.SF_NEWS` or its exported methods; the wall calls them by name.
//    - Move the `grab()` fallback ladder L26–31 to another file; it is tightly coupled to the fetch
//    - strategy here.
//    - Add network calls outside `grab()` or the `get` functions in `SCRIPTURE`; all fetches must
//    - go through the mirror/metal ladder.
//    - Change the item shape without updating all callers (parse, ytChannel, and the scripture get
//    - functions).
//    - Add new `localStorage` keys without documenting them in a comment; they are user state.
//    - Move `FALLBACK`, `COMICS`, `WEIRD`, or `SCRIPTURE` definitions to settings or the clock;
//    - they are the wire's source of truth for what feeds exist.
//    - Implement feed autodiscovery or GOFAI here; that lives in settings (the "+add a source" flow
//    - mentioned at L109).
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  // OUR mirror first (psv-mirror worker — our account, edge-cached, origin-locked); the public
  // allorigins stays as the SPARE TIRE. this is the road user-added feeds (their local paper) ride.
  const MIRROR  = u => 'https://psv-mirror.sumbhodi.workers.dev/?url=' + encodeURIComponent(u)
  const MIRROR2 = u => 'https://api.allorigins.win/raw?url=' + encodeURIComponent(u)

  // the metal: the native bolt, no CORS at the wire (same ladder as the clock)
  async function metal(url) {
    const P = window.parent, c = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__)
    if (!(c && c.invoke)) throw new Error('no bolt')
    const t = await c.invoke('fetch_page', { url }); if (!t) throw new Error('empty'); return t
  }
  async function grab(url) {
    try { const r = await fetch(url); if (r.ok) return await r.text() } catch (_) {}
    try { return await metal(url) } catch (_) {}
    try { const r = await fetch(MIRROR(url)); if (r.ok) return await r.text() } catch (_) {}
    const r = await fetch(MIRROR2(url)); if (r.ok) return await r.text()
    throw new Error('feed unreachable')
  }

  const picOf = m => {
    const u = m.getAttribute('url') || ''
    const t = (m.getAttribute('type') || '') + (m.getAttribute('medium') || '')
    return u && (/image/.test(t) || /\.(jpe?g|png|webp)([?#]|$)/i.test(u)) ? u : ''
  }
  function parse(xml) {
    const doc = new DOMParser().parseFromString(xml, 'text/xml')
    let nodes = Array.from(doc.querySelectorAll('item'))            // RSS
    if (!nodes.length) nodes = Array.from(doc.querySelectorAll('entry'))  // Atom
    return nodes.slice(0, 14).map(it => {
      const g = t => it.querySelector(t)?.textContent || ''
      const raw = g('description') || g('summary') || g('content') || ''
      let img = '', best = 0
      ;['thumbnail', 'content'].forEach(tag => Array.from(it.getElementsByTagNameNS('*', tag)).forEach(m => {
        const u = picOf(m), w = parseInt(m.getAttribute('width'), 10) || 1
        if (u && w > best) { img = u; best = w }
      }))
      if (!img) { const e = it.querySelector('enclosure[type^="image"]'); if (e) img = e.getAttribute('url') || '' }
      if (!img) { const mm = raw.match(/<img[^>]+src=['"]([^'"]+)['"]/i); if (mm && !/pixel|track|1x1/i.test(mm[1])) img = mm[1] }
      // many comic feeds (SMBC · Dino · PDL) put the STRIP in content:encoded, often entity-encoded — so the
      // plain <img> scan above misses it. dig content:encoded + decode entities, then re-scan (Sum 2026-07-24).
      if (!img) {
        let enc = ''; try { const n = it.getElementsByTagNameNS('*', 'encoded')[0]; enc = n ? n.textContent : '' } catch (_) {}
        const hay = (enc || raw).replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#0?39;|&apos;/g, "'").replace(/&amp;/g, '&')
        const mm = hay.match(/<img[^>]+src=['"]([^'"]+)['"]/i); if (mm && !/pixel|track|1x1/i.test(mm[1])) img = mm[1]
      }
      let link = (it.querySelector('link')?.textContent || '').trim()
      if (!link) { const a = it.querySelector('link'); link = (a && (a.getAttribute('href') || a.textContent) || '').trim() }
      const when = g('pubDate') || g('published') || g('updated') || ''
      return {
        title: (g('title') || '').replace(/\s+/g, ' ').trim(), link,
        desc: raw.replace(/<[^>]*>/g, ' ').replace(/&[a-z#0-9]+;/gi, ' ').replace(/\s+/g, ' ').trim().slice(0, 360),
        img, hero: !!img, ts: when ? Date.parse(when) || 0 : 0,
      }
    }).filter(x => x.title && x.link)
  }

  // shipped fallback — the clock's verified URLs, so the wire runs before the clock ever has
  const FALLBACK = {
    bbc:       { name: 'BBC',        section: 'world',   url: 'https://feeds.bbci.co.uk/news/world/rss.xml' },
    aljazeera: { name: 'Al Jazeera', section: 'world',   url: 'https://www.aljazeera.com/xml/rss/all.xml' },
    npr:       { name: 'NPR',        section: 'us',      url: 'https://feeds.npr.org/1001/rss.xml' },
    guardian:  { name: 'Guardian',   section: 'world',   url: 'https://www.theguardian.com/world/rss' },
    ars:       { name: 'Ars',        section: 'tech',    url: 'https://feeds.arstechnica.com/arstechnica/index' },
    positive:  { name: 'Positive',   section: 'good',    url: 'https://www.positive.news/feed/' },
    ksl:       { name: 'KSL',         section: 'local',  url: 'https://www.ksl.com/rss/news' },              // SLC local (Sum 2026-07-22); opt-in.
    abc4:      { name: 'ABC4 Utah',   section: 'local',  url: 'https://www.abc4.com/feed/' },
    // FOX 13 Utah removed as a source (Sum 2026-07-26: "remove my local fox news, so it never toggles
    // on — I hate fox, can't stand the spin, not on my local"). national 'fox' stays as the red-hat voice.
    deseret:   { name: 'Deseret News',section: 'local',  url: 'https://www.deseret.com/arc/outboundfeeds/rss/' },
    // beyond SLC, "find my town's news" (settings) discovers local feeds by the paper's town — no hardcoding.
    // THE RAG (Sum 2026-07-26) — the gossip-and-satire broadsheet. all verified live. opt-in (The Rag edition).
    // both aisles on purpose: the Onion next to the Babylon Bee, so it can't be accused of one lean.
    onion:     { name: 'The Onion',    section: 'rag',  url: 'https://www.theonion.com/rss' },
    bee:       { name: 'Babylon Bee',  section: 'rag',  url: 'https://babylonbee.com/feed' },
    reductress:{ name: 'Reductress',   section: 'rag',  url: 'https://reductress.com/feed/' },
    tmz:       { name: 'TMZ',          section: 'rag',  url: 'https://www.tmz.com/rss.xml' },
    nypost:    { name: 'NY Post',      section: 'rag',  url: 'https://nypost.com/feed/' },
    // ── VIDEO-NEWS (Sum 2026-07-22) — a YouTube channel's RSS (feeds/videos.xml). the entry link is a
    //    watch URL → clicking plays it in the Portal (video-in-Portal). section 'video' → the card says
    //    "watch". opt-in. smoke-tested live (BBC/AJ/DW/France24/CNN, 15 vids each, thumbs ride in). ──
    bbcvid:    { name: 'BBC News · video',   section: 'video', url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC16niRr50-MSBwiO3YDb3RA' },
    ajvid:     { name: 'Al Jazeera · video', section: 'video', url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCNye-wNBqNL5ZzHSJj3l8Bg' },
    dwvid:     { name: 'DW News · video',    section: 'video', url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCknLrEdhRCp1aegoMqRaCZg' },
    france24:  { name: 'France 24 · video',  section: 'video', url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCQfwfsi5VrQ8yKZ-UWmAEFg' },
    cnn:       { name: 'CNN', url: 'https://news.google.com/rss/search?q=when:24h+site:cnn.com&hl=en-US&gl=US&ceid=US:en' },   // CNN killed public RSS (2026) — Google News carries them
    cnnvid:    { name: 'CNN · video',        section: 'video', url: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCupvZG-5ko_eiXAupbDfxWw' },
    // ── THE DRAFTING TABLE (Sum 2026-07-25: "good architecture · green building · sustainable
    //    living") — default OFF like all taste; toggle on in the wire. failures swallowed as ever. ──
    dezeen:    { name: 'Dezeen · architecture', section: 'design', url: 'https://www.dezeen.com/feed/' },
    archdaily: { name: 'ArchDaily',             section: 'design', url: 'https://feeds.feedburner.com/Archdaily' },
    inhabitat: { name: 'Inhabitat · green design', section: 'design', url: 'https://inhabitat.com/feed/' },
  }
  const DEFAULT_ON = ['bbc', 'aljazeera', 'cnn', 'npr', 'guardian']   // FOX dropped from the default (Sum 2026-07-26: "I have fox toggled off everywhere, still getting fox — I hate fox, can't stand the spin"). MUST match settings NEWS_DEFAULT or the chip lies (shows off while the paper prints it). national fox stays available as an opt-in chip.

  // the reader's OWN added sources — { id: {name, url, section} } — found by the "+add a source" GOFAI
  // autodiscovery in settings (Sum 2026-07-22: "make ksl a button"). merged like FALLBACK, but user-owned.
  function customSrc() { try { return JSON.parse(localStorage.getItem('scroll-custom-sources') || '{}') } catch (_) { return {} } }
  function sources() {
    let tax = {}; try { tax = JSON.parse(localStorage.getItem('clock-taxonomy') || '{}') } catch (_) {}
    const urls = tax.feedUrls || {}, names = tax.feeds || {}, cust = customSrc()
    // the empty-array trap (Sum 2026-07-23: "all news off, still noisy feed") — null=never-set → default;
    // [] = you explicitly turned them ALL off → show NO news. same fix comics got. off means off.
    let on = null
    try { const raw = localStorage.getItem('scroll-feeds'); if (raw != null) on = JSON.parse(raw) } catch (_) {}
    if (on === null) on = DEFAULT_ON
    if (!Array.isArray(on)) on = []
    return on.map(id => ({
      id,
      name: names[id] || (FALLBACK[id] && FALLBACK[id].name) || (cust[id] && cust[id].name) || id,
      section: (FALLBACK[id] && FALLBACK[id].section) || (cust[id] && cust[id].section) || '',
      url: urls[id] || (FALLBACK[id] && FALLBACK[id].url) || (cust[id] && cust[id].url),
    })).filter(s => s.url)
  }

  // load every selected feed in parallel; failures are swallowed (the wire never blanks)
  // the channel-page wire — distinct videoIds in document order, zipped with the lockup titles
  // (verified 30/30 aligned on the live page). thumbs are deterministic (i.ytimg.com); ts staggers
  // by index so newest-first survives the global sort. failures swallowed like any wire.
  async function ytChannel(cid) {
    const html = await grab('https://www.youtube.com/channel/' + cid + '/videos')
    const ids = []
    String(html).replace(/"videoId":"([\w-]{6,})"/g, (m, id) => { if (ids.indexOf(id) < 0) ids.push(id); return m })
    const titles = []
    String(html).replace(/"lockupMetadataViewModel":\{"title":\{"content":"((?:[^"\\]|\\.)*)"/g, (m, t) => { try { titles.push(JSON.parse('"' + t + '"')) } catch (_) { titles.push(t) } return m })
    const now = Date.now()
    return ids.slice(0, 14).map((id, i) => ({
      title: String(titles[i] || '').replace(/\s+/g, ' ').trim() || 'a video', link: 'https://www.youtube.com/watch?v=' + id,
      desc: '', img: 'https://i.ytimg.com/vi/' + id + '/maxresdefault.jpg', imgAlt: 'https://i.ytimg.com/vi/' + id + '/hqdefault.jpg', hero: true, ts: now - i * 60000,
    }))
  }

  async function load() {
    let vidOff = false; try { vidOff = localStorage.getItem('oz-videos-off') === '1' } catch (_) {}   // the videos master hides video-news too
    let view = 'both'; try { view = localStorage.getItem('scroll-view') || 'both' } catch (_) {}
    // the view splits the SOURCES (Sum 2026-07-22): "just text" fetches only your text feeds, "just video"
    // only your video feeds, "both" fetches both. we only ever load the ones YOU toggled on — no auto-picking.
    const src = sources().filter(s => {
      const isVid = s.section === 'video'
      if (vidOff && isVid) return false            // master kills video everywhere
      if (view === 'text' && isVid) return false   // just text → skip the video feeds (saves the fetch)
      if (view === 'video' && !isVid) return false // just video → skip the text feeds
      return true
    }), all = []
    await Promise.allSettled(src.map(async s => {
      // YOUTUBE KILLED RSS (2026-07-25: all five channel feeds 404, every form — feeds/videos.xml
      // is gone). the road left: the channel PAGE via the same grab ladder (metal → mirror),
      // parsed for the 2026 lockup markup. same item shape out — the wall never sees the swap.
      const yt = /youtube\.com\/feeds\/videos\.xml\?channel_id=([\w-]+)/.exec(s.url || '')
      try {
        const items = yt ? await ytChannel(yt[1]) : parse(await grab(s.url))
        items.forEach(it => all.push(Object.assign({ src: s.name, section: s.section }, it)))
      } catch (_) {}
    }))
    all.sort((a, b) => b.ts - a.ts)
    return all
  }

  // ── COMICS (Sum 2026-07-22): the GENEROUS indies — open RSS, image in the feed, and clicking
  // links BACK to the artist's site (a real human hit through the front door, which supports them).
  // The locked legends (Calvin & Hobbes, Dilbert, GoComics) are walls → you PORT those, never embed.
  // linkout:true → a click opens the artist's site, not the Portal — that's the whole point. ──
  const COMICS = {
    xkcd:    { name: 'xkcd',                url: 'https://xkcd.com/rss.xml' },
    smbc:    { name: 'SMBC',                url: 'https://www.smbc-comics.com/comic/rss' },
    pdl:     { name: 'Poorly Drawn Lines',  url: 'https://poorlydrawnlines.com/feed/' },
    oatmeal: { name: 'The Oatmeal',         url: 'https://theoatmeal.com/feed/rss' },
    dino:    { name: 'Dinosaur Comics',     url: 'https://www.qwantz.com/rssfeed.php' },
    qc:      { name: 'Questionable Content', url: 'https://www.questionablecontent.net/QCRSS.xml' },
  }
  async function loadComics() {
    // no master toggle anymore (Sum 2026-07-23: redundant) — the empty-array fix IS the off switch:
    // the empty-array trap: [] meant "use default" → comics couldn't be turned off. now null=never-set
    // (→ default), [] = explicitly emptied (→ show none). unchecking every comic finally means OFF.
    let on = null
    try { const raw = localStorage.getItem('scroll-comics'); if (raw != null) on = JSON.parse(raw) } catch (_) {}
    if (on === null) on = Object.keys(COMICS)   /* calm default = ALL comics ON (Sum 2026-07-27: "all of them from api, pull in comics, full-color funny pages"). the gear showed every comic checked while the loader defaulted to NONE — the drift that left the funny pages text-jokes-only. [] still means explicitly-off. */
    if (!Array.isArray(on) || !on.length) return []
    const out = []
    await Promise.allSettled(on.map(async id => {
      const c = COMICS[id]; if (!c) return
      try { parse(await grab(c.url)).slice(0, 4).forEach(it => out.push(Object.assign({ src: c.name, section: 'comics', kind: 'comic', linkout: true }, it))) } catch (_) {}   // 4 strips per source (was 2) — a fuller funny page (Sum: "all of them")
    }))
    out.sort((a, b) => b.ts - a.ts)
    return out
  }

  // ── WEIRD (Sum 2026-07-22) — News of the Weird (the Shepherd column) is locked at uexpress
  // (Andrews McMeel, same wall as Calvin & Hobbes) → PORT it, don't embed. But the GENRE is open:
  // Oddity Central · Weird Universe (Shepherd's old blog) · Boing Boing.
  // NOT linkout (Sum 2026-07-23: "why isn't this just opening in portal") — these are real ARTICLES,
  // not comic strips. the feed only carries a truncated excerpt, so they READ IN THE PORTAL (a real
  // fetch + strip = the WHOLE article). only comics stay linkout (the strip lives on the artist's site). ──
  const WEIRD = {
    oddity:   { name: 'Oddity Central', url: 'https://www.odditycentral.com/feed' },
    weirduni: { name: 'Weird Universe', url: 'https://www.weirduniverse.net/feed' },
    boing:    { name: 'Boing Boing',    url: 'https://boingboing.net/feed' },
  }
  async function loadWeird() {
    // per-source toggles (Sum 2026-07-23 morning: "boing boing never got a toggle") — same law as
    // comics/news: null = never set → default all on; [] = explicitly emptied → weird is OFF.
    let on = null
    try { const raw = localStorage.getItem('scroll-weird'); if (raw != null) on = JSON.parse(raw) } catch (_) {}
    if (on === null) on = Object.keys(WEIRD)
    if (!Array.isArray(on) || !on.length) return []
    const out = []
    await Promise.allSettled(Object.entries(WEIRD).filter(([id]) => on.includes(id)).map(async ([, c]) => {
      try { parse(await grab(c.url)).slice(0, 3).forEach(it => out.push(Object.assign({ src: c.name, section: 'weird' }, it))) } catch (_) {}
    }))
    out.sort((a, b) => b.ts - a.ts); return out
  }

  // ── HOROSCOPE (Sum 2026-07-22) — the user's sign (scroll-sign) or the sign in SEASON as default. ──
  const Z = [['capricorn', '♑', 119], ['aquarius', '♒', 218], ['pisces', '♓', 320], ['aries', '♈', 419], ['taurus', '♉', 520], ['gemini', '♊', 620], ['cancer', '♋', 722], ['leo', '♌', 822], ['virgo', '♍', 922], ['libra', '♎', 1022], ['scorpio', '♏', 1121], ['sagittarius', '♐', 1221], ['capricorn', '♑', 1231]]
  function seasonSign(d) { const key = (d.getMonth() + 1) * 100 + d.getDate(); for (const z of Z) if (key <= z[2]) return { sign: z[0], glyph: z[1] }; return { sign: 'capricorn', glyph: '♑' } }
  // modes (Sum 2026-07-22): 'season' = your sun (or the sign in season if unset) · 'three' =
  // sun · rising · moon (whichever you've set) · 'all' = the whole wheel. Set in the gear.
  const glyphOf = s => { const f = Z.find(z => z[0] === s); return f ? f[1] : '✨' }
  async function oneHoro(s) {
    const cap = s.charAt(0).toUpperCase() + s.slice(1)
    try { const j = JSON.parse(await grab('https://horoscope-app-api.vercel.app/api/v1/get-horoscope/daily?sign=' + s + '&day=TODAY')); const t = j && j.data && j.data.horoscope_data; if (t) return { sign: cap, glyph: glyphOf(s), text: t } } catch (_) {}
    try { const j = JSON.parse(await grab('https://ohmanda.com/api/horoscope/' + s)); if (j && j.horoscope) return { sign: cap, glyph: glyphOf(s), text: j.horoscope } } catch (_) {}
    return null
  }
  async function loadHoroscope() {
    const rd = k => { try { return localStorage.getItem(k) } catch (_) { return null } }
    const mode = rd('scroll-horo-mode') || 'season'
    const sun = rd('scroll-sign'), rising = rd('scroll-rising'), moon = rd('scroll-moon')
    const labels = {}; if (sun) labels[sun] = 'sun'; if (rising) labels[rising] = 'rising'; if (moon) labels[moon] = 'moon'
    let signs
    if (mode === 'all') signs = Z.slice(0, 12).map(z => z[0])
    else if (mode === 'three') signs = [sun, rising, moon].filter(Boolean)
    else signs = [sun]                                    // season: your sun...
    signs = [...new Set(signs.filter(Boolean))]
    if (!signs.length) { const s = seasonSign(new Date()); signs = [s.sign]; labels[s.sign] = 'in season' }   // ...or the season sign
    const out = []
    for (const s of signs.slice(0, 12)) { const h = await oneHoro(s); if (h) { h.label = labels[s] || ''; out.push(h) } }
    return out.length ? out : null
  }

  // ── SCRIPTURE — the LONGER PASSAGES (Sum 2026-07-22): a reference is the headline; the whole
  // section/chapter opens in the content card. Bible/Qur'an/Tanakh return full sections in one call;
  // Gita (verse-assembled) + literature "whole scenes" (a search) are the follow-up. Opt-in. ──
  const stripHtml = s => String(s).replace(/<[^>]*>/g, ' ').replace(/&[a-z#0-9]+;/gi, ' ').replace(/\s+/g, ' ').trim()
  const SCRIPTURE = {
    bible: { name: 'Bible', refs: ['john 1', 'psalms 23', 'genesis 1', 'ecclesiastes 3', 'proverbs 3', '1 corinthians 13', 'matthew 5', 'romans 8', 'isaiah 40', 'psalms 91'],
      get: async ref => { const j = JSON.parse(await grab('https://bible-api.com/' + encodeURIComponent(ref))); return { title: j.reference || ref, body: (j.text || '').trim() } } },
    quran: { name: "Qur'an", refs: [1, 112, 113, 114, 36, 55, 67, 93, 94, 103],
      get: async n => { const d = JSON.parse(await grab('https://api.alquran.cloud/v1/surah/' + n + '/en.sahih')).data; return { title: 'Surah ' + d.englishName + ' · ' + d.englishNameTranslation, body: d.ayahs.map(a => a.text).join('\n') } } },
    torah: { name: 'Tanakh', refs: ['Genesis 1', 'Psalms 23', 'Ecclesiastes 3', 'Proverbs 3', 'Exodus 20', 'Deuteronomy 6', 'Psalms 121', 'Isaiah 40', 'Genesis 22', 'Ecclesiastes 1'],
      get: async ref => { const j = JSON.parse(await grab('https://www.sefaria.org/api/texts/' + encodeURIComponent(ref.replace(/ /g, '.')))); const t = (Array.isArray(j.text) ? j.text.flat(Infinity) : [j.text]).filter(x => typeof x === 'string' && x.trim()); return { title: j.ref || ref, body: t.map(stripHtml).filter(Boolean).join('\n') } } },
    // the Gita — vedicscriptures API is per-verse (CORS-friendly GitHub Pages); one famous śloka a day,
    // Sanskrit transliteration + an English translation (Sivananda → Purohit → others). (Sum 2026-07-22)
    gita: { name: 'Gita', refs: [[2, 47], [2, 20], [2, 48], [3, 19], [4, 7], [6, 5], [9, 22], [12, 15], [18, 66], [2, 62]],
      get: async ref => { const [ch, v] = ref; const d = JSON.parse(await grab('https://vedicscriptures.github.io/slok/' + ch + '/' + v + '/')); const en = (d.siva && d.siva.et) || (d.purohit && d.purohit.et) || (d.san && d.san.et) || (d.gambir && d.gambir.et) || (d.adi && d.adi.et) || ''; return { title: 'Bhagavad Gita ' + ch + '.' + v, body: (d.transliteration ? d.transliteration.trim() + '\n\n' : '') + en.trim() } } },
  }
  async function loadScripture() {
    let on; try { on = JSON.parse(localStorage.getItem('scroll-scripture') || 'null') } catch (_) {}
    if (!Array.isArray(on) || !on.length) return []          // opt-in
    const day = Math.floor(Date.now() / 86400000), out = []
    await Promise.allSettled(on.map(async id => {
      const s = SCRIPTURE[id]; if (!s) return
      const ref = s.refs[day % s.refs.length]
      try { const p = await s.get(ref); if (p && p.body) out.push({ lane: 'scripture', src: s.name, title: p.title, body: p.body }) } catch (_) {}
    }))
    return out
  }

  window.SF_NEWS = { load, sources, loadComics, loadWeird, loadHoroscope, loadScripture }
})()
