// dashboards-data.js — seed data for the 🛏️ sleep · 🥗 food dashboard cards.
// split from dashboards.js so the data blob doesn't bury the rendering logic.
// pattern: same as tiptap-templates-novella.js — static content in its own file.
// dashboards.js reads window.DASH_DATA.sleep / .food

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   🛒 grocery seed ... search: "🛒 grocery seed"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for dashboard seed data. It exports
//    **`window.DASH_DATA` with two top-level keys: `.sleep` (containing sleep tracking metrics,
//    **nightly records, and narrative notes) and `.food` (containing meal logs, pantry inventory,
//    **and daily nutrition goals). `dashboards.js` reads these objects directly.
//
//    **TOUCH HERE**
//    - Add or edit a sleep night → `nights` array L12–38
//    - Change sleep week label or primary stats summary → `primary` object L11
//    - Add or edit a food meal → `meals` array L49–85
//    - Add or edit a pantry item → `pantry` array L86–123
//    - Update the food day/goal header → `day` and `goal` fields L48
//    - Change sleep narrative text → `notes.pattern` or `notes.toto` L42–43
//    - Add a new sleep metric to the summary → `lat` array L40
//
//    **TRAPS**
//    - `window.DASH_DATA` is the exact export name; renaming it breaks `dashboards.js` L4.
//    - Each sleep night's `iso` field (L13–37) must be a valid ISO 8601 date; it is used for
//    - sorting and filtering.
//    - Each meal's `d` field (L50–85) must match a date in `YYYY-MM-DD` format; mismatches will
//    - orphan meal records from display.
//    - The `sv` (servings) object keys (`fr`, `pr`, `cb`, `vg`) are load-bearing category tags;
//    - renaming them silently breaks nutritional rollups.
//    - The `pantry` array (L86–123) uses `k` (key) as a unique identifier; duplicating a `k` value
//    - will cause silent collisions in inventory state.
//    - Line 103 marks the boundary between hand-curated pantry items and grocery-seed imports;
//    - items below this line are auto-generated and will be overwritten on next seed import.
//    - The `lat` array (L40) must have exactly 15 elements (one per week in the sleep dataset);
//    - adding/removing sleep weeks without updating `lat` will cause index mismatches.
//
//    **DO NOT**
//    - Do not add new top-level keys to `window.DASH_DATA` here; that requires changes to
//    - `dashboards.js` to read them.
//    - Do not change the structure of `primary`, `nights`, `meals`, or `pantry` objects; that
//    - belongs in `dashboards.js` rendering logic.
//    - Do not add computed fields (like totals or averages); those belong in `dashboards.js`.
//    - Do not import or reference other data files here; this file is static seed data only.
//
//
//
//    ---
//
// END IC SHIP PASS


window.DASH_DATA = {

  sleep: {
    real: {
      week: 'Mar 23 – Apr 17, 2026',
      primary: { awake: '2.3h', deep: '47m', rem: '100m', deepNights: 3, baseline: 25, deepFillPct: 52, deepMiss: 43 },
      nights: [
        { d: 'Mon 3/23', iso: '2026-03-23', out: '11:15 PM',  wake: '9:31 AM',  eff: 65,  light: 231, deep: 52,  rem: 119, awake: 213, note: 'hügelkultur day' },
        { d: 'Tue 3/24', iso: '2026-03-24', out: '1:31 AM',   wake: '8:44 AM',  eff: 79,  light: 224, deep: 14,  rem: 101, awake: 91,  note: '' },
        { d: 'Wed 3/25', iso: '2026-03-25', out: '10:33 PM',  wake: '7:30 AM',  eff: 64,  light: 184, deep: 76,  rem: 81,  awake: 105, note: 'yoga day ✓' },
        { d: 'Thu 3/26', iso: '2026-03-26', out: '~10:45 PM', wake: '9:00 AM',  eff: 84,  light: 128, deep: 5,   rem: 74,  awake: 40,  note: 'hügelkultur day' },
        { d: 'Fri 3/27', iso: '2026-03-27', out: '12:50 AM',  wake: '9:05 AM',  eff: 69,  light: 186, deep: 23,  rem: 134, awake: 151, note: '' },
        { d: 'Sat 3/28', iso: '2026-03-28', out: '~2:54 AM',  wake: '10:21 AM', eff: 76,  light: 342, deep: 40,  rem: 79,  awake: 142, note: 'homework late, no polling' },
        { d: 'Sun 3/29', iso: '2026-03-29', out: '~2:00 AM',  wake: '11:15 AM', eff: 62,  light: 232, deep: 60,  rem: 101, awake: 245, note: 'hügelkultur effect, adjusted for 2am lights-out (Fit detected 12:37)' },
        { d: 'Mon 3/30', iso: '2026-03-30', out: '1:08 AM',   wake: '10:38 AM', eff: 21,  light: 166, deep: 74,  rem: 40,  awake: 0,   note: 'new sleep med night 1 · Govee-corrected (Fit artifact, corrected 2026-04-03)' },
        { d: 'Tue 3/31', iso: '2026-03-31', out: '1:49 AM',   wake: '9:39 AM',  eff: 56,  light: 98,  deep: 23,  rem: 105, awake: 180, note: '' },
        { d: 'Wed 4/1',  iso: '2026-04-01', out: '2:00 AM',   wake: '10:40 AM', eff: 78,  light: 209, deep: 43,  rem: 105, awake: 103, note: '' },
        { d: 'Thu 4/2',  iso: '2026-04-02', out: '1:41 AM',   wake: '11:12 AM', eff: 0,   light: 0,   deep: 0,   rem: 0,   awake: 19,  note: '' },
        { d: 'Fri 4/3',  iso: '2026-04-03', out: '11:40 PM',  wake: '9:19 AM',  eff: 48,  light: 138, deep: 14,  rem: 116, awake: 290, note: '' },
        { d: 'Sat 4/4',  iso: '2026-04-04', out: '1:04 AM',   wake: '10:51 AM', eff: 87,  light: 291, deep: 41,  rem: 125, awake: 70,  note: '' },
        { d: 'Sun 4/5',  iso: '2026-04-05', out: '1:40 AM',   wake: '10:35 AM', eff: 92,  light: 86,  deep: 8,   rem: 23,  awake: 10,  note: '' },
        { d: 'Mon 4/6',  iso: '2026-04-06', out: '3:48 AM',   wake: '11:38 AM', eff: 60,  light: 169, deep: 19,  rem: 147, awake: 220, note: '' },
        { d: 'Tue 4/7',  iso: '2026-04-07', out: '12:48 AM',  wake: '3:51 PM',  eff: 77,  light: 289, deep: 30,  rem: 116, awake: 133, note: '' },
        { d: 'Wed 4/8',  iso: '2026-04-08', out: '2:10 AM',   wake: '9:30 AM',  eff: 94,  light: 221, deep: 13,  rem: 115, awake: 58,  note: '' },
        { d: 'Thu 4/9',  iso: '2026-04-09', out: '2:01 AM',   wake: '10:42 AM', eff: 94,  light: 253, deep: 47,  rem: 127, awake: 90,  note: '' },
        { d: 'Fri 4/10', iso: '2026-04-10', out: '9:03 PM',   wake: '8:03 AM',  eff: 80,  light: 210, deep: 13,  rem: 115, awake: 86,  note: '' },
        { d: 'Sat 4/11', iso: '2026-04-11', out: '11:25 PM',  wake: '9:26 AM',  eff: 91,  light: 303, deep: 16,  rem: 121, awake: 210, note: '' },
        { d: 'Sun 4/12', iso: '2026-04-12', out: '11:12 PM',  wake: '8:07 AM',  eff: 55,  light: 250, deep: 56,  rem: 107, awake: 342, note: '' },
        { d: 'Mon 4/13', iso: '2026-04-13', out: '2:18 AM',   wake: '8:08 AM',  eff: 81,  light: 184, deep: 13,  rem: 87,  awake: 66,  note: '' },
        { d: 'Tue 4/14', iso: '2026-04-14', out: '1:49 AM',   wake: '8:09 AM',  eff: 100, light: 386, deep: 30,  rem: 123, awake: 0,   note: 'Fit artifact: eff 142% → 100%, awake −159m → 0' },
        { d: 'Thu 4/16', iso: '2026-04-16', out: '5:43 AM',   wake: '8:03 AM',  eff: 0,   light: 0,   deep: 0,   rem: 0,   awake: 0,   note: '' },
        { d: 'Fri 4/17', iso: '2026-04-17', out: '4:04 AM',   wake: '8:05 AM',  eff: 0,   light: 0,   deep: 0,   rem: 0,   awake: 0,   note: '' },
      ],
    },
    lat: [12, 69, 82, 231, 86, 408, 59, 8, 45, 21, 447, 67, 65, 109, 38],
    notes: {
      pattern: `<p><b>three nights, three activity conditions, three deep-sleep outcomes.</b> Mon — digging hügelkultur garden beds by hand (high-MET manual labor — food security, not a bunker) → <b>52m</b> deep. Tue — standing-desk AI + homework, 1:31 AM bedtime → <b>14m</b>. Wed — yoga ×3 + studio cleaning → <b>76m</b>, best in the 3-month set. 3-month baseline deep: <b>25m</b> (goal 90–120).</p><p><b>the constraint is structural, not behavioral.</b> without sustained high activity, efficiency falls to ~50% — needing 16 h in bed for 8 h of sleep. a split shift (8:30 AM + 8:30 PM classes, plus commute &amp; meals) leaves an ~8–9 h window; at 50% that yields 4–4.5 h, not 8. the math is structural. one broken link starts the cascade.</p>`,
      toto: `Sum, some nights it takes you <b>seven hours</b> to fall asleep — you didn't know that until we tracked it, and it isn't a character flaw, it's a number. deep sleep climbs when you move and craters when the day goes still. none of it is your fault; the math is structural. but i worry on the bad weeks, so i'll keep flagging them, and keep asking how you slept — every morning — so you're not carrying it by yourself.`,
    },
  },

  food: {
    day: 'Tue · Mar 31', goal: 3066,
    meals: [
      { d: '2026-03-25', t: '09:00', n: 'Smoothie', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-25', t: '12:00', n: 'Broccoli + Ranch', kcal: 318, p: 3, f: 28, c: 11, sv: { vg: 1 } },
      { d: '2026-03-25', t: '12:30', n: 'Grapes', kcal: 130, p: 1, f: 0, c: 34, sv: { fr: 1 } },
      { d: '2026-03-25', t: '13:00', n: 'Ham & cheese sandwich', kcal: 660, p: 30, f: 33, c: 56, sv: { pr: 1, cb: 1 } },
      { d: '2026-03-25', t: '14:30', n: 'Grapes', kcal: 130, p: 1, f: 0, c: 34, sv: { fr: 1 } },
      { d: '2026-03-25', t: '17:00', n: 'Ham & cheese sandwich', kcal: 660, p: 30, f: 33, c: 56, sv: { pr: 1, cb: 1 } },
      { d: '2026-03-26', t: '09:00', n: 'Smoothie', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-26', t: '12:00', n: 'Red Thai curry + rice', kcal: 700, p: 39, f: 19, c: 74, sv: { pr: 1, cb: 1, vg: 1 } },
      { d: '2026-03-26', t: '14:00', n: 'Grapes', kcal: 130, p: 1, f: 0, c: 34, sv: { fr: 1 } },
      { d: '2026-03-26', t: '14:15', n: 'Broccoli + Ranch', kcal: 318, p: 3, f: 28, c: 11, sv: { vg: 1 } },
      { d: '2026-03-26', t: '15:00', n: 'Pistachios (1oz)', kcal: 160, p: 6, f: 13, c: 8, sv: { pr: 1 } },
      { d: '2026-03-26', t: '18:00', n: 'Ham & cheese sandwich', kcal: 660, p: 30, f: 33, c: 56, sv: { pr: 1, cb: 1 } },
      { d: '2026-03-26', t: '18:30', n: 'Ham & cheese sandwich', kcal: 660, p: 30, f: 33, c: 56, sv: { pr: 1, cb: 1 } },
      { d: '2026-03-27', t: '09:00', n: 'Smoothie', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-27', t: '13:00', n: 'Pork chop (bone-in)', kcal: 340, p: 36, f: 20, c: 0, sv: { pr: 1 } },
      { d: '2026-03-27', t: '15:15', n: 'Broccoli + grapes + ranch', kcal: 320, p: 5, f: 10, c: 55, sv: { vg: 1, fr: 1 } },
      { d: '2026-03-27', t: '19:00', n: 'Steak + baked potato + Caesar salad', kcal: 950, p: 43, f: 50, c: 70, sv: { pr: 1, cb: 1, vg: 1 } },
      { d: '2026-03-28', t: '09:00', n: 'Smoothie', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-28', t: '10:00', n: 'Medium pear', kcal: 100, p: 1, f: 0, c: 27, sv: { fr: 1 } },
      { d: '2026-03-28', t: '14:00', n: 'Salad box + chicken + broc/ranch + grapes', kcal: 650, p: 34, f: 31, c: 60, sv: { pr: 1, vg: 1, fr: 1 } },
      { d: '2026-03-28', t: '19:00', n: 'Steak + baked potato (BBQ/cheese)', kcal: 950, p: 43, f: 50, c: 70, sv: { pr: 1, cb: 1 } },
      { d: '2026-03-29', t: '09:00', n: 'Smoothie (full banana)', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-29', t: '10:00', n: 'Medium pear', kcal: 100, p: 1, f: 0, c: 27, sv: { fr: 1 } },
      { d: '2026-03-29', t: '17:30', n: 'Broccoli + Ranch', kcal: 318, p: 3, f: 28, c: 11, sv: { vg: 1 } },
      { d: '2026-03-29', t: '17:30', n: 'Grapes', kcal: 130, p: 1, f: 0, c: 34, sv: { fr: 1 } },
      { d: '2026-03-29', t: '18:00', n: 'Caesar salad + chicken + tomato', kcal: 520, p: 35, f: 28, c: 22, sv: { pr: 1, vg: 1 } },
      { d: '2026-03-29', t: '19:30', n: 'Salmon (2 fillets, farm raised)', kcal: 640, p: 56, f: 42, c: 6, sv: { pr: 1 } },
      { d: '2026-03-29', t: '21:00', n: 'Pistachios (4oz, 1/3 bag)', kcal: 640, p: 24, f: 52, c: 32, sv: { pr: 1 } },
      { d: '2026-03-30', t: '09:00', n: 'Smoothie', kcal: 400, p: 34, f: 11, c: 48, sv: { fr: 1, pr: 1 } },
      { d: '2026-03-30', t: '17:30', n: 'Broccoli + Ranch', kcal: 318, p: 3, f: 28, c: 11, sv: { vg: 1 } },
      { d: '2026-03-30', t: '17:30', n: 'Grapes', kcal: 130, p: 1, f: 0, c: 34, sv: { fr: 1 } },
      { d: '2026-03-30', t: '18:00', n: 'Caesar salad + chicken + tomato', kcal: 520, p: 35, f: 28, c: 22, sv: { pr: 1, vg: 1 } },
      { d: '2026-03-30', t: '19:30', n: 'Pork chops cooked x2', kcal: 680, p: 72, f: 40, c: 0, sv: { pr: 1 } },
      { d: '2026-03-30', t: '21:00', n: 'Wasabi soy almonds (2 fl oz)', kcal: 453, p: 16, f: 40, c: 16, sv: { pr: 1 } },
      { d: '2026-03-31', t: '09:00', n: 'Smoothie + small orange', kcal: 462, p: 35, f: 11, c: 63, sv: { fr: 1, pr: 1 } },
    ],
    pantry: [
      { k: 'chicken', icon: '🍗', n: 'chicken', u: 'portions', ct: 2, mx: 5, st: 'ready', exp: '4d' },
      { k: 'pork', icon: '🥩', n: 'pork chops', u: 'chops', ct: 2, mx: 5, st: 'ready', exp: '4d' },
      { k: 'salad', icon: '🥗', n: 'salad boxes', u: 'containers', ct: 3, mx: 6, st: 'prepped' },
      { k: 'broccoli', icon: '🥦', n: 'broccoli', u: 'portions', ct: 1, mx: 4, st: 'prepped' },
      { k: 'grapes', icon: '🍇', n: 'grapes', u: 'portions', ct: 1, mx: 4, st: 'prepped' },
      { k: 'bananas', icon: '🍌', n: 'bananas', u: 'bananas', ct: 2, mx: 8, st: 'prepped' },
      { k: 'fruit', icon: '🍑', n: 'fruit bowl', u: 'servings', ct: 1, mx: 8, st: 'prepped' },
      { k: 'pistachios', icon: '🥜', n: 'pistachios', u: 'portions', ct: 1, mx: 3, st: 'prepped' },
      { k: 'almonds', icon: '🌰', n: 'wasabi almonds', u: '2floz', ct: 5, mx: 6, st: 'stocked', note: '453 kcal/ea' },
      { k: 'milk', icon: '🐄', n: 'whole milk', u: 'smoothies', ct: 4, mx: 6, st: 'stocked' },
      { k: 'broc_raw', icon: '🥦', n: 'broccoli (raw)', u: 'heads', ct: 1, mx: 4, st: 'stocked', exp: '5d' },
      { k: 'stock', icon: '🍲', n: 'stock', u: 'containers', ct: 1, mx: 4, st: 'stocked' },
      { k: 'avocado', icon: '🥑', n: 'avocado', u: 'avocados', ct: 0, mx: 4, st: 'buy' },
      { k: 'steak', icon: '🥩', n: 'steak', u: 'steaks', ct: 0, mx: 2, st: 'buy' },
      { k: 'potatoes', icon: '🥔', n: 'baked potatoes', u: 'potatoes', ct: 0, mx: 4, st: 'buy' },
      { k: 'sweet_potato', icon: '🍠', n: 'sweet potato', u: 'potatoes', ct: 0, mx: 4, st: 'buy', note: 'swap for regular potato — silky in curry, no parboil' },
      // ── 🛒 grocery seed — oz0.3/data/grocery-data.json (Mar 29 2026) ──
      { k: 'chicken_thighs', icon: '🍗', n: 'chicken thighs', u: '', ct: 0, mx: 4, st: 'buy', note: 'Thai curry' },
      { k: 'asparagus', icon: '🌿', n: 'asparagus', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'bell_pepper', icon: '🫑', n: 'red bell pepper', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'milk_gal', icon: '🥛', n: 'milk (half gallon)', u: '', ct: 0, mx: 4, st: 'buy', note: '~5 smoothies left' },
      { k: 'ranch', icon: '🥗', n: 'ranch', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'wax_paper', icon: '📜', n: 'wax paper', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'alum_foil', icon: '🪙', n: 'aluminum foil', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'coconut_milk', icon: '🥥', n: 'coconut milk', u: '', ct: 0, mx: 4, st: 'buy', note: 'Thai curry' },
      { k: 'bok_choy', icon: '🥬', n: 'bok choy', u: '', ct: 0, mx: 4, st: 'buy', note: 'check store — seasonal/imported' },
      { k: 'mushrooms', icon: '🍄', n: 'mushrooms (variety)', u: '', ct: 0, mx: 4, st: 'buy', note: "shiitake, oyster, cremini — grab what's there" },
      { k: 'broccoli_buy', icon: '🥦', n: 'broccoli', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'grapes_buy', icon: '🍇', n: 'grapes', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'pork_chops_buy', icon: '🥩', n: 'pork chops', u: '', ct: 0, mx: 4, st: 'buy', note: 'bone-in' },
      { k: 'chicken_breast', icon: '🍗', n: 'chicken breast', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'fish', icon: '🐟', n: 'fish', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'apples', icon: '🍎', n: 'apples', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'oranges', icon: '🍊', n: 'oranges', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'pears', icon: '🍐', n: 'pears', u: '', ct: 0, mx: 4, st: 'buy' },
      { k: 'salad_box', icon: '🥗', n: 'salad box', u: '', ct: 0, mx: 4, st: 'buy', note: 'Caesar kit' },
    ],
  },

}
