// wellness-import.js — the 🩹 IMPORTER. bolts a "⤵ import" affordance onto the 🧘 wellness card and turns a
// dropped/pasted health export into rows the human EYEBALLS before anything writes. HIL, never silent: parse →
// PREVIEW table → the human CONFIRMS → write into the SAME three stores the cards read (toto_sleep_nights via
// window.sleepAddNight, toto_exercise_log via window.exerciseAddLog, food-plan.json for food). ADDITIVE: one IIFE,
// self-mounts by observing #desk for the spa card, wraps NOTHING, touches NO existing dashboards.js state.
//
// the ONE canonical shape everything funnels through is an NDJSON EVENT — one flat object per line:
//   { timestamp, type, value, unit, source }   (the _SPEC spine; diff-able + human-editable)
// PARSE accepts three carriers of that shape — plain NDJSON, a JSON array, and simple CSV — plus a defensive
// field-name MAP that folds common Health-Connect-export + Apple export.xml names onto it. everything lands as
// canonical events; the store-MAP is the only place that knows toto_* shapes. reads happen in YOUR browser.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the canonical event 'type' vocabulary — the ... search: "the canonical event"
//   field-name MAP — defensive aliases → .......... search: "field-name MAP"
//   fold ANY loose object → a canonical event ..... search: "fold ANY loose object →"
//   PARSE — three carriers, best-effort. .......... search: "PARSE — three carriers,"
//   the store-MAP — canonical events → the REAL ... search: "the store-MAP"
//   COMMIT — execute a write plan the human ....... search: "COMMIT — execute a"
//   a tiny bare toast anchored to the card ........ search: "a tiny bare toast"
//   SELF-MOUNT — drop a "⤵ import" chip into ...... search: "SELF-MOUNT — drop a "⤵"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the sole source of truth for parsing health-export formats (Apple XML,
//    **JSON, CSV, NDJSON) into canonical events and writing them to three stores:
//    **`window.sleepAddNight`, `window.exerciseAddLog`, and `toto_food_plan` in localStorage. It
//    **exports `window.OZ_WIMPORT` (line 334) with methods `parse`, `preview`, `plan`, `commit`,
//    **`open`, and the `TYPES` vocabulary. It self-mounts a "⤵ import" button into the wellness
//    **card without touching any other dashboard state.
//
//    **TOUCH HERE** —
//    - Add a new event type → `TYPES` object L18, then add a regex rule to `TYPE_MAP` L36
//    - Add a new field alias (e.g., a Health-Connect column name) → `ALIAS` object L28
//    - Add a new sleep-stage bucket name → `STAGE_MAP` L44
//    - Change what gets written to a store (sleep/exercise/food shape) → `nightArg()` L190,
//    - `exArg()` L196, or `foodWrite()` L219
//    - Change the preview table columns or row detail text → `preview()` L164 or `renderPrev()`
//    - L260
//    - Change the modal UI (buttons, labels, layout) → `openModal()` L233
//    - Change the toast message after commit → line 295 in `go.onclick`
//    - Adjust the file-size limit for paste → line 283 (currently 200000 chars)
//
//    **TRAPS** —
//    - `ALIAS` keys (line 28: `timestamp`, `type`, `value`, `unit`, `source`) are the canonical
//    - field names; renaming them breaks `toEvent()` L63 and `pick()` calls throughout.
//    - `TYPES` keys (line 18: `sleep_session`, `sleep_stage`, `steps`, `heart_rate`, `exercise`)
//    - are the closed vocabulary; any new type must be added here AND to `TYPE_MAP` L36 AND handled
//    - in `plan()` L138 or it will silently drop.
//    - `plan()` L138 returns `{ nights, sessions, steps, hr }` — this shape is read by `preview()`
//    - L164; changing the key names breaks the preview.
//    - `commit()` L206 checks `r.write.fn` against string literals `'sleepAddNight'`,
//    - `'exerciseAddLog'`, `'food'` (lines 211–213); these must match the `fn` field set in
//    - `nightArg()`, `exArg()`, and food rows.
//    - `foodWrite()` L219 mutates `window.SANDBOX['food-plan.json']` AND
//    - `localStorage.toto_food_plan` in lockstep; both must be updated or the poller (line 204)
//    - will not re-render.
//    - The modal is idempotent (line 234 checks for `.wimp-modal`); opening it twice in quick
//    - succession is safe but the second call returns early.
//    - `isoOf()` L52 deliberately uses local timezone, not UTC, to keep a late-evening sleep on the
//    - same calendar day as the person who logged it; changing this breaks sleep-session grouping.
//    - `toEvent()` L63 returns `null` if type cannot be mapped; these nulls are silently filtered
//    - out (lines 95, 109, 119, 129); a row that maps to no type vanishes without warning.
//
//    **DO NOT** —
//    - Do not rename `window.OZ_WIMPORT` or its exported methods; external code (line 334) and the
//    - handoff API (line 333 comment) depend on these names.
//    - Do not move the idempotency check (line 13) or the IIFE boundary (lines 12, 335); this file
//    - must not double-boot.
//    - Do not change the canonical event shape `{ timestamp, type, value, unit, source }` (line 8)
//    - without updating every place that reads it: `toEvent()`, `plan()`, `preview()`, and the
//    - store-write functions.
//    - Do not add new stores (sleep/exercise/food) here; that belongs in the card files that own
//    - those stores. This file only calls the globals they provide.
//    - Do not add UI styling here; CSS for `.wimp-*` classes belongs in a separate stylesheet.
//    - Do not add new parse carriers (XML/JSON/CSV/NDJSON) without also updating the modal help
//    - text (line 238) and the error messages.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  if (window.OZ_WIMPORT) return                                       // idempotent — never double-boot
  var TXT = window                                                     // shorthand

  // ── the canonical event 'type' vocabulary — the closed set the parser normalizes onto + the store-MAP fans out.
  //    sleep is two flavours: a whole SESSION (in-bed→out) and per-STAGE minutes (deep/rem/light/awake). ──
  var TYPES = {
    sleep_session: 1,   // one night: value = total asleep MINUTES; timestamp = the night's date; +stages if present
    sleep_stage:   1,   // one stage span: value = MINUTES, unit = 'deep'|'rem'|'light'|'awake' (folded into its night)
    steps:         1,   // value = step count for the day (informational — no dedicated store; rides the note)
    heart_rate:    1,   // value = bpm sample (mean folds onto the day's exercise session as hr_mean)
    exercise:      1,   // one workout: value = MINUTES, unit = the activity name (walk/run/…); +met/hr if present
  }

  // ── field-name MAP — defensive aliases → canonical keys. Apple export.xml shifts per iOS + Health Connect json
  //    varies by exporter, so we sniff loosely + never trust one spelling. unknown columns ride along untouched. ──
  var ALIAS = {
    timestamp: ['timestamp', 'time', 'date', 'startdate', 'startDate', 'start', 'startTime', 'day', 'iso', 'creationDate'],
    type:      ['type', 'kind', 'metric', 'recordType', 'dataType', 'category'],
    value:     ['value', 'val', 'qty', 'quantity', 'amount', 'minutes', 'duration', 'count', 'steps', 'bpm'],
    unit:      ['unit', 'units', 'uom', 'stage', 'sleepStage', 'activity', 'activityType', 'exerciseType', 'name'],
    source:    ['source', 'sourceName', 'device', 'app', 'origin'],
  }
  // Apple HK type strings + Health-Connect record names → our closed 'type' set (loose contains-match, lowercased).
  var TYPE_MAP = [
    [/sleepstage|sleep_stage/,                                            'sleep_stage'],   // an EXPLICIT stage record first
    [/asleep|sleepsession|sleep_session|sleepanalysis|sleep|inbed|timeasleep/, 'sleep_session'],
    [/stepcount|steps|step_count/,                                        'steps'],
    [/heartrate|heart_rate|heart|bpm/,                                    'heart_rate'],
    [/workout|exercise|activesession|activity|move|activecalories/,       'exercise'],
    [/\bdeep\b|\brem\b|\bcore\b/,                                         'sleep_stage'],   // bare stage words LAST (loose)
  ]
  var STAGE_MAP = [                                                    // stage-name spellings → our 4 buckets
    [/deep|n3/, 'deep'], [/rem/, 'rem'], [/light|core|n1|n2/, 'light'], [/awake|wake/, 'awake'],
  ]

  var lower = function (s) { return String(s == null ? '' : s).toLowerCase() }
  // day-identity: fold to the LOCAL calendar day (toISOString would UTC-roll a late-evening night onto the next
  // day, splitting a sleep_session from its stages). a bare YYYY-MM-DD passes straight through; a parsed date is
  // shifted by its own tz offset before slicing so 2026-06-01T23:00 stays 2026-06-01 for the person who logged it.
  var isoOf = function (v) {
    var s = String(v == null ? '' : v)
    if (/^\d{4}-\d{2}-\d{2}/.test(s)) return s.slice(0, 10)              // already a plain date → trust it verbatim
    var d = new Date(v); if (isNaN(d)) return s.slice(0, 10)
    return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10)
  }
  function pick(obj, keys) { for (var i = 0; i < keys.length; i++) if (obj[keys[i]] != null && obj[keys[i]] !== '') return obj[keys[i]]; return '' }
  function mapType(raw) { var s = lower(raw); for (var i = 0; i < TYPE_MAP.length; i++) if (TYPE_MAP[i][0].test(s)) return TYPE_MAP[i][1]; return '' }
  function mapStage(raw) { var s = lower(raw); for (var i = 0; i < STAGE_MAP.length; i++) if (STAGE_MAP[i][0].test(s)) return STAGE_MAP[i][1]; return '' }

  // ── fold ANY loose object → a canonical event (or null if we can't place its type). value coerced to a number. ──
  function toEvent(o) {
    if (!o || typeof o !== 'object') return null
    var canon = {}
    // aliased pulls
    var tRaw = pick(o, ALIAS.type), uRaw = pick(o, ALIAS.unit)
    canon.type = TYPES[lower(tRaw)] ? lower(tRaw) : mapType(tRaw) || mapType(uRaw)
    if (!canon.type) return null
    canon.timestamp = isoOf(pick(o, ALIAS.timestamp))
    canon.value = +String(pick(o, ALIAS.value)).replace(/[^\d.\-]/g, '') || 0
    canon.unit = String(uRaw || '')
    canon.source = String(pick(o, ALIAS.source) || 'import')
    var met = +pick(o, ['met', 'MET', 'mets']); if (met) canon.met = met         // optional — carried onto exercise
    var hr = +pick(o, ['hr_mean', 'hrMean', 'avgHr', 'heartRateMean']); if (hr) canon.hr_mean = hr
    // a stage row that carries its stage in a dedicated column → normalize the unit to our bucket
    if (canon.type === 'sleep_stage') canon.unit = mapStage(canon.unit) || mapStage(tRaw) || canon.unit
    // seconds→minutes rescue: HK sleep/workout often arrives in seconds; a >600 "minute" value is really seconds.
    if ((canon.type === 'sleep_session' || canon.type === 'sleep_stage' || canon.type === 'exercise') && canon.value > 600) canon.value = Math.round(canon.value / 60)
    return canon
  }

  // ── PARSE — three carriers, best-effort. returns { events, warns }. never throws; a bad line is a warning, not a crash.
  function parse(text) {
    text = String(text || '').trim()
    var events = [], warns = []
    if (!text) return { events: events, warns: ['nothing to parse'] }

    // 1) Apple export.xml — <Record type="…" startDate="…" value="…" unit="…"/> — pulled by regex (no DOM, defensive).
    if (/^\s*</.test(text) && /<Record\b/i.test(text)) {
      var re = /<Record\b([^>]*)\/?>/gi, m
      while ((m = re.exec(text))) {
        var attrs = {}, ar = /(\w+)="([^"]*)"/g, a
        while ((a = ar.exec(m[1]))) attrs[a[1]] = a[2]
        var ev = toEvent(attrs); if (ev) events.push(ev)
      }
      if (!events.length) warns.push('xml had no readable <Record> rows')
      return { events: events, warns: warns }
    }

    // 2) JSON — an array of objects, OR an object wrapping one (Health-Connect exporters nest under a key).
    if (/^\s*[\[{]/.test(text)) {
      try {
        var j = JSON.parse(text)
        var arr = Array.isArray(j) ? j : (function () {
          for (var k in j) if (Array.isArray(j[k])) return j[k]                 // first array-valued key wins
          return [j]
        })()
        arr.forEach(function (o) { var ev = toEvent(o); if (ev) events.push(ev) })
        if (!events.length) warns.push('json parsed but no rows mapped to a known type')
        return { events: events, warns: warns }
      } catch (e) { warns.length = 0 }                                 // not one JSON blob — fall through to NDJSON/CSV cleanly
    }

    // 3) NDJSON — one JSON object per line. if a line isn't JSON, fall through to CSV for the whole blob.
    var lines = text.split(/\r?\n/).filter(function (l) { return l.trim() })
    var ndOk = lines.length && lines.every(function (l) { return /^\s*{/.test(l) })
    if (ndOk) {
      lines.forEach(function (l, i) { try { var ev = toEvent(JSON.parse(l)); if (ev) events.push(ev) } catch (e) { warns.push('line ' + (i + 1) + ' skipped') } })
      return { events: events, warns: warns }
    }

    // 4) CSV — sniff the header, split on comma/tab/semicolon, zip each row into an object, then fold.
    var delim = (lines[0].match(/\t/) ? '\t' : lines[0].match(/;/) ? ';' : ',')
    var head = lines[0].split(delim).map(function (h) { return h.trim().replace(/^["']|["']$/g, '') })
    lines.slice(1).forEach(function (l) {
      var cells = l.split(delim), row = {}
      head.forEach(function (h, i) { row[h] = (cells[i] || '').trim().replace(/^["']|["']$/g, '') })
      var ev = toEvent(row); if (ev) events.push(ev)
    })
    if (!events.length) warns.push('csv header didn’t match any known field (need a type + value column)')
    return { events: events, warns: warns }
  }

  // ── the store-MAP — canonical events → the REAL toto_* writes. folds stage/hr/steps events onto their day first,
  //    so one night = one sleepAddNight call + one exercise session = one exerciseAddLog call. returns a WRITE PLAN
  //    (what would be written) so PREVIEW can show it and CONFIRM can execute the SAME thing. no writes happen here.
  function plan(events) {
    var nights = {}, sessions = {}, hrDay = {}, stepDay = {}
    events.forEach(function (e) {
      var iso = e.timestamp
      if (e.type === 'sleep_session') {
        var n = nights[iso] || (nights[iso] = { iso: iso, deep: 0, rem: 0, light: 0, awake: 0, asleep: 0 })
        n.asleep = Math.max(n.asleep, Math.round(e.value)); n.source = e.source
      } else if (e.type === 'sleep_stage') {
        var m = nights[iso] || (nights[iso] = { iso: iso, deep: 0, rem: 0, light: 0, awake: 0, asleep: 0 })
        if (m[e.unit] != null) m[e.unit] += Math.round(e.value)
      } else if (e.type === 'exercise') {
        var key = iso + '·' + (e.unit || 'session')
        var s = sessions[key] || (sessions[key] = { iso: iso, name: e.unit || 'session', min: 0, met: 0, hr: [] })
        s.min += Math.round(e.value); if (e.met) s.met = +e.met; s.source = e.source
      } else if (e.type === 'heart_rate') {
        // fold hr onto that day's sessions (all of them) as a mean — approximate but useful for MET-min math
        Object.keys(sessions).forEach(function (k) { if (sessions[k].iso === iso) sessions[k].hr.push(e.value) })
        ;(hrDay[iso] = hrDay[iso] || []).push(e.value)
      } else if (e.type === 'steps') {
        stepDay[iso] = (stepDay[iso] || 0) + Math.round(e.value)
      }
    })
    return { nights: nights, sessions: sessions, steps: stepDay, hr: hrDay }
  }

  // build the PREVIEW rows — a flat, human-readable table of exactly what CONFIRM will write.
  function preview(events) {
    var p = plan(events), rows = []
    Object.keys(p.nights).sort().forEach(function (iso) {
      var n = p.nights[iso], mins = n.asleep || (n.deep + n.rem + n.light)
      rows.push({ store: '🛏️ sleep', when: iso, what: fmtHrs(mins) + ' asleep',
        detail: 'deep ' + n.deep + ' · rem ' + n.rem + ' · light ' + n.light + ' · awake ' + n.awake,
        write: { fn: 'sleepAddNight', arg: nightArg(n, mins, p.steps[iso]) } })
    })
    Object.keys(p.sessions).sort().forEach(function (k) {
      var s = p.sessions[k], dayHr = p.hr[s.iso] || []
      var hr = s.hr.length ? mean(s.hr) : (dayHr.length ? mean(dayHr) : 0)
      rows.push({ store: '🏃 move', when: s.iso, what: s.min + ' min ' + s.name,
        detail: (s.met ? 'met ' + s.met : 'met ~guess') + (hr ? ' · hr ' + hr : ''),
        write: { fn: 'exerciseAddLog', arg: exArg(s, hr) } })
    })
    // steps with NO matching workout → surface as context rows (no dedicated store; ride a note onto a light walk)
    Object.keys(p.steps).forEach(function (iso) {
      if (Object.keys(p.sessions).some(function (k) { return p.sessions[k].iso === iso })) return
      rows.push({ store: '👣 steps', when: iso, what: p.steps[iso].toLocaleString() + ' steps',
        detail: 'no workout that day — logged as a light walk',
        write: { fn: 'exerciseAddLog', arg: { iso: iso, name: 'steps (walk)', min: Math.round(p.steps[iso] / 100), met: 3.0, note: p.steps[iso] + ' steps' } } })
    })
    return { rows: rows, warns: [] }
  }
  function mean(a) { return Math.round(a.reduce(function (x, y) { return x + y }, 0) / a.length) }
  function fmtHrs(min) { return (min / 60).toFixed(1) + 'h' }
  function nightArg(n, mins, steps) {
    var a = { iso: n.iso, deep: n.deep, rem: n.rem, light: n.light, awake: n.awake, manual: false, source: n.source || 'import' }
    if (mins) a.eff = Math.round(mins / ((mins + n.awake) || 1) * 100)   // rough sleep-efficiency %
    a.note = 'imported' + (steps ? ' · ' + steps + ' steps' : '')
    return a
  }
  function exArg(s, hr) {
    var a = { iso: s.iso, name: s.name, min: s.min, note: 'imported' }
    if (s.met) a.met = s.met
    if (hr) a.hr_mean = hr
    return a
  }

  // ── COMMIT — execute a write plan the human just confirmed. calls the SAME globals the cards own; food goes to
  //    the sandbox doc + localStorage mirror so the 1.2s _foodWatch poller re-renders an open food card. HIL: only
  //    the checked rows write. returns a human summary string. ──
  function commit(rows) {
    var done = 0, foodTouched = false
    rows.forEach(function (r) {
      if (r._skip) return
      try {
        if (r.write.fn === 'sleepAddNight' && window.sleepAddNight) { window.sleepAddNight(r.write.arg); done++ }
        else if (r.write.fn === 'exerciseAddLog' && window.exerciseAddLog) { window.exerciseAddLog(r.write.arg); done++ }
        else if (r.write.fn === 'food') { foodWrite(r.write.arg); foodTouched = true; done++ }
      } catch (e) {}
    })
    return { done: done, food: foodTouched }
  }
  // food — mimic saveDoc: mutate meals, restring the sandbox doc to a NEW value + mirror to localStorage (poller catches it).
  function foodWrite(meal) {
    try {
      var j = localStorage.getItem('toto_food_plan')
      var obj = j ? JSON.parse(j) : (window.DASH_DATA && window.DASH_DATA.food) || { day: '', goal: 2000, meals: [], pantry: [] }
      obj.meals = obj.meals || []; obj.meals.push(meal)
      var data = JSON.stringify(obj, null, 2)
      window.SANDBOX = window.SANDBOX || {}
      window.SANDBOX['food-plan.json'] = { kind: 'doc', ext: 'json', mime: 'application/json', data: data }
      localStorage.setItem('toto_food_plan', data)
    } catch (e) {}
  }

  // ─────────────────────────────────────────────────────────────── UI ───────────────────────────────────────────
  // one modal: a drop-zone + paste box → parse → a preview table with per-row checkboxes → ✅ confirm writes.
  function openModal(host) {
    if (document.querySelector('.wimp-modal')) return
    var back = el('div', 'wimp-back'), modal = el('div', 'wimp-modal')
    modal.innerHTML =
      '<div class="wimp-head"><span class="wimp-title">⤵ import wellness data</span><button class="wimp-x" title="close">✕</button></div>' +
      '<div class="wimp-drop"><b>drop</b> an Apple <code>export.xml</code>, a Fit/Health-Connect <code>.json</code>/<code>.csv</code>, or NDJSON — or paste below. <span class="wimp-dim">parsed in your browser · nothing leaves this machine</span></div>' +
      '<textarea class="wimp-paste" rows="4" placeholder="…or paste NDJSON / JSON / CSV rows here"></textarea>' +
      '<div class="wimp-tools"><button class="wimp-parse">🔍 preview</button><input type="file" class="ab-file wimp-file" hidden><button class="wimp-pick">📎 choose file</button><span class="wimp-note"></span></div>' +
      '<div class="wimp-prev"></div>' +
      '<div class="wimp-foot"><label class="wimp-all"><input type="checkbox" class="wimp-allbox" checked> all</label><button class="wimp-go" disabled>✅ confirm & write</button></div>'
    back.appendChild(modal); document.body.appendChild(back)

    var paste = modal.querySelector('.wimp-paste'), prev = modal.querySelector('.wimp-prev')
    var note = modal.querySelector('.wimp-note'), go = modal.querySelector('.wimp-go'), file = modal.querySelector('.wimp-file')
    var lastRows = []
    var close = function () { back.remove() }
    modal.querySelector('.wimp-x').onclick = close
    back.addEventListener('click', function (e) { if (e.target === back) close() })

    function doParse(text) {
      var r = parse(text)
      var pv = preview(r.events); pv.warns = (pv.warns || []).concat(r.warns || [])
      lastRows = pv.rows
      note.textContent = pv.rows.length + ' row' + (pv.rows.length === 1 ? '' : 's') + ' parsed' + (pv.warns.length ? ' · ' + pv.warns.length + ' note(s)' : '')
      renderPrev(pv)
      go.disabled = !pv.rows.length
    }
    function renderPrev(pv) {
      if (!pv.rows.length) { prev.innerHTML = '<div class="wimp-empty">no rows mapped. ' + (pv.warns[0] || 'check the file format.') + '</div>'; return }
      var body = pv.rows.map(function (r, i) {
        return '<tr data-i="' + i + '"><td><input type="checkbox" class="wimp-row" checked></td>' +
          '<td>' + r.store + '</td><td>' + r.when + '</td><td>' + esc(r.what) + '</td><td class="wimp-dim">' + esc(r.detail) + '</td></tr>'
      }).join('')
      prev.innerHTML =
        (pv.warns.length ? '<div class="wimp-warns">⚠ ' + pv.warns.map(esc).join(' · ') + '</div>' : '') +
        '<table class="wimp-table"><thead><tr><th></th><th>store</th><th>day</th><th>what</th><th>detail</th></tr></thead><tbody>' + body + '</tbody></table>'
      prev.querySelectorAll('.wimp-row').forEach(function (cb, i) { cb.addEventListener('change', function () { lastRows[i]._skip = !cb.checked }) })
    }

    modal.querySelector('.wimp-parse').onclick = function () { doParse(paste.value) }
    modal.querySelector('.wimp-pick').onclick = function () { file.click() }
    modal.querySelector('.wimp-allbox').onchange = function (e) {
      prev.querySelectorAll('.wimp-row').forEach(function (cb, i) { cb.checked = e.target.checked; lastRows[i]._skip = !e.target.checked })
    }
    file.addEventListener('change', function () {
      var f = file.files[0]; if (!f) return
      var reader = new FileReader()
      reader.onload = function () {
        var t = String(reader.result || '')
        if (/^data:/.test(t)) { note.textContent = 'that looks like a .zip/binary — unzip it first (Health-Connect SQLite zips need the native import).'; return }
        paste.value = t.slice(0, 200000); doParse(t)
      }
      // .zip → binary (data URL, can't readAsText — matches attach.js); everything else is text.
      if (/\.zip$/i.test(f.name)) reader.readAsDataURL(f); else reader.readAsText(f)
      file.value = ''
    })
    // native paste of a big blob → auto-preview after a tick
    paste.addEventListener('paste', function () { setTimeout(function () { if (paste.value.trim()) doParse(paste.value) }, 30) })

    go.onclick = function () {
      var res = commit(lastRows)
      close()
      toast(host, res.done + ' entr' + (res.done === 1 ? 'y' : 'ies') + ' written 🌱 — reopen 🛏️/🏃 to see them' + (res.food ? ' (🍎 updates live)' : ''))
    }
  }

  // ── a tiny bare toast anchored to the card (mirrors OZ_SHARE.toast). ──
  function toast(near, text) {
    var t = el('div', 'wimp-toast'); t.textContent = '✓ ' + text
    ;(near || document.body).appendChild(t)
    setTimeout(function () { t.classList.add('go') }, 10); setTimeout(function () { t.remove() }, 2400)
  }
  function el(tag, cls) { var n = document.createElement(tag); if (cls) n.className = cls; return n }
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] }) }

  // ── SELF-MOUNT — drop a "⤵ import" chip into the wellness card's topbar controls the moment it appears. one flag
  //    per card so re-scans don't double-add; observe #desk for the late-mounting spa card (same shape as voice.js). ──
  function wire(card) {
    if (!card || card._wimpWired) return
    // only the spa/wellness card — match its skin or its known topbar control span
    var ctrls = card.querySelector('.well-topctrls')
    if (!ctrls && !(card.className && /p-wellness/.test(card.className))) return
    card._wimpWired = true
    var btn = el('button', 'well-daychip wimp-open'); btn.type = 'button'; btn.title = 'import a health export (Apple / Fit / Health-Connect)'
    btn.textContent = '⤵ import'
    btn.addEventListener('click', function (e) { e.stopPropagation(); openModal(card) })
    if (ctrls) ctrls.insertBefore(btn, ctrls.firstChild); else card.appendChild(btn)
  }
  function scan() {
    // the wellness card carries skin 'p-wellness'; also catch its topbar-control host directly
    document.querySelectorAll('.card').forEach(function (c) { if (/p-wellness/.test(c.className || '')) wire(c) })
    document.querySelectorAll('.well-topctrls').forEach(function (s) { var c = s.closest('.card'); if (c) wire(c) })
  }
  function boot() {
    scan()
    var desk = document.getElementById('desk') || document.body
    new MutationObserver(function () { scan() }).observe(desk, { childList: true, subtree: true })
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot()

  // handoff API — the AI's hands / a native unzip path can call parse+commit directly, bypassing the modal.
  window.OZ_WIMPORT = { parse: parse, preview: preview, plan: plan, commit: commit, open: openModal, TYPES: TYPES }
})()
