// voice.js — oz's ears + mouth, bolted onto the agent bar (the wiring the always-on-mic prototype
// pointed at). two tiny head controls per bot: 🎤 push-to-talk (SpeechRecognition → the active bot's
// stream → runTurn) and 🔈 read-aloud (SpeechSynthesis speaks the bot's reply). ADDITIVE: it observes
// bars as they mount, wraps window.runTurn to voice the answer, and touches NOTHING in workspace.js.
//
// GRACEFUL DEGRADE: WKWebView (the ozbolt host) exposes NO SpeechRecognition and the app carries no mic
// permission — so 🎤 feature-detects and, when absent, falls back to a prompt() (same as the prototype),
// wearing a muted look + a title that says why. NATIVE/OFFLINE path (later): swap listen() for a Rust
// whisper.cpp capture over the bridge (window.ozMic), then feed the transcript to sendTranscript() below.
// speechSynthesis is more likely to work (AVSpeech under the hood, no mic) but is still guarded try/catch.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   SPEECH OUT speak the bot's final reply. ....... search: "SPEECH OUT speak the"
//   SPEECH IN drop a transcript into a bar ........ search: "SPEECH IN drop a"
//   the voice controls — 👂 ear + ➤ green send ..... search: "the voice controls — 👂"
//   boot — wrap runTurn, dress every bar that's ... search: "boot — wrap runTurn,"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for voice I/O bolted onto agent bars:
//    **speech recognition (🎤 push-to-talk transcript → `sendTranscript()`) and speech synthesis
//    **(bot reply → `speak()`). It exports `window.OZ_VOICE` (line 185) with `speak`, `hush`,
//    **`isSpeaking`, `voices`, `send`, `hasMic`, `hasTTS` for native bridges and other callers. It
//    **also wraps `window.runTurn` (line 65) so every reply auto-voices without touching
//    **workspace.js.
//
//    **TOUCH HERE** —
//    - Toggle read-aloud on/off globally → `readOn()` L15 and `READ_KEY` L14 (localStorage key
//    - name)
//    - Change default voice name or per-bot voice storage key → `pickVoice()` L27, lines 30–31
//    - (localStorage keys `'oz-voice'` and `'toto_bot_' + agentId + '_voice'`)
//    - Adjust speech rate/pitch defaults → `speak()` L38, line 46 (rate `1.04`, pitch `0.9`)
//    - Change language for recognition → `ensureRec()` L82, line 84 (`rec.lang = 'en-US'`)
//    - Swap the recognizer for a native bridge → `ensureRec()` L82 (replace `new SR()` block lines
//    - 84–96) or `startListen()` L107 (replace lines 108–112)
//    - Alter the UI button text/emoji or titles → `addControls()` L127, lines 137–138 (ear), 140
//    - (send), 155 (speaker)
//    - Change where controls mount → `addControls()` L127, line 129 (`.ctx-voice` selector)
//
//    **TRAPS** —
//    - `READ_KEY` (line 14) is a localStorage key; renaming it orphans all saved user read-aloud
//    - preferences. Same for `'oz-voice'` and `'toto_bot_' + agentId + '_voice'` (lines 30–31).
//    - `window.runTurn._voiced` flag (line 64) prevents double-wrapping; if you remove it,
//    - `wrapRunTurn()` will re-wrap on every boot.
//    - `rec`, `recBar`, `recId`, `recStream`, `recBtn` (line 81) are shared state across all bars;
//    - a second recognizer or per-bar state will break push-to-talk targeting.
//    - `bar._voiceWired` (line 130) prevents re-wiring controls; removing it causes duplicate
//    - buttons.
//    - `wrapRunTurn()` (line 56) must run before `scan()` (line 172) so the wrapped `runTurn` is in
//    - place when `sendTranscript()` calls it (line 75).
//    - `hush()` (line 51) is called in `startListen()` (line 110) to cancel any in-flight speech
//    - before recording; removing it causes the mic to pick up the speaker.
//    - `setMic()` (line 100) drives both the `.rec` class AND the `.ab-send` button visibility
//    - (line 103); they must stay coupled or the UI will desync.
//
//    **DO NOT** —
//    - Rename `window.runTurn`, `window.OZ_VOICE`, `window.SpeechRecognition`,
//    - `window.speechSynthesis`, `window.MutationObserver`, or `window.prompt` — these are external
//    - APIs.
//    - Move the `wrapRunTurn()` call or the MutationObserver setup (lines 174–178) — they belong in
//    - `boot()` and must fire in order.
//    - Add new localStorage keys without documenting them; they are user data.
//    - Change the `.agent-bar`, `.ctx-voice`, `.msg-stream`, `.ab-ear`, `.ab-send`, `.ab-speak`,
//    - `.rec`, `.on` selectors or class names — the skin (CSS) depends on them.
//    - Add voice features to workspace.js or context-bar.js; this file is additive and must not
//    - require changes elsewhere.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  var SR = window.SpeechRecognition || window.webkitSpeechRecognition
  var HAS_TTS = !!window.speechSynthesis
  var READ_KEY = 'toto_voice_read'                                    // read-aloud on/off, persisted (per app, all bots)
  function readOn() { try { return localStorage.getItem(READ_KEY) === '1' } catch (_) { return false } }

  // ── SPEECH OUT ── speak the bot's final reply. cancels any in-flight utterance (barge-in), strips
  //    code the chat already hid to "📄 code…", and no-ops silently if the API isn't there.
  // THE ONE speak() (Sum 2026-07-21: "tts/stt should be global, not hardcoded in 12 places").
  // opts.force → speak even when the read-aloud toggle is OFF (a11y's "R", the alarm's wake words);
  // the auto-voicing of replies leaves force unset, so it still respects the toggle. opts.rate/pitch
  // let a caller keep its own voice character (the alarm reads slow at .85, a11y a touch quick at 1.02).
  // CHOOSE A VOICE (Sum 2026-07-21) — per-bot override (toto_bot_<id>_voice) falls back to the global
  // default (oz-voice), matched by name against the DEVICE's own voices (getVoices — "just use native
  // device options", which is also all the web demo has). null = the system default voice.
  function voices() { try { return window.speechSynthesis.getVoices() || [] } catch (_) { return [] } }
  function pickVoice(agentId) {
    try {
      var want = ''
      if (agentId) { try { want = localStorage.getItem('toto_bot_' + agentId + '_voice') || '' } catch (_) {} }
      if (!want) { try { want = localStorage.getItem('oz-voice') || '' } catch (_) {} }
      if (!want) return null
      var list = voices()
      for (var i = 0; i < list.length; i++) { if (list[i].name === want || list[i].voiceURI === want) return list[i] }
      return null
    } catch (_) { return null }
  }
  function speak(text, opts) {
    opts = opts || {}
    if (!HAS_TTS) return
    if (!opts.force && !readOn()) return
    var t = String(text == null ? '' : text).replace(/```[\s\S]*?```/g, ' (code) ').trim()
    if (!t) return
    try {
      var u = new SpeechSynthesisUtterance(t)
      u.rate = opts.rate || 1.04; u.pitch = opts.pitch == null ? 0.9 : opts.pitch
      var v = pickVoice(opts.agentId); if (v) u.voice = v
      speechSynthesis.cancel(); speechSynthesis.speak(u)
    } catch (_) {}
  }
  function hush() { if (HAS_TTS) try { speechSynthesis.cancel() } catch (_) {} }
  function isSpeaking() { try { return !!(HAS_TTS && speechSynthesis.speaking) } catch (_) { return false } }

  // wrap runTurn ONCE — after it resolves, voice the reply. keeps the original return value untouched,
  // so every caller (Enter · the ＋ upload · ozShowBot · our own 🎤) speaks with zero extra wiring.
  function wrapRunTurn() {
    if (!window.runTurn || window.runTurn._voiced) return false
    var orig = window.runTurn
    var wrapped = function (bar, id, text, opts) {
      var p = orig(bar, id, text, opts)
      if (p && p.then) p.then(function (res) { if (res && res.text && !res.error) speak(res.text, { agentId: id }) }, function () {})
      return p
    }
    wrapped._voiced = true
    window.runTurn = wrapped
    return true
  }

  // ── SPEECH IN ── drop a transcript into a bar exactly as the Enter handler does: echo it as a user
  //    turn + run the conductor cascade. this is the AnAI hand-off point — a native whisper transcript
  //    lands here too. (window.runTurn is the wrapped one, so the answer also gets spoken.)
  function sendTranscript(bar, id, text) {
    text = (text || '').trim()
    if (!text || !window.runTurn) return
    window.runTurn(bar, id, text, { echo: true })
  }

  // one shared recognizer, retargeted to whichever bar's 🎤 is held (push-to-talk, NOT always-on — the
  // desk has ≤4 docked bots, and always-on would cross-talk between them). interim text previews live in
  // the stream so you watch it transcribe; the final result fires the turn.
  var rec, recBar, recId, recStream, recBtn
  function ensureRec() {
    if (rec || !SR) return rec
    rec = new SR(); rec.continuous = false; rec.interimResults = true; rec.lang = 'en-US'
    rec.onresult = function (e) {
      var t = ''; for (var i = 0; i < e.results.length; i++) t += e.results[i][0].transcript
      if (recStream) recStream.textContent = t                       // live preview in the input
      if (e.results[e.results.length - 1].isFinal) {
        var final = t.trim()
        if (recStream) recStream.textContent = ''
        if (final) sendTranscript(recBar, recId, final)
      }
    }
    rec.onend = function () { setMic(recBtn, false) }                 // release the pressed look when the OS stops us
    rec.onerror = function () { setMic(recBtn, false) }               // no-permission / no-speech → just un-press
    return rec
  }
  // the ear lights while recording AND shows/hides its sibling green send arrow (so you can see, across the
  // room, that you're on the record). one place drives both — onresult/onend/onerror all route through here.
  function setMic(btn, on) {
    if (!btn) return
    btn.classList.toggle('rec', !!on)
    var send = btn.parentNode && btn.parentNode.querySelector('.ab-send'); if (send) send.hidden = !on
  }

  // press-and-hold the 🎤: start listening, aim the recognizer at THIS bar; release: stop (onresult fires the turn).
  function startListen(bar, btn) {
    var r = ensureRec(); if (!r) return
    recBar = bar; recId = bar.dataset.agent; recStream = bar.querySelector('.msg-stream'); recBtn = btn
    hush()                                                            // don't listen to ourselves talking
    setMic(btn, true)
    try { r.start() } catch (_) { setMic(btn, false) }                // start() throws if already running — ignore
  }
  function stopListen() { if (rec) try { rec.stop() } catch (_) {} }

  // FALLBACK (no SpeechRecognition in this webview): click → prompt() for the line, exactly as the
  // always-on-mic prototype degrades. the button wears .no-sr so the skin can mute it.
  function promptFallback(bar, btn) {
    var said = null
    try { said = window.prompt('say it to ' + (bar.dataset.agent || 'the bot') + ':') } catch (_) {}
    if (said != null) sendTranscript(bar, bar.dataset.agent, said)
  }

  // ── the voice controls — 👂 ear + ➤ green send arrow + 🔈 speaker — NOT in the head anymore: they live in
  //    the tiny bottom strip (.ctx-voice, built by context-bar.js). If the strip isn't up yet, bail WITHOUT
  //    marking wired so a later scan retries once the meter mounts. mic → EAR, click-to-record (Sum). ──
  function addControls(bar) {
    if (!bar || bar._voiceWired) return
    var slot = bar.querySelector('.ctx-voice'); if (!slot) return     // the bottom strip isn't mounted yet — retry later
    bar._voiceWired = true

    // 👂 EAR — CLICK to listen (not hold): a bright-green ➤ send arrow appears + blinks while recording, so you
    //    can tell from across the room you're on the record. Click the arrow (or the ear again) to send the snippet,
    //    then the ear again for the next one. No live SpeechRecognition in this webview → the ear types a prompt.
    var ear = document.createElement('button')
    ear.className = 'ab-ear' + (SR ? '' : ' no-sr')
    ear.textContent = '👂'
    ear.title = SR ? 'click to listen · click the green arrow (or the ear again) to send' : 'talk (type it — no live mic in this webview yet)'
    var send = document.createElement('button')
    send.className = 'ab-send'; send.type = 'button'; send.textContent = '➤'; send.title = 'send this snippet'; send.hidden = true
    ear.addEventListener('mousedown', function (e) { e.stopPropagation() })
    ear.addEventListener('click', function (e) {
      e.stopPropagation()
      if (!SR) { promptFallback(bar, ear); return }
      if (ear.classList.contains('rec')) stopListen()                 // click the ear again → finish this snippet (onresult fires the turn)
      else startListen(bar, ear)
    })
    send.addEventListener('mousedown', function (e) { e.stopPropagation() })
    send.addEventListener('click', function (e) { e.stopPropagation(); if (SR) stopListen() })   // green arrow → send

    // 🔈 read-aloud toggle — app-wide (one voice, all bots). muted look when the API is missing.
    var spk = document.createElement('button')
    spk.className = 'ab-speak' + (HAS_TTS ? '' : ' no-tts')
    var paint = function () { spk.textContent = readOn() ? '🔈' : '🔇'; spk.classList.toggle('on', readOn()) }
    spk.title = HAS_TTS ? 'read aloud — speak the reply' : 'read aloud (no speech in this webview)'
    paint()
    spk.addEventListener('mousedown', function (e) { e.stopPropagation() })
    spk.addEventListener('click', function (e) {
      e.stopPropagation()
      if (!HAS_TTS) return
      try { localStorage.setItem(READ_KEY, readOn() ? '0' : '1') } catch (_) {}
      if (!readOn()) hush()                                           // turning it off cuts any live speech
      document.querySelectorAll('.ab-speak').forEach(function (b) { b._paint && b._paint() })   // keep every bar's toggle in sync
    })
    spk._paint = paint

    slot.appendChild(spk); slot.appendChild(ear); slot.appendChild(send)   // speaker · ear · arrow, left→right
  }

  // ── boot — wrap runTurn, dress every bar that's up, and watch for bars that mount later (toggleAgent
  //    builds them on demand). one observer on the desk; cheap. ──
  function scan() { document.querySelectorAll('.agent-bar').forEach(addControls) }
  function boot() {
    wrapRunTurn()
    scan()
    var desk = document.getElementById('desk')
    if (desk && window.MutationObserver) {
      new MutationObserver(function () { wrapRunTurn(); scan() }).observe(desk, { childList: true, subtree: true })
    }
  }
  if (document.readyState === 'loading') window.addEventListener('DOMContentLoaded', boot)
  else boot()

  // expose the hand-off + speaker for the native path / other callers (window.botSay voicing, whisper bridge)
  window.OZ_VOICE = { speak: speak, hush: hush, isSpeaking: isSpeaking, voices: voices, send: sendTranscript, hasMic: !!SR, hasTTS: HAS_TTS }
})()
