// almanac.js — window.OZ_CLOCK · the ambient data layer (NOT a card). time · weather · air · moon · sun.
// ported from /clock/canvas (clock-geo + clock-wx), rounded out with air-quality, moon phase, sun times.
// THE LAW (from the clock): never block a turn. every getter returns cached/computed instantly; real
// data refreshes in the background, ready next call. free APIs, no keys (open-meteo · ip-api).
// callable / queue-able:  OZ_CLOCK.now() · .geo() · .weather() · .forecast() · .air() · .moon() · .sun() · .all()

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   geo — ip-api, cached 24h, SLC fallback, ..... search: "geo — ip-api, cached"
//   weather code → emoji / text (ported from .... search: "weather code → emoji /"
//   the cache — getters read this instantly; .... search: "the cache — getters"
//   moon phase — pure calc, no API (synodic ..... search: "moon phase — pure calc,"
//   now — fresh local time, no fetch (this is ... search: "now — fresh local time,"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for ambient data (time, weather, air
//    **quality, moon phase, sun times, geolocation). It exports `window.OZ_CLOCK` with methods:
//    **`now()`, `geo()`, `moon()`, `weather()`, `forecast()`, `air()`, `sun()`, `all()`, and
//    **`refresh()`.
//
//    **TOUCH HERE**
//    - Add a new weather code or description → `WX_ICON` L28 or `WX_DESC` L29
//    - Change AQI band thresholds → `aqiBand()` L63
//    - Change refresh interval → `setInterval()` L94
//    - Add a new field to cached weather/air/sun → `cache` object L32, then populate it in
//    - `refresh()` L34–62
//    - Change geolocation fallback → `SLC` L11
//    - Change geo cache TTL → `GEO_TTL` L11
//    - Change moon phase calculation base → `NEW0` L68 or `SYN` L68
//
//    **TRAPS**
//    - `localStorage` keys `'oz_geo'` and `'oz_geo_manual'` (L11, L15) are load-bearing; renaming
//    - orphans user location data.
//    - `cache.ts` (L32, L61) is read by external code to check freshness; removing it breaks
//    - staleness detection elsewhere.
//    - `refresh()` is called on init (L93) and every 10 minutes (L94); changing the interval
//    - affects data staleness across the app.
//    - `geo()` returns a Promise but always resolves instantly on first call (L24 returns SLC
//    - immediately; real location lands next call). This is intentional — do not block.
//    - `WX_ICON` and `WX_DESC` keys must match open-meteo weather codes (L28–29); mismatched codes
//    - silently fall back to `'⛅'` and `''` (L46).
//    - Moon calculation uses a hardcoded known new moon (L68); changing `NEW0` shifts all phase
//    - calculations backward/forward in time.
//
//    **DO NOT**
//    - Rename `OZ_CLOCK` or its public methods — external code calls these by name.
//    - Add blocking I/O to any getter (`weather()`, `air()`, `sun()`, `moon()`, `now()`); they must
//    - return instantly.
//    - Move `refresh()` calls (L93–94) to a different file; they must run here to initialize and
//    - maintain the cache.
//    - Add API keys to this file; the design is "free APIs, no keys" (L4).
//    - Change the geo fallback logic (manual → cached → fetch → SLC) without updating both `geo()`
//    - (L13–25) and its docstring (L14).
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


(function () {
  if (window.OZ_CLOCK) return

  // ── geo — ip-api, cached 24h, SLC fallback, never blocks (ported from clock-geo.js) ──
  const GEO_KEY = 'oz_geo', GEO_TTL = 864e5, SLC = { lat: 40.76, lon: -111.89 }
  let geoP = null
  function geo() {
    // a MANUAL pick (settings → HIL → location) is sticky — never overwritten by auto-detect
    try { const m = JSON.parse(localStorage.getItem('oz_geo_manual') || 'null'); if (m && m.lat != null) return Promise.resolve({ lat: m.lat, lon: m.lon }) } catch (_) {}
    try { const c = JSON.parse(localStorage.getItem(GEO_KEY) || 'null'); if (c && Date.now() - c.ts < GEO_TTL) return Promise.resolve({ lat: c.lat, lon: c.lon }) } catch (_) {}
    if (!geoP) geoP = (async () => {
      try {
        const ctrl = new AbortController(); const t = setTimeout(() => ctrl.abort(), 2000)
        const r = await fetch('https://ip-api.com/json/', { signal: ctrl.signal }); clearTimeout(t)
        if (r.ok) { const g = await r.json(); if (g.lat) localStorage.setItem(GEO_KEY, JSON.stringify({ lat: g.lat, lon: g.lon, ts: Date.now() })) }
      } catch (_) {}
    })().finally(() => { geoP = null })
    return Promise.resolve(SLC)   // SLC now; real location lands for the next call
  }

  // ── weather code → emoji / text (ported from clock-wx.js) ──
  const WX_ICON = { 0:'☀️',1:'🌤',2:'⛅',3:'☁️',45:'🌫',48:'🌫',51:'🌦',53:'🌦',55:'🌧',61:'🌧',63:'🌧',65:'🌧',71:'🌨',73:'🌨',75:'❄️',80:'🌦',81:'🌧',82:'⛈',95:'⛈',96:'⛈',99:'⛈' }
  const WX_DESC = { 0:'Clear',1:'Mostly Clear',2:'Partly Cloudy',3:'Overcast',45:'Foggy',48:'Icy Fog',51:'Light Drizzle',53:'Drizzle',55:'Heavy Drizzle',61:'Light Rain',63:'Rain',65:'Heavy Rain',71:'Light Snow',73:'Snow',75:'Heavy Snow',80:'Showers',81:'Rain Showers',82:'Violent Showers',95:'Thunderstorm',96:'Thunderstorm',99:'Thunderstorm' }

  // ── the cache — getters read this instantly; refresh() fills it in the background ──
  const cache = { wx: null, forecast: null, air: null, sun: null, ts: 0 }

  async function refresh() {
    const { lat, lon } = await geo()
    const rt = Math.round
    // weather + sunrise/sunset (open-meteo forecast — free, no key)
    try {
      const u = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}`
        + `&current=temperature_2m,weathercode,apparent_temperature,relative_humidity_2m,windspeed_10m,surface_pressure`
        + `&hourly=visibility`   // visibility is hourly-only in open-meteo — grab the current hour for "vis now"
        + `&daily=weathercode,temperature_2m_max,temperature_2m_min,sunrise,sunset`
        + `&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=8`
      const d = await (await fetch(u)).json(), c = d.current
      let vis = null; try { const h = d.hourly, i = h.time.findIndex(t => t >= c.time); vis = h.visibility[i > 0 ? i - 1 : 0] } catch (_) {}
      cache.wx = { temp: rt(c.temperature_2m), code: c.weathercode, icon: WX_ICON[c.weathercode] || '⛅', desc: WX_DESC[c.weathercode] || '', feels: rt(c.apparent_temperature), humidity: rt(c.relative_humidity_2m), wind: rt(c.windspeed_10m), pressure: rt(c.surface_pressure), vis: vis != null ? rt(vis) : null }
      cache.forecast = d.daily.time.map((iso, i) => ({ date: iso, code: d.daily.weathercode[i], hi: rt(d.daily.temperature_2m_max[i]), lo: rt(d.daily.temperature_2m_min[i]), icon: WX_ICON[d.daily.weathercode[i]] || '⛅' }))
      cache.sun = { sunrise: d.daily.sunrise && d.daily.sunrise[0], sunset: d.daily.sunset && d.daily.sunset[0] }
    } catch (_) {}
    // particulates (PM2.5/PM10) · AQI · ozone · pollen (open-meteo air-quality — free, no key).
    // pollen is EU-domain only; null elsewhere (e.g. SLC) — exposed anyway, callers handle null.
    try {
      const u = `https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}`
        + `&current=us_aqi,pm2_5,pm10,ozone,uv_index,grass_pollen,birch_pollen,ragweed_pollen&timezone=auto`
      const d = await (await fetch(u)).json(), c = d.current
      cache.air = {
        aqi: rt(c.us_aqi), pm25: c.pm2_5, pm10: c.pm10, ozone: c.ozone, uv: c.uv_index, band: aqiBand(c.us_aqi),
        pollen: { grass: c.grass_pollen, birch: c.birch_pollen, ragweed: c.ragweed_pollen },
      }
    } catch (_) {}
    cache.ts = Date.now()
  }
  function aqiBand(a) { return a == null ? '—' : a <= 50 ? 'Good' : a <= 100 ? 'Moderate' : a <= 150 ? 'Unhealthy for sensitive' : a <= 200 ? 'Unhealthy' : a <= 300 ? 'Very Unhealthy' : 'Hazardous' }

  // ── moon phase — pure calc, no API (synodic month from a known new moon) ──
  function moon(date) {
    const d = date || new Date()
    const SYN = 29.530588853, NEW0 = Date.UTC(2000, 0, 6, 18, 14)   // a known new moon
    const age = ((((d.getTime() - NEW0) / 864e5) % SYN) + SYN) % SYN
    const frac = age / SYN
    const names = ['New Moon', 'Waxing Crescent', 'First Quarter', 'Waxing Gibbous', 'Full Moon', 'Waning Gibbous', 'Last Quarter', 'Waning Crescent']
    const icons = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘']
    const i = Math.round(frac * 8) % 8
    return { phase: names[i], icon: icons[i], age: Math.round(age * 10) / 10, illumination: Math.round((1 - Math.cos(frac * 2 * Math.PI)) / 2 * 100) }
  }

  // ── now — fresh local time, no fetch (this is what PA bakes in each prompt) ──
  function now() {
    // ⚠ 2 Sep 2026 — the YEAR was missing. "Tuesday, Sep 2, 11:42 AM local" is what every bot read as NOW,
    //    and trawman filled the gap from training: "today is September 2, 2024" — then refused to look up a
    //    2026 result because it "hasn't happened yet". A clock that omits the year is a clock that lies to
    //    anything with a training cutoff.
    return new Date().toLocaleString(undefined, { weekday: 'long', year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) + ' local'
  }

  window.OZ_CLOCK = {
    now, geo, moon,
    weather:  () => cache.wx,
    forecast: () => cache.forecast,
    air:      () => cache.air,
    sun:      () => cache.sun,
    // everything ambient in one object — ready to inject into a prompt or hand back as a tool result
    all() { return { time: now(), weather: cache.wx, air: cache.air, sun: cache.sun, moon: moon(), forecast: cache.forecast } },
    refresh,
  }

  refresh()
  setInterval(refresh, 10 * 60 * 1000)
})()
