// cards.js — the card system. makeCard(spec) is the ONE chrome, written once:
//   top bar (icon · title · your controls · jewels · STOP · ▾)  +  body  +  bottom resize bar.
// each card is then just tokens + content (a micro-file). the desk scrolls; cards HOLD their
// height + push down, scroll to find. toto is an edge bar (workspace.js), NOT a card.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   makeCard — spec in, .card element out .......... search: "makeCard — spec in,"
//   a wing SLIDER — same edge handle a bot bar ..... search: "a wing SLIDER — same"
//   a card with no builder yet — the placeholder ... search: "a card with no builder"
//   toggle a card on/off in the main column ........ search: "toggle a card on/off in"
//   THE ACCORDION (Sum, 2026-07-02) — keep as ...... search: "THE ACCORDION (Sum,"
//   bundle a sandbox HTML page into ONE ............ search: "bundle a sandbox HTML"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The card chrome system: `makeCard(spec)` builds the one-time UI shell (head + body
//    **+ resize bars) that every card wears. Exports to window: `makeCard`, `toggleCard`,
//    **`setJewel`, `printDoc`, `bundleSandbox`, `expandCard`, `cardIsOpen`, `OZ_CARD_BOTTOM`.
//    **Maintains `mountedCards` (the live card registry) and `cardStack` (the DOM container).
//
//    **TOUCH HERE** —
//    - Change card's top bar layout (icon, title, controls, jewels, stop button) → `makeCard()`
//    - L22–40
//    - Change card's bottom resize behavior or appearance → `mkBottom()` L123
//    - Change card's side resize (wing cards only) → `wireCardResize()` L64
//    - Change the stop button's icon, tooltip, or halt logic → `mkStop()` L109
//    - Change how cards open/close or the accordion rule (one open at a time) → `expandOnly()` L228
//    - and `toggleCard()` L194
//    - Change the jewel (g/a/r status lights) colors or states → `setJewel()` L96
//    - Change how a card's icon renders (emoji vs. image vs. CSS) → `mkIcon()` L89
//    - Change the print dialog's iframe size or timing → `printDoc()` L167
//    - Change how sandbox assets are bundled/inlined → `bundleSandbox()` L244
//
//    **TRAPS** —
//    - `mountedCards` (L8) is the source of truth for which cards are on the desk; `toggleCard()`
//    - (L194) and `expandOnly()` (L228) must stay in sync with it or cards vanish silently.
//    - The `.collapsed` class (L204, L210, L232, L234) is the accordion state; CSS in desk.css
//    - hides the body when present — renaming it orphans the visual collapse.
//    - `cardStack` (L6) is queried by id in `mkBottom()` (L132) and `expandOnly()` (L231); if the
//    - HTML id changes, resize and accordion break.
//    - `data-edge` (L67) is set by workspace.js and read here to decide if a card resizes; a wing
//    - card with no edge attribute will not resize.
//    - `data-card` (L27) is the card's id; the deck and topbar use it to find and toggle cards —
//    - must match the key in `mountedCards`.
//    - `data-skin` (L26) and `.card-title` (L35) are read by skins and a11y; hidden by CSS but must
//    - stay in the DOM.
//    - The stop button's click handler (L112–118) checks `window.OZ_HIL` for a live ask before
//    - halting; if OZ_HIL is not loaded, it falls through to `handler(card)` — order matters.
//    - `syncEmpty()` (L10) is called by workspace.js after docking; if not called, the empty desk
//    - state won't update.
//    - The resize bar's auto-scroll logic (L139–158) uses `requestAnimationFrame` and `lastY`; the
//    - `tick()` closure reads `lastY` updated by `move()` — breaking this coupling will stall the
//    - resize.
//
//    **DO NOT** —
//    - Do not move card creation logic into workspace.js or the deck; `makeCard()` is the single
//    - chrome.
//    - Do not rename `cardStack`, `mountedCards`, or `syncEmpty` without updating workspace.js and
//    - the deck.
//    - Do not change the card's HTML structure (section > div.card-head, div.card-body, etc.)
//    - without updating desk.css selectors and any code that queries `.card-head` or `.card-body`.
//    - Do not add a close button to the head; the comment at L40 says it's intentionally absent
//    - (close = deck switch / launcher toggle, not a card button).
//    - Do not move the print frame logic; it's self-contained and reused by settings (L162).
//    - Do not move the sandbox bundler; it's shared by monaco's launch button and the webview
//    - render (comment at L241–243).
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


const cardStack = document.getElementById('card-stack')
const deskEmpty = document.getElementById('desk-empty')
const mountedCards = {}

function syncEmpty() {
  // ⭐ THE DOM DECIDES NOW (Sum 2026-08-25) — desk.css owns this: #card-stack:empty collapses, and
  //    #desk-empty hides only while the stack actually holds something. This used to write inline display
  //    onto both nodes, which meant the empty-desk brand was only ever as correct as the last caller, and
  //    a single close path that skipped it left the desk black over an empty stack with no way back.
  //    All this does now is CLEAR any inline display still carried from an older build, so the stylesheet
  //    wins. Kept and still exported because OZ_DOCK + workspace.js call it after moving a panel, and
  //    because clearing is the repair: one call unsticks a desk that a previous build painted into a corner.
  cardStack.style.display = ''
  deskEmpty.style.display = ''
}
window.syncEmpty = syncEmpty   // OZ_DOCK calls this after moving a panel on/off the desk

// ── mountGear — the ONE way a gear gets onto a head (Sum 2026-08-28: "move the gear to far
//    right like it is in the apps top bar"). Same convention as the top bar (topbar.css .tb-spacer):
//    gear = the OUTERMOST right control, past STOP, set apart by a little space. The .card-gearbox
//    wrap carries the whole convention in CSS (desk.css): the far-right seat, the set-apart gap,
//    AND the squeeze rule — on a narrow head the gearbox shrinks away FIRST so STOP survives
//    (Sum: "on min width, hides settings before kill"). Every gear goes through here — makeCard's
//    gear: param, makeSettings, appCard — so no card can scatter the seat again.
window.mountGear = function (head, node) {
  if (!head || !node) return node
  const box = document.createElement('span')
  box.className = 'card-gearbox'
  // the box carries the click-guards, so a gear press never folds or drags the card — the same
  // mousedown+click stops every gear used to carry itself (settings.js, app-card.js; those keep
  // theirs, harmlessly doubled). A gear mounted here needs NO guard of its own (AIOLI's doesn't).
  box.addEventListener('mousedown', e => e.stopPropagation())
  box.addEventListener('click', e => e.stopPropagation())
  box.appendChild(node)
  head.appendChild(box)
  return node
}

// ── makeCard — spec in, .card element out ─────────────────────────────────────
//   icon:   '🏁' (emoji) · 'path/to.png' (a crop) · {css:'<html>'} (pure CSS) — the three rungs
//   topbar/body: a Node OR an HTML string. jewels: the g/a/r status cluster.
//   stop:   () => haltRun()  → the fat red ■ (halt the run, keep what's done).
//   bottom: true (a ⇕ handle) · a png path (its texture) · false (none).
//   gear:   a settings button Node → seated FAR RIGHT (past STOP) via mountGear, never in .card-ctrls.
window.makeCard = function (spec) {
  const { id, icon = '▢', title = id, skin = '', wear = '', topbar, subbar, body, jewels = false, stop = null, bottom = true, headArt = '', headArtPos = 'center', gear = null } = spec
  const card = document.createElement('section')
  card.className = 'card' + (skin ? ' ' + skin : '')
  if (wear) card.dataset.skin = wear   // THE BEAN — a card can wear an agent skin (historian · phone …): [data-skin] on the card, same marker the agent bar uses, so the skin's rules dress the card too
  card.dataset.card = id

  const head = document.createElement('div')
  head.className = 'card-head'
  head.title = title   // ICON-ONLY (2026-07-09): the name is a hover tooltip, not visible text — the icon carries the identity

  // ── THE HEAD WEARS ART (Sum 2026-08-24: "this is not what I mean by top bar — we need better card
  //    builder bean"). A card's own chrome bar is its TOP BAR, the same way an agent bar's head is.
  //    Pass headArt and the bar becomes the picture; no words on it — the icon is still the identity
  //    and the title is still the tooltip, so a11y loses nothing. Any card, one line. (5 R's: reuse.)
  if (headArt) {
    head.classList.add('has-art')
    head.style.backgroundImage = 'url("' + headArt + '")'
    head.style.backgroundPosition = headArtPos
  }
  head.appendChild(mkIcon(icon))
  // the title stays in the DOM (card-reorder reads its text · skins hook .card-title · a11y), but is
  // hidden by .card-title { display:none } in desk.css — the icon is the identity, the name is the tooltip.
  const t = document.createElement('span'); t.className = 'card-title'; t.textContent = title
  head.appendChild(t)
  const slot = document.createElement('div'); slot.className = 'card-ctrls'; if (topbar) into(slot, topbar); head.appendChild(slot)
  if (jewels) head.appendChild(htmlNode('<span class="card-jewels"><i class="cj cj-g"></i><i class="cj cj-a"></i><i class="cj cj-r"></i></span>'))
  if (stop)   head.appendChild(mkStop(card, stop))   // stop sits top-right, jewels just left of it
  // CORRECTION (2026-08-28): stop is no longer the LAST seat — the gear sits past it, far right,
  // matching the app's top bar. jewels · STOP still cluster together; the gearbox rides outside.
  if (gear)   window.mountGear(head, gear)
  card.appendChild(head)   // NO close in the head (Sum's call — head's crowded). close = the deck switch / launcher toggle

  // IC BREAK · "one chrome row." most cards need exactly one — but a real tool (a formatting
  // toolbar, a file row) won't fit a single 46px line. so the top bar may grow INTERIOR rows: a
  // .card-subbar of extra rows that COLLAPSE WITH THE CARD, leaving the main bar (icon · title ·
  // jewels · STOP · ▾) — so the status + the halt survive a collapse. broken on purpose. (tiptap.)
  if (subbar) { const sb = document.createElement('div'); sb.className = 'card-subbar'; into(sb, subbar); card.appendChild(sb) }

  const pb = document.createElement('div'); pb.className = 'card-body'
  into(pb, body)
  card.appendChild(pb)

  if (bottom) card.appendChild(mkBottom(pb, bottom))

  // ── a wing SLIDER — same edge handle a bot bar wears (Sum 2026-07-09: "cards don't have side sliders in wings").
  //    CSS hides it unless the card is docked to a wing (a desk card fills the stack, no slider). ──
  const rz = htmlNode('<div class="card-resize" title="drag to resize"></div>')
  card.appendChild(rz)
  wireCardResize(card, rz)
  return card
}

// drag a wing card's edge handle to resize it — width on a side wing, height on top/bottom.
// mirrors workspace.js wireResize, but self-contained (no bot-geo store to pollute).
function wireCardResize(card, handle) {
  handle.addEventListener('mousedown', e => {
    e.preventDefault(); e.stopPropagation()
    const edge = card.dataset.edge
    if (!edge || edge === 'center') return                          // only a wing card resizes
    const horizontal = (edge === 'left' || edge === 'right')
    const sign = (edge === 'left' || edge === 'top') ? 1 : -1        // handle sits on the INNER edge → drag toward the wall grows it
    const start = horizontal ? e.clientX : e.clientY
    const startSize = horizontal ? card.offsetWidth : card.offsetHeight
    const min = horizontal ? 280 : 140
    document.body.style.cursor = horizontal ? 'col-resize' : 'row-resize'
    document.body.style.userSelect = 'none'
    document.body.classList.add('resizing')                         // kill iframe pointer-events so an open card's iframe can't swallow the drag
    const onMove = ev => {
      const delta = (horizontal ? ev.clientX : ev.clientY) - start
      const max = (horizontal ? window.innerWidth : window.innerHeight) * 0.7
      card.style.setProperty('--ab-size', Math.max(min, Math.min(max, startSize + sign * delta)) + 'px')
    }
    const onUp = () => { document.removeEventListener('mousemove', onMove); document.removeEventListener('mouseup', onUp); document.body.style.cursor = ''; document.body.style.userSelect = ''; document.body.classList.remove('resizing') }
    document.addEventListener('mousemove', onMove)
    document.addEventListener('mouseup', onUp)
  })
}

// icon — emoji · png · {css}
function mkIcon(icon) {
  if (icon && typeof icon === 'object' && icon.css) return htmlNode(`<span class="card-icon">${icon.css}</span>`)
  if (typeof icon === 'string' && /\.(png|svg|jpe?g|webp)$/i.test(icon)) return htmlNode(`<img class="card-icon-img" src="${icon}" alt="">`)
  return htmlNode(`<span class="card-icon">${icon}</span>`)
}

// jewels — green/amber/red. setJewel(card, state) drives them + the stop's enabled state.
window.setJewel = function (card, state) {   // 'running' | 'waiting' | 'done' | 'off'
  if (!card) return
  card.querySelectorAll('.cj').forEach(j => j.classList.remove('lit', 'blink'))
  const g = card.querySelector('.cj-g'), a = card.querySelector('.cj-a'), stop = card.querySelector('.card-stop')
  if (state === 'running') { g && g.classList.add('lit', 'blink'); stop && (stop.disabled = false) }
  else if (state === 'waiting') { a && a.classList.add('lit'); stop && (stop.disabled = false) }
  else if (state === 'done') { g && g.classList.add('lit'); stop && (stop.disabled = true) }
  else { stop && (stop.disabled = true) }
  if (stop) stop.classList.toggle('armed', !stop.disabled)   // glow red only when there's a live run to halt
}

// the big fat red STOP — halt the run, salvage what's there. an OCTAGON (stop-sign) icon so it reads as HALT,
// not a random square; dark at rest, glows red while a run is live (.armed, driven by setJewel/barJewel).
function mkStop(card, handler) {
  const b = htmlNode('<button class="card-stop" title="stop — keep what\'s done"><svg class="stop-glyph" viewBox="0 0 24 24" width="14" height="14" fill="currentColor" aria-hidden="true"><path d="M7.9 2h8.2L22 7.9v8.2L16.1 22H7.9L2 16.1V7.9z"/></svg></button>')
  b.addEventListener('mousedown', e => e.stopPropagation())   // press the halt without collapsing/dragging the bar
  b.addEventListener('click', e => {
    e.stopPropagation()
    // (Sum 2026-07-09) a green ask blinking for this bot? RED = DENY it. otherwise RED = halt the live run.
    const bot = card.dataset && card.dataset.agent
    if (bot && window.OZ_HIL && window.OZ_HIL.count && window.OZ_HIL.count(bot) > 0) { window.OZ_HIL.deny(bot); return }
    handler(card)
  })
  return b
}

// the bottom bar — drag to resize THIS card's body (independent). the desk scrolls to find it.
function mkBottom(body, look) {
  const bar = document.createElement('div')
  bar.className = 'card-bottom'; bar.title = 'drag to resize'
  if (typeof look === 'string' && /\.(png|svg|jpe?g|webp)$/i.test(look)) bar.style.backgroundImage = `url('${look}')`
  bar.addEventListener('mousedown', e => {
    e.preventDefault(); e.stopPropagation()
    // GLOBAL DESK RULE (Sum): drag to the bottom and KEEP GOING — the desk auto-scrolls for more room and the
    // card grows as tall as you pull it (a book, a long note, a feed of your own work). the room is the desk's
    // scroll; we reveal it live. height = pointer delta + however far the desk auto-scrolled while you dragged.
    const scroller = body.closest('#card-stack') || document.scrollingElement || document.documentElement
    const sy = e.clientY, sh = body.offsetHeight, startScroll = scroller.scrollTop
    let lastY = e.clientY, curH = sh, raf = 0
    document.body.style.userSelect = 'none'
    document.body.classList.add('resizing')   // CSS kills iframe pointer-events so an iframe body (woodshop · preview) can't swallow the drag → mouseup always lands → no stuck resize
    // the height the gesture is ASKING for: pointer delta + however far the desk auto-scrolled while you dragged.
    const target = () => Math.max(120, sh + (lastY - sy) + (scroller.scrollTop - startScroll))
    const tick = () => {                       // while the pointer rides an edge, scroll the desk + grow with it
      // 1) ride-an-edge auto-scroll — gentle PROPORTIONAL ramp (not a hard on/off): ~0 at the threshold, eases up
      //    the deeper you push, capped low so it never bolts. (was a flat 16px/frame the instant you crossed.)
      const r = scroller.getBoundingClientRect(), margin = 44, MAX = 7, RAMP = 0.14
      const below = lastY - (r.bottom - margin), above = (r.top + margin) - lastY
      if (below > 0) scroller.scrollTop += Math.min(MAX, below * RAMP)
      else if (above > 0 && scroller.scrollTop > 0) scroller.scrollTop -= Math.min(MAX, above * RAMP)
      // 2) EASE the real height toward the target at ≤ STEP px/frame — so a fast flick of the bar can't SNAP the
      //    card, growing OR shrinking. shrink used to be raw 1:1 pointer (twitchy); now it's throttled like grow.
      //    grow's target only climbs at the auto-scroll rate (≤MAX) so this cap never bottlenecks it — it just
      //    tames the fast free-pointer shrink. one knob to taste: STEP (px/frame, ~60fps → STEP*60 px/sec).
      const STEP = 10
      curH += Math.max(-STEP, Math.min(STEP, target() - curH))
      body.style.height = curH + 'px'
      raf = requestAnimationFrame(tick)
    }
    const move = ev => { lastY = ev.clientY }   // tick reads lastY + eases — no direct 1:1 resize on every mousemove
    const up = () => { cancelAnimationFrame(raf); document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); document.body.style.userSelect = ''; document.body.classList.remove('resizing') }
    document.addEventListener('mousemove', move); document.addEventListener('mouseup', up)
    raf = requestAnimationFrame(tick)
  })
  return bar
}
window.OZ_CARD_BOTTOM = mkBottom   // settings (custom chrome) reuses the proven resize bar

// the PRINT bean — render an HTML doc and hand it to the OS print dialog (→ Save as PDF, or a printer).
// reliable on file:// (no popup blocker). a REAL off-screen size, not 0×0 — paragraphs need a width or they
// print one word per line. one engine; every card's print button calls this. (no markdown — HTML in, PDF out.)
window.printDoc = function (html) {
  // ⭐ THE APP ROAD (Sum 2026-08-29: "I want it to open the same interface command P does"). THE HOLE:
  //   WKWebView never implements window.print(), so the iframe road below — which works fine in the
  //   BROWSER build, and is why 🖨 "used to work" on localhost — is a silent no-op in the app, taking
  //   every 🖨 with it. THE PATCH: print_webview (main.rs) reaches past the webview to AppKit and runs
  //   the real system print panel. It prints the WHOLE webview, so isolating is this half's job:
  //   the sheet goes into #oz-print-sheet, and an @media print rule hides everything else.
  //   ⚠ ALL OF IT LIVES INSIDE @media print, so nothing here touches the app on screen.
  // CORRECTION 2026-08-29, same day, hours later — THE APP BRANCH IS GONE (Sum: "the chromium easy
  //   button, we need to wire that back in at all the patches"). The Electron twin (0zweb/electron/)
  //   runs Chromium, where the iframe road below just works — and the iframe is its OWN document, so
  //   no app CSS reaches the sheet. That last part matters: CDP print-media emulation showed the
  //   in-page sheet blanked by tiptap.css L193 (`@media print { body * { visibility: hidden } }` —
  //   tiptap's own print isolation), in BOTH shells. The note above is still true about the HOLE —
  //   WKWebView still has no print, so in the TAURI twin every 🖨 is dead again, on purpose, until
  //   its build is retired or the branch is revived WITH the tiptap override. The branch's code +
  //   the revival recipe: _recycle/print-webview-app-branch.md. The Rust bolt stays registered in
  //   main.rs, unwired.
  // CORRECTION 2026-08-29, round two, his finger on the button — the iframe road fired blanks IN THE
  //   TWIN too: Electron ships no Chrome print-preview UI, and its contentWindow.print() prints the
  //   WHOLE webContents, not the frame (the CDP spy saw print() fire on the right document; Electron
  //   then aimed the pipeline at the wrong one). So the twin answers `print_sheet` (electron/main.js):
  //   the sheet renders ALONE through printToPDF and opens in the built-in PDF viewer — the preview
  //   he pointed at ("I want second pic's interface"), print + save-as-pdf buttons included. Try that
  //   first; a shell with no print_sheet (the browser build, the Tauri twin) rejects and falls to the
  //   iframe road below, which in a real browser still opens Chrome's own preview. Still true above:
  //   the iframe is the right isolation — print_sheet's hidden window is the same idea, one document
  //   further out.
  const c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
  if (c && c.invoke) {
    c.invoke('print_sheet', { html }).catch(() => { printDocFrame(html) })
    return
  }
  printDocFrame(html)
}
function printDocFrame(html) {
  let f = document.getElementById('toto-print-frame'); if (f) f.remove()
  f = document.createElement('iframe'); f.id = 'toto-print-frame'
  f.style.cssText = 'position:fixed;left:-10000px;top:0;width:800px;height:1120px;border:0;'
  document.body.appendChild(f)
  const d = f.contentWindow.document; d.open(); d.write(html); d.close()
  setTimeout(() => { try { f.contentWindow.focus(); f.contentWindow.print() } catch (_) {} }, 350)
}

// helpers — HTML string → first node; append a Node / array / HTML string into a parent
function htmlNode(html) { const d = document.createElement('div'); d.innerHTML = html.trim(); return d.firstElementChild }
function into(parent, content) {
  if (!content) return
  if (typeof content === 'string') parent.innerHTML = content
  else if (Array.isArray(content)) content.forEach(c => parent.appendChild(c))
  else parent.appendChild(content)
}

// ── a card with no builder yet — the placeholder ──
function buildPlaceholder(id, meta) {
  meta = meta || {}
  return window.makeCard({ id, icon: meta.img || meta.icon || '▢', title: meta.label || id, body: '<div class="card-soon">coming soon</div>', bottom: false })
}

window.CARD_BUILDERS = window.CARD_BUILDERS || {}   // card modules register here

// ── toggle a card on/off in the main column ──
window.toggleCard = function (id, on, meta) {
  // ⭐ THE PROFILE GATE, 2026-08-30 — the twin of the one in workspace.js:1233. Sum: "coder is
  // gone, preview lives. apply same fix to cards please."
  //
  // Same shape of hole, second map. applyProfile narrows the CARDS array, which is what the top
  // bar builds from — so no tile appears. But a card MOUNTS through this function, and this
  // function never asked whose build it was in. So desk n dog, cards:['injection'], still had a
  // working monaco: gone from the bar, gone from the registry the bar reads, and one call away
  // from being on screen.
  //
  // ⚠ THE GATE BELONGS AT THE DOOR. Everything that opens a card comes through here — a tile, a
  // bot's tool, boot restore, ?open=<id>, a deep link. Guarding those one at a time is how the
  // agent version of this bug survived a roster filter and shipped anyway.
  //
  // ⚠ 'gear' AND 'setup' ARE NEVER GATED. The gear is the only road to the API keys, and a build
  // that filters it out is a build nobody can start. Same reason bootLayout heals them out of a
  // saved layout instead of trusting it. Sum, on what a strip's gear holds: "full gear."
  var _P = window.OZ_PROFILE
  // ⚠ 'fupm' JOINS THE NEVER-GATED SET, 2026-08-30. It is the tip jar — the one card every build
  // must be able to open, including the ones given away, because the give-away builds are exactly
  // where the ask belongs. Caught by wiring the ferryman note's link: it called toggleCard('fupm')
  // and this gate refused it, since no strip lists fupm in `cards`. The alternative was adding
  // 'fupm' to four profiles and every profile after them — a list to remember instead of a rule.
  if (on && _P && _P.cards && id !== 'gear' && id !== 'setup' && id !== 'fupm' && _P.cards.indexOf(id) < 0) return false

  if (on && mountedCards[id]) {
    expandOnly(mountedCards[id]); if (window.OZ_HULL) window.OZ_HULL.scrollTo(mountedCards[id])                         // already on the desk → bring it forward (open it, the rest become bars)
  } else if (on) {
    // 💤 THE CARD'S CODE MAY NOT BE IN YET (shell/lazy.js — monaco and its templates come in on idle,
    //    after first paint). If it is missing but a bundle covers it, the placeholder holds the seat
    //    and the press RE-RUNS itself the moment the real builder lands. Nothing else changes: a card
    //    with no bundle behaves exactly as before, which is every card but monaco.
    if (!window.CARD_BUILDERS[id] && window.OZ_LAZY && window.OZ_LAZY.covers(id)) {
      window.OZ_LAZY.need(id).then(function () {
        if (!window.CARD_BUILDERS[id]) return                       // bundle carried no builder — leave the placeholder
        const seat = mountedCards[id]
        if (!seat || !seat.isConnected) return                      // he closed it while we fetched — do not reopen
        seat.remove(); delete mountedCards[id]
        window.toggleCard(id, true, meta)
      }).catch(function () {})                                      // the placeholder is the honest failure
    }
    const el = window.CARD_BUILDERS[id] ? window.CARD_BUILDERS[id]() : buildPlaceholder(id, meta)
    mountedCards[id] = el
    cardStack.insertBefore(el, cardStack.firstChild)     // newest sits at the top of the bar stack
    cardStack.scrollTop = 0
    const head = el.querySelector('.card-head')
    if (head) head.addEventListener('click', () => {     // a collapsed bar → OPEN it (expandOnly runs the desk accordion only for desk cards) · the open one → collapse
      if (el.classList.contains('collapsed')) { expandOnly(el); if (window.OZ_HULL) window.OZ_HULL.scrollTo(el) }
      else el.classList.add('collapsed')
      if (window.syncSolo) window.syncSolo()             // (Sum) re-stamp data-orient — a wing card that just collapsed becomes a rail → rotate its art
    })
    expandOnly(el)                                       // a freshly opened card is THE open one; every other card becomes a bar
    if (window.OZ_HULL) window.OZ_HULL.scrollTo(el)   // the hull: land it on the glass (3 Sep)
  } else if (!on && mountedCards[id]) {
    const wasOpen = !mountedCards[id].classList.contains('collapsed')
    const hadFocus = mountedCards[id].contains(document.activeElement)   // ♿ closing the card you're IN strands focus
    mountedCards[id].remove(); delete mountedCards[id]
    if (wasOpen) { const next = Object.values(mountedCards)[0]; if (next) expandOnly(next) }   // don't leave the desk all-bars
    // ♿ focus RETURNS TO THE TRIGGER (Sum 2026-07-14 — "the last thing"): the topbar tile that opened it;
    //    if that's gone, the next open card's head. keyboard/switch users never get dropped on <body>.
    if (hadFocus || document.activeElement === document.body) {
      const trig = document.querySelector(`.tb-btn[data-card="${id}"]`) ||
                   (Object.values(mountedCards)[0] && Object.values(mountedCards)[0].querySelector('.card-head'))
      if (trig) { if (!trig.hasAttribute('tabindex') && !trig.matches('button, a[href]')) trig.setAttribute('tabindex', '-1'); trig.focus({ preventScroll: true }) }
    }
  }
  if (window.markActive) window.markActive(id, on)   // light up the topbar drawer icon (esp. when JS opened it)
  syncEmpty()
}

// ── THE ACCORDION (Sum, 2026-07-02) — keep as many cards on the desk as you like, but exactly ONE is OPEN
//    (fullscreen); every other is a BAR. open a card (or click a bar's head) → it opens, the rest close to bars. ──
function expandOnly(el) {
  // (Sum 2026-07-11) an occupant is "on the desk" when it lives in #card-stack (the center) — NOT by data-edge, which
  //   a stray dock/restore can set and silently exempt a card (that was the learn-suite two-open bug). container = truth.
  const stack = document.getElementById('card-stack')
  if (!stack || !stack.contains(el)) { el.classList.remove('collapsed'); return }   // a WING card/bar opens on its own — never runs the desk accordion
  // ONE desk occupant open at a time — cards AND bots AND cli. wings are the place for two-up; the desk is one-at-a-time.
  Array.from(stack.children).forEach(c => { if (c.classList.contains('card') || c.classList.contains('agent-bar')) c.classList.toggle('collapsed', c !== el) })
  if (window.OZ_A11Y && window.OZ_A11Y.restoreFocus) window.OZ_A11Y.restoreFocus(el)   // ♿ focus memory — reopen where you were
}
window.expandCard = expandOnly

window.cardIsOpen = id => !!mountedCards[id]   // the deck reads this to show open cards lit + toggle them closed

// ── bundle a sandbox HTML page into ONE self-contained doc (inline its css/js/images by basename) so it
//    renders accurately in the PREVIEW iframe. single-page / SPA works; multi-page navigation + runtime
//    fetch still need the server (native). shared by monaco's launch button + the webview render. ──
window.bundleSandbox = function (html) {
  const sb = window.SANDBOX || {}
  const get = ref => { const n = String(ref).split(/[?#]/)[0].split('/').pop(); const e = sb[n] || sb[ref] || sb[String(ref).replace(/^\.?\//, '')]; return e && typeof e.data === 'string' ? e : null }
  // an asset's usable URL inside the preview's srcdoc: a data: URI stays; a disk PATH → an ABSOLUTE file:// URL
  // (resolved against the page) so it loads without base64 and without depending on the srcdoc's base.
  const assetUrl = e => /^(https?:|data:|blob:)/i.test(e.data) ? e.data : new URL(e.data, document.baseURI).href
  return String(html)
    .replace(/<link\b[^>]*?href=["']([^"']+\.css)["'][^>]*>/gi, (m, href) => { const e = get(href); return e ? '<style>\n' + e.data + '\n</style>' : m })
    .replace(/<script\b[^>]*?src=["']([^"']+\.js)["'][^>]*>\s*<\/script>/gi, (m, src) => { const e = get(src); return e ? '<script>\n' + e.data + '\n<\/script>' : m })
    .replace(/(<img\b[^>]*?src=)["']([^"']+)["']/gi, (m, pre, src) => { if (/^(https?:|data:)/i.test(src)) return m; const e = get(src); return e ? pre + '"' + assetUrl(e) + '"' : m })
    // CSS url(...) → the asset (background images, fonts). runs LAST, so it also catches url()s in inlined <style>/css.
    .replace(/url\(\s*(['"]?)([^'")]+\.(?:png|jpe?g|gif|webp|svg|woff2?|ttf|otf))\1\s*\)/gi, (m, q, ref) => { if (/^(https?:|data:)/i.test(ref)) return m; const e = get(ref); return e ? 'url("' + assetUrl(e) + '")' : m })
    // a NESTED <iframe src="x.html"> → bundle that page RECURSIVELY and inline it as srcdoc. this is how a
    // multi-file template runs at file:// — the inner page keeps its OWN viewport (a phone frame iframing a game).
    .replace(/<iframe\b([^>]*?)\ssrc=["']([^"']+\.html?)["']([^>]*)>/gi, (m, pre, src, post) => {
      if (/^(https?:|data:)/i.test(src)) return m
      const e = get(src); if (!e) return m
      const inner = window.bundleSandbox(e.data).replace(/&/g, '&amp;').replace(/"/g, '&quot;')   // escape for the srcdoc attribute
      return '<iframe' + pre + post + ' srcdoc="' + inner + '">'
    })
}

syncEmpty()   // start empty → the brand shows
