// cascade.js — OZ_CASCADE, the HAWKING PREDICTOR. NOT a phone book — a predictive CASCADE: a handful of the
// most-likely NEXT tokens at each step (ranked, the way ACAT/SwiftKey ranked Hawking's own words). tap-tap-tap
// to build a command or a line of code — never scroll a giant list, never type a whole word. + MACROS: one tap
// → a block (the hacker's "5 keystrokes → a program running in seconds"). vanilla models ship in; the CHERRY
// (rank/seed from YOUR history + codebase) is the next layer. GOFAI — pure frequency + next-token, no model call.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   VANILLA next-token maps (bigram-ish). key = ... search: "VANILLA next-token maps"
//   the SUGGESTOR brain (Sum TNG-16) — the same ... search: "the SUGGESTOR brain"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for `OZ_CASCADE`, a predictive token/macro
//    **suggester exposed on `window.OZ_CASCADE`. It ships vanilla next-token maps (CLI_NEXT,
//    **CODE_NEXT, CLI_MACROS, CODE_MACROS) and exposes three entry points: `.open()` for custom
//    **maps, `.cli()` for shell commands, and `.code(lang)` for code completion. The `.suggest()`
//    **method lets other UI strips read the same brain without opening the overlay.
//
//    **TOUCH HERE** —
//    - Add a new CLI command suggestion → `CLI_NEXT` object L10–20
//    - Add a new code language or syntax → `CODE_NEXT` object L28–35, then `CODE_MACROS` L36–41
//    - Add a macro (one-tap block) → `CLI_MACROS` L21–27 or `CODE_MACROS` L36–41
//    - Change the prompt symbol or button label → `.open()` call L104, pass `ps` or `commitLabel`
//    - Change how tokens are spaced when added → `addTok()` L57–62, specifically the regex on L60
//    - Change keyboard shortcuts (arrow keys, Enter, Backspace, Escape) → event handlers in
//    - `build()` L87–93
//    - Change how the UI renders or looks → `render()` L68–76 or `build()` L78–101 (HTML structure
//    - and class names)
//
//    **TRAPS** —
//    - `state.next`, `state.macros`, `state.built`, `state.filter`, `state.sel` are the live state
//    - object (L55, L104). Renaming any of these breaks the cascade mid-session.
//    - `nextFor()` L43 is called by both the overlay (L51) and the external `.suggest()` method
//    - (L109). Change its signature or return shape and both break.
//    - The regex on L60 (`/[\n(]$/.test(b) || /^[)\];,.:]/.test(t)`) controls spacing; it is
//    - load-bearing for readability of generated code and CLI commands.
//    - `state.onCommit` callback (L65–66) is the only way results escape the overlay. If you change
//    - how it is called or what it receives, the caller's contract breaks.
//    - `el` is the DOM node (L55, L79). It is checked for null in `close()` L56, `render()` L69,
//    - and `addTok()` L62. Removing any of these checks causes crashes.
//    - The `.suggest()` method (L109) must always read from the same maps as `.open()` uses, or the
//    - live strip and overlay will show different suggestions.
//
//    **DO NOT** —
//    - Rename `CLI_NEXT`, `CODE_NEXT`, `CLI_MACROS`, `CODE_MACROS` without updating the `.open()`,
//    - `.cli()`, `.code()`, and `.suggest()` calls that reference them.
//    - Move the `esc()` function (L7) or change its name; it is called on L73, L75, L80, L81, L83.
//    - Add state fields to the `state` object without initializing them in the `.open()` call
//    - (L104).
//    - Change the HTML class names (`.cs-wrap`, `.cs-filter`, `.cs-built`, `.cs-toks`, `.cs-macs`,
//    - etc.) without updating all the `querySelector()` calls that find them (L71, L72, L75, L81,
//    - L82, L83, L85, L95, L96, L97, L98).
//    - Move the event listener setup (L86–99) outside `build()` or the overlay will not respond to
//    - input.
//    - Add new languages to `CODE_NEXT` without also adding them to `CODE_MACROS`, or `.code(lang)`
//    - will crash trying to read undefined macros (L106).
//    - Put user-facing strings (prompt symbols, button labels, placeholder text) into the maps;
//    - they belong in the `.open()` call or as parameters.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }

  // ── VANILLA next-token maps (bigram-ish). key = the built context (or its last token); value = ranked next. ──
  var CLI_NEXT = {
    '': ['ls', 'cd', 'git', 'python3', 'npm', 'node', 'cat', 'grep', 'mkdir', 'curl', 'find', 'echo'],
    'ls': ['-la', '-a', '-lh'], 'cd': ['..', '~'],
    'git': ['status', 'add', 'commit', 'push', 'pull', 'log', 'diff', 'checkout', 'branch', 'clone'],
    'git add': ['-A', '.'], 'git commit': ['-m', '-am'], 'git commit -m': ['"wip"', '"fix"', '"update"'],
    'git checkout': ['-b', 'main'], 'git log': ['--oneline', '-p', '--stat'],
    'npm': ['install', 'run', 'start', 'test', 'init'], 'npm run': ['dev', 'build', 'start', 'test'], 'npm install': ['-D', '-g'],
    'python3': ['-m', 'app.py'], 'python3 -m': ['http.server', 'venv', 'pip', 'pytest'],
    'grep': ['-r', '-i', '-n', '-rn'], 'find': ['.', '-name', '-type'], 'find .': ['-name', '-type f'],
    'curl': ['-s', '-O', '-L'], 'cat': ['README.md', 'package.json'], 'mkdir': ['-p'], 'node': ['index.js', '-e'],
  }
  var CLI_MACROS = [
    ['⚡ serve', 'python3 -m http.server 8000'],
    ['⚡ ship', 'git add -A && git commit -m "wip" && git push'],
    ['⚡ tree', 'find . -type f -not -path "*/node_modules/*" -not -path "*/.git/*"'],
    ['⚡ ports', 'lsof -i -P -n | grep LISTEN'],
    ['⚡ sync', 'git pull && npm install'],
  ]
  var CODE_NEXT = {
    javascript: { '': ['const ', 'let ', 'function ', 'if (', 'for (', 'return ', 'console.log(', 'import ', 'export ', 'async ', 'await ', '=> '], 'function ': ['name() {\n  \n}'], 'if (': [') {\n  \n}'], 'console.log(': [')'], 'const ': ['x = '], 'for (': ['let i = 0; i < n; i++) {\n  \n}'] },
    html: { '': ['<div>', '<span>', '<button>', '<p>', '<a href="">', '<img src="">', '<script>', '</script>', '<style>', '</style>', '<ul>', '<li>'], '<div>': ['</div>'], '<button>': ['</button>'] },
    css: { '': ['display: ', 'color: ', 'background: ', 'margin: ', 'padding: ', 'border: ', 'font-size: ', 'position: ', 'flex', 'grid'], 'display: ': ['flex;', 'grid;', 'block;', 'none;'], 'position: ': ['relative;', 'absolute;', 'fixed;'] },
    python: { '': ['def ', 'import ', 'from ', 'for ', 'if ', 'print(', 'return ', 'class ', 'while ', 'with ', 'try:'], 'def ': ['name():\n    '], 'print(': [')'], 'for ': ['x in items:\n    '], 'if ': [':\n    '] },
    json: { '': ['{', '}', '[', ']', '": "', ': ', ': true', ': false', ': null'] },
    markdown: { '': ['# ', '## ', '- ', '**', '`', '```', '> ', '[]()'] },
  }
  var CODE_MACROS = {
    javascript: [['⚡ fn', 'function name() {\n  \n}\n'], ['⚡ log', "console.log('x:', )"], ['⚡ each', 'arr.forEach((x) => {\n  \n})'], ['⚡ fetch', "fetch('')\n  .then(r => r.json())\n  .then(d => {\n    \n  })"]],
    html: [['⚡ page', '<!DOCTYPE html>\n<html>\n<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title></title>\n  <style>\n    \n  </style>\n</head>\n<body>\n  \n</body>\n</html>\n']],
    css: [['⚡ center', 'display: flex;\nalign-items: center;\njustify-content: center;'], ['⚡ reset', '* { margin: 0; padding: 0; box-sizing: border-box; }']],
    python: [['⚡ main', 'if __name__ == "__main__":\n    '], ['⚡ def', 'def name():\n    pass\n']],
  }

  function nextFor(map, built) {
    var b = built.trim()
    if (map[b]) return map[b]
    var last = b.split(/\s+/).pop()
    if (map[last]) return map[last]
    return b ? [] : (map[''] || [])
  }
  function currentOpts() {
    var opts = nextFor(state.next, state.built), q = (state.filter || '').toLowerCase()
    return q ? opts.filter(function (o) { return o.toLowerCase().indexOf(q) >= 0 }) : opts
  }

  var el = null, state = null
  function close() { if (el) { el.remove(); el = null; state = null } }
  function addTok(t) {
    var b = state.built
    if (!b) state.built = t
    else if (/[\n(]$/.test(b) || /^[)\];,.:]/.test(t)) state.built = b + t   // no space after ( or before punctuation
    else state.built = b + ' ' + t
    state.filter = ''; state.sel = 0; if (el) el.querySelector('.cs-filter').value = ''; render()
  }
  function undo() { var b = state.built.replace(/\s+$/, ''), i = Math.max(b.lastIndexOf(' '), b.lastIndexOf('\n')); state.built = i > 0 ? b.slice(0, i) : ''; state.filter = ''; if (el) el.querySelector('.cs-filter').value = ''; render() }
  function commit() { var b = state.built, cb = state.onCommit; close(); if (cb && b) cb(b) }
  function macro(exp) { var cb = state.onCommit; close(); if (cb) cb(exp) }

  function render() {
    if (!el) return
    var opts = currentOpts()
    el.querySelector('.cs-built').textContent = state.built || ' '
    el.querySelector('.cs-toks').innerHTML = opts.length
      ? opts.map(function (o, i) { return '<button class="cs-tok' + (i === state.sel ? ' on' : '') + '" data-tok="' + esc(o) + '">' + esc(o.replace(/\n/g, '↵').slice(0, 30)) + '</button>' }).join('')
      : '<span class="cs-none">— end of chain · ▶ commit, or ⌫ back —</span>'
    el.querySelector('.cs-macs').innerHTML = state.macros.map(function (m) { return '<button class="cs-mac" data-mac="' + esc(m[1]) + '">' + esc(m[0]) + '</button>' }).join('')
  }

  function build() {
    el = document.createElement('div'); el.className = 'cs-wrap'
    el.innerHTML = '<div class="cs-box"><div class="cs-line"><span class="cs-ps">' + esc(state.ps) + '</span> <span class="cs-built"></span><span class="cs-cur">▋</span></div>' +
      '<input class="cs-filter" placeholder="tap a token · or type a letter to narrow · ↵ picks · ⌫ back · ⌘↵ commit · esc" spellcheck="false" autocomplete="off">' +
      '<div class="cs-toks"></div><div class="cs-macs-lbl">macros — one tap, a block</div><div class="cs-macs"></div>' +
      '<div class="cs-bar"><button class="cs-back">⌫ back</button><button class="cs-commit">▶ ' + esc(state.commitLabel) + '</button></div></div>'
    document.body.appendChild(el)
    var f = el.querySelector('.cs-filter')
    f.addEventListener('input', function () { state.filter = f.value; state.sel = 0; render() })
    f.addEventListener('keydown', function (e) {
      var opts = currentOpts()
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') { state.sel = Math.min(opts.length - 1, state.sel + 1); render(); e.preventDefault() }
      else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { state.sel = Math.max(0, state.sel - 1); render(); e.preventDefault() }
      else if (e.key === 'Enter') { if (e.metaKey || e.ctrlKey) commit(); else if (opts[state.sel]) addTok(opts[state.sel]); e.preventDefault() }
      else if (e.key === 'Backspace' && !f.value) { undo(); e.preventDefault() }
      else if (e.key === 'Escape') { close(); e.preventDefault() }
    })
    el.querySelector('.cs-toks').addEventListener('click', function (e) { var b = e.target.closest('[data-tok]'); if (b) addTok(b.dataset.tok) })
    el.querySelector('.cs-macs').addEventListener('click', function (e) { var b = e.target.closest('[data-mac]'); if (b) macro(b.dataset.mac) })
    el.querySelector('.cs-back').addEventListener('click', undo)
    el.querySelector('.cs-commit').addEventListener('click', commit)
    el.addEventListener('mousedown', function (e) { if (e.target === el) close() })
    setTimeout(function () { try { f.focus() } catch (_) {} }, 20)
  }

  window.OZ_CASCADE = {
    open: function (o) { close(); state = { next: o.next || { '': [] }, macros: o.macros || [], onCommit: o.onCommit, built: o.start || '', filter: '', sel: 0, ps: o.ps || '›', commitLabel: o.commitLabel || 'COMMIT' }; build(); render() },
    cli: function (onCommit) { this.open({ next: CLI_NEXT, macros: CLI_MACROS, onCommit: onCommit, ps: '$', commitLabel: 'TO LINE' }) },
    code: function (lang, onCommit) { this.open({ next: CODE_NEXT[lang] || CODE_NEXT.javascript, macros: CODE_MACROS[lang] || CODE_MACROS.javascript, onCommit: onCommit, ps: '‹' + (lang || 'code') + '›', commitLabel: 'INSERT' }) },
    // ── the SUGGESTOR brain (Sum TNG-16) — the same next-token maps, exposed so the CLI/Monaco LIVE strip can
    //    read them without opening the overlay. ONE brain, two faces. kind = 'cli' or a code language. ──
    suggest: function (kind, built) { var map = kind === 'cli' ? CLI_NEXT : (CODE_NEXT[kind] || CODE_NEXT.javascript); return nextFor(map, built || '') },
    macros:  function (kind) { return kind === 'cli' ? CLI_MACROS : (CODE_MACROS[kind] || []) },
  }
})()
