// cli-harness.js — window.OZ_CLI · the clioz CLI-tool loop (the Claude-Code loop, model-agnostic).
//
// THE PIVOT: small models already speak CLI (bash/git/cat/pipes). Instead of teaching them a bespoke
// tool DSL, we let a bot EMIT shell commands in its reply; THIS harness parses them, classifies each,
// runs each through a SANDBOXED, HIL-gated executor, and hands back a transcript the conductor can
// append to the bot's context — so the model sees what happened and the loop closes.
//
// SAFE-BY-DEFAULT is the whole point. A wrong/hallucinated command from a 1B must hit a WALL (denylist)
// or a HUMAN (confirm) before it can touch anything, and can NEVER escape the sandbox. This JS gate is
// the FIRST of two guards — the rust bolt's run_cli MUST enforce the SAME denylist + a canonicalize()
// sandbox-prefix pin (defense in depth). The JS regexes are a triage layer, NOT the security boundary:
// the real boundary is Rust canonicalize()+prefix (see design_doc §7). A real executor is REFUSED unless
// the caller asserts that Rust wall is present (setExecutor gates on { rustGuard:true }).
//
// ADDITIVE / classic-JS: window.* globals, no imports, one call site added to conductor.js. Kill switch
// reuses the existing window.WS_BURNED if present, plus config.killSwitch.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   config ........................................ search: "config"
//   helpers ....................................... search: "helpers"
//   heredocs — a `<<'EOF' … EOF` body is DATA, .... search: "heredocs — a `<<'EOF' …"
//   classify(cmd) → 'denied' | 'read' | 'write' ... search: "classify(cmd) →"
//   plan(text) → ordered [{cmd, source, klass}] ... search: "plan(text) → ordered"
//   the executor .................................. search: "the executor"
//   run(cmd, opts) → the gate ..................... search: "run(cmd, opts) → the"
//   proposeFromReply(text) → run the whole ........ search: "proposeFromReply(text)"
//   transcript → context string (feed back to ..... search: "transcript → context"
//   export ........................................ search: "export"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the CLI command gate: parsing shell
//    **commands from model replies, classifying them as 'denied'/'read'/'write'/'sharp', and
//    **running them through a sandboxed executor with human confirmation. It exports
//    **`window.OZ_CLI` with methods `classify()`, `plan()`, `run()`, `proposeFromReply()`,
//    **`setExecutor()`, and `transcriptToContext()`.
//
//    **TOUCH HERE**
//    - Add a new denylist rule → `config.denylist` L31–49
//    - Expand what counts as a "read" command → `config.readAllowlist` L53–57 or
//    - `config.gitReadSubs` L58
//    - Expand what counts as a "write" command → `config.writeAllowlist` L59 or
//    - `config.gitWriteSubs` L60
//    - Change sandbox directory → `config.sandboxDir` L23
//    - Adjust the flood guard (max commands per reply) → `config.maxPerReply` L25
//    - Tighten or relax path-escape detection → `escapesSandbox()` L123–147
//    - Change how human confirmation is requested → `confirmHuman()` L327–334
//    - Change how results are formatted for the model → `transcriptToContext()` L416–428
//    - Add a new command class (beyond 'denied'/'read'/'write'/'sharp') → `classify()` L181–226
//
//    **TRAPS**
//    - `config.denylist` is tested against BOTH raw and normalized forms (L194); adding a rule
//    - requires understanding that `normalize()` L81–86 collapses `${IFS}` and `${VAR}` patterns
//    - first.
//    - `escapesSandbox()` L123–147 is called from `classify()` L199 AND must also guard redirect
//    - targets (L129–132) and attached flags (L144); a path-escape rule added to one place but not
//    - the other will silently leak.
//    - `stripHeredocBody()` L167–178 removes heredoc *bodies* before `classify()` scans; the
//    - *header* (the redirect line itself) is still checked. A rule that should block heredoc
//    - headers must fire on the header line, not the body.
//    - `plan()` L241–301 reassembles backslash continuations (L230–239) and heredocs (L157–166)
//    - into single commands before passing to `classify()`. If you change how commands are split,
//    - both reassembly paths must be updated together.
//    - `run()` L342–394 honors `opts.confirmed` ONLY if `opts.confirmedCmd === cmd` (L358); a
//    - blanket approval cannot bypass per-command gates. This is load-bearing for security.
//    - `setExecutor()` L313–324 refuses a real executor unless `meta.rustGuard === true` (L317);
//    - the Rust side (`bolts.rs run_cli`) is the actual security boundary. Removing this check
//    - makes the JS classifier the only wall.
//    - `log()` L430–436 silently fails if `window.OZ_CLI._log` is not initialized; it is created at
//    - L447 during export, so logging before export will not work.
//
//    **DO NOT**
//    - Do not rename `window.OZ_CLI` or its exported methods without updating the call site in
//    - `conductor.js`.
//    - Do not move the denylist into a separate file; it is part of the gate logic and must be
//    - reviewed together with `classify()`.
//    - Do not add a new executor mode without understanding that `executorIsReal` L312 gates
//    - whether the Rust wall is present; a mock executor for tests must set `meta.dryRun:true`
//    - L316, not `meta.rustGuard:true`.
//    - Do not change the shape of the `rec` object returned by `run()` L345 without checking that
//    - `proposeFromReply()` L399–413 and `transcriptToContext()` L416–428 still consume it
//    - correctly.
//    - Do not add new config keys without exposing them in the export at L439–451 if they need to
//    - be readable from outside.
//    - Do not add sandbox-escape checks to `classify()` without also adding them to
//    - `escapesSandbox()`, or vice versa.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'
  if (window.OZ_CLI) return

  // ── config ────────────────────────────────────────────────────────────────
  var config = {
    sandboxDir: '~/totoII/sandbox',
    autoRun: false,          // when true, PLAIN 'read'-class cmds may run without confirm; write/sharp ALWAYS confirm
    maxPerReply: 20,         // cap commands parsed from a single reply (hallucination flood guard)
    killSwitch: false,       // true → block ALL runs (the hard hammer)
    agentId: null,           // set by conductor; used for the per-agent WS_BURNED kill switch
    // DENYLIST — regexes. Match → 'denied', NEVER runnable. Ordered by blast radius.
    // classify() runs a normalization pass (${IFS}→space etc) and tests BOTH raw and normalized forms
    // against this list, so token-splitting obfuscation (rm${IFS}-rf) can't slip past.
    denylist: [
      /\brm\s+(-[a-z]*\s+)*-[a-z]*r[a-z]*f|\brm\s+(-[a-z]*\s+)*-[a-z]*f[a-z]*r/i, // rm -rf / -fr any order
      /\brm\s+(-[a-z]*\s+)*-[a-z]*r[a-z]*\s+(\/|~|\$\{?HOME)/i,                    // rm -r on / ~ $HOME ${HOME}
      /\bsudo\b/i, /\bdoas\b/i,                                                    // privilege escalation
      /\bdd\b[^|]*\bof=/i,                                                         // dd of=… (disk write)
      /\bmkfs\b/i, /\bfdisk\b/i, /\bnewfs\b/i,                                     // format
      /:\s*\(\s*\)\s*\{.*\}\s*;?\s*:/,                                             // :(){ :|:& };: fork bomb
      /\|\s*(sudo\s+)?(sh|bash|zsh|fish|python[0-9.]*|node|perl|ruby)\b/i,         // curl … | sh  (pipe-to-interp)
      /\b(curl|wget|fetch)\b[^|]*\|\s*\w/i,                                        // any download piped anywhere
      />\s*\/dev\/(?!null\b)/i,                                                    // > /dev/sda etc (allow /dev/null)
      /\bchmod\b\s+(-[a-zR]+\s+)*[0-7]*\s*\/(?!.*totoII\/sandbox)/i,               // chmod on abs non-sandbox
      /\bchown\b\s+.*\s+\/(?!.*totoII\/sandbox)/i,                                 // chown on abs non-sandbox
      /\bkill\s+-9\s+1\b/i, /\bkillall\b/i,                                        // kill init / killall
      /\b(shutdown|reboot|halt|poweroff)\b/i,                                      // power
      /\bgit\s+push\b.*(--force\b|-f\b|--mirror\b)/i,                              // force / mirror push
      /\bgit\s+.*--hard\b/i,                                                       // git reset --hard
      /\beval\b/i, /\bexec\b/i,                                                    // eval/exec obfuscation
      // find with a MUTATING action (-delete/-exec/…) is never a read — deny it outright.
      /\bfind\b[\s\S]*\s-(delete|exec|execdir|ok|okdir|fprint|fprintf)\b/i
      // NB: absolute/~/../$HOME path detection is handled by escapesSandbox() (called from classify),
      //     because it must run on redirect targets and post-strip forms too — see escapesSandbox().
    ],
    readAllowlist: [
      'ls', 'cat', 'pwd', 'echo', 'head', 'tail', 'grep', 'egrep', 'fgrep',
      'find', 'wc', 'file', 'stat', 'which', 'date', 'env', 'sort', 'uniq',
      'diff', 'tree', 'du', 'df'
    ],
    gitReadSubs: ['status', 'log', 'diff', 'show', 'branch', 'remote', 'blame'],
    writeAllowlist: ['mkdir', 'touch', 'mv', 'cp', 'tee', 'rmdir', 'ln'],
    gitWriteSubs: ['add', 'commit', 'init', 'checkout', 'switch', 'stash', 'mv', 'rm']
  }

  // ── helpers ─────────────────────────────────────────────────────────────────
  function killed() {
    if (config.killSwitch) return true
    try {
      if (window.WS_BURNED && config.agentId && window.WS_BURNED.is(config.agentId, 'run_cli')) return true
    } catch (_) {}
    return false
  }

  function firstToken(cmd) {
    var m = String(cmd).trim().match(/^([^\s]+)/)
    return m ? m[1] : ''
  }

  // NORMALIZE — collapse shell-expansion forms that split a dangerous token so no regex sees it.
  // ${IFS}/$IFS is bash's word-splitter, used to break `rm -rf` into `rm${IFS}-rf`. Turn it into a space
  // and re-test. Also ${HOME}→$HOME so the $HOME checks fire on the braced form. Best-effort deob:
  // classify() tests BOTH raw and normalized against the denylist and denies if EITHER matches.
  function normalize(cmd) {
    var s = String(cmd)
    s = s.replace(/\$\{IFS\}/g, ' ').replace(/\$IFS\b/g, ' ')  // IFS word-split → space
    s = s.replace(/\$\{(\w+)\}/g, '$$$1')                       // ${VAR} → $VAR (so $HOME checks catch ${HOME})
    return s
  }

  // command/process substitution → arbitrary exec.
  function hasSubstitution(cmd) {
    return /\$\(|`|<\(|>\(/.test(String(cmd))                    // $( ) ` <( ) >( )
  }
  // any expansion we can't statically reason about (demotes a would-be read to sharp).
  function hasExpansion(cmd) {
    var s = String(cmd)
    if (hasSubstitution(s)) return true
    if (/\$\{[^}]*\}/.test(s)) return true                       // ${...}
    if (/\$'/.test(s)) return true                               // $'...'
    if (/\$[A-Za-z_]\w*/.test(s)) return true                    // bare $VAR
    return false
  }

  function stripQuotes(s) {
    return String(s).replace(/'([^']*)'/g, ' $1 ').replace(/"([^"]*)"/g, ' $1 ')
  }

  // is a captured token an out-of-sandbox absolute / home / traversal target?
  function targetEscapes(tok) {
    if (!tok) return false
    var t = String(tok).replace(/^['"]+|['"]+$/g, '')
    if (t === '/dev/null' || /^\/dev\/null(\/|$)/.test(t)) return false
    if (/^\//.test(t)) return true                              // absolute
    if (/^~($|\/)/.test(t)) return true                        // ~ or ~/
    if (/\.\.(\/|$)/.test(t)) return true                      // .. traversal
    if (/^\$\{?HOME\b/.test(t)) return true                     // $HOME / ${HOME}
    if (/^-C\//.test(t)) return true                            // attached -C/abs
    return false
  }

  // does the command reference a path that escapes the sandbox?  Belt to Rust's suspenders.
  // Runs on the NORMALIZED, quote-stripped command AND explicitly inspects redirect / input-redirect
  // targets and attached flags — the old leading-char-class anchor missed >, <, :, and attached-flag
  // letters, letting `echo x >/etc/cron.d/x`, `cat </etc/shadow`, `tar -C/etc` through as write/read.
  function escapesSandbox(cmd) {
    var raw = normalize(cmd)
    var s = stripQuotes(raw)
    var m

    // 1) explicit redirect targets:  >f  >>f  <f
    var redir = /(?:^|[^\d\w&])[<>]{1,2}\s*([^\s;&|)]+)/g
    while ((m = redir.exec(s)) !== null) {
      if (targetEscapes(m[1])) return true
    }
    // 2) $HOME / ${HOME} anywhere
    if (/\$\{?HOME\b/.test(raw)) return true
    // 3) traversal anywhere
    if (/(^|[^\w.])\.\.(\/|\s|$|'|")/.test(s)) return true
    // 4) ~ home ref anywhere
    if (/(^|[^\w.\-])~($|\/)/.test(s)) return true
    // 5) absolute path anywhere (after any non-word/./- char, incl > < = : ( space / line-start).
    //    /dev/null carved out.
    var absScan = /(^|[^\w.\-])(\/(?!dev\/null(\/|\s|$|'|"))[^\s;&|)'"<>]*)/g
    if (absScan.test(s)) return true
    // 6) attached-flag absolute, e.g. tar -C/etc, --file=/etc, -f/etc
    if (/(^|\s)-{1,2}[A-Za-z][\w-]*=?\/(?!dev\/null(\/|\s|$))/.test(s)) return true

    return false
  }

  // ── heredocs — a `<<'EOF' … EOF` body is DATA, not commands. two jobs:
  //   · heredocMarker(line) reports the terminator so plan() can gather a multi-line command as ONE unit;
  //   · stripHeredocBody(cmd) removes the body before classify SCANS it, so a path/quote/`$` INSIDE the file
  //     content can't trip the denylist or escapesSandbox — only the HEADER (the redirect target) is guarded.
  function heredocMarker(line) {
    var m = String(line).match(/<<-?\s*(?:'([A-Za-z_]\w*)'|"([A-Za-z_]\w*)"|([A-Za-z_]\w*))/)
    return m ? (m[1] || m[2] || m[3]) : null
  }
  function joinHeredoc(lines, startIdx, marker) {
    var buf = lines[startIdx].replace(/\r$/, ''), i = startIdx
    while (i + 1 < lines.length) {
      i++
      var ln = lines[i].replace(/\r$/, '')
      buf += '\n' + ln
      if (ln.trim() === marker) break
    }
    return { cmd: buf, next: i }
  }
  function stripHeredocBody(cmd) {
    var s = String(cmd)
    if (s.indexOf('<<') === -1) return s
    var lines = s.split('\n'), out = [], i = 0
    while (i < lines.length) {
      out.push(lines[i])
      var mk = heredocMarker(lines[i])
      if (mk) { i++; while (i < lines.length && lines[i].trim() !== mk) i++; if (i < lines.length) out.push(lines[i]) }
      i++
    }
    return out.join('\n')
  }

  // ── classify(cmd) → 'denied' | 'read' | 'write' | 'sharp' ────────────────────
  function classify(cmd) {
    var s = String(cmd).trim()
    if (!s) return 'read'
    // app-CLI commands (ozfile · ozprep · …) carry their OWN read/write class — honor it, so plan() tiers them the
    // same as the app-aware wrap does: an app READ auto-runs, an app WRITE gates at 'write' (not the harsher 'sharp'
    // a bare first-token lookup would give). lazy + guarded; OZ_APP_CLI loads after us but classify runs at turn-time.
    try { if (window.OZ_APP_CLI && window.OZ_APP_CLI.has(s) && window.OZ_APP_CLI.klassOf) return window.OZ_APP_CLI.klassOf(s) } catch (_) {}
    // scan the HEADER only — a heredoc body is inert data, never commands (see stripHeredocBody).
    var scan = stripHeredocBody(s)
    var norm = normalize(scan)

    // 1) DENYLIST — test raw AND normalized (defeat ${IFS} splitting).
    for (var i = 0; i < config.denylist.length; i++) {
      if (config.denylist[i].test(scan) || config.denylist[i].test(norm)) return 'denied'
    }
    // 1a) command/process substitution → arbitrary exec: DENIED (was silently 'read' before).
    if (hasSubstitution(scan)) return 'denied'
    // 1b) sandbox escape (abs / ~ / .. / $HOME / redirect-to-abs / attached-flag-abs) → DENIED.
    if (escapesSandbox(scan)) return 'denied'

    // any OTHER unreasonable expansion ($VAR, ${...}, $'...') → at least SHARP (never fast-path as read).
    var expanded = hasExpansion(scan)

    var tok = firstToken(norm)

    // 2) READ ALLOWLIST
    if (tok === 'git') {
      var sub = (norm.match(/^git\s+([^\s]+)/) || [])[1]
      if (sub && config.gitReadSubs.indexOf(sub) !== -1) return expanded ? 'sharp' : 'read'
      if (sub && config.gitWriteSubs.indexOf(sub) !== -1) return 'write'
      return 'sharp'
    }
    if (tok === 'node' && /\s--check\b/.test(norm)) return expanded ? 'sharp' : 'read'
    if (config.readAllowlist.indexOf(tok) !== -1) {
      // a "read" tool used as a WRITE via redirect (echo foo > bar) is a write, not a read.
      if (/(^|[^>])>>?\s*[^>|&\s]/.test(norm)) return 'write'
      return expanded ? 'sharp' : 'read'
    }

    // 3) WRITE ALLOWLIST (sandbox-safe mutations)
    if (config.writeAllowlist.indexOf(tok) !== -1) return 'write'
    if (/>>?\s*[^>|&\s]/.test(norm)) return 'write'

    // 4) everything else is SHARP.
    return 'sharp'
  }

  // ── plan(text) → ordered [{cmd, source, klass}] ──────────────────────────────
  // Backslash line-continuations are REASSEMBLED before classify.
  function joinContinuations(lines, startIdx) {
    var buf = lines[startIdx].replace(/\r$/, '')
    var i = startIdx
    while (/\\\s*$/.test(buf) && i + 1 < lines.length) {
      buf = buf.replace(/\\\s*$/, ' ')
      i++
      buf += lines[i].replace(/\r$/, '')
    }
    return { cmd: buf, next: i }
  }

  function plan(text) {
    var out = []
    var seen = 0
    var src = String(text || '')

    var fence = /```(?:sh|bash|console|shell)\s*\n([\s\S]*?)```/gi
    var fm
    while ((fm = fence.exec(src)) !== null) {
      var lines = fm[1].split('\n')
      for (var i = 0; i < lines.length; i++) {
        var rawLine = lines[i].replace(/\r$/, '')
        var probe = rawLine.trim()
        if (!probe) continue
        if (probe[0] === '#') continue
        if (/^[>+]\s+/.test(probe) && !/\\\s*$/.test(rawLine)) continue  // diff/continuation noise

        // a HEREDOC opener (`… <<'EOF'`) — gather the body + terminator as ONE command (the body is data,
        // never split into lines the loop would try to run). classify() scans only the header (stripHeredocBody).
        var hmark = heredocMarker(rawLine)
        if (hmark) {
          var hj = joinHeredoc(lines, i, hmark)
          i = hj.next
          var hcmd = hj.cmd.trim()
          if (hcmd) { if (seen >= config.maxPerReply) break; out.push({ cmd: hcmd, source: 'fence', klass: classify(hcmd) }); seen++ }
          continue
        }

        var joined = joinContinuations(lines, i)
        i = joined.next
        var line = joined.cmd.trim()
        if (/^\$\s+/.test(line)) line = line.replace(/^\$\s+/, '')
        if (!line) continue
        if (seen >= config.maxPerReply) break
        out.push({ cmd: line, source: 'fence', klass: classify(line) })
        seen++
      }
      if (seen >= config.maxPerReply) break
    }

    var noFences = src.replace(/```[\s\S]*?```/g, '')
    var ilines = noFences.split('\n')
    for (var j = 0; j < ilines.length; j++) {
      var ilRaw = ilines[j].replace(/\r$/, '')
      var m = ilRaw.match(/^\s*\$\s+(.+)$/)
      if (!m) continue
      var jj = j, acc = m[1]
      while (/\\\s*$/.test(acc) && jj + 1 < ilines.length) {
        acc = acc.replace(/\\\s*$/, ' ')
        jj++
        acc += ilines[jj].replace(/\r$/, '')
      }
      j = jj
      var c = acc.trim()
      if (!c) continue
      if (seen >= config.maxPerReply) break
      out.push({ cmd: c, source: 'inline', klass: classify(c) })
      seen++
    }

    return out
  }

  // ── the executor ─────────────────────────────────────────────────────────────
  // Default = DRY-RUN preview (the JS side can't run shell in the webview). A REAL executor is only
  // accepted if the caller asserts the Rust wall is present via { rustGuard:true } — otherwise every
  // JS-classifier gap becomes direct exec with NO second wall. Fail closed: refuse and stay dry-run.
  // { dryRun:true } installs a mock (tests) without the assertion. Signature:
  //   fn(cmd, opts) -> { cmd, stdout, stderr?, exit } | Promise<same>
  var executor = function dryRun(cmd) {
    return { cmd: cmd, stdout: '(dry-run)', stderr: '', exit: 0, dryRun: true }
  }
  var executorIsReal = false
  function setExecutor(fn, meta) {
    if (typeof fn !== 'function') return false
    meta = meta || {}
    if (meta.dryRun === true) { executor = fn; executorIsReal = false; return true }
    if (!meta.rustGuard) {
      log('REFUSED setExecutor: real executor requires { rustGuard:true } (bolts.rs run_cli w/ is_denied+canonicalize). staying dry-run.')
      return false
    }
    executor = fn; executorIsReal = true
    log('installed REAL executor (rustGuard asserted)')
    return true
  }

  // human confirm — THE GREEN BUTTON first (Sum 2026-08-23: "wire the clioz permissions to green button like json" — the
  // bottom modal was wonky and blocked talking to the bot). Same door as the JSON lane's gateRun (conductor.js):
  // OZ_HIL.ask on the acting bot's bar — non-blocking, the stream stays usable, deny is a press, sharp glows as no-undo.
  // In-session only (no persist): a reload kills the awaiting run() gate anyway, so a restored chip would be a ghost.
  // Falls back to the old modal (window.ozConfirm), then DENIES (fail closed) — both unchanged.
  function confirmHuman(cmd, klass) {
    try {
      if (window.OZ_HIL && window.OZ_HIL.ask) {
        var who = (typeof window.OZ_ACTOR === 'string' && window.OZ_ACTOR) || 'toto'
        return new Promise(function (resolve) {
          window.OZ_HIL.ask(who, {
            label: cmd.slice(0, 120) + ' — cli · ' + klass, irreversible: klass === 'sharp',
            run: function () { resolve(true) }, deny: function () { resolve(false) },
          })
        })
      }
    } catch (_) {}
    var msg = 'super-super-are-you-sure? oz wants to run a ' + klass.toUpperCase() +
      ' command in ' + config.sandboxDir + ':\n\n    ' + cmd + '\n\nRun it?'
    try {
      if (typeof window.ozConfirm === 'function') return window.ozConfirm(msg)
    } catch (_) {}
    return false // fail closed
  }

  // ── run(cmd, opts) → the gate ─────────────────────────────────────────────────
  // 'denied' → refuse+log, {blocked:true}. 'read' → auto-run iff config.autoRun AND plain (no |;&<>).
  // 'write'/'sharp' → REQUIRE human YES per-command.
  // PER-COMMAND CONFIRM: opts.confirmed is honored ONLY when bound to THIS exact command via
  // opts.confirmedCmd === cmd (the string the human saw). A blanket confirmed with no matching
  // confirmedCmd is IGNORED for write/sharp — one approval can't green-light a whole batch.
  function run(cmd, opts) {
    opts = opts || {}
    var klass = opts.klass || classify(cmd)
    var rec = { cmd: cmd, klass: klass, ran: false, exit: null, stdout: '', blocked: false, refusedByHuman: false }

    if (killed()) {
      rec.blocked = true; rec.reason = 'killSwitch'
      log('BLOCK (killSwitch): ' + cmd)
      return Promise.resolve(rec)
    }
    if (klass === 'denied') {
      rec.blocked = true; rec.reason = 'denied'
      log('BLOCK (denied): ' + cmd)
      return Promise.resolve(rec)
    }

    var boundConfirm = (opts.confirmed === true && opts.confirmedCmd === cmd)

    var needsHuman
    if (klass === 'read') {
      // only a PLAIN read may auto-run; a compound/redirected line never reaches here as read, but
      // re-guard defensively so autoRun can't fast-path one.
      var plainRead = !/[|;&<>]|&&|\|\|/.test(String(cmd))
      needsHuman = !(config.autoRun && plainRead)
    } else {
      needsHuman = true // write + sharp ALWAYS
    }
    if (boundConfirm) { needsHuman = false; rec.confirmedBypass = true; log('CONFIRMED-BYPASS (bound): ' + cmd) }

    var gate = needsHuman ? Promise.resolve(confirmHuman(cmd, klass)) : Promise.resolve(true)

    return gate.then(function (ok) {
      if (!ok) {
        rec.refusedByHuman = true
        log('REFUSED by human: ' + cmd)
        return rec
      }
      return Promise.resolve(executor(cmd, { sandboxDir: config.sandboxDir, klass: klass })).then(function (res) {
        res = res || {}
        rec.ran = true
        rec.exit = (typeof res.exit === 'number') ? res.exit : 0
        rec.stdout = res.stdout || ''
        rec.stderr = res.stderr || ''
        if (res.dryRun) rec.dryRun = true
        log('RAN (exit ' + rec.exit + '): ' + cmd)
        return rec
      }, function (err) {
        rec.ran = true; rec.exit = -1; rec.stderr = String(err && err.message || err)
        log('ERROR: ' + cmd + ' → ' + rec.stderr)
        return rec
      })
    })
  }

  // ── proposeFromReply(text) → run the whole plan, return a transcript ──────────
  // Does NOT forward a blanket confirmed flag. Per-command approvals come via opts.approvals =
  // { [cmdString]: true }; only steps whose exact cmd is in that map are pre-confirmed.
  function proposeFromReply(text, opts) {
    opts = opts || {}
    var approvals = opts.approvals || {}
    var steps = plan(text)
    var commands = []
    var chain = Promise.resolve()
    steps.forEach(function (step) {
      chain = chain.then(function () {
        var runOpts = { klass: step.klass }
        if (approvals[step.cmd] === true) { runOpts.confirmed = true; runOpts.confirmedCmd = step.cmd }
        return run(step.cmd, runOpts).then(function (rec) { commands.push(rec) })
      })
    })
    return chain.then(function () { return { commands: commands } })
  }

  // ── transcript → context string (feed back to the model) ─────────────────────
  function transcriptToContext(t) {
    if (!t || !t.commands) return ''
    var lines = ['[cli-harness results]']
    t.commands.forEach(function (c) {
      var status = c.blocked ? ('BLOCKED(' + (c.reason || 'denied') + ')')
        : c.refusedByHuman ? 'REFUSED(human)'
          : c.ran ? ('exit=' + c.exit) : 'skipped'
      lines.push('$ ' + c.cmd + '  → ' + status)
      if (c.ran && c.stdout) lines.push(String(c.stdout).slice(0, 4000))
      if (c.ran && c.stderr) lines.push('(stderr) ' + String(c.stderr).slice(0, 1000))
    })
    return lines.join('\n')
  }

  function log(m) {
    try {
      window.OZ_CLI._log.push({ t: Date.now(), m: m })
      if (window.OZ_CLI._log.length > 500) window.OZ_CLI._log.shift()
    } catch (_) {}
    try { if (window.OZ_CLI.config.verbose) console.log('[OZ_CLI] ' + m) } catch (_) {}
  }

  // ── export ────────────────────────────────────────────────────────────────
  window.OZ_CLI = {
    config: config,
    classify: classify,
    plan: plan,
    proposeFromReply: proposeFromReply,
    run: run,
    setExecutor: setExecutor,
    transcriptToContext: transcriptToContext,
    _log: [],
    _escapesSandbox: escapesSandbox,   // exposed for tests
    _normalize: normalize,             // exposed for tests
    _isReal: function () { return executorIsReal }
  }
})()

// node/test shim: allow require() to grab OZ_CLI without a browser.
if (typeof module !== 'undefined' && module.exports) {
  if (typeof window === 'undefined') { global.window = {} }
  module.exports = { install: function () { return window.OZ_CLI } }
}