// factory.js — DOGFOOD FACTORY RESET (Sum 2026-07-23: "refresh 0z to factory default on each build for
//   true dogfooding… keep my api, music, time map, don't clean my sandbox, I wanna see 0z out the box on
//   each rebuild"). This is the first-run experience, restored on every new build.
//
// FOR HUMANS: when the app is a NEW build, 0z wipes its saved settings back to out-of-box — so the
//   "how do you drive?" splash and the default lanes/skin/feeds return every rebuild, the way a first
//   user meets them. It KEEPS only the things you'd hate to re-do: your BYOK API keys, your My Music
//   library, and your time-travel map. Your sandbox lives on disk and is not touched, except the PAPERS
//   (since 22 Aug 2026: My View, The Feedline, the bible, the drawer, the reading log — see papers()). For a real
//   RELEASE (where users must NOT lose their settings on update), set OZ_DOGFOOD=0 in build.sh (it already does) — that
//   ships OZ_DOGFOOD=0 and this whole reset stays asleep.
//
// FOR AI:
//   1. loads FIRST in index.html, before any card reads localStorage — the reset must beat the readers.
//   2. build id comes from build-id.js (build.sh restamps it every build). reset fires only when the
//      stored build id differs AND OZ_DOGFOOD==='1'. idempotent: many builds → one reset on next boot.
//   3. whitelist = oz-build · scroll-radio-collection (My Music) · tt_trips (the time MAP) · any BYOK
//      key (…_key / …_token / apikey / secret / byok). IndexedDB (tt thumbs) + the on-disk sandbox are
//      SEPARATE storage — a localStorage wipe never reaches them, so they survive for free; the one exception
//      is papers(), which removes the newsie suite's paper files by name (22 Aug 2026).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the AUTHORED LIBRARY — content the user (or ... search: "the AUTHORED LIBRARY"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for which localStorage keys survive a
//    **dogfood factory reset. It runs before any other code reads localStorage (line 13 comment),
//    **and it owns the reset logic: it reads `window.OZ_BUILD` and `window.OZ_DOGFOOD` from the
//    **environment, compares against the stored build id, and selectively wipes localStorage. It
//    **exports nothing; it only has side effects.
//
//    **TOUCH HERE** —
//    - Add a new localStorage key to the survival whitelist → `keep()` function, lines 31–46. Add a
//    - new condition before line 47.
//    - Change which build id triggers a reset → line 23 (`cur = window.OZ_BUILD`), but this is set
//    - by build-id.js, not here.
//    - Change the reset trigger from dogfood-only to always-reset → line 22 (`if (window.OZ_DOGFOOD
//    - !== '1')`).
//    - Log or report what was wiped → line 51 (the console.log after the reset fires).
//
//    **TRAPS** —
//    - Line 22: the reset only fires if `OZ_DOGFOOD === '1'` (string, not boolean). A release build
//    - ships `OZ_DOGFOOD=0` and this entire reset sleeps (line 9–10).
//    - Line 25: `seen` is read from localStorage inside a try/catch. If localStorage is
//    - unavailable, `seen` stays null and the reset fires anyway (line 26 check will fail). This is
//    - intentional — the reset is defensive.
//    - Lines 31–46: the `keep()` function is a whitelist. Every key matching one of these patterns
//    - survives; everything else dies. Renaming a key here orphans real user data from old builds
//    - (they will be wiped on next boot). The regex patterns on lines 35, 37–40 are load-bearing —
//    - they match keys created by the app elsewhere.
//    - Line 48: the loop reads `localStorage.key(i)` while deleting. This is safe in modern
//    - browsers but fragile; do not refactor to `.entries()` or `.keys()` without testing in old
//    - Safari.
//    - Line 50: the new build id is written *after* the wipe (not before). If this line fails, the
//    - reset will fire again on next boot. This is intentional — idempotent (line 15 comment).
//
//    **DO NOT** —
//    - Do not add app-specific reset logic here (e.g., "wipe this key only if it's corrupted").
//    - This file is for the factory reset only; per-key validation belongs in the card that reads
//    - it.
//    - Do not move this code to load after other cards. It must run first (line 13 comment).
//    - Do not change `OZ_BUILD` or `OZ_DOGFOOD` here; they come from the build system (build.sh,
//    - build-id.js). If the reset condition needs to change, edit line 22, but coordinate with
//    - build.sh.
//    - Do not add IndexedDB logic here. The only sandbox logic is papers() (22 Aug 2026), the newsie
//    - suite's files by name; everything else on disk survives for free.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  // ⚠ keep() + the export are LIFTED ABOVE THE GUARDS (Sum 2026-08-17). The three early returns
  //   below (release build · no build id · same build) are correct for the AUTOMATIC reset — but they
  //   also skipped the export, so window.OZ_FACTORY never existed and the button said "not loaded".
  //   The list and the callable are declared first; the auto-reset still guards itself.
  // ⭐ ONE PATTERN, TWO BUTTONS (2026-08-25). The factory reset KEEPS whatever matches this; the
  //    "reset keys" button WIPES exactly the same set and nothing else. They are opposites, so they
  //    must never be two regexes — the day one grew a case the other did not, a reset would either
  //    strand a dead key or eat a live one, silently, and the symptom would be a bot that just
  //    stopped working. Add a key shape HERE and both buttons learn it at once.
  var KEYPAT = /(_key$|_key_|_token$|apikey|secret|byok)/i
  var keep = function (k) {
    return k === 'oz-build'
      || k === 'scroll-radio-collection'                // My Music (mp3 PATHS; the files live on disk)
      || k === 'tt_trips'                               // the time-travel MAP
      // 2 Sep 2026 — Sum: "the permissions need to live past soft reset, rebundle and rebuild too." The reach tier he set
      //    on a bot (oz-perm.js: pkey = the pick, ckey = the granted lift) is a decision, like a key or a model pick. A wipe that
      //    forgot it pinned the tutor back at the green press (three buttons waiting, 16:30) after every reset.
      || k.indexOf('toto_bot_') === 0 || k.indexOf('toto_bot_') === 0   // the permission tiers, per bot
      || KEYPAT.test(k)                                 // BYOK API keys — the pattern is KEYPAT, just below
      // ── the AUTHORED LIBRARY — content the user (or their studios) MADE; cost tokens, gone = gone ──
      || /^clock-gen-/.test(k)                          // every studio-made pool (koans, authors-long, …)
      || /^clock-never-/.test(k)                        // their prunes ("removed once = never again")
      || /^clock-off-/.test(k)                          // their line-by-line curation
      || /^clock-filter-/.test(k)                       // their doctrines (typed by hand)
      || k === 'clock-authors' || k === 'clock-authors-known'  // their author roster
      || k === 'clock-interests'                        // their interests line
      || k === 'scroll-custom-sources'                  // feeds they hunted + added
      || k === 'scroll-geos'                            // their saved towns
      || k === 'scroll-mute'                            // their muzzle list — words they never want back
      // ── the MODEL PICKS (2 Sep 2026): which model runs which bot is a setting he'd hate to redo — on a local-model
      //    day a reset that forgets them drops every bot back to haiku (and a spent key answers "credit balance too
      //    low"). A pick is not a persona; the persona still resets. Sum to veto if out-of-box should forget them.
      || /^toto_bot_.*_model$/.test(k)
      // ── ⭐ THE COURSEWORK (1 Sep 2026, Sum: "I don't like that they wiped on factory reset… they did,
      //    it explains it, it SHOULDN'T have"). Same doctrine as the authored library above and it was
      //    always meant to be covered by it: a lesson is content he MADE, it cost tokens and an evening,
      //    and gone = gone. It just was not on the list, so a reset ate a whole day's study silently.
      //    ⚠ THE GRADES ARE THE WORST OF IT — every practice attempt and test score, oldest first. That
      //    is not regenerable at any price: it is the record of what he actually got wrong, which is the
      //    one input the tutor pitches from. A re-run gets you a new lesson; nothing gets you back the
      //    history of your own mistakes. It ranks above the lesson text it sits next to.
      //    COVERS: toto_learn_lesson (the working lesson) · _courses (the shelf) · _grades · _perf ·
      //    _skills · and the profile he typed by hand (_how · _style · _level · _hard · _disorders ·
      //    _strong · _weak) — the accommodations especially, which nobody should have to re-declare.
      //    ⚠ Safe against the OTHER button: resetKeys() matches KEYPAT (API keys) and never keep(), so
      //    nothing here becomes deletable by the second rung. Checked before writing this, not assumed.
      || /^toto_learn_/.test(k)                         // every lesson, grade, and the learner profile
      || /^toto_tutor_/.test(k)                         // how he asked to be taught (persona req · teach-how)
  }

  // ── ⭐ THE BUTTON (Sum 2026-08-17: "reset whole app to factory and save my keys, should be an easy
  //    button for that"). The wipe above already did exactly this — it just only ever fired on its
  //    own, when the build stamp changed. Same `keep()` list, same rules, now callable on purpose.
  //    KEPT: BYOK API keys · My Music · the time-travel map · every studio-made pool, prune,
  //    curation, doctrine, author roster, custom feed, saved town and muzzle word.
  //    KILLED: everything else — bot personas, saved voices, chats, card state, drafts.
  //    Returns the number of keys wiped so a caller can say so.
  window.OZ_FACTORY = {
    keep: keep,
    KEYPAT: KEYPAT,
    peek: function () {   // what WOULD go — count first, wipe second. never a surprise.
      var k = [], i
      for (i = 0; i < localStorage.length; i++) { var x = localStorage.key(i); if (x && !keep(x)) k.push(x) }
      return k
    },
    // ── ⭐ THE SECOND RUNG (Sum 2026-08-25: "reset keys / delete sandbox files / as 3 separate buttons
    //    for the level of refresh you want"). The EXACT INVERSE of the reset above: that one keeps every
    //    key and wipes the rest; this one wipes every key and keeps the rest. Same KEYPAT, so the two can
    //    never disagree about what a key is.
    //    THIS IS THE ONE THAT COSTS REAL MONEY TO UNDO — a wiped key has to be re-issued or re-pasted from
    //    the provider, and nothing in oz can give it back. peekKeys() first, always, so the count is on
    //    screen before the press. No reload: the pickers read live and a keyless bot simply goes quiet.
    peekKeys: function () {
      var k = [], i
      for (i = 0; i < localStorage.length; i++) { var x = localStorage.key(i); if (x && KEYPAT.test(x)) k.push(x) }
      return k
    },
    resetKeys: function () {
      var kill = this.peekKeys(), i
      for (i = 0; i < kill.length; i++) { try { localStorage.removeItem(kill[i]) } catch (_) {} }
      return kill.length
    },
    // THE PAPERS (Sum 2026-08-22: "factory reset needs to reset my view and the feedline"; 22 Aug eve: "my reset to factory
    // button still isn't clearing the papers" — the sweep lived only in the newsie bean, shell/oz-app-ui.js factory_reset;
    // moved here so the button and the bean are one door). The sandbox files the newsie suite wrote — My View's and The
    // Feedline's editions, the bible, the link book, the hold drawer, the reading log — go off disk through sandbox_remove.
    // Everything else in the sandbox stays (the studio, the trips, your files). Returns how many went.
    papers: function () {
      var PAPERS = /^(editions\/(myview|feedline)-|feedline\/|reads\/|port\/hold-)/, gone = 0
      try { var c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__); var sb = window.SANDBOX || {}
        Object.keys(sb).filter(function (k) { return PAPERS.test(k) }).forEach(function (k) { try { c && c.invoke && c.invoke('sandbox_remove', { name: k }); delete sb[k]; gone++ } catch (_) {} }) } catch (_) {}
      return gone
    },
    reset: function () {
      var kill = window.OZ_FACTORY.peek()
      kill.forEach(function (k) { try { localStorage.removeItem(k) } catch (_) {} })
      var papers = window.OZ_FACTORY.papers()
      try { localStorage.setItem('oz-build', (window.OZ_BUILD || 'manual')) } catch (_) {}
      try { console.log('[factory] manual reset — wiped ' + kill.length + ' keys + ' + papers + ' paper file(s), kept API+music+map+authored') } catch (_) {}
      return kill.length
    },
  }


  try {
    if (window.OZ_DOGFOOD !== '1') return                 // release build → never reset
    var cur = window.OZ_BUILD || ''
    if (!cur) return
    var seen = null; try { seen = localStorage.getItem('oz-build') } catch (_) {}
    if (seen === cur) return                               // same build — leave everything alone

    // a NEW build → out-of-box reset. SETTINGS reset; AUTHORED CONTENT survives (Sum 2026-07-23
    // morning: the first reset ate his studio library — "everything is blank again". the line:
    // out-of-box means fresh DEFAULTS + the onboarding splash, never destroying what he MADE.)
    var kill = []
    for (var i = 0; i < localStorage.length; i++) { var k = localStorage.key(i); if (k && !keep(k)) kill.push(k) }
    kill.forEach(function (k) { try { localStorage.removeItem(k) } catch (_) {} })
    try { localStorage.setItem('oz-build', cur) } catch (_) {}
    try { console.log('[factory] out-of-box reset for build ' + cur + ' — wiped ' + kill.length + ' keys, kept API+music+map') } catch (_) {}
  } catch (_) { /* never let the reset break boot */ }

})();
