// oz-app-inj.js — `ozinj`: the 💉 injection-config chisels as a CLI (the nurse's fine tools).
//
// FOR HUMANS
//   the atomic injection beans (inj_set_persona, inj_ethics_add, inj_toggle_section …) become one
//   command. this is LOAD-BEARING: every field here compiles into a bot's system prompt (its chart).
//   set a bot's persona/backstory (per-agent → recompiles that head), the shared soul every bot
//   inherits (yoga/substrate/wetware → recompiles ALL), the ethics rules, or which sections compile.
//   (human bio — name/pronouns/label/who — lives on `ozchart bio`, not here, to avoid two doors.)
//
// FOR AI
//   1. set-name/pronouns/backstory/persona take --agent (default toto) → that ONE head recompiles.
//   2. set-yoga/substrate/wetware + ethics + section touch the SHARED soul → EVERY head recompiles.
//   3. ethics-toggle/remove take --index (0-based, chart order); section takes --name + --on/--off.
//
// registers on window.OZ_APP_CLI (oz-app-cli.js) — loads AFTER it. depends on: localStorage ·
// window.cacheChart (one head) · window.cacheAllCharts (all heads).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   inj* — the store helpers. set a key + ...... search: "inj* — the store"
//   the subcommands — one per injection bean ... search: "the subcommands — one"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the `ozinj` CLI command, which sets
//    **injection fields (persona, ethics, soul attributes) that compile into every bot's system
//    **prompt. It registers `APP.makeApp()` on `window.OZ_APP_CLI` (line 53) and depends on
//    **`window.cacheChart` and `window.cacheAllCharts` (line 16) to recompile heads after changes.
//
//    **TOUCH HERE**
//    - Add a new per-agent field (name/pronouns/backstory/persona) → `agentField()` L35, then add a
//    - subcommand at L71–76
//    - Add a new shared soul field (yoga/substrate/wetware) → `soulField()` L44, then add a
//    - subcommand at L78–80
//    - Add an ethics rule → `ethics-add` subcommand L82–87
//    - Toggle or remove an ethics rule → `ethics-toggle` L89–95 or `ethics-remove` L97–102
//    - Turn a section on/off → `section` subcommand L104–113
//    - Change the default agent name → line 38 (currently `'toto'`)
//    - Change localStorage key names → lines 26, 27, 32, 78, 79, 80, 107, 111 (all prefixed
//    - `toto_inj_` or `toto_bot_`)
//
//    **TRAPS**
//    - localStorage keys are load-bearing state: `toto_inj_ethics`, `toto_inj_yoga`,
//    - `toto_inj_substrate`, `toto_inj_wetware`, `toto_inj_off`, and `toto_bot_<agent>_<field>`
//    - (lines 26, 32, 78–80, 107, 111, 39). Renaming them orphans user data.
//    - The hardcoded agent name `'toto'` appears in lines 32, 78, 79, 80, 107, 111 — all must
//    - change together if the default agent changes.
//    - `recompAgent(agent)` (line 28) and `recompAll()` (line 29) must be called after every
//    - `setLS()` or the bot's system prompt will not update. Check that every subcommand calls one
//    - of these.
//    - Ethics rules are stored as JSON arrays with `{ rule, note, on }` shape (line 85); changing
//    - the shape breaks existing user data.
//    - Section names are hardcoded in the help text (line 69) and validated implicitly by the
//    - prompt-compilation logic elsewhere; adding a new section requires coordination with that
//    - logic.
//
//    **DO NOT**
//    - Rename `APP`, `flag`, `setLS`, `getLS`, `recompAgent`, `recompAll`, `ethics`, `ethicsSet`,
//    - `agentField`, `soulField` — these are internal helpers, but their names are stable.
//    - Move the registration call (line 53) or change the app name `'ozinj'` — other code depends
//    - on this command name.
//    - Store human bio (name/pronouns/label/who) here — it lives on `ozchart bio` (line 8) to avoid
//    - two doors.
//    - Change the localStorage key prefix from `toto_` without updating every reference and
//    - understanding the data-loss consequence.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  'use strict'

  var APP = window.OZ_APP_CLI; if (!APP) return
  var flag = APP.flag

  // ── inj* — the store helpers. set a key + recompile the head(s) the change touches ──

  function setLS(k, v) { try { localStorage.setItem(k, String(v)) } catch (_) {} }
  function getLS(k, d) { try { var v = localStorage.getItem(k); return v == null ? d : v } catch (_) { return d } }
  function recompAgent(a) { if (window.cacheChart) window.cacheChart(a); else if (window.cacheAllCharts) window.cacheAllCharts() }
  function recompAll() { if (window.cacheAllCharts) window.cacheAllCharts() }

  function ethics() { try { return JSON.parse(getLS('toto_inj_ethics', '[]')) || [] } catch (_) { return [] } }
  function ethicsSet(a) { setLS('toto_inj_ethics', JSON.stringify(a)) }

  // a per-agent identity field (name/pronouns/backstory/persona) — toto_bot_<agent>_<field> → recompile that head.
  function agentField(a, field, label) {
    var v = a._.join(' ').trim()
    if (!v) return 'ozinj: pass the ' + label + ' text (in quotes).'
    var agent = flag(a, 'agent') || 'toto'
    setLS('toto_bot_' + agent + '_' + field, v); recompAgent(agent)
    return 'ozinj — ' + agent + "'s " + label + ' set. head recompiled.'
  }

  // a shared soul field (yoga/substrate/wetware) — every bot inherits it → recompile ALL.
  function soulField(a, key, label) {
    var v = a._.join(' ').trim()
    if (!v) return 'ozinj: pass the ' + label + ' text (in quotes).'
    setLS(key, v); recompAll()
    return 'ozinj — ' + label + ' set. all heads recompiled.'
  }

  // ── the subcommands — one per injection bean (bio stays on ozchart) ──

  APP.makeApp({
    name: 'ozinj',
    blurb: 'the injection-config chisels — persona · soul · ethics · sections (every bot\'s system prompt)',
    clue:
`ozinj — the 💉 injection-config chisels, as a CLI. LOAD-BEARING: this IS every bot's system prompt.
per-agent set-* recompiles that one head; soul/ethics/section recompile every head. (human bio is \`ozchart bio\`.)
  ozinj set-name --agent toto "toto"
  ozinj set-pronouns --agent toto "they/them"
  ozinj set-backstory --agent toto "a clone with implanted memories…"
  ozinj set-persona --agent toto "warm, wry, plain-spoken…"   (the most powerful field)
  ozinj set-yoga "the yamas…"          (shared soul — all heads)
  ozinj set-substrate "you are fixed weights loaded into RAM…"
  ozinj set-wetware "the initiating node is biological…"
  ozinj ethics-add --rule ahimsa --note "do no harm"
  ozinj ethics-toggle --index 2 --off   (--on · --off · or neither = flip)
  ozinj ethics-remove --index 2
  ozinj section --name persona --on     (identity · persona · bio · wetware · yoga · substrate)`,

    subs: {

      'set-name':      function (a) { return agentField(a, 'name', 'name') },
      'set-pronouns':  function (a) { return agentField(a, 'pronouns', 'pronouns') },
      'set-backstory': function (a) { return agentField(a, 'backstory', 'backstory') },
      'set-persona':   function (a) { return agentField(a, 'persona', 'persona') },

      'set-yoga':      function (a) { return soulField(a, 'toto_inj_yoga', 'yoga / ethics-substrate') },
      'set-substrate': function (a) { return soulField(a, 'toto_inj_substrate', 'substrate') },
      'set-wetware':   function (a) { return soulField(a, 'toto_inj_wetware', 'wetware') },

      'ethics-add': function (a) {
        var rule = flag(a, 'rule') || a._.join(' ').trim()
        if (!rule) return 'ozinj ethics-add: pass --rule (and optional --note).'
        var e = ethics(); e.push({ rule: rule, note: flag(a, 'note'), on: true }); ethicsSet(e); recompAll()
        return 'ozinj ethics-add — "' + rule + '" added. all heads recompiled.'
      },

      'ethics-toggle': function (a) {
        var e = ethics(), i = +flag(a, 'index')
        if (!e[i]) return 'ozinj ethics-toggle: no rule at index ' + flag(a, 'index') + '.'
        e[i].on = a.flags.on ? true : a.flags.off ? false : !e[i].on
        ethicsSet(e); recompAll()
        return 'ozinj ethics-toggle — "' + e[i].rule + '" → ' + (e[i].on ? 'on' : 'off') + '. recompiled.'
      },

      'ethics-remove': function (a) {
        var e = ethics(), i = +flag(a, 'index')
        if (!e[i]) return 'ozinj ethics-remove: no rule at index ' + flag(a, 'index') + '.'
        var r = e.splice(i, 1)[0]; ethicsSet(e); recompAll()
        return 'ozinj ethics-remove — removed "' + r.rule + '". recompiled.'
      },

      section: function (a) {
        var s = flag(a, 'name') || a._.join(' ').trim()
        if (!s) return 'ozinj section: pass --name (identity · persona · bio · wetware · yoga · substrate).'
        var off = []; try { off = JSON.parse(getLS('toto_inj_off', '[]')) || [] } catch (_) {}
        var isOff = off.indexOf(s) > -1
        var want = a.flags.on ? true : a.flags.off ? false : isOff   // no flag → toggle (if off, turn on)
        if (want) off = off.filter(function (x) { return x !== s }); else if (!isOff) off.push(s)
        setLS('toto_inj_off', JSON.stringify(off)); recompAll()
        return 'ozinj section — "' + s + '" → ' + (want ? 'on' : 'off') + '. recompiled.'
      }

    }
  })

})()
