// oz-app-ui.js — 🖥 THE DESK, both lanes. "any button a human can hit, a bot can use too" (Sum's
//   rule — the whole reason 0z exists). the cards were mapped long ago; this bean maps THE TOP BAR
//   + THE DESK, twice over:
//   · the JSON lane — ui_* tools via makeTool (the tool-loop path every bot already walks)
//   · the CLI lane — the `ozui` program via OZ_APP_CLI.makeApp, NO owner → UNIVERSAL (taught to
//     every bot's chart automatically, web or native)
//   GOFAI rails + bumpers, like the code lane has: card names are LINTED (typo → "did you mean"),
//   edges validated, docking an unopened card AUTO-OPENS it first (rails carry, they don't scold),
//   zoom reports its own clamp. every error is a JUST-IN-TIME TUTORIAL — the correct template +
//   a live example ride back in the message. `ozui tools` / ui_help = the overview: everything a
//   bot can do here, explained, both lanes. deterministic — no model call inside any verb.
//   loads AFTER oz-app-cli.js + tools.js. depends on: cards.js (toggleCard) · workspace.js
//   (OZ_DOCK) · zoom.js (zoomBy) · topbar.js (setSkin) · a11y.js (OZ_KBD).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the GOFAI floor — known names + the linter ... search: "the GOFAI floor — known"
//   the VERBS — one implementation, both lanes ... search: "the VERBS — one"
//   LANE 1: the JSON tools (makeTool — the ....... search: "LANE 1: the JSON tools"
//   LANE 2: the `ozui` CLI program (OZ_APP_CLI ... search: "LANE 2: the `ozui` CLI"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the desk UI verbs (open, dock, zoom,
//    **skin, access, explain, tools). It exports nothing to window; instead it registers tools via
//    **`window.makeTool` (LANE 1, lines 110–139) and a CLI app via `window.OZ_APP_CLI.makeApp`
//    **(LANE 2, lines 142–169). Both lanes call the same verb functions (lines 37–107), so a bot
//    **can use the desk the same way a human does.
//
//    **TOUCH HERE** —
//    - Add a new card type → add to `CARD_BUILDERS` in cards.js, not here
//    - Add a new desk verb (open/dock/zoom/skin/access/explain/tools) → write the `doVerb()`
//    - function (lines 37–107), then register it twice: once in `MT()` call (lines 110–139) and
//    - once in `APP.makeApp` subs (lines 157–168)
//    - Change a verb's behavior → edit its `doVerb()` function (lines 37–107); both lanes will pick
//    - it up automatically
//    - Change the list of valid skins → edit `SKINS` array L28, then update the template strings in
//    - `doTools()` L101 and `APP.makeApp` clue L152
//    - Change the list of valid edges → edit `EDGES` array L27, then update the template string in
//    - `doDock()` L47
//    - Change error messages or tutorials → edit the return strings in each `doVerb()` function
//    - (lines 37–107)
//    - Change accessibility modes (focus/chunky) → edit the pool in `doAccess()` L76 and the logic
//    - in lines 79–82
//
//    **TRAPS** —
//    - `nearest()` L29 is the linter; it must stay deterministic (no model calls). Renaming it
//    - breaks the typo-correction rail in every verb.
//    - `knownCards()` L20 reads from `window.CARD_BUILDERS`, which is built elsewhere; if a card is
//    - not registered there, it will not appear here and `doOpen` will reject it silently.
//    - `openCards()` L21 reads live DOM state (`.card[data-card]`); if the card HTML structure
//    - changes, this breaks without warning.
//    - `cardEl()` L26 is called by `doDock()` L50 to check if a card exists before docking; if the
//    - selector changes, docking will fail silently.
//    - `doOpen()` L37 calls `window.toggleCard()` L42, which must exist before any verb runs; if it
//    - loads late, early calls return "the desk isn't up yet" (line 39).
//    - `doDock()` L45 has a RAIL (line 51): it auto-opens a card if it's not open. This is
//    - load-bearing behavior — removing it will break the "docking an unopened card opens it first"
//    - promise in the header comment (line 8).
//    - `doZoom()` L58 persists zoom to `localStorage.toto_zoom`; changing the key will orphan
//    - existing user zoom settings.
//    - `doAccess()` L75 persists chunky mode to `localStorage.oz_chunky`; changing the key will
//    - orphan existing user settings.
//    - LANE 1 and LANE 2 must call the same verb functions; if you add a verb to one lane but not
//    - the other, the bot will have different capabilities in JSON vs CLI mode.
//    - The `pos()` helper L143 extracts positional args from the CLI parser; it assumes `a._[0]` is
//    - the first positional arg. If the CLI parser changes, this breaks silently.
//
//    **DO NOT** —
//    - Do not add new window dependencies here without checking that they load before this file
//    - (see header comment, line 12: "loads AFTER oz-app-cli.js + tools.js").
//    - Do not move the verb functions (lines 37–107) into separate files; they are the contract
//    - that both lanes depend on.
//    - Do not change card registration or the CARD_BUILDERS map; that lives in cards.js.
//    - Do not change the topbar, theme switching, or keyboard mode logic; those live in topbar.js
//    - and a11y.js respectively.
//    - Do not add model calls or async logic to any verb; they must be deterministic (line 11: "no
//    - model call inside any verb").
//    - Do not change the CLI parser or argument shape; that lives in oz-app-cli.js.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  const MT = window.makeTool
  const APP = window.OZ_APP_CLI

  // ── the GOFAI floor — known names + the linter (typo → nearest real thing) ──────────────────
  const knownCards = () => Object.keys(window.CARD_BUILDERS || {})
  const openCards = () => [...document.querySelectorAll('.card[data-card]')].map(c => ({
    id: c.dataset.card,
    where: c.dataset.edge && c.dataset.edge !== 'center' ? c.dataset.edge + ' wing' : 'the desk',
    open: !c.classList.contains('collapsed'),
  }))
  const cardEl = id => document.querySelector(`.card[data-card="${id}"]`)
  const EDGES = ['left', 'right', 'top', 'bottom', 'desk']
  const SKINS = ['oz', 'unicorn', 'clinical', 'corporate', 'orange']
  function nearest(name, pool) {   // the linter: exact → prefix → OVERSHOOT → contains → nothing
    const n = String(name || '').toLowerCase()
    if (pool.indexOf(n) > -1) return n
    // ⚠ THE OVERSHOOT STEP (2026-08-16). This linter was built for the HUMAN direction — a short typed
    //   prefix reaching a longer real name ("mon" → monaco). A MODEL misses the other way: it invents a
    //   name LONGER than the real one ("bc_shows" → bc_show, "fs_sheet_folder" → fs_sheet), and every
    //   step here failed on that. Both directions now resolve, so the conductor's stray rail can share it.
    return pool.find(p => p.startsWith(n)) || pool.find(p => n.startsWith(p)) || pool.find(p => p.indexOf(n) > -1) || null
  }
  // ⭐ THE ONE LINTER, SHARED (Sum 2026-08-16: "coder and writer have something that just reads all output
  //    being sent to convo, and if it recognizes content in wrong place just js copies and fires, then if
  //    close to but wrong has a did you mean function"). It lived here as a closure; the conductor's
  //    stray-call rail needs the SAME one, so it goes on the window rather than getting re-carved there.
  window.OZ_LINT = { nearest }
  const teachCard = bad => `"${bad}" isn't a card. cards on this build: ${knownCards().join(' · ') || '(none registered yet)'}${openCards().length ? `\nopen right now: ${openCards().map(c => c.id).join(' · ')}` : ''}`

  // ── the VERBS — one implementation, both lanes call it. every unhappy path returns a lesson. ──
  function doOpen(id, on) {
    if (!id) return 'which card? — template: ui_open {"card":"monaco","on":true} · cli: `ozui open monaco`\n' + teachCard('')
    if (!window.toggleCard) return 'the desk isn\'t up yet — try again in a moment.'
    const real = nearest(id, knownCards())
    // ⭐ 1 Sep 2026 — BOTS TOO. The SAY road's own error says "open the bot first ({"tool":"ui_open","card":"tutor"})"
    //    and this function answered '"tutor" isn't a card'. Same knob the topbar tile flips: an id that is
    //    not a card but IS a registered agent goes to toggleAgent (workspace.js), which docks the bar.
    if (!real) {
      const bots = ((window.REG && window.REG.agents) || []).map(x => x.id)   // REG.agents is an ARRAY of records
      const bot = bots.includes(id) ? id : nearest(id, bots)
      if (bot && window.toggleAgent) { window.toggleAgent(bot, on !== false); return `${bot} (a bot) ${on !== false ? 'docked' : 'closed'}.${bot !== id ? ` (you said "${id}" — I read it as ${bot}.)` : ''}` }
      // and SUITES — the topbar's one-click launchers (tutor + learn is 'study'). toggleSuite is topbar.js's own.
      if (window.toggleSuite && window.toggleSuite(id, on !== false)) return `suite ${id} ${on !== false ? 'opened' : 'closed'}.`
      return teachCard(id)
    }
    window.toggleCard(real, on !== false)
    return `${real} ${on !== false ? 'opened' : 'closed'}.${real !== id ? ` (you said "${id}" — I read it as ${real}.)` : ''}`
  }
  function doDock(id, edge) {
    const eg = nearest(String(edge || ''), EDGES)
    if (!eg) return `dock where? edges: left · right · top · bottom · desk (desk = the middle).\ntemplate: ui_dock {"card":"monaco","edge":"left"} · cli: \`ozui dock monaco left\``
    const real = nearest(id, knownCards())
    if (!real) return teachCard(id)
    let el = cardEl(real), railNote = ''
    if (!el) { doOpen(real, true); el = cardEl(real); railNote = `(${real} wasn't open — opened it first.) ` }   // the RAIL: carry, don't scold
    if (!el) return `couldn't raise ${real} — is its builder registered?`
    if (!window.OZ_DOCK) return 'the dock isn\'t up yet.'
    if (eg === 'desk') { window.OZ_DOCK.toDesk(el); return railNote + `${real} is back on the desk (the middle).` }
    window.OZ_DOCK.toWing(el, eg)
    return railNote + `${real} docked ${eg}.`
  }
  function doZoom(dir) {
    if (!window.zoomBy) return 'zoom isn\'t up yet.'
    const d = nearest(String(dir || 'bigger'), ['bigger', 'smaller', 'reset']) || 'bigger'
    if (d === 'reset') { try { localStorage.setItem('toto_zoom', '1') } catch (_) {} window.zoomBy(0); return 'zoom reset — 100%.' }
    const before = parseFloat(localStorage.getItem('toto_zoom') || '1')
    window.zoomBy(d === 'smaller' ? -0.1 : 0.1)
    const after = parseFloat(localStorage.getItem('toto_zoom') || '1')
    if (before === after) return `already at the ${d === 'smaller' ? 'smallest (70%)' : 'biggest (200% — the WCAG bar)'} — the bumper held.`   // the BUMPER speaks
    return `zoom ${d} — now ${Math.round(after * 100)}%.`
  }
  function doSkin(s) {
    const real = nearest(s, SKINS)
    if (!real) return `"${s || ''}" isn't a skin. skins: ${SKINS.join(' · ')}.\ntemplate: ui_skin {"skin":"clinical"} · cli: \`ozui skin clinical\``
    if (!window.setSkin) return 'the skinner isn\'t up yet.'
    window.setSkin(real)
    return `dressed in ${real}.`
  }
  function doAccess(mode, on) {
    const m = nearest(mode, ['focus', 'chunky'])
    if (!m) return 'which mode? focus (keyboard travel: arrows walk, G grabs) · chunky (fatter targets).\ntemplate: ui_access {"mode":"focus","on":true} · cli: `ozui access focus on`'
    const want = on !== false
    if (m === 'focus') { if (!window.OZ_KBD) return 'focus mode isn\'t up yet.'; window.OZ_KBD.set(want); return `focus mode ${want ? 'ON — arrows travel, G grabs and lets go, ? shows the key map' : 'off'}.` }
    document.body.classList.toggle('chunky', want)
    try { localStorage.setItem('oz_chunky', want ? '1' : '0') } catch (_) {}
    return `chunky ${want ? 'ON — fatter buttons and sliders' : 'off'}.`
  }
  function doExplain() {
    const cards = openCards()
    const lines = ['THE SCREEN, plainly:']
    lines.push(`- theme: ${document.documentElement.dataset.skin || 'oz'} · zoom ${Math.round(parseFloat(localStorage.getItem('toto_zoom') || '1') * 100)}%` +
      `${document.body.classList.contains('kbd-mode') ? ' · focus mode ON' : ''}${document.body.classList.contains('chunky') ? ' · chunky targets' : ''}`)
    if (!cards.length) lines.push('- the desk is empty — the topbar tiles (top of the window) open cards.')
    cards.forEach(c => lines.push(`- ${c.id}: ${c.open ? 'open' : 'a collapsed bar'} on ${c.where}`))
    lines.push('- the topbar, left to right: bot tiles · card tiles · ⌖ focus mode · theme · eat-me/drink-me (zoom) · ▮ chunky · ⚙ settings')
    lines.push('(walk the human through ONE step at a time — never the whole list at once.)')
    return lines.join('\n')
  }
  function doTools() {   // the OVERVIEW — everything a bot can do on the desk, explained, both lanes
    return [
      'THE DESK — what you can do here (JSON tool · CLI twin):',
      '  ui_open    · `ozui open <card>`        — open/close a card (the human\'s topbar tile, pressed by you)',
      '  ui_dock    · `ozui dock <card> <edge>` — move a card: left · right · top · bottom · desk (the middle)',
      '  ui_zoom    · `ozui zoom bigger`        — bigger · smaller · reset (the eat-me/drink-me buttons)',
      '  ui_skin    · `ozui skin clinical`      — theme: ' + SKINS.join(' · '),
      '  ui_access  · `ozui access focus on`    — accessibility: focus (keyboard travel) · chunky (fat targets)',
      '  ui_explain · `ozui explain`            — map the screen plainly (use when the human sounds lost)',
      'rails: a typo\'d card name gets matched or listed · docking an unopened card opens it first · zoom clamps and says so.',
      'cards on this build: ' + (knownCards().join(' · ') || '(none yet)'),
    ].join('\n')
  }

  // ── LANE 1: the JSON tools (makeTool — the tool-loop path) ──────────────────────────────────
  if (MT) {
    // ── ui_probe — EYES AND HANDS THROUGH THE PORT (Sum 2026-08-22, "go autonomous and finish up this suite
    //    while I run errands"; this session can press the Mac but cannot see it). A smoke test that needs no
    //    screen: name a card and a paper, optionally CLICK one selector inside that paper's frame, wait, then
    //    READ selectors back (count · first text · computed type · href) plus the sheet beacon's tail.
    //    Selectors only, never code. Port shape: {"tool":"ui_probe","card":"scroll","paper":"myview",
    //    "top":true,"click":".hat","wait":800,"read":["article",".breakdown"]} ──
    // ⭐ MMMM READ-BACKS (26 Aug) — the desk tools answer from the DOM, which is the only surface that
    //    can contradict them. "I opened the card" is a claim; a list of what is actually on the desk is
    //    the check. deskBack is shared because every one of these changes the same one surface.
    //    ⚠ card 'desk' is a DEAD NAME — there is no CARD_BUILDERS.desk. Left alone on purpose: these act
    //    on the whole desk rather than one card, so there is nothing to rename it TO, and inventing a
    //    card to satisfy a scan would be worse than the honest mismatch. Sum's call when he wants it.
    const deskBack = () => { try {
      const open = [...document.querySelectorAll('.card[data-card]')].map(c => c.dataset.card)
      const bars = [...document.querySelectorAll('.agent-bar[data-agent]')].map(b => b.dataset.agent)
      const r = document.documentElement
      return 'on the desk: ' + (open.join(' \u00b7 ') || 'nothing') + ' \u00b7 bars: ' + (bars.join(' \u00b7 ') || 'none') +
        ' \u00b7 skin ' + (r.dataset.skin || '?') + ' \u00b7 zoom ' + (r.style.getPropertyValue('--oz-zoom') || '1')
    } catch (e) { return 'could not read the desk' } }
    MT({ id: 'ui_probe', card: '0z-controls', klass: 'read', readback: deskBack,
      blurb: 'smoke-test a paper through the port: click a selector inside a card\'s frame, wait, read selectors back. Eyes for a session that cannot see the screen.',
      clue: 'probe a card.\ntemplate: { "tool": "ui_probe", "card": "scroll", "paper": "myview", "click": ".hat", "wait": 800, "read": ["article", ".breakdown"] }\npaper "desk" = the whole page (a sheet, the top bar, a card without a frame) · "card" = the card\'s own bar · "bar" = a bot bar (agent: …) · max: chars of text per read (240) · frame: "<selector>" = any iframe on the page (the woodshop\'s .forge-frame).',
      strike: async call => {
        // paper "desk" (alias "top") = the WHOLE page as the root (Sum 2026-08-23, "add it please"): a sheet like ⚙ settings, the top
        // bar, any card drawn straight onto the desk. Those have no frame and no card id, so the card lookup below would refuse them.
        const desk = call.paper === 'desk' || call.paper === 'top'
        // frame: "<selector>" = ANY iframe on the page by selector (Sum 2026-08-23, "yes, we need eyes in there"): the woodshop's
        // .forge-frame, monaco's .mc-preview-frame, a card's own frame by its class. Only the app-card frames carry .app-frame.
        const pick = call.frame ? document.querySelector(String(call.frame)) : null
        if (call.frame && !(pick && pick.tagName === 'IFRAME')) return JSON.stringify({ error: 'no frame matches ' + call.frame })
        const card = (desk || pick) ? null : [...document.querySelectorAll('[data-card="' + String(call.card || 'scroll') + '"]')].find(c => c.querySelector('iframe.app-frame'))
        if (!card && !desk && !pick) return JSON.stringify({ error: 'no open card ' + call.card })
        const out = { card: desk ? 'desk' : pick ? 'frame ' + call.frame : (call.card || 'scroll'), ls: { columns: (() => { try { return localStorage.getItem('paper-columns') } catch (_) { return null } })() } }
        if (card && call.top && call.paper) { const want = String(call.paper).toLowerCase().replace(/[^a-z]/g, ''); const b = [...card.querySelectorAll('.card-paper')].find(x => (x.getAttribute('aria-label') || '').toLowerCase().replace(/[^a-z]/g, '').includes(want) || (x.querySelector('img') && (x.querySelector('img').getAttribute('src') || '').replace(/[^a-z]/g, '').includes(want))); if (b) { b.click(); out.top = b.getAttribute('aria-label') } await new Promise(r => setTimeout(r, call.wait || 800)) }
        const frames = card ? [...card.querySelectorAll('iframe.app-frame')] : []
        // paper "card" = the card's own document (the bar, the cookies strip), not a frame; "bar" = a bot bar; "desk" = the page
        if (desk || call.paper === 'card' || call.paper === 'bar') {
          const doc = document, root = desk ? document : call.paper === 'bar' ? (document.querySelector('.agent-bar[data-agent="' + (call.agent || 'newsie') + '"]') || card) : card
          if (call.click) { const el = root.querySelector(call.click); if (!el) out.click = 'NOT FOUND ' + call.click; else { el.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, button: 0, view: window })); out.click = 'clicked ' + call.click } }
          if (call.click || call.wait) await new Promise(r => setTimeout(r, call.wait || 800))
          out.read = {}; [].concat(call.read || []).forEach(sel => { try { const all = root.querySelectorAll(sel); const el = all[0]; out.read[sel] = { count: all.length, items: call.list ? [...all].slice(-30).map(x => (x.innerText || x.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 90)) : undefined, text: el ? (el.innerText || el.textContent || '').replace(/\s+/g, ' ').trim().slice(0, +call.max || 240) : '', hidden: el ? getComputedStyle(el).display === 'none' : null } } catch (e) { out.read[sel] = { error: e.message } } })
          try { const sb = window.SANDBOX || {}; out.reads = JSON.parse((sb['reads/log.json'] || {}).data || '[]').slice(-3) } catch (_) {}
          return JSON.stringify(out)
        }
        const frame = pick || (call.paper ? frames.find(f => (f.dataset.paper || '') === call.paper) : frames.find(f => !f.hidden))
        out.frames = frames.map(f => ({ paper: f.dataset.paper || '', hidden: !!f.hidden, src: (f.getAttribute('src') || '').slice(0, 50), srcdoc: (f.srcdoc || '').length, port: (f.dataset.port || '').slice(0, 60) }))
        if (!frame) return JSON.stringify(Object.assign(out, { error: 'no frame for ' + call.paper }))
        let doc = null; try { doc = frame.contentDocument } catch (e) { return JSON.stringify(Object.assign(out, { error: 'frame not readable: ' + e.message })) }
        if (!doc || !doc.body) return JSON.stringify(Object.assign(out, { error: 'frame has no document yet' }))
        out.paper = doc.body.dataset.paper || ''; out.title = (doc.title || '').slice(0, 40); out.breakdown = typeof doc.defaultView.BREAKDOWN
        if (call.click) { const el = doc.querySelector(call.click); if (!el) out.click = 'NOT FOUND ' + call.click; else { el.scrollIntoView({ block: 'center' }); el.dispatchEvent(new doc.defaultView.MouseEvent('click', { bubbles: true, cancelable: true, button: 0, view: doc.defaultView })); out.click = 'clicked ' + call.click + ' <' + el.tagName.toLowerCase() + (el.className ? '.' + String(el.className).split(' ')[0] : '') + '>' } }
        if (call.click || call.wait) await new Promise(r => setTimeout(r, call.wait || 800))
        const reads = [].concat(call.read || [])
        out.read = {}
        reads.forEach(sel => { try { const all = doc.querySelectorAll(sel); const el = all[0]; const cs = el ? doc.defaultView.getComputedStyle(el) : null
          out.read[sel] = { count: all.length, items: call.list ? [...all].slice(0, 30).map(x => (x.innerText || x.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 90)) : undefined, text: el ? (el.innerText || el.textContent || '').replace(/\s+/g, ' ').trim().slice(0, +call.max || 240) : '', font: cs ? cs.fontSize + ' ' + cs.fontWeight + ' ' + cs.fontFamily.split(',')[0] + ' ' + cs.textDecorationLine + ' ' + cs.color : '', href: el && el.href ? String(el.href).slice(0, 80) : '', hidden: el ? (cs.display === 'none' || cs.visibility === 'hidden') : null, grid: cs && cs.display === 'grid' ? cs.gridTemplateColumns.slice(0, 60) : undefined, cls: el ? String(el.className).slice(0, 40) : '' } } catch (e) { out.read[sel] = { error: e.message } } })
        if (call.rules) { try { const el = doc.querySelector(call.rules); const hits = []; if (el) [...doc.styleSheets].forEach(ss => { let rs = []; try { rs = [...ss.cssRules] } catch (_) { return } rs.forEach(r => { try { if (r.selectorText && el.matches(r.selectorText) && /font|color|decoration|text-transform/.test(r.style.cssText)) hits.push((ss.href || 'inline').split('/').pop().slice(0, 30) + ' :: ' + r.selectorText.slice(0, 60) + ' { ' + r.style.cssText.slice(0, 120) + ' }') } catch (_) {} }) }); out.rules = hits.slice(-12) } catch (e) { out.rules = 'error ' + e.message } }
        try { const sb = window.SANDBOX || {}; const log = JSON.parse((sb['port/sheet-log.json'] || {}).data || '[]'); out.beacon = log.slice(-8).map(l => new Date(l.at).toLocaleTimeString() + ' ' + l.paper + ' ' + l.what + (l.extra ? ' · ' + l.extra.slice(0, 120) : '')) } catch (_) {}
        return JSON.stringify(out)
      } })
    MT({ id: 'ui_open', card: '0z-controls', klass: 'write', readback: deskBack,
      blurb: 'open or close a card on the desk — the same switch the human\'s topbar tiles flip.',
      clue: 'open/close a card.\ntemplate: { "tool": "ui_open", "card": "monaco", "on": true }',
      strike: call => doOpen(String(call.card || '').trim(), call.on) })
    MT({ id: 'ui_dock', card: '0z-controls', klass: 'write', readback: deskBack,
      blurb: 'move a card to a wing (left · right · top · bottom) or back to the desk — the bot\'s grab key.',
      clue: 'dock a card.\ntemplate: { "tool": "ui_dock", "card": "monaco", "edge": "left" }',
      strike: call => doDock(String(call.card || '').trim(), call.edge) })
    MT({ id: 'ui_zoom', card: '0z-controls', klass: 'write', readback: deskBack,
      blurb: 'grow or shrink the whole UI — "make everything bigger".',
      clue: 'zoom the UI.\ntemplate: { "tool": "ui_zoom", "dir": "bigger" }  (bigger|smaller|reset)',
      strike: call => doZoom(call.dir) })
    // FACTORY RESET (Sum 2026-08-16: "reset my app to factory — keep live keys, reset all convos and chat
    // rooms"). DESTRUCTIVE, so: card:null (never surfaces to a bot's cascade), and the strike refuses
    // unless the call carries confirm:"wipe" — a human at the port, on purpose. KEEPS every localStorage
    // entry that is a key (toto_*_key: the model + search tolls) and NOTHING else; writes a receipt of what
    // it kept and how many it wiped; reloads. Sandbox files on disk are untouched (that is the courier's).
    // 2 Sep 2026 — hil_press: THE RIG'S FINGER. Sum: "did the clickable link show up for hil to just click instead of say yes 3
    //    times? cause if so, that is what it's for." The rig could post a chip and never press it, so every chip read as a stall.
    //    Presses the OLDEST green button waiting on a bot — the same OZ_HIL.resolve the bar button calls. Key-locked at the port
    //    (links.js PORT_KNOBS): no download carries the key, so nothing outside this machine can press a human's button.
    MT({ id: 'hil_press', card: null, klass: 'sharp',
      blurb: 'press the oldest green button waiting on a bot — the rig\'s finger. key-locked; a human at the keyboard just presses the button.',
      clue: 'template: { "tool": "hil_press", "bot": "tutor" }',
      readback: call => { try { const H = window.OZ_HIL; const l = H && H.peek ? H.peek(String((call && call.bot) || '')) : null; return l ? (l.length ? l.length + ' green button(s) still waiting: ' + l.slice(0, 2).join(' · ') : 'nothing waiting on that bot now') : 'OZ_HIL has no peek' } catch (_) { return 'could not read the buttons' } },
      strike: call => {
        const bot = String((call && call.bot) || '').trim(); const H = window.OZ_HIL
        if (!bot) return 'hil_press: pass "bot".'
        if (!H || !H.resolve || !H.peek) return 'hil_press: OZ_HIL is not on this build.'
        const before = H.peek(bot); if (!before.length) return 'hil_press: nothing is waiting on ' + bot + '.'
        H.resolve(bot)
        return 'hil_press: pressed "' + before[0] + '" on ' + bot + (before.length > 1 ? ' (' + (before.length - 1) + ' more waiting)' : '') + '.'
      } })
    MT({ id: 'factory_reset', card: null, klass: 'sharp',
      // ⭐ MMMM (26 Aug) — the sharpest bean in the app, so its read-back counts what SURVIVED rather
      //    than what went. "reset — done" tells you nothing you can act on; a key count tells you
      //    whether your API keys are still there, which is the one thing this reset promises to keep.
      //    card: null is right and stays — it acts on the whole app, not a surface, so it groups as
      //    [meta] and no card-grant can hand it out by accident.
      readback: () => { try {
        const F = window.OZ_FACTORY
        return localStorage.length + ' key(s) left in storage' +
          (F && F.peekKeys ? ' \u00b7 ' + F.peekKeys().length + ' of them API keys (kept by design)' : '')
      } catch (_) { return 'could not re-read storage' } },
      blurb: '(human-only, port-only) wipe every convo, room, dial, and setting — KEEP the API keys — reload.',
      clue: 'factory reset. template: { "tool": "factory_reset", "confirm": "wipe" }',
      strike: call => {
        if (call.confirm !== 'wipe') return 'refused — a factory reset needs confirm:"wipe" in the call.'
        // ⭐ 2 Sep 2026 (Sum: "need a better reset button your end — use this button; just use the small wipe reset").
        //    The gear's ↺ factory reset is OZ_FACTORY.reset() (shell/factory.js): it wipes what keep() does not name and
        //    KEEPS the keys, My Music, the time-travel map, everything authored, the coursework. The loop below kept only
        //    the API keys — it ate his class shelf on every rig run last night. Same road as the button now; the loop
        //    stays as the fallback for a build where the factory did not load. COPY, DON'T IMITATE.
        if (window.OZ_FACTORY && typeof window.OZ_FACTORY.reset === 'function') {
          const n = window.OZ_FACTORY.reset()
          setTimeout(() => location.reload(), 900)
          return 'factory reset (the gear\'s own small wipe) — wiped ' + n + ' entries · kept API keys, My Music, the time-travel map, the authored library and the coursework · reloading.'
        }
        const kept = {}, ks = []
        for (let i = 0; i < localStorage.length; i++) ks.push(localStorage.key(i))
        ks.forEach(k => { if (/^toto_.*_key$/.test(k)) kept[k] = localStorage.getItem(k) })
        const wiped = ks.length - Object.keys(kept).length
        localStorage.clear()
        Object.keys(kept).forEach(k => localStorage.setItem(k, kept[k]))
        // THE PAPERS TOO (Sum 2026-08-22: "factory reset needs to reset my view and the feedline") — ONE sweep, in the factory
        // (shell/factory.js OZ_FACTORY.papers), the same one the settings button runs; it lived only here until 22 Aug eve.
        const gone = (window.OZ_FACTORY && window.OZ_FACTORY.papers) ? window.OZ_FACTORY.papers() : 0
        setTimeout(() => location.reload(), 900)
        return 'factory reset — kept ' + Object.keys(kept).length + ' key(s): ' + Object.keys(kept).join(', ') + ' · wiped ' + wiped + ' entries · ' + gone + ' paper file(s) off disk · reloading.'
      } })
    MT({ id: 'ui_skin', card: '0z-controls', klass: 'write', readback: deskBack,
      blurb: 'change the theme — the dropdown by the zoom buttons.',
      clue: 'set the skin.\ntemplate: { "tool": "ui_skin", "skin": "clinical" }',
      strike: call => doSkin(String(call.skin || '').trim()) })
    MT({ id: 'ui_access', card: '0z-controls', klass: 'write', readback: deskBack,
      blurb: 'accessibility switches — focus mode (keyboard travel) and chunky mode (fatter targets).',
      clue: 'flip an accessibility mode.\ntemplate: { "tool": "ui_access", "mode": "focus", "on": true }',
      strike: call => doAccess(String(call.mode || ''), call.on) })
    MT({ id: 'ui_explain', card: '0z-controls', klass: 'read', readback: deskBack,
      blurb: 'the OT move — read the screen and say what\'s where, plainly. use it when the human is lost.',
      clue: 'map the current screen.\ntemplate: { "tool": "ui_explain" }',
      strike: doExplain })
    MT({ id: 'ui_help', card: '0z-controls', klass: 'read', readback: deskBack,
      blurb: 'the overview — everything you can do on the desk, both lanes, explained.',
      clue: 'list the desk tools.\ntemplate: { "tool": "ui_help" }',
      strike: doTools })
  }

  // ── LANE 2: the `ozui` CLI program (OZ_APP_CLI — universal: no OWNERS entry → taught to ALL bots) ──
  if (APP) {
    const pos = a => (a._ && a._[0]) || ''
    APP.makeApp({
      name: 'ozui',
      blurb: 'the desk — open/dock cards · zoom · theme · accessibility · explain the screen.',
      // the 2x4 cue card — buildSystem hands this to EVERY bot (JIT: templates + live examples inline)
      clue: 'ozui — the DESK. any button the human can hit, you can hit:\n' +
            '  ozui open monaco          # open a card (ozui close monaco puts it away)\n' +
            '  ozui dock monaco left     # left | right | top | bottom | desk (the middle)\n' +
            '  ozui zoom bigger          # bigger | smaller | reset\n' +
            '  ozui skin clinical        # ' + SKINS.join(' | ') + '\n' +
            '  ozui access focus on      # focus | chunky · on | off\n' +
            '  ozui explain              # map the screen plainly — use when the human is lost\n' +
            '  ozui tools                # everything you can do here, explained\n' +
            'typos are caught (a near name is matched or the real list comes back). docking an unopened card opens it first.',
      subs: {
        open:    a => doOpen(pos(a), true),
        close:   a => doOpen(pos(a), false),
        dock:    a => doDock(pos(a), (a._ && a._[1]) || a.flags.edge),
        zoom:    a => doZoom(pos(a)),
        skin:    a => doSkin(pos(a)),
        access:  a => doAccess(pos(a), ((a._ && a._[1]) || 'on') !== 'off'),
        explain: doExplain,
        tools:   doTools,
        onboard: () => window.OZ_ONBOARD ? (window.OZ_ONBOARD.open(), 'the setup door is open — "how do you drive?" (each row is a toggle; done closes it).') : 'onboarding isn\'t up yet.',   // a lost human can just ASK the bot
        read:    doExplain,   // `ozui read` = a READ for the permission tier (klassOf) — the safe default probe
      },
    })
  }
})()
