// oz-verify.js — HILLICINOT FOR CODE (Sum 2026-07-27: "what gemma local does for words, for code").
//
// THE WHOLE IDEA: the word-checker needs a MODEL, because "is this claim verifiable?" is a judgment
// call. A code claim isn't. "I wrote perm-fix.js" is `test -f`. "It parses" is a syntax check. "63
// lines" is a count. So this checker is GOFAI — deterministic, instant, free, and with no false
// positives (it never flags a metaphor, because it only ever looks at things that are literally true
// or literally not). It is strictly cheaper AND stricter than asking a model to review the same claim.
//
// WHY IT EXISTS (the night that earned it, 2026-07-27): a bot said "all three files are on disk,
// ready — apply them to the live app" and TWO OF THE THREE DID NOT EXIST. Twice. It wasn't lying; it
// genuinely could not tell SHOWING a code block from SAVING one. No agent has privileged access to its
// own process — every "I did X" is a hypothesis, not a report. This turns the hypothesis into a fact
// before it reaches the human.
//
// USED BY: the SAY road (shell/links.js) after each tool turn, engineSelfCheck (shell/engine.js)
// as the FREE first pass — a hard disk failure returns without ever spending a model call — and since
// 2026-08-16 the CONDUCTOR's chat road (verifyPass, shell/conductor.js), so an ordinary chat turn is
// audited too; it was not, and that is how a false 'showing it to you now' reached the human.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the CLAIM SCANNER — what did the bot assert ... search: "the CLAIM SCANNER"
//   the CHECK — deterministic, no model, no ....... search: "the CHECK"
//   the REPORT — null when everything checks ...... search: "the REPORT — null when"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for deterministic verification of bot
//    **claims about the filesystem. It exports `window.OZ_VERIFY` with four public methods:
//    **`audit()` (the entry point), `claims()`, `check()`, and `report()`, plus two internal
//    **helpers `_read()` and `_parses()`.
//
//    **TOUCH HERE** —
//    - Add a new claim type (e.g., "contains X string") → add a regex to `claims()` L44–57, then
//    - add a handler in `check()` L61–77.
//    - Change what counts as a syntax error → `parses()` L35–36.
//    - Change the line-count tolerance (currently ±2) → `check()` L69.
//    - Change the error message the bot sees → `report()` L84–91.
//    - Add a new file extension to recognize → `FILE` regex L39.
//    - Change how filenames are normalized (e.g., strip `code/` prefix) → `read()` L26–27.
//
//    **TRAPS** —
//    - `FILE` (L39) is a regex fragment used in three places (L46, L51, L53); renaming or changing
//    - it breaks all three without a syntax error.
//    - `window.SANDBOX` (L25) is the live source of truth — if it stops being a Proxy to disk, all
//    - checks become lies.
//    - The deduplication logic (L56–57) silently drops duplicate claims; if you add a new claim
//    - type, it will be deduplicated by `kind:file` automatically.
//    - `parses()` (L35) catches all exceptions but only returns `false` for `SyntaxError`; this is
//    - intentional (L36 comment) — do not change the exception type without understanding why.
//    - The ±2 tolerance on line counts (L69) was added after a live incident (L49 comment);
//    - removing it will flag legitimate claims.
//
//    **DO NOT** —
//    - Do not add network calls or model inference; this file's value is that it is instant and
//    - deterministic (L5–7).
//    - Do not change the shape of objects returned by `check()` (L62–76); `report()` depends on
//    - `.ok`, `.kind`, `.file`, `.n`, and `.actual` fields.
//    - Do not move the deduplication logic out of `claims()`; it must run before `check()` to avoid
//    - redundant disk reads.
//    - Do not add new claim types without also adding a handler in `check()` — unhandled claims
//    - will silently pass (L75).
//    - Do not change how `read()` accesses `window.SANDBOX`; that is the contract with
//    - `shell/engine.js` and `shell/links.js` (L15).
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  if (window.OZ_VERIFY) return

  // the file's own view of the sandbox. window.SANDBOX is the app's live map (a Proxy that mirrors to
  // disk); a bot's own ozfile/write_file writes land here, so it IS the right truth for its claims.
  function read(name) {
    try {
      var sb = window.SANDBOX || {}
      var k = String(name || '').replace(/^\.\//, '').replace(/^\/+/, '')
      var f = sb[k] || sb[k.replace(/^code\//, '')]   // tolerate the 'code/' habit — check the real file
      return (f && typeof f.data === 'string') ? f.data : null
    } catch (_) { return null }
  }

  // JS syntax check WITHOUT executing a line: the Function constructor parses its body and throws on a
  // syntax error, but we never call the function — so this is a compile check, not a run. (The browser
  // has no `node --check`; this is the honest equivalent.)
  function parses(src) {
    try { new Function(src); return true } catch (e) { return (e instanceof SyntaxError) ? false : true }
  }

  var FILE = '[\\w./-]+\\.(?:js|json|md|html|css|txt|jsonl)'

  // ── the CLAIM SCANNER — what did the bot assert about the filesystem? ────────────────────────────
  // deliberately narrow: only claims with a checkable subject. a vague "done!" is not a claim, it's a
  // mood, and flagging moods is how a checker becomes noise (the word-checker's metaphor problem).
  function claims(text) {
    var t = String(text || ''), out = [], m, re
    re = new RegExp('(?:wrote|written|created|saved|added)\\s+(?:it\\s+)?(?:to\\s+)?[`\'"]?(' + FILE + ')', 'gi')
    while ((m = re.exec(t))) out.push({ kind: 'exists', file: m[1] })
    // tolerate the hedges a bot hides an estimate behind — '412+ lines', '~412 lines', 'about 412
    // lines', '412 or so'. Found live 2026-07-27: a '+' let a 4x-wrong count through unflagged, and
    // the bot then recommended splitting the SMALLEST file because it never counted, only guessed.
    re = new RegExp('(' + FILE + ')[^\\n]{0,40}?(?:~|about |around |roughly )?\\b(\\d{1,6})\\+?\\s*(?:or so\\s*)?lines', 'gi')
    while ((m = re.exec(t))) out.push({ kind: 'lines', file: m[1], n: parseInt(m[2], 10) })
    re = new RegExp('(' + FILE + ')[^\\n]{0,60}?\\b(?:parses|compiles|no syntax errors|syntax[- ]clean)', 'gi')
    while ((m = re.exec(t))) out.push({ kind: 'parses', file: m[1] })
    // ── the SHOW claim (2026-08-16, Sysisphinx) — "DONE Found it — showing it to you now in Binary
    //    Complex", and the card never moved. It is the SAME hypothesis as "I wrote the file": no agent
    //    can see whether its own act landed. Requires BOTH a show verb AND a named file, so a bare
    //    "done!" stays a mood (the narrowness law above). Its own file pattern — the FILE fragment is
    //    load-bearing in three places (see TRAPS) and a photo is not a source file.
    // the verbs a bot ACTUALLY reaches for — "Pulling it up in your preview now" missed the first cut
    // because it wanted "pulled up" and "in THE preview". Live misses, added 2026-08-16.
    if (/\b(?:show(?:ing|n)?|select(?:ed|ing)?|open(?:ed|ing)?|pull(?:ing|ed)?\s+(?:it\s+)?up|bring(?:ing)?\s+(?:it\s+)?up|here it is|on screen|in (?:the|your) (?:preview|card)|in binary complex)\b/i.test(t)) {
      re = new RegExp('([\\w][\\w .()\\-]{0,60}\\.(?:heic|heif|jpe?g|png|gif|webp|tiff?|bmp|svg|pdf|mov|mp4|m4a|wav|zip|csv|xlsx?|docx?|pages|numbers|key))', 'i')
      m = re.exec(t); if (m) out.push({ kind: 'shown', file: m[1].trim() })
    }
    // dedupe (a bot repeats a filename across a paragraph; one check per file+kind is enough)
    var seen = {}
    return out.filter(function (c) { var k = c.kind + ':' + c.file; if (seen[k]) return false; seen[k] = 1; return true })
  }

  // ── the CHECK — deterministic, no model, no network ─────────────────────────────────────────────
  function check(list) {
    return (list || []).map(function (c) {
      // ⚠ BEFORE read(): a 'shown' file lives on the real disk, not in SANDBOX, so the read below would
      //   call every true claim 'not on disk'. Ask the CARD instead — OZ_BC.where() is the ground truth.
      if (c.kind === 'shown') {
        var w = null
        try { w = window.OZ_BC && window.OZ_BC.where && window.OZ_BC.where() } catch (_) {}
        if (!w) return Object.assign({ ok: true, actual: 'no card open to check' }, c)   // closed card is not a lie
        var base = function (x) { return String(x || '').split('/').pop().toLowerCase() }
        var at = base(w.selected)
        return Object.assign({ ok: at === base(c.file), actual: at ? ('the card is showing ' + at) : ('the card is in ' + (w.cwd || '?') + ' with NOTHING selected') }, c)
      }
      var src = read(c.file)
      if (src == null) return Object.assign({ ok: false, actual: 'not on disk' }, c)
      if (c.kind === 'exists') return Object.assign({ ok: true, actual: src.split('\n').length + ' lines' }, c)
      if (c.kind === 'lines') {
        var n = src.split('\n').length
        // ±2 tolerance: a trailing newline or a header line is not a lie, it's counting.
        return Object.assign({ ok: Math.abs(n - c.n) <= 2, actual: n + ' lines' }, c)
      }
      if (c.kind === 'parses') {
        if (!/\.js$/i.test(c.file)) return Object.assign({ ok: true, actual: 'not js — skipped' }, c)
        return Object.assign({ ok: parses(src), actual: parses(src) ? 'parses' : 'SYNTAX ERROR' }, c)
      }
      return Object.assign({ ok: true, actual: '' }, c)
    })
  }

  // ── the REPORT — null when everything checks out (silence is the reward for being right) ─────────
  // when something fails, the shape mirrors HILLICINOT's review so the bot corrects itself the same way.
  function report(results) {
    var bad = (results || []).filter(function (r) { return !r.ok })
    if (!bad.length) return null
    return 'VERIFY (disk check, not an opinion) — ' + bad.length + ' claim(s) do not match the filesystem:\n' +
      bad.map(function (r) {
        if (r.kind === 'exists') return '  · you said you wrote ' + r.file + ' — it is NOT on disk. Showing a code block is not saving it; use ozfile write, then ozfile read it back.'
        if (r.kind === 'lines') return '  · you said ' + r.file + ' is ' + r.n + ' lines — disk says ' + r.actual + '.'
        if (r.kind === 'parses') return '  · you said ' + r.file + ' parses — it has a SYNTAX ERROR.'
        if (r.kind === 'shown') return '  · you said you are showing ' + r.file + ' — ' + r.actual + '. Naming a file in a code block is not showing it; end your reply with the cards block so bc_show actually fires.'
        return '  · ' + r.file + ': ' + r.actual
      }).join('\n') +
      '\nCorrect the record and fix it. Do not restate the claim without a read-back.'
  }

  // one call for the common case: text in → correction string, or null if the bot told the truth.
  function audit(text) { return report(check(claims(text))) }

  window.OZ_VERIFY = { claims: claims, check: check, report: report, audit: audit, _read: read, _parses: parses }
})()
