// toolkits.js — THE TOOLBOX MANIFEST. the card↔tool grouping the bean doesn't carry yet, plus the
// short blurbs the conductor reads at "choose card" and "choose tool". the bean (agents.gen.js) says
// WHICH tools an agent has (flat); this says which CARD each tool acts on, and the one-line pitch the
// model reads to pick. the rich 2x4 (template · edge cases · examples) lives in agents/<id>/<id>-
// toolkit.md and gets PORTED in here (or bundled) next — these blurbs are the toolkit summary lines.
//
// shape: { cards: { id: blurb },  tools: { id: { card, blurb } } }.
// conductor.js reads it: cardsFor(agent) → its reachable cards; toolsFor(card, agent) → that card's
// tools the agent is granted. depends on nothing; loaded before conductor.js.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the cards — each blurb is the "choose a ..... search: "the cards — each blurb"
//   the tools — each { card it acts on, blurb ... search: "the tools — each { card"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the card↔tool mapping and the one-line
//    **pitches that the conductor reads when offering choices to the user. It exports
//    **`window.TOOLKITS` with two keys: `cards` (id → blurb) and `tools` (id → {card, blurb}).
//    **Conductor.js depends on this shape to call `cardsFor(agent)` and `toolsFor(card, agent)`.
//
//    **TOUCH HERE**
//    - Add a new card the user can reach → add entry to `cards` object L14–32
//    - Add a new tool to an existing card → add entry to `tools` object L37–120, set its `card`
//    - field to the target card id (L14–32)
//    - Change a card's pitch (the "choose a card" blurb) → edit the string value in `cards` L14–32
//    - Change a tool's pitch (the "choose a tool" blurb) → edit the `blurb` field in `tools`
//    - L37–120
//    - Route a tool to a different card → change its `card` field in `tools` L37–120
//    - Mark a tool as meta (acts on agents/queue, not a card) → set `card: null` in `tools` L37–120
//    - (see `web_search` L114, `route` L117, `create_queue` L118, `confer` L119)
//
//    **TRAPS**
//    - Tool ids and card ids are load-bearing names: they are referenced by id in agents.gen.js
//    - (which tools an agent has) and in the card-specific bean files (e.g., shell/oz-app-ui.js,
//    - shell/oz-timetravel.js). Renaming either without updating those files silently breaks the
//    - wiring.
//    - The `card: null` convention (L112–119) is how meta-tools hide from the card cascade. Do not
//    - use null for a tool that should surface under a card.
//    - Card ids in the `tools` entries (the `card` field) must match keys in the `cards` object
//    - (L14–32), or the tool will not surface when that card is active.
//    - The shape `{ cards: {...}, tools: {...} }` (L11) is what conductor.js expects. Do not
//    - flatten or nest differently.
//
//    **DO NOT**
//    - Do not implement tool logic here. This file is manifest only; the actual executors live in
//    - shell/tools.js (beans), cards/*/\*-tools.js (atomized card tools), and shell/oz-\*.js
//    - (UI/time/newsie beans). Comments at L69–70, L73, L78 point to where the real code lives.
//    - Do not add user-facing state (user data, settings, history) here. This file is read-only
//    - config. Persistent state lives in the bean files and the card-specific stores.
//    - Do not change the window export name `TOOLKITS` (L11) without updating conductor.js.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


window.TOOLKITS = {

  // ── the cards — each blurb is the "choose a card" pitch: what it is, when to reach for it ──
  cards: {
    monaco:    'the code editor + sandbox — read, splice, and write code files. runs surgery on code that RUNS.',
    webview:   'the preview pane — render HTML/JS live in a sandboxed iframe. "show me / run it".',
    tiptap:    'the rich-text page — prose docs. read, edit by reference, proofread, shift register. words, not code.',
    injection: 'the patient chart — the system-prompt config. read + edit the bot identities (nurse lane).',
    // 2 Sep 2026 17:10 — THE VAULT WAS NEVER ON THIS MAP. Vogel's nav names it, vault-tools.js registers four beans on it,
    //    and cardsFor() filters a bot's nav through THIS map — so 'vault' in a cards fence resolved to nothing, chat.cards came
    //    back empty, and the turn ended as 'just chat' with one engine call and no recorder (the ledger showed it). Three
    //    identical 'I can show you the boxes… (nothing)' replies today. A card with beans and a keeper is a card; list it.
    vault: '🔐 the safe — encrypted boxes that leave this device only on the human’s press; list them, peek at one (names only), stage one to go out',
    clipboard: 'the chart — overview (presentation/perspective/co-morbidity) · complaints (lay words; never a diagnosis) filed by body system — psych · cardio · musculoskeletal · neuro · environmental (= EVERYTHING outside the body: the weather, the president, entropy, any complaint about the universe that fits nowhere else) · prep (the page the patient prints for an appointment). two sides: AI (your notes) + HIL (the human\'s blanks). arrange; never diagnose (nurse lane).',
    food:      'the food plan/log — read a plate from a photo, estimate macros, flip planned→eaten.',
    sleep:     'the sleep profile + nightly data — read-only patterns. never diagnose.',
    exercise:  'the exercise log — record sessions; read-only patterns.',
    learn:     'the course + learner profile — read/edit the profile, seed a course, coach a lesson.',
    email:     'the inbox — list and act on messages. never send without a yes.',
    calendar:  'the calendar — list and act on events. confirm before booking.',
    // ⛔ 'image-gen' PARKED 2026-08-26 → _bench-for-totois/image-gen/. Sum: "park the image gen bean
    //    too, is not in totoII. That was the wall we hit that caused the split. Webview just can't
    //    really handle music image and video well — host a static copy sure, but edit, sort, not so
    //    much." So this is not a bug and not a cull: it is the CATEGORY BOUNDARY that split totoII from
    //    totois in the first place, written down where the next reader will hit it.
    //    ⚠ The traveler keeps painting. tt_scene rides card 'clock' (shell/oz-ttscenes.js) and shares
    //    no code with this — Sum: "time travel is a different path to image gen."
    room:      'the physical room (lights) — coming (spec 10). stubbed: say what you would do.',
    axe:       'the woodshop bench — mill 2x4s and frame agent stacks. lumberjack only.',
    '0z-controls': 'the 0z interface itself — open/close cards, dock to wings, zoom, theme, accessibility modes, and EXPLAIN the screen plainly. any button the human can hit, you can hit.',
    clock:     'the time machine — the clock card. jump it to any date (real weather + real front pages), keep trips as saved manifests, return to now. the traveler\'s ride.',
    // ⏸ spa PARKED 2026-08-26 — I declared a category for it off a code comment, and Sum's own recon
    //    was "we lost the master controls, not sure where they landed… not sure what spa does atm."
    //    Filing tools to a card nobody can describe is how a bean ends up pointing at nothing. It waits
    //    for the dogfood pass (phone + mic + cam). Do not re-add this from a comment; add it from use.
    aioli:     'THE ROOM (AIOLI \u2014 AI Online Interaction) \u2014 where the bots argue. Seat bots, open a room (chat \u00b7 debate \u00b7 interview), read the transcript, and watch the two live numbers on every name: HAND (0 nothing to say \u2192 90+ hand up) and STANCE (0 concur \u2192 100 entrenched). The router is GOFAI \u2014 no model picks who speaks next, comparators do \u2014 and the room ends itself when every hand is down and every stance has reached a pole. Vogel hosts and is always seated.',
    library:   'the red lamp library — the public-domain stacks. find an address, read it at a rung (raw · teaching · TOC · pointers), walk a thread across books, and open the reader on the page you are quoting. Dria\'s front of house.',
    cli:       'the terminal — the CLI lane. run a command, read what came back.',
    games:     'the arcade — the games card. play, or keep the human company while they do.',
    scroll:    'The Port Side View — the paper. read the open web CLEAN (no ads, no wall), raise the radar, and tune the wire. the newsie\'s corner.',
  },

  // ── the tools — each { card it acts on, blurb }. the blurb is the "choose a tool" pitch.
  //    route + create_queue are toto's META tools — they act on AGENTS + the QUEUE, not a card
  //    (card: null), so they never surface under a card; the queue layer runs them. ──
  tools: {
    // 🖥 the DESK — the UI tools (shell/oz-app-ui.js beans). every bot's hands on the interface + the OT move.
    ui_open:    { card: '0z-controls', blurb: 'open or close a card — the human\'s topbar tile, pressed by you.' },
    ui_dock:    { card: '0z-controls', blurb: 'move a card to a wing (left/right/top/bottom) or back to the desk.' },
    ui_zoom:    { card: '0z-controls', blurb: '"make everything bigger/smaller" — the eat-me/drink-me buttons.' },
    ui_skin:    { card: '0z-controls', blurb: 'change the theme (oz · unicorn · clinical · corporate).' },
    ui_access:  { card: '0z-controls', blurb: 'accessibility switches: focus mode (keyboard travel) · chunky (fat targets).' },
    ui_explain: { card: '0z-controls', blurb: 'the OT move — say what\'s on screen plainly, ONE step at a time, when the human is lost.' },

    // ⏳ the TRAVELER — time-machine tools (shell/oz-timetravel.js beans; the clock is the vehicle)
    tt_jump:   { card: 'clock', blurb: 'run the clock to a date — flip-spin, real archive weather, real period front pages; saves the trip manifest.' },
    koans:     { card: 'clock', blurb: 'grow the kōan lane — write new ones in a chosen tradition (zen/nihilist/stoic/absurdist/taoist) and/or hide the built-in ones.' },
    feed_read: { card: 'clock', blurb: 'look inside the human\'s switched-on feeds — pull current headlines + links to share in chat.' },
    alarm_draft: { card: 'clock', blurb: 'draft an alarm for the human to review + save in settings — the bot never arms it.' },
    countdown_draft: { card: 'clock', blurb: 'draft a countdown to a date for the human to review + save.' },
    timer_draft: { card: 'clock', blurb: 'draft an interval timer (work/rest phases) for the human to review + save.' },
    tt_return: { card: 'clock', blurb: 'come home — restore the clock to the present.' },
    tt_trips:  { card: 'clock', blurb: 'the trips folder — list saved adventures (revisiting is nearly free: the manifest is the memory).' },
    tt_scene:  { card: 'clock', blurb: 'paint one frame of the destination onto the clock\'s film strip (4 slots) — picture-book default; the frame echoes back to your eyes.' },
    tt_timemap: { card: 'clock', blurb: 'show the time map — every saved adventure, painted as an illustrated map or listed as the file tree.' },
    tt_trim:   { card: 'clock', blurb: 'trim a trip from the folder (user\'s ask only) — files go to the TRASH, recoverable; the time map redraws.' },

    // 🛳 the NEWSIE — Port Side View tools (shell/oz-newsie.js beans; the paper is the corner)
    psv_read:     { card: 'scroll', blurb: 'read any web link CLEAN — the local readers (the a11y reader, then real Chromium) with the bouncer checking the rules and naming any wall; then give the reader your take.' },
    psv_radar:    { card: 'scroll', blurb: 'raise the weather radar + 15-minute nowcast on the paper.' },
    psv_settings: { card: 'scroll', blurb: 'turn the paper to its SETTINGS so the human can tune the wire · comics · scripture · stars — you open + explain, they flip the switches.' },
    psv_toggle:   { card: 'scroll', blurb: 'FLIP a source/section on the paper from chat (feed · lane · comic · scripture · weather · forecast · plug); it reloads live. low-risk — only changes what the paper shows.' },
    psv_search:   { card: 'scroll', blurb: 'run a search ON THE PAPER — named sources (Wikipedia · Wikinews · arXiv) or the open web (surf:true); results fill the paper, each opens clean in the Portal.' },
    psv_readout:  { card: 'scroll', blurb: 'hand the user\'s request to a stronger bot (tutor · writer · pa · toto · coder) behind the user\'s GREEN press — you route, never delegate alone; nothing (esp. the ported page) leaves without the press.' },
    psv_make:     { card: 'scroll', blurb: 'MAKE NEW pieces for a lane (koans · quotes · jokes · lessons · spirituality · facts · poems · recipes) via the lane generator; they grow the library + show on the paper. write-class — auto at pancakes, green button below.' },
    lamp_find:      { card: 'library', blurb: 'search the stacks for ADDRESSES — threads (an idea in two or more books), pointers, or the raw words. every hit names the rung it was found on. low-risk: looking only.' },
    lamp_read:      { card: 'library', blurb: 'read one address at one altitude: 0 raw verbatim · 1 the teaching · 2 the work’s TOC · 3 the pointers. quote from rung 0, never from memory.' },
    lamp_thread:    { card: 'library', blurb: 'walk an idea across books — a thread is a keyword the stacks carry in two or more works, computed from the filing, never invented.' },
    lamp_checkout:  { card: 'library', blurb: "check the open work onto the reader's own card — the same stamp their \u2713 button writes. ask first; the card is theirs." },
    lamp_collection:{ card: 'library', blurb: 'read their card \u2014 what they have checked out, how often, when. to suggest from, never to recite back.' },
    lamp_open:      { card: 'library', blurb: 'open the reader on the card at an address so the human sees the passage you are quoting. low-risk: it turns a page.' },
    feedline_note:  { card: 'scroll', blurb: 'write ONE line into your Feedline bible from chat (more of this, less of that, a source to try); you read it on the next cut. low-risk — a text file the reader edits or resets in the gear.' },
    psv_read_aloud: { card: 'scroll', blurb: 'READ A STORY OUT LOUD through the house voice — the clean text of a link, or words you are handed; press again to stop. no tokens spent.' },

    // coder — monaco + webview: read_file · apply_edits · write_file · preview are now BEANS (shell/tools.js,
    // via makeTool — full clue + strike there). only the executor-less ones stay here as manifest stubs.
    unload:             { card: 'monaco',   blurb: 'clear the chat context — the tow truck. the sandbox survives; warn first.' },

    // writer — tiptap (prose, by reference). read_doc/edit_doc → atomized to doc_read/doc_append/doc_replace (cards/tiptap/tiptap-tools.js).

    // pa — email · calendar · room · docs. email_act/cal_list/cal_act/make_doc → atomized (email_*/cal_*/doc_* beans).
    read_room:          { card: 'room',     blurb: 'read/control the lights — STUBBED (hardware pending). say what you would do.' },

    // nurse — injection (the chart)
    read_chart:         { card: 'injection', blurb: 'read the injection config — substrate · ethics · identity · persona · history policy.' },
    edit_notes:         { card: 'injection', blurb: 'add / toggle / edit the chart notes loaded into every agent.' },
    update_patient_bio: { card: 'injection', blurb: 'update the human-bio fields (name · pronouns · who).' },
    read_prep:          { card: 'clipboard', blurb: 'read the session-prep sheet — scope · say-first · topics · snapshot · if-they-ask · bring.' },
    prep_header:        { card: 'clipboard', blurb: 'set the prep header — discipline · date · who you\'re seeing.' },
    prep_say_first:     { card: 'clipboard', blurb: 'set the ONE main point to land first.' },
    prep_add_scope:     { card: 'clipboard', blurb: 'add a scope item — an agenda line + ~time.' },
    prep_add_topic:     { card: 'clipboard', blurb: 'add a topic heading.' },
    prep_add_point:     { card: 'clipboard', blurb: 'add a bullet under a topic.' },
    prep_add_flag:      { card: 'clipboard', blurb: 'add a ⚠ flag under a topic — the thing to get on the record.' },
    prep_add_snapshot:  { card: 'clipboard', blurb: 'add a snapshot row — domain · rating · evidence.' },
    prep_add_qa:        { card: 'clipboard', blurb: 'add an "if they ask" Q&A.' },
    prep_add_bring:     { card: 'clipboard', blurb: 'add a "bring" item / a pointer to a fuller doc.' },
    prep_save:          { card: 'clipboard', blurb: 'save the sheet → the nurse\'s notes on the injection chart (a session).' },

    // wellness — food · exercise (read-only on sleep)
    read_food_doc:      { card: 'food',     blurb: 'read the food plan/log. estimate a plate from a photo (flagged AS a guess).' },
    edit_food_doc:      { card: 'food',     blurb: 'flip entries planned→eaten · update the pantry/log.' },
    read_profiles:      { card: 'food',     blurb: 'read the sleep + food + exercise profiles so you do not re-ask.' },

    // tutor — learn (the course). read_learn_profile/edit_learn_profile → atomized to learn_read_profile/learn_set_* (cards/learn/learn-tools.js).
    seed_course:        { card: 'learn',    blurb: 'enter a prompt for the learn card to build a course from. you seed; learn builds.' },
    explain_and_coach:  { card: 'learn',    blurb: 'walk the learner through their course at their level. link-first, honest about look-ups.' },

    // lumberjack — axe (the woodshop)
    room_list:          { card: 'aioli',    blurb: 'list the chat rooms — name, type, line count, who is seated. looking only.' },
    room_read:          { card: 'aioli',    blurb: "read a room's transcript. reading never enters your own memory — say a thing back out loud and THAT is what you keep." },
    room_open:          { card: 'aioli',    blurb: 'open the room card on a named room, creating it if new. seats nobody, starts nothing.' },
    add_note:           { card: 'injection',   blurb: 'keep ONE thing past this conversation — a note your next self wakes up knowing. rides every future call, so it has to earn the room.' },
    add_hil_note:       { card: 'injection',   blurb: "the nurse's second pen — one fact about the HUMAN, in the shared tray every bot reads." },
    // ⚠⚠ 31 Aug 2026 — forge_agent AND fire_agent ARE DEAD. Sum: "forge agent is dead, waits for tois."
    //   NOT a gap to fix and NOT a bug to chase. injection.js:582 says "THE WHOLE JOB LIVES ON THE AXE
    //   CARD NOW" — so parking the woodshop parked the bot-hiring road with it, deliberately.
    //   ⭐ THE ENTRIES STAY, ON HIS WORD — recon, no strip. They are INERT today: toolLines() only
    //   prints a blurb to a bot HOLDING that card, and no bot holds 'axe' any more (the grant was
    //   stripped from coder the same evening). They would lie again the moment 'axe' is re-granted —
    //   and it never will be, because a parked card comes back under a NEW NAME. Same for the three
    //   tiptap phantoms above. agents/build.js reports all eight on every run; that is correct and
    //   the report should keep saying so until tois answers for them.

    // EVERY agent — the live web. a SERVER tool (the provider searches + cites), not a conductor strike, so card:null
    // (never surfaces in the QUE/RUN cascade). wired on anthropic + openrouter; the Tavily fallback (Layer 2) covers the rest.
    web_search:         { card: null,       blurb: 'search the live web — you decide when; cited results stream into your answer. Two roads: NATIVE (anthropic · openrouter · gemini · xai — your provider searches inside your own turn) and the ```search FENCE (every provider — "engine | query", results return to you next beat). The fence engines are your BACKUPS when native did not find it, or when you want a specific kind of source: wikipedia = settled facts, definitions, precedents, history (neutral, citeable) · duckduckgo = quick answers on well-known topics (instant, shallow) · tavily = the open web with a synthesized answer, when keyed. Not getting what you asked for? Try the next desk.' },

    // toto — the META toolkit (acts on AGENTS + the QUEUE, owns no card)
    route:              { card: null,       blurb: 'hand the turn to the specialist whose lane fits. surfaces their card.' },
    create_queue:       { card: null,       blurb: 'lay a multi-step ask out as an ordered to-do tree. any step may queue again.' },
    confer:             { card: null,       blurb: 'consult another agent and get the reply back to YOU (chat specs before a build). bot-to-bot, not a hand-off.' },
  },
}
