// fupm.js — the FUPM card. "f#$% you, pay me." the ask, made literal.
// donate (→ square, real bank) · subscribe (→ square, $1.99/mo) · book me ($1/min —
// yoga, or just sit) · then the big one: HIRE ME NOW (→ linkedin).
// registers as a card; opens from the blank-desk tagline. dismiss = back to the bone.
// build phase: lean. folio header at ship.

// ── the links — real where they exist, flagged where they don't ──────

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the links — real where they exist, flagged ... search: "the links — real where"
//   build the card ............................... search: "build the card"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the FUPM card's four payment/hire links
//    **and their UI states. It exports `window.CARD_BUILDERS.fupm`, which `cards.js` calls to
//    **render the card into the DOM.
//
//    **TOUCH HERE**
//    - Change a link URL → edit `FUPM` object, lines 8–25 (donate L11, subscribe L14, book L20,
//    - hire L24)
//    - Disable or enable the book button → set `FUPM.book` to empty string (disabled, shows "soon")
//    - or a URL (enabled, becomes a link), line 20
//    - Change button text or copy → edit the template strings in `buildFupm()`, lines 44–75
//    - Change the card's CSS class or data attribute → lines 30–31
//
//    **TRAPS**
//    - Line 20: `FUPM.book` is checked for truthiness at line 34. If you set it to a non-empty
//    - string, the button becomes a live link; if empty, it shows the "soon" state. No other state
//    - exists.
//    - Line 73: the back button calls `window.toggleCard('fupm', false)` by name. The string
//    - `'fupm'` must match `card.dataset.card` (line 31) and the key in `window.CARD_BUILDERS`
//    - (line 81).
//    - Lines 52, 57, 68: three `<a>` tags interpolate `FUPM.donate`, `FUPM.subscribe`, and
//    - `FUPM.hire` directly into `innerHTML`. If any of these are undefined or malformed, the links
//    - will be broken or unsafe.
//    - Line 62: `${bookBtn}` is interpolated into the template. The `bookBtn` variable (lines
//    - 34–42) must be defined before the template runs, or the card will not render.
//
//    **DO NOT**
//    - Rename `buildFupm`, `FUPM`, or `bookBtn` without updating all references (line 81 depends on
//    - the function name; lines 34–42 and 44–75 depend on the variable names).
//    - Move the `window.CARD_BUILDERS` registration (lines 80–81) to another file; it must stay
//    - here.
//    - Add state or persistence to this file; it is stateless. If you need to track booking
//    - availability or link status, that belongs in a data layer or config file.
//    - Change the card's HTML structure without coordinating with the CSS file that styles `.fupm`,
//    - `.fupm-go`, `.fupm-soon`, etc. (those selectors are not defined here).
//
//
//
//    ---
//
// END IC SHIP PASS

const FUPM = {
  // donate → square, straight to Sum's real bank. the square page owns the amount
  // ($5 + an auto $1 tip; give more if you like). the card just says "donate".
  donate: 'https://square.link/u/7pZIFtbs',

  // subscribe → square. $1.99/month. real + working today.
  subscribe: 'https://square.link/u/yREg71er',

  // book me → $1/minute consulting (yoga, or just sit — a good listener).
  //
  // ✅ LIVE 2026-08-30 — Sum pasted the url. The button is a real door now.
  // ⚠️ CORRECTION to the note below, which is kept because most of it still stands: it said
  //    "Sum makes it in Square (Appointments or a store product)". He made it in GOOGLE CALENDAR
  //    appointment scheduling instead, which is why the host is calendar.app.google and not
  //    square.link like its two neighbours. Verified 200 before wiring; it redirects to
  //    calendar.google.com/calendar/appointments/schedules/…
  //    STILL TRUE: the tier plan in the old note (90-min intro, then 20 or 50 min for members
  //    after the first session) is a booking-page setting, not a code one, and lives over there.
  //    STILL TRUE: empty → the button rests as "soon". That path is untouched and still works.
  //
  // (was) ⚠️ NO booking product exists yet. Sum makes it in Square (Appointments or a
  //    store product) + pastes the url here. tiers: 90-min intro, then 20 or 50
  //    min for members after the first session. empty → the button rests as "soon".
  book: 'https://calendar.app.google/T7FUoYap6CLY34o16',

  // hire me → linkedin. James Davis (the legal name; Sum Bhodi is the handle + brand).
  // confirmed by Sum, 2026-06-14.
  hire: 'https://www.linkedin.com/in/james-davis-013764416/',
}

// ── build the card ───────────────────────────────────────────────────
function buildFupm() {
  const card = document.createElement('section')
  card.className = 'card fupm'
  card.dataset.card = 'fupm'

  // book me — wired if the link exists, resting "(soon)" if it doesn't. honest either way.
  const bookBtn = FUPM.book
    ? `<a class="fupm-go" href="${FUPM.book}" target="_blank" rel="noopener">
         <span class="fupm-way-name">book me</span>
         <span class="fupm-way-sub">$1 a minute. we can do yoga, or just sit there.<br>i'm a really good listener.</span>
       </a>`
    : `<div class="fupm-go fupm-soon" title="Sum's still wiring this one up">
         <span class="fupm-way-name">book me</span>
         <span class="fupm-way-sub">$1 a minute — yoga, or just sit there.<br>i'm a really good listener. <em>(booking soon)</em></span>
       </div>`

  card.innerHTML = `
    <div class="card-head"><span class="card-icon">🦴</span><span class="card-title">FUPM</span>
      <!-- ✕ (Sum 2026-08-30): "back to the bone is the only way to close — that is a little too
           aggressive, we can give more clues, x marks the spot, most users know x out." The ← back
           button at the foot STAYS (it says where you land, which the ✕ cannot). Same call as the
           gear sheet's own ✕: close always lets you out, and it lives where a stranger looks first. -->
      <button class="fupm-x" title="close" aria-label="close FUPM" onclick="window.toggleCard('fupm', false)">✕</button></div>
    <div class="fupm-body">

      <p class="fupm-open">if you pay me…</p>

      <div class="fupm-ways">

        <a class="fupm-go" href="${FUPM.donate}" target="_blank" rel="noopener">
          <span class="fupm-way-name">tip</span>
          <span class="fupm-way-sub">straight to my real bank</span>
        </a>

        <a class="fupm-go" href="${FUPM.subscribe}" target="_blank" rel="noopener">
          <span class="fupm-way-name">subscribe</span>
          <span class="fupm-way-sub">support oz · $1.99/mo · ends world hunger</span>
        </a>

        ${bookBtn}

      </div>

      <p class="fupm-drumroll">…and if you really mean it —</p>

      <a class="fupm-hire" href="${FUPM.hire}" target="_blank" rel="noopener">
        <span class="fupm-hire-big">HIRE ME NOW</span>
        <span class="fupm-hire-fine">while you can still afford me</span>
      </a>

      <button class="fupm-back" onclick="window.toggleCard('fupm', false)">← back to the bone</button>

    </div>`

  return card
}

window.CARD_BUILDERS = window.CARD_BUILDERS || {}   // register with cards.js
window.CARD_BUILDERS.fupm = buildFupm
