// oz-app-cli.js — THE APP-CLI LANE (the router). the card-data jenga, re-cut as CLI.
//
// FOR HUMANS
//   the rust bolt (run_cli) runs REAL shell on REAL files in ~/totoII/sandbox.
//   but some of oz's data isn't a file — it's app state in the browser (the nurse's
//   prep sheet, the food doc, the chart notes). a real subprocess can't touch that.
//   so those beans get a SECOND lane: a tiny CLI that runs right here, in the page.
//   the bot writes `ozprep add-topic "Sleep"` and this router hands it to the right
//   program — same as the old JSON tool-call, in the one language every model speaks.
//   this file is JUST the router. each program (ozprep · ozfood · ozchart) is its own
//   sealed file that registers here with makeApp — one concern per file, the IC way.
//
// FOR AI
//   1. an app command starts with a registered program name (`ozprep` · `ozfood` · `ozchart`).
//   2. has(line) is true for those; OZ_CLI routes them here, never to the bolt.
//   3. run(line) → argv (quotes honored) → dispatch the subcommand → return text.
//   4. never touch the filesystem here. this lane is app state only (localStorage).
//   5. one program per data surface. one subcommand per old bean. keep it flat.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   argv — split a command line into tokens, .... search: "argv — split a command"
//   parse — the tokens AFTER the subcommand → ... search: "parse — the tokens"
//   the REGISTRY — one program per data ......... search: "the REGISTRY — one"
//   heredoc — the app lane's UNAMBIGUOUS ........ search: "heredoc — the app"
//   wire into OZ_CLI (cli-harness.js) — app ..... search: "wire into OZ_CLI"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — the app-side CLI router that intercepts commands matching registered program names
//    **and dispatches them to subcommand handlers. Exports `window.OZ_APP_CLI` with methods
//    **`makeApp`, `run`, `has`, `klassOf`, `clues`, `argv`, `parse`, `flag`, `names` (L143–146).
//    **Programs register themselves via `makeApp(spec)` (L63–66) and are stored in the `progs`
//    **registry (L61).
//
//    **TOUCH HERE**
//    - Add a new app program → call `makeApp({ name, blurb, clue, subs: {...} })` from that
//    - program's file; it will auto-register in `progs` (L61, L63–66).
//    - Change how a subcommand reads its arguments → edit the subcommand's handler function
//    - (registered in `prog.subs`); use `a._` for positionals (L38), `flag(a, key)` for named flags
//    - (L54–57), `rest(a)` for trailing args (not defined here; check the calling program).
//    - Add permission scoping for a new program → the bot's OWN record now: "cli": ["ozmail"] in
//      agents/<bot>/<bot>.json. (Was an `OWNERS` map here; see owners() and its note.) bots listed
//    - there will be taught only that program's cue card.
//    - Change the heredoc marker syntax (e.g., `<<'EOF'`) → edit the regex at L82 and the
//    - replacement at L85.
//    - Change how read vs. write commands are classified → edit `klassOf()` (L114–116); currently
//    - checks if second token is `'read'`.
//
//    **TRAPS**
//    - `progs` (L61) is the live registry. Renaming it breaks `makeApp` (L63), `has` (L69), `clues`
//    - (L133), and `wireOzCli` (L154–162).
//    - The `OWNERS` map (L123–130) keys must match program names in `progs` exactly, or permission
//    - scoping silently fails.
//    - `splitHeredoc` (L77–89) must find the marker on the *first line* after the header (L87); if
//    - a file's first content line matches a marker name, the body will be truncated.
//    - `wireOzCli` (L153–165) wraps `OZ_CLI.classify` and `OZ_CLI.run` *once* (guarded by
//    - `CLI._appWired` at L156). If `OZ_CLI` doesn't exist yet, `setInterval` polls every 300ms
//    - (L167–169); removing this breaks late-loading scenarios.
//    - The heredoc body is pushed to `a._` *and* `a.flags.content` (L102) so subcommands can read
//    - it either way; changing this breaks programs that expect both channels.
//
//    **DO NOT**
//    - Rename `window.OZ_APP_CLI` or its exported methods; `cli-harness.js` and other callers
//    - depend on these names.
//    - Add filesystem I/O here; this lane is app state only (L17). File commands belong in a
//    - separate program that uses `window.SANDBOX` (L128).
//    - Move `wireOzCli` logic into a separate file; it must run in the same scope as `OZ_CLI` to
//    - wrap its methods.
//    - Change the shape of the object returned by `run()` at L161 without updating callers in
//    - `cli-harness.js`.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  'use strict'

  // ── argv — split a command line into tokens, honoring "double" and 'single' quotes ──
  // `add-point --topic "Sleep hygiene" "term — the detail"` → 4 clean tokens, quotes gone.

  function argv(line) {
    var out = [], re = /"([^"]*)"|'([^']*)'|(\S+)/g, m
    while ((m = re.exec(String(line || '')))) {
      out.push(m[1] != null ? m[1] : m[2] != null ? m[2] : m[3])
    }
    return out
  }

  // ── parse — the tokens AFTER the subcommand → positionals + `--flags` ──
  // `--flag value` sets flag=value; a bare `--flag` (or one before another --flag) is boolean true.

  function parse(tokens) {
    var pos = [], flags = {}
    for (var i = 0; i < tokens.length; i++) {
      var t = tokens[i]
      if (t.slice(0, 2) === '--') {
        var k = t.slice(2)
        var next = tokens[i + 1]
        flags[k] = (next != null && next.slice(0, 2) !== '--') ? tokens[++i] : true
      } else {
        pos.push(t)
      }
    }
    return { _: pos, flags: flags }
  }

  // flag(a, key) → the string value, or '' — the guard every subcommand leans on (a bare --flag is not a value).

  function flag(a, key) {
    var v = a.flags[key]
    return (v != null && v !== true) ? String(v) : ''
  }

  // ── the REGISTRY — one program per data surface. makeApp stamps it in (the bean, app-side) ──

  var progs = {}   // name → { name, blurb, clue, subs: { sub: run(args) } }

  function makeApp(spec) {
    progs[spec.name] = spec
    return spec.name
  }

  function has(line) {
    return !!progs[argv(line)[0]]
  }

  // ── heredoc — the app lane's UNAMBIGUOUS multi-line content path (mirrors the disk shell's cat<<'EOF'). ──
  // `ozfile write page.html <<'EOF' … EOF` → { header: 'ozfile write page.html', body: '…the file…' }. the body
  // is fenced by a marker, so a whole file (quotes, newlines and all) rides in with nothing to escape. run()
  // strips it off the header, then hands the body to the program as BOTH a trailing positional and --content,
  // so whichever channel a subcommand reads (rest(a) or flag(a,'content')), it gets the payload whole.
  function splitHeredoc(line) {
    var s = String(line == null ? '' : line)
    var nl = s.indexOf('\n')
    if (nl === -1) return { header: s, body: null }
    var first = s.slice(0, nl)
    var m = first.match(/<<-?\s*(?:'([A-Za-z_]\w*)'|"([A-Za-z_]\w*)"|([A-Za-z_]\w*))/)
    if (!m) return { header: s, body: null }
    var marker = m[1] || m[2] || m[3]
    var header = first.replace(/<<-?\s*(?:'[A-Za-z_]\w*'|"[A-Za-z_]\w*"|[A-Za-z_]\w*)\s*/, '').replace(/\s+$/, '')
    var rest = s.slice(nl + 1).split('\n'), body = []
    for (var i = 0; i < rest.length; i++) { if (rest[i].trim() === marker) break; body.push(rest[i]) }
    return { header: header, body: body.join('\n') }
  }

  function help(prog) {
    return prog.name + ' — ' + (prog.blurb || '') + '\n  subcommands: ' + Object.keys(prog.subs).join(' · ')
  }

  function run(line) {
    var hd = splitHeredoc(line)                      // pull a `<<'EOF' … EOF` body off the header, if any
    var t = argv(hd.header), prog = progs[t[0]]
    if (!prog) return t[0] + ': unknown oz command'
    var sub = t[1], entry = prog.subs[sub]
    if (!sub || sub === 'help' || !entry) return help(prog)
    var a = parse(t.slice(2))
    if (hd.body != null) { a.flags.content = hd.body; a._.push(hd.body) }   // the heredoc body → content, both channels
    try {
      var out = entry(a)
      return String(out == null ? '' : out)
    } catch (e) {
      return prog.name + ' ' + sub + ': ' + ((e && e.message) || e)
    }
  }

  // is this app command a READ (auto-run, zero blast radius) or a WRITE? the second token tells us —
  // `ozprep read` is a read; everything else mutates. OZ_CLI uses this to pick the permission tier.

  function klassOf(line) {
    return argv(line)[1] === 'read' ? 'read' : 'write'
  }

  // every registered program's cue card, joined — the 2x4 engine.buildSystem hands an enabled bot.

  // each program's OWNER bot(s) — a bot is TAUGHT only its own programs' cue cards, so prompts stay lean at any
  // program count. capability is NOT scoped: ANY bot can still RUN any oz* command (the OZ_CLI wrap routes them
  // all) — this scopes the teaching, not the reach. a program with no entry here is universal (taught to all).
  // ── ⭐ THE WHOLE MAP MOVED TO THE BOTS, 26 Aug (second pass, same day) ────────────────────────
  //  The eight lines that used to sit here are kept below, verbatim, because they are the clearest
  //  statement of the intent this file has:
  //        ozprep: ['nurse'], ozchart: ['nurse'], ozinj: ['nurse'],
  //        ozfood: ['wellness'], ozwell: ['wellness'],
  //        ozmail: ['pa'], ozcal: ['pa'],
  //        ozdoc: ['writer'], ozlearn: ['tutor'],
  //  Nine facts about five bots, filed where none of those bots can see them. The morning's pass
  //  had already moved ozfile and ozforge onto records as caps and left these behind — half a fix
  //  reads as a whole one to the next person, which is worse than not starting.
  //  ⚠ WHY A FUNCTION AND NOT A CONST. The old object was evaluated ONCE at load. The two withCap
  //  calls inside it therefore snapshotted whatever the registry knew at that instant — and if this
  //  file loads before agents.gen.js, that is nothing, permanently, silently. registry.js says this
  //  in its own margin ("caps() reads window.AGENT_DATA LAZILY, at call time"). Now so does this.
  //  Each bot names its own lanes: "cli": ["ozmail", "ozcal"]. Caps still answer for the two that
  //  are genuinely capabilities rather than desks — a lane you own because you ARE the file bot is
  //  not the same as a lane you own because you keep the chart.
  var CAP_LANES = { ozfile: 'file', ozforge: 'forge' }
  function owners() {
    var m = {}, D = window.AGENT_DATA || {}, k
    for (k in CAP_LANES) m[k] = (window.REG && window.REG.withCap) ? window.REG.withCap(CAP_LANES[k]) : []
    m.ozimage = []
    Object.keys(D).forEach(function (id) {
      ((D[id] && D[id].cli) || []).forEach(function (lane) { (m[lane] = m[lane] || []).push(id) })
    })
    return m
  }
  // ── the two corrections this map already carried, kept — they are the reason the shape changed ──
  //  ⭐ MOVED TO THE BOT'S RECORD, 26 Aug (caps: ["file"] / ["forge"]). WAS: ozfile: ['coder'],
  //     ozforge: ['lumberjack']. A CLI lane's owner is a capability, and it belongs on the bot — which
  //     also means a lane can never again point at a bot that has left (ozimage pointed at jem, then at
  //     asterix, and both were gone within the hour).
  //     NO FALLBACK NAMING A BOT: if REG is missing the answer is an empty list, not a guess. A default
  //     that names a bot is the same leak in a smaller coat, and it would hide REG being absent behind
  //     something plausible — which is the failure mode that is hardest to ever find.
  // ── CORRECTION, attached (26 Aug, twice in one afternoon) ───────────────────────────────────
  //  ozimage read ['jem'] for months. When jem left 0zweb I repointed it to asterix — and an hour later
  //  asterix was parked too ("bleep is asterix not two bots"). Chasing a lane's owner from one leaving
  //  bot to the next is the wrong move; the honest answer is that the lane has NO owner.
  //  image_generate is granted to nobody now (Sum: "strip image generate, never worked, never tested,
  //  waits for tois"), so an empty list is the truth: the ozimage lane is dark until totois. That empty
  //  list is now the one literal left in owners() — a lane declared and deliberately unowned.
  //  ⚠ NOT the traveler. tt_scene is a different road entirely — card 'clock', shell/oz-ttscenes.js.

  function clues(botId) {
    var keys = Object.keys(progs)
    var OWNERS = owners()   // resolved per call — see the note above; a const here snapshots an empty registry
    if (botId) keys = keys.filter(function (n) { var o = OWNERS[n]; return !o || o.indexOf(botId) > -1 })
    if (botId && window.WS_BURNED) keys = keys.filter(function (n) { return !window.WS_BURNED.is(botId, n) })   // the burn reaches the CLI reference too (Sum 2026-08-23: "json has this, did cli get it?" — it had the kill switch in the harness, not the menu)
    var body = keys.map(function (n) { return progs[n].clue }).filter(Boolean).join('\n\n')
    if (!body) return ''
    // the emit instruction lives HERE, not in the shell cue — so the app commands work even in the web build
    // (no CLI): they run IN THE APP, not the sandboxed shell. always-safe, web or native.
    return 'To run an app command, write it in a ```sh code block — it runs IN THE APP (not the shell), so it ' +
      'works even in the web build with no CLI. these are your app-DATA commands:\n\n' + body
  }

  window.OZ_APP_CLI = {
    makeApp: makeApp, run: run, has: has, klassOf: klassOf, clues: clues,
    argv: argv, parse: parse, flag: flag, names: function () { return Object.keys(progs) }
  }

  // ── wire into OZ_CLI (cli-harness.js) — app commands route HERE, tier-gated, never to the rust bolt ──
  // ADDITIVE: wrap classify + run once, after OZ_CLI exists. an app command classifies read|write (so OZ_PERM
  // gates writes at the cli tier); run returns a rec shaped like run_cli's, minus the metal (app:true, no shell).
  // this makes the WHOLE harness app-aware — the cli card, the coder loop, any future caller — in one place.

  function wireOzCli() {
    var CLI = window.OZ_CLI
    if (!CLI) return false
    if (CLI._appWired) return true
    var origClassify = CLI.classify, origRun = CLI.run
    CLI.classify = function (cmd) { return has(cmd) ? klassOf(cmd) : origClassify.call(CLI, cmd) }
    CLI.run = function (cmd, opts) {
      if (!has(cmd)) return origRun.call(CLI, cmd, opts)
      return Promise.resolve({ cmd: cmd, klass: klassOf(cmd), ran: true, exit: 0, stdout: run(cmd), stderr: '', blocked: false, refusedByHuman: false, app: true })
    }
    CLI._appWired = true
    return true
  }

  if (!wireOzCli() && typeof setInterval !== 'undefined') {
    var wait = setInterval(function () { if (wireOzCli()) clearInterval(wait) }, 300)
  }

})()
