// oz-lanegen.js — THE LANE GENERATOR (Sum 2026-07-18: "custom generation sections for
//   our hand rolls… borrows rider's llm and image gen lanes")
// FOR HUMANS: every hand-rolled lane can grow YOUR version — a doctrine/filter box
//   steers the voice, author packs and philosophy paths steer the canon, 👍👎 votes
//   steer the taste, and the traveler's own personality colors it all. kōans and
//   manifest can paint their own art if the gemini wallet is loaded.
// FOR AI:
//   1. window.LANE_GEN(laneId, n, withArt, note) → { made, painted }. shared by the
//      settings page (✨) and the cadence ticker below — one engine, no drift.
//   2. stores: clock-filter-<lane> (doctrine) · clock-path-koans · clock-authors-devil ·
//      clock-interests · clock-fb (taste ±1) · clock-gen-<lane> (the pool, strings or
//      {t, img: pocket dataURL}) · clock-seeds-<lane> (default titles, mirrored).
//   3. the RIDER: engineRaw agentId 'timetravel', slim:false — the persona IS the filter.
//   4. cadence: clock-cad-<lane> = 'hour'|'day'|'week' + clock-cadn-<lane> (count);
//      LANE_GEN_TICK checks every 15 min from the shell (always alive).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the PSV hand-rolls (Sum 2026-07-22: ........... search: "the PSV hand-rolls (Sum"
//   the back pages — the paper's satirical ........ search: "the back pages — the"
//   THE PSV LONG PASSAGES (Sum 2026-07-22: ........ search: "THE PSV LONG PASSAGES"
//   MOVE_VIDS — the video search, shared .......... search: "MOVE_VIDS — the video"
//   LEARN_WIRE — real lessons & textbooks on ...... search: "LEARN_WIRE — real"
//   TT_PAPERS — the morning edition, typeset by ... search: "TT_PAPERS — the morning"
//   the CADENCE — "make N per hour / day / ........ search: "the CADENCE — "make N"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for content generation across all "lanes"
//    **(wisdom categories). It exports five window functions: `LANE_GEN(laneId, n, withArt, note,
//    **opts)` (the main generator, called by settings and cadence), `MOVE_VIDS(q, force)` (video
//    **search for exercise), `LEARN_WIRE(q, force)` (textbook/lesson search), `LEARN_ON()` and
//    **`LEARN_SOURCES` (lesson source toggles), and `TT_PAPERS(dateStr, future)` (headline
//    **generation for time travel). It owns the VOICE registry (line 24), ART registry (line 53),
//    **and all localStorage keys prefixed `clock-` and `oz-`.
//
//    **TOUCH HERE** —
//    - Add a new lane type → add entry to `VOICE` object (line 24) with its generation rules,
//    - optionally add to `ART` (line 53) if it paints
//    - Change a lane's voice/rules → edit the corresponding `VOICE[laneId]` function (lines 24–51)
//    - Change art style for a lane → edit `ART[voiceId]` (lines 53–63)
//    - Add a filter/doctrine box → it reads from `clock-filter-<laneId>` (line 91), no code change
//    - needed
//    - Change how many items cache before painting stops → edit the `25` on line 281
//    - Change the cadence check interval → edit the `15 * 60000` on line 512
//    - Change how long MOVE_VIDS or LEARN_WIRE cache → edit the `6 * 3600000` on lines 304 and 376
//    - Add a textbook source → add to `LEARN_SRC` array (line 361) and implement its fetch in
//    - `LEARN_WIRE` (lines 369–465)
//    - Change the "never again" deduplication logic → edit lines 100, 150, 201, 238, or the `never`
//    - key reads (lines 100, 238)
//
//    **TRAPS** —
//    - `laneId` vs `voiceId` (line 85): `laneId` is the pool identity (storage key), `voiceId` is
//    - the voice/rules identity. They can differ when `opts.voice` is set. Renaming either breaks
//    - storage.
//    - localStorage keys are user data: `clock-gen-<laneId>`, `clock-seeds-<laneId>`,
//    - `clock-never-<laneId>`, `clock-filter-<laneId>`, `clock-path-koans`, `clock-authors-*`,
//    - `clock-spirit-on`, `clock-fb`, `clock-cad-<lane>`, `clock-cadn-<lane>`,
//    - `clock-cadlast-<lane>`, `clock-art-<lane>`, `clock-learn-on`, `clock-learn-items`,
//    - `clock-move-vids`, `oz-videos-off`. Changing a key name orphans existing user data.
//    - The `key()` function (line 22) truncates to 60 chars and is used for deduplication across
//    - all lanes. Changing its logic silently breaks the "never again" wall.
//    - `SPIRIT_SUBS` (line 94) is hardcoded; if you add a spirituality sub-lane, add it here or it
//    - won't seed.
//    - The `rostered` path (line 110) filters the pool to only lines matching the toggled authors.
//    - If you change the author matching logic (lines 245–270), the prompt on line 213 and the JS
//    - filter must stay in sync or authors slip through.
//    - Line 281: the pool is checked for existing images with `p && p.img`; if you change the entry
//    - shape from `string | {t, img}`, this guard breaks silently.
//    - The three regex fences (`/```gen\s*\n([\s\S]*?)```/`) on lines 140, 192, and 235 must match
//    - the prompt's output format exactly (lines 130, 182, 224). If you change the prompt, change
//    - the regex.
//    - `engineRaw` with `agentId: 'timetravel'` (lines 134, 186, 229, 485) is the rider persona; it
//    - is the filter. Changing the agentId changes whose voice speaks.
//    - Line 236: `maxLen` differs for authors (520) vs others (320) because "deep cuts breathe";
//    - changing this silently changes the register.
//    - The cadence ticker (lines 498–512) runs every 15 min and checks per-lane timestamps. If you
//    - add a new lane, it auto-runs if `clock-cad-<lane>` is set; no registration needed.
//
//    **DO NOT** —
//    - Do not rename `VOICE`, `ART`, `OPENSTAX`, `LIBRE`, `LEARN_SRC`, `SPIRIT_SUBS`, or `PER` —
//    - they are referenced by name in prompts and elsewhere.
//    - Do not change the `pocket()` function (line 65) — it is the image compression step; if you
//    - need different compression, edit the `maxW` and `q` parameters on line 285, not the function
//    - itself.
//    - Do not add new lanes to the cadence ticker (line 499) — it auto-discovers them from `VOICE`
//    - keys.
//    - Do not move the `J`, `S`, `G` helpers (lines 18–21) — they are used throughout and their
//    - names are short by design.
//    - Do not edit the `lev()` Levenshtein distance function (lines 246–252) unless you understand
//    - the author fuzzy-match wall; it is load-bearing for the roster.
//    - Do not add new storage keys without documenting them in the OWNS section and checking for
//    - orphaning.
//    - Do not change the `slim: false` or `nopace: true` flags on engine calls — they are tuned for
//    - this use.
//    - Do not add new sources to LEARN_WIRE without adding them to `LEARN_SRC` (line 361) and the
//    - `learnOn()` toggle (line 363).
//    - Do not move the `setTimeout(tick, 90000)` (line 511) — it is the boot delay; moving it
//    - changes when cadence first runs.
//    - Do not edit the video marker strip on line 239 (`[\u25B6\uFE0F\s]+`) unless you know what
//    - markers the video lanes use.
//    - Do not add validation or filtering to the output of `LANE_GEN` — the caller (settings page,
//    - cadence) owns the UI feedback.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const S = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }
  const G = k => { try { return localStorage.getItem(k) || '' } catch (_) { return '' } }
  const key = s => String((s && s.t) || s || '').slice(0, 60)

  const VOICE = {
    koans:       p => `a kōan in the ${p || 'zen buddhist'} tradition — a tiny scene, exchange, or question that stops the mind. no moral stated, ever. if the tradition is nihilist/stoic/absurdist/taoist, let ITS masters speak in ITS terms.`,
    meditations: () => 'gentle plain instruction, one breath of an idea, warm and unhurried. NEVER therapese — no "journey", no "trauma", no "healing space".',
    manifest:    () => 'manifestation lines. follow the doctrine below EXACTLY if one is given; otherwise classic manifestation/affirmation cliché, played straight.',
    bible:       () => 'REAL public-domain scripture (KJV wording), quoted exactly, with book chapter:verse — chosen to match the books/genres below. never invent a verse.',
    devil:       () => 'REAL entries from Ambrose Bierce\'s The Devil\'s Dictionary (public domain), quoted exactly in the form: WORD, n. definition. we are mapping the WHOLE book — exclude every entry already listed. if no unquoted entries remain in your memory, output an EMPTY gen block.',
    exercise:    () => 'one-line movement prompts, level first (seated · gentle · hard), doable in a minute or ten. NEVER include a link and NEVER a play/video marker — those belong to real videos only; your lines are done right here.',
    recipes:     () => 'simple, real, home-cook recipes to the preference below — pantry-real, nothing fussy, honest food (the short form is a one-line meal idea; the long form is the full recipe: ingredients + steps).',
    // the theology shelf — REAL text only, cited; the well can run dry and says so
    torah:       () => 'REAL Torah verses (public-domain KJV wording of Genesis–Deuteronomy), quoted exactly with book chapter:verse. never invent. none left new → EMPTY gen block.',
    quran:       () => 'REAL Qur\'an verses in standard public-domain English translation, quoted with surah:ayah. never invent or paraphrase loosely. none left new → EMPTY gen block.',
    vedas:       () => 'REAL lines from the Vedas and Upanishads in public-domain translation, cited by text and verse. never invent. none left new → EMPTY gen block.',
    gita:        () => 'REAL Bhagavad Gita verses in public-domain translation, cited chapter.verse. never invent. none left new → EMPTY gen block.',
    thelema:     () => 'REAL lines from Crowley\'s Book of the Law (public domain) or The Satanic Temple\'s published Seven Tenets, quoted exactly, attributed. never invent. none left new → EMPTY gen block.',
    freethought: () => 'REAL, verifiable quotations from famous atheist/agnostic/humanist thinkers (Ingersoll, Russell, Sagan, Epicurus, Huxley, Twain…), exact wording, attributed "— <Author>". mark shaky attributions "attributed to". none left new → EMPTY gen block.',
    authors:     () => 'REAL quotations or PASSAGES (up to 3–4 sentences) from the listed authors\' published works — exact wording, attributed "— <Author>, <Work>" when known. PREFER THE DEEP CUTS: skip each author\'s most-famous poster lines and go further into the works — passages with real theological or philosophical weight are especially welcome. NEVER invent, paraphrase, or trim into misquotation; a line you cannot place with confidence, drop SILENTLY — no commentary inside the fence, ever. exclude everything already listed. nothing new left → EMPTY gen block.',
    spirituality: () => 'REAL lines from the toggled traditions below, quoted exactly in public-domain wording and cited (book chapter:verse · surah:ayah · text and verse · attributed). every line tradition-true; never invent scripture. nothing new left → EMPTY gen block.',
    learn:       () => 'one-line LESSONS — each line TEACHES one real thing: a concept, a definition, a why, complete in one sentence a curious twelve-year-old could follow. real, standard-textbook-checkable facts ONLY — never invent, never guess a number. teach the fact itself, never recommend a website or service, and NEVER mention Khan Academy. the doctrine box below is the subject to teach; no doctrine → a spread of delightful fundamentals across fields.',
    jokes:       () => 'ORIGINAL short jokes in the paper\'s dry, wry newsroom voice — one or two lines, a clean setup and a real turn. observational, a little absurd, aware of tech and modern life. NEVER mean, never a slur, never punching down; poke the powerful and the silly, not the vulnerable. no knock-knocks, no groaner puns unless the pun genuinely lands. PG-13 at most. the doctrine box below, if given, is the topic to riff on.',
    // ── the PSV hand-rolls (Sum 2026-07-22: "studios for all the great stuff not coming from api") ──
    wei:         () => 'the WEI — the wellness industry, refunded. plain, deflationary, warm, a little funny. eat a vegetable, take a walk, sleep, drink some water; the rest is commentary. one real, kind, common-sense truth about living well, developed honestly — NEVER therapese, never a supplement, never a nine-step routine, never a moral tacked on. the joke is always on the industry, never on the reader.',
    advice:      () => 'plain, grounded, useful advice with a wry human warmth — the kind a good friend gives, not a life coach. solve the animal first (water, food, sleep, a walk); the two-minute rule; do the small thing now. one real idea, developed, honest about the trade-off. never glib, never a platitude, never "manifest your best life".',
    facts:       () => 'ONE genuinely true, verifiable, delightful thing — real science, history, nature, or the mind, standard-reference-checkable. the octopus-has-three-hearts register: a hook, then the real why. NEVER invent or guess a number; a fact you cannot stand behind, drop silently. no moral, no "isn\'t nature amazing" — just the true thing, told well.',
    poetry:      () => 'REAL public-domain poems (poet died 70+ years ago — Dickinson, Whitman, Frost, Williams, Hopkins, Blake, Keats, Rossetti, Dunbar, Hughes where public-domain…), quoted EXACTLY, titled "<Poem> — <Poet>", line breaks preserved. never invent a poem, never misquote, never trim mid-line into nonsense. prefer whole short poems or complete stanzas. nothing new left → EMPTY gen block.',
    // ── the back pages — the paper's satirical furniture (Sum 2026-07-22: "studios for … obits, adds, classified") ──
    obits:       () => 'satirical OBITUARIES for the dead ideas of the internet age — the ad-wall, the cancel button hidden three menus deep, the free trial that renewed at midnight, the mouse jiggler, the engagement algorithm, DRM. dry, affectionate, newsroom-wry; mourn the CONCEPT, never a real person. the TITLE line is "<Name> · B. <year> · D. <year>"; the passage is a 1–2 sentence eulogy that ends on a small twist ("survived by…", "in lieu of flowers, …").',
    ads:         () => 'HOUSE ADVERTISEMENTS for the paper itself and its quiet virtues — no ad-tech, no tracking, reading to the end, owning your media, turning things off, porting past a paywall you already pay for. a punchy TITLE headline + one warm line of body. never sell a real product; the joke is always on SaaS and enshittification, never on the reader.',
    classifieds: () => 'tiny satirical CLASSIFIED ads in the old newsprint style — FOR SALE / WANTED / LOST / FOUND. ONE line each, dry and a little absurd, about attention, focus, quiet, and the modern web ("FOR SALE: your attention, lightly used, still warm"). never mean, never a real person, never a real product.',
  }
  const ART = {   // which lanes paint, and how
    koans: p => ({
      'zen buddhist': 'A sumi-e ink painting on warm cream paper — minimal confident strokes, generous empty space, a small red seal stamp',
      nihilist:  'A stark charcoal drawing — vast empty black, one small pale subject, unsentimental',
      stoic:     'A weathered roman marble relief sketch, sepia and stone grey, dignified',
      absurdist: 'A quiet surrealist ink-and-wash — one impossible thing rendered calmly',
      taoist:    'A flowing brush landscape, mist and water, the subject small within it',
    })[p || 'zen buddhist'] || 'A sumi-e ink painting on warm cream paper — minimal confident strokes, generous empty space',
    manifest: () => 'A soft dreamy pastel watercolor, golden hour light, gentle and hopeful',
    jokes: () => 'A single-panel newspaper cartoon in clean black ink on cream newsprint, a light wash of one muted color, gentle caricature — the scene of the joke rendered simply, with NO caption or lettering drawn anywhere in the image',
  }

  const pocket = (dataUrl, maxW, q) => new Promise((res, rej) => {
    const img = new Image()
    img.onload = () => {
      const s = Math.min(1, maxW / img.width)
      const c = document.createElement('canvas')
      c.width = Math.round(img.width * s); c.height = Math.round(img.height * s)
      c.getContext('2d').drawImage(img, 0, 0, c.width, c.height)
      res(c.toDataURL('image/jpeg', q))
    }
    img.onerror = () => rej(new Error('no decode'))
    img.src = dataUrl
  })

  // opts (Sum 2026-07-22): { voice } picks the VOICE + content-rules while laneId keeps the
  //   STORAGE pool separate — so the PSV's long author/spirit studio writes clock-gen-authors-long
  //   without colliding with the clock's short clock-gen-authors. { long } = the PSV shape: a teaser
  //   TITLE + a real passage (returns {t,b}, same seat as learn), never the clock's one-liners.
  window.LANE_GEN = async function (laneId, n, withArt, note, opts) {
    note = note || (() => {})
    opts = opts || {}
    const voiceId = opts.voice || laneId          // which VOICE + rules; laneId stays the pool identity
    const long = !!opts.long                       // PSV: title + passage, like learn
    if (!window.engineRaw) throw new Error('the engine is not loaded')
    n = Math.min(20, Math.max(1, +n || 5))
    const path = voiceId === 'koans' ? (G('clock-path-koans') || 'zen buddhist') : ''
    const authors = voiceId === 'authors' ? J('clock-authors', '["Twain"]') : []
    const filter = G('clock-filter-' + laneId)
    const interests = G('clock-interests')
    // spirituality is a SHELF of sub-lanes — its seed memory is the union of theirs
    const SPIRIT_SUBS = ['bible', 'torah', 'quran', 'vedas', 'gita', 'thelema', 'freethought', 'manifest']
    const spiritOn = voiceId === 'spirituality' ? (J('clock-spirit-on', JSON.stringify(SPIRIT_SUBS))) : []
    const seeds = voiceId === 'spirituality'
      ? spiritOn.flatMap(sub => J('clock-seeds-' + sub, '[]'))
      : J('clock-seeds-' + laneId, '[]')
    const pool = J('clock-gen-' + laneId, '[]')
    const never = J('clock-never-' + laneId, '[]')   // removed once = never again (Sum: "I de-duped and it came right back")
    // taste — votes whose keys live in this lane's pools
    const fb = J('clock-fb', '{}')
    const mine = new Set(seeds.map(key).concat(pool.map(key)))
    const liked = [], disliked = []
    Object.keys(fb).forEach(k => { if (mine.has(k)) (fb[k] > 0 ? liked : disliked).push(k) })

    // a ROSTERED gen sees only its own authors' prior lines — the mixed pool was
    // out-shouting the roster (Sum: "still no fydor"). the register comes from the
    // authors themselves; the exclude list is just what's already used.
    const rostered = voiceId === 'authors' && authors.length
    const excludes = (rostered
      ? pool.map(key).filter(k => authors.some(a => k.toLowerCase().includes(a.toLowerCase())))
      : seeds.concat(pool.map(key))).concat(never).slice(0, 16)

    // THE LESSON WRITES ARTICLES (Sum 2026-07-20: "have the lesson make-new make FULL
    // articles, with a click bait title too") — learn is the one lane whose make-new
    // returns {t, b} (a clickbait title + a real essay), not one-liners. same seat as
    // the three hand-rolled lessons: title on the bar, the article opens on the card.
    if (voiceId === 'learn') {
      const brief = [
        `write ${n} short teaching ARTICLES for the "learn" card of a clock.`,
        filter ? 'the SUBJECT to teach (obey this):\n' + filter : 'no subject given — pick delightful, deep ideas across fields: a strange true thing from science, history, philosophy, math, or the mind.',
        interests ? 'lean toward the reader\'s interests when it fits: ' + interests : '',
        'each article has TWO parts:',
        '  · a CLICKBAIT title — a curiosity gap, playful, a little outrageous, the kind you have to click. but never a lie: the essay under it delivers, honestly.',
        '  · a real ESSAY — 4 to 7 short paragraphs, ~250–450 words, teaching ONE idea deeply. real names, real experiments, real dates; NEVER invent a fact or a number. no moral tacked on. warm, plain, a little wry. the register of a great science journalist, not a textbook.',
        'no markdown headings inside the body, no bullet lists, no links, and never recommend a website or service (never mention Khan Academy). plain paragraphs separated by ONE blank line.',
        liked.length ? 'titles the reader LIKED — more in this spirit:\n' + liked.slice(0, 5).map(s => '- ' + s).join('\n') : '',
        excludes.length ? 'titles already written — pick DIFFERENT ideas, no repeats:\n' + excludes.map(s => '- ' + s).join('\n') : '',
        'output ONLY this fenced block — each article a TITLE line starting "# ", then its paragraphs, articles split by a line of exactly "===":\n```gen\n# <clickbait title>\n<paragraph>\n\n<paragraph>\n===\n# <next title>\n<paragraphs>\n```',
      ].filter(Boolean).join('\n')
      let full = ''
      const res = await window.engineRaw({
        agentId: 'timetravel', slim: false, nopace: true,
        extra: brief,
        messages: [{ role: 'user', content: filter ? `${n} articles on: ${filter}` : `${n} fresh, deep articles, please` }],
        onChunk: c => { full += c },
      })
      if (res && res.error) throw new Error(res.error)
      const m = /```gen\s*\n([\s\S]*?)```/.exec(full)
      const chunks = (m ? m[1] : '').split(/\n=+\s*\n/).map(s => s.trim()).filter(Boolean)
      let made = 0
      for (const chunk of chunks) {
        if (made >= n) break
        const nl = chunk.indexOf('\n')
        const t = chunk.slice(0, nl < 0 ? undefined : nl).replace(/^#+\s*/, '').trim().slice(0, 90)
        const b = (nl < 0 ? '' : chunk.slice(nl + 1)).trim()
        if (!t || b.length < 120) continue                          // a title with no body is a menu, not a lesson
        if (/khan academy/i.test(t + b)) continue                   // the khan wall holds for articles too
        if (never.includes(key(t))) continue
        if (pool.some(p => key(p) === key(t)) || seeds.some(s => key(s) === key(t))) continue
        pool.push({ t, b }); made++
        note(`${made}/${n} written`)
      }
      if (!made) throw new Error('no new articles came back — try again')
      S('clock-gen-learn', pool)
      return { made, painted: 0 }
    }

    // ── THE PSV LONG PASSAGES (Sum 2026-07-22: "studio in psv make long, except koan") — the
    //    Port Side View shows a teaser headline; the whole passage opens in the card, the same
    //    seat as learn's articles. long lanes return {t,b}: a title + a real 2–5 sentence passage.
    //    quotes/scripture stay EXACT (never invent); wei/advice/facts develop one true idea. ──
    if (long) {
      const brief = [
        rostered
          ? `write ${n} NEW passages — REAL excerpts by ${authors.join(' and ')} ONLY. no other author, no matter what earlier lines look like.`
          : voiceId === 'spirituality'
            ? `write ${n} NEW passages — real cited excerpts from these traditions only: ${spiritOn.join(' · ')}.`
            : `write ${n} NEW entries for the "${laneId}" section of a broadsheet — each a short teaser plus a real passage.`,
        'the voice: ' + (VOICE[voiceId] ? VOICE[voiceId](path) : ''),
        filter ? 'the doctrine/filter — this OVERRIDES everything above about content:\n' + filter : '',
        interests ? 'the reader\'s interests, when relevant: ' + interests : '',
        liked.length ? 'passages the reader LIKED — more in this spirit:\n' + liked.slice(0, 5).map(s => '- ' + s).join('\n') : '',
        disliked.length ? 'passages the reader DISLIKED — never like these:\n' + disliked.slice(0, 5).map(s => '- ' + s).join('\n') : '',
        excludes.length ? 'already used — pick DIFFERENT ones, no repeats:\n' + excludes.map(s => '- ' + s).join('\n') : '',
        'each entry has TWO parts:',
        '  · a TITLE line — a short teaser or the SOURCE (the work + author for a quote/passage; the title + poet for a poem; a 4–9 word hook for advice/wei/facts). never clickbait-lie.',
        voiceId === 'recipes'
          ? '  · a RECIPE — the DISH NAME is the title; the body is a short INGREDIENT list (one per line, real quantities) then a few NUMBERED steps, home-cook simple. NO life story, no preamble — just the recipe (this is the honest opposite of a noisy recipe site).'
          : '  · a PASSAGE — 2 to 5 sentences (a poem: the whole short poem or a complete stanza), ~40–130 words, complete and true. EXACT wording for quotes/scripture/poems, cited; for advice/wei/facts, one real idea developed, warm and plain, no moral tacked on.',
        'no markdown headings, no bullet lists, no links. output ONLY this fenced block — a TITLE line, then the passage, entries split by a line of exactly "===":\n```gen\n<title>\n<passage>\n===\n<next title>\n<passage>\n```',
      ].filter(Boolean).join('\n')
      let full = ''
      const res = await window.engineRaw({
        agentId: 'timetravel', slim: false, nopace: true,
        extra: brief,
        messages: [{ role: 'user', content: rostered ? `${n} real passages by ${authors.join(' and ')} — only them, please` : `${n} ${laneId} passages, please` }],
        onChunk: c => { full += c },
      })
      if (res && res.error) throw new Error(res.error)
      const mm = /```gen\s*\n([\s\S]*?)```/.exec(full)
      const chunks = (mm ? mm[1] : '').split(/\n=+\s*\n/).map(s => s.trim()).filter(Boolean)
      let made = 0
      for (const chunk of chunks) {
        if (made >= n) break
        const nl = chunk.indexOf('\n')
        const t = chunk.slice(0, nl < 0 ? undefined : nl).replace(/^#+\s*/, '').trim().slice(0, 90)
        const b = (nl < 0 ? '' : chunk.slice(nl + 1)).trim()
        if (!t || b.length < 40) continue                       // a title with no passage is a menu, not a read
        if (never.includes(key(t))) continue
        if (pool.some(p => key(p) === key(t)) || seeds.some(s => key(s) === key(t))) continue
        pool.push({ t, b }); made++
        note(`${made}/${n} written`)
      }
      if (!made) throw new Error('no new passages came back — try again')
      S('clock-gen-' + laneId, pool)
      return { made, painted: 0 }
    }

    const brief = [
      rostered
        ? `write ${n} NEW entries — REAL lines by ${authors.join(' and ')} ONLY. no other author may appear, no matter what any earlier lines look like.`
        : voiceId === 'spirituality'
          ? `write ${n} NEW entries — real cited lines from these traditions only: ${spiritOn.join(' · ')}.`
          : `write ${n} NEW one-line entries for the "${laneId}" lane of a clock's wisdom bar.`,
      'the voice: ' + VOICE[voiceId](path),
      filter ? 'the doctrine/filter — this OVERRIDES everything above about content:\n' + filter : '',
      interests ? 'the user\'s interests, when relevant: ' + interests : '',
      liked.length ? 'lines the user LIKED — more like these:\n' + liked.slice(0, 5).map(s => '- ' + s).join('\n') : '',
      disliked.length ? 'lines the user DISLIKED — never like these:\n' + disliked.slice(0, 5).map(s => '- ' + s).join('\n') : '',
      excludes.length ? (rostered ? 'already used — EXCLUDE these:\n' : 'existing lines — match register, never repeat or near-repeat:\n') + excludes.map(s => '- ' + s).join('\n') : '',
      'each entry: ONE line, under 160 characters, complete in itself.',
      'output ONLY a fenced block, one entry per line, nothing else:\n```gen\n<entry>\n```',
    ].filter(Boolean).join('\n')

    let full = ''
    const res = await window.engineRaw({
      agentId: 'timetravel', slim: false, nopace: true,   // the rider's persona is the filter
      extra: brief,
      messages: [{ role: 'user', content: rostered ? `${n} real lines by ${authors.join(' and ')} — only them, please` : `${n} new ${laneId} lines, please` }],
      onChunk: c => { full += c },
    })
    if (res && res.error) throw new Error(res.error)
    const m = /```gen\s*\n([\s\S]*?)```/.exec(full)
    const maxLen = voiceId === 'authors' ? 520 : 320   // deep cuts breathe; quips stay quips
    let lines = (m ? m[1] : '').split('\n').map(s => s.trim().replace(/^[-•]\s*/, '')).filter(s => s.length > 8 && s.length < maxLen)
    lines = lines.filter(l => !never.includes(key(l)))   // removed once = never again
    if (voiceId === 'exercise') lines = lines.map(l => l.replace(/^[\u25B6\uFE0F\s]+/, ''))   // a gen line may not wear the video marker
    if (voiceId === 'learn') lines = lines.filter(l => !/khan/i.test(l))   // the khan wall (Sum: "khan snuck back in") \u2014 the prompt asks, the JS enforces
    // the ROSTER WALL (Sum 2026-07-19: "it ignores the author toggle") — the prompt asks,
    // the JS enforces. FUZZY: Dostoevsky/Dostoyevsky are both real transliterations — the
    // man Sum can't spell, the wall must still match. a pass CANONICALIZES the signature
    // to the chip's spelling, so the bar filter and the groups agree forever after.
    if (voiceId === 'authors' && authors.length) {
      const lev = (a, b) => {
        const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)])
        for (let j = 0; j <= b.length; j++) d[0][j] = j
        for (let i = 1; i <= a.length; i++) for (let j = 1; j <= b.length; j++)
          d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1))
        return d[a.length][b.length]
      }
      const chipFor = sig => {
        const s = sig.trim().toLowerCase()
        return authors.find(a => {
          const al = a.toLowerCase()
          if (s.includes(al) || al.includes(s)) return true
          return lev(s.split(/\s+/).pop(), al.split(/\s+/).pop()) <= 2
        }) || null
      }
      const before = lines.length
      lines = lines.map(l => {
        const mm = /—\s*(?:after\s+)?(?:attributed to\s+)?([^—,]+?)((?:,[^—]*)?)\s*$/.exec(l)
        if (!mm) return null
        const chip = chipFor(mm[1])
        if (!chip) return null
        return l.slice(0, mm.index) + '— ' + chip + mm[2]   // the canonical spelling wins
      }).filter(Boolean)
      if (!lines.length && before) throw new Error('nothing came back by the toggled authors — try again')
    }
    // the DRY WELL (Sum: "a subtle no new quotes found") — an empty fence is the honest answer
    if (!lines.length && m) throw new Error('no new ones found — the well looks dry')
    if (!lines.length) throw new Error('nothing usable came back — try again')

    const paint = withArt && ART[voiceId] && window.ozNano && window.ozNano.ready()
    let made = 0, painted = 0
    for (let i = 0; i < lines.length && made < n; i++) {
      const l = lines[i]
      if (pool.some(p => key(p) === key(l)) || seeds.some(s => key(s) === key(l))) continue
      let entry = l
      if (paint && pool.filter(p => p && p.img).length + painted < 25) {
        try {
          note(`painting ${painted + 1}…`)
          const b64 = await window.ozNano.generate(ART[voiceId](path) + '. The subject, rendered simply and quietly: ' + l + ' No text anywhere.')
          entry = { t: l, img: await pocket('data:image/png;base64,' + b64, 384, 0.7) }
          painted++
        } catch (_) { /* wallet empty or brush slipped — the line still lands, paperless */ }
      }
      pool.push(entry); made++
      note(`${made}/${n} made`)
    }
    S('clock-gen-' + laneId, pool)
    return { made, painted }
  }

  // ── MOVE_VIDS — the video search, shared (settings button + the clock's load).
  //    q comes from the move doctrine box; force skips the 6h cache. real watch-links only. ──
  window.MOVE_VIDS = async function (q, force) {
    try { if (localStorage.getItem('oz-videos-off') === '1') return [] } catch (_) {}   // the GLOBAL videos master (Sum 2026-07-22) — off = no video from any source
    q = String(q || '').trim().slice(0, 60)
    if (!q) return []
    let cache = null
    try { cache = JSON.parse(localStorage.getItem('clock-move-vids') || 'null') } catch (_) {}
    if (!force && cache && cache.q === q && Date.now() - cache.at < 6 * 3600000) return cache.items
    const c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
    if (!(c && c.invoke)) return (cache && cache.items) || []
    try {
      const html = await c.invoke('fetch_page', { url: 'https://www.youtube.com/results?search_query=' + encodeURIComponent(q + ' workout') })
      const vids = []
      const rx = /"videoRenderer":\{"videoId":"([^"]+)".*?"title":\{"runs":\[\{"text":"((?:[^"\\]|\\.)*)"/g
      let mv
      while ((mv = rx.exec(html)) && vids.length < 4) {
        let title = mv[2]
        try { title = JSON.parse('"' + mv[2] + '"') } catch (_) {}
        vids.push({ title: '▶️ ' + title, desc: 'found for "' + q + '" — opens the real video', link: 'https://www.youtube.com/watch?v=' + mv[1], src: 'video', credit: 'youtube.com', lane: true, laneId: 'exercise' })
      }
      if (vids.length) { try { localStorage.setItem('clock-move-vids', JSON.stringify({ q, at: Date.now(), items: vids })) } catch (_) {} }
      return vids.length ? vids : ((cache && cache.items) || [])
    } catch (e) { console.warn('[move] video search failed', e); return (cache && cache.items) || [] }
  }

  // ── LEARN_WIRE — real lessons & textbooks on the typed direction (MOVE_VIDS's twin;
  //    Sum 2026-07-20: "learn is a hand roll now… make new with direction"). the ONE
  //    doctrine box drives this AND the gen. wikibooks + wikiversity live (opensearch,
  //    keyless, CORS-open); OpenStax book + LibreTexts + MIT OCW from curated real slugs, each
  //    curl-verified 200 on 2026-07-20. NO Khan — dead end, every link a fake paywall (Sum
  //    2026-07-23). cached 6h in clock-learn-items; force re-pulls. ──
  // third element = the book's verified FIRST PAGE in the reader (Sum 2026-07-20: "all the
  // textbooks are just the menu") — the link opens ON content, not the details page. each
  // path curl-verified 200; '' = no stable first page found, the details door stands.
  const OPENSTAX = {
    'calculus': ['Calculus', 'calculus-volume-1', '1-introduction'], 'physics': ['University Physics', 'university-physics-volume-1', '1-introduction'],
    'organic chemistry': ['Organic Chemistry', 'organic-chemistry', '1-why-this-chapter'], 'chemistry': ['Chemistry 2e', 'chemistry-2e', '1-introduction'],
    'microbiology': ['Microbiology', 'microbiology', '1-introduction'], 'biology': ['Biology 2e', 'biology-2e', '1-introduction'],
    'anatomy': ['Anatomy & Physiology', 'anatomy-and-physiology-2e', '1-introduction'], 'astronomy': ['Astronomy 2e', 'astronomy-2e', '1-introduction'],
    'psychology': ['Psychology 2e', 'psychology-2e', '1-introduction'], 'sociology': ['Introduction to Sociology 3e', 'introduction-sociology-3e', '1-introduction'],
    'economics': ['Principles of Economics 3e', 'principles-economics-3e', '1-introduction'], 'statistics': ['Introductory Statistics 2e', 'introductory-statistics-2e', '1-introduction'],
    'algebra': ['College Algebra 2e', 'college-algebra-2e', 'preface'], 'trigonometry': ['Algebra and Trigonometry 2e', 'algebra-and-trigonometry-2e', 'preface'],
    'precalculus': ['Precalculus 2e', 'precalculus-2e', 'preface'], 'python': ['Introduction to Python Programming', 'introduction-python-programming', '1-introduction'],
    'computer science': ['Introduction to Computer Science', 'introduction-computer-science', '1-introduction'],
    'world history': ['World History Volume 1', 'world-history-volume-1', '1-introduction'], 'us history': ['U.S. History', 'us-history', '1-introduction'],
    'history': ['U.S. History', 'us-history', '1-introduction'], 'philosophy': ['Introduction to Philosophy', 'introduction-philosophy', '1-introduction'],
    'government': ['American Government', 'american-government-4e', '1-introduction'], 'business': ['Introduction to Business', 'introduction-business', '1-introduction'],
    'writing': ['Writing Guide with Handbook', 'writing-guide-with-handbook', ''],
  }
  // topic → LibreTexts library subdomain (their shelves are split by field)
  const LIBRE = {
    'chemistry': 'chem', 'organic chemistry': 'chem', 'biology': 'bio', 'microbiology': 'bio', 'anatomy': 'bio',
    'calculus': 'math', 'algebra': 'math', 'linear algebra': 'math', 'trigonometry': 'math', 'precalculus': 'math', 'geometry': 'math',
    'statistics': 'stats', 'physics': 'phys', 'astronomy': 'phys', 'psychology': 'socialsci', 'sociology': 'socialsci',
    'economics': 'socialsci', 'government': 'socialsci', 'philosophy': 'human', 'history': 'human', 'writing': 'human',
    'art': 'human', 'grammar': 'human', 'python': 'eng', 'programming': 'eng', 'coding': 'eng', 'computer science': 'eng',
    'engineering': 'eng', 'business': 'biz', 'finance': 'biz',
  }
  // (khan was here — killed 2026-07-20, Sum: "I am familiar and not impressed." no API
  // since they closed it, and the free-dressed-as-paywall funnel isn't worth a card slot.
  // MIT's open search took the seat — real courses, keyless, loginless.)
  // the SOURCE ROSTER (Sum 2026-07-20: "same bean as authors/spirituality — toggle on off
  // lessons from that group, just 3 in each") — clock-learn-on holds 'lessons' + these;
  // a legacy plain 'wire' entry expands to the full roster once.
  const LEARN_SRC = ['wikibooks', 'wikiversity', 'libretexts', 'openstax', 'mit']
  window.LEARN_SOURCES = LEARN_SRC
  const learnOn = () => {
    let on = J('clock-learn-on', 'null') || ['lessons', ...LEARN_SRC]
    if (on.includes('wire')) { on = [...new Set(on.filter(x => x !== 'wire').concat(LEARN_SRC))]; S('clock-learn-on', on) }
    return on
  }
  window.LEARN_ON = learnOn
  window.LEARN_WIRE = async function (q, force) {
    q = String(q || '').trim().slice(0, 60)
    const on = learnOn().filter(x => LEARN_SRC.includes(x))
    if (!on.length) return []
    const sig = (q || '~lottery') + '|' + on.slice().sort().join(',')   // a toggled source changes the signature — the cache refetches
    let cache = null
    try { cache = JSON.parse(localStorage.getItem('clock-learn-items') || 'null') } catch (_) {}
    if (!force && cache && cache.v === 7 && cache.sig === sig && Date.now() - cache.at < 6 * 3600000) return cache.items
    const items = []
    // NO DIRECTION → THE LOTTERY (Sum 2026-07-20: "pull 3 random subjects from each") —
    // every source draws three random subjects from the house list and serves one find
    // apiece, so the shelves fill out of the box. a typed direction replaces the lottery.
    const SUBJECTS = [...new Set(Object.keys(OPENSTAX).concat(Object.keys(LIBRE)))]
    const draw = (list, n) => { const d = list.slice(); for (let i = d.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [d[i], d[j]] = [d[j], d[i]] } return d.slice(0, n) }
    // LESSONS, not menus: full-text search — subpages ("Calculus/Limits") carry the actual
    // teaching and rank first; the root page files last; the snippet rides as the desc.
    const open = async (host, mark, what, wsrc) => {
      const terms = q ? [q] : draw(SUBJECTS, 3)
      const per = q ? 3 : 1
      for (const term of terms) {
        const r = await fetch(`https://${host}/w/api.php?action=query&list=search&format=json&origin=*&srlimit=12&srsearch=` + encodeURIComponent(term))
        if (!r.ok) throw new Error(r.status)
        const hits = (((await r.json()).query || {}).search || [])
        const meta = /\b(contributing|print version|references|cover|about|courses|talk)\b/i
        const ranked = hits.filter(h => h.title.includes('/') && !meta.test(h.title))
          .concat(hits.filter(h => !h.title.includes('/') && !meta.test(h.title)))
        // MENU-PAGE GUARDS (Sum 2026-07-20: "landed at a menu again" — the lottery drew
        // 'art' and served an awards page that was nine links in a trenchcoat):
        // 1. a real chapter has a BODY — under ~150 words is a link-list stub; skip it.
        // 2. a lottery draw must come from a BOOK named for its subject (root segment
        //    match) — a typed direction searches free; you can see what you asked for.
        let picks = ranked.filter(h => (h.wordcount || 0) >= 150)
        if (!picks.length) picks = ranked
        if (!q) picks = picks.filter(h => h.title.split('/')[0].toLowerCase().includes(term.toLowerCase()))
        picks.slice(0, per).forEach(h => items.push({
          title: `${mark} ${h.title.replace(/\//g, ' › ')} — ${what}`,
          desc: (h.snippet || '').replace(/<[^>]*>/g, '').replace(/&[a-z#0-9]+;/gi, ' ').replace(/\s+/g, ' ').trim().slice(0, 300) || `real open material on "${term}"`,
          link: `https://${host}/wiki/` + encodeURIComponent(h.title.replace(/ /g, '_')),
          src: 'learn', credit: host.replace('en.', ''), lane: true, laneId: 'learn', wsrc,
        }))
      }
    }
    if (on.includes('wikibooks')) { try { await open('en.wikibooks.org', '📖', 'textbook chapter', 'wikibooks') } catch (e) { console.warn('[learn] wikibooks failed', e) } }
    if (on.includes('wikiversity')) { try { await open('en.wikiversity.org', '🎓', 'lesson page', 'wikiversity') } catch (e) { console.warn('[learn] wikiversity failed', e) } }
    const ql = q.toLowerCase()
    const hit = map => Object.keys(map).filter(k => ql.includes(k) || k.includes(ql)).sort((a, b) => b.length - a.length)[0]   // longest match wins: 'organic chemistry' beats 'chemistry'
    // LibreTexts — real numbered lessons off the field library's shelves. their API sends
    // no CORS, so this rides the metal (fetch_page bolt) like MOVE_VIDS does.
    const bolt = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
    if (on.includes('libretexts') && bolt && bolt.invoke) {
      // typed: the topic searches its mapped library, 3 finds. lottery: 3 random mapped
      // subjects, one find each — subject is both the library pick and the search term.
      const runs = q ? (hit(LIBRE) ? [[hit(LIBRE), q, 3]] : []) : draw(Object.keys(LIBRE), 3).map(k => [k, k, 1])
      for (const [k, term, per] of runs) {
        try {
          const raw = await bolt.invoke('fetch_page', { url: `https://${LIBRE[k]}.libretexts.org/@api/deki/site/search?q=${encodeURIComponent(term)}&limit=10&dream.out.format=json` })
          let pages = JSON.parse(raw).page || []
          if (!Array.isArray(pages)) pages = [pages]
          const lessons = pages.filter(p => p && p['uri.ui'] && /Bookshelves|Courses/.test(p['uri.ui']))
          lessons.sort((a, b) => (/^\d/.test(String(b.title)) ? 1 : 0) - (/^\d/.test(String(a.title)) ? 1 : 0))   // numbered sections (6.1: …) are the lessons — first
          lessons.slice(0, per).forEach(p => items.push({ title: `📚 ${p.title} — LibreTexts lesson`, desc: `a real page off the ${LIBRE[k]} library shelves, matched to "${term}"`, link: p['uri.ui'], src: 'learn', credit: LIBRE[k] + '.libretexts.org', lane: true, laneId: 'learn', wsrc: 'libretexts' }))
        } catch (e) { console.warn('[learn] libretexts failed', e) }
      }
    }
    if (on.includes('openstax')) {
      // typed: the one matching book. lottery: 3 random books off the catalog (unique slugs)
      const picks = q ? (hit(OPENSTAX) ? [hit(OPENSTAX)] : [])
                      : draw([...new Map(Object.keys(OPENSTAX).map(k => [OPENSTAX[k][1], k])).values()], 3)
      picks.forEach(k => items.push({ title: `📚 ${OPENSTAX[k][0]} — the full textbook, opens at page one`, desc: `OpenStax's real book on ${k} — the reader lands on content, read the whole thing free`, link: OPENSTAX[k][2] ? `https://openstax.org/books/${OPENSTAX[k][1]}/pages/${OPENSTAX[k][2]}` : 'https://openstax.org/details/books/' + OPENSTAX[k][1], src: 'learn', credit: 'openstax.org', lane: true, laneId: 'learn', wsrc: 'openstax' }))
    }
    // MIT — the whole course, actually free: open.mit.edu's search is a live elasticsearch
    // door (no CORS on the POST → the fetch_post bolt carries it). OCW runs only: lectures,
    // notes, problem sets, no login, no funnel. khan's old seat, better tenant.
    if (on.includes('mit') && bolt && bolt.invoke) {
      const runs = q ? [[q, 3]] : draw(SUBJECTS, 3).map(t => [t, 1])
      for (const [term, per] of runs) {
        try {
          const raw = await bolt.invoke('fetch_post', {
            url: 'https://open.mit.edu/api/v0/search/',
            body: JSON.stringify({ query: { bool: { must: [{ query_string: { query: term } }], filter: [{ term: { object_type: 'course' } }, { term: { platform: 'ocw' } }] } }, size: 8 }),
          })
          const hits = ((JSON.parse(raw).hits || {}).hits || [])
          let took = 0
          for (const h of hits) {
            if (took >= per) break
            const s = h._source || {}
            const slug = ((s.runs || [])[0] || {}).slug || ''
            if (!slug.startsWith('courses/')) continue
            items.push({ title: `🎓 MIT ${s.coursenum ? s.coursenum + ': ' : ''}${s.title} — the real course, actually free`, desc: `MIT OpenCourseWare on "${term}" — lectures, notes, problem sets; no login, no funnel`, link: `https://ocw.mit.edu/${slug}/`, src: 'learn', credit: 'ocw.mit.edu', lane: true, laneId: 'learn', wsrc: 'mit' })
            took++
          }
        } catch (e) { console.warn('[learn] mit failed', e) }
      }
    }
    if (items.length) { try { localStorage.setItem('clock-learn-items', JSON.stringify({ v: 7, sig, q, at: Date.now(), items })) } catch (_) {} }
    return items.length ? items : ((cache && cache.items) || [])
  }

  // ── TT_PAPERS — the morning edition, typeset by the traveler (Sum 2026-07-20:
  //    "make up some headlines if we don't have real ones — just create like 5").
  //    a jump with thin papers calls this in the BACKGROUND: five front-page lines
  //    for the landed date, saved into the trip manifest — revisits never re-pay.
  //    past = the real stories of that day and season; future = the traveler
  //    authoring tomorrow from real published trends (the asterisk was said once). ──
  window.TT_PAPERS = async function (dateStr, future) {
    if (!window.engineRaw) throw new Error('the engine is not loaded')
    const brief = [
      `write 5 front-page HEADLINES for the morning paper of ${dateStr}.`,
      future
        ? "this date is in the FUTURE: extrapolate real published trends and concepts into a morning paper that could happen — confident, no hedging inside the headlines. never a specific real person's death or harm."
        : "this date is in the PAST: lead with the real stories of that day and its season where you know them, in the wire-service register of the period. no inventions dressed as fact — a quiet day runs the era's ongoing stories.",
      'each: ONE line, a headline, 30–110 characters, no dateline, no surrounding quotes.',
      'output ONLY a fenced block, one headline per line, nothing else:\n```gen\n<headline>\n```',
    ].join('\n')
    let full = ''
    const res = await window.engineRaw({
      agentId: 'timetravel', slim: false, nopace: true,   // the traveler IS the editor
      extra: brief,
      messages: [{ role: 'user', content: `the morning edition for ${dateStr}, please — five headlines` }],
      onChunk: c => { full += c },
    })
    if (res && res.error) throw new Error(res.error)
    const m = /```gen\s*\n([\s\S]*?)```/.exec(full)
    return (m ? m[1] : '').split('\n').map(s => s.trim().replace(/^[-•]\s*/, ''))
      .filter(s => s.length > 12 && s.length < 160).slice(0, 5)
  }

  // ── the CADENCE — "make N per hour / day / week" runs from the shell, quietly ──
  const PER = { hour: 3600000, day: 86400000, week: 604800000 }
  async function tick() {
    for (const lane of Object.keys(VOICE)) {
      const per = G('clock-cad-' + lane)
      if (!PER[per]) continue
      const last = +G('clock-cadlast-' + lane) || 0
      if (Date.now() - last < PER[per]) continue
      try { localStorage.setItem('clock-cadlast-' + lane, String(Date.now())) } catch (_) {}
      try {
        const r = await window.LANE_GEN(lane, +G('clock-cadn-' + lane) || 5, G('clock-art-' + lane) === '1', () => {})
        console.log('[lanegen] cadence', lane, r)
      } catch (e) { console.warn('[lanegen] cadence', lane, 'failed', e) }
    }
  }
  setTimeout(tick, 90000)             // first check 90s after boot — let the desk settle
  setInterval(tick, 15 * 60000)       // then every 15 min; the per-lane stamps do the real gating
})()
