// settings.js — THE SETTINGS BEAN. one vanilla factory; every surface wears it the same way.
//
// FOR HUMANS:
//   a ⚙️ gear that opens a settings panel, worn by any bot or card. it obeys ONE global rule
//   (the learn card set it): settings OR content, never both — and you close it two ways, by
//   toggling the gear or by the ✕ at the bottom. the bean is just the CHROME (gear + panel +
//   that nav). the caller hands it the FILLING via render(panel). one factory, every surface —
//   so the gear looks + navigates identically everywhere (IC: reuse over copy-paste).
//   the default bot filling is its CHART: persona · backstory · pronouns · model · skin — the
//   same toto_bot_<id>_* record the 💉 injection + ⚙️ settings cards keep. change one, change both.
//
// FOR AI:
//   1. window.makeSettings(host, opts) → { gear, panel, show }. mounts the gear + a hidden panel.
//   2. on open: hide opts.content, render the body, append a ✕ row if the body lacks one.
//   3. window.wireBotSettings(bar, id) → the default persona/model filling for a bot.
//   4. never invent a new data model — reuse toto_bot_<id>_* and window.REG / window.AGENT_DATA.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the bean — gear + panel + the GLOBAL nav ..... search: "the bean — gear + panel"
//   the DEFAULT bot filling — the bot's CHART, ... search: "the DEFAULT bot filling"
//   the small wiring factories — reusable so ..... search: "the small wiring"
//   the factories the SPECIAL panels ............. search: "the factories the"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The settings panel chrome (gear icon + hidden panel + show/hide toggle) worn by
//    **every bot and card. Exports `window.makeSettings()`, `window.wireBotSettings()`,
//    **`window.wireCardSettings()`, and `window.SETTINGS` (a bundle of reusable field builders and
//    **wiring factories). The default bot filling (`renderBot`) reads and writes `toto_bot_<id>_*`
//    **localStorage keys — the same record the injection card keeps.
//
//    **TOUCH HERE**
//    - Change the gear icon appearance → `window.OZ_GEAR_SVG` L22, or the fallback SVG in `gear`
//    - setup L46
//    - Change which localStorage keys a bot saves → edit `renderBot()` L151 (the `field()` calls
//    - L155–159) and corresponding `wireModel/wireSkin/wireVoice` calls L164
//    - Add a new field to the bot chart → add a `field()` call in `renderBot()` L151–159, then wire
//    - it in L162–164 if it needs live-save or special handling
//    - Change the close button text or styling → L70 (the `ls-close` row HTML)
//    - Change where the gear mounts on a bar → `before` option L51, or pass `opts.before` when
//    - calling `makeSettings()`
//    - ^ CORRECTION (2026-08-28): `before` is retired — the gear always seats FAR RIGHT (past STOP)
//    - via window.mountGear (shell/cards.js). The seat is a convention now, not an option.
//    - Add a special panel for a new bot (like tutor or writer) → create a new render function and
//    - call `window.makeSettings()` with it (see `wireBotSettings()` L181 as the template)
//    - Change voice device detection or TTS behavior → `voiceField()` L110, `voiceOptions()` L104,
//    - `wireVoice()` L117
//
//    **TRAPS**
//    - `toto_bot_<id>_*` keys are persisted in localStorage — renaming them orphans user data. The
//    - injection card (elsewhere) uses the same keys; change both files together or data splits.
//    - `toto` and `pa` share a model (L140) — they are the same bot in different hats. Changing one
//    - must change both, or they desync.
//    - The GLOBAL rule (settings OR content, never both) is enforced by `show()` L62 via
//    - `content.hidden` and `content.style.display` — L64 uses inline style because `.convo` and
//    - `.card-body` carry `display:flex`, which outranks the UA `[hidden]` rule. Removing the style
//    - will leave content visible while settings are open.
//    - `voiceOptions()` L104 calls `window.OZ_VOICE.voices()` which may be empty on first paint —
//    - `wireVoice()` L117 refills it async. If you change the voice select's structure, the refill
//    - logic (L121) must still find it.
//    - The ✕ close button is appended only if `panel.querySelector('.ls-close')` returns null (L68)
//    - — if you change the class name, the guard fails and you get two close buttons.
//    - `window.AGENT_DATA[a]` (L152) is read to populate fallback values for persona and backstory
//    - (L157–158). If that object is not populated before `renderBot()` runs, those fields will be
//    - empty.
//
//    **DO NOT**
//    - Rename `toto_bot_<id>_*` keys without updating the injection card and any other code that
//    - reads them.
//    - Move the `get()` / `set()` helpers (L24–25) — they are used throughout and exported in
//    - `window.SETTINGS` L198.
//    - Change the panel's class name from `tutor-settings` (L55) without updating the CSS that
//    - styles it.
//    - Add new localStorage keys without documenting them — they are user data and persist across
//    - sessions.
//    - Implement voice, model, or skin logic here that belongs in the device layer
//    - (`window.OZ_VOICE`, `window.REG`) — this file only reads and wires them.
//    - Add bot-specific logic (like the timetravel folder button L168) to `renderBot()` if it will
//    - clutter the default chart — consider a separate render function instead.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  // (Sum 2026-07-10) THE GEAR BEAN — one flat gear, shared everywhere (bots · cards · app-cards · calendar · cli).
  // inline SVG, currentColor (themes with the skin), crisp at any zoom, renders IDENTICALLY on Mac + PC (the ⚙️ emoji
  // does not — it's Apple-3D on Mac). must port to PC by Fri. use `window.OZ_GEAR_SVG` anywhere a gear is drawn.
  window.OZ_GEAR_SVG = '<img class="oz-gear-ico" src="cards/gear/gear.png" alt="settings">'
  const esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
  const get = k => localStorage.getItem(k) || ''
  const set = (k, v) => localStorage.setItem(k, v)

  // ── the bean — gear + panel + the GLOBAL nav rule. host = an .agent-bar OR a .card. ──
  // headSel  where the gear mounts          (default '.ab-head', falls back to '.card-head')
  // before   insert the gear before this selector in the head   (e.g. '.ab-add')
  //          ^ CORRECTION (2026-08-28): retired — the gear always seats far right now (mountGear); passing `before` is ignored
  // content  the node hidden while settings show  (default '.convo' || '.card-body')
  // title    gear tooltip
  // render   fills the panel on each open; the bean appends a ✕ row if render didn't add one
  window.makeSettings = function (host, opts) {
    opts = opts || {}
    // auto-detect the surface: an agent BAR (.ab-head + .convo) or a CARD (.card-head + .card-body).
    // the GLOBAL rule is the same either way — opening settings hides the surface's CONTENT.
    const isCard = host.classList.contains('card') || !host.querySelector('.ab-head')
    const head = host.querySelector(opts.headSel || (isCard ? '.card-head' : '.ab-head'))
    if (!head || head.querySelector('.ab-gear')) return null   // no head, or already worn — don't double up
    const content = opts.content || host.querySelector(isCard ? '.card-body' : '.convo')

    const gear = document.createElement('button')
    // (Sum 2026-07-10) a flat inline-SVG gear, NOT the ⚙️ emoji — the emoji renders Apple-3D on Mac + wrong on Windows,
    // and this HAS to port to PC. one gear, currentColor (themes with the skin), crisp at any zoom. changes every bot+card at once.
    gear.className = 'ab-gear' + (isCard ? ' card-gear' : ''); gear.type = 'button'
    gear.innerHTML = window.OZ_GEAR_SVG || '<svg viewBox="0 0 24 24" width="17" height="17" fill="currentColor" aria-hidden="true"><path d="M12 15.5A3.5 3.5 0 1 1 12 8.5a3.5 3.5 0 0 1 0 7zm7.43-2.53c.04-.32.07-.65.07-.97s-.03-.65-.07-.97l2.11-1.65a.5.5 0 0 0 .12-.64l-2-3.46a.5.5 0 0 0-.61-.22l-2.49 1a7.3 7.3 0 0 0-1.69-.98l-.38-2.65A.49.49 0 0 0 14 2h-4a.49.49 0 0 0-.49.42l-.38 2.65c-.61.25-1.17.59-1.69.98l-2.49-1a.5.5 0 0 0-.61.22l-2 3.46a.5.5 0 0 0 .12.64L4.57 11c-.04.32-.07.65-.07.97s.03.65.07.97l-2.11 1.65a.5.5 0 0 0-.12.64l2 3.46c.14.24.44.32.68.22l2.49-1c.52.39 1.08.73 1.69.98l.38 2.65c.05.24.26.42.49.42h4c.24 0 .44-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.24.1.54.02.68-.22l2-3.46a.5.5 0 0 0-.12-.64l-2.11-1.65z"/></svg>'
    gear.title = opts.title || 'settings'
    gear.addEventListener('mousedown', e => e.stopPropagation())   // a bar head must not collapse on gear-press
    // bars slot the gear at the END of the LEFT cluster — after ＋ and 🧠ESP, before the .ab-fill spacer
    // (so the head reads: icon · name · ＋ · ESP · ⚙ · [space] · jewels · STOP). cards append it (right side).
    // CORRECTION (Sum 2026-08-28): the left-cluster seat is RETIRED — the gear now sits FAR RIGHT,
    // past STOP, on bars AND cards alike, matching the app's top bar (topbar.css .tb-spacer + gear
    // last). One seat, one mount: window.mountGear (shell/cards.js) wraps it in .card-gearbox, which
    // also carries the squeeze rule (narrow head → gear hides BEFORE stop). The `before` opt died
    // with the old seat — callers passing it (before:'.ab-add') were cleaned the same day; the knob
    // is gone so the seat can't scatter again. Everything else above is still true: same gear bean,
    // same mousedown guard, same settings-or-content law.
    if (window.mountGear) window.mountGear(head, gear)
    else head.appendChild(gear)   // belt-and-braces if cards.js hasn't loaded (it always has — script order)

    const panel = document.createElement('div')
    panel.className = 'tutor-settings'; panel.hidden = true   // reuse the styled panel chrome
    const parent = content ? content.parentNode : host
    parent.insertBefore(panel, content || null)

    // settings OR content; close two ways — the gear, or the ✕ at the bottom.
    // NOTE: use inline display, not [hidden] — .convo / .card-body carry `display:flex`, and a class
    // selector outranks the UA [hidden] rule, so the attribute alone would leave the content visible.
    const show = on => {
      panel.hidden = !on
      if (content) { content.hidden = on; content.style.display = on ? 'none' : '' }
      if (!on) return
      panel.innerHTML = ''
      if (opts.render) opts.render(panel)
      if (!panel.querySelector('.ls-close')) {
        const row = document.createElement('div'); row.className = 'ls-close-row'
        row.innerHTML = '<button class="ls-close">✕ close settings</button>'
        panel.appendChild(row)
      }
    }
    gear.addEventListener('click', e => { e.stopPropagation(); show(panel.hidden) })
    panel.addEventListener('click', e => { if (e.target.closest('.ls-close')) show(false) })
    return { gear, panel, show }
  }

  // ── the DEFAULT bot filling — the bot's CHART, keyed toto_bot_<id>_* (shared with injection). ──
  function field(k, label, ph, rows, fallback) {
    const v = get(k) || fallback || ''
    const input = rows > 1
      ? `<textarea class="ls-ta" rows="${rows}" data-k="${k}" spellcheck="false" placeholder="${esc(ph)}">${esc(v)}</textarea>`
      : `<input class="ls-in" type="text" data-k="${k}" value="${esc(v)}" placeholder="${esc(ph)}">`
    return `<div class="ls-row"><label class="ls-label">${label}</label>${input}</div>`
  }
  function modelField(a) {
    const avail = (window.REG && window.REG.availableModels && window.REG.availableModels(a)) || []
    if (!avail.length) return `<div class="ls-row"><label class="ls-label">model</label><div class="ls-skillnote">add + save a key in the ⚙️ settings card to unlock a model.</div></div>`
    // unset → SHOW haiku, because that's what the engine sends (ENGINE_DEFAULT_MODEL, 00-providers:
    // "the conductor is call-heavy, so a cheap default"). without this the <select> falls to option
    // one — fable, the flagship — and one touch saves it. Sum 2026-08-09: "default back to haiku to
    // save users some tokens... if they know they know, if not, pennies to chat all day."
    // ⭐ 2 Sep 2026 — SHOW THE TRUTH. This displayed 'claude-haiku-4-5' for any unpicked bot no matter which keys
    //    existed, while pickProvider() ran something else (a Gemini-only user saw "haiku" and got gemini-flash).
    //    With no pick, the dropdown now reads the SAME walk the engine will take — last-entered key first.
    const live = (() => { try { const p = !get('toto_bot_' + a + '_model') && window.pickProvider ? window.pickProvider(a) : null; return p && p.model } catch (_) { return null } })()
    const cur = get('toto_bot_' + a + '_model') || live || 'claude-haiku-4-5'
    const groups = avail.map(p => `<optgroup label="${esc(p.name)}">${p.models.map(m => `<option value="${esc(m)}"${m === cur ? ' selected' : ''}>${esc(m)}</option>`).join('')}</optgroup>`).join('')
    return `<div class="ls-row"><label class="ls-label">model</label><select class="ls-sel" data-k="toto_bot_${a}_model" data-model>${groups}</select></div>`
  }
  function skinField(a) {
    const skins = (window.REG && window.REG.skins) || []
    const cur = get('toto_bot_' + a + '_skin')
    const opts = ['<option value="">— default hat —</option>']
      .concat(skins.map(s => `<option value="${esc(s)}"${s === cur ? ' selected' : ''}>${esc(s)}</option>`)).join('')
    return `<div class="ls-row"><label class="ls-label">skin (the hat)</label><select class="ls-sel" data-k="toto_bot_${a}_skin" data-skin>${opts}</select></div>`
  }
  // VOICE (Sum 2026-07-21: "choose voice… injection around persona… gear this bot, all bots"). The list
  // is the DEVICE's own voices (getVoices — same on native + web demo). Per-bot override (toto_bot_<a>_voice)
  // over the global default (oz-voice); the "apply to" scope writes one or the other.
  function voiceOptions(a) {
    const list = (window.OZ_VOICE && window.OZ_VOICE.voices && window.OZ_VOICE.voices()) || []
    const cur = get('toto_bot_' + a + '_voice') || get('oz-voice') || ''
    return '<option value="">— system default —</option>' + list.map(v =>
      `<option value="${esc(v.name)}"${v.name === cur ? ' selected' : ''}>${esc(v.name)}${v.lang ? ' · ' + esc(v.lang) : ''}</option>`).join('')
  }
  function voiceField(a) {
    if (!(window.OZ_VOICE && window.OZ_VOICE.hasTTS)) return `<div class="ls-row"><label class="ls-label">voice</label><div class="ls-skillnote">no speech engine on this device.</div></div>`
    return `<div class="ls-row"><label class="ls-label">voice</label><select class="ls-sel" data-k="toto_bot_${a}_voice" data-voice>${voiceOptions(a)}</select></div>`
      + `<div class="ls-row"><label class="ls-label">apply to</label>`
      + `<select class="ls-sel" data-voice-scope><option value="this">just ${esc(a)}</option><option value="all">all bots</option></select>`
      + `<button class="ls-in ls-voice-test" type="button" data-voice-test style="flex:0 0 auto;cursor:pointer;text-align:center">▶ test</button></div>`
  }
  function wireVoice(scope, a) {
    const sel = scope.querySelector('select[data-voice]'); if (!sel) return
    const scopeSel = scope.querySelector('select[data-voice-scope]')
    // getVoices() is often empty on first paint — voices load async; refill when they arrive
    const refill = () => { const cur = sel.value; sel.innerHTML = voiceOptions(a); if (cur) sel.value = cur }
    if (sel.options.length <= 1) { try { window.speechSynthesis.addEventListener('voiceschanged', refill); setTimeout(refill, 400) } catch (_) {} }
    sel.addEventListener('change', () => {
      const val = sel.value, s = scopeSel ? scopeSel.value : 'this'
      if (s === 'all') { set('oz-voice', val); set('toto_bot_' + a + '_voice', '') }   // all bots → the global default; drop this bot's override
      else set('toto_bot_' + a + '_voice', val)
    })
    const test = scope.querySelector('[data-voice-test]')
    if (test) test.addEventListener('click', e => {
      e.preventDefault()
      if (window.OZ_VOICE && window.OZ_VOICE.speak) window.OZ_VOICE.speak('This is how ' + a + ' will sound.', { force: true, agentId: a })
    })
  }

  // ── the small wiring factories — reusable so EVERY bot panel saves identically. ──
  // wire only the model picker in a scope. toto ⇄ pa share a model (same bot, different hat).
  // ── CORRECTION 26 Aug: the pair used to be spelled out here — `if (a === 'toto' || a === 'pa')`.
  //    That is a fact about two bots, filed in the settings card, where neither of them can see it; the
  //    day one of them gets renamed or benched the other silently keeps writing to a dead key. The pair
  //    is now declared on both records as "modelTwin", so it travels with the bot. Symmetric on purpose:
  //    each names the other, so this reads one field and never has to search the roster for a partner.
  function wireModel(scope, a) {
    const twin = (window.AGENT_DATA && window.AGENT_DATA[a] && window.AGENT_DATA[a].modelTwin) || ''
    scope.querySelectorAll('select[data-model]').forEach(el => el.addEventListener('change', () => {
      set(el.dataset.k, el.value)
      if (twin) { set('toto_bot_' + a + '_model', el.value); set('toto_bot_' + twin + '_model', el.value) }
    }))
  }
  // wire only the skin picker. changing the hat re-skins the live bar.
  function wireSkin(scope, a) {
    scope.querySelectorAll('select[data-skin]').forEach(el => el.addEventListener('change', () => {
      set(el.dataset.k, el.value)
      if (window.rebuildAgentIfLive) window.rebuildAgentIfLive(a)
    }))
  }

  // THE PAPER — the newsie's knobs, in ITS gear (Sum 2026-08-22: "put the controls in newsie's gear to trim, not on paper";
  // "this is newsie's gear"). Plain localStorage keys read by cards/feedline/feedline.html and cards/myview/wire-db.js at
  // the next cut: how long a paper · wires per cut · candidates per wire · the link book's cap.
  function paperFields(a) {
    // ── CORRECTION 26 Aug: was `a !== 'newsie'`. The paper's knobs belong to whoever cuts the
    //    paper; that is caps: ["paper"] now, so a second paper bot gets its gear without a line here.
    if (!(window.REG && window.REG.hasCap && window.REG.hasCap(a, 'paper'))) return ''
    const sel = (k, label, note, opts, d) => { const cur = get(k) || d; return `<div class="ls-row"><label class="ls-label">${label}</label><select class="ls-sel" data-paper data-k="${k}">${opts.map(([v, t]) => `<option value="${v}"${String(v) === String(cur) ? ' selected' : ''}>${esc(t)}</option>`).join('')}</select></div>` + (note ? `<div class="ls-skillnote">${esc(note)}</div>` : '') }
    let book = 0; try { const f = window.SANDBOX && window.SANDBOX['feedline/links.json']; book = f ? JSON.parse(f.data || '[]').length : 0 } catch (_) {}
    return `<div class="ls-skillnote" style="margin-top:12px"><b>the paper</b> — the Feedline's knobs; they take on the next cut.</div>`
      + sel('feedline-target', 'how long a paper', "the Port Side View's front page runs about seventy stories.", [['40', 'about 40 stories'], ['70', 'about 70, a front page'], ['100', 'about 100'], ['0', 'everything that earns a 7']], '70')
      + sel('feedline-wires', 'wires per cut', 'the newsie picks them; more wires, more tokens.', [['3-6', '3 to 6'], ['4-8', '4 to 8'], ['6-10', '6 to 10']], '4-8')
      + sel('feedline-per-wire', 'candidates per wire', 'how deep into each wire the cut looks; the link book adds older ones.', [['25', '25'], ['40', '40'], ['60', '60']], '40')
      + `<div class="ls-row"><label class="ls-label">the link book</label><input class="ls-in" type="number" min="200" step="100" data-k="wire-db-max" value="${esc(get('wire-db-max') || '3000')}" aria-label="how many links the book keeps"></div>`
      + `<div class="ls-skillnote">one line per link seen, no pictures; ${book} in it now. past the cap the oldest-seen go first. nothing here leaves this machine.</div>`
      + bibleFields() + cookieFields() + ladderFields()
      + `<div class="ls-row" style="margin-top:10px"><label class="ls-label">the paper</label>${paperBtn('paper-reset', 'reset the paper to factory')}</div>`
      + `<div class="ls-skillnote">the editions, the bible, the link book, the drawer, the reading log and the knobs go; the wires' catalog, your keys and the chats stay.</div>`
  }
  // THE READ LADDER'S JENGA (Sum 2026-08-23: "a jenga for each rung of the ladder and the bouncer for the user to see and
  // learn and edit, like toggle on off over edit code, but we leave a tag to code; you can brick it — the factory reset is
  // for experimentations"). Toggles only, never code; the tag names the file.
  function ladderFields() {
    let L = {}; try { L = JSON.parse(get('read-ladder') || '{}') || {} } catch (_) {}
    const onTop = k => L[k] !== false
    const onB = k => ((L.bouncer || {})[k] !== false)
    const row = (k, label, note, sub) => `<div class="ls-row" style="align-items:center${sub ? ';padding-left:18px' : ''}"><label class="ls-label" style="flex:1 1 auto;font-weight:400">${label} <span style="opacity:.65">· ${note}</span></label><input type="checkbox" data-ladder="${k}"${(sub ? onB(k.slice(8)) : onTop(k)) ? ' checked' : ''}></div>`
    return `<div class="ls-skillnote" style="margin-top:12px"><b>the read ladder</b> — how a link becomes text, rung by rung. Toggle, don't edit; you can brick it, and the factory reset walks it back. The code behind it: <i>shell/clean-read.js</i>.</div>`
      + row('robots', 'the rules check', 'robots.txt first — a page the site asks bots to skip stays skipped; we answer to a higher authority')
      + row('eyesFirst', 'eyes first', 'a seeing bot gets the rendered page and its picture (the crawl rung with a shot)')
      + row('ally', 'the a11y rung', 'a plain fetch read clean by trafilatura on the local server — deterministic, no middleman; first for blind bots')
      + row('crawl', 'the crawl rung', 'real Chromium at 127.0.0.1:11235 — start it: ~/Local/crawl4ai/server.sh')
      + `<div class="ls-skillnote">the paste ask has no switch — the human rung always answers. <b>the bouncer's verdicts</b>, one each:</div>`
      + row('bouncer.challenge', 'challenge', 'prove-you-are-human pages', 1)
      + row('bouncer.paywall', 'paywall', "including the page's own declaration", 1)
      + row('bouncer.login', 'login wall', 'members only past this point', 1)
      + row('bouncer.refused', 'refused', 'the site, or the reader service, said no', 1)
      + row('bouncer.thin', 'thin read', 'almost nothing came back', 1)
      + `<div class="ls-row" style="margin-top:6px"><label class="ls-label">the ladder</label>${paperBtn('ladder-reset', 'reset the ladder to factory')}</div>`
  }
  // THE BIBLE, READABLE AND CORRECTABLE (Sum 2026-08-22: "correct newsie's bible by editing notes"): themes · rules · notes as
  // plain text; an edit is written straight to feedline/bible.json and the newsie reads it on the next cut.
  const sbFile = name => { try { const f = window.SANDBOX && window.SANDBOX[name]; return f ? JSON.parse(f.data || 'null') : null } catch (_) { return null } }
  const sbPut = (name, obj) => { try { window.SANDBOX[name] = { kind: 'code', ext: 'json', mime: '', data: JSON.stringify(obj) } } catch (_) {} }
  const sbGone = name => { try { const c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__); c && c.invoke && c.invoke('sandbox_remove', { name }); delete window.SANDBOX[name] } catch (_) {} }
  const paperBtn = (act, label) => `<button class="ls-in" type="button" data-paper-act="${act}" style="flex:0 0 auto;cursor:pointer;text-align:center">${esc(label)}</button>`
  function bibleFields() {
    const b = sbFile('feedline/bible.json') || {}
    const B = window.BIBLE, txt = B ? B.text(Object.assign({ editions: 0 }, b)) : ''
    const led = B ? B.ledger(b, (window.WIRE_NAMES || {})) : ''
    return `<div class="ls-skillnote" style="margin-top:12px"><b>the bible</b> — exactly what the newsie reads before a cut. One box; edit it, it reads it next cut. Its cuts add a line a day at the bottom.</div>`
      + `<div class="ls-row"><label class="ls-label">the bible</label><textarea class="ls-ta ls-bible" rows="10" data-bible="text" spellcheck="false" placeholder="nothing cut yet; the newsie starts from the short bible (the desks) and writes its own after the first cut">${esc(txt)}</textarea></div>`
      + (led ? `<div class="ls-skillnote">${esc(led)} (counted by the cuts, not edited)</div>` : '')
      + (b.editions ? `<div class="ls-row"><label class="ls-label"></label>${paperBtn('bible-reset', 'start the bible over')}</div>` : '')
  }
  // COOKIES AND MILK, READABLE AND DELETABLE (Sum: "delete just some milk and cookies"): the reading log, newest first, a ✕ each.
  function cookieFields() {
    const log = sbFile('reads/log.json'); const rows = Array.isArray(log) ? log : []
    const face = r => r.rating > 0 ? '👍' : r.rating < 0 ? '👎' : '😐'
    const line = (r, i) => `<div class="ls-row" style="align-items:center"><label class="ls-label" style="flex:1 1 auto;font-weight:400">${esc(new Date(r.at).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }))} · ${esc(r.paper || '')} · ${esc(r.source || '')} · ${esc(r.category || '')} · ${esc((r.keywords || []).slice(0, 4).join(', '))} ${face(r)}</label><button class="ls-in" type="button" data-cookie-x="${i}" aria-label="forget this one" style="flex:0 0 auto;cursor:pointer;padding:4px 10px">✕</button></div>`
    const shown = rows.map((r, i) => [r, i]).reverse().slice(0, 40)
    return `<div class="ls-skillnote" style="margin-top:12px"><b>cookies and milk</b> — your reading log, ${rows.length} line${rows.length === 1 ? '' : 's'}, on this machine only: source · category · keywords · rating, never the headline. The newsie reads it only when you tick the box on The Feedline.</div>`
      + (rows.length ? shown.map(([r, i]) => line(r, i)).join('') + (rows.length > 40 ? `<div class="ls-skillnote">(the newest 40 shown)</div>` : '') : `<div class="ls-skillnote">nothing rated yet.</div>`)
      + (rows.length ? `<div class="ls-row"><label class="ls-label"></label>${paperBtn('cookies-reset', 'forget all my cookies')}</div>` : '')
  }
  const PAPER_FILES = /^(editions\/(myview|feedline)-|feedline\/|reads\/|port\/hold-)/
  function wirePaper(scope, a) {
    scope.querySelectorAll('select[data-paper]').forEach(el => el.addEventListener('change', () => set(el.dataset.k, el.value)))
    scope.querySelectorAll('input[data-ladder]').forEach(el => el.addEventListener('change', () => {
      let L = {}; try { L = JSON.parse(get('read-ladder') || '{}') || {} } catch (_) {}
      const k = el.dataset.ladder
      if (k.indexOf('bouncer.') === 0) { L.bouncer = L.bouncer || {}; L.bouncer[k.slice(8)] = el.checked } else L[k] = el.checked
      set('read-ladder', JSON.stringify(L))
    }))
    scope.querySelectorAll('textarea[data-bible]').forEach(el => el.addEventListener('input', () => {
      const b = sbFile('feedline/bible.json') || { editions: 0, lastAt: 0, wires: {}, sources: {}, themes: [], rules: [], asks: [], notes: [] }
      b.text = el.value; sbPut('feedline/bible.json', b)   // the one text the newsie reads; the ledger underneath is untouched
    }))
    scope.querySelectorAll('button[data-cookie-x]').forEach(el => el.addEventListener('click', e => {
      e.preventDefault(); const log = sbFile('reads/log.json'); if (!Array.isArray(log)) return
      log.splice(+el.dataset.cookieX, 1); sbPut('reads/log.json', log); renderBot(scope, a)
    }))
    // the three resets: press once to arm, again to do it (no dialog, no accident)
    scope.querySelectorAll('button[data-paper-act]').forEach(el => el.addEventListener('click', e => {
      e.preventDefault()
      if (el.dataset.armed !== '1') { el.dataset.armed = '1'; el.dataset.label = el.textContent; el.textContent = 'press again to ' + el.textContent; setTimeout(() => { if (el.isConnected) { el.dataset.armed = ''; el.textContent = el.dataset.label } }, 4000); return }
      const act = el.dataset.paperAct
      if (act === 'ladder-reset') { try { localStorage.removeItem('read-ladder') } catch (_) {} }
      else if (act === 'bible-reset') sbGone('feedline/bible.json')
      else if (act === 'cookies-reset') sbGone('reads/log.json')
      else if (act === 'paper-reset') { Object.keys(window.SANDBOX || {}).filter(k => PAPER_FILES.test(k)).forEach(sbGone); ['feedline-target', 'feedline-wires', 'feedline-per-wire', 'wire-db-max', 'myview-wires', 'myview-opts', 'myview-horo', 'milk-consent', 'paper-columns'].forEach(k => { try { localStorage.removeItem(k) } catch (_) {} }) }
      renderBot(scope, a)
    }))
  }

  function renderBot(panel, a) {
    const d = (window.AGENT_DATA && window.AGENT_DATA[a]) || {}
    panel.innerHTML =
      `<div class="ls-skillnote">${esc(a)}'s chart — the same one the 💉 injection card keeps. persona is the strongest field; change it here or there, it's one record.</div>` +
      field('toto_bot_' + a + '_name', 'name', 'optional', 1) +
      field('toto_bot_' + a + '_pronouns', 'pronouns', 'they/them', 1) +
      field('toto_bot_' + a + '_persona', 'persona', 'core personality + how it speaks. the most powerful field.', 4, d.persona) +
      field('toto_bot_' + a + '_backstory', 'backstory', 'implanted memories — a history that shapes the voice.', 3, d.backstory) +
      voiceField(a) + modelField(a) + skinField(a) + paperFields(a)

    // text fields live-save on input; the selects wire through the shared factories.
    panel.querySelectorAll('input[data-k], textarea[data-k]').forEach(el =>
      el.addEventListener('input', () => set(el.dataset.k, el.value)))
    wireModel(panel, a); wireSkin(panel, a); wireVoice(panel, a); wirePaper(panel, a)

    // the traveler's gear carries the door to its trips folder (Sum 2026-07-18) —
    // every adventure is real files; open it in Finder and clean it like any folder.
    // ── CORRECTION 26 Aug: was `a === 'timetravel'`. caps: ["travel"] on the bot. The button still
    //    only draws when TT_REVEAL exists, so a build without the traveler's machinery shows nothing.
    if ((window.REG && window.REG.hasCap && window.REG.hasCap(a, 'travel')) && window.TT_REVEAL) {
      const b = document.createElement('button')
      b.className = 'tt-folder-btn'
      b.textContent = '🗂 open the trips folder — every adventure is files; the trash is undo'
      b.style.cssText = 'display:block;width:100%;min-height:44px;margin-top:10px;padding:8px 12px;'
        + 'background:#171b22;color:#ffd27a;border:1px solid #3a4250;border-radius:8px;'
        + 'box-shadow:0 3px 0 rgba(0,0,0,.55);font-family:inherit;font-size:inherit;font-weight:bold;cursor:pointer'
      b.addEventListener('click', () => window.TT_REVEAL())
      panel.appendChild(b)
    }
  }

  // every bot WITHOUT a special panel (tutor=learn, writer=voices keep theirs) wears this.
  window.wireBotSettings = function (bar, agentId) {
    return window.makeSettings(bar, {
      headSel: '.ab-head',   // (2026-08-28) before:'.ab-add' retired — gear seats far right via mountGear
      content: bar.querySelector('.convo'),
      title: 'persona · backstory · model',
      render: panel => renderBot(panel, agentId),
    })
  }

  // any CARD wears the bean the same way a bot does — the rule (settings OR content) is automatic:
  // the card's .card-body is hidden while the panel is open. pass a render(panel) for the filling.
  window.wireCardSettings = function (card, render, opts) {
    return window.makeSettings(card, Object.assign({ title: 'settings', render: render }, opts || {}))
  }

  // ── the factories the SPECIAL panels (tutor=learn, writer=voices) drop in for their model picker. ──
  // field() builds a plain localStorage-bound row — reusable by any card's settings render, too.
  window.SETTINGS = { modelField, skinField, voiceField, wireModel, wireSkin, wireVoice, field, esc, get, set }

  // ⭐⭐ HEAL THE TWINS AT BOOT (Sum 1 Sep 2026). wireModel only writes both keys ON CHANGE — so a
  //  pair that was already stale, or that BECAME a pair after one side was set, stayed split
  //  forever. That is exactly what bit: he set the model on the LEARNER panel (fable-5) and then
  //  chatted with the TUTOR, which reads its own key. Unset, so modelField's default showed haiku
  //  and the ENGINE ran haiku — the picker said one thing and the bot was another.
  //  ⚠ THE FIX IS ON THE DATA, NOT THE READERS. Five separate files read `toto_bot_<id>_model` raw
  //  (engine.js:170 · sys.js:31 · context-bar.js:118 · settings.js:180 · cards/settings/settings.js:184).
  //  Teaching each of them about twins would be ONE CONCERN LIVING IN FIVE PLACES — the exact shape
  //  the tape test calls built-wrong. Heal the stored key once and all five are right, untouched.
  //  ⚠ FILLS EMPTIES ONLY. It never overwrites a set value, so it cannot quietly undo a deliberate
  //  choice; a real disagreement between two twins is left alone and stays visible.
  try {
    const D = window.AGENT_DATA || {}
    Object.keys(D).forEach(id => {
      const twin = D[id] && D[id].modelTwin
      if (!twin || !D[twin]) return
      const mine = get('toto_bot_' + id + '_model'), theirs = get('toto_bot_' + twin + '_model')
      if (!mine && theirs) {
        set('toto_bot_' + id + '_model', theirs)
        try { console.info('[twin] ' + id + ' adopted ' + twin + "'s model: " + theirs) } catch (_) {}
      }
    })
  } catch (_) {}
})()
