// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   🛏️ sleep ...................................... search: "🛏️ sleep"
//   editable clinical notes (you OR the AI ........ search: "editable clinical notes"
//   sleep profile: load from localStorage, save ... search: "sleep profile: load"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the sleep card UI: the weekly sleep
//    **report, night-by-night tiles, manual night entry form, and the settings panel. It exports
//    **`window.CARD_BUILDERS.sleep`, a function that returns the DOM element `el` (line 10). The
//    **card persists three things to localStorage: manual nights via `saveNights()` (line 98),
//    **dream text as `toto_sleep_dream` (line 34, 99), and sleep profile fields as
//    **`toto_sleep_profile` (line 117).
//
//    **TOUCH HERE** —
//    - Change the report's CSS or HTML layout → `printSleep()` L42–74
//    - Change which stats appear in the weekly summary table → `printSleep()` L54–59
//    - Change the night-by-night table columns → `printSleep()` L69
//    - Add or remove a profile field (e.g., "goal deep sleep") → edit `PROFILE_HTML` (not in this
//    - file; see DO NOT) and add `data-k="fieldname"` to the input, then it auto-loads/saves via
//    - `spLoad()` L119 and `spSave()` L125
//    - Change the onset-latency block visibility → `showLat` flag L6, toggled at L84
//    - Change sub-card heights (report 480px, journal 460px) → `subHeight` object L16
//    - Change the range default (7 days) → `range` L6
//    - Swap which sub-card opens first (osc vs journal) → `subOpen` object L16
//    - Change the gear button icon → `window.OZ_GEAR_SVG` (line 8, set elsewhere)
//    - Reword the badge or title → line 10
//
//    **TRAPS** —
//    - `localStorage` keys are load-bearing: `toto_sleep_dream` (L34, 99), `toto_sleep_profile`
//    - (L117). Renaming orphans user data.
//    - `current.nights` shape is persisted (L98). Adding/removing fields breaks old imports;
//    - coordinate with `normalizeNight()` (L96, defined elsewhere).
//    - `notes.pattern` and `notes.toto` (L5) are rendered in the print report (L70) and edited in
//    - the UI (L78). Renaming either breaks the edit-persist cycle.
//    - `subOpen` and `subHeight` (L16) are paired: the applySubs logic (L17–22) reads both.
//    - Changing one without the other breaks the collapse/expand behavior.
//    - The dream textarea (L93) must clear after a night is added (L99) or the dream persists to
//    - the next entry.
//    - `spFields()` (L118) queries `[data-k]` on the panel; the HTML must match the keys you read
//    - in `spLoad()` and `spSave()` (L122, 126).
//    - `renderReport()` (L23) calls `applySubs()` (L24); if you add new sub-cards, they must exist
//    - in the HTML before `applySubs()` runs or the toggle will fail silently.
//    - The file input (L114, 138–150) clears itself (L139) to allow re-importing the same file; do
//    - not remove that line.
//
//    **DO NOT** —
//    - Do not edit `REAL.week`, `REAL.primary`, `REAL.nights` (L4) — they are seed data from
//    - elsewhere.
//    - Do not edit `loadNights()`, `saveNights()`, `normalizeNight()`, `windowNights()`,
//    - `statsOf()`, `latestIsoOf()`, `dShiftIso()`, `todayIso()`, `rangeLabel()`, `sleepBody()`,
//    - `sTiles()`, `sNightsHTML()`, `parseImport()`, `wellnessPrint()`, `esc()`, `fmt()` — all
//    - defined elsewhere.
//    - Do not edit `PROFILE_HTML`, `SETUP_HTML`, `REPORT_CSS`, `NOTE_PATTERN`, `NOTE_TOTO` — all
//    - defined elsewhere.
//    - Do not edit the event delegation pattern (lines 25–33, 75–101, 130–150) without
//    - understanding that it survives `renderReport()` because listeners are on `dashBody`, not on
//    - re-rendered children.
//    - Do not move the panel creation (L102–104) or the `spSetOpen()` logic (L106–112) — the gear
//    - button (L132) and close button (L135) depend on the panel being a sibling in `.card-body`.
//
//
//
//    ---
//
// END IC SHIP PASS

  // ── 🛏️ sleep ──────────────────────────────────────────────────────
  window.CARD_BUILDERS = window.CARD_BUILDERS || {}
  window.CARD_BUILDERS.sleep = function buildSleep() {
    let current = { week: REAL.week, primary: REAL.primary, nights: loadNights() || REAL.nights.slice() }   // saved nights win; REAL is the seed fallback
    let notes = { pattern: NOTE_PATTERN, toto: NOTE_TOTO }
    let range = 7, end = latestIsoOf(current.nights), showLat = true
    const gear = document.createElement('button')
    gear.className = 'dash-gear'; gear.type = 'button'; gear.innerHTML = (window.OZ_GEAR_SVG || '⚙')
    gear.title = 'setup — get your own data in (the export dance + import)'
    const el = dashCard('sleep', 'cards/wellness/sleep.png', 'SLEEP', sleepBody(current, notes, range, end, showLat), { badge: 'real · Mar 2026', live: true, lav: true, badgeTitle: 'Sum’s real Google Fit + Nest Hub radar data · shared with consent', gear })
    const cardBody = el.querySelector('.card-body'); cardBody.style.overflowY = 'auto'   // (Sum 2026-07-10) interior scroll back ON — the card was growing + getting clipped by .card{overflow:hidden} → cut off   // grow → the desk doom-scrolls
    const badge = el.querySelector('.dash-demo')
    const dashBody = el.querySelector('.dash-body')
    dashBody.style.flex = 'none'; dashBody.style.overflowY = 'visible'
    // collapsible osc / journal sub-cards (osc = the report, fixed height + inner scroll · journal = grows to the page)
    const subOpen = { osc: false, journal: false }, subHeight = { osc: 480, journal: 460 }   // (Sum 2026-08-17) BOTH start collapsed, each toggles on its own — the card scrolls well
    const applySubs = () => dashBody.querySelectorAll('.dash-sub').forEach(s => {
      const k = s.classList.contains('dash-osc') ? 'osc' : 'journal'
      s.classList.toggle('collapsed', !subOpen[k])
      const b = s.querySelector('.dash-sub-body'); if (!b) return
      if (k === 'osc') { b.style.minHeight = ''; b.style.height = subHeight.osc + 'px' } else { b.style.height = 'auto'; b.style.minHeight = subHeight.journal + 'px' }
    })
    const renderReport = () => { dashBody.innerHTML = sleepBody(current, notes, range, end, showLat); applySubs() }
    applySubs()
    dashBody.addEventListener('mousedown', e => {   // the ⇕ on each sub-card → set its height (osc) / floor (journal)
      const sl = e.target.closest('.dash-sub-slider'); if (!sl) return
      e.preventDefault(); e.stopPropagation()
      const k = sl.dataset.sub, b = sl.parentElement.querySelector('.dash-sub-body'); if (!b) return
      const sy = e.clientY, sh = b.offsetHeight; document.body.classList.add('resizing')
      const move = ev => { const h = Math.max(80, sh + ev.clientY - sy); if (k === 'osc') b.style.height = h + 'px'; else b.style.minHeight = h + 'px'; subHeight[k] = h }
      const up = () => { document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up); document.body.classList.remove('resizing') }
      document.addEventListener('mousemove', move); document.addEventListener('mouseup', up)
    })
    dashBody.addEventListener('input', e => { const d = e.target.closest('.sleep-dream'); if (d) { try { localStorage.setItem('toto_sleep_dream', d.value) } catch (_) {} } })
    // borrowed from the food log: nav re-renders ONLY the tiles + night columns (keeps scroll + the entry form)
    const renderTiles = () => { const c = dashBody.querySelector('.sleep-tiles'); if (c) c.innerHTML = sTiles(statsOf(windowNights(current.nights, range, end)), rangeLabel(range, end)) }
    const renderNights = () => { const c = dashBody.querySelector('.sleep-nights'); if (c) c.innerHTML = sNightsHTML(range, end, current.nights) }
    // ── editable clinical notes (you OR the AI write them · clear to delete) + the ＋ manual night entry,
    //    delegated on the (persistent) body so both survive a re-render. times → 12h for the report. ──
    const t12 = v => { if (!v) return ''; const [H, M] = v.split(':').map(Number); if (isNaN(H)) return ''; const ap = H >= 12 ? 'PM' : 'AM'; const h = ((H + 11) % 12) + 1; return h + ':' + String(M).padStart(2, '0') + ' ' + ap }
    // 🖨 the PRINT bean on sleep — the week's nights as a clinician report (Sum's session-prep format)
    function printSleep() {
      const win = windowNights(current.nights, range, end), s = statsOf(win), label = rangeLabel(range, end)
      const strip = h => esc(String(h || '').replace(/<[^>]*>/g, ' ')).trim()
      const rows = win.slice().sort((a, b) => (a.iso < b.iso ? -1 : 1)).map(n =>
        `<tr><td class="d">${esc(n.d)}</td><td class="n">${n.eff || 0}%</td><td class="n">${n.deep || 0}m</td><td class="n">${n.rem || 0}m</td><td class="n">${n.awake ? fmt(n.awake) : '—'}</td><td>${esc(n.out)} – ${esc(n.wake)}${n.note ? '<br>' + esc(n.note) : ''}</td></tr>`
      ).join('') || '<tr><td colspan="6" class="z">no nights in range</td></tr>'
      const now = new Date().toLocaleDateString()
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Sleep Report · ${label}</title><style>${REPORT_CSS}</style></head><body>
        <h1>Sleep Report &mdash; ${label} 🛏️</h1>
        <div class="subtitle">Sum Bhodi  |  Google Fit + Nest Hub radar  &middot;  generated ${now}</div>
        <hr>
        <table class="scope">
          <tr><th>THIS WEEK &mdash; Sleep Summary</th><th class="t">Value (avg)</th></tr>
          <tr><td>Sleep efficiency</td><td class="t">${s.eff}%</td></tr>
          <tr class="${s.deep < 90 ? 'note' : ''}"><td>Deep sleep / night</td><td class="t">${s.deep} min (goal 90&ndash;120)</td></tr>
          <tr><td>REM / night</td><td class="t">${s.rem} min</td></tr>
          <tr class="${s.awake > 60 ? 'note' : ''}"><td>Awake in bed / night</td><td class="t">${fmt(s.awake)}</td></tr>
          <tr><td>Nights recorded</td><td class="t">${s.count}</td></tr>
        </table>
        <h2>📊 What the numbers mean</h2>
        <ul>
          <li><b>Efficiency &mdash;</b> time asleep ÷ time in bed; below ~85% means restless or fragmented nights.</li>
          <li><b>Deep sleep &mdash;</b> the restorative stage, goal 90&ndash;120 min. ${s.deep < 90 ? 'Currently below target.' : 'On target.'}</li>
          <li><b>Awake in bed &mdash;</b> time lying awake — high values point to onset latency / fragmentation.</li>
        </ul>
        ${s.deep < 90 ? '<div class="warn">⚠ Deep sleep is averaging below the 90-min target this week.</div>' : ''}
        <h2>📅 Night by night</h2>
        <table class="days"><thead><tr><th>Night</th><th style="text-align:right">Eff</th><th style="text-align:right">Deep</th><th style="text-align:right">REM</th><th style="text-align:right">Awake</th><th>Lights out &ndash; wake</th></tr></thead><tbody>${rows}</tbody></table>
        ${(strip(notes.pattern) || strip(notes.toto)) ? `<h2>📝 Notes</h2><div class="notes-box">${strip(notes.pattern)}${strip(notes.toto) ? '<br><br>' + strip(notes.toto) : ''}</div>` : ''}
        <div class="foot">Prepared with toto &middot; Google Fit + Nest Hub Soli radar + Govee, shared with consent.<br>This report covers <b>${label}</b>. Pair with the activity + nutrition reports for the full picture.</div>
      </body></html>`
      wellnessPrint(html)
    }
    dashBody.addEventListener('focusout', e => {
      const nt = e.target.closest('.dash-note[contenteditable]'); if (!nt) return
      if (!nt.textContent.trim()) nt.innerHTML = ''        // clear stray <br> → the placeholder shows
      notes[nt.dataset.note] = nt.innerHTML                // persist the edit (or the AI's write) across re-renders
    })
    dashBody.addEventListener('click', e => {
      const sh = e.target.closest('.dash-sub-head'); if (sh) { e.stopPropagation(); const k = sh.dataset.sub; subOpen[k] = !subOpen[k]; applySubs(); return }   // (Sum 2026-08-17) INDEPENDENT — you used to have to open one to collapse the other
      const pp = e.target.closest('.sleep-print'); if (pp) { e.stopPropagation(); printSleep(); return }
      // ✕ close the onset-latency section — great demo, but it's Sum's data + editorial; a real user can dismiss it
      const lx = e.target.closest('.sleep-lat-x'); if (lx) { e.stopPropagation(); showLat = false; const blk = lx.closest('.dash-block'); if (blk) blk.remove(); return }
      // the food-log nav — jump to latest · pick a range · slide one night ←/→ (partial re-render)
      const tdy = e.target.closest('[data-today]'); if (tdy) { e.stopPropagation(); end = todayIso(); renderTiles(); renderNights(); return }   // jump to the REAL current week
      const arr = e.target.closest('.fc-arrow'); if (arr) { e.stopPropagation(); end = dShiftIso(end, +arr.dataset.arrow); renderTiles(); renderNights(); return }   // ← / → page whole weeks (±7)
      const snap = e.target.closest('.fc-att')   // 📸/🖥️/📎 → the wellness bot's attach engine
      if (snap) { e.stopPropagation(); ozSnapTo('wellness', snap.dataset.att); return }
      const add = e.target.closest('.se-add'); if (!add) return
      e.stopPropagation()
      const g = k => { const i = dashBody.querySelector('.se-in[data-k="' + k + '"]'); return i ? i.value.trim() : '' }
      const date = g('date')
      if (!date) { add.textContent = '↑ choose a night first'; setTimeout(() => { add.textContent = '＋ add night' }, 1800); return }
      const dreamVal = (() => { const d = dashBody.querySelector('.sleep-dream'); return d ? d.value.trim() : '' })()   // tonight's dream rides into the night
      const night = normalizeNight({ date, out: t12(g('lightsoff')) || t12(g('inbed')) || '—', wake: t12(g('out')) || t12(g('alarm')) || '—',
        eff: g('eff'), deep: g('deep'), rem: g('rem'), awake: g('awake'),
        inbed: t12(g('inbed')), lightsoff: t12(g('lightsoff')), alarm: t12(g('alarm')), outbed: t12(g('out')), onset: g('onset'), light: g('light'), note: dreamVal, manual: true })
      current = { week: current.week, primary: current.primary, nights: current.nights.concat(night) }
      saveNights(current.nights)   // PERSIST — manual nights survive reload now (the refactor)
      try { localStorage.removeItem('toto_sleep_dream') } catch (_) {}   // the dream now lives on the night → the textarea clears, the 48h view shows it
      end = latestIsoOf(current.nights); renderReport()   // jump to the new night + recompute the tiles
    })
    const panel = document.createElement('div'); panel.className = 'sleep-setup'; panel.hidden = true
    panel.innerHTML = PROFILE_HTML + SETUP_HTML + `<div class="ls-close-row"><button class="ls-close sleep-setup-x">✕ close settings</button></div>`
    el.querySelector('.card-body').appendChild(panel)   // into the BODY (not the whole card) → the head + ⚙️ gear stay visible, so the gear toggles it
    // GLOBAL settings rule: settings OR content. opening the panel hides the card's data; ✕ at the bottom (or the gear) brings it back.
    const spSetOpen = on => {
      const cb = el.querySelector('.card-body')
      ;[...cb.children].forEach(n => { if (n !== panel) { n.hidden = on; n.style.display = on ? 'none' : '' } })
      panel.hidden = !on
      if (on) el.classList.remove('collapsed')   // if the wellness station was collapsed, open it so the panel shows
      cb.style.height = 'auto'; cb.style.overflow = 'visible'   // panel flows → body grows to it, the desk scrolls
      if (on) spLoad()
    }
    const fileIn = panel.querySelector('.sleep-setup-file'), msg = panel.querySelector('.sleep-setup-msg')

    // ── sleep profile: load from localStorage, save on button click ──
    const SP_KEY = 'toto_sleep_profile'
    const spFields = () => panel.querySelectorAll('[data-k]')
    const spLoad = () => {
      try {
        const p = JSON.parse(localStorage.getItem(SP_KEY) || '{}')
        spFields().forEach(f => { if (p[f.dataset.k] != null) f.value = p[f.dataset.k] })
      } catch (_) {}
    }
    const spSave = () => {
      const p = {}; spFields().forEach(f => { if (f.value.trim()) p[f.dataset.k] = f.value.trim() })
      localStorage.setItem(SP_KEY, JSON.stringify(p))
      const m = panel.querySelector('.sp-msg'); if (m) { m.textContent = '✓ saved'; setTimeout(() => { m.textContent = '' }, 1800) }
    }
    panel.addEventListener('click', e => { if (e.target.closest('.sp-save')) { e.stopPropagation(); spSave() } })

    gear.addEventListener('click', e => { e.stopPropagation(); spSetOpen(panel.hidden) })
    panel.addEventListener('click', e => {
      e.stopPropagation()
      if (e.target.closest('.sleep-setup-x')) { spSetOpen(false); return }
      if (e.target.closest('.sleep-imp')) fileIn.click()
    })
    fileIn.addEventListener('change', async () => {
      const f = fileIn.files[0]; fileIn.value = ''; if (!f) return
      try {
        msg.className = 'sleep-setup-msg'; msg.textContent = 'parsing ' + f.name + '…'
        const R = await parseImport(f)
        current = R; saveNights(R.nights); notes = { pattern: '', toto: '' }; range = 7; end = latestIsoOf(R.nights); renderReport()   // PERSIST the import → survives reload + the AI can read it (window.sleepNights)
        if (badge) { badge.textContent = 'imported'; badge.title = R.nights.length + ' nights imported · parsed in your browser · notes cleared for your data' }
        msg.className = 'sleep-setup-msg ok'; msg.textContent = '✓ imported ' + R.nights.length + ' nights from ' + f.name + ' — the report above is now yours.'
      } catch (err) {
        console.error('[sleep import]', err)
        msg.className = 'sleep-setup-msg warn'; msg.textContent = '⚠ ' + (err.message || 'could not read that file') + ' — tell me its format and I’ll map it.'
      }
    })
    return el
  }

