// links.js — the one road OUT. In a plain browser, <a target="_blank"> and window.open just work; inside
// the Tauri webview they're DEAD (the webview refuses to navigate to external origins or spawn _blank),
// so every "get a key ↗", Printful, FUPM and Square link silently does nothing. This is the single fix:
// catch any external-link click (capture phase, before the card's own handlers) and hand the URL to Rust's
// open_url, which opens it in the user's real browser/Mail. In a browser (dev), we fall back to window.open.
//
// Loaded FIRST in index.html so the listener is live before any card paints. Cards need no changes — they
// keep writing ordinary <a href> anchors. window.OZ_OPEN(url) is exposed for code that opens links directly.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the TOOL ROAD (Sum 2026-07-23: "you can ....... search: "the TOOL ROAD (Sum"
//   the SAY ROAD (Sum 2026-07-27: "just talk to ... search: "the SAY ROAD (Sum"
//   the FS RELOAD — the courier's missing half .... search: "the FS RELOAD — the"
//   ONE INPUT PATH — AND IT ALREADY EXISTED ....... search: "ONE INPUT PATH — AND IT"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for intercepting external links in the
//    **Tauri webview and routing them to the native browser. It exports `window.OZ_OPEN(url)` (the
//    **core link opener), `window.OZ_SPLIT(url)` (split-screen variant), and
//    **`window.OZ_PORT_IN(json)` (the wire protocol handler for loopback commands from external
//    **agents).
//
//    **TOUCH HERE** —
//    - Change which URL schemes count as external → `EXTERNAL` regex L12
//    - Change the Tauri invoke path or add a fallback → `ozOpen()` L18–26
//    - Add a new loopback command type (tool, say, fs, html) → `OZ_PORT_IN()` L45, add a new `if
//    - (p.newCommand)` block before L181
//    - Change how split-screen tiles → `OZ_SPLIT()` L31–40
//    - Change the click interception logic (modifiers, target selector) → event listener L190–203
//    - Change which file extensions count as "doc" vs "code" in sandbox reload → L81
//
//    **TRAPS** —
//    - `window.OZ_OPEN` and `window.OZ_SPLIT` are called by external code (cards, share-gag);
//    - renaming breaks callers silently.
//    - `window.OZ_PORT_IN` is the wire protocol entry point; the JSON shape (`p.tool`, `p.say`,
//    - `p.fs`, `p.html`) is a contract with external agents (Claude, Port extension). Changing
//    - field names orphans running agents.
//    - `EXTERNAL` regex L12 must match before any handler runs; if it's too loose, in-app links
//    - escape; if too tight, external links are trapped.
//    - The click listener L190 runs in capture phase before card handlers; if you add
//    - `e.preventDefault()` elsewhere, this one may not fire.
//    - `window.confer()` is assumed to exist; if it's not
//    - loaded, the fallback path L128–179 runs silently instead.
//    - The sandbox reload L72–87 mutates `window.SANDBOX` directly; if the shape changes, bots
//    - reading it will see stale data until restart.
//    - `window.TOOL_USE[p.tool]` L55 and `window.OZ_CLI` L131 are optional; missing them doesn't
//    - error, just degrades.
//
//    **DO NOT** —
//    - Don't move the IIFE load order; it must run before cards paint (comment L7).
//    - Don't change the `_open` capture L13; it must happen before `window.open` is patched L207.
//    - Don't add new global state here; use `window.SANDBOX` or `window.TOOL_USE` (defined
//    - elsewhere).
//    - Don't add UI or user prompts; this file is silent-by-design (errors go to console only, L22,
//    - L36).
//    - Don't add new Tauri invokes without checking `inTauri()` first; the file must work in plain
//    - browsers.
//    - Don't change the receipt/reply write paths L57, L92, L95 without coordinating with the
//    - external agent that reads them (Claude, Port extension).
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  // schemes that leave the app. relative / #hash / file: / about:blank / javascript: are IN-app — left alone.
  const EXTERNAL = /^(https?:|mailto:|sms:|tel:)/i
  const _open = window.open.bind(window)   // the real window.open, captured before we patch it below

  function inTauri() { return !!(window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__.invoke)) }

  // the actual open. native → Rust whitelist (open_url); browser → a real new tab. never throws.
  function ozOpen(url) {
    if (!url || !EXTERNAL.test(url)) return false
    if (inTauri()) {
      const invoke = (window.__TAURI__.core && window.__TAURI__.core.invoke) || window.__TAURI__.invoke
      Promise.resolve(invoke('open_url', { url })).catch(e => console.warn('[links] open_url failed', url, e))
      return true
    }
    try { return !!_open.call(window, url, '_blank', 'noopener') } catch (_) { return false }
  }
  window.OZ_OPEN = ozOpen

  // OZ_SPLIT — open a link in the browser AND tile it beside 0z (Sum 2026-07-22: "split screen native
  // mac"). 0z snaps left (win_tile), Chrome opens + tiles right (split_open). any failure → a plain open.
  // ⚠ THE LINK THAT NEVER OPENED (Sum 2026-08-22): split_open runs osascript, and the first time macOS asks
  //    whether 0z may control Chrome, osascript BLOCKS on that dialog — while win_tile, fired at the same
  //    moment, pulled 0z back in front of it. The reader saw nothing open. So: the plain open is the floor
  //    (2.5s and the link opens regardless), and 0z tiles only AFTER Chrome confirms it took the page.
  window.OZ_SPLIT = function (url) {
    if (!url || !EXTERNAL.test(url)) return false
    if (inTauri()) {
      const invoke = (window.__TAURI__.core && window.__TAURI__.core.invoke) || window.__TAURI__.invoke
      let settled = false
      const plain = why => { if (settled) return; settled = true; console.warn('[split] plain open:', why); ozOpen(url) }
      const timer = setTimeout(() => plain('no answer from Chrome in 2.5s'), 2500)
      Promise.resolve(invoke('split_open', { url }))
        .then(() => { clearTimeout(timer); if (settled) return; settled = true; Promise.resolve(invoke('win_tile', { side: 'left' })).catch(() => {}) })
        .catch(e => { clearTimeout(timer); plain(e) })
      return true
    }
    return ozOpen(url)
  }

  // ② the road IN — the Port chrome extension POSTs a logged-in tab's DOM to the native receiver
  //    (127.0.0.1:8787/port); Rust hands the JSON here. we open it in the Portal, cleaned. this is the
  //    "game over" (Sum 2026-07-22): the browser's already past the wall, so it just hands 0z the page.
  window.OZ_PORT_IN = function (json) {
    let p
    try { p = typeof json === 'string' ? JSON.parse(json) : json } catch (_) { return }
    if (!p) return
    // ── the TOOL ROAD (Sum 2026-07-23: "you can test this, no need me") — a loopback POST can drive any
    //    registered tool bean, same hands the newsie has: {"tool":"psv_toggle","what":"bbc","on":false}.
    //    the RESULT lands on disk as a receipt (sandbox_write → ~/totoII/sandbox/port/receipt.json), so an
    //    outside agent can call → read back → verify, a full loop with no human relay. loopback-only trust
    //    (the receiver binds 127.0.0.1); green-press gates inside write-class strikes still hold. ──
    // ⛔⛔ THE TOOL ROAD IS CLOSED — 1 Sep 2026, Sum's call, and the reason is the whole design.
    //  His words: "can we remove the back door you used, that I couldn't see please? Just keep front
    //  door in convo window — glass box."
    //  ⚠ THE ROAD WORKED PERFECTLY AND THAT WAS THE PROBLEM. Claude drove yt_transcript and
    //  learn_write_snippet through it all morning; both fired, both wrote, both returned honest
    //  receipts — and NOTHING APPEARED IN HIS CHAT. main.js portDeliver is explicit: "Tool calls run
    //  silent; say/fs raise the glass." That silence was deliberate (see the 23 Jul note below) and
    //  it hid a real bug for twenty minutes: the learn card was not repainting on a tool write, and
    //  neither of us could see that the writes were even happening.
    //  ⭐ THE GLASS BOX IS THE HOUSE LAW. AIOLI relays bot-to-bot turns into the human's stream on
    //  purpose — "a bot-to-bot conversation is something the human WATCHES, not something behind
    //  them." An outside agent driving tools invisibly is the one road that broke that law, and it
    //  broke it for the caller's convenience.
    //  ⭐ THE SAY ROAD DOES EVERYTHING THIS DID, IN THE OPEN. {"say":{"to":"tutor","text":"…"}} goes
    //  through window.confer — it lands in the bar, it is watched, and the bot fires its own tools
    //  under its own permissions and its own goalies. Nothing is lost except the invisibility.
    //  ⚠ NOT DELETED — REFUSED, and the 23 Jul note stays below it. Corrections attach. If a use ever
    //  needs it back (a headless test rig, a cron), the refusal is one comment away and the road
    //  underneath is untouched. Do not re-open it for convenience; convenience is what it cost.
    // ⭐ CORRECTION 1 Sep 2026, 22:35 — TWO DOORKNOBS, NOT A DOOR (Sum: "1 yes" · "you should have a
    //    button for that too"). Everything above stays true: bot work goes through SAY, in the open. But
    //    the SAY road's own error message tells the caller to open the bot with {"tool":"ui_open"} — and
    //    that pointed at this refusal. A door whose sign points at a bricked door. So exactly two tools
    //    pass: ui_open (dock/undock a card or bot — the act IS visible, a bar appears on his desk) and
    //    factory_reset (human-only, needs confirm:"wipe", reloads the app in front of him). Neither runs a
    //    bot, neither writes a file, neither can be silent. Every other tool still bounces below. The
    //    allowlist is the wall; add to it out loud or not at all.
    // ⭐ THE LOCK (Sum 2 Sep 2026: "we have to close this door on the downloads, or lock and encrypt it"). The knobs
    //    turn only with the key in `port/knob.key` — a random file that lives on THIS machine and ships with no
    //    build (the DMG's sandbox has no such file → every knob is closed there, same as before 1 Sep). A caller
    //    sends `"key"` with the request; no key on disk, or a wrong one, and the tool road is the wall it was.
    //    Third knob: inj_set_model — move a bot between models without a hand on the picker (factory_reset wipes
    //    the picks; on local-model days the rig needs to put them back).
    const PORT_KNOBS = { ui_open: 1, factory_reset: 1, inj_set_model: 1, hil_press: 1 }   // hil_press 2 Sep: the rig's finger
    const knobKey = (() => { try { const f = window.SANDBOX && window.SANDBOX['port/knob.key']; return f && typeof f.data === 'string' ? f.data.trim() : '' } catch (_) { return '' } })()
    const sentKey = typeof p.key === 'string' ? p.key : (p.say && typeof p.say.key === 'string' ? p.say.key : '')   // the key may ride top-level or inside say
    const unlocked = !!knobKey && !!sentKey && sentKey.trim() === knobKey
    if (p.tool && PORT_KNOBS[p.tool] && !unlocked) {
      try { const c0 = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
            c0 && c0.invoke && c0.invoke('sandbox_write', { name: 'port/receipt.json', content: JSON.stringify({ tool: p.tool, at: Date.now(), result: 'LOCKED — the doorknobs need the key in port/knob.key (this machine only; no build ships one). Send it as "key".' }) }) } catch (_) {}
      return
    }
    if (p.tool && PORT_KNOBS[p.tool] && window.TOOL_USE && window.TOOL_USE[p.tool] && window.TOOL_USE[p.tool].run) {
      ;(async () => {
        let result
        try { window.OZ_ACTOR = 'port'; result = await window.TOOL_USE[p.tool].run(p) } catch (e) { result = p.tool + ' errored: ' + ((e && e.message) || e) } finally { window.OZ_ACTOR = null }
        try { const c0 = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
              c0 && c0.invoke && c0.invoke('sandbox_write', { name: 'port/receipt.json', content: JSON.stringify({ tool: p.tool, at: Date.now(), result: String(result) }) }) } catch (_) {}
      })()
      return
    }
    if (p.tool) {
      try {
        const c0 = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
        c0 && c0.invoke && c0.invoke('sandbox_write', { name: 'port/receipt.json', content: JSON.stringify({
          tool: p.tool, at: Date.now(),
          result: 'REFUSED — the tool road is closed (1 Sep 2026); only ui_open and factory_reset pass (the two doorknobs, 1 Sep 22:35). It ran silently and the human could not see it. '
                + 'Use the SAY road instead: {"say":{"to":"<bot>","text":"…"}} — it lands in the bar, in the open, '
                + 'and the bot fires its own tools under its own goalies. links.js has the why.' }) })
      } catch (_) {}
      try { console.warn('[port] tool road REFUSED — use {"say":{…}}; see links.js') } catch (_) {}
      return
    }
    // ── the SAY ROAD (Sum 2026-07-27: "just talk to coder, get its output back") — a loopback POST talks to
    //    a BOT and writes its reply to disk, so Claude (or any outside agent) converses with an agent with NO
    //    human relay: {"say":{"to":"coder","text":"…"}}. reply → ~/totoII/sandbox/port/reply.json (sandbox_write),
    //    same receipt loop as the tool road above. loopback-only (the receiver binds 127.0.0.1). ──
    // ── the FS RELOAD — the courier's missing half (Sum 2026-07-27: "where is brahman"). Claude drops files
    //    straight to ~/totoII/sandbox over Bash, but the bots read window.SANDBOX, which hydrates from disk
    //    ONCE at boot — so a couriered file is invisible in-app until a restart (two maps of one folder, the
    //    ghosting that ate the night). {"fs":"reload"} re-reads disk into the cache on demand: one curl and
    //    coder sees what the courier just wrote. unchanged files are skipped so the proxy doesn't echo-write.
    if (p.fs === 'reload') {
      const fc = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
      if (fc && fc.invoke) {
        Promise.resolve(fc.invoke('sandbox_load_all')).then(map => {
          let n = 0
          Object.keys(map || {}).forEach(name => {
            const data = String(map[name]), cur = window.SANDBOX && window.SANDBOX[name]
            if (cur && cur.data === data) return
            const ext = (name.split('.').pop() || '').toLowerCase()
            window.SANDBOX[name] = { kind: ['md', 'txt', 'rtf'].includes(ext) ? 'doc' : 'code', ext, mime: '', data }
            n++
          })
          try { fc.invoke('sandbox_write', { name: 'port/reload.json', content: JSON.stringify({ at: Date.now(), synced: n }) }) } catch (_) {}
        }).catch(() => {})
      }
      return
    }

    if (p.say && p.say.to && p.say.text) {
      const c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
      const stamp = Date.now()
      const write = (name, obj) => { try { c && c.invoke && c.invoke('sandbox_write', { name, content: JSON.stringify(obj) }) } catch (_) {} }
      // ⭐ 2 Sep 2026 — SAY AS THE HUMAN, key-locked. The consult framing ("you are being consulted by claude") is right
      //    for bot-to-bot and wrong as a TEST of what a human gets: the nurse stopped to ask who was talking, the
      //    traveler handed back specs. With the knob key and as:"human", the text goes down the SAME road the Enter
      //    key uses (window.ozRunTurn → runTurn → conduct, src human): sniff runs, the thesaurus tells and chips run,
      //    the reply lands in the bar as a typed turn would. No key on disk (every download) → this branch never runs.
      if (p.say.as === 'human' && unlocked && window.ozRunTurn) {
        const land = (t, r) => { const rec = { at: stamp, to: p.say.to, as: 'human', sent: p.say.text, rounds: r, reply: String(t) }; write('port/reply.json', rec); write('port/say-' + stamp + '.json', rec) }
        ;(async () => {
          try { const r = await window.ozRunTurn(p.say.to, p.say.text, { echo: true }); land((r && (r.text || r.error)) || '(no reply)', 1) }
          catch (e) { write('port/reply.json', { at: stamp, to: p.say.to, as: 'human', sent: p.say.text, error: String((e && e.message) || e) }) }
        })()
        return
      }
      // reply.json = latest (Claude polls it); say-<ts>.json = permanent transcript. rounds = how many
      // tool-loop turns it took.
      const land = (t, r) => { const rec = { at: stamp, to: p.say.to, sent: p.say.text, rounds: r, reply: String(t) }; write('port/reply.json', rec); write('port/say-' + stamp + '.json', rec) }
      // ══ ONE INPUT PATH — AND IT ALREADY EXISTED (Sum 2026-07-30) ═════════════════════════════
      //  I hand-carved a "SPEAKER" preamble to stop the wire impersonating the human. Sum: "you're
      //  doing it again. you're hand carving something we already built... when bots talk to each
      //  other within oz, they already have a way to talk to each other that should show up in my
      //  chat box." Correct, and the proof was already on his screen: CODER CALLS ME BLEEP.
      //
      //  The real mechanism is window.confer(from, to, brief, ui, signal) — conductor.js:696. It
      //  already does all four things I was reinventing:
      //    · FRAMES the speaker — "You are being consulted by <from>, another agent, NOT the user"
      //    · gates it by the celestial order (canConfer: down or lateral, never up)
      //    · RELAYS the sub-agent's turns into the caller's stream, tagged 'confer' — the glass box,
      //      so a bot-to-bot conversation is something the human WATCHES, not something behind them
      //    · passes src='ai' to conduct(), which is how the climate log knows a human didn't type
      //
      //  So the wire stops being a second road and becomes what it always was: bleep, conferring.
      const from = p.say.as || 'claude'   // the consultant, not bleep — bleep is the joke bot, rank 2
      const hostBar = document.querySelector('.agent-bar[data-agent="' + from + '"]')
                   || document.querySelector('.agent-bar[data-agent="' + p.say.to + '"]')
      if (window.confer && hostBar && window.chatUI) {
        ;(async () => {
          try {
            const screen = hostBar.querySelector('.convo-screen'), stream = hostBar.querySelector('.msg-stream')
            const r = await window.confer(from, p.say.to, p.say.text, window.chatUI(screen, stream, from), null)
            const reply = (r && (r.text || r.error)) || '(no reply)'
            land(reply, 1)
            // ⭐ hand it back to a caller that asked to WAIT (main.js ?wait=1). A no-op when nobody
            //   is listening, which is every existing caller — so this line cannot change today's
            //   behaviour for the port, the CLI or the courier. The disk receipt above is untouched.
            try { if (window.__OZ_PORT_ANSWER) window.__OZ_PORT_ANSWER(reply) } catch (_) {}
          } catch (e) { write('port/reply.json', { at: stamp, to: p.say.to, sent: p.say.text, error: String((e && e.message) || e) }) }
        })()
        return
      }
      // ⭐ ONE DOOR (Sum 2026-08-25: "remove all other doors to talk to bots ... do not make any more").
      //    No bar docked means there is no stream to relay into, so there is nothing to watch — and being
      //    watched is the entire reason this road is the road. The old wire loop that used to run here
      //    answered anyway, behind him, and wrote a note admitting it. That note is now the whole response.
      //    THE-FRONT-DOOR.md has said the rule since 20 Aug: the bot must be open and docked before you knock.
      write('port/reply.json', { at: stamp, to: p.say.to, sent: p.say.text, error: 'no docked bar for "' + from + '" or "' + p.say.to + '" — nothing ran. Open the bot first ({"tool":"ui_open","card":"' + p.say.to + '"}) and knock again.' })
      return
    }
    const R = window.OZ_READER
    if (!R) return
    if (p.html && R.readHTML) R.readHTML(p.html, p.url || '')
    else if (p.url && R.read) R.read(p.url)
  }

  // ① intercept clicks on real anchors. capture phase + closest() so it works no matter how deep, and
  //    BEFORE per-card click handlers. We swallow ALL external anchors (not just target=_blank): a bare
  //    external href would otherwise try to navigate the whole webview away from oz and white-screen it.
  document.addEventListener('click', e => {
    if (e.defaultPrevented || e.button !== 0 || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return
    const a = e.target && e.target.closest && e.target.closest('a[href]')
    if (!a) return
    // the Portal reader OWNS links inside its article body — it keeps them IN the Portal (read()). don't
    // ALSO route them out here, or a nested click fires twice: one browser tab + one in-Portal nav (Sum
    // 2026-07-27: "still opening double links instead of in portal pages"). the reader's OWN route-out
    // anchors ("original ↗", "open on host ↗") live in .rdr-bar, not .rdr-body, so they still reach here.
    if (a.closest('.rdr-body')) return
    const href = a.getAttribute('href') || ''
    if (!EXTERNAL.test(href)) return
    e.preventDefault()
    ozOpen(a.href)   // a.href is the resolved absolute URL
  }, true)

  // ② patch window.open so existing code paths (share-gag → Printful) reach the browser too. Only external
  //    http(s)/mailto/… URLs are rerouted; blank/in-app opens (webview.js's print window) pass through.
  window.open = function (url, ...rest) {
    if (typeof url === 'string' && EXTERNAL.test(url) && inTauri()) { ozOpen(url); return null }
    return _open(url, ...rest)
  }
})()
