// clipboard.js — the 📋 SESSION-PREP CLIPBOARD. the nurse's second surface (in addition to the injection
// config): a clinical clipboard that holds ONE living prep sheet — the page you fill before an appointment
// and print to bring. browser-native (localStorage 'toto_prep'), no server. the TEMPLATE is the shape;
// the INPUT is what you type into it. the section flow (scope → say-first → topics → snapshot → if-they-ask
// → bring) is modeled on a real session-prep doc's flow/brevity/vibe — terse bullets, ⚠ flags, prepared
// answers — so a blank sheet already teaches the right shape. the nurse reads it via read_prep and fills it
// section by section via the granular prep_* tools (shell/tools.js); edits here and edits there are the same doc.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   OVERVIEW — three WHOLE-FILE docs (not ........ search: "OVERVIEW — three"
//   COMPLAINTS — folders (body systems + ......... search: "COMPLAINTS — folders"
//   QUICK GUIDES — survival cheat-sheets (one .... search: "QUICK GUIDES — survival"
//   PREP (the session sheet — the page the ....... search: "PREP (the session sheet"
//   saved SESSIONS — a row of past prep sheets ... search: "saved SESSIONS — a row"
//   the discipline chips — quick-set the kind .... search: "the discipline chips"
//   the chart's tab dividers — Overview .......... search: "the chart's tab"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The clipboard card's data model, persistence, and UI rendering. Exports
//    **`window.CARD_BUILDERS.clipboard` (the card factory at line 572), `window.prepSaveSession`
//    **(the session-save path at line 128), and fires `toto-prep-changed` events (line 83) that
//    **other cards listen to. The prep doc shape (lines 19–34) is the contract: any code reading
//    **`toto_prep` or `toto_prep_hil` from localStorage depends on this structure staying stable.
//
//    **TOUCH HERE** —
//    - Add a new section to the prep sheet → add a key to `prepFresh()` (line 18), a row to
//    - `prepIsEmpty()` (line 38), a render block in `renderPrep()` (line 246), and a leaf template
//    - in `prepNewLeaf()` (line 369).
//    - Change the complaint folder taxonomy → edit `COMPLAINT_FOLDERS` (line 170) and update
//    - `specToFolder()` (line 53) to route old data.
//    - Add a discipline chip option → edit `PREP_DISCIPLINES` (line 136).
//    - Change what prints → edit `prepPrint()` (line 383).
//    - Change the overview docs (presentation / perspective / co-morbidity) → edit `OV_DOCS` (line
//    - 152) and `OV_PH` (line 153).
//    - Change the chart tabs (overview · complaints · guides · prep) → edit `CHART_TABS` (line
//    - 144).
//    - Alter how a session is labeled or saved → edit `sessLabel()` (line 98) or `prepToText()`
//    - (line 101).
//
//    **TRAPS** —
//    - The prep doc shape (lines 19–34) is persisted to localStorage. Renaming or removing a key
//    - orphans user data. Migrations exist for old `presents` → `presentation` (line 62) and old
//    - `complaints[{complaint,specialist}]` → new shape (lines 64–65), but new shape changes need a
//    - migration path.
//    - `prepKey()` (line 70) determines which localStorage key is used (`toto_prep` for AI,
//    - `toto_prep_hil` for human). The two sides are separate docs; switching sides (line 468)
//    - loads a different doc entirely.
//    - `prepIsEmpty()` (line 38) gates whether a blank doc shows the worked demo (line 78). If you
//    - add a section, you must add its emptiness check or blank sheets will seed the demo
//    - unexpectedly.
//    - Sessions are stored in `toto_prep_sessions` (line 95) AND mirrored as nurse notes in
//    - `toto_notes` (line 120). A save must do both (line 131); a delete must do both (line 545).
//    - Missing either breaks the sync.
//    - The click handler (line 463) is delegated and order-sensitive. New buttons must have unique
//    - `data-*` attributes and be checked before generic `.clip-chip` (line 537) or they'll fall
//    - through to the wrong handler.
//    - `autoGrow()` (line 443) caps textarea height differently for `.clip-doc` (whole-file docs,
//    - 6000px) vs others (360px, line 446). Changing this breaks layout for long overview docs.
//    - `renderSheet()` (line 237) dispatches to four render functions based on `ui.tab`. If you add
//    - a tab, add a branch here.
//
//    **DO NOT** —
//    - Do not rename `prepFresh()`, `prepGet()`, `prepSet()`, `prepPath()`, `cmpId()`, `sessId()` —
//    - they are the stable API that shell/tools.js and the nurse's beans call.
//    - Do not move the `toto-prep-changed` event (line 83) or the listener (line 561) — they are
//    - the bridge between the clipboard card and external edits (beans, watcher).
//    - Do not change the localStorage key names (`toto_prep`, `toto_prep_hil`,
//    - `toto_prep_sessions`, `toto_notes`) without a migration strategy.
//    - Do not edit the HTML structure of the print output (lines 400–423) without checking that CSS
//    - in the print stylesheet still applies.
//    - Do not add new fields to the prep doc without updating `prepIsEmpty()` — it will break the
//    - demo-seeding logic.
//    - Do not move complaint or guide logic into a separate file — they are tightly coupled to the
//    - render and click handlers here. Session loading (lines 95–96, 129–131, 543, 545) is also
//    - clipboard-specific and should stay.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


window.CARD_BUILDERS = window.CARD_BUILDERS || {}

function prepEsc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }

// the blank template — one empty row per section, so a fresh sheet shows its skeleton. placeholders (below)
// carry the guidance; the values stay empty until you fill them. nurse + HIL share this one doc.
// a stable id for a complaint file (cross-filing needs identity, not array position)
function cmpId() { return 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 5) }

function prepFresh() {
  return {
    // ── OVERVIEW — three WHOLE-FILE docs (not boxes), switched by a sub-bar ──
    patient: '', presentation: '', perspective: '', comorbidity: '',
    // ── COMPLAINTS — folders (body systems + environmental) holding files; cross-filed; NEVER a diagnosis ──
    complaints: [],
    // ── QUICK GUIDES — survival cheat-sheets (one protocol per card) ──
    guides: [],
    // ── PREP (the session sheet — the page the patient prints + brings) ──
    discipline: '', date: '', seeing: '',
    sayFirst: '',
    scope:    [{ item: '', time: '' }],
    topics:   [{ heading: '', bullets: [''], flags: [''] }],
    snapshot: [{ domain: '', rating: '', evidence: '' }],
    qa:       [{ q: '', a: '' }],
    bring:    [''],
  }
}
// is a doc's BODY blank? (discipline/date/seeing are just a label — a real prep needs a say-first or a section)
// → treat label-only docs like unsaved, so the worked sample shows instead of an empty shell.
function prepIsEmpty(d) {
  if (!d) return true
  if ((d.patient || '').trim() || (d.presentation || '').trim() || (d.perspective || '').trim() || (d.comorbidity || '').trim()) return false
  if ((d.complaints || []).some(c => (c.title || '').trim() || (c.body || '').trim())) return false
  if ((d.guides || []).some(g => (g.title || '').trim() || (g.body || '').trim())) return false
  if ((d.sayFirst || '').trim()) return false
  if ((d.scope || []).some(r => (r.item || '').trim() || (r.time || '').trim())) return false
  if ((d.topics || []).some(t => (t.heading || '').trim() || (t.bullets || []).some(b => (b || '').trim()) || (t.flags || []).some(f => (f || '').trim()))) return false
  if ((d.snapshot || []).some(r => (r.domain || '').trim() || (r.rating || '').trim() || (r.evidence || '').trim())) return false
  if ((d.qa || []).some(r => (r.q || '').trim() || (r.a || '').trim())) return false
  if ((d.bring || []).some(b => (b || '').trim())) return false
  return true
}
// migrate a pre-folders doc (old: presents + complaints[{complaint,specialist}]) → current shape, so stale
// localStorage and saved sessions don't render orphaned. best-effort routes the old free-text specialist to a folder.
function specToFolder(s) {
  s = (s || '').toLowerCase()
  if (/cardio|heart|\bbp\b|blood pressure/.test(s)) return 'cardio'
  if (/neuro|migraine|head|nerve|seizure/.test(s)) return 'neuro'
  if (/ortho|muscul|skelet|\bpt\b|physical|back|joint|edema/.test(s)) return 'msk'
  if (/psych|therap|lcsw|mood|mental|sleep/.test(s)) return 'psych'
  return 'env'
}
function prepMigrate(d) {
  if (d.presents && !d.presentation) d.presentation = d.presents
  delete d.presents
  if (Array.isArray(d.complaints)) d.complaints = d.complaints.map(c =>
    c && 'complaint' in c ? { id: cmpId(), title: c.complaint || '', body: '', folders: [specToFolder(c.specialist)] } : c)
  return d
}
// the chart has two SIDES: 'ai' (the nurse's notes — seeds the worked demo) and 'hil' (the human's own — ships BLANK).
// each persists to its own key; the nurse's beans + watcher use the AI side (toto_prep), the human fills the HIL side.
function prepKey(side) { return side === 'hil' ? 'toto_prep_hil' : 'toto_prep' }
function prepGet(side) {
  side = side || 'ai'
  let saved = null
  try { saved = JSON.parse(localStorage.getItem(prepKey(side)) || 'null') } catch (_) {}
  if (saved && typeof saved === 'object') { saved = prepMigrate(Object.assign(prepFresh(), saved)); if (!prepIsEmpty(saved)) return saved }
  // AI side blank/unsaved → seed the worked mockup (the nurse's notes — the toto demo). HIL side stays blank: the
  // human fills it themselves. type anything on either side and it's yours.
  if (side !== 'hil' && window.DEMO_PREP) { try { return Object.assign(prepFresh(), JSON.parse(JSON.stringify(window.DEMO_PREP))) } catch (_) {} }
  return prepFresh()
}
function prepSet(doc) {
  try { localStorage.setItem('toto_prep', JSON.stringify(doc)) } catch (_) {}
  window.dispatchEvent(new CustomEvent('toto-prep-changed'))   // an open card (or the watcher) re-reads
}
// set a dotted path (scope.2.item, topics.0.bullets.1) into the doc
function prepPath(o, path, val) {
  const ks = path.split('.'); let t = o
  for (let i = 0; i < ks.length - 1; i++) { const k = ks[i]; t = t[/^\d+$/.test(k) ? +k : k] }
  t[ks[ks.length - 1]] = val
}

// ── saved SESSIONS — a row of past prep sheets per provider. each save ALSO drops a NURSE NOTE on the
//    injection config (owner 'nurse', folder 'session-prep'), so the patient's chart carries it AND it's
//    loadable here. the structured doc lives in toto_prep_sessions (to reload); the note is readable text. ──
function loadSessions() { try { const a = JSON.parse(localStorage.getItem('toto_prep_sessions') || '[]'); return Array.isArray(a) ? a : [] } catch (_) { return [] } }
function saveSessions(a) { try { localStorage.setItem('toto_prep_sessions', JSON.stringify(a)) } catch (_) {} }
function sessId() { return 's' + Date.now().toString(36) }
function sessLabel(doc) { const d = new Date().toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); return `${(doc.discipline || '').trim() || 'session'} — ${d}` }

// the readable text the nurse's note carries (the chart injects text, not JSON)
function prepToText(doc) {
  const L = []
  L.push(`${doc.patient || doc.discipline || 'session'} — chart${doc.date ? ' · ' + doc.date : ''}${doc.seeing ? ' · ' + doc.seeing : ''}`)
  if ((doc.presentation || '').trim()) L.push(`presentation: ${doc.presentation}`)
  if ((doc.perspective || '').trim()) L.push(`perspective: ${doc.perspective}`)
  if ((doc.comorbidity || '').trim()) L.push(`co-morbidity: ${doc.comorbidity}`)
  ;(doc.complaints || []).filter(c => (c.title || '').trim() || (c.body || '').trim()).forEach(c => L.push(`complaint [${(c.folders || []).join(', ')}]: ${c.title}${c.body ? ' — ' + c.body : ''}`))
  ;(doc.guides || []).filter(g => (g.title || '').trim() || (g.body || '').trim()).forEach(g => L.push(`quick guide: ${g.title}${g.body ? '\n' + g.body : ''}`))
  if ((doc.sayFirst || '').trim()) L.push(`say first: ${doc.sayFirst}`)
  ;(doc.scope || []).filter(r => r.item || r.time).forEach(r => L.push(`• ${r.item}${r.time ? ' (' + r.time + ')' : ''}`))
  ;(doc.topics || []).forEach(t => { if (t.heading || (t.bullets || []).some(Boolean)) { L.push(`# ${t.heading || ''}`); (t.bullets || []).filter(Boolean).forEach(b => L.push(`  - ${b}`)); (t.flags || []).filter(Boolean).forEach(f => L.push(`  ⚠ ${f}`)) } })
  ;(doc.snapshot || []).filter(r => r.domain).forEach(r => L.push(`${r.domain}: ${r.rating || ''} — ${r.evidence || ''}`))
  ;(doc.qa || []).filter(r => r.q).forEach(r => L.push(`Q: ${r.q}\nA: ${r.a || ''}`))
  ;(doc.bring || []).filter(Boolean).forEach(b => L.push(`bring: ${b}`))
  return L.join('\n')
}
// mirror a session into / out of the nurse's chart notes (toto_notes)
function nurseNoteAdd(id, label, body) {
  let n = []; try { n = JSON.parse(localStorage.getItem('toto_notes') || '[]') } catch (_) {}
  n.push({ folder: 'session-prep', name: 'prep-' + id, display: label, on: false, body, owner: 'nurse' })
  try { localStorage.setItem('toto_notes', JSON.stringify(n)) } catch (_) {}
}
function nurseNoteRemove(id) {
  let n = []; try { n = JSON.parse(localStorage.getItem('toto_notes') || '[]') } catch (_) {}
  try { localStorage.setItem('toto_notes', JSON.stringify(n.filter(x => x.name !== 'prep-' + id))) } catch (_) {}
}
// exposed so the nurse's prep_save bean reuses the EXACT save (a session + a nurse note) the 💾 button uses
window.prepSaveSession = function (doc) {
  const id = sessId(), label = sessLabel(doc), list = loadSessions()
  list.push({ id, discipline: doc.discipline || '', label, savedAt: Date.now(), doc: JSON.parse(JSON.stringify(doc)) })
  saveSessions(list); nurseNoteAdd(id, label, prepToText(doc))
  return label
}

// ── the discipline chips — quick-set the kind of session (free text still wins) ──
const PREP_DISCIPLINES = ['LCSW', 'OT', 'PT', 'PCP', 'Psych', 'Intake']

// a textarea that grows with its text (the sheet has no inner scrollbars — the desk scrolls)
function prepArea(path, val, ph, cls) {
  return `<textarea class="clip-in ${cls || ''}" data-path="${path}" rows="1" placeholder="${prepEsc(ph)}" spellcheck="false">${prepEsc(val)}</textarea>`
}

// ── the chart's tab dividers — Overview · Complaints · Prep. the tabs stay; the body below swaps. ──
const CHART_TABS = [['overview', '📋 overview'], ['complaints', '🩹 complaints'], ['guides', '📑 quick guides'], ['prep', '📝 prep']]
function renderTabs(tab) {
  return `<div class="clip-tabs">${CHART_TABS.map(([id, label]) =>
    `<button class="clip-tab${tab === id ? ' on' : ''}" data-tab="${id}">${label}</button>`).join('')}</div>`
}

// 📋 OVERVIEW — three WHOLE-FILE docs (not boxes), switched by a sub-bar (the prep discipline-chip pattern).
//    each is a full document — exec summary, then sections — the way a real presentation / perspective reads.
const OV_DOCS = [['presentation', '📄 presentation'], ['perspective', '🧭 perspective'], ['comorbidity', '🔀 co-morbidity']]
const OV_PH = {
  presentation: 'PRESENTATION — the whole picture, a document not a line.\nlead with an executive summary, then sections. how they present, what shows in a session.',
  perspective:  'PERSPECTIVE — how it looks from the INSIDE.\ntheir words, their cognitive frame — first-person, not the clinician’s view.',
  comorbidity:  'CO-MORBIDITY — how the complaints OVERLAP.\nthe shared wire under them; which folders feed which.',
}
function renderOverview(doc, ui) {
  const sub = OV_DOCS.map(([id, label]) =>
    `<button class="clip-chip clip-ovsub${ui.ovTab === id ? ' on' : ''}" data-ovsub="${id}">${label}</button>`).join('')
  return `
    <div class="clip-ov-name">${prepArea('patient', doc.patient, 'patient / user name', 'clip-ov-patient')}</div>
    <div class="clip-subbar">${sub}</div>
    <div class="clip-doc-wrap">${prepArea(ui.ovTab, doc[ui.ovTab], OV_PH[ui.ovTab], 'clip-doc')}</div>
    <div class="clip-harness-note">this chart is what the <b>nurse sees</b> — it doesn’t change toto. to change the harness (what toto <i>becomes</i>): 🗂️ injection config · ⚙️ settings.</div>`
}

// 🩹 COMPLAINTS — FOLDERS (body systems + environmental) holding FILES. lay words, NEVER a diagnosis.
//    a complaint can be cross-filed in several folders (edema → musculoskeletal + cardio). the folder IS the routing.
const COMPLAINT_FOLDERS = [
  ['psych', '🧠 psych', 'mood, thought, behavior — what the mind reports'],
  ['cardio', '❤️ cardio', 'heart, blood pressure, circulation'],
  ['msk', '🦴 musculoskeletal', 'bones, joints, muscles, swelling, pain'],
  ['neuro', '⚡ neuro', 'head, nerves, sleep, the wiring'],
  ['env', '🌍 environmental', 'EVERYTHING outside the body — the catch-all. the weather, the president, the noise, entropy itself. any complaint about the universe that fits nowhere else.'],
]
const folderLabel = id => (COMPLAINT_FOLDERS.find(f => f[0] === id) || [, id])[1]
const folderDesc = id => (COMPLAINT_FOLDERS.find(f => f[0] === id) || [])[2] || ''
function renderComplaints(doc, ui) {
  const folders = COMPLAINT_FOLDERS.map(([id, label]) => {
    const n = doc.complaints.filter(c => (c.folders || []).includes(id)).length
    return `<button class="clip-chip clip-folder${ui.cmpFolder === id ? ' on' : ''}" data-folder="${id}">${label}${n ? ` <span class="clip-folder-n">${n}</span>` : ''}</button>`
  }).join('')
  // files in the OPEN folder — iterate the full list (real index i) so paths + delete still resolve.
  const list = doc.complaints.map((c, i) => [c, i]).filter(([c]) => (c.folders || []).includes(ui.cmpFolder)).map(([c, i]) => {
    const tags = COMPLAINT_FOLDERS.map(([fid, flabel]) =>
      `<button class="clip-cfile-tag${(c.folders || []).includes(fid) ? ' on' : ''}" data-cmpfolder="${i}.${fid}" title="file in ${flabel}">${flabel.split(' ')[0]}</button>`).join('')
    return `<div class="clip-cfile">
        <div class="clip-cfile-head">${prepArea(`complaints.${i}.title`, c.title, 'the complaint in plain words — “sleep,” not “insomnia”', 'clip-cfile-title')}<button class="clip-x clip-cfile-x" data-del="complaints.${i}" title="remove">✕</button></div>
        ${prepArea(`complaints.${i}.body`, c.body, 'what they report — their words. when, how often, how bad.', 'clip-cfile-body')}
        <div class="clip-cfile-tags"><span class="clip-cfile-tags-l">files in</span>${tags}</div>
      </div>`
  }).join('')
  const open = folderLabel(ui.cmpFolder)
  return `
    <div class="clip-cmp-note">complaints, not diagnoses — plain words, filed by body system. the folder is the routing; a complaint can live in several (edema → 🦴 + ❤️). never name the condition.</div>
    <div class="clip-subbar">${folders}</div>
    <div class="clip-folder-desc">${folderDesc(ui.cmpFolder)}</div>
    <div class="clip-cfiles">${list || `<div class="clip-cfile-empty">no complaints filed under ${open} yet</div>`}</div>
    <button class="clip-add clip-add-cmp" data-addcmp="1">+ complaint in ${open}</button>`
}

// the TOP LINE — AI / HIL source tabs (left) + the chart's actions (right). sits just above the section tabs.
//   AI  = the AI's notes, written by the nurse (seeded). HIL = the human's own — blanks to fill in.
const CHART_SIDES = [['ai', 'AI'], ['hil', 'HIL']]
function renderTopline(ui) {
  const sides = CHART_SIDES.map(([id, label]) =>
    `<button class="clip-side${ui.side === id ? ' on' : ''}" data-side="${id}" title="${id === 'ai' ? "the AI's notes — the nurse wrote these" : 'your own — blanks to fill in'}">${label}</button>`).join('')
  // ⚠ CORRECTION (Sum 2026-08-29, the release pass: "strip fiction"). A 🤝 "data in" button used to sit
  //    first in clip-acts, opening the device-pairing panel — install a 0z collector, grant HealthKit,
  //    enter a code, sync over wifi. NONE of it was built (no receiver, the code was Math.random into
  //    localStorage, the statuses were hardcoded). Panel parked in _parked/oz-handshake.{js,css}.
  //    The real road into the chart is unchanged: the nurse's prep_* beans, and the 📥 importer for
  //    health exports (cards/dashboards/wellness-import.js).
  return `<div class="clip-topline">
    <div class="clip-sides">${sides}</div>
    <div class="clip-acts">
      <button class="clip-tool clip-print" title="print this chart — Save as PDF or print to a device">🖨 print</button>
      <button class="clip-tool clip-new" title="start a fresh blank sheet (this side)">↺ new sheet</button>
    </div>
  </div>`
}

// 📑 QUICK GUIDES — survival cheat-sheets. nav like overview: a sub-bar of guide titles + an "add" chip; the
//    selected guide opens as a WHOLE-FILE doc (title editable + delete). one protocol per card. ui.guide = index.
function renderGuides(doc, ui) {
  const guides = doc.guides || []
  const note = `<div class="clip-cmp-note">quick guides — cheat sheets you read mid-crisis. one protocol per card: when it happens, here’s what to do. print one and tape it up.</div>`
  const addChip = `<button class="clip-chip clip-add-guide" data-addguide="1">+ add guide</button>`
  if (!guides.length) return `${note}<div class="clip-subbar">${addChip}</div><div class="clip-cfile-empty">no quick guides yet — add one</div>`
  const idx = Math.min(ui.guide || 0, guides.length - 1)
  const sub = guides.map((g, i) =>
    `<button class="clip-chip clip-gsub${i === idx ? ' on' : ''}" data-guide="${i}" title="${prepEsc(g.title || 'untitled')}">${prepEsc(g.title || 'untitled')}</button>`).join('') + addChip
  const g = guides[idx]
  return `${note}
    <div class="clip-subbar">${sub}</div>
    <div class="clip-guide-head">${prepArea(`guides.${idx}.title`, g.title, 'guide title — e.g. “NOT DYING — IT’S THE FAMINE”', 'clip-cfile-title')}<button class="clip-x clip-guide-x" data-del="guides.${idx}" title="remove this guide">✕</button></div>
    <div class="clip-doc-wrap">${prepArea(`guides.${idx}.body`, g.body, 'the cheat sheet. when it happens → what to do.', 'clip-doc')}</div>`
}

// the whole sheet for the active tab: a sticky header (top line + section tabs) + the active section's body below.
function renderSheet(doc, ui) {
  const body = ui.tab === 'overview' ? renderOverview(doc, ui)
    : ui.tab === 'complaints' ? renderComplaints(doc, ui)
    : ui.tab === 'guides' ? renderGuides(doc, ui)
    : renderPrep(doc)
  return `<div class="clip-stick">${renderTopline(ui)}${renderTabs(ui.tab)}</div><div class="clip-tab-body">${body}</div>`
}

// 📝 PREP — the session sheet (the page the patient prints + brings). header → scope → topics → snapshot → Q&A → bring.
function renderPrep(doc) {
  const chips = PREP_DISCIPLINES.map(d => `<button class="clip-chip${doc.discipline === d ? ' on' : ''}" data-disc="${d}">${d}</button>`).join('')
  // past sessions for THIS provider (discipline) — a row of tabs, each loadable + trashable
  const sess = loadSessions().filter(s => (s.discipline || '') === (doc.discipline || ''))
  const sessTabs = sess.map(s => `<span class="clip-sess"><button class="clip-sess-load" data-sess="${s.id}">${prepEsc(s.label)}</button><button class="clip-sess-x" data-trash="${s.id}" title="delete this saved sheet">✕</button></span>`).join('')

  // 🗓 scope — the realistic agenda: what / how long
  const scope = doc.scope.map((r, i) => `<div class="clip-scope-row">
      ${prepArea(`scope.${i}.item`, r.item, 'what we cover — one line', 'clip-scope-item')}
      ${prepArea(`scope.${i}.time`, r.time, '~min', 'clip-scope-time')}
      <button class="clip-x" data-del="scope.${i}" title="remove">✕</button>
    </div>`).join('')

  // 📝 topics — the body. each = a heading + bold-lead bullets + ⚠ flags (things the clinician should note)
  const topics = doc.topics.map((t, ti) => {
    const bullets = t.bullets.map((b, bi) => `<div class="clip-bullet-row">
        <span class="clip-dot">•</span>${prepArea(`topics.${ti}.bullets.${bi}`, b, 'term — the detail in a phrase', 'clip-bullet')}
        <button class="clip-x" data-del="topics.${ti}.bullets.${bi}" title="remove">✕</button>
      </div>`).join('')
    const flags = t.flags.map((f, fi) => `<div class="clip-flag-row">
        <span class="clip-warn">⚠</span>${prepArea(`topics.${ti}.flags.${fi}`, f, 'the thing you need on the record', 'clip-flag')}
        <button class="clip-x" data-del="topics.${ti}.flags.${fi}" title="remove">✕</button>
      </div>`).join('')
    return `<div class="clip-topic">
        <div class="clip-topic-head">${prepArea(`topics.${ti}.heading`, t.heading, 'topic — e.g. a domain, a question, an area', 'clip-topic-h')}<button class="clip-x clip-topic-x" data-del="topics.${ti}" title="remove topic">✕</button></div>
        <div class="clip-bullets">${bullets}</div>
        <button class="clip-add clip-add-bullet" data-add="topics.${ti}.bullets">+ point</button>
        <div class="clip-flags">${flags}</div>
        <button class="clip-add clip-add-flag" data-add="topics.${ti}.flags">+ ⚠ flag</button>
      </div>`
  }).join('')

  // 📊 snapshot — the at-a-glance grid: domain · rating · the one fact that shows it
  const snap = doc.snapshot.map((r, i) => `<div class="clip-snap-row">
      ${prepArea(`snapshot.${i}.domain`, r.domain, 'domain', 'clip-snap-d')}
      ${prepArea(`snapshot.${i}.rating`, r.rating, 'mild · moderate · marked · extreme', 'clip-snap-r')}
      ${prepArea(`snapshot.${i}.evidence`, r.evidence, 'the one fact that shows it', 'clip-snap-e')}
      <button class="clip-x" data-del="snapshot.${i}" title="remove">✕</button>
    </div>`).join('')

  // ❓ if they ask — the question you dread + your prepared, honest answer
  const qa = doc.qa.map((r, i) => `<div class="clip-qa">
      <div class="clip-qa-q">${prepArea(`qa.${i}.q`, r.q, 'the question you expect…', 'clip-qa-in')}</div>
      <div class="clip-qa-a">${prepArea(`qa.${i}.a`, r.a, '…your prepared answer', 'clip-qa-in')}</div>
      <button class="clip-x clip-qa-x" data-del="qa.${i}" title="remove">✕</button>
    </div>`).join('')

  // 📎 bring — forms · letters · med list · prior notes
  const bring = doc.bring.map((b, i) => `<div class="clip-bring-row">
      <span class="clip-clip">📎</span>${prepArea(`bring.${i}`, b, 'form · letter · med list · prior notes', 'clip-bring')}
      <button class="clip-x" data-del="bring.${i}" title="remove">✕</button>
    </div>`).join('')

  return `
    <div class="clip-meta">
      <div class="clip-disc-row"><span class="clip-disc-chips">${chips}</span>${prepArea('discipline', doc.discipline, 'discipline / who', 'clip-disc-in')}</div>
      <div class="clip-sessions">
        <button class="clip-save" title="save this sheet → the nurse's notes on the injection config">💾 save</button>
        ${sessTabs || '<span class="clip-sess-empty">no saved sheets for this provider yet</span>'}
      </div>
      <div class="clip-meta-row">${prepArea('seeing', doc.seeing, "who I'm seeing — clinician / clinic", 'clip-seeing')}</div>
      <div class="clip-meta-row">${prepArea('date', doc.date, 'date / when', 'clip-date')}</div>
    </div>

    <div class="clip-sec clip-say">
      <div class="clip-sec-h">🎯 say this first</div>
      ${prepArea('sayFirst', doc.sayFirst, 'the one thing to land before anything else…', 'clip-say-in')}
    </div>

    <div class="clip-sec">
      <div class="clip-sec-h">🗓 this session — realistic scope</div>
      <div class="clip-scope">${scope}</div>
      <button class="clip-add" data-add="scope">+ item</button>
    </div>

    <div class="clip-sec">
      <div class="clip-sec-h">📝 topics</div>
      <div class="clip-topics">${topics}</div>
      <button class="clip-add clip-add-topic" data-add="topics">+ topic</button>
    </div>

    <div class="clip-sec">
      <div class="clip-sec-h">📊 snapshot</div>
      <div class="clip-snap-head"><span>domain</span><span>rating</span><span>evidence</span><span></span></div>
      <div class="clip-snap">${snap}</div>
      <button class="clip-add" data-add="snapshot">+ row</button>
    </div>

    <div class="clip-sec clip-ataglance">
      <div class="clip-sec-h">📈 at-a-glance — consolidated health report</div>
      <div class="clip-cmp-note">the patient's own sleep · food · movement, pulled into one print-out to hand across the desk. pick what to include and how far back, then print:</div>
      <div class="clip-subbar clip-hr-cats">
        <button type="button" class="clip-chip clip-hr-cat clip-hr-all on" data-cat="all">All</button>
        <button type="button" class="clip-chip clip-hr-cat on" data-cat="sleep">😴 Sleep</button>
        <button type="button" class="clip-chip clip-hr-cat on" data-cat="food">🍎 Food</button>
        <button type="button" class="clip-chip clip-hr-cat on" data-cat="exercise">🏃 Move</button>
      </div>
      <div class="clip-subbar clip-hr-scopes">
        <button type="button" class="clip-chip clip-hr-scope" data-scope="day">Day</button>
        <button type="button" class="clip-chip clip-hr-scope on" data-scope="week">Week</button>
        <button type="button" class="clip-chip clip-hr-scope" data-scope="month">Month</button>
      </div>
      <div class="clip-subbar clip-hr-week" data-week-offset="0">
        <button type="button" class="clip-chip clip-hr-wk" data-wk="-1" title="the week before">◀</button>
        <span class="clip-hr-wklabel">this week</span>
        <button type="button" class="clip-chip clip-hr-wk" data-wk="1" title="the week after">▶</button>
      </div>
      <div class="clip-subbar clip-hr-go">
        <button type="button" class="clip-chip clip-hr-print" data-hr-print="1">🖨 print</button>
        <button type="button" class="clip-chip clip-hr-save" data-hr-save="1" title="file this week's report under wellness/reports/">💾 save week</button>
      </div>
    </div>

    <div class="clip-sec">
      <div class="clip-sec-h">❓ if they ask</div>
      <div class="clip-qas">${qa}</div>
      <button class="clip-add" data-add="qa">+ Q&amp;A</button>
    </div>

    <div class="clip-sec">
      <div class="clip-sec-h">📎 bring</div>
      <div class="clip-brings">${bring}</div>
      <button class="clip-add" data-add="bring">+ item</button>
    </div>

    <div class="clip-foot">prep is the work — print it, bring it, hand them the parts they need.</div>`
}

// a new empty leaf for an array push (objects for the structured sections, '' for the flat lists)
function prepNewLeaf(addPath) {
  if (/scope$/.test(addPath))      return { item: '', time: '' }
  if (/topics$/.test(addPath))     return { heading: '', bullets: [''], flags: [''] }
  if (/snapshot$/.test(addPath))   return { domain: '', rating: '', evidence: '' }
  if (/qa$/.test(addPath))         return { q: '', a: '' }
  return ''   // bullets · flags · bring — flat strings
}
function prepGetArr(doc, path) {
  const ks = path.split('.'); let t = doc
  for (const k of ks) t = t[/^\d+$/.test(k) ? +k : k]
  return t
}

// print the sheet as a clean document (hidden iframe — reliable on file://, no popup blocker)
function prepPrint(doc) {
  const row = (a, b) => a || b ? `<tr><td>${prepEsc(a)}</td><td>${prepEsc(b)}</td></tr>` : ''
  const topics = doc.topics.filter(t => t.heading || t.bullets.some(Boolean) || t.flags.some(Boolean)).map(t => `
    <h2>${prepEsc(t.heading) || '—'}</h2>
    <ul>${t.bullets.filter(Boolean).map(b => `<li>${prepEsc(b)}</li>`).join('')}</ul>
    ${t.flags.filter(Boolean).map(f => `<p class="warn">⚠ ${prepEsc(f)}</p>`).join('')}`).join('')
  const snap = doc.snapshot.filter(r => r.domain || r.rating || r.evidence).map(r => `<tr><td>${prepEsc(r.domain)}</td><td><b>${prepEsc(r.rating)}</b></td><td>${prepEsc(r.evidence)}</td></tr>`).join('')
  const qa = doc.qa.filter(r => r.q || r.a).map(r => `<p><b>${prepEsc(r.q)}</b><br>${prepEsc(r.a)}</p>`).join('')
  const bring = doc.bring.filter(Boolean).map(b => `<li>${prepEsc(b)}</li>`).join('')
  const ovDoc = (label, txt) => (txt || '').trim() ? `<h2>${label}</h2><div class="doc">${prepEsc(txt)}</div>` : ''
  const ov = ovDoc('presentation', doc.presentation) + ovDoc('perspective', doc.perspective) + ovDoc('co-morbidity', doc.comorbidity)
  // complaints grouped by folder (a complaint cross-filed in two folders prints under both)
  const cmp = COMPLAINT_FOLDERS.map(([fid, flabel]) => {
    const items = doc.complaints.filter(c => (c.folders || []).includes(fid) && (c.title || c.body))
    return items.length ? `<h3>${prepEsc(flabel)}</h3><ul>${items.map(c => `<li><b>${prepEsc(c.title)}</b>${c.body ? '<br>' + prepEsc(c.body) : ''}</li>`).join('')}</ul>` : ''
  }).join('')
  const guides = (doc.guides || []).filter(g => g.title || g.body).map(g => `<h3>${prepEsc(g.title)}</h3><div class="doc">${prepEsc(g.body)}</div>`).join('')
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>chart</title><style>
    body { font: 13px/1.5 -apple-system, system-ui, sans-serif; color: #1a1a1a; max-width: 700px; margin: 30px auto; padding: 0 24px; }
    h1 { font-size: 19px; margin: 0 0 2px; } .sub { color: #555; margin: 0 0 16px; font-size: 12px; }
    h2 { color: #b91c1c; font-size: 14px; margin: 18px 0 4px; border-bottom: 1px solid #eee; padding-bottom: 3px; }
    h3 { color: #334155; font-size: 12.5px; margin: 12px 0 2px; } .doc { white-space: pre-wrap; margin: 0 0 12px; }
    .say { background: #f5f0e6; border-left: 3px solid #c8a96b; padding: 8px 12px; margin: 0 0 14px; font-style: italic; }
    table { border-collapse: collapse; width: 100%; margin: 6px 0 12px; font-size: 12px; }
    th, td { border: 1px solid #ddd; padding: 5px 8px; text-align: left; vertical-align: top; } th { background: #334155; color: #fff; }
    .warn { color: #b45309; margin: 2px 0; font-size: 12px; } ul { margin: 4px 0 8px; padding-left: 20px; } li { margin: 2px 0; }
    .foot { margin-top: 24px; color: #888; font-size: 11px; border-top: 1px solid #eee; padding-top: 8px; }
  </style></head><body>
    <h1>${prepEsc(doc.patient) || (prepEsc(doc.discipline) || 'session') + ' prep'}</h1>
    <p class="sub">${[prepEsc(doc.seeing), prepEsc(doc.discipline), prepEsc(doc.date)].filter(Boolean).join(' · ')}</p>
    ${ov}
    ${cmp ? `<h2>complaints — filed by system, not diagnoses</h2>${cmp}` : ''}
    ${guides ? `<h2>quick guides</h2>${guides}` : ''}
    ${doc.sayFirst ? `<div class="say">🎯 ${prepEsc(doc.sayFirst)}</div>` : ''}
    ${doc.scope.some(r => r.item) ? `<h2>this session — scope</h2><table><tr><th>item</th><th>~time</th></tr>${doc.scope.map(r => row(r.item, r.time)).join('')}</table>` : ''}
    ${topics}
    ${snap ? `<h2>snapshot</h2><table><tr><th>domain</th><th>rating</th><th>evidence</th></tr>${snap}</table>` : ''}
    ${qa ? `<h2>if they ask</h2>${qa}` : ''}
    ${bring ? `<h2>bring</h2><ul>${bring}</ul>` : ''}
    <div class="foot">prep reflects effort, not baseline — hand them the parts they need.</div>
  </body></html>`
  window.printDoc(html)   // the shared print bean (shell/cards.js) — HTML in, OS print dialog → Save as PDF
}

function buildClipboard() {
  const body = htmlNode(`<div class="clip-board"><div class="clip-sheet"></div></div>`)   // tools moved into the sheet's sticky top line

  const card = window.makeCard({ id: 'clipboard', icon: 'cards/clipboard/clipboard.png', title: 'chart', skin: 'card-clipboard p-clipboard', body, jewels: false, stop: false, bottom: true })

  // GROW with content → the desk doom-scrolls (no capped inner box; the sheet just gets longer)
  const cardBody = card.querySelector('.card-body'); if (cardBody) { cardBody.style.height = 'auto'; cardBody.style.overflow = 'visible' }

  const sheet = card.querySelector('.clip-sheet')
  // chart nav state: which SIDE (ai/hil), which section tab, + the two sub-bars (overview doc · complaint folder)
  let ui = { side: 'ai', tab: 'overview', ovTab: 'presentation', cmpFolder: 'psych', guide: 0 }
  let doc = prepGet(ui.side)

  // grow to fit text, but CAP it — a field measured mid-layout (collapsed narrow) could otherwise report a
  // full-page scrollHeight and eat the whole sheet (the old "blank page" bug). a .clip-doc is a WHOLE FILE —
  // it grows tall and the sheet scrolls (much higher cap, taller floor).
  function autoGrow(ta) {
    const big = ta.classList.contains('clip-doc')
    ta.style.height = 'auto'
    ta.style.height = Math.min(Math.max(ta.scrollHeight, big ? 180 : 20), big ? 6000 : 360) + 'px'
  }
  function render() {
    sheet.innerHTML = renderSheet(doc, ui)
    // grow AFTER the card is on the desk — at build time it's still detached (scrollHeight = 0)
    requestAnimationFrame(() => sheet.querySelectorAll('.clip-in').forEach(autoGrow))
  }

  // text edits → write the path, persist, grow (no re-render → focus stays put)
  sheet.addEventListener('input', e => {
    const ta = e.target.closest('.clip-in'); if (!ta) return
    prepPath(doc, ta.dataset.path, ta.value); autoGrow(ta)
    localStorage.setItem(prepKey(ui.side), JSON.stringify(doc))   // quiet save to the active side (no event — we ARE the source)
  })
  // our OWN edits save quietly (no event) → never re-trigger our listener (which would re-seed the demo on empty)
  const saveQuiet = d => { try { localStorage.setItem(prepKey(ui.side), JSON.stringify(d)) } catch (_) {} }
  // structural: chips · add · remove → mutate + re-render
  sheet.addEventListener('click', e => {
    const tb = e.target.closest('.clip-tab')
    if (tb) { ui.tab = tb.dataset.tab; render(); return }   // swap the chart divider — overview · complaints · prep
    // AI / HIL source tabs — switch which doc is loaded (the nurse's notes vs the human's blanks)
    const sd = e.target.closest('.clip-side')
    if (sd) { ui.side = sd.dataset.side; doc = prepGet(ui.side); render(); return }
    // top-line actions — print · new sheet (this side). the harness pointer is copy now, not a button (see overview).
    if (e.target.closest('.clip-print')) { prepPrint(doc); return }
    // 📈 at-a-glance health report — category multi-select · scope single-select · 🖨 print (window.ozHealthReport, set by clip-health-report.js)
    // (1) category chips — multi-select, with an "All" master toggle
    var hrCat = e.target.closest('.clip-hr-cat')
    if (hrCat) {
      var catBar = hrCat.closest('.clip-hr-cats')
      var realCats = catBar ? catBar.querySelectorAll('.clip-hr-cat:not(.clip-hr-all)') : []
      var allBtn = catBar ? catBar.querySelector('.clip-hr-all') : null
      if (hrCat.classList.contains('clip-hr-all')) {
        realCats.forEach(function (b) { b.classList.add('on') })
        if (allBtn) allBtn.classList.add('on')
      } else {
        hrCat.classList.toggle('on')
        var anyOn = false, allOn = true
        realCats.forEach(function (b) { if (b.classList.contains('on')) anyOn = true; else allOn = false })
        if (!anyOn) { hrCat.classList.add('on'); allOn = realCats.length === 1 }
        if (allBtn) allBtn.classList.toggle('on', allOn)
      }
      return
    }
    // (2) scope buttons — single-select
    var hrScope = e.target.closest('.clip-hr-scope')
    if (hrScope) {
      var scopeBar = hrScope.closest('.clip-hr-scopes')
      if (scopeBar) scopeBar.querySelectorAll('.clip-hr-scope').forEach(function (b) { b.classList.remove('on') })
      hrScope.classList.add('on')
      return
    }
    // (2b) ◀ ▶ any week — an offset in weeks from today, kept on the row (2 Sep 2026, the magic chart)
    var hrWk = e.target.closest('.clip-hr-wk')
    if (hrWk) {
      var row = hrWk.closest('.clip-hr-week')
      // 2 Sep 2026 — step through the weeks that HAVE data (window.ozHealthWeeks, newest first), not blind 7-day hops.
      //    index 0 = this week (may be empty); 1.. = the data weeks. Falls back to the blind hop if the collector is not loaded.
      var weeks = (window.ozHealthWeeks ? window.ozHealthWeeks() : []).filter(function (w) { return w.end < new Date().toISOString().slice(0, 10) })
      var idx = (+row.dataset.weekIdx || 0) + (+hrWk.dataset.wk || 0) * -1
      if (idx < 0) idx = 0; if (idx > weeks.length) idx = weeks.length
      row.dataset.weekIdx = idx
      var end, st, f = function (d) { return (d.getMonth() + 1) + '/' + d.getDate() }
      if (idx === 0 || !weeks.length) { end = new Date(); if (idx && !weeks.length) end.setDate(end.getDate() - idx * 7) }
      else { end = new Date(weeks[idx - 1].end + 'T12:00:00') }
      st = new Date(end); st.setDate(end.getDate() - 6)
      row.dataset.weekEnd = end.getFullYear() + '-' + String(end.getMonth() + 1).padStart(2, '0') + '-' + String(end.getDate()).padStart(2, '0')
      row.querySelector('.clip-hr-wklabel').textContent = idx === 0 ? 'this week' : f(st) + ' – ' + f(end) + (weeks[idx - 1] ? ' · ' + weeks[idx - 1].days + ' day' + (weeks[idx - 1].days === 1 ? '' : 's') + ' logged' : '')
      return
    }
    // (3) 🖨 print / 💾 save — gather the DOM selection and hand it to the report
    var hrPrint = e.target.closest('.clip-hr-print') || e.target.closest('.clip-hr-save')
    if (hrPrint) {
      if (!window.ozHealthReport) { window.ozConfirm('open a 🧘 wellness card first so the health data is loaded, then try again.'); return }
      var root = hrPrint.closest('.clip-ataglance') || sheet
      var cats = Array.prototype.slice.call(root.querySelectorAll('.clip-hr-cat:not(.clip-hr-all).on')).map(function (b) { return b.dataset.cat })
      var scopeBtn2 = root.querySelector('.clip-hr-scope.on')
      var scope = scopeBtn2 ? scopeBtn2.dataset.scope : 'week'
      var wkRow = root.querySelector('.clip-hr-week')
      var anchorD = new Date(), anchor = (wkRow && wkRow.dataset.weekEnd) || (anchorD.getFullYear() + '-' + String(anchorD.getMonth() + 1).padStart(2, '0') + '-' + String(anchorD.getDate()).padStart(2, '0'))
      window.ozHealthReport({ scope: scope, cats: cats.length ? cats : ['sleep', 'food', 'exercise'], date: anchor, save: !!hrPrint.classList.contains('clip-hr-save') })
      return
    }
    if (e.target.closest('.clip-new')) {
      window.ozConfirm('start a fresh blank sheet for this side? overview, complaints, and prep will be cleared.').then(ok => { if (ok) { doc = prepFresh(); saveQuiet(doc); render() } })
      return
    }
    // overview sub-bar — switch which WHOLE-FILE doc is open (presentation · perspective · co-morbidity)
    const ovs = e.target.closest('.clip-ovsub')
    if (ovs) { ui.ovTab = ovs.dataset.ovsub; render(); return }
    // complaints folder sub-bar — open a body-system folder
    const fol = e.target.closest('.clip-folder')
    if (fol) { ui.cmpFolder = fol.dataset.folder; render(); return }
    // + complaint → a new file in the OPEN folder
    const addc = e.target.closest('.clip-add-cmp')
    if (addc) { doc.complaints.push({ id: cmpId(), title: '', body: '', folders: [ui.cmpFolder] }); saveQuiet(doc); render(); return }
    // quick-guides sub-bar — open a guide
    const gsub = e.target.closest('.clip-gsub')
    if (gsub) { ui.guide = +gsub.dataset.guide; render(); return }
    // + quick guide → a new cheat-sheet, and open it
    const addg = e.target.closest('.clip-add-guide')
    if (addg) { (doc.guides = doc.guides || []).push({ id: cmpId(), title: '', body: '' }); ui.guide = doc.guides.length - 1; saveQuiet(doc); render(); return }
    // cross-file: toggle a complaint into / out of a folder — keep ≥1 so it never vanishes from every folder
    const ctag = e.target.closest('.clip-cfile-tag')
    if (ctag) {
      const dot = ctag.dataset.cmpfolder.indexOf('.'), c = doc.complaints[+ctag.dataset.cmpfolder.slice(0, dot)], fid = ctag.dataset.cmpfolder.slice(dot + 1)
      if (c.folders.includes(fid)) { if (c.folders.length > 1) c.folders = c.folders.filter(f => f !== fid) }
      else c.folders.push(fid)
      saveQuiet(doc); render(); return
    }
    // discipline chip (prep) — guard on data-disc so the sub-bar chips (also .clip-chip) don't fall through here
    const chip = e.target.closest('.clip-chip')
    if (chip && chip.dataset.disc) { doc.discipline = chip.dataset.disc; saveQuiet(doc); render(); return }
    // 💾 save → a session + a nurse note (on the injection chart) · load a tab · trash a tab
    const save = e.target.closest('.clip-save')
    if (save) { window.prepSaveSession(doc); render(); return }   // same path the nurse's prep_save bean uses
    const sLoad = e.target.closest('.clip-sess-load')
    if (sLoad) { const s = loadSessions().find(x => x.id === sLoad.dataset.sess); if (s) { doc = prepMigrate(Object.assign(prepFresh(), JSON.parse(JSON.stringify(s.doc)))); saveQuiet(doc); render() } return }
    const sTrash = e.target.closest('.clip-sess-x')
    if (sTrash) { saveSessions(loadSessions().filter(x => x.id !== sTrash.dataset.trash)); nurseNoteRemove(sTrash.dataset.trash); render(); return }
    const add = e.target.closest('.clip-add')
    if (add) { prepGetArr(doc, add.dataset.add).push(prepNewLeaf(add.dataset.add)); saveQuiet(doc); render(); return }
    const del = e.target.closest('.clip-x')
    if (del) {
      const p = del.dataset.del, ks = p.split('.'), idx = +ks.pop()
      const arr = prepGetArr(doc, ks.join('.'))
      arr.splice(idx, 1); if (!arr.length && !/(complaints|guides)$/.test(ks.join('.'))) arr.push(prepNewLeaf(ks.join('.')))   // prep sections never empty; complaints + guides may
      saveQuiet(doc); render(); return
    }
  })

  // (harness · print · new sheet now live in the sticky top line, handled by the delegated click listener above —
  //  they re-render with the sheet, so they can't be bound once here.)

  // the nurse (or anything) edited the doc via a bean → re-read the AI side, if this card is on the desk + showing it
  window.addEventListener('toto-prep-changed', () => {
    if (!document.body.contains(card)) return
    if (ui.side !== 'ai') return   // the nurse writes the AI side; don't disturb the human's HIL side
    if (document.activeElement && card.contains(document.activeElement)) return   // don't yank a field mid-type
    doc = prepGet('ai'); render()
  })

  render()
  return card
}

window.CARD_BUILDERS.clipboard = buildClipboard
