// clock-arrange.js — drag the FACE itself: reorder tiles, swap sides, shuffle bars
// FOR HUMANS: grab any widget ON the clock — drag up/down to reorder, drag
//   across to the other column. the center rows (date · time · forecast)
//   reorder among themselves. keyboard: focus a tile, G latches it —
//   arrows move it (←→ jump columns), G or Esc lets go.
//   settings is just location + toggles now — the arrange page retired.
// FOR AI:
//   1. writes order-left / order-bars / order-right into clock-widget-order —
//      the SAME keys applyWidgetOrder (clock.html) replays on load.
//   2. window._faceDrag guards the tile click→overlay (lb-clock-bars.js).
//   3. bars (date-row/time/forecast) stay in center; side tiles swap freely.
//   4. moving a focused node drops focus → the `moving` flag stops the
//      blur handler from releasing the latch mid-move.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   mouse drag ............................... search: "mouse drag"
//   keyboard latch — G grabs, arrows move, ... search: "keyboard latch — G"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for how tiles reorder on the clock face. It
//    **writes three keys into `localStorage['clock-widget-order']` (`order-left`, `order-bars`,
//    **`order-right`) that `clock.html` reads on load to replay the arrangement. It also sets
//    **`window._faceDrag` (line 36, 45) to guard against tile click→overlay in `lb-clock-bars.js`.
//
//    **TOUCH HERE** —
//    - Change which widgets can be dragged → add/remove from `BARS` array (line 16)
//    - Change where tiles are allowed to move → edit the zone constraint at line 53
//    - Change keyboard shortcut from G → edit `e.key === 'g'` check (line 72)
//    - Change arrow-key behavior (up/down reorder, left/right swap columns) → `keydown` handler
//    - (lines 83–101)
//    - Change visual feedback class name → replace `'cw-dragging'` (lines 37, 42) and
//    - `'cw-latched'` (lines 65, 77) everywhere they appear
//    - Persist a new arrangement field → add a new `order[...]` assignment in `saveOrder()` (lines
//    - 24–26) and a matching `ids()` call
//
//    **TRAPS** —
//    - `BARS` (line 16) is load-bearing: line 52 checks membership to enforce that
//    - date-row/time/forecast stay in center. Removing a bar from the array will let it drift to
//    - the sides.
//    - `localStorage` key `'clock-widget-order'` is persisted user data (line 21, 27). Renaming it
//    - orphans all saved arrangements. The three sub-keys `'order-left'`, `'order-bars'`,
//    - `'order-right'` (lines 24–26) must match what `clock.html` expects on load.
//    - `window._faceDrag` (lines 36, 45) is a contract with `lb-clock-bars.js`. Removing it will
//    - break click-to-overlay suppression during drag.
//    - The `moving` flag (lines 89, 92, 97, 100, 103) prevents blur from releasing the latch
//    - mid-move. It must be set before `insertBefore`/`appendChild` and cleared after `focus()`.
//    - Line 53's logic `isBar !== (zone.dataset.zone === 'center')` is a double-negative: it
//    - returns early if a bar tries to leave center OR a tile tries to enter center. Inverting this
//    - silently breaks the constraint.
//
//    **DO NOT** —
//    - Do not rename `items()` (line 17) without checking all call sites; it is called at lines 32,
//    - 69.
//    - Do not move `saveOrder()` calls (lines 44, 67) or add new ones without understanding that
//    - they fire after the DOM is already rearranged.
//    - Do not change the `[data-zone]` or `[data-widget]` attribute names; they are the contract
//    - with the HTML structure.
//    - Do not add new localStorage keys here; that belongs in a settings/persistence module.
//    - Do not add visual styling (colors, animations); that belongs in CSS.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const BARS  = ['date-row', 'time', 'forecast']
  const items = () => document.querySelectorAll('[data-zone] > [data-widget]')

  function saveOrder() {
    let order = {}
    try { order = JSON.parse(localStorage.getItem('clock-widget-order') || '{}') } catch {}
    const ids = z => Array.from(document.querySelectorAll(`[data-zone="${z}"] > [data-widget]`))
                          .map(e => e.dataset.widget)
    order['order-left']  = ids('left')
    order['order-bars']  = ids('center')
    order['order-right'] = ids('right')
    localStorage.setItem('clock-widget-order', JSON.stringify(order))
  }

  // ── mouse drag ─────────────────────────────────────────────
  let dragged = null
  items().forEach(el => {
    el.setAttribute('draggable', 'true')
    el.addEventListener('dragstart', e => {
      dragged = el
      window._faceDrag = true
      el.classList.add('cw-dragging')
      e.dataTransfer.effectAllowed = 'move'
      try { e.dataTransfer.setData('text/plain', el.dataset.widget) } catch {}
    })
    el.addEventListener('dragend', () => {
      el.classList.remove('cw-dragging')
      dragged = null
      saveOrder()
      setTimeout(() => { window._faceDrag = false }, 0)   // let the stray click die first
    })
  })

  document.querySelectorAll('[data-zone]').forEach(zone => {
    zone.addEventListener('dragover', e => {
      if (!dragged) return
      const isBar = BARS.includes(dragged.dataset.widget)
      if (isBar !== (zone.dataset.zone === 'center')) return   // bars keep center; tiles keep sides
      e.preventDefault()
      const sibs  = Array.from(zone.children).filter(c => c !== dragged && c.dataset && c.dataset.widget)
      const after = sibs.find(c => { const r = c.getBoundingClientRect(); return e.clientY < r.top + r.height / 2 })
      zone.insertBefore(dragged, after || null)
    })
  })

  // ── keyboard latch — G grabs, arrows move, G/Esc lets go ──
  let latch = null, moving = false
  function release() {
    if (!latch) return
    latch.classList.remove('cw-latched')
    latch = null
    saveOrder()
  }
  items().forEach(el => {
    if (!el.hasAttribute('tabindex')) el.setAttribute('tabindex', '0')   // bars weren't focusable
    el.addEventListener('keydown', e => {
      if (e.key === 'g' || e.key === 'G') {
        e.preventDefault()
        if (latch === el) { release(); return }
        release()
        latch = el
        el.classList.add('cw-latched')
        return
      }
      if (latch !== el) return
      if (e.key === 'Escape') { e.stopPropagation(); release(); return }

      if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        e.preventDefault()
        const zone = el.parentElement
        const sibs = Array.from(zone.children).filter(c => c.dataset && c.dataset.widget)
        const i = sibs.indexOf(el), j = e.key === 'ArrowUp' ? i - 1 : i + 1
        if (j < 0 || j >= sibs.length) return
        moving = true
        zone.insertBefore(el, e.key === 'ArrowUp' ? sibs[j] : sibs[j].nextSibling)
        el.focus()
        moving = false
      } else if ((e.key === 'ArrowLeft' || e.key === 'ArrowRight') && !BARS.includes(el.dataset.widget)) {
        e.preventDefault()
        const target = document.querySelector(e.key === 'ArrowLeft' ? '[data-zone="left"]' : '[data-zone="right"]')
        if (!target || el.parentElement === target) return
        moving = true
        target.appendChild(el)
        el.focus()
        moving = false
      }
    })
    el.addEventListener('blur', () => { if (!moving && latch === el) release() })
  })
})()
