// attach.js — the + on an agent bar opens a little menu:
//   📸 photo · 🖥️ screenshot · 📎 file · 🔗 link
// each lands in the sandbox, then ROUTES by what it is:
//   image → shows it (a vision model reads it; a blind one says it can't see it)
//   code  → opens 🏁 monaco + 👀 preview; the bot gets a copy inline
//   doc   → opens 📄 tiptap; copy inline
//   link  → cached; the bot gets the url (reading its contents needs a reader/browsing)
//   other → cached; the bot is told what kind of file it is
// build phase: the sandbox is an in-browser CACHE (the git/Pages floor). native copies
// the file into a real sandbox folder. vision routing (food photo → 🥗 food) is live-model.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the menu dispatch — photo / screenshot / ...... search: "the menu dispatch"
//   a picked/shot file: cache it, then route it ... search: "a picked/shot file:"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The attachment pipeline: menu dispatch (`attachAction`), file capture
//    **(`captureScreen`), and file routing (`attachFile`). Exports three window functions:
//    **`attachAction`, `captureScreen`, `attachFile`. Also owns the `kind()` classifier that maps
//    **file types to card destinations, and `SANDBOX` — the in-browser cache where all attachments
//    **land before the agent sees them.
//
//    **TOUCH HERE** —
//    - Add a new file type (e.g., video) → `kind()` L20, add extension check and return value
//    - Change where code files land in the sandbox → `attachFile()` L97, edit the `folder`
//    - assignment
//    - Add a new card destination (e.g., a new kind opens a new card) → `attachFile()` L109–126,
//    - add an `else if (k === 'newkind')` block with `openCard()` call and `say()` message
//    - Change the screenshot capture UI message → `captureScreen()` L69 or L83, edit the `say()`
//    - call
//    - Change what the agent is told when a file arrives → `attachFile()` L136–150, edit the
//    - `noun`, `where`, or `msg` construction
//    - Adjust the inline content cap (currently 400 lines) → `attachFile()` L147, change `CAP =
//    - 400`
//
//    **TRAPS** —
//    - `window.SANDBOX[key]` at L99 is the load-bearing cache key. Changing the `folder` logic at
//    - L97 will orphan files already cached under the old key — users' old attachments become
//    - unreachable.
//    - The `kind()` return values at L22–30 are hardcoded in the routing chain at L101–126. Add a
//    - new kind without adding its `else if` block and it silently falls through to the 'other'
//    - case.
//    - `window.OZ_VISION_PENDING` at L108 is read elsewhere (not in this file); changing its shape
//    - breaks vision attachment.
//    - `reader.readAsDataURL()` vs `reader.readAsText()` at L158–159 must match the kind logic —
//    - images and zips must be data URLs; text files must be text. Swapping them silently breaks
//    - display or inlining.
//    - `window.toggleCard()` at L50 and `window.runTurn()` at L152 are called but defined
//    - elsewhere; they must exist or attachments fail silently.
//
//    **DO NOT** —
//    - Do not rename `attachAction`, `attachFile`, `captureScreen`, or `SANDBOX` — they are the
//    - public API.
//    - Do not move the `kind()` classifier to another file; it is tightly coupled to the routing at
//    - L101–126.
//    - Do not add new file-type detection logic outside `kind()` — it is the single source of
//    - truth.
//    - Do not change how `say()` works to add styling or layout — that belongs in CSS, not here.
//    - Do not add agent-specific behavior (e.g., "if agent is wellness, do X") — that belongs in
//    - the agent's own toolkit or in `runTurn()`.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {

  // the sandbox — in-browser cache for now. native: a real folder copy. (the git floor.)
  window.SANDBOX = window.SANDBOX || {}

  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }

  // what kind of thing is this? drives WHICH card it opens in — its home surface.
  function kind(name, mime) {
    const n = (name || '').toLowerCase(), ext = (n.split('.').pop() || '')
    if ((mime || '').startsWith('image/')) return 'image'
    if (['ics','ical','vcs'].includes(ext)) return 'calendar'                                   // → 📅 calendar
    if (['mbox','eml'].includes(ext)) return 'email'                                             // → ✉️ email
    // a health export: a Samsung/Fit/Apple/Fitbit/Garmin dump — by name hint + a data extension. → 🧘 wellness
    if (/samsung|google.?fit|takeout|fitbit|garmin|apple.?health|\bhealth\b|\bsleep\b|\bsteps\b|heart.?rate/.test(n)
        && ['zip','json','csv','xml'].includes(ext)) return 'health'
    if (['html','htm','js','css','py','json','ts','jsx','tsx','c','cpp','java','rb','go','rs','sh','sql'].includes(ext)) return 'code'
    if (['md','txt','rtf','doc','docx','odt','pdf'].includes(ext)) return 'doc'
    return 'other'
  }

  // ── the FILE ROUTER (Sum, 15 Aug: "show file name, hyper text to open in appropriate app —
  //    coder is catch all"). EASY images thumb inline; html/pdf/off-brand images → 👀 preview;
  //    docs → 📄 tiptap; code and everything else → 🏁 monaco. ──
  const EASY_IMG = /\.(png|jpe?g|gif|webp|bmp|svg)$/i
  function cardFor(k, ext) {
    if (ext === 'pdf' || ext === 'html' || ext === 'htm') return 'webview'
    if (k === 'image') return 'webview'          // an off-brand image the <img> tag can't chew
    // CORRECTION 2026-08-29 — tiptap · calendar · email PARKED (_bench-for-totois/, Sum's call).
    // Their rows pointed docs/ics/eml at cards that no longer mount; those kinds fall through to
    // monaco (the catch-all — "coder is catch all" was the original law anyway). Rows as they were:
    //   if (k === 'doc') return 'tiptap'
    //   if (k === 'calendar') return 'calendar'
    //   if (k === 'email') return 'email'
    if (k === 'health') return 'spa'
    return 'monaco'                              // the catch-all
  }
  const linkHTML = (key, card, name) => `<button class="att-file" data-key="${esc(key)}" data-card="${card}" title="click to open">${esc(name)}</button>`

  // drop a message into an agent bar's convo (above the live input line), OR — for a CARD with
  // no convo (e.g. 📝 learn) — into its `.att-sink`. lets the + attach engine serve cards too.
  function say(bar, html) {
    const screen = bar.querySelector('.convo-screen')
    if (screen) {
      const stream = bar.querySelector('.msg-stream')
      const msg = document.createElement('div')
      msg.className = 'msg msg-bot msg-attach'; msg.innerHTML = html
      screen.insertBefore(msg, stream); msg.scrollIntoView({ block: 'nearest' }); return
    }
    const sink = bar.querySelector('.att-sink')
    if (!sink) return
    const row = document.createElement('div'); row.className = 'att-row'; row.innerHTML = html
    sink.appendChild(row); row.scrollIntoView({ block: 'nearest' })
  }

  // open a route-target card. placeholder cards still open — they show the slot.
  function openCard(id) { if (window.toggleCard) window.toggleCard(id, true, {}) }

  // ── the menu dispatch — photo / screenshot / file / link ──────────────
  window.attachAction = function (bar, act) {
    const input = bar.querySelector('.ab-file')
    if (act === 'photo')      { input.accept = 'image/*'; input.setAttribute('capture', 'environment'); input.click() }
    else if (act === 'file')  { input.accept = ''; input.removeAttribute('capture'); input.click() }
    else if (act === 'screen') captureScreen(bar)
    else if (act === 'link') {   // 🔗 the fourth door (Sum 2026-08-23: "we never got the link added to plus") —
      // the July no-link rule is superseded: the ladder reads it honestly now. url → OZ_CLEAN_READ →
      // lands as link-<host>.txt through attachFile (folder routing + the hand-off ride free). a wall →
      // the bouncer's sentence IS the paste ask; what the human brings back lands the same way.
      ;(async () => {
        const ask = q => Promise.resolve(window.ozPrompt ? window.ozPrompt(q) : window.prompt(q))
        const url = String(await ask('the link (https://…) — the bot reads it down the ladder') || '').trim()
        if (!/^https?:\/\//i.test(url)) return
        let host = 'link'; try { host = new URL(url).hostname.replace(/^www\./, '') } catch (_) {}
        const land = text => window.attachFile(bar, new File(['FROM: ' + url + '\n\n' + text], 'link-' + host + '.txt', { type: 'text/plain' }))
        // ── THE SNIFF AT THE DOOR (Sum 2026-08-28: "if youtube… prime get transcript as first option
        //    bot leans on, but checks first with hil"). A watch page down the clean-read ladder strips
        //    to soup — so a youtube link SKIPS the ladder and lands as a marker naming the primed move.
        //    The bot ASKS the human first (the marker says so); on a yes it fires yt_transcript.
        const sn = window.OZ_LANE && window.OZ_LANE.sniff ? window.OZ_LANE.sniff(url) : { kind: 'url' }
        if (sn.kind === 'youtube') {
          window.attachFile(bar, new File(['FROM: ' + url + '\n\nA YOUTUBE VIDEO (id ' + sn.id + '), not a page — the clean-read ladder was skipped on purpose.\nTHE PRIMED MOVE: yt_transcript saves its transcript to the library (lessons/transcripts/). ASK THE HUMAN FIRST — "want the transcript saved?" — then fire it on a yes and digest what comes back.'], 'link-youtube-' + sn.id + '.txt', { type: 'text/plain' }))
          return
        }
        try {
          const text = await window.OZ_CLEAN_READ(url, {})
          if (text && String(text).trim()) { land(String(text)); return }
          throw { say: 'the read came back empty' }
        } catch (e) {
          const why = (e && e.say) ? e.say : 'the ladder could not get in'
          const paste = await ask('the door: ' + why + ' — hit the link yourself and paste the pertinent part')
          if (paste && String(paste).trim()) land(String(paste))
        }
      })()
    }
  }

  // (🔗 promptLink removed 2026-07-21 — the ＋ no longer parks a URL. Links arrive in chat and
  //  read in place via mdLite → OZ_READER; the reader is invoked there, not from a paste box.)

  // 🖥️ screenshot — NATIVE FIRST (2026-08-15): screenshot_pick shells macOS's own
  //    `screencapture -i` — drag a region or press SPACE to click a window. THE OS IS THE
  //    PICKER (Sum: "upgrade screenshot to picker"). getDisplayMedia stays as the web fallback.
  //    sinkFile/note generalize the landing so cards can borrow the same door (OZ_ATTACH).
  async function captureScreen(bar, sinkFile, note) {
    const land = sinkFile || (f => window.attachFile(bar, f))
    const tell = note || (h => say(bar, h))
    const c = window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)
    if (c && c.invoke) {
      try {
        const s = await c.invoke('screenshot_pick')
        const bin = atob(s), arr = new Uint8Array(bin.length)
        for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i)
        land(new File([arr], `screenshot-${Date.now()}.png`, { type: 'image/png' }))
      } catch (_) {
        tell(`<div class="att-card"><div class="att-meta">🖥️ <span class="att-dim">screenshot canceled.</span></div></div>`)
      }
      return
    }
    const md = navigator.mediaDevices
    if (!md || !md.getDisplayMedia) {
      tell(`<div class="att-card"><div class="att-meta">🖥️ <span class="att-dim">screenshot needs screen-capture — unavailable here. it needs https (works on Pages); native grabs it directly.</span></div></div>`)
      return
    }
    try {
      const stream = await md.getDisplayMedia({ video: true })
      const track = stream.getVideoTracks()[0]
      const video = document.createElement('video')
      video.srcObject = stream; await video.play()
      const canvas = document.createElement('canvas')
      canvas.width = video.videoWidth; canvas.height = video.videoHeight
      canvas.getContext('2d').drawImage(video, 0, 0)
      track.stop()
      canvas.toBlob(blob => land(new File([blob], `screenshot-${Date.now()}.png`, { type: 'image/png' })), 'image/png')
    } catch (e) {
      tell(`<div class="att-card"><div class="att-meta">🖥️ <span class="att-dim">screenshot canceled.</span></div></div>`)
    }
  }

  // ── OZ_ATTACH — ONE PLUS EVERYWHERE (Sum 2026-08-15: "same function, same code, same
  //    symbol on every bot and card"). The menu is this file's; only the SINK differs per
  //    host: { file(f), note(text) }. Four doors — photo · screenshot · file · link. (The July
  //    'no link' rule is SUPERSEDED, Sum 2026-08-23: "next tool in attach toolbox is url, we have
  //    jina now" — the clean read through the bolt, never a raw fetch; walled → paste the part.) ──
  // ── THE TIPS, LIFTED OUT (Sum 2026-08-17: "the tips aren't popping on bots, or wellness inputs,
  //    or learn inputs — all 3 need same tips just in time before click"). They used to live inside
  //    menu() as closures, so only the DROPDOWN had them; the three hand-rolled ROWS had none.
  //    Now one helper, one text table, four callers. Same flyout, same rule: it must paint BEFORE
  //    the click, because a screen capture freezes the webview and nothing shown after ever paints.
  const OZ_TIPS = {
    photo:  "uses the device's camera",
    screen: 'space to switch capture,\nalt/cmd + Tab to switch apps\nesc to cancel',
    file:   'search local disk',
  }
  let _tipEl = null
  const tipOff = () => { if (_tipEl) { _tipEl.remove(); _tipEl = null } }
  const tipOn = (item, text) => {
    tipOff()
    _tipEl = document.createElement('div')
    _tipEl.style.cssText = 'position:fixed;z-index:100;background:#fff;color:#000;border:2px solid;border-color:#404040 #dfdfdf #dfdfdf #404040;padding:6px 12px;font-size:var(--fs-ui);white-space:pre-line;pointer-events:none;max-width:260px'
    _tipEl.textContent = text
    document.body.appendChild(_tipEl)
    ozFit(_tipEl, item.getBoundingClientRect())
  }

  // ── STAY ON SCREEN (Sum 2026-08-17: "pop outs need rules to always be on screen, can move, can
  //    flip sides as needed"). Place beside the anchor, FLIP to whichever side has more room, then
  //    CLAMP all four edges. Measured after append — you cannot know the width until it is in the DOM.
  //    (The declarative version is CSS anchor positioning, `position-try-fallbacks: flip-inline`.
  //     Not in WKWebView, so this stays JS. Revisit for the Slint port, where it is a layout param.)
  //    Shared by the flyout AND the ＋ dropdown — both used to run off the right edge. ──
  function ozFit(el, r, below) {
    const PAD = 8, w = el.offsetWidth, h = el.offsetHeight
    const vw = window.innerWidth, vh = window.innerHeight
    let left, top
    if (below) {                                   // the dropdown: under the anchor, aligned left
      left = r.left; top = r.bottom + 2
      if (top + h > vh - PAD) top = r.top - h - 2  // no room under → flip above
    } else {                                       // the flyout: beside the anchor
      const roomRight = vw - r.right, roomLeft = r.left
      left = (roomRight >= w + PAD || roomRight >= roomLeft) ? r.right + 2 : r.left - w - 2
      top = r.top
    }
    el.style.left = Math.round(Math.max(PAD, Math.min(left, vw - w - PAD))) + 'px'
    el.style.top  = Math.round(Math.max(PAD, Math.min(top,  vh - h - PAD))) + 'px'
  }
  // wire a plain button (a row button, not a menu item) to the same flyout. act = photo|screen|file
  function tipWire(el, act) {
    const text = OZ_TIPS[act]; if (!el || !text) return el
    el.addEventListener('mouseenter', () => tipOn(el, text))
    el.addEventListener('mouseleave', tipOff)
    el.addEventListener('focus', () => tipOn(el, text))
    el.addEventListener('blur', tipOff)
    el.addEventListener('click', tipOff)
    return el
  }
  // any container holding [data-att] or [data-act] row buttons gets the tips in one call
  function tipRow(root) {
    if (!root) return
    root.querySelectorAll('[data-att],[data-act]').forEach(b => tipWire(b, b.dataset.att || b.dataset.act))
  }
  // ⭐ …but DELEGATION beats wiring every mount point. The snap row is injected as raw HTML in three
  //   places and the learn tools in a fourth; each would have to remember to call tipRow after render,
  //   and the one that forgot would silently have no tips — which is exactly the bug we are fixing.
  //   One listener on document, keyed off the SAME data-att/data-act the click handlers already use.
  //   Works for anything added later without a line of wiring.
  const tipTarget = e => {
    const el = e.target && e.target.closest && e.target.closest('[data-att],[data-act]')
    if (!el) return null
    const act = el.dataset.att || el.dataset.act
    return OZ_TIPS[act] ? { el, text: OZ_TIPS[act] } : null
  }
  document.addEventListener('mouseover', e => { const t = tipTarget(e); if (t) tipOn(t.el, t.text) })
  document.addEventListener('mouseout',  e => { if (tipTarget(e)) tipOff() })
  document.addEventListener('focusin',   e => { const t = tipTarget(e); if (t) tipOn(t.el, t.text) })
  document.addEventListener('focusout',  e => { if (tipTarget(e)) tipOff() })
  document.addEventListener('click',     e => { if (tipTarget(e)) tipOff() }, true)

  window.OZ_ATTACH = {
    screenshot: (sinkFile, note) => captureScreen(null, sinkFile, note),
    tips: OZ_TIPS, tipWire, tipRow,
    menu(anchor, sink) {
      const old = document.querySelector('.oz-plus-menu'); if (old) old.remove()
      const m = document.createElement('div'); m.className = 'oz-plus-menu'
      m.style.cssText = 'position:fixed;z-index:99;background:#fff;color:#000;border:2px solid;border-color:#404040 #dfdfdf #dfdfdf #404040;padding:2px;display:flex;flex-direction:column;min-width:190px'
      const r = anchor.getBoundingClientRect()
      m.style.left = Math.round(r.left) + 'px'; m.style.top = Math.round(r.bottom + 2) + 'px'
      // (2026-08-17) the menu ran off the right edge on a bar docked right — same fix, applied
      // after append below so it can be measured.
      // per-item FLYOUT (Sum, 15 Aug: "pop up as soon as I point at screenshot, pop out
      // RIGHT of it so it doesn't cover paper clip"). A box beside the dropdown — same
      // border as the menu itself, shown on hover OR keyboard focus, gone on leave.
      let tipEl = null
      const tipHide = () => { if (tipEl) { tipEl.remove(); tipEl = null } }
      const tipShow = (item, text) => {
        tipHide()
        tipEl = document.createElement('div')
        tipEl.style.cssText = 'position:fixed;z-index:100;background:#fff;color:#000;border:2px solid;border-color:#404040 #dfdfdf #dfdfdf #404040;padding:6px 12px;font-size:var(--fs-ui);white-space:pre-line;max-width:300px'
        tipEl.textContent = text
        const r = item.getBoundingClientRect()
        tipEl.style.left = Math.round(r.right + 2) + 'px'
        tipEl.style.top = Math.round(r.top) + 'px'
        document.body.appendChild(tipEl)
      }
      const mi = (txt, fn, tip) => {
        const b = document.createElement('button'); b.textContent = txt
        b.style.cssText = 'font-family:inherit;font-size:var(--fs-ui);text-align:left;padding:6px 10px;background:none;border:none;cursor:pointer;color:#000'
        b.addEventListener('click', e => { e.stopPropagation(); tipHide(); m.remove(); fn() })
        if (tip) {
          b.addEventListener('mouseenter', () => tipShow(b, tip))
          b.addEventListener('mouseleave', tipHide)
          b.addEventListener('focus', () => tipShow(b, tip))
          b.addEventListener('blur', tipHide)
        }
        return b
      }
      const pick = accept => {
        const i = document.createElement('input'); i.type = 'file'; if (accept) i.accept = accept
        i.style.display = 'none'; document.body.appendChild(i)
        i.addEventListener('change', () => { const f = i.files && i.files[0]; i.remove(); if (f) sink.file(f) })
        i.click()
      }
      // tips read BEFORE the click (Sum: "needs to open before screenshot does, cause
      // screenshot freezes screen" — the capture blocks the webview repaint, so nothing
      // shown after the click ever paints). Newlines are Sum's, verbatim.
      m.append(
        mi('📸 photo', () => pick('image/*'), OZ_TIPS.photo),
        mi('🖥️ screenshot', () => captureScreen(null, sink.file, () => sink.note && sink.note('screenshot canceled — or unavailable here.')),
          OZ_TIPS.screen),
        mi('📎 file', () => pick(''), OZ_TIPS.file),
        // 🔗 THE LINK DOOR (Sum 2026-08-23: "attach gets link… we have jina now, and if that fails, ask user to copy and
        // paste pertinent part"). The clean text becomes a plain .txt FILE and rides every existing rail (folder routing,
        // the doc card, read_file, the hand-off chain) — sink.file is the whole landing, nothing new to carry it.
        mi('🔗 link', async () => {
          const url = window.ozPrompt ? await window.ozPrompt('the link — we read it clean:', 'https://') : null
          if (!url || !/^https?:\/\//i.test(url)) { if (sink.note) sink.note('no link — nothing fetched.'); return }
          // the sniff at this door too (Sum 2026-08-28) — same youtube tee as the bar door above:
          // skip the ladder, land the marker, the bot asks the human before firing yt_transcript.
          const sn0 = window.OZ_LANE && window.OZ_LANE.sniff ? window.OZ_LANE.sniff(url) : { kind: 'url' }
          if (sn0.kind === 'youtube') {
            sink.file(new File(['FROM: ' + url + '\n\nA YOUTUBE VIDEO (id ' + sn0.id + '), not a page — the clean-read ladder was skipped on purpose.\nTHE PRIMED MOVE: yt_transcript saves its transcript to the library (lessons/transcripts/). ASK THE HUMAN FIRST — "want the transcript saved?" — then fire it on a yes and digest what comes back.'], 'link-youtube-' + sn0.id + '.txt', { type: 'text/plain' }))
            return
          }
          let text = ''
          try { text = await (window.OZ_CLEAN_READ ? window.OZ_CLEAN_READ(url) : Promise.reject(new Error('no clean read'))) } catch (e) {
            const why = (e && e.say) || ((e && e.blocked) ? 'a wall or a bouncer' : ((e && e.message) || 'no read'))
            const pasted = window.ozPrompt ? await window.ozPrompt('the site did not hand over the text (' + why + '). open it yourself, copy the pertinent part, paste it here:', '') : null
            if (!pasted || !pasted.trim()) { if (sink.note) sink.note('the read was walled and nothing was pasted — nothing attached.'); return }
            text = pasted.trim()
          }
          let host = 'page'; try { host = new URL(url).hostname.replace(/^www\./, '') } catch (_) {}
          const name = 'link-' + host.replace(/[^a-z0-9.-]/gi, '') + '.txt'
          sink.file(new File(['FROM: ' + url + '\n\n' + text], name, { type: 'text/plain' }))
        }, 'we read it clean;\nwalled → paste the part')
      )
      const close = e => { if (!m.contains(e.target)) { tipHide(); m.remove(); document.removeEventListener('mousedown', close) } }
      document.addEventListener('mousedown', close)
      document.body.appendChild(m)
      ozFit(m, anchor.getBoundingClientRect(), true)
    },
    // ── the THUMB + the LIGHTBOX (Sum, 15 Aug: "same code to show thumb that you can click
    //    on to expand as a card-over-view bigger than chat box or card — into chat room, same
    //    code as into convo"). ONE overlay at body level (the menu's own idiom, L177/L199) —
    //    over every card. Click or ESC closes. Styling inline like the menu; the thumb wears
    //    .att-img (attach.css L29) so room and convo look identical. ──
    lightbox(src, name) {
      const old = document.querySelector('.oz-lightbox'); if (old) old.remove()
      const v = document.createElement('div'); v.className = 'oz-lightbox'
      v.setAttribute('role', 'dialog'); v.setAttribute('aria-label', (name || 'picture') + ' — expanded. click, or press escape, to close')
      v.style.cssText = 'position:fixed;inset:0;z-index:120;background:rgba(0,0,0,.82);display:flex;align-items:center;justify-content:center;cursor:zoom-out'
      const i = document.createElement('img'); i.src = src; i.alt = name || ''
      i.style.cssText = 'max-width:94vw;max-height:94vh;background:#c0c0c0;padding:3px;border:2px solid;border-color:#dfdfdf #404040 #404040 #dfdfdf'
      const shut = () => { v.remove(); document.removeEventListener('keydown', onk) }
      const onk = e => { if (e.key === 'Escape') shut() }
      v.addEventListener('click', shut); document.addEventListener('keydown', onk)
      v.appendChild(i); document.body.appendChild(v)
    },
    thumb(src, name) {
      const i = document.createElement('img'); i.className = 'att-img'
      i.src = src; i.alt = name || 'shared picture'
      i.tabIndex = 0; i.setAttribute('role', 'button'); i.title = 'click to expand'
      return i
    },
    // the router, exported for other hosts (the room's porch) — one classifier, one map
    kindOf: kind,
    cardFor,
    easyImg: name => EASY_IMG.test(name),
    fileLink(key, card, label) {
      const b = document.createElement('button'); b.className = 'att-file'
      b.dataset.key = key; b.dataset.card = card
      b.textContent = label || key; b.title = 'click to open'
      return b
    }
  }
  // DELEGATED like the thumbs: any .att-file anywhere opens its card AND hands it the file —
  // preview via previewSandboxFile (webview.js L140), monaco via mcOpenSandbox (10-run.js —
  // the CLI's own open, exported), tiptap via tiptapReveal/tiptapNewDoc (tiptap.js L556-7).
  document.addEventListener('click', e => {
    const t = e.target.closest ? e.target.closest('.att-file') : null
    if (!t) return
    e.stopPropagation()
    const card = t.dataset.card, key = t.dataset.key
    openCard(card)
    const sb = (window.SANDBOX || {})[key]
    if (card === 'webview' && window.previewSandboxFile) window.previewSandboxFile(key)
    else if (card === 'monaco' && window.mcOpenSandbox) window.mcOpenSandbox(key)
    else if (card === 'tiptap' && window.tiptapReveal && !window.tiptapReveal(key) && window.tiptapNewDoc && sb && typeof sb.data === 'string') {
      const pre = document.createElement('pre'); pre.textContent = sb.data.slice(0, 60000)
      window.tiptapNewDoc(key, pre.outerHTML)
    }
  })
  // DELEGATED — any .att-img anywhere expands (convo, room, whatever host comes next): no
  // per-host wiring, which is the whole law. Keyboard rides along — every control named, every
  // control reachable (tabindex lives on thumbs; the convo's inline imgs carry it in their tag).
  document.addEventListener('click', e => {
    const t = e.target
    if (t && t.classList && t.classList.contains('att-img')) { e.stopPropagation(); window.OZ_ATTACH.lightbox(t.src, t.alt) }
  })
  document.addEventListener('keydown', e => {
    const t = e.target
    if ((e.key === 'Enter' || e.key === ' ') && t && t.classList && t.classList.contains('att-img')) { e.preventDefault(); window.OZ_ATTACH.lightbox(t.src, t.alt) }
  })

  // ── a picked/shot file: cache it, then route it ───────────────────────
  window.attachFile = function (bar, file) {
    const ext = (file.name.split('.').pop() || '').toLowerCase()
    const k = kind(file.name, file.type)
    const reader = new FileReader()

    reader.onload = () => {
      // code → code/<name> · docs → writing/<name> (the domain folders the bots are told to work under, so a +
      // attachment lands where they look). everything else keeps its plain name — images route to vision, calendar/
      // email/health to their cards, not the file-bot sandbox. (Sum, 2026-06-29 — folder jenga.)
      const folder = k === 'code' ? 'code/' : k === 'doc' ? 'writing/' : ''
      const key = folder + file.name
      window.SANDBOX[key] = { kind: k, ext, mime: file.type, data: reader.result }   // cached (code/docs folder-routed)

      const card = cardFor(k, ext)
      // THE HAND-OFF MARKER (2026-08-23): every landing — photo, file, link — tells the next turn's rules to ride the
      // bot's chain (conductor.js attachRules). Images ALSO keep OZ_VISION_PENDING (the pixels fold into the turn).
      window.OZ_ATTACH_PENDING = { agent: bar.dataset.agent, name: file.name, kind: k, key, at: Date.now() }
      if (k === 'image' && EASY_IMG.test(file.name)) {
        say(bar, `<div class="att-card">
          <img class="att-img" src="${reader.result}" alt="${esc(file.name)}" tabindex="0" role="button" title="click to expand">
          <div class="att-meta"><b>${esc(file.name)}</b><br><span class="att-dim">cached. a model with vision reads it — one without will say it can't see it.</span></div>
        </div>`)
        // VISION (Sum, 2026-06-28): stash the pixels for the NEXT turn — engine.attachVision folds them into the
        // user message IF the bot's model can see; a blind model drops them and just gets the "photo attached" note.
        window.OZ_VISION_PENDING = { agent: bar.dataset.agent, name: file.name, data: reader.result }
      } else if (k === 'image') {
        // an off-brand image the <img> tag can't chew (Sum: "a lot of off brand image formats
        // will open in preview") — a NAMED LINK instead of a thumb
        openCard('webview'); if (window.previewSandboxFile) window.previewSandboxFile(key)
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, 'webview', file.name)}<br><span class="att-dim">an odd image format — opened in 👀 preview. click the name to see it again.</span></div></div>`)
      } else if (k === 'code') {
        openCard('monaco'); openCard('webview')
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, card, file.name)}<br><span class="att-dim">opened in 🏁 monaco + 👀 preview. click the name to reopen — you've got a copy inline.</span></div></div>`)
      } else if (k === 'doc') {
        openCard(card)
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, card, file.name)}<br><span class="att-dim">opens in ${card === 'webview' ? '👀 preview' : '📄 tiptap'} — click the name, any time.</span></div></div>`)
      } else if (k === 'calendar') {
        openCard('calendar')
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, 'calendar', file.name)}<br><span class="att-dim">opened in 📅 calendar — cached. let's go over it together.</span></div></div>`)
      } else if (k === 'email') {
        openCard('email')
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, 'email', file.name)}<br><span class="att-dim">opened in ✉️ email — cached. let's go over it together.</span></div></div>`)
      } else if (k === 'health') {
        openCard('spa')
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, 'spa', file.name)}<br><span class="att-dim">opened in 🧘 wellness — cached. let's read it together.</span></div></div>`)
      } else {
        say(bar, `<div class="att-card"><div class="att-meta">${linkHTML(key, 'monaco', file.name)}<br><span class="att-dim">a <b>.${esc(ext)}</b> file — 🏁 monaco is the catch-all. click the name to open it.</span></div></div>`)
      }

      // FIRE ON UPLOAD (Sum, 2026-06-20): the drop IS a run. nudge the agent to react to the file it now
      // holds — per its own toolkit (wellness logs the plate · coder reads the code · PA files the doc).
      // echo off (the att-card already shows it). queues behind a live run via runTurn's FIFO.
      // tell the agent WHAT + WHERE it landed. it's ALWAYS shown (routing is by file-type, not the agent's
      // lane). so in-lane → act on it; out-of-lane → it's already open in its card, just say so and ask
      // what the user wants ("so what do you want me to do with this?") — never refuse, never fake-handle.
      const agentId = bar.dataset.agent
      if (agentId && window.runTurn && bar.querySelector('.msg-stream')) {
        const noun = { image: 'a photo', code: 'a code file', doc: 'a document', calendar: 'a calendar',
          email: 'an email export', health: 'health data' }[k] || 'a file'
        const where = { code: '🏁 monaco + 👀 preview', doc: '📄 tiptap', calendar: '📅 calendar',
          email: '✉️ email', health: '🧘 wellness' }[k]
        let msg = `I just attached ${noun}: ${file.name}${where ? ` — it's open in ${where} now` : ''}.`
        // INLINE THE CONTENT (Sum, 2026-06-28): text-y files (the readAsText branch below) carry their
        // contents in reader.result — hand them to the agent in THIS message so it can actually see the
        // file, not just a note that one exists. (was: only the note → the coder would try to "read" it,
        // which on a small model misfires into a web search.) capped; the full file stays in the sandbox.
        const isText = !(k === 'image' || k === 'other' || ext === 'zip' || ext === 'pdf')
        if (isText && typeof reader.result === 'string') {
          const lines = reader.result.split('\n'), CAP = 400
          const shown = lines.slice(0, CAP).join('\n')
          const tail = lines.length > CAP ? `\n…(${lines.length - CAP} more lines — the whole file is in the sandbox as "${key}"; read_file to see the rest)` : ''
          msg += `\n\nits contents (sandbox key "${key}"):\n\`\`\`${ext}\n${shown}${tail}\n\`\`\``
        }
        window.runTurn(bar, agentId, msg, { echo: false })
      }
    }

    // images / unknowns / binary health ZIPs → data URL to show/store; everything text-y (code · docs ·
    // .ics · .mbox · fit/health json) → text, to hand inline.
    if (k === 'image' || k === 'other' || ext === 'zip' || ext === 'pdf') reader.readAsDataURL(file)   // pdf as data URL — the preview iframe renders it natively
    else reader.readAsText(file)
  }

})()
