// card-reorder.js — drag-to-reorder the cards in #card-stack, STICKY across reloads. the WHOLE
// card head is the target: click = collapse (the head's own toggle), DRAG = reorder. a move
// threshold tells them apart; the trailing click is swallowed so a drag never also collapses.
// (Sum 2026-07-09) DRAG is COLLAPSED-ONLY — only a collapsed bar/rail reorders or moves between wings;
// an open card isn't draggable (kills the accidental-drag noise + the open-card-fouls-the-math backwardness).
// the ⠿ grip + ▾ triangle stay as visual HINTS only. modular + self-contained: a MutationObserver
// grips/orders every card as it mounts (makeCard OR custom). no library, no change to the builder.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the hoop — toss a card into it .............. search: "the hoop — toss a card"
//   persistence — the order is a list of card ... search: "persistence — the order"
//   observe the stack — grip new cards + slot ... search: "observe the stack"
//   the sortable — grab anywhere on the head .... search: "the sortable — grab"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for drag-to-reorder on `#card-stack`. It
//    **exports nothing but wires itself: `window.OZ_DOCK._save` (line 27) must be set by the
//    **docking system to persist card wing assignments, and `window.OZ_DOCK.toWing()`,
//    **`window.OZ_DOCK.toDesk()`, `window.OZ_DOCK.nearestEdge()` (lines 25, 110, 133, 135, 142)
//    **must exist. It also calls `window.toggleCard()` (line 134) to close cards and
//    **`window.syncSolo()` / `window.syncEmpty()` (lines 146, 148) to sync state after a card
//    **returns home.
//
//    **TOUCH HERE** —
//    - Change the localStorage key for card order → `ORDER_KEY` L13
//    - Change the localStorage key for card wing assignments → `DOCK_KEY` L14
//    - Change which elements can't start a drag → `NODRAG` L40
//    - Change the drag threshold (pixels before a mousedown becomes a drag) → `Math.abs()` checks
//    - L99
//    - Change the hoop's hit zone (the close target) → `overHoop()` L34–37
//    - Change the toast timeout → `setTimeout(close, 4500)` L164
//    - Change which card state is saved on drop → `saveOrder()` L51 and `applyOrderFor()` L60
//    - Change when a card is sent to a wing vs. the desk → `onPendingUp()` L120–151
//    - Change the visual feedback while dragging → `.card-dragging`, `.card-toss`, `.show`, `.hot`
//    - class toggles L101, 103, 106–107, 131
//
//    **TRAPS** —
//    - `ORDER_KEY` (L13) and `DOCK_KEY` (L14) are localStorage keys; renaming them orphans saved
//    - user order and wing state. Existing users will lose their layout.
//    - `dragging` (L42) is the single source of truth for whether a drag is in flight; it gates
//    - `applyOrder()` (L55) to prevent reordering while a card is mid-air, and gates
//    - `restoreDock()` (L78) to prevent teleporting a card to its wing while it's being moved.
//    - The `MutationObserver` (L74) must stay connected during `applyOrderFor()` (L68–70) or new
//    - cards won't be gripped/ordered. It is deliberately disconnected and reconnected around the
//    - reorder.
//    - `saveDock()` (L16) and `restoreDock()` (L22) are paired: `saveDock()` is wired to
//    - `window.OZ_DOCK._save` (L27) so the docking system calls it; `restoreDock()` is called on
//    - card mount (L78). If one is removed, wing state will not persist.
//    - Line 152 sets `justDragged = true` to swallow the trailing click after a drag ends; the
//    - document click listener (L182–184) must stay in CAPTURE phase or the head's collapse toggle
//    - will fire anyway.
//    - Line 117 checks `dragging.parentElement !== stack` to detect a card docked in a wing; this
//    - assumes cards in wings have a different parent. If wing cards move to a different DOM
//    - structure, this logic breaks silently.
//
//    **DO NOT** —
//    - Do not rename `stack`, `desk`, `hoop`, `obs`, `dragging`, `down`, `cards()`, `others()`
//    - without checking every reference; they are wired together.
//    - Do not change the shape of the saved order (a flat array of card IDs, L52) or dock map (an
//    - object `{cardId: 'left'|'right'|'center'}`, L19) without a migration path for existing
//    - localStorage.
//    - Do not move the `ensureGrip()` call (L84) or the `MutationObserver` setup (L83) to a
//    - different file; they must run once at startup.
//    - Do not add new persistence (e.g., card width, position) to this file; that belongs in the
//    - docking system or the card builder.
//    - Do not change the drag threshold or hoop geometry without testing on touch devices and slow
//    - networks.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const stack = document.getElementById('card-stack')
  if (!stack) return
  const desk = document.getElementById('desk')
  const ORDER_KEY = 'toto_card_order'
  const DOCK_KEY  = 'toto_card_dock'   // (Sum 2026-07-09) which WING each card is docked to (absent = the center desk)

  // ⭐ ONE-TIME ID MIGRATION (26 Aug) — the injection card's id changed from 'folder' to 'injection'.
  //    Both keys above store CARD IDS, so without this a human who had docked or reordered that card
  //    would silently lose its place and find it back on the default desk. A rename that costs someone
  //    their layout is not a free rename. Runs once, then leaves a stamp so it never runs again.
  try {
    if (localStorage.getItem('toto_card_id_v') !== 'folder2injection+aiol2aioli') {
      const o = JSON.parse(localStorage.getItem(ORDER_KEY) || 'null')
      const REN = { folder: 'injection', aiol: 'aioli' }   // 26 Aug: two card ids changed on one day
      if (Array.isArray(o)) localStorage.setItem(ORDER_KEY, JSON.stringify(o.map(x => REN[x] || x)))
      const d = JSON.parse(localStorage.getItem(DOCK_KEY) || 'null')
      if (d && typeof d === 'object') { Object.keys(REN).forEach(k => { if (d[k]) { d[REN[k]] = d[k]; delete d[k] } }); localStorage.setItem(DOCK_KEY, JSON.stringify(d)) }
      localStorage.setItem('toto_card_id_v', 'folder2injection+aiol2aioli')
    }
  } catch (_) {}
  const loadDocks = () => { try { return JSON.parse(localStorage.getItem(DOCK_KEY) || '{}') } catch (_) { return {} } }
  function saveDock(card) {
    if (!card || !card.dataset || !card.dataset.card) return
    const d = loadDocks(), id = card.dataset.card, edge = card.dataset.edge || 'center'
    if (edge === 'center') delete d[id]; else d[id] = edge
    try { localStorage.setItem(DOCK_KEY, JSON.stringify(d)) } catch (_) {}
  }
  function restoreDock(card) {   // on mount, send a card to its remembered wing
    if (!card || !window.OZ_DOCK) return
    const edge = loadDocks()[card.dataset && card.dataset.card]
    if (edge && card.parentElement && card.parentElement.id === 'card-stack') window.OZ_DOCK.toWing(card, edge)
  }
  ;(function wireSaver() { if (window.OZ_DOCK) window.OZ_DOCK._save = saveDock; else setTimeout(wireSaver, 50) })()   // OZ_DOCK persists a CARD's dock through this

  // ── the hoop — toss a card into it (bottom-center) to close it. shows only while dragging a card; kept
  //    small + centered so dragging down to the LEFT or RIGHT of it still reorders (it doesn't eat that). ──
  const hoop = document.createElement('div'); hoop.className = 'card-hoop'; hoop.setAttribute('aria-hidden', 'true')
  hoop.innerHTML = `<svg viewBox="0 0 64 60" fill="none" stroke="currentColor" stroke-width="2"><rect x="20" y="2" width="24" height="15" rx="2"/><rect x="28" y="6" width="8" height="6" stroke-width="1.4"/><ellipse cx="32" cy="20" rx="11" ry="3.5" stroke="#ff7a3c" stroke-width="2.6"/><path d="M22 21l4 13 6 3 6-3 4-13" stroke-width="1.2" opacity=".7"/><path d="M27 22l2 13M32 22v15M37 22l-2 13" stroke-width="1" opacity=".5"/></svg>`
  document.body.appendChild(hoop)
  function overHoop(e) {
    if (!hoop.classList.contains('show') || !e) return false
    const r = hoop.getBoundingClientRect()
    return e.clientX >= r.left - 6 && e.clientX <= r.right + 6 && e.clientY >= r.top - 10 && e.clientY <= r.bottom + 12
  }
  // head bits that must keep their own click/drag — never start a reorder from these
  const NODRAG = 'button, select, input, textarea, a, label, [contenteditable], .card-jewels, .card-stop, .mc-lights, .mc-wrecker, .mc-tab, .wv-tab'

  let dragging = null, down = null, justDragged = false
  const cards  = () => [...stack.querySelectorAll(':scope > .card')]
  const others = () => cards().filter(c => c !== dragging)

  // grip REMOVED (Sum: noise, like the ▾ arrow) — the whole head is already BOTH the drag-to-reorder AND the
  // click-to-collapse handle; the ⠿ hint was just clutter. kept as a no-op so the MutationObserver call is safe.
  function ensureGrip(card) { /* no grip — the whole top bar drags + collapses */ }

  // ── persistence — the order is a list of card ids; saved on drop, re-applied as cards mount. ──
  function saveOrder() {
    try { localStorage.setItem(ORDER_KEY, JSON.stringify(cards().map(c => c.dataset.card).filter(Boolean))) } catch (_) {}
  }
  function applyOrder() {
    if (dragging) return
    applyOrderFor(ORDER_KEY, '.card', 'card')
    applyOrderFor('toto_bot_order', '.agent-bar', 'agent')   // (Sum 2026-07-10) restore the bots' saved desk order too
  }
  // reorder ONE kind of stack child (cards by toto_card_order · bots by toto_bot_order) to its saved sequence.
  function applyOrderFor(key, sel, attr) {
    let saved; try { saved = JSON.parse(localStorage.getItem(key) || '[]') } catch (_) { saved = [] }
    if (!saved.length) return
    const els = [...stack.querySelectorAll(':scope > ' + sel)]
    const byId = {}; els.forEach(e => { if (e.dataset[attr]) byId[e.dataset[attr]] = e })
    const ordered = [], seen = new Set()
    saved.forEach(id => { const e = byId[id]; if (e) { ordered.push(e); seen.add(e) } })
    els.forEach(e => { if (!seen.has(e)) ordered.push(e) })
    obs.disconnect()
    ordered.forEach(e => stack.appendChild(e))
    obs.observe(stack, { childList: true })
  }

  // ── observe the stack — grip new cards + slot them into the remembered order. ──
  const obs = new MutationObserver(muts => {
    let added = false
    muts.forEach(m => m.addedNodes.forEach(n => {
      if (n.nodeType !== 1 || !n.classList) return
      if (n.classList.contains('card')) { ensureGrip(n); if (!dragging) restoreDock(n); added = true }   // (Sum) don't teleport a card to its remembered wing while it's being reordered
      else if (n.classList.contains('agent-bar')) { added = true }   // (Sum 2026-07-10) a bot mounted → re-apply the saved bot order
    }))
    if (added) applyOrder()
  })
  obs.observe(stack, { childList: true })
  cards().forEach(ensureGrip); applyOrder()

  // ── the sortable — grab anywhere on the head (not a control), pass the threshold → reorder. ──
  function onMove(e) {
    if (!dragging) return
    let before = null
    for (const c of others()) {
      const r = c.getBoundingClientRect()
      if (e.clientY < r.top + r.height / 2) { before = c; break }
    }
    before ? stack.insertBefore(dragging, before) : stack.appendChild(dragging)
  }
  function onPending(e) {
    if (!down) return
    if (!dragging) {
      if (Math.abs(e.clientX - down.x) < 6 && Math.abs(e.clientY - down.y) < 6) return   // still a click
      dragging = down.card
      dragging.classList.add('card-dragging')
      document.body.style.cursor = 'grabbing'; document.body.style.userSelect = 'none'
      hoop.classList.add('show')   // the hoop appears the moment a drag starts
    }
    const hot = overHoop(e)
    hoop.classList.toggle('hot', hot)
    dragging.classList.toggle('card-toss', hot)
    if (hot) { desk.classList.remove('docking'); delete desk.dataset.dockHint; return }   // aiming to close
    // (Sum 2026-07-09) over a WING? show the dock hint, don't reorder. over the center → reorder in the stack.
    const edge = (window.OZ_DOCK && window.OZ_DOCK.nearestEdge(e.clientX, e.clientY)) || 'center'
    if (edge !== 'center') { desk.classList.add('docking'); desk.dataset.dockHint = edge }
    // CENTER means two different things, and conflating them hid the basket (Sum 2026-07-21:
    // "never get the desk basket… traveler gets desk basket"). A card already on the desk →
    // center is a REORDER, so no basket. A card docked in a WING → center is COME HOME, so light
    // the 🦴 target the way a bot's drag does, and let the drop run toDesk (which clears the
    // remembered wing). Bars always set dockHint='center'; cards never did.
    else if (dragging.parentElement !== stack) { desk.classList.add('docking'); desk.dataset.dockHint = 'center' }
    else { desk.classList.remove('docking'); delete desk.dataset.dockHint; onMove(e) }
  }
  function onPendingUp(e) {
    document.removeEventListener('mousemove', onPending)
    document.removeEventListener('mouseup', onPendingUp)
    desk.classList.remove('docking'); delete desk.dataset.dockHint
    if (dragging) {
      const dunk = overHoop(e)
      const id = dragging.dataset.card
      const tEl = dragging.querySelector('.card-title'); const label = (tEl && tEl.textContent) || id
      const drop = dragging
      dragging.classList.remove('card-dragging', 'card-toss')
      document.body.style.cursor = ''; document.body.style.userSelect = ''
      hoop.classList.remove('show', 'hot')
      dragging = null
      const edge = (window.OZ_DOCK && window.OZ_DOCK.nearestEdge(e.clientX, e.clientY)) || 'center'
      if (dunk && id && window.toggleCard) { window.toggleCard(id, false); tossToast(id, label) }   // swish + an undo toast — nothing's lost
      else if (edge !== 'center' && window.OZ_DOCK) { window.OZ_DOCK.toWing(drop, edge) }            // (Sum) dock the CARD to a wing (one per wing)
      else {
        // BACK TO THE DESK. ⚠️ The live reorder (onMove) has usually ALREADY appended the card to the
        // stack by now, so the old `parentElement !== stack` guard skipped toDesk — which meant
        // saveDock never ran and the remembered WING survived. Next open, restoreDock threw the card
        // straight back into the wing. (Sum 2026-07-21: "open it again is back in wing sometimes.")
        // Now: if it isn't home, send it home; if it IS home but still carries a wing stamp, clear it.
        if (drop.parentElement !== stack && window.OZ_DOCK) window.OZ_DOCK.toDesk(drop)
        else if (drop.dataset.edge && drop.dataset.edge !== 'center') {
          drop.dataset.edge = 'center'
          drop.style.removeProperty('--ab-size')
          try { window.syncSolo && window.syncSolo() } catch (_) {}
          saveDock(drop)                                   // forget the wing — this is the bit that was missing
          if (window.syncEmpty) window.syncEmpty()
        }
        saveOrder()
      }
      justDragged = true; setTimeout(() => { justDragged = false }, 60)   // swallow the trailing click → no collapse
    }
    down = null
  }
  // the "are you sure" — non-blocking, because nothing's actually lost (state lives on disk; close = remove from desk)
  function tossToast(id, label) {
    const old = document.getElementById('card-toss-toast'); if (old) old.remove()
    const t = document.createElement('div'); t.id = 'card-toss-toast'; t.className = 'card-toss-toast'
    t.innerHTML = `<span>🏀 closed <b></b></span><button class="ctt-undo">undo</button>`
    t.querySelector('b').textContent = label
    document.body.appendChild(t)
    const close = () => t.remove()
    const tmr = setTimeout(close, 4500)
    t.querySelector('.ctt-undo').addEventListener('click', () => { clearTimeout(tmr); close(); if (window.toggleCard) window.toggleCard(id, true) })
    requestAnimationFrame(() => t.classList.add('show'))
  }
  desk.addEventListener('mousedown', e => {
    const head = e.target.closest('.card-head'); if (!head) return
    const card = head.closest('.card'); if (!card) return
    const home = card.parentElement                       // (Sum) drag a card from the desk stack OR from a wing
    if (!home || (home !== stack && !home.classList.contains('zone'))) return
    if (e.target.closest(NODRAG)) return                 // a control in the head — let it work
    // (Sum 2026-08-16: "drag open cards, not just collapsed — a confusing extra step") the collapsed-only gate of
    // 2026-07-09 is LIFTED. Its two reasons are both handled now: (1) accidental drag — the 6px dead-zone in
    // onPending tells click from drag; (2) a giant open card fouling the midpoint math — others() already skips
    // the dragged card, and the desk is one-open-at-a-time since 07-11 (expandCard collapses the rest), so no
    // OTHER open card is in the stack to foul it. Open or shut, the head is the grab.
    down = { card, x: e.clientX, y: e.clientY }
    document.addEventListener('mousemove', onPending)
    document.addEventListener('mouseup', onPendingUp)
  })
  // a drag just ended → eat the click in the CAPTURE phase, before the head's collapse toggle sees it
  document.addEventListener('click', e => {
    if (justDragged) { e.stopPropagation(); e.preventDefault(); justDragged = false }
  }, true)
})()
