// glyph.js — 🔤 THE ICON BEAN. ONE ICON, EVERY SKIN (rewritten 2026-08-17).
//   Sum: "lets make clinical and corporate start matching… I want it to change less as we build."
//   THE LADDER, applied on every skin in this order:
//       drawn art (PNG_MAP → svg preferred, png as backup)  →  glyph twin (MAP)  →  scrubbed
//   pngSwap runs FIRST and on ALL skins, replacing the emoji text node with an <img>. So MAP only
//   ever catches the emoji that have NO art yet, and every svg we draw retires its own MAP row.
//   Clinical/corporate are now a CSS TREATMENT (base.css: grayscale on [data-skin]), not a second
//   icon set — the old behaviour substituted three different looks for one button, which is exactly
//   the churn Sum asked us to stop. stripImgs/restoreImgs survive on disk but are NOT wired.
//   USER CONTENT IS NEVER TOUCHED — editors, inputs, chat logs, console output and code are SKIPped.
//   Slint-ready: PNG_MAP is the icon census for the native port, and svg paths port directly.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the TABLE — the SURE rows of EMOJI-SWAPS.md ... search: "the TABLE — the SURE"
//   where the law does NOT reach — user content ... search: "where the law does NOT"
//   THE PNG STRIP (Sum 2026-07-14 v2: "every ...... search: "THE PNG STRIP (Sum"
//   THE GENERIC SCRUB — any emoji NOT in the ...... search: "THE GENERIC SCRUB — any"
//   THE FANTASY SIDE (Sum 2026-07-14: "png over ... search: "THE FANTASY SIDE (Sum"
//   THE SKY (Sum-approved 2026-07-14: one cloud ... search: "THE SKY (Sum-approved"
//   the desk objects .............................. search: "the desk objects"
//   the DRAWN bubbles (Sum 2026-07-14: clean ...... search: "the DRAWN bubbles (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for glyph swapping rules on
//    **clinical/corporate skins (emoji → monochrome glyphs) and png swapping on fantasy skins. It
//    **exports `window.OZ_GLYPH` (line 212) with three tables: `sweep` (the main entry point),
//    **`MAP` (emoji-to-glyph mappings), and `IMG_GLYPH` (button icon filename stems to glyphs).
//
//    **TOUCH HERE** —
//    - Add a new emoji→glyph mapping → `MAP` object L15–33
//    - Add a new button icon filename → `IMG_GLYPH` object L73–78
//    - Add a new emoji→png mapping for fantasy skins → `PNG_MAP` object L128–141
//    - Add a new emoji→drawn shape (speech/thought bubbles) → `DRAWN` object L171
//    - Exclude a new editor/input type from glyph swapping → `SKIP` selector L37–39
//    - Change when the sweep runs → `schedule()` L205
//
//    **TRAPS** —
//    - `MAP`, `IMG_GLYPH`, and `PNG_MAP` keys must be exact emoji codepoints; if you add a variant
//    - selector (like `'☀️'` vs `'☀'`), it will silently fail to match. Line 34 and 142 build
//    - regexes from these keys — they must stay in sync.
//    - `DRAWN` (L171) and `DRAWN_RX` (L172) are a pair; if you add an emoji to one, add it to the
//    - other or it won't swap.
//    - `V` (L14) is the variation selector appended to some glyphs to force text presentation;
//    - removing it from a glyph will cause shape-shifters (U+26xx) to render as emoji on some
//    - platforms.
//    - `_wasClean` (L198) persists skin state across renders; if you change the `clean()` logic
//    - (L41), users switching skins mid-session may see orphaned `.gl-chip` elements or hidden
//    - images.
//    - `SKIP` (L37–39) is a CSS selector used in four places (L49, L59, L116, L148, L178); if you
//    - add a new user-content container, add it here or glyphs will swap inside it.
//    - The sweep runs on a 250ms debounce (L205); if you add a synchronous DOM walk that's
//    - expensive, it will block renders.
//
//    **DO NOT** —
//    - Do not rename `swapText`, `swapAttrs`, `scrubChrome`, `stripImgs`, `restoreImgs`, `pngSwap`,
//    - or `drawnSwap` without updating the calls in `sweep()` (L201–202).
//    - Do not move the `clean()` check (L41) or the skin observer (L209) — they control the entire
//    - mode switch.
//    - Do not add new emoji mappings to `MAP` without approval from Sum; this file documents only
//    - the "SURE rows" (L13 comment).
//    - Do not change the `em-ico` class name (L161) or `.gl-chip` class name (L95, L102) without
//    - updating the CSS that styles them (that lives elsewhere).
//    - Do not add logic to detect user content here; `SKIP` is the contract — if a new user-facing
//    - container exists, update `SKIP` instead of adding acceptNode filters.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'

  // ── the TABLE — the SURE rows of EMOJI-SWAPS.md (❓ rows wait for Sum; add approved rows here) ──
  const V = '︎'   // VARIATION SELECTOR-15 — forces TEXT presentation on 26xx shape-shifters
  const MAP = {
    '🖊': '✎', '🖋': '✎', '✏️': '✎', '✂️': '✂' + V,
    '⭐': '★', '🌟': '★', '✨': '✧', '⚡': '↯',
    '▶️': '▸', '◀️': '◂', '▶': '▸', '◀': '◂',
    '✔️': '✓', '❌': '✕', '⚠️': '⚠' + V, '⚙️': '⚙' + V,
    '🟢': '●', '🟡': '▲', '🔴': '■',                      // the jewel shapes ride along
    '✉️': '✉' + V,
    '📊': '▥',
    '↻': '↻', '🔧': '⚒' + V, '🎓': '∴',
    // the tiptap/writer toolbar family + common card chrome (Sum: "I still see emoticons in tip tap")
    '📖': '▤', '📚': '▤', '🗂': '▤',
    '🪶': '✎', '📌': '⌖', '🔗': '⧉', '🖼': '▦', '🎨': '◐', '🧺': '▣',
    '🤖': '⌬', '👤': '◉', '👥': '◉', '🧠': '☘', '🦴': '≡',
    '🎭': '◐', '🃏': '▤', '🂠': '▤', '📤': '⭱', '🔓': '⚿',
    '▾': '▾', '🕐': '◷', '⏰': '◷', '📈': '▥', '💼': '▥', 
  }
  const RX = new RegExp('(' + Object.keys(MAP).map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')', 'g')

  // ── where the law does NOT reach — user content + the editors + code ──
  const SKIP = '.monaco-editor, [contenteditable], input, textarea, pre, code, .mc-console-body, ' +
    '.mc-cli-out, .mc-tool-log, .mc-fix-log, .mc-sq-chat-log, .convo-screen, .mc-stream-body, ' +
    '.mc-preview-out, .mc-cfold-body, iframe'

  const clean = () => /^(clinical|corporate)$/.test(document.documentElement.dataset.skin || '')

  function swapText(root) {
    const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: n => {
        if (!n.nodeValue || !RX.test(n.nodeValue)) return NodeFilter.FILTER_REJECT
        RX.lastIndex = 0
        const p = n.parentElement
        if (!p || p.closest(SKIP)) return NodeFilter.FILTER_REJECT
        return NodeFilter.FILTER_ACCEPT
      },
    })
    const hits = []
    while (w.nextNode()) hits.push(w.currentNode)
    hits.forEach(n => { n.nodeValue = n.nodeValue.replace(RX, m => MAP[m]) })
  }
  function swapAttrs(root) {
    root.querySelectorAll('[title], [aria-label], [placeholder]').forEach(el => {
      if (el.closest(SKIP)) return
      ;['title', 'aria-label', 'placeholder'].forEach(a => {
        const v = el.getAttribute(a)
        if (v && RX.test(v)) { RX.lastIndex = 0; el.setAttribute(a, v.replace(RX, m => MAP[m])) }
        RX.lastIndex = 0
      })
    })
  }

  // ── THE PNG STRIP (Sum 2026-07-14 v2: "every button becomes a glyph, in every card" — clinical +
  //    corp carry ZERO pngs; oz/unicorn/bleep keep theirs like content packs). mechanism: every <img>
  //    inside a control is hidden and a CHIP takes its place — a mapped glyph where one exists, else
  //    the control's accessible name (the a11y bean already named every button — that work pays here).
  //    fully reversible: leaving the clean skins restores the imgs + drops the chips. ──
  const IMG_GLYPH = {   // filename stem → glyph (extend as approved; unmapped stems fall back to the name)
    gear: '⚙' + V, wrench: '⚒' + V, gradcap: '∴', minimap: '▦', dragrace: '◧', find: '⌕',
    sandbox: '▣', 'flag yellow': '⚑' + V, 'launch preview': '▸', devtools: '⌬', deck: '▤',
    strawberry: '+', blueberry: '−', cake: '+', potion: '−', 'gp': '⌗', drawer: '☰',
    greenroom: '◉', brain: '☘', stop: '■', paddock: '⌗', pitlane: '⌗',
  }
  function stripImgs(root) {
    root.querySelectorAll('button img, a img, [role="button"] img').forEach(img => {
      const btn = img.closest('button, a, [role="button"]')
      if (!btn || img.dataset.gl) return
      img.dataset.gl = '1'
      img.style.display = 'none'
      if (btn.querySelector('.gl-chip')) return
      const stem = (img.getAttribute('src') || '').split('/').pop().replace(/\.\w+$/, '').replace(/[-_]+/g, ' ').trim().toLowerCase()
      let face = IMG_GLYPH[stem]
      if (!face) {   // no glyph twin → the control's NAME, first REAL word (skip a/an/the — "The Port
        // Side View" chipped as just "The", which told nothing; Sum's screenshot 2026-07-23)
        const name = clnm(btn.getAttribute('aria-label') || btn.getAttribute('title') || stem)
        const words = name.split(/[ —·|-]+/).filter(Boolean)
        while (words.length > 1 && /^(the|a|an)$/i.test(words[0])) words.shift()
        face = (words[0] || '?').slice(0, 9)
      }
      const chip = document.createElement('span'); chip.className = 'gl-chip'; chip.textContent = face
      btn.appendChild(chip)
    })
  }
  const clnm = s => String(s || '').replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/gu, '').trim()
  function restoreImgs(root) {   // fantasy skins get their pngs back
    root.querySelectorAll('img[data-gl]').forEach(img => { img.style.display = ''; delete img.dataset.gl })
    root.querySelectorAll('.gl-chip').forEach(c => c.remove())
  }

  // ── THE GENERIC SCRUB — any emoji NOT in the MAP still can't survive on a clean skin's CHROME:
  //    inside buttons/labels/headers it's simply removed (the text label remains; if the button was
  //    emoji-ONLY, the a11y-derived name chip above carries it). user content (SKIP) stays sacred. ──
  const ANY_EMOJI = /[\u{1F000}-\u{1FAFF}]/gu
  function scrubChrome(root) {
    const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: n => {
        if (!n.nodeValue) return NodeFilter.FILTER_REJECT
        ANY_EMOJI.lastIndex = 0
        if (!ANY_EMOJI.test(n.nodeValue)) return NodeFilter.FILTER_REJECT
        const p = n.parentElement
        if (!p || p.closest(SKIP)) return NodeFilter.FILTER_REJECT
        if (!p.closest('button, a, [role="button"], .card-head, .card-title, h1, h2, h3, summary, label, .tb-btn')) return NodeFilter.FILTER_REJECT
        return NodeFilter.FILTER_ACCEPT
      },
    })
    const hits = []; while (w.nextNode()) hits.push(w.currentNode)
    hits.forEach(n => { ANY_EMOJI.lastIndex = 0; n.nodeValue = n.nodeValue.replace(ANY_EMOJI, '').replace(/  +/g, ' ') })
  }

  // ── THE FANTASY SIDE (Sum 2026-07-14: "png over emoticons — I like the png UI"): on oz/unicorn/
  //    bleep, approved emoji get their REAL png (shell/icons/) swapped in-place — Task A, one bean,
  //    every card, and the Slint port inherits a chrome with zero emoji. clouds join when approved. ──
  const PNG_MAP = {
    // ── THE SKY (Sum-approved 2026-07-14: one cloud + one sun, everything derived) ──
    '☀️': 'uv.png',                       // clear sky = the photoreal sun (the flat sun.png stays for the tracker)
    '🌤️': 'wx/mainly-clear.png', '⛅': 'wx/partly.png', '☁️': 'wx/overcast.png',
    '🌦️': 'wx/partly-rain-30.png', '🌧️': 'wx/raining.png',
    '🌨️': 'wx/snow-30.png', '❄️': 'wx/snow-50.png',
    '⛈️': 'wx/storm-rain.png', '🌫️': 'wx/fog.png',
    '🌑': 'moon-new.png', '🌒': 'moon-waxcres.png', '🌓': 'moon-firstq.png', '🌔': 'moon-waxgib.png',
    '🌕': 'moon-full.png', '🌖': 'moon-wangib.png', '🌗': 'moon-lastq.png', '🌘': 'moon-wancres.png',
    // ── the desk objects ──
    '💬': 'chat.png', '💭': 'thinking.png',
    '📎': 'paperclip.png', '📅': 'calendar.png', '🔒': 'padlock.png', '🔐': 'padlock.png',
    '🖨': 'printer.png', '🧹': 'broom.png', '💾': 'disk.png', '📂': 'open.png', '🗑': 'trash.png', '📥': 'import.png',
    // ── THE WELLNESS SET (2026-08-17). DRAWN (svg) where the object needed inventing; the three that
    //    already had art just point at it. one row here converts EVERY call site — 🔪 alone was 9. ──
    '🛒': 'grocery-list.svg',   // groceries = the LIST, not a cart. "no one uses grocery carts in 2050,
                               //   drones deliver it" — the motion (list → fetch) survives, the vehicle doesn't
    '🔪': 'prep-container.svg', // prep = the stackable box you fill for the week, not a knife
    '🩺': 'monitor.svg',        // the oscilloscope beans — a vitals monitor, traces + numbers
    '🍽': 'eat-now.svg',        // eat now = the bitten apple
    '🧘': 'journal.png',        // wellness overall = the leather journal the bot already wears
    '💪': 'muscle.png',         // the exercise profile — same sneaker its card head wears
    '🛏': 'bed.png', '🛏️': 'bed.png',
    // ── THE DEVICE FAMILY (2026-08-17) — one drawn set, five kinds, plus the PAIR button which is
    //    just two of them with a two-way arc. oz-handshake.js DEVICE_CLASSES is the roster. ──
    '📱': 'dev-phone.svg', '⌚': 'dev-watch.svg', '💍': 'dev-ring.svg',
    '🖥️': 'dev-desktop.svg', '🖥': 'dev-desktop.svg',
    '🕶️': 'dev-glasses.svg', '🕶': 'dev-glasses.svg',
    '🤝': 'pair-devices.svg',
    '📋': 'clipboard.svg', '📷': 'camera.svg', '📸': 'camera.svg', '🏁': 'flag.svg', '📝': 'note.svg', '🔍': 'search.svg', '📄': 'page.svg', '📃': 'page.svg',
    '🎯': 'target.svg', '💉': 'syringe.svg', '👀': 'eyes.svg', '🥗': 'salad.svg', '🍎': 'apple.png',      // DRAWN — supersedes the ⎘ glyph twin, now RETIRED from MAP. the pattern:
                               //   a drawn svg lands → its MAP row comes out. one icon, every skin.
  }
  const PNG_RX = new RegExp('(' + Object.keys(PNG_MAP).map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')')
  function pngSwap(root) {
    const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: n => {
        if (!n.nodeValue || !PNG_RX.test(n.nodeValue)) return NodeFilter.FILTER_REJECT
        const p = n.parentElement
        if (!p || p.closest(SKIP)) return NodeFilter.FILTER_REJECT
        return NodeFilter.FILTER_ACCEPT
      },
    })
    const hits = []; while (w.nextNode()) hits.push(w.currentNode)
    hits.forEach(n => {
      const frag = document.createDocumentFragment()
      let rest = n.nodeValue
      while (rest) {
        const m = rest.match(PNG_RX)
        if (!m) { frag.appendChild(document.createTextNode(rest)); break }
        if (m.index > 0) frag.appendChild(document.createTextNode(rest.slice(0, m.index)))
        const img = document.createElement('img')
        img.className = 'em-ico'; img.alt = ''; img.src = 'shell/icons/' + PNG_MAP[m[0]]
        frag.appendChild(img)
        rest = rest.slice(m.index + m[0].length)
      }
      n.parentNode.replaceChild(frag, n)
    })
  }

  // ── the DRAWN bubbles (Sum 2026-07-14: clean tier speech/thought are DRAWN, not glyphs) — two
  //    monochrome CSS shapes, currentColor, tail vs dot-trail = the same two-tails idea in line art ──
  const DRAWN = { '💬': 'gl-speech', '💭': 'gl-think' }
  const DRAWN_RX = /(💬|💭)/
  function drawnSwap(root) {
    const w = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: n => {
        if (!n.nodeValue || !DRAWN_RX.test(n.nodeValue)) return NodeFilter.FILTER_REJECT
        const p = n.parentElement
        if (!p || p.closest(SKIP)) return NodeFilter.FILTER_REJECT
        return NodeFilter.FILTER_ACCEPT
      },
    })
    const hits = []; while (w.nextNode()) hits.push(w.currentNode)
    hits.forEach(n => {
      const frag = document.createDocumentFragment()
      let rest = n.nodeValue
      while (rest) {
        const m = rest.match(DRAWN_RX)
        if (!m) { frag.appendChild(document.createTextNode(rest)); break }
        if (m.index > 0) frag.appendChild(document.createTextNode(rest.slice(0, m.index)))
        const sp = document.createElement('span'); sp.className = 'gl-drawn ' + DRAWN[m[0]]; sp.setAttribute('aria-hidden', 'true')
        frag.appendChild(sp)
        rest = rest.slice(m.index + m[0].length)
      }
      n.parentNode.replaceChild(frag, n)
    })
  }

  let _t = null, _wasClean = false
  function sweep() {
    try {
      // ⭐ ONE ICON, EVERY SKIN (Sum 2026-08-17: "lets make clinical and corporate start matching…
      //   I want it to change less as we build"). ART RUNS FIRST, on every skin — so a drawn icon is
      //   the SAME object everywhere and clinical/corporate just wear a CSS treatment (base.css:
      //   grayscale on [data-skin]). The old behaviour SUBSTITUTED a different icon set per skin,
      //   which is why a button looked like three different things. THE LADDER IS NOW:
      //       drawn art (svg · png)  →  glyph twin  →  scrubbed
      //   pngSwap replaces the text node with an <img>, so swapText below only ever sees the emoji
      //   that have NO art yet. Every svg we draw retires its MAP row automatically.
      //   ⚠ stripImgs/restoreImgs are NO LONGER CALLED — they hid your art and put text chips in its
      //   place. Kept on disk (the 5th R), not wired.
      if (_wasClean && !clean()) { restoreImgs(document.body); _wasClean = false }
      pngSwap(document.body)
      if (clean()) { swapText(document.body); swapAttrs(document.body); scrubChrome(document.body); drawnSwap(document.body); _wasClean = true }
    } catch (_) {}
  }
  function schedule() { clearTimeout(_t); _t = setTimeout(sweep, 250) }
  sweep()
  try {
    new MutationObserver(schedule).observe(document.body, { childList: true, subtree: true, characterData: true })
    new MutationObserver(schedule).observe(document.documentElement, { attributes: true, attributeFilter: ['data-skin'] })
  } catch (_) {}

  window.OZ_GLYPH = { sweep, MAP, IMG_GLYPH }   // the tables double as the Slint port's census
})()
