// lane-gofai.js — window.OZ_LANE · the TWO-LANE maze: CLI and JSON, best-first + a backup, GOFAI fallback.
//
// FOR HUMANS
//   the A/B settled it (2026-07-05, see [[jenga-cli-migration]]): a rule-following coder model is great at
//   STRUCTURED calls in EITHER language — but multi-line CONTENT splits them. a whole file / a page of prose is
//   unambiguous in JSON (escaping is a solved problem) and treacherous as a quoted CLI arg (one stray " or a
//   dropped newline and a 1B spirals). so we don't crown ONE language — we pick the RIGHT one per task, and keep
//   the other as a backup:
//     · a flat / structured move (rename · toggle · list · read · set one field) → CLI first  (leaner; both nail it)
//     · a big multi-line BLOCK (write a whole file · a page of prose · a long note) → JSON first (backup: a heredoc)
//   and if a lane doesn't land — the model mangles the quotes, the run errors, the call won't format — GOFAI
//   notices ("off track") and hands the bot the OTHER lane's tutorial. two roads through the maze, a guide at the
//   fork, a detour when one's blocked. the maze-not-model creed ([[maze-not-model-philosophy]]) applied to grammar.
//
// FOR AI
//   pick(kind)        → { first, backup, why }         the lane ORDER for a task kind ('content' | 'structured')
//   kindOf(action)    → 'content' | 'structured'        classify a concrete cmd STRING or a { tool, content } call
//   lintCli(cmd)      → { ok, issues, advice, tryLane }  the CLI content linter — the OFF-TRACK check, PRE-run
//   offTrack(cmd,rec) → { offTrack, advice, tryLane }    POST-run: blocked / errored / mangled → try the other lane
//   whenWhichClue()   → the short "you have both — here's when to use which" block (buildSystem, always-on)
//   cliContentClue()  → the JUST-IN-TIME heredoc tutorial (fed on an off-track content write; not always-on)
//
// pure + classic-JS + additive. no deps at load; reads nothing global. testable under node (module.exports).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the LANE MAP — which road first, which as ..... search: "the LANE MAP — which"
//   small readers ................................. search: "small readers"
//   kindOf — is this concrete action CONTENT (a ... search: "kindOf — is this"
//   quote balance — a heredoc body is DATA, ....... search: "quote balance — a"
//   lintCli — the CLI content linter. catches a ... search: "lintCli — the CLI"
//   offTrack — POST-run: did the bot get stuck? ... search: "offTrack — POST-run:"
//   the ALWAYS-ON clue — short, goes in ........... search: "the ALWAYS-ON clue"
//   the JUST-IN-TIME clue — the heredoc ........... search: "the JUST-IN-TIME clue"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — the two-lane routing logic for CLI vs JSON: which lane to try first for a given
//    **task kind, how to detect if a command is "content-heavy" vs "structured", and the linters
//    **that catch quote/heredoc mangling before a run fails. Exports `window.OZ_LANE` (or
//    **`module.exports` in Node) with `pick`, `kindOf`, `lintCli`, `offTrack`, `whenWhichClue`,
//    **`cliContentClue`, and the lane `MAP`.
//
//    **TOUCH HERE** —
//    - Change which lane is "first" for a task kind → `MAP` L29–31
//    - Change the heuristics for detecting a "content" task (multiline, long body, heredoc, quoted
//    - spans) → `kindOf()` L54–68, `isMultiline()` L36, `longBody()` L37, `hasHeredoc()` L38,
//    - `quotedBody()` L41–45
//    - Change what CLI commands are recognized as content-carrying → `CONTENT_CLI` regex L48
//    - Change what JSON tool names are recognized as content-carrying → `CONTENT_TOOL` regex L50
//    - Change the linting rules that flag unsafe CLI content → `lintCli()` L91–110
//    - Change the post-run failure detection (what counts as "off track") → `offTrack()` L114–129,
//    - specifically the `failedRun` condition L118–120
//    - Change the user-facing guidance text → `whenWhichClue()` L132–139 or `cliContentClue()`
//    - L142–153
//
//    **TRAPS** —
//    - `MAP` keys (`'content'`, `'structured'`) are the task kind names; they are read by `pick()`
//    - L33 and `kindOf()` L54–68. Renaming either key breaks the routing.
//    - `CONTENT_CLI` L48 and `CONTENT_TOOL` L50 are the source of truth for what counts as a
//    - "content" action; both `kindOf()` L61, L66 and `lintCli()` L96 depend on them. Change one
//    - without the other and the lane choice will contradict the lint.
//    - `stripHeredocBodies()` L71–82 must correctly parse heredoc markers (the regex on L77) or
//    - `unbalancedQuotes()` L83–86 will count quotes inside the body and give false positives. The
//    - marker-matching logic is load-bearing.
//    - `lintCli()` L91 returns `{ ok, issues, advice, tryLane }`; `offTrack()` L114 reads `lint.ok`
//    - and `lint.tryLane` L125–127. If you change the return shape, both callers break.
//    - `offTrack()` L114 is called POST-run with `(cmd, rec)` where `rec` is the execution record;
//    - it reads `rec.blocked`, `rec.refusedByHuman`, `rec.ran`, `rec.exit`, `rec.stdout`,
//    - `rec.stderr` L118–120. The caller must provide these fields or the failure detection
//    - silently passes.
//
//    **DO NOT** —
//    - Do not rename `pick`, `kindOf`, `lintCli`, `offTrack`, `whenWhichClue`, `cliContentClue` —
//    - they are the public API exported on L155–162.
//    - Do not move the lane logic into a different file; this file is the single source of truth
//    - for routing.
//    - Do not add state or side effects; the file is pure functions only.
//    - Do not change the regex flags or anchors in `CONTENT_CLI` L48 or `CONTENT_TOOL` L50 without
//    - testing against real commands; they are fragile.
//    - Do not add new task kinds to `MAP` without updating `kindOf()` to classify actions into
//    - those kinds.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  'use strict'

  // ── the LANE MAP — which road first, which as backup, per task kind. the A/B is the source of truth. ──
  var MAP = {
    content:    { first: 'json', backup: 'cli',  why: 'multi-line content is unambiguous in JSON; a CLI heredoc is the backup' },
    structured: { first: 'cli',  backup: 'json', why: 'a flat/structured op is leaner as a CLI command; JSON is the backup' }
  }
  function pick(kind) { return MAP[kind] || MAP.structured }

  // ── small readers ──
  function isMultiline(s) { return /\r?\n/.test(String(s == null ? '' : s)) }
  function longBody(s) { return String(s == null ? '' : s).length > 160 }   // ~2+ lines of real content
  function hasHeredoc(cmd) { return /<<-?\s*['"]?[A-Za-z_]\w*/.test(String(cmd == null ? '' : cmd)) }

  // the LARGEST quoted span in a command — the arg most likely to BE the content payload.
  function quotedBody(cmd) {
    var s = String(cmd == null ? '' : cmd), best = '', re = /"([^"]*)"|'([^']*)'/g, m
    while ((m = re.exec(s))) { var v = m[1] != null ? m[1] : m[2]; if (v.length > best.length) best = v }
    return best
  }

  // the CLI programs / shells that CARRY a body (a content write) vs the flat data ops.
  var CONTENT_CLI = /\b(ozfile\s+(?:write|add|edit)|ozdoc\s+(?:append|new|replace)|cat\s*>|tee\b|printf\b|echo\b[^|]*>)/i
  // the JSON beans that carry a body (conductor tool names).
  var CONTENT_TOOL = /^(?:write_file|add|find_replace)$/i

  // ── kindOf — is this concrete action CONTENT (a body) or STRUCTURED (flat args)? ──
  // accepts a CLI command STRING or a JSON call object { tool, content|new }.
  function kindOf(action) {
    if (action == null) return 'structured'
    if (typeof action === 'string') {
      var cmd = action
      if (hasHeredoc(cmd)) return 'content'
      var q = quotedBody(cmd)
      if (q && (isMultiline(q) || longBody(q))) return 'content'
      if (CONTENT_CLI.test(cmd) && (isMultiline(cmd) || longBody(cmd))) return 'content'
      return 'structured'
    }
    var tool = action.tool || ''
    var body = action.content != null ? action.content : (action.new != null ? action.new : '')
    if (CONTENT_TOOL.test(tool) && (isMultiline(body) || longBody(body))) return 'content'
    return 'structured'
  }

  // ── quote balance — a heredoc body is DATA, strip it before counting (its "…" don't count). ──
  function stripHeredocBodies(cmd) {
    var s = String(cmd == null ? '' : cmd)
    if (!hasHeredoc(s)) return s
    var lines = s.split('\n'), out = [], i = 0
    while (i < lines.length) {
      out.push(lines[i])
      var m = lines[i].match(/<<-?\s*(?:'([A-Za-z_]\w*)'|"([A-Za-z_]\w*)"|([A-Za-z_]\w*))/)
      if (m) { var mark = m[1] || m[2] || m[3]; i++; while (i < lines.length && lines[i].trim() !== mark) i++ }   // drop the body; the loop's i++ steps past the marker
      i++
    }
    return out.join('\n')
  }
  function unbalancedQuotes(cmd) {
    var s = stripHeredocBodies(String(cmd == null ? '' : cmd))
    return ((s.match(/"/g) || []).length % 2 !== 0) || ((s.match(/'/g) || []).length % 2 !== 0)
  }

  // ── lintCli — the CLI content linter. catches a model cramming a body into a fragile quoted arg. ──
  // this is the CLI analog of the JSON lane's linters: a deterministic GOFAI rule that flags "off track"
  // BEFORE the command runs, so a half-written file never lands. ok:true = the command is safe to run.
  function lintCli(cmd) {
    var s = String(cmd == null ? '' : cmd)
    var issues = []
    var heredoc = hasHeredoc(s)
    var q = quotedBody(s)
    var contenty = CONTENT_CLI.test(s) || (q && (isMultiline(q) || longBody(q)))

    if (!heredoc && unbalancedQuotes(s)) issues.push("unbalanced quotes — the content arg isn't closed (the classic multi-line mangle)")
    if (contenty && !heredoc && q && isMultiline(q)) issues.push('a multi-line body is crammed into a quoted arg — one stray quote breaks it')
    if (contenty && !heredoc && !isMultiline(q) && longBody(q)) issues.push('a long body in a quoted arg — a heredoc is safer')

    var ok = issues.length === 0
    return {
      ok: ok,
      issues: issues,
      advice: ok ? '' : cliContentClue(),
      // where to go instead: they skipped the heredoc → the JSON lane is the sure content path; a heredoc is the CLI fix.
      tryLane: ok ? '' : 'json'
    }
  }

  // ── kickJson — THE GOALIE KICKS IT IN (Sum 2026-08-25: "goalie gofai can format tool call from a
  //    very fuzzy prompt — kick it in the last few inches for a bot"). Bouncing a near-miss back costs a
  //    WHOLE round trip; most misses are inches. So before the goalie judges, it repairs — deterministically,
  //    no model call, pure rules.
  //    The trick that makes it honest: every clue carries a `template:` line, so the real argument names are
  //    already written down. GOFAI reads them off the tutorial instead of guessing. A rule only fires when
  //    it is UNAMBIGUOUS — one candidate, not the best of several — because a wrong repair is worse than a
  //    bounce: it runs the wrong act quietly.
  function templateOf(tool) {
    try {
      var clue = String((((typeof window !== 'undefined' && window.TOOL_USE) || {})[tool] || {}).clue || '')
      var i = clue.indexOf('template:'); if (i < 0) return null
      var j = clue.indexOf('{', i); if (j < 0) return null
      var depth = 0, k = j
      for (; k < clue.length; k++) { if (clue[k] === '{') depth++; else if (clue[k] === '}') { depth--; if (!depth) break } }
      return JSON.parse(clue.slice(j, k + 1))
    } catch (_) { return null }
  }
  // ── ⭐ nearTool — ONE HOME for the near-miss tool name (Sum 2026-09-01: "one character off is what we
  //    built goalie 2 of 4 for"). Lifted out of kickJson's body so the QUE lane can use the SAME matcher.
  //    It had been hand-rolled a second time over in conductor.js's paper-name salvage as a plain exact
  //    hash lookup — `use[token]` — which finds nothing when a single character is off. Two matchers for
  //    one job, and the weaker one was guarding the lane every carded bot walks on every tool turn.
  //    ⚠ DELIBERATELY STRICT: exactly ONE candidate or nothing. Two candidates is a guess, and a wrong
  //    tap-in fires the wrong tool — worse than handing back. Prefix either way, because both halves of
  //    the miss happen: a truncated name ("learn_read_sec") and an over-long one ("learn_read_sections").
  function nearTool(name) {
    var known = (typeof window !== 'undefined' && window.TOOL_USE) || {}
    var n = String(name == null ? '' : name).trim().toLowerCase()
    if (!n || !Object.keys(known).length) return ''
    if (known[n]) return n
    var near = Object.keys(known).filter(function (k) { return k.indexOf(n) === 0 || n.indexOf(k) === 0 })
    return near.length === 1 ? near[0] : ''
  }

  function kickJson(call, tool) {
    var fixed = []
    var t = String(tool || '')
    var known = (typeof window !== 'undefined' && window.TOOL_USE) || {}

    // an array with one call in it — models wrap when they think in batches
    if (Array.isArray(call) && call.length === 1) { call = call[0]; fixed.push('unwrapped a one-item array') }
    // the usual wrappers
    if (call && typeof call === 'object' && !Array.isArray(call)) {
      var keys = Object.keys(call)
      var WRAP = ['call', 'args', 'arguments', 'parameters', 'params', 'input']
      if (keys.length === 1 && WRAP.indexOf(keys[0]) > -1 && call[keys[0]] && typeof call[keys[0]] === 'object') {
        call = call[keys[0]]; fixed.push('unwrapped "' + keys[0] + '"')
      }
    }
    var tpl = templateOf(t)
    var argKeys = tpl ? Object.keys(tpl).filter(function (k) { return k !== 'tool' }) : []

    // a bare string, and the template takes exactly one argument — that string IS the argument
    if (typeof call === 'string' && argKeys.length === 1) {
      var v = call.trim(); call = {}; call[argKeys[0]] = v
      fixed.push('placed a bare value into "' + argKeys[0] + '"')
    }
    if (!call || typeof call !== 'object' || Array.isArray(call)) return { call: call, fixed: fixed }

    // we KNOW the tool — runnerBot was called with it. never make the bot say it twice.
    if (!call.tool && t) { call.tool = t; fixed.push('named the tool') }
    // a near-miss tool name, and exactly one candidate
    if (call.tool && !known[call.tool] && Object.keys(known).length) {
      var near = nearTool(call.tool)   // ⭐ 2026-09-01 — was inlined here; now shared with the que lane
      if (near) { fixed.push('"' + call.tool + '" \u2192 "' + near + '"'); call.tool = near }
      else if (t && known[t]) { fixed.push('"' + call.tool + '" \u2192 "' + t + '" (the tool it was asked for)'); call.tool = t }
    }
    // key aliases: exactly ONE template key unfilled and exactly ONE key we do not recognise → they are each other
    if (argKeys.length) {
      var given = Object.keys(call).filter(function (k) { return k !== 'tool' })
      var missing = argKeys.filter(function (k) { return call[k] === undefined })
      var strangers = given.filter(function (k) { return argKeys.indexOf(k) < 0 })
      if (missing.length === 1 && strangers.length === 1) {
        call[missing[0]] = call[strangers[0]]; delete call[strangers[0]]
        fixed.push('"' + strangers[0] + '" \u2192 "' + missing[0] + '"')
      }
    }
    return { call: call, fixed: fixed }
  }

  // ── lintJson — THE GOALIE ON THE JSON LANE (Sum 2026-08-25: "add lintjson like lintcli please").
  //    lintCli's own header calls itself "the CLI analog of the JSON lane's linters" — that analog was
  //    never written. The JSON lane went parseFence → JSON.parse → straight into the act, with nothing
  //    standing between the slim run and the world. This is that check, in lintCli's exact shape, and
  //    it is deliberately GOFAI: a handful of sharp deterministic rules, not a schema validator. Rules
  //    that cannot be sure say nothing — a false stop costs a whole round.
  //    THE ADVICE IS THE TOOL'S OWN CLUE. That is the point: a bot that mis-formats gets that one tool's
  //    tutorial handed straight back, just in time, exactly the way cliContentClue() works on the CLI
  //    side. Ask it what it wanted; do not tell it at the end that it failed.
  var PLACEHOLDER = /^(?:<[^>]*>|\.{3}|…|example\.com|https?:\/\/example|path\/to\b|your[-_ ]|filename\.\w+|the file|TODO|xxx+)$/i
  function lintJson(call, tool) {
    var issues = []
    var t = String(tool || (call && call.tool) || '')
    var known = (typeof window !== 'undefined' && window.TOOL_USE) || {}

    if (call === null || typeof call !== 'object' || Array.isArray(call)) {
      issues.push('that is not a call object — the ```call fence has to hold one flat JSON object')
    } else {
      if (!t) issues.push('no tool named — a call needs its tool, exactly as the template spells it')
      else if (Object.keys(known).length && !known[t]) {
        var near = Object.keys(known).filter(function (k) { return k.indexOf(t) === 0 || t.indexOf(k) === 0 })
        issues.push('"' + t + '" is not a registered tool' + (near.length ? ' — did you mean ' + near.slice(0, 3).join(' or ') + '?' : ''))
      }
      var keys = Object.keys(call).filter(function (k) { return k !== 'tool' })
      var filled = keys.filter(function (k) {
        var v = call[k]
        return v !== '' && v !== null && v !== undefined && !(typeof v === 'string' && PLACEHOLDER.test(v.trim()))
      })
      if (keys.length && !filled.length) issues.push('every argument is empty or still the template\u2019s placeholder — the values have to be the real ones')
      else keys.filter(function (k) { return filled.indexOf(k) < 0 && typeof call[k] === 'string' && PLACEHOLDER.test(String(call[k]).trim()) })
        .forEach(function (k) { issues.push('"' + k + '" is still a placeholder (' + call[k] + ') — fill it with the real value') })
    }

    var ok = issues.length === 0
    var clue = (!ok && t && known[t] && known[t].clue) ? String(known[t].clue) : ''
    return {
      ok: ok,
      issues: issues,
      // the tool's OWN tutorial, just in time — the JSON twin of cliContentClue()
      advice: ok ? '' : (clue ? 'here is that tool again, in full:\n' + clue : ''),
      // where to go instead: a call that will not shape up in JSON is often a plain flat op — the CLI is leaner
      tryLane: ok ? '' : 'cli'
    }
  }

  // ── offTrack — POST-run: did the bot get stuck? if so, hand it the OTHER lane. ──
  // "off track" = the pre-run lint failed, OR the run itself failed (blocked / refused / non-zero / an error string).
  function offTrack(cmd, rec) {
    rec = rec || {}
    var lint = lintCli(cmd)
    var out = String(rec.stdout == null ? '' : rec.stdout) + ' ' + String(rec.stderr == null ? '' : rec.stderr)
    var failedRun = !!rec.blocked || !!rec.refusedByHuman ||
      (rec.ran === true && typeof rec.exit === 'number' && rec.exit !== 0) ||
      /\berror\b|not found|no such|isn't in the sandbox|unknown oz command|couldn't|can't format/i.test(out)
    if (lint.ok && !failedRun) return { offTrack: false, advice: '', tryLane: '' }
    var lane = pick(kindOf(cmd))
    return {
      offTrack: true,
      advice: !lint.ok ? lint.advice
        : ('that command didn\'t land — do the same job in the ' + lane.backup.toUpperCase() + ' lane instead (' + lane.why + ').'),
      tryLane: !lint.ok ? (lint.tryLane || lane.backup) : lane.backup
    }
  }

  // ── the ALWAYS-ON clue — short, goes in buildSystem for a two-lane bot. "you have both; when to use which." ──
  function whenWhichClue() {
    return 'TWO LANES — you speak BOTH a CLI (```sh commands) and your JSON tools. use whichever fits, and if one ' +
      "doesn't land, don't hammer it — do the same job the other way:\n" +
      '· a flat/structured move (rename · toggle · list · read · set ONE field) → the CLI is leaner; reach for it first.\n' +
      '· a big multi-line BLOCK (a whole file · a page of prose · a long note) → your JSON write is unambiguous; ' +
      "prefer it. a CLI heredoc (<<'EOF' … EOF) is the backup.\n" +
      '· mangled quotes or an error back? switch lanes and redo it — that\'s the intended move, not a failure.'
  }

  // ── the JUST-IN-TIME clue — the heredoc tutorial, fed only when an off-track CONTENT write is caught. ──
  function cliContentClue() {
    return 'For MULTI-LINE content in the CLI, never cram a whole file into a quoted "…" arg — one stray quote and ' +
      'it breaks. Use a HEREDOC: the body is fenced by a marker, so nothing inside needs escaping:\n' +
      "```sh\n" +
      "ozfile write page.html <<'EOF'\n" +
      '<!DOCTYPE html>\n' +
      '<html> … the whole file, verbatim, quotes and all … </html>\n' +
      'EOF\n' +
      "```\n" +
      "the same shape drives the disk shell (cat > path <<'EOF' … EOF). or just use your JSON write_file — for a " +
      'whole file, that is the surest lane of all.'
  }

  // ── THE SNIFF (Sum 2026-08-28: "we need if url from youtube js gofai goalie on attach and convo —
  //    is url, is filepath, is code, is html — gofai on convo would be good tools too"). Pure
  //    string-smell, no model: what IS this text the human just handed over? attach.js asks it at the
  //    link door (a youtube link routes to yt_transcript instead of the clean-read ladder — a watch
  //    page strips to soup); anything else can ask it before guessing. Heuristics, honestly ranked:
  //    the first smell that lands wins, 'text' is the shrug at the bottom.
  function sniff(s) {
    s = String(s == null ? '' : s).trim()
    if (!s) return { kind: 'empty' }
    var yt = s.match(/(?:youtube\.com\/(?:watch\?[^#\s]*v=|shorts\/)|youtu\.be\/)([\w-]{6,20})/)
    if (yt) return { kind: 'youtube', id: yt[1] }
    if (/^https?:\/\/\S+$/i.test(s)) return { kind: 'url' }
    if (/^file:\/\//i.test(s) || (/^(~\/|\.{0,2}\/|\/)[\w.\-\/ ]+$/.test(s) && /\.\w{1,8}$/.test(s) && !/\s{2}/.test(s))) return { kind: 'filepath' }
    if (/<\s*(!doctype|html|head|body|div|p|table|a|img|h[1-6])\b/i.test(s) && /<\/|\/>/.test(s)) return { kind: 'html' }
    if (/(^|\n)\s*(function|const|let|var|class|import|def|fn|pub|#include|package)\b/.test(s) || /[;{}]\s*\n.*[;{}]/.test(s)) return { kind: 'code' }
    return { kind: 'text' }
  }


  // ── ⭐ lintReads — THE PROOF-OF-READ GOALIE (Sum 2026-08-30: "cant we make this a gofai check —
  //    did you read on 0z, not you?"). The write half has been guarded since the make-tool standard:
  //    a bean must declare a `readback`, and the surface answers instead of the bot. The READ half had
  //    nothing — a bot (or I) could name a path, a key, a signature that was never opened, and the
  //    sentence reads exactly like one that was. Reconstruction feels identical to recall from inside.
  //
  //    THE MOVE IS TO ASK 0z, NOT THE MODEL. Everything 0z ever handed this agent is on tape: the
  //    injection it compiled, the convo it stored, and every tool result it returned (OZ_CALLS). So:
  //        the reply names shell/tools.js:188
  //        → did that string EVER enter this agent's world through 0z, inside the recent window?
  //        → no  ⇒  it came from the weights. Flag it.
  //    Pure string containment over records we own. No model is consulted, so nothing here can be
  //    talked out of its answer. If the read was honest the check costs microseconds and says nothing —
  //    Sum's own point: "if it's right, it cost nothing."
  //
  //    ⚠ THE WINDOW IS THE WHOLE DESIGN (his): "like 10 turns, but then even best bot has drifted —
  //    give it a recent window to check." Evidence from 40 turns ago is not evidence: trimHist has
  //    long since cut it out of what the model can actually see, so a path from back there is being
  //    REMEMBERED, which is the exact failure this catches. A window that grows forever would bless
  //    every hallucination the moment its subject was mentioned once, an hour ago.
  //
  //    Returns { ok, unbacked:[…], checked:n }. It JUDGES; it never edits and never refuses — wiring
  //    is the caller's business (today: a count in the boot census, the same road the tool debt took).
  var PATHY = /\b((?:[\w.-]+\/){1,}[\w.-]+\.[A-Za-z]{1,5})(?::\d+)?\b/g
  function pathsIn(text) {
    var out = {}, m
    var s = String(text == null ? '' : text)
    PATHY.lastIndex = 0
    while ((m = PATHY.exec(s))) {
      var p = m[1]
      // ⚠ CHECK WHAT PRECEDES THE MATCH, not the match itself (caught in test): inside
      //    "https://0zhub.com/app/index.html" the regex captures "0zhub.com/app/index.html", which
      //    carries no scheme of its own — testing the capture alone let every URL through as a
      //    "claim about this repo". Look at the source text just before the hit instead.
      var before = s.slice(Math.max(0, m.index - 10), m.index)
      if (/(https?:)?\/\/$|@$/.test(before)) continue         // a URL or an email, not a repo path
      if (/^(https?:|data:)/.test(p)) continue
      if (/\.(com|org|net|io|dev|md5|sha)$/i.test(p)) continue // a bare domain slips through the shape
      out[p] = true
    }
    return Object.keys(out)
  }
  // the evidence 0z can vouch for, newest first, capped at `turns`
  function evidenceFor(agentId, turns) {
    var n = turns || 10, parts = []
    try {
      var hist = (window.engineHist && window.engineHist.load(agentId)) || []
      hist.slice(-n * 2).forEach(function (t) { parts.push(String(t && t.content || '')) })   // a turn is user+assistant
    } catch (_) {}
    try {
      var calls = (window.OZ_CALLS && window.OZ_CALLS.load(agentId)) || []
      calls.slice(-n * 3).forEach(function (c) {                 // a turn can fire several tools
        parts.push(String(c && c.msgs || ''))                    // what was SENT (the call args)
        parts.push(String(c && c.reply || ''))                   // what came BACK (the tool result)
        parts.push(String(c && c.extra || ''))                   // the injection it was compiled with
      })
    } catch (_) {}
    return parts.join('\n')
  }
  function lintReads(agentId, replyText, opts) {
    var turns = (opts && opts.turns) || 10
    var claimed = pathsIn(replyText)
    if (!claimed.length) return { ok: true, unbacked: [], checked: 0 }
    var seen = evidenceFor(agentId, turns)
    var unbacked = claimed.filter(function (p) { return seen.indexOf(p) < 0 })
    return { ok: unbacked.length === 0, unbacked: unbacked, checked: claimed.length }
  }

  var API = {
    MAP: MAP,
    lintReads: lintReads,
    pathsIn: pathsIn,
    pick: pick,
    sniff: sniff,
    nearTool: nearTool,   // the tap-in matcher — shared by kickJson and the que lane
    kindOf: kindOf,
    lintCli: lintCli,
    lintJson: lintJson,   // the goalie on the JSON lane — same shape, same contract
    kickJson: kickJson,   // the goalie's boot: repair the inches before you judge the shot
    offTrack: offTrack,
    whenWhichClue: whenWhichClue,
    cliContentClue: cliContentClue,
    // exposed for tests
    _quotedBody: quotedBody,
    _hasHeredoc: hasHeredoc,
    _unbalancedQuotes: unbalancedQuotes,
    _stripHeredocBodies: stripHeredocBodies
  }

  // ⚠ MERGE, DO NOT REPLACE (found 2026-08-16). Two unrelated subsystems both claim window.OZ_LANE:
  //   shell/oz-lane.js (index.html:186) is THE LANE WALL — folder · ownerOf · MOUNTS · canWrite · canRead,
  //   "the structural backstop under the permission ladder" — and this file (index.html:189) is the maze.
  //   This line was a bare assignment, so the maze loaded second and DELETED the wall on every boot:
  //   canWrite was never enforced, and tools.js:121 called canRead on undefined the moment OZ_ACTOR was
  //   set. The two APIs share no method names, so a merge restores both. Whoever loads first, both live.
  if (typeof window !== 'undefined') window.OZ_LANE = Object.assign(window.OZ_LANE || {}, API)
  if (typeof module !== 'undefined' && module.exports) module.exports = API

})()
