// onboard.js — 🚪 THE PER-BODY BUILD (Sum 2026-07-14: "per body build on onboarding, and a way to
//   get back to it"). first boot asks ONE question — "how do you drive?" — and 0z dresses itself
//   for that body: keyboard/switch → ⌖ focus mode on · shaky hands → ▮ chunky targets · big+clear
//   → zoom up (+ clinical is one tap away) · extra letter-air for dyslexic eyes. every choice is a
//   TOGGLE (bodies are combinations, not categories), all reversible in one tap, nothing is asked
//   twice. get back to it any time: window.OZ_ONBOARD.open() · the bot path `ozui onboard` (a lost
//   human can just ASK their bot to open it) · big type throughout (it must itself be accessible).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   PEAK SAAS (Sum 2026-07-14, final form): the ... search: "PEAK SAAS (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — the onboarding dialog that runs on first boot, asking "how do you drive?" and
//    **setting accessibility toggles. Exports `window.OZ_ONBOARD.open()` to reopen the dialog at
//    **any time. The five toggles (keyboard, chunky, bigger, airy, clinical) plus the Peak SaaS
//    **skin option are the complete set of body customizations this file controls.
//
//    **TOUCH HERE**
//    - Add a new toggle option → add row to `ROWS` array (L27), add `STATE` getter (L13), add
//    - `FLIP` setter (L20)
//    - Change toggle label or description text → edit the strings in `ROWS` (L27–33)
//    - Change what happens when a toggle is clicked → edit the corresponding function in `FLIP`
//    - (L20–26, L40–44)
//    - Change the dialog's opening question or instructions → edit the `innerHTML` template
//    - (L50–61)
//    - Change the "done" button text → edit L61
//    - Adjust the delay before first-boot dialog appears → change the `setTimeout` argument (L81)
//
//    **TRAPS**
//    - `K = 'oz_onboarded'` (L11) is the localStorage key that marks first boot as complete.
//    - Renaming it orphans all existing users and forces the dialog to reappear forever.
//    - `STATE` and `FLIP` keys must match exactly — if you add `['foo', ...]` to `ROWS` (L27), you
//    - must add `STATE.foo` (L13) and `FLIP.foo` (L20) with identical names, or clicks will fail
//    - silently (L69).
//    - `localStorage.setItem('oz_air', ...)` (L24) and the pre-launch read at L76 must use the same
//    - key, or the airy setting won't survive a page reload.
//    - The `data-ob` attribute on buttons (L55, L56) is read by the click handler (L68) — renaming
//    - it breaks toggle detection.
//    - `window.OZ_KBD`, `window.zoomBy`, `window.setSkin` are external APIs (L21, L23, L25, L41,
//    - L43) — if they don't exist, the toggle silently does nothing. No error is thrown.
//    - The Peak SaaS row (L56–59) is hardcoded separately from `ROWS` because it has custom markup
//    - and aria-label. Adding it to `ROWS` will break the glyph rendering.
//
//    **DO NOT**
//    - Do not move the `localStorage.setItem('oz_air')` logic (L24) or the pre-launch read (L76)
//    - without keeping them in sync.
//    - Do not rename `open`, `paint`, `done`, or `seen` — they are internal to the IIFE and safe to
//    - refactor, but `open` is exported as `window.OZ_ONBOARD.open` (L78), so that export name is
//    - load-bearing.
//    - Do not add new toggles by editing only `ROWS` — you must add matching `STATE` and `FLIP`
//    - entries or the toggle will not work.
//    - Do not change the dialog's HTML structure (role, aria attributes, class names) without
//    - checking the CSS file that styles it — that file is not shown here.
//    - Do not move the first-boot check (L80–81) into a different file — it must run in this
//    - module's scope to read `localStorage` before the dialog is created.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'

  const K = 'oz_onboarded'
  const isOn = fn => { try { return fn() } catch (_) { return false } }
  const STATE = {
    keyboard: () => isOn(() => window.OZ_KBD && window.OZ_KBD.on()),
    chunky:   () => document.body.classList.contains('chunky'),
    bigger:   () => isOn(() => parseFloat(localStorage.getItem('toto_zoom') || '1') >= 1.3),
    airy:     () => document.body.classList.contains('dyslexia-air'),
    clinical: () => (document.documentElement.dataset.skin === 'clinical'),
  }
  const FLIP = {
    keyboard: on => { if (window.OZ_KBD) window.OZ_KBD.set(on) },
    chunky:   on => { document.body.classList.toggle('chunky', on); try { localStorage.setItem('oz_chunky', on ? '1' : '0') } catch (_) {} },
    bigger:   on => { try { localStorage.setItem('toto_zoom', on ? '1.3' : '1') } catch (_) {} if (window.zoomBy) window.zoomBy(0) },
    airy:     on => { document.body.classList.toggle('dyslexia-air', on); try { localStorage.setItem('oz_air', on ? '1' : '0') } catch (_) {} },
    clinical: on => { if (window.setSkin) window.setSkin(on ? 'clinical' : 'oz') },
  }
  const ROWS = [
    ['keyboard', '⌖ keyboard or switch', 'no mouse — arrows walk, G grabs, Esc climbs out'],
    ['chunky',   '▮ steadier targets',   'fatter buttons and sliders — for shaky-hand days'],
    ['bigger',   '⊕ bigger everything',  'the whole app grows (the 🍓 buttons adjust it any time)'],
    ['airy',     'a i r y   l e t t e r s', 'extra space between letters and lines — easier reading'],
    ['clinical', '□ plain + high contrast', 'the clinical look — black on white, nothing fancy'],
  ]

  // ── PEAK SAAS (Sum 2026-07-14, final form): the LAST row, below high contrast — a washing-machine
  //    GLYPH + a dial-set-to-NORMAL GLYPH (both CSS-drawn, monochrome), then the words "Peak SaaS Skin"
  //    set in ACTUAL fine print. the joke is the row: for the normal-cycle crowd, "normal" = the dense
  //    dark corporate look at 80%. it's a toggle like everything else (off → back to oz at 100%). ──
  STATE.peaksaas = () => (document.documentElement.dataset.skin === 'corporate')
  FLIP.peaksaas = on => {
    if (window.setSkin) window.setSkin(on ? 'corporate' : 'oz')
    try { localStorage.setItem('toto_zoom', on ? '0.8' : '1') } catch (_) {}
    if (window.zoomBy) window.zoomBy(0)
  }

  function open() {
    if (document.getElementById('oz-onboard')) return
    const o = document.createElement('div'); o.id = 'oz-onboard'
    o.setAttribute('role', 'dialog'); o.setAttribute('aria-modal', 'true'); o.setAttribute('aria-label', 'how do you drive?')
    o.innerHTML = `<div class="oz-ob-box">
      <h2>how do you drive?</h2>
      <p>tap what fits — everything is a toggle, nothing is permanent, and this door reopens any time
      (ask your bot to "open my setup", or press ? for the key map).</p>
      <div class="oz-ob-rows">${ROWS.map(([id, big, small]) =>
        `<button class="oz-ob-row" data-ob="${id}" aria-pressed="false"><span class="oz-ob-big">${big}</span><span class="oz-ob-small">${small}</span></button>`).join('')}
        <button class="oz-ob-row oz-ob-saas" data-ob="peaksaas" aria-pressed="false" aria-label="Peak SaaS skin — the corporate look at 80 percent">
          <span class="oz-ob-saas-glyphs" aria-hidden="true"><span class="ob-washer"></span><span class="ob-dial-wrap"><span class="ob-dial-lbl">NORMAL</span><span class="ob-dial"></span></span></span>
          <span class="oz-ob-fineprint">Peak SaaS Skin</span>
        </button>
      </div>
      <button class="oz-ob-done">that's me — let's go</button></div>`
    document.body.appendChild(o)
    const paint = () => o.querySelectorAll('[data-ob]').forEach(b => {
      const on = STATE[b.dataset.ob]()
      b.classList.toggle('on', on); b.setAttribute('aria-pressed', on ? 'true' : 'false')
    })
    o.addEventListener('click', e => {
      const b = e.target.closest('[data-ob]')
      if (b) { FLIP[b.dataset.ob](!STATE[b.dataset.ob]()); paint(); return }
      if (e.target.closest('.oz-ob-done')) { try { localStorage.setItem(K, '1') } catch (_) {} o.remove() }
    })
    paint()
    const done = o.querySelector('.oz-ob-done'); if (done) setTimeout(() => done.focus(), 50)
  }

  try { if (localStorage.getItem('oz_air') === '1') document.body.classList.add('dyslexia-air') } catch (_) {}   // airy letters survive relaunch

  window.OZ_ONBOARD = { open }
  // first boot only — after that, the door is OZ_ONBOARD.open() / `ozui onboard` / the bot
  let seen = null; try { seen = localStorage.getItem(K) } catch (_) {}
  if (!seen) setTimeout(open, 600)   // let the desk paint first
})()
