// oz-map.js — OZ_MAP, the JENGA TOWER. a live dependency graph of the sandbox, built as a BYPRODUCT of the
// tools (never a bible you hope gets read). every write touches it; every read rides home with its
// neighborhood. arrows are DETERMINISTIC (regex over imports), not ML embeddings — exact, free, instant.
//
// the map lets a small model (a 3b) trace any file UP to the driver (index / .app) and DOWN to the 150-line
// skin, and — when it renames — name every file+line that references the thing (the cross-file multicursor).
// when an arrow points at a file that ISN'T in the sandbox, that's the map noticing the gap: ask for it.
//
// shape (all derived from ONE cache so touch(name) is truly incremental):
//   _out[name]  = [resolved sandbox keys this file pulls in]     ← the only thing we extract + cache
//   _miss[name] = [raw local-looking paths that DON'T resolve]   ← the "ask for it" list
//   in / roots / leaves / missing are DERIVED on demand from _out (+ live SANDBOX), so they never go stale.
// depends on: window.SANDBOX (fs.js). loads before tools.js so ctx.write can touch it. plain-browser safe.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the resolver: a raw ref from `src` → a ..... search: "the resolver: a raw ref"
//   extract every arrow out of one file ........ search: "extract every arrow out"
//   derivations (cheap, always fresh) .......... search: "derivations (cheap,"
//   trace UP to a driver (root) — follow one ... search: "trace UP to a driver"
//   the map, delivered as TEXT ................. search: "the map, delivered as"
//   refs(word): every file+line where an ....... search: "refs(word): every"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the live dependency graph of the
//    **sandbox. It exports `window.OZ_MAP`, a set of query and mutation functions that other tools
//    **(especially `ctx.write` in tools.js) call to keep the graph in sync as files change.
//
//    **TOUCH HERE**
//    - Add a new import/reference pattern (e.g., a new HTML attribute) → add regex to `RX` array
//    - L53–63
//    - Change how a raw path resolves to a sandbox key → `resolve()` L36–50
//    - Add a new derivation (e.g., "all files that import X") → add function alongside `callsOf`
//    - L84–89
//    - Change what the text output shows (line, tower, refs) → `line()` L104–112, `tower()`
//    - L114–131, `refs()` L134–142
//    - Exclude a file type from scanning → modify `CODE` regex L22
//
//    **TRAPS**
//    - `_out` and `_miss` (L16–17) are the only cached state; everything else derives from them.
//    - Renaming these breaks the contract stated in the file header (L10–11) and will orphan user
//    - data if persisted elsewhere.
//    - `extract()` (L64–79) is the only place that populates `_out` and `_miss`. If you change what
//    - it stores, `touch()` (L147) will silently produce stale results for files edited before the
//    - change.
//    - `prune()` (L81) is called at the start of every derivation (L84–89). If you add state that
//    - should survive file deletion, it will be wiped here.
//    - `ensure()` (L145) is called once on first read; `scan()` (L146) is a full rebuild. The
//    - `_scanned` flag (L18) gates the difference. If you add initialization logic, it must go in
//    - `ensure()`, not at module load.
//    - `resolve()` (L36) calls `SB()` (L20) to read the live sandbox. If the sandbox is mutated
//    - between calls, the graph can diverge. `touch()` (L147) is the only incremental update;
//    - anything else requires `scan()`.
//
//    **DO NOT**
//    - Rename `_out`, `_miss`, `_scanned`, or `SB` without updating the header comment (L10–12) and
//    - all call sites.
//    - Change the shape of `_out[name]` or `_miss[name]` without a migration strategy for persisted
//    - caches.
//    - Add synchronous I/O or network calls; this file must stay instant and browser-safe (L13).
//    - Move the regex patterns (L53–63) or the resolver logic (L36–50) into a separate file; they
//    - are tightly coupled to `extract()` and must stay here to keep incremental updates correct.
//    - Implement cycle detection or topological sorting here; that belongs in a separate analysis
//    - layer if needed.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const _out = Object.create(null)   // name → [resolved deps]
  const _miss = Object.create(null)  // name → [raw unresolved local paths]
  let _scanned = false

  const SB = () => window.SANDBOX || {}
  const isFile = v => v && typeof v === 'object' && typeof v.data === 'string' && v.kind !== 'url' && v.kind !== 'path'
  const CODE = /\.(html?|js|mjs|cjs|jsx|ts|tsx|css|vue|svelte)$/i   // files we scan for arrows (others are leaves)
  const keys = () => Object.keys(SB()).filter(n => isFile(SB()[n]))

  // ── the resolver: a raw ref from `src` → a sandbox key, or null (external), or {missing:raw} (local, absent) ──
  const EXTERNAL = /^(https?:)?\/\/|^data:|^mailto:|^tel:|^javascript:|^blob:|^#|^\{\{|^\$\{/i
  function norm(path) {                                   // resolve ./  ../  and //
    const parts = []
    for (const seg of path.split('/')) {
      if (seg === '' || seg === '.') continue
      if (seg === '..') { parts.pop(); continue }
      parts.push(seg)
    }
    return parts.join('/')
  }
  function resolve(src, raw) {
    let r = String(raw || '').trim().replace(/^['"`]|['"`]$/g, '').split(/[?#]/)[0].trim()
    if (!r || EXTERNAL.test(r)) return null                // external / template / anchor → not an edge
    const dir = src.indexOf('/') >= 0 ? src.slice(0, src.lastIndexOf('/')) : ''
    const cand = r[0] === '/' ? norm(r.slice(1)) : norm(dir ? dir + '/' + r : r)
    const sb = SB()
    if (isFile(sb[cand])) return cand                      // direct hit
    // bare-basename fallback — coder sandboxes are often flat; match a unique basename
    const base = cand.split('/').pop()
    if (base && base.indexOf('.') >= 0) {
      const hits = keys().filter(k => k.split('/').pop() === base)
      if (hits.length === 1) return hits[0]
    }
    return { missing: r }                                  // looks local, isn't here → ask for it
  }

  // ── extract every arrow out of one file (imports / script-src / link / css url / fetch / worker) ──
  const RX = [
    /\bimport\s+(?:[^'"`;]*?\bfrom\s*)?['"`]([^'"`]+)['"`]/g,   // import x from '…'  /  import '…'
    /\bimport\s*\(\s*['"`]([^'"`]+)['"`]\s*\)/g,                // dynamic import('…')
    /\brequire\s*\(\s*['"`]([^'"`]+)['"`]\s*\)/g,               // require('…')
    /<(?:script|iframe|img|source|audio|video)\b[^>]*?\bsrc\s*=\s*['"`]?([^'"`\s>]+)/gi,
    /<(?:link|a)\b[^>]*?\bhref\s*=\s*['"`]?([^'"`\s>]+)/gi,
    /@import\s+(?:url\()?\s*['"`]?([^'"`)\s]+)/gi,              // css @import
    /\burl\(\s*['"`]?([^'"`)\s]+)/gi,                          // css url(…)
    /\bfetch\s*\(\s*['"`]([^'"`]+)['"`]/g,                     // fetch('…')
    /\bnew\s+Worker\s*\(\s*['"`]([^'"`]+)['"`]/g,              // new Worker('…')
  ]
  function extract(name) {
    const f = SB()[name]
    if (!isFile(f) || !CODE.test(name)) { _out[name] = []; _miss[name] = []; return }
    const seen = new Set(), miss = new Set()
    for (const rx of RX) {
      rx.lastIndex = 0
      let m
      while ((m = rx.exec(f.data))) {
        const got = resolve(name, m[1])
        if (got == null) continue
        if (typeof got === 'string') { if (got !== name) seen.add(got) }
        else miss.add(got.missing)
      }
    }
    _out[name] = [...seen]; _miss[name] = [...miss]
  }

  function prune() { for (const k of Object.keys(_out)) if (!isFile(SB()[k])) { delete _out[k]; delete _miss[k] } }

  // ── derivations (cheap, always fresh) ──
  const callsOf    = n => (prune(), (_out[n] || []).slice())
  const calledByOf = n => (prune(), Object.keys(_out).filter(k => (_out[k] || []).includes(n)))
  const missingOf  = n => (_miss[n] || []).slice()
  const roots = () => { prune(); const called = new Set(); Object.values(_out).forEach(a => a.forEach(x => called.add(x))); return keys().filter(k => !called.has(k) && CODE.test(k)) }
  const leaves = () => { prune(); return keys().filter(k => !(_out[k] && _out[k].length)) }
  const allMissing = () => { prune(); const out = {}; for (const k of Object.keys(_miss)) (_miss[k] || []).forEach(r => (out[r] = out[r] || []).push(k)); return out }

  // ── trace UP to a driver (root) — follow one caller each hop, no cycles ──
  function traceUp(name) {
    const path = [name], seen = new Set([name])
    let cur = name
    for (let i = 0; i < 40; i++) {
      const up = calledByOf(cur).find(x => !seen.has(x))
      if (!up) break
      path.unshift(up); seen.add(up); cur = up
    }
    return path
  }

  // ── the map, delivered as TEXT ──
  function line(name) {                                    // one compact line — what read_file rides home with
    if (!isFile(SB()[name])) return `map: "${name}" isn't in the sandbox.`
    const calls = callsOf(name), by = calledByOf(name), miss = missingOf(name)
    const callStr = calls.length ? calls.join(' · ') : '(nothing — leaf)'
    const missStr = miss.length ? ` · ⚠ MISSING (ask for): ${miss.join(' · ')}` : ''
    const byStr = by.length ? by.join(' · ') : '(nothing points here — a root/driver)'
    const tr = traceUp(name)
    const trStr = tr.length > 1 ? `\n  trace: ${tr.join(' → ')}` : ''
    return `🗼 map · ${name}\n  calls: ${callStr}${missStr}\n  called-by: ${byStr}${trStr}`
  }
  function tower() {                                       // the whole jenga tower, from each driver down
    ensure(); prune()
    const rs = roots(), out = [`🗼 sandbox map — ${keys().length} files, ${rs.length} driver(s)`]
    const drawn = new Set()
    function walk(n, depth, seen) {
      if (depth > 12) return
      out.push('  '.repeat(depth + 1) + (depth ? '→ ' : '') + n + (leaves().includes(n) ? '  (leaf)' : '') + (drawn.has(n) && callsOf(n).length ? '  ↑(seen)' : ''))
      if (drawn.has(n)) return
      drawn.add(n)
      for (const c of callsOf(n)) { if (seen.has(c)) { out.push('  '.repeat(depth + 2) + '→ ' + c + '  ↻(cycle)'); continue } walk(c, depth + 1, new Set(seen).add(c)) }
    }
    ;(rs.length ? rs : keys()).forEach(r => walk(r, 0, new Set([r])))
    const orphans = keys().filter(k => !drawn.has(k))     // reachable from nothing we drew
    if (orphans.length) out.push(`\nnot wired to any driver: ${orphans.join(' · ')}`)
    const miss = allMissing(), mk = Object.keys(miss)
    if (mk.length) out.push(`\n⚠ referenced but NOT in the sandbox (ask for these): ${mk.map(r => `${r} (from ${miss[r].join(', ')})`).join(' · ')}`)
    return out.join('\n')
  }

  // ── refs(word): every file+line where an identifier appears — the cross-file multicursor's eyes ──
  function refs(word) {
    const esc = String(word).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const rx = new RegExp('\\b' + esc + '\\b')
    const hits = []
    for (const n of keys()) {
      if (!CODE.test(n)) continue
      SB()[n].data.split('\n').forEach((ln, i) => { if (rx.test(ln)) hits.push({ file: n, line: i + 1, text: ln.trim().slice(0, 80) }) })
    }
    return hits
  }

  function ensure() { if (!_scanned) { keys().forEach(extract); _scanned = true } }
  function scan() { for (const k of Object.keys(_out)) { delete _out[k]; delete _miss[k] } keys().forEach(extract); _scanned = true }
  function touch(name) { if (isFile(SB()[name])) extract(name); else { delete _out[name]; delete _miss[name] } }  // incremental, one file
  function forget(name) { delete _out[name]; delete _miss[name] }

  window.OZ_MAP = {
    ensure, scan, touch, forget,
    calls: callsOf, calledBy: calledByOf, missing: missingOf, allMissing,
    roots, leaves, traceUp, refs, line, tower,
    deps: name => ({ calls: callsOf(name), calledBy: calledByOf(name), missing: missingOf(name), trace: traceUp(name) }),
  }
})()
