// oz-perm.js — the PERMISSION TIER GATE (oz 4.2 reborn · Sum's refined ladder).
//
// Each bot has a standing trust TIER, dialed once in its bar — NO click-per-command within it. The GOFAI:
//   • within tier → it just runs, silently (no button, no ceremony).
//   • ABOVE its tier → the bot gets NO warning, NO refusal. The HUMAN sees a GLOWING GREEN BUTTON + exactly
//     what the bot wants; press to grant that one act. No press → it waits. (clioz-loop renders the button.)
//   • weird bot → knock it to read/talk. That boxes it to HIL-only: below 'cli' it can't delegate to other bots.
//   • god = the button is pre-pressed (unlocked "if you're crazy like me"); the rust cage still floors 1–4.
//
// The ladder (rank order): talk < read < cli(read+write your lane) < robot(oz-wide) < reach(read-out/server/copy-in) < god(push/save-out/delete).
// This file owns the MODEL + the DIAL. The gate DECISION is OZ_PERM.grants(); clioz-loop paints the green button.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   THE PNGs COME BACK (Sum 2026-07-30: "we ....... search: "THE PNGs COME BACK (Sum"
//   the CELESTIAL ORDER (Sum 2026-07-09) — rank ... search: "the CELESTIAL ORDER"
//   (Sum 2026-07-30) THE CONSULTANT SITS ABOVE .... search: "(Sum 2026-07-30) THE"
//   the DIAL — a perm dropdown in each bot's ...... search: "the DIAL — a perm"
//   ASK ROWS — the tiers above this bot's ......... search: "ASK ROWS — the tiers"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The permission tier system: which bots can run which commands without human
//    **approval. Exports `window.OZ_PERM` with tier names (`TIERS`), the decision function
//    **(`grants()`), tier ceilings per bot (`maxTier()`), and the dial UI (`setTier()`,
//    **`mountDial()`). The gate decision at line 118 (`grants()`) is called by clioz-loop to decide
//    **whether to show the green button.
//
//    **TOUCH HERE** —
//    - Add a new tier to the ladder → `TIERS` L17, then add its row to `OPT` L26–31 (icon + label),
//    - then update `requiredTier()` L108–116 to assign it to command classes.
//    - Change a bot's rank or ceiling → `RANK` L59 (rank) or `CEIL` L65 (explicit cap).
//    - Change what tier a command class requires → `requiredTier()` L108–116.
//    - Change the default tier a new bot starts at → `DEFAULT` L47.
//    - Add a new bot that can grant tiers to others → `RANK` L59 (give it rank ≥ 3 to use
//    - `canConfer()` L79).
//    - Revoke a human-granted ceiling lift → `ungrant()` L175 (already exported).
//
//    **TRAPS** —
//    - `TIERS` L17 is the source of truth for tier names. `rank()` L105 uses `indexOf()` on it, so
//    - order matters: tier 0 is weakest, tier 4 is strongest. Reordering breaks all saved
//    - permissions and the dial.
//    - `localStorage` keys at L70 (`ckey`) and L81 (`pkey`) are baked into user data. Changing the
//    - string `'toto_bot_'` orphans all saved tiers and ceiling grants.
//    - `tier()` L82 has a silent migration for the deleted 'read' tier — if you delete another
//    - tier, add a similar fallback or old bots will lose their setting.
//    - `requiredTier()` L108 and `grants()` L118 are a pair: the first defines what tier a command
//    - needs, the second checks if the bot has it. Both must use the same tier names.
//    - `maxTier()` L72 checks `granted()` before `CEIL` before `rankOf()` — this order is
//    - load-bearing. A human grant must beat a hardcoded ceiling (line 73 comment explains why).
//    - `paintDials()` L156 is called by `setTier()` L89 and must run after any tier change, or the
//    - button face won't update (see line 160 comment about the PNG→SVG migration bug).
//    - The `oz-perm-ask` class at L139 is CSS-coupled; renaming it breaks the escalation UI.
//
//    **DO NOT** —
//    - Do not change `ICON` L33 directly; it is built from `OPT` L26–31. Edit `OPT` instead.
//    - Do not add tiers above 'god' in `TIERS` — the comment at L51–55 explains that 'god' is the
//    - top rung a bot can be dialed to. The rank 6 (claude) is off the ladder by design.
//    - Do not move the `mountDial()` L122 or `scan()` L165 logic; they are wired to the DOM and
//    - MutationObserver at L168. If you need to change when dials are mounted, edit those lines,
//    - not the function bodies.
//    - Do not add new localStorage keys without a migration path in `tier()` L82 — old bots will
//    - silently lose their setting.
//    - Do not call `grantCeiling()` L96 from bot-facing code. It is exported for
//    - `shell/perm-escalate.js` only (line 92 comment).
//    - Do not change the `oz-perm` class or `.ab-head` selector — they are CSS-coupled and used by
//    - the DOM query at L125.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'
  // (Sum 2026-07-30) THE READ TIER IS GONE — "we don't need classes." It was never a separate rung:
  // its own label read "talk + read your lane", and ICON['talk'] was aliased to it. Two names, one floor.
  // Collapsed into `talk`, which is why ozhunga-assets/tier-icons holds exactly FIVE icons and no read.
  var TIERS = ['talk', 'cli', 'robot', 'reach', 'god']
  // (Sum 2026-07-09) rendered PNG icons now (was emoji). ⚡ god = ONLY toto + coder may be dialed there.
  // SVG now (was emoji-ish PNGs) — currentColor themes with the skin, crisp at any zoom, ~67KB
  // of PNG gone, and it ports to the sli build (Sum 2026-07-21). CSS sizes them (.oz-perm-ico svg).
  // FIVE named tiers (Sum 2026-07-21) — same GATES as before (requiredTier + maxTier unchanged), just
  // clearer names + icons. bubble=talk+read · pencil=write-your-lane (glow, you press) · pancakes=all
  // your tools (runs them) · telescope=read outside + pull a disk file into the sandbox (toto/coder/pa
  // ceiling) · god=push out / delete outside / irreversible (toto+coder ceiling). The old bare 'talk'
  // floor folds into bubble (ICON['talk'] = bubble) so a legacy dial still renders.
  var OPT = [
    ['talk',  '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M5 5h14a2 2 0 012 2v6a2 2 0 01-2 2h-7l-4 3.5V15H5a2 2 0 01-2-2V7a2 2 0 012-2z"/></svg>',  'talk + read your lane'],
    ['cli',   '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20l1.2-4.2L15.5 5.5a1.9 1.9 0 012.7 0l.3.3a1.9 1.9 0 010 2.7L8.2 18.8 4 20z"/><path d="M14 7.2l2.8 2.8"/></svg>',  'write your lane — the button glows, you press it'],
    ['robot', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="8" rx="7.2" ry="2.5"/><path d="M4.8 8v3c0 1.4 3.2 2.5 7.2 2.5s7.2-1.1 7.2-2.5V8M4.8 11.5v3c0 1.4 3.2 2.5 7.2 2.5s7.2-1.1 7.2-2.5v-3"/><path d="M11 6.4c.6-.8 1.4-.8 2 0"/></svg>', 'all your tools — it runs them for you'],
    ['reach', '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="M3.6 14l4.2-1.7 1.7 4.2-4.2 1.7z"/><path d="M7.8 12.3l7.4-3 1.7 4.2-7.4 3"/><path d="M15.2 9.3l2.6-1a1.4 1.4 0 011.8.8l.5 1.2-4.9 2"/><path d="M7.5 18l-1.2 3.2M4.6 21.2h4.4"/></svg>', 'read outside oz · search your disk \u2192 sandbox'],
    ['god',   '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M13 2 4 13h5l-1 9 9-12h-5l2-8z"/></svg>',   'push out · delete outside oz · truly irreversible  \ud83d\udd12'],
  ]
  var ICON = {}; OPT.forEach(function (o) { ICON[o[0]] = o[1] })
  // ── THE PNGs COME BACK (Sum 2026-07-30: "we made the png icons already · grep before carve").
  //    Six tier icons were generated and APPROVED — talk bubble · reading glasses · pencil · pancakes
  //    (full stack) · telescope (look out, bring back) · lightning bolt (irreversible) — and then the
  //    PNG→SVG migration of 2026-07-27 deleted every reference to them. Same migration that broke the
  //    dial (see the note below). The art never went anywhere; only the wiring did.
  //    THE RULE, in Sum's words: "png for oz and unicorn, draw or code, svg or css for clin and corp.
  //    just no emoji ever, every png gets a drawn version." So we ship BOTH and let CSS choose — the
  //    svg above IS the drawn version, and it was never the enemy. It was just wearing the wrong hat.
  var PNG = { talk: 'talk', cli: 'cli', robot: 'robot', reach: 'reach', god: 'god' }
  function ico(t) {
    return '<img class="oz-perm-png" src="shell/perm/perm-' + (PNG[t] || 'talk') + '.png" alt="">' +
           '<span class="oz-perm-svg">' + (ICON[t] || ICON.read) + '</span>'
  }
  // ⭐ OUT OF THE BOX A BOT HAS ITS HANDS (Sum 2026-08-25: "I want out the box defaults on all bots
  //    pancakes — all your tools inside 0z"). It shipped at 'talk' on a safety instinct that was aimed at
  //    the wrong thing: pancakes is oz-WIDE, and oz is the sandbox. Everything that leaves — push out,
  //    delete outside, anything irreversible — is god or is flagged irreversible, and irreversible asks at
  //    EVERY tier including god. So the floor was never protecting the outside world; it was just making
  //    every bot useless until the human found the dial, and then making the bot sound broken when asked
  //    why. A bot dialed lower still works — this is only where an unset one starts.
  var DEFAULT = 'robot'
  // ── the CELESTIAL ORDER (Sum 2026-07-09) — rank governs WHO MAY CONFER WHOM. As of 2026-08-25 it no
  //    longer sets the tier ceiling too; CEIL below owns that now, and the two were never the same question.
  //    toto = God · coder = Archangel · nurse + PA = first choir · wellness + tutor + writer = second choir ·
  //    provider cards (jem · asterix · aoladdin · muskett) = demigods (future). delegation flows DOWN /
  //    lateral, never up.
  //
  //    📋 SCOPED, NOT BUILT (Sum 2026-08-25, describing how it works — not a spec): "toto can tell other
  //    bots to do things, no other bot can initiate bot chats. they can only talk to each other in aioli,
  //    with vogel moderating, in a sandbox, that user can use dm to pull content from aioli into that bot's
  //    conversation history." The line below still reads rank-order down/lateral. Do not narrow it without
  //    him saying so — this note is knowledge, not a work order.
  // ── (Sum 2026-07-30) THE CONSULTANT SITS ABOVE THE LADDER, not on it.
  //    "you are quite literally a god to them, beyond lightning bolt — you control their entire reality."
  //    Which is exact: this one does not run tools inside oz, it REBUILDS OZ. It edits the source, writes
  //    the personas, and ships the binary they wake up in. `god` is the top rung a BOT can be dialled to
  //    (push out · delete outside oz · truly irreversible). 6 is not a taller rung — it is off the ladder.
  //    It is also NOT bleep. bleep is the joke: the bot that cannot say its maker's name. Different thing.
  //    Display consequence, and it is the right one: bleep() grawlixes this name on the way to screen, so
  //    the consultant shows up as ⊗@#$%&. The censor catching its own author is the gag working correctly.
  var RANK = { claude: 6, toto: 5, coder: 4, pa: 3, nurse: 3, wellness: 2, tutor: 2, writer: 2, jem: 1, asterix: 1, aoladdin: 1, muskett: 1 }
  function rankOf(bot) { return RANK[bot] != null ? RANK[bot] : 2 }   // unknown → second-choir default
  // ⭐ THE DIAL, IN SUM'S WORDS (2026-08-25): "only toto and coder can push out, the last god level. all the
  //    rest up to telescope." Then, same breath: "writer needs full tier" — publishing a finished work and
  //    updating a blog IS pushing out, so writer earns god by the job, not by rank.
  //
  //    ── CORRECTION, 27 Aug — WRITER NEVER GOT IT, AND THAT WAS RIGHT. Sum, asked to check: "toto and
  //    coder should have push out privileges, I think I put writer on that tier by mistake… put writer
  //    back on dria tier, all tools, and look no touch outside 0z."
  //    THE CODE ALREADY AGREED. CEIL below holds two names and has all along, so maxTier('writer') is
  //    'reach' — the same ceiling as dria, exactly what he now wants. It is this PARAGRAPH that was
  //    wrong, and the "only 3 push out" line under it, which counted a bot the table never had.
  //    Left standing rather than deleted, because prose that disagrees with the code is the trail:
  //    twice today I trusted a comment over the running app and was wrong both times.
  //    THE REASONING THAT REPLACES IT, and it is his: publishing is a JOB, not a TIER. When yanker
  //    comes to totois it becomes the publisher for the writer and the newsie — one bot that pushes
  //    out, taking the risk for both, instead of two bots each carrying the ability full time.
  //    That is the same shape as the containment argument three lines down: the bot that CAN push out
  //    does not go reading. A writer that reads sources and also publishes closes the loop by itself.
  //
  //    TELESCOPE IS THE DEFAULT (maxTier below returns 'reach'), because the containment here is not a
  //    height — it is a SHAPE. The bots that touch hostile text (the open web, the disk, the feeds) are
  //    read-only outside oz: nothing they read can ever leave. The bot that CAN push out does not go
  //    reading. Point toto at a poisoned page and it leaks; keep toto home and let the researchers read,
  //    and the loop never closes. That is the whole security argument, and it is structural.
  //
  //    ⭐ AND IT IS A BINARY (Sum 2026-08-25, revising himself mid-carve): "no special rule for newsie, I
  //    changed my mind. just push out or no push out, only 3 push out." So this table holds THREE NAMES and
  //    nothing else — every other bot is telescope, full stop.
  //    ⚠ COUNT THE TABLE: it holds TWO. The third was the writer, and it was never added — see the
  //    correction above, where Sum confirms two is the right number. "Only 3" is the stale half of that
  //    sentence; "just push out or no push out" is the half that is still exactly true. The card-bots' old robot caps are gone: a
  //    ceiling that says "this one may not look at the disk" was a second axis doing no work, since what a
  //    bot can actually touch is its TOOLS LIST. One question, one table.
  var CEIL = { toto: 'god', coder: 'god' }   // "all but toto coder who get one more level"
  // A HUMAN-GRANTED CEILING LIFT (Sum 2026-07-27) — the only way a bot ever exceeds its hardcoded cap,
  // and the key can only be written from inside an OZ_HIL green press (grantCeiling, below). Checked
  // FIRST and it beats CEIL on purpose: a deliberate human approval outranks a default, because in this
  // system the human is the final authority. No bot-facing code path can create this key.
  function ckey(bot) { return 'toto_bot_' + (bot || '') + '_ceil' }
  function granted(bot) { try { var g = localStorage.getItem(ckey(bot)); return (g && TIERS.indexOf(g) > -1) ? g : null } catch (_) { return null } }
  function maxTier(bot) {                               // the top of this bot's dial
    // ⭐ THE DIAL GOES TO TELESCOPE FOR EVERYONE (Sum 2026-08-25, after I broke this twice in one hour).
    //    Ceiling = reach for every bot; toto and coder get one more rung. The human TURNS THE DIAL to reach
    //    — it is not behind a green-press grant, and I put it there twice by misreading him.
    //    What he was actually describing, and what was already working: a bot cannot change its own tier,
    //    and neither can I from outside. "you couldn't change permissions remotely — that was working."
    //    THAT is the wall. It lives in setTier + the dial being a human control, not in the ceiling.
    var base = CEIL[bot] || 'reach'
    var g = granted(bot)
    // ⚠ A HUMAN GRANT ONLY EVER RAISES (fixed 2026-08-25, caught the hour it started biting). This used to
    //   `if (g) return g` — the grant simply replaced the ceiling. That was harmless while the defaults were
    //   LOW, because every grant was a lift. The moment the default rose to reach, every stale green-press
    //   from an older session became a CAP: Dria had a 'robot' lift banked from before, so raising the house
    //   default to telescope silently pinned her at pancakes, and she reported reach as still above her.
    //   A grant is a gift, never a leash. Take the higher of the two and the old lifts fall away on their own.
    return (g && rank(g) > rank(base)) ? g : base
    // NB: a bot's real fence is its TOOLS LIST, not its tier — tutor has no write_file, so 'reach' costs nothing.
  }
  function canConfer(from, to) { return from !== to && rankOf(from) >= rankOf(to) }   // down or lateral — NEVER up
  function opts(bot) { var mx = rank(maxTier(bot)); return OPT.filter(function (o) { return rank(o[0]) <= mx }) }   // dial shows only tiers ≤ ceiling
  function pkey(bot) { return 'toto_bot_' + (bot || '') + '_perm' }
  function tier(bot) { try { var t = localStorage.getItem(pkey(bot)); if (rank(t) > rank(maxTier(bot))) t = maxTier(bot); return TIERS.indexOf(t) > -1 ? t : DEFAULT } catch (_) { return DEFAULT } }
    // MIGRATION: bots saved before 2026-07-30 may hold 'read'. That rung no longer exists, so it
    // resolves to the floor it always was. Silent and idempotent — nobody loses a tier, nobody gains one.
  function setTier(bot, t) {
    if (TIERS.indexOf(t) < 0) return
    if (rank(t) > rank(maxTier(bot))) return             // can't dial a bot above its rank ceiling (⚡ god = toto/coder · 🔭 reach = first choir · …)
    try { localStorage.setItem(pkey(bot), t) } catch (_) {}
    paintDials()
    try { window.dispatchEvent(new CustomEvent('oz-perm', { detail: { bot: bot, tier: t } })) } catch (_) {}
  }
  // LIFT a bot's ceiling then dial it there — call ONLY from a human-approved OZ_HIL green press
  // (shell/perm-escalate.js). Without this, escalation is theater: setTier silently refuses anything
  // above maxTier, so an "approved" request would change nothing and the human would never know.
  // Also dials the bot up, because the point of asking was to USE the tier, not just be allowed it.
  function grantCeiling(bot, t) {
    if (TIERS.indexOf(t) < 0) return false
    try { localStorage.setItem(ckey(bot), t) } catch (_) {}
    setTier(bot, t)                                     // now permitted — the ceiling check above passes
    return true
  }
  // the tiers a bot CANNOT currently reach — what the dial's "ask for …" rows offer. Today opts() hides
  // these entirely, which is why a bot had no way to even REQUEST more trust (Sum: the real gap).
  function above(bot) { var mx = rank(maxTier(bot)); return OPT.filter(function (o) { return rank(o[0]) > mx }) }
  function rank(t) { return TIERS.indexOf(t) }

  // a clioz command class (+ context flags) → the TIER required to run it WITHOUT the green button.
  function requiredTier(klass, opts) {
    opts = opts || {}
    if (opts.outsideWrite || opts.irreversible) return 'god'      // save-out · overwrite · delete · push · deploy
    if (opts.outsideRead || opts.server) return 'reach'           // read outside oz · run a server · copy in
    if (opts.delegate) return 'cli'                               // talk to other bots (confer) = read+write tier+
    if (klass === 'read') return 'talk'   // a read-class command needs the floor, and the floor is talk
    if (klass === 'write') return 'cli'                           // write in your lane
    if (klass === 'sharp') return 'robot'                         // unknown/broad in-oz op
    return 'robot'                                                // 'denied' never runs (the rust cage); god is nominal
  }
  function grants(bot, klass, opts) { return rank(tier(bot)) >= rank(requiredTier(klass, opts)) }
  function canDelegate(bot) { return rank(tier(bot)) >= rank('cli') }   // below cli = HIL-only, no bot-to-bot

  // ── the DIAL — a perm dropdown in each bot's .ab-head (oz 4.2's `perm-btn` idiom) ──────────────────────
  function mountDial(bar) {
    try {
      if (!bar || bar._permWired || !bar.classList || !bar.classList.contains('agent-bar')) return
      var head = bar.querySelector('.ab-head'); if (!head) return
      var bot = ''; try { bot = bar.dataset && bar.dataset.agent } catch (_) {}
      if (!bot) return
      bar._permWired = true
      var wrap = document.createElement('div'); wrap.className = 'oz-perm'; wrap.dataset.bot = bot
      wrap.innerHTML =
        '<button type="button" class="oz-perm-btn" title="permission tier — how far this bot may reach"><span class="oz-perm-ico">' + ico(tier(bot)) + '</span></button>' +
        '<div class="oz-perm-menu">' + opts(bot).map(function (o) {
          return '<div class="oz-perm-opt' + (o[0] === tier(bot) ? ' on' : '') + (o[0] === 'god' ? ' god' : '') + '" data-t="' + o[0] + '"><span class="oz-perm-ico">' + ico(o[0]) + '</span> ' + o[2] + '</div>'
        }).join('') +
        // ── ASK ROWS — the tiers above this bot's ceiling. Picking one does NOT set it: it raises an
        //    OZ_HIL request and only your green press grants it. Before this, opts() hid these entirely,
        //    so a bot had no way to ask for more trust at all — there was no path upward. (Sum 2026-07-27)
        above(bot).map(function (o) {
          return '<div class="oz-perm-opt oz-perm-ask" data-ask="' + o[0] + '" title="above this bot\'s ceiling — asks for your OK, it cannot grant itself"><span class="oz-perm-ico oz-perm-dim">' + ico(o[0]) + '</span> <span style="opacity:.7">ask for ' + o[0] + '</span> <span style="opacity:.45">↑ needs your OK</span></div>'
        }).join('') + '</div>'
      var btn = wrap.querySelector('.oz-perm-btn')
      wrap.addEventListener('mousedown', function (e) { e.stopPropagation() })   // the WHOLE dial (button + dropdown options) is NOT a drag/collapse handle — picking a tier must never fold the bar
      btn.addEventListener('click', function (e) { e.stopPropagation(); wrap.classList.toggle('open') })
      wrap.addEventListener('click', function (e) {
        var o = e.target.closest('.oz-perm-opt'); if (!o) return
        e.stopPropagation()
        // an ASK row never sets a tier — it posts the request and waits for the human's green button.
        if (o.dataset.ask) { try { window.OZ_ESCALATE && window.OZ_ESCALATE.request(bot, o.dataset.ask, 'asked from the dial') } catch (_) {} }
        else setTier(bot, o.dataset.t)
        wrap.classList.remove('open')
      })
      var anchor = head.querySelector('.ab-mic') || head.querySelector('.ab-ear') || head.querySelector('.ab-esp') || head.querySelector('.ab-fill')
      if (anchor) head.insertBefore(wrap, anchor); else head.appendChild(wrap)
    } catch (_) {}
  }
  function paintDials() {
    try {
      document.querySelectorAll('.oz-perm').forEach(function (w) {
        var t = tier(w.dataset.bot), b = w.querySelector('.oz-perm-btn')
        var bi = b && b.querySelector('.oz-perm-ico'); if (bi) bi.innerHTML = ico(t)   // SVG now, not <img> (Sum 2026-07-27: the dial 'did nothing' — setTier fired + saved, but this // still queried an <img> that the PNG→SVG migration deleted, so the button face never repainted)
        w.querySelectorAll('.oz-perm-opt').forEach(function (o) { o.classList.toggle('on', o.dataset.t === t) })
      })
    } catch (_) {}
  }
  function scan() { try { document.querySelectorAll('.agent-bar').forEach(mountDial) } catch (_) {} }
  document.addEventListener('click', function () { document.querySelectorAll('.oz-perm.open').forEach(function (w) { w.classList.remove('open') }) })
  if (document.readyState !== 'loading') scan(); else document.addEventListener('DOMContentLoaded', scan)
  try { new MutationObserver(scan).observe(document.documentElement, { childList: true, subtree: true }) } catch (_) {}

  window.OZ_PERM = {
    TIERS: TIERS, ICON: ICON, tier: tier, setTier: setTier, rank: rank,
    requiredTier: requiredTier, grants: grants, canDelegate: canDelegate,
    rankOf: rankOf, maxTier: maxTier, canConfer: canConfer,   // the celestial order
    label: function (t) { var r = null; OPT.forEach(function (o) { if (o[0] === t) r = o[2] }); return r || t },   // the rung's plain English — so a bot can be told where it stands in words, not a rank number
    above: above, granted: granted, grantCeiling: grantCeiling,   // escalation: ask · what was granted · the human's yes
    ungrant: function (bot) { try { localStorage.removeItem(ckey(bot)) } catch (_) {}; setTier(bot, maxTier(bot)); paintDials() },   // take the lift back
    strip: function (bot) { setTier(bot, 'talk') }   // the "smell smoke" leash
  }
})()
