// registry.js — THE MASTER LISTS. one source for providers · models · skins · agents.
// every picker READS from here; every ＋ add button PUSHES here; the registry fires a change
// and open pickers re-render. the data twin of the builders: makeCard/makeAgent build the
// chrome, REG holds the lists they choose from. loaded FIRST so settings · injection · topbar
// all share it. browser-only (localStorage), no server of ours.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   providers — a saved key unlocks a provider; ... search: "providers — a saved key"
//   IMAGE providers (Sum 2026-07-27 — diversify ... search: "IMAGE providers (Sum"
//   SHELF PLAN (not built — note only) ............ search: "SHELF PLAN (not built"
//   skins — the 4 GLOBAL app-skins lead (oz ....... search: "skins — the 4 GLOBAL"
//   the agent roster — built-ins + customs ........ search: "the agent roster"
//   the fruit basket: providers-as-characters. .... search: "the fruit basket:"
//   pub/sub — pickers subscribe; an add/remove .... search: "pub/sub — pickers"
//   the add buttons push here (and persist) → ..... search: "the add buttons push"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the five master lists: `providers` (API
//    **keys + rate limits), `modelsByProvider` (curated model names per provider), `skins` (UI
//    **themes), `agents` (bot roster), and custom agents persisted in localStorage. Everything
//    **exported as `window.REG` and aliased as `window.AGENTS_ROSTER` (line 145).
//
//    **TOUCH HERE** —
//    - Add or remove a provider → edit `providers` array L15–33, then add its models to
//    - `modelsByProvider` L35–56.
//    - Change a model name or add new ones to a provider → `modelsByProvider` L35–56.
//    - Add a new built-in agent → `agents` array L92–112.
//    - Add a new global skin → `skins` array L87.
//    - Change rate limits or pricing tier for a provider → the `rpm`, `tpm`, `pay` fields in
//    - `providers` L15–33.
//    - Restrict an agent to specific providers (e.g., Jem to Gemini only) → edit
//    - `window.AGENT_DATA[id].providers` in agents.gen.js, NOT here; `agentProviders()` L70 reads
//    - it.
//
//    **TRAPS** —
//    - `localStorage.getItem('toto_' + id + '_key')` L66: the key prefix `'toto_'` is load-bearing;
//    - renaming it orphans all saved API keys.
//    - `localStorage.getItem('toto_custom_agents')` L114: same; renaming breaks custom agent
//    - persistence.
//    - `modelsByProvider[provider]` L137: if you add a provider to `providers` but forget to add it
//    - to `modelsByProvider`, `addModel()` will silently create an empty array instead of failing
//    - loudly.
//    - Line 116: custom agents are merged into the `agents` array at load time; if a custom agent's
//    - `id` matches a built-in, the built-in wins and the custom is ignored.
//    - `agentProviders()` L70 returns `null` if `window.AGENT_DATA` is not yet defined;
//    - `availableModels()` L77 treats `null` as "no fence" (all providers allowed). If AGENT_DATA
//    - loads after REG, the fence is ignored until a re-render.
//
//    **DO NOT** —
//    - Do not rename `window.REG` or `window.AGENTS_ROSTER`; they are read by settings.js,
//    - injection.js, topbar.js, and the woodshop.
//    - Do not move agent icon paths; they are relative to the agents/ folder and read by the UI at
//    - render time.
//    - Do not add agent metadata (skin, convo, edge config) here; that lives in workspace.js
//    - `AGENT_BARS` L91.
//    - Do not add provider auth logic or API call logic; that belongs in engine.js and the provider
//    - bridge files.
//    - Do not persist new fields to `toto_custom_agents` without a migration plan; the shape is `{
//    - id, label }` only L127.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


window.REG = (function () {
  // ── providers — a saved key unlocks a provider; its models become pickable. ──
  // rpm · tpm = the free-tier (or entry-tier) requests/min + tokens/min. the conductor reads these to
  // PACE its calls under the limit (engine.js provPace) — a 429 is a burst, not heavy use, so we space.
  // pay — the pricing tier, rendered as a chip in the key-gate: 'free' (free but rate-limited) · 'payg' (pay
  // as you go, load a card) · 'both' (a free tier AND a card unlocks more). the funnel: free to enter, payg to
  // grow — every key is money the user pays the provider DIRECT, never us (gowf · fupm). 'tag' stays for the
  // special call-outs ('recommended' · 'yocal').
  const providers = [
    { id: 'anthropic',  name: 'Anthropic',     tag: 'recommended', pay: 'payg', url: 'https://console.anthropic.com/settings/keys', ph: 'sk-ant-…', rpm: 50, tpm: 40000,  limits: 'pay as you go · ~50 req/min (climbs as you add credit)' },
    { id: 'groq',       name: 'Groq',          tag: '',            pay: 'free', url: 'https://console.groq.com/keys',                ph: 'gsk_…',    rpm: 30, tpm: 12000,  limits: 'free · ~30 req/min · 12k tok/min — the tight one (paces ~12s/call)' },
    { id: 'gemini',     name: 'Google Gemini', tag: '',            pay: 'both', url: 'https://aistudio.google.com/apikey',           ph: 'AIza…',    rpm: 15, tpm: 250000, limits: 'free tier (~15 req/min) — or add a card for pay-as-you-go + higher limits · IMAGES (nano) need prepay on' },
    { id: 'mistral',    name: 'Mistral',       tag: '',            pay: 'both', url: 'https://console.mistral.ai/api-keys',          ph: '…',        rpm: 60, tpm: 500000, limits: 'free tier + pay as you go (EU · clean licenses)' },
    { id: 'deepseek',   name: 'DeepSeek',      tag: '',            pay: 'payg', url: 'https://platform.deepseek.com/api_keys',       ph: 'sk-…',     rpm: 60, tpm: 60000,  limits: 'pay as you go · the cheapest tokens going' },
    { id: 'openai',     name: 'OpenAI',        tag: '',            pay: 'payg', url: 'https://platform.openai.com/api-keys',          ph: 'sk-…',     rpm: 60, tpm: 60000,  limits: 'pay as you go · generous' },
    { id: 'xai',        name: 'xAI (Grok)',    tag: '',            pay: 'payg', url: 'https://console.x.ai/',                         ph: 'xai-…',    rpm: 60, tpm: 60000,  limits: 'pay as you go · grok-4.3, 1M context' },
    { id: 'openrouter', name: 'OpenRouter',    tag: '',            pay: 'payg', url: 'https://openrouter.ai/keys',                    ph: 'sk-or-…',  rpm: 20, tpm: 40000,  limits: 'pay as you go · one key, every model' },
    // 🤗 HUGGING FACE — ONE KEY, MANY LABS (Sum 2026-08-30: "everything already built is one stop
    //    shopping on HF"). The router fronts 136 models across together · fireworks · deepinfra ·
    //    novita · baseten and the labs themselves. OpenAI-shaped, so engine.js needed one URL.
    //    Free HF account with a real free allowance — the cheapest key on this list, still a key.
    { id: 'hf',         name: 'Hugging Face',  tag: 'free',        pay: 'both', url: 'https://huggingface.co/settings/tokens',        ph: 'hf_…',     rpm: 60, tpm: 0,      limits: 'one key, many labs · free allowance, then pay as you go' },
    // ── IMAGE providers (Sum 2026-07-27 — diversify the port): a key box + a get-a-key link each; the image
    //    pipeline reads these (also mirror into ~/Local/0z-desk/keys.json for the backend paint scripts). ──
    { id: 'replicate',  name: 'Replicate',    tag: 'image',       pay: 'payg', url: 'https://replicate.com/account/api-tokens',     ph: 'r8_…',     rpm: 60, tpm: 0,      limits: 'pay as you go · every model + the UPSCALERS (clarity · SUPIR · Real-ESRGAN) + Flux/SDXL — your sunk credits' },
    { id: 'tensor',     name: 'Tensor.art',   tag: 'image',       pay: 'payg', url: 'https://tensor.art/',                           ph: 'tensor api key', rpm: 60, tpm: 0, limits: 'credit-based — spends your Credits (~300/day refill) · make a key in Account → API · Nano Banana Pro 4K' },
    // yocal — the loyal local. no key, no spend, no network: an MLX-lm server on THIS Mac. noKey:true so it
    // shows in the picker without a saved key; the onboarding bot installs MLX + starts the server.
    { id: 'local',      name: 'yocal (this Mac)', tag: 'yocal',    pay: '',     noKey: true, url: '', ph: '', rpm: 0, tpm: 0, limits: 'local · no key · no API spend · runs on your machine (start mlx_lm.server)' },
    // ollama — the OTHER local runtime (GGUF, :11434). also keyless. this is where dolphin · heretic · nemo live.
    { id: 'ollama',     name: 'ollama (this Mac)', tag: 'yocal',   pay: '',     noKey: true, url: '', ph: '', rpm: 0, tpm: 0, limits: 'local GGUFs · no key · run `ollama serve` (dolphin · heretic · nemo)' },
  ]
  // a curated model per provider (a live model-list fetch is a later wire).
  const modelsByProvider = {
    anthropic:  ['claude-fable-5', 'claude-opus-4-8', 'claude-sonnet-5', 'claude-sonnet-4-6', 'claude-haiku-4-5'],   // fable-5 = the Mythos-class flagship (2026-07-18)
    groq:       ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'],
    gemini:     ['gemini-2.5-pro', 'gemini-2.5-flash'],
    mistral:    ['mistral-large-latest', 'mistral-small-latest'],
    deepseek:   ['deepseek-chat', 'deepseek-reasoner'],
    openai:     ['gpt-4o', 'gpt-4o-mini', 'o3-mini'],
    xai:        ['grok-4.3'],
    openrouter: ['stealth/ox-alpha', 'anthropic/claude-opus-4-8', 'meta-llama/llama-3.3-70b'],
    // 🤗 chosen by HOW MANY BACKENDS SERVE THEM, read live off /v1/models rather than from memory —
    //    a model with eleven providers behind it is the one least likely to be down when someone
    //    tries the app for the first time.
    //    ⚠ THESE STRINGS ARE THE ROUTING TABLE. engine.js provOf() checks this list BEFORE any
    //    prefix rule, because every id here contains '/' (which would otherwise fall to openrouter)
    //    and 'Qwen/…' additionally matches the yocal regex. Editing a name here moves a model
    //    between providers — that is the mechanism, same as ollama's list.
    hf:         ['openai/gpt-oss-120b',                 // 11 backends — the safest bet on the router
                 'zai-org/GLM-5.2',                     // 8
                 'openai/gpt-oss-20b',                  // 7 — the small one, cheap and quick
                 'deepseek-ai/DeepSeek-V4-Flash-0731',  // 5
                 'moonshotai/Kimi-K3',                  // 5
                 'meta-llama/Llama-3.3-70B-Instruct',   // 5
                 'Qwen/Qwen3.5-397B-A17B',              // 5 — MoE, the big one
                 'google/gemma-4-31B-it'],              // 5
    local:      ['mlx-community/gemma-4-26b-a4b-it-4bit',            // FULL repo id — mlx_lm.server 404s on a bare short name.
                 'mlx-community/Qwen2.5-Coder-7B-Instruct-4bit',     // the Qwen2.5-Coder ladder — all PULLED on disk (2026-07-05),
                 'mlx-community/Qwen2.5-Coder-3B-Instruct-4bit',     // just weren't listed here. biggest→smallest so the picker reads
                 'mlx-community/Qwen2.5-Coder-1.5B-Instruct-4bit',   // as a size ladder. the 0.5B is the tiny-model thesis test.
                 'mlx-community/Qwen2.5-Coder-0.5B-Instruct-4bit'],
    ollama:     ['qwen3-coder:30b',        // MoE, ~3B ACTIVE of 30B → 30B-class reasoning at 3B-class decode speed, 256K ctx.
                 //                        the one that fixes coder's "can't read 887 lines" wall (2026-07-29). ~19GB Q4.
                 'devstral:24b',          // dense, agentic-tuned (46.8% SWE-Bench Verified) — cleanest multi-file diffs. ~14GB.
                 'dolphin3:latest',                                        // ollama GGUFs (need `ollama serve` on :11434) —
                 'dolphin-mixtral:8x7b',                                   // sent to the endpoint VERBATIM, tag and all.
                 'hf.co/dphn/dolphin-2.9.3-mistral-nemo-12b-gguf:Q4_K_M',  // dolphin + nemo in one · heretic below.
                 'hf.co/mradermacher/gemma-4-12B-it-heretic-GGUF:Q4_K_M'],
  }
  // ── SHELF PLAN (not built — note only) ──────────────────────────────────────────────────────────
  // THIS is where more SMART WRITER VOICES land: add the extra local repo ids to modelsByProvider.local
  // (each pulled via mlx_lm; the writer's model picker reads them through availableModels('writer') →
  // SETTINGS.modelField('writer') in agents/writer/writer-voices.js). a distinct writer "voice" model
  // shows in the writer panel's 🧠 model row the moment its repo id is listed here.
  // The 3-CODER CONFER SETUP is the bigger wire (deferred): a confer runner that picks THREE coder
  // models here and has them cross-check (see oz_confer / oz-mcp bridge). its model choices come from
  // this same list — grow modelsByProvider.local first, then build the confer orchestration separately.
  // ────────────────────────────────────────────────────────────────────────────────────────────────
  // no machine, no local model (Sum 2026-08-09, the 0zhub web demo: "strip yocal... no local option
  // from website"). same knife as the cli card: a browser can't run mlx_lm or ollama, so in a plain
  // browser the yocal-tagged providers vanish from the master list — the gear, the model pickers,
  // and the engine order all starve from this one cut. native builds (1 button, 1 permission) keep it.
  if (!window.__TAURI__) {
    for (let i = providers.length - 1; i >= 0; i--) if (providers[i].tag === 'yocal') providers.splice(i, 1)
    delete modelsByProvider.local
    delete modelsByProvider.ollama
  }

  const hasKey = id => !!localStorage.getItem('toto_' + id + '_key')
  // a bot may DECLARE the providers it's allowed to use (AGENT_DATA[id].providers, e.g. jem: ['gemini']).
  // when it does, the pickers are FENCED to those — Jem is Google-only everywhere (standalone AND deluxe),
  // and 'local' (yocal, noKey) can't slip in. no declaration → null → no fence (every other bot, unchanged).
  function agentProviders(id) {
    try { const p = window.AGENT_DATA && window.AGENT_DATA[id] && window.AGENT_DATA[id].providers
      return (Array.isArray(p) && p.length) ? p : null } catch (_) { return null }
  }
  // ⭐⭐ CAPABILITIES LIVE ON THE BOT (Sum 2026-08-26: "bots should all be pretty much identical with
  //    different tools and permissions and persona and rules"). agentProviders above is the precedent —
  //    a bot DECLARES its providers and the pickers read the declaration. Everything else about a bot
  //    should work the same way, and until today six capabilities did not: they were hard-listed in
  //    shared code, one array per capability, in six different files.
  //        conductor.js   DELEGATORS = ['toto','pa','coder','newsie']
  //        search.js      NO_WEB     = ['newsie']
  //        clioz-loop.js  shellBots  = ['coder']
  //        oz-app-cli.js  ozfile     = ['coder']  ·  ozforge = ['lumberjack']
  //        oz-lane.js     MOUNTS     = { tutor: ['coder'] }
  //    Every one of those is a fact ABOUT A BOT stored somewhere the bot cannot see, which is how a bot
  //    that leaves quietly keeps its capability (yanker was in DELEGATORS for days after it had no data —
  //    a route to nowhere) and how a new bot silently gets none of them.
  //    caps() reads window.AGENT_DATA LAZILY, at call time, exactly as agentProviders does — so this file
  //    can keep loading before agents.gen.js and nothing has to move.
  //    A capability is a STRING IN THE BOT'S OWN RECORD now: "caps": ["delegate", "shell"].
  function caps(id) {
    try { const c = window.AGENT_DATA && window.AGENT_DATA[id] && window.AGENT_DATA[id].caps
      return Array.isArray(c) ? c : [] } catch (_) { return [] }
  }
  function hasCap(id, cap) { return caps(id).indexOf(cap) > -1 }
  // the bots holding a capability — for the handful of callers that want the LIST rather than a test
  function withCap(cap) {
    try { return Object.keys(window.AGENT_DATA || {}).filter(id => hasCap(id, cap)) } catch (_) { return [] }
  }
  // ── ⭐ THE HOUSE CHAIR (26 Aug) — which bot greets you while a given SKIN is on.
  //    Sum's rule for the strips, verbatim: "each theme gets a toto like bot, same authority delegator."
  //    It was a hardcoded map in topbar.js (HOUSE_BOTS = { oz:'toto', clinical:'nurse', … }), which is the
  //    same leak caps() was built to end: a fact about a bot, filed where the bot cannot see it — so a new
  //    theme's bot could not exist without editing the chrome every theme shares.
  //    Now the BOT names its own theme: "house": "unicorn" in its record, beside its caps.
  //    Falls back to the FIRST bot holding cap "house", then to nothing. NO NAME IS HARDCODED HERE: if the
  //    roster is empty the honest answer is empty, not a guess (same law as oz-app-cli's ozfile lane).
  function houseFor(skin) {
    try {
      const D = window.AGENT_DATA || {}
      if (skin) { for (const id of Object.keys(D)) if (D[id] && D[id].house === skin) return id }
      const any = withCap('house'); return any.length ? any[0] : ''
    } catch (_) { return '' }
  }

  // the models you can ACTUALLY run — grouped by the providers you've saved a key for. this is
  // what fixes "i never entered an Anthropic key but could pick opus": no key, no opus, anywhere.
  // pass an agentId to also fence to that bot's declared providers (google-only bots see only gemini).
  function availableModels(agentId) {
    const allow = agentId ? agentProviders(agentId) : null
    return providers
      .filter(p => p.noKey || hasKey(p.id))
      .filter(p => !allow || allow.includes(p.id))
      .map(p => ({ id: p.id, name: p.name, models: modelsByProvider[p.id] || [] }))
  }

  // ── skins — the 4 GLOBAL app-skins lead (oz · unicorn · clinical · corporate); the rest are
  //    the convo-skin "hats" a per-agent picker can apply. (oz = renamed from black, the house skin.) ──
  // 'phone' parked from this list 2026-08-29: its css/frame png sit in _bench-for-totois (beta cut),
  // so picking it did nothing — index.html parks the matching <link> the same day. Re-seat together.
  const skins = ['oz', 'unicorn', 'clinical', 'corporate', 'analog', 'beach', 'desert', 'historian', 'monaco', 'neo', 'orange']

  // ── the agent roster — built-ins + customs forged in the woodshop (toto_custom_agents). ──
  // each carries its picker ICON (img · cssRef → a window svg · emoji); the bar's full config
  // (skin, convo, edge) lives in workspace.js AGENT_BARS.
  const agents = [
    { id: 'toto',       label: 'toto',       img: 'agents/toto/collar.png' },
    { id: 'coder',      label: 'coder',      img: 'agents/coder/coder.png' },
    // (26 Aug) benched, then RESTORED the same hour — Sum: "restore the one that uses right glyphs."
    //   It is the only Anthropic bot with a GLYPH NAME; asterix is the other Anthropic seat and its name
    //   is plain 'asterix' (what it wears is the bleep() display filter). This one holds GOAT's 4th chair.
    { id: 'bleep',      label: '¢|@∪0Ɛ',     img: 'agents/bleep/bleep.jpg' },   // the senior dev — its own name never prints (bleep() → ⊗@#$%&); the glyphs ARE the wink       // rendered icon (was 🤖) — 2026-07-09
    // PARKED 2026-08-29 (Sum: "scratchpads of ideas, not finished code") — writer + pa benched in
    // _bench-for-totois/ beside sphinx and yanker; a better pair returns after the beta ships. Were:
    // { id: 'writer',     label: 'writer',     img: 'agents/pa/personal-assistant.png' },      // 🖋 quill in an inkwell (was 🪶) — 2026-07-09
    { id: 'nurse',      label: 'nurse',      img: 'agents/nurse/nurse.png' },       // rendered icon (was NURSE_CAP css) — 2026-07-09
    { id: 'wellness',   label: 'Vita',       img: 'agents/wellness/wellness-icon.png' },
    { id: 'tutor',      label: 'tutor',      img: 'agents/tutor/gradcap.png' },
    { id: 'learner',    label: 'learner',    img: 'cards/learn/learn.png' },      // (Sum 2026-08-17) NOT a character — the learn card's section builder. Its persona slot holds the SECTION JOBS (snippet · phd · fifth · explore · practice · test), not a personality. Called via engineRaw slim, never through the conductor.      // 🎓 grad cap (from monaco's 'teach me') — was the learn book, but book==learn in the drawer was confusing. just-graduated tutor. (Sum 2026-07-10)
    // PARKED 2026-08-29 with writer (see the note above):
    // { id: 'pa',         label: 'PA',         img: 'agents/pa/phone.png' },   // reverted from the blackberry pa.png back to the ORIGINAL phone.png — 2026-07-09
    { id: 'timetravel', label: 'traveler',   img: 'agents/timetravel/skate.png' },   // ⏳ the time-traveling AI that lives in a pair of rollerblades (Sum's own gen) — 2026-07-18
    { id: 'newsie',     label: 'the newsie', img: 'agents/newsie/newsie-roll-sm.png' },   // 🛳 the orphaned smart-paper — runs The Port Side View, reads the web clean (Sum 2026-07-22)
    { id: 'dria',       label: 'Dria',       img: 'agents/dria/alexa-card.png' },   // 🏮 DRIA, ALEXA N. — librarian of all human public domain, president of Port Side U. Rides the red lamp (library) card; the paper prints the excerpt and sends the reader to her for the whole text. (Sum 2026-07-24, seated 2026-08-25)
    { id: 'gamer',      label: 'the gamer',  img: 'agents/gamer/gamer.png' },   // 🕹 a washed-up coin-op cabinet, revived — an honest machine that reads the board (Sum 2026-07-22)
    // ── the fruit basket: providers-as-characters. each one only wakes on ITS provider's key. ──
    // (Sum 2026-07-29) jem back ON, muskett + aoladdin wired for the first time. Their data has
    // been in agents.gen.js all along — THIS list is the on/off switch, because REG.agents is what
    // the green room and the drawer read. Data without a roster line is a bot nobody can reach.
    // (26 Aug) jem left 0zweb entirely — folder, bar and roster line. _bench-for-totois/ holds it for
    //   the slint/rust builds. Her Mondrian SKIN stayed: alpha wears it (skin/jem.css, workspace.js).
    { id: 'alpha',      label: 'Alpha',      img: 'agents/alpha/alpha.png' },   // 🔤 Gemini — the tech bro to the extreme. not the top dog in any room, in every room. wants every debate. the ABC tile on a lanyard.
    { id: 'aoladdin',   label: 'AOLaddin',   img: 'agents/aoladdin/aoladdin.png' },   // 🫧 OpenAI — the genie somebody OPENED. a goldfish, sure it can walk on two legs it hasn't got
    { id: 'muskett',    label: 'Muskett',    img: 'agents/muskett/muskett.png' },     // 🎩 xAI — E. Long Muskett, chrome gentleman. courtly on top, apocalypse-prepper underneath
    // ── the agnostic seat (Sum 2026-08-14) — vogel takes ANY provider: a small API, a local model,
    //    whatever is left over. moderates AIOL beside the human sysop. the icon is the emoji PIN pad
    //    because vogel IS the input: a clerk who processes property all day and has never filed
    //    themselves. pronouns are literally [ ] — the one box left blank in nineteen years.
    { id: 'vogel',      label: 'Vogel',      img: 'agents/vogel/vogel.png' },
    // ⭐⭐ 31 Aug 2026 — THE FIFTH REGISTRATION, and it is the one that bites SILENTLY.
    //   A bot needs FIVE lines, not four: allowed (profile) · seated (AGENT_BARS) · placed (a suite or
    //   the bar) · dressed (skin css) · and NAMED HERE. itemMeta() resolves a drawer tile by walking
    //   CARDS → NAV → REG.agents, and its last line is `return { id, label: id, emoji: '▢' }`.
    //   ▢ draws as an EMPTY BOX.
    //   ⚠ SO THE SYMPTOM IS NOT "no icon" — IT IS A BLANK TILE WHOSE TOOLTIP SHOWS THE RAW ID
    //   instead of the display name. That tooltip is the tell: 'trawman', not 'S. Trawman'.
    //   Both lines below were added AFTER their bots shipped without one. uni never showed the
    //   fault only because it has no suite drawer to appear in — the bug was there, just unlit.
    { id: 'trawman',    label: 'S. Trawman', img: 'agents/trawman/trawman.png' },   // 📜 keeps the minutes in THE ROOM; the legal-fiction person, and he discloses it
    { id: 'uni',        label: 'UNI corn',   img: 'agents/uni/uni.png' },           // 🌽 Unnatural Intelligence — the unicorn skin's house bot
    // ── SYSISPHINX (Sum 2026-08-16) — System Intelligence Sphinx; the boulder is in the name. the file desk's being:
    //    guards Binary Complex (riddle locks, hidden means hidden, REFUSES to delete — the Trash, never past it).
    //    the greenroom cast is P.agents minus suite bots (topbar.js), so the suite line below is what keeps them out.
  ]
  // (Sum 2026-07-09) lumberjack retired → folded into coder.
  // ── CORRECTION, attached 26 Aug 2026 — bub came BACK and this line was the reason nobody could
  //    find it. It has a folder, art, an injection, eleven tools, a bar in workspace.js, the `axe`
  //    card (registered, live in the boot report) and the `forge` cap that oz-app-cli's ozforge lane
  //    resolves through — but no roster line, so it drew as a "coming soon" placeholder for seven
  //    weeks. agents/agents.json is the ship list and it names lumberjack; when the ship list and a
  //    hand-kept array disagree, the ship list wins. Seated below, and seated in profile.js too —
  //    build.js's 4th and 5th organs both flagged this every build and both were right.
  //    The July sentence stays: for those seven weeks it WAS folded into the coder, and that is why
  //    the coder still carries file tools that read like a forge.
  // ── AND THE CORRECTION IS ITSELF CORRECTED, four hours later, by the only authority that counts.
  //    Sum, 26 Aug: "un ship and park bub next to yanker and shpinx." So the July sentence above was
  //    right all along and my reasoning was wrong in a specific, worth-writing-down way: I read the
  //    ship list as newer than this array and let that settle a question the ship list was never
  //    deciding. A roster is a fact; whether a bot should EXIST is a decision. The organs were right
  //    that the two disagreed and had no business picking the winner — and neither did I.
  //    The `agents.push({ id: 'lumberjack', … })` line that stood here for those four hours is gone.
  //    Everything of bub is in _bench-for-totois/lumberjack/ + lumberjack-AGENT_BARS.js, unedited.
  const readCustom = () => { try { return JSON.parse(localStorage.getItem('toto_custom_agents') || '[]') } catch (_) { return [] } }
  const writeCustom = list => { try { localStorage.setItem('toto_custom_agents', JSON.stringify(list)) } catch (_) {} }
  readCustom().forEach(a => { if (a.id && !agents.find(b => b.id === a.id)) agents.push({ id: a.id, label: a.label, emoji: '🧩' }) })

  // ── pub/sub — pickers subscribe; an add/remove emits so every OPEN list re-renders live. ──
  const subs = new Set()
  function emit() { subs.forEach(fn => { try { fn() } catch (_) {} }) }
  function onChange(fn) { subs.add(fn); return () => subs.delete(fn) }

  // ── the add buttons push here (and persist) → emit → pickers refresh. ──
  // ⭐ `extra` (2026-08-25) — the RECORD, not just the nameplate. A forged bot used to persist as
  //    { id, label } and nothing else, so on the next boot it came back as a roster line with no nav,
  //    no tools and no role: seated, and unknown to every tool that asks the bean. The seat and the
  //    record are ONE write, and this is the function that owns that write — the caller passes the
  //    whole bot, agents.gen.js absorbs it back into AGENT_DATA at boot. Reserved keys (id/label) are
  //    written from the arguments, never from `extra`.
  function addAgent(id, label, extra) {
    if (!id || agents.find(a => a.id === id)) return
    agents.push({ id, label: label || id, emoji: '🧩' })
    const rec = Object.assign({}, extra || {}, { id, label: label || id })
    const custom = readCustom(); if (!custom.find(a => a.id === id)) { custom.push(rec); writeCustom(custom) }
    emit()
  }
  function removeAgent(id) {
    const i = agents.findIndex(a => a.id === id); if (i >= 0) agents.splice(i, 1)
    writeCustom(readCustom().filter(a => a.id !== id))
    emit()
  }
  function addSkin(name) { if (name && !skins.includes(name)) { skins.push(name); emit() } }
  function addModel(provider, model) {
    const l = modelsByProvider[provider] || (modelsByProvider[provider] = [])
    if (model && !l.includes(model)) { l.push(model); emit() }
  }

  return { providers, modelsByProvider, skins, agents, hasKey, availableModels, agentProviders, caps, hasCap, withCap, houseFor, addAgent, removeAgent, addSkin, addModel, onChange, emit }
})()

// back-compat alias — the injection config + woodshop already read window.AGENTS_ROSTER.
window.AGENTS_ROSTER = window.REG.agents
