// a11y.js — the ♿ ACCESSIBILITY BEAN. one mechanism, the whole app, forever.
//   doctrine (ACCESSIBILITY.md): 0z does NOT rebuild assistive input — it gives the OS a CLEAN DOM
//   and lets Switch Control / VoiceOver / Voice Control drive it. this bean is that cleaning crew:
//   · NAMES    — every icon-only button/link gets an aria-label, derived (title → img alt → img
//                filename → data-* hint). ~500 buttons, one sweep, future buttons free.
//   · IMGS     — an img inside a named control is decoration (alt="") · a bare img gets a filename alt.
//   · LIVE     — chat logs / streams / status tickers get aria-live so VoiceOver announces replies.
//   · LANDMARK — the topbar declares itself <nav>-equivalent (index.html already has <main>).
//   · ESC POPS OUT — Esc from any input/editor blurs back to the card (the "no keyboard trap" rule);
//                fires only when nothing else claimed the key (bubble phase, defaultPrevented check).
//   a MutationObserver re-sweeps (debounced) as cards build, so late DOM is covered automatically.
//   self-contained, no deps. loaded from index.html after topbar.js.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the LEXICON (Sum 2026-07-14): a blind user .... search: "the LEXICON (Sum"
//   the naming well — where a label can be ........ search: "the naming well — where"
//   the GLYPH well — last, because anything ....... search: "the GLYPH well — last,"
//   pass 1a: FIELDS — the naming pass never ....... search: "pass 1a: FIELDS — the"
//   pass 1: NAMES — buttons + links + ............. search: "pass 1: NAMES — buttons"
//   pass 1b: CLICK-ONLY DIVS (Sum 2026-07-23, ..... search: "pass 1b: CLICK-ONLY"
//   pass 2: LIVE REGIONS — the streams a blind .... search: "pass 2: LIVE REGIONS"
//   pass 3: LANDMARK — the topbar is the nav ...... search: "pass 3: LANDMARK — the"
//   pass 4: ARIA STATES + HEADINGS (Sum ........... search: "pass 4: ARIA STATES +"
//   the sweep + the watcher — run now, re-run ..... search: "the sweep + the watcher"
//   the announcer — ONE polite live region for .... search: "the announcer — ONE"
//   the EARCONS — a felt click for ................ search: "the EARCONS — a felt"
//   ⌨ THE DESK GRAB — LATCH MODE (Sum ............. search: "⌨ THE DESK GRAB — LATCH"
//   ? = THE KEY MAP (Sum: "key map overlay for .... search: "? = THE KEY MAP (Sum:"
//   R = READ THIS TO ME (Sum: "it's free, do ...... search: "R = READ THIS TO ME"
//   ESC POPS OUT — the no-trap rule. popOut ....... search: "ESC POPS OUT — the"
//   ⌨ FOCUS MODE (Sum 2026-07-14) — the topbar .... search: "⌨ FOCUS MODE (Sum"
//   the shared tabbable walk + the live pointer ... search: "the shared tabbable"
//   ARROWS TRAVEL (Sum: "hook it to arrows too .... search: "ARROWS TRAVEL (Sum:"
//   F6 = THE QUASIMODE (Sum's fix for "can't ...... search: "F6 = THE QUASIMODE"
//   FOCUS MEMORY (Sum 2026-07-14) — a card ........ search: "FOCUS MEMORY (Sum"
//   the SCROLL PIN — the shell NEVER scrolls ...... search: "the SCROLL PIN — the"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for accessibility sweeps across the DOM:
//    **naming unlabeled controls, marking live regions, setting ARIA states, and keyboard travel.
//    **It exports `window.OZ_A11Y` with `{ sweep, popOut, say, tick, restoreFocus, pinDesk }` (line
//    **465), and `window.OZ_KBD` with keyboard mode state (line 354).
//
//    **TOUCH HERE** —
//    - Add a new curated name for a button/icon → `LEX` object L18
//    - Change what text a screen reader hears for a specific data-* hint → `LEX` L18
//    - Add a new selector to the naming well (title, img alt, etc.) → `hintAttrs` L35
//    - Mark a new chat log or status ticker as live → `LIVE` array L175
//    - Add a new glyph (✕, ＋, ‹, etc.) that has no text → `GLYPH` object L69
//    - Exclude a new high-churn DOM region from the clickable-div pass → `CLICKDIV_SKIP` L148
//    - Change the keyboard shortcut for grab mode → search `e.key === 'g'` L253
//    - Change the keyboard shortcut for read-aloud → search `e.key !== 'r'` L302
//    - Change the keyboard shortcut for keymap → search `e.key === '?'` L296
//    - Change the keyboard shortcut for focus mode toggle → search `e.key !== 'F6'` L376
//    - Add a new card type to focus memory or landmark detection → `restoreFocus()` L442 or
//    - `landmarks()` L188
//
//    **TRAPS** —
//    - `LEX` keys must be lowercase (line 41 lowercases the lookup); a key added in uppercase will
//    - never match.
//    - `FIELDS` selector (L93) is a string used in two places (L121, line 356 in tabbables);
//    - changing it requires both edits.
//    - `clean()` function (L36) deliberately strips emoji to prevent VoiceOver hearing "wrench
//    - emoji"; passing a glyph through it deletes it (line 65 warns this). Do not call `clean()` on
//    - glyph lookups.
//    - `GLYPH` table (L69) is a last-resort fallback; a curated name in `LEX` will always win first
//    - (line 42 checks `LEX` before `GLYPH`).
//    - `_dgrab`, `_kbd`, `_say`, `_ac`, `_px`, `_py`, `_lastFocus` are module-scoped state (lines
//    - 219, 226, 233, 247, 345, 358, 437); renaming one breaks the keydown listeners that reference
//    - it.
//    - `MutationObserver` (L223) watches `childList`, `subtree`, and `attributes` with
//    - `attributeFilter: ['class']`; it re-runs `sweep()` on class flips but not aria-* writes
//    - (line 223 comment: "sweep writes only aria-* → no loop"). Adding aria-* writes to sweep
//    - without understanding this can cause infinite loops.
//    - `isEditable()` (L325) is called from five separate keydown listeners (lines 253, 296, 302,
//    - 339, 366, 392, 399, 427); it must stay in scope and its logic must not change without
//    - auditing all five.
//    - `popOut()` (L327) adds `tabindex="-1"` to surfaces that lack it (L331); this is load-bearing
//    - for the Esc-climb logic (L428 assumes `-1` means "popped").
//    - Focus mode state `_kbd` is persisted to `localStorage` (L349); changing the key
//    - `'oz_kbd_mode'` orphans existing user settings.
//    - `say()` creates a single hidden live region on first call (L228); calling it multiple times
//    - reuses the same element, so rapid messages overwrite each other (by design — only one
//    - announcement at a time).
//
//    **DO NOT** —
//    - Do not rename `window.OZ_A11Y`, `window.OZ_KBD`, or `window.OZ_DOCK` (L258, 354, 465); other
//    - files depend on these exports.
//    - Do not move the `MutationObserver` setup (L223) or change its config without understanding
//    - the no-loop guarantee.
//    - Do not add new aria-* attributes inside `sweep()` (L220) without checking that the
//    - MutationObserver won't re-trigger infinitely.
//    - Do not change the `GLYPH` table to include ambiguous glyphs (line 62 warns: "A wrong name is
//    - worse than no name").
//    - Do not add keyboard shortcuts without checking for conflicts with browser defaults (line 302
//    - comment: ⌘R is the browser's reload).
//    - Do not move the `restoreFocus()` call or change when it fires; it is called from outside
//    - this file (search the codebase for `OZ_A11Y.restoreFocus`).
//    - Do not add new selectors to `FIELDS` (L93) without testing that they don't break the
//    - form-control naming pass (L121–125).
//    - Do not change the `CLICKDIV_SKIP` string without understanding that it protects Monaco and
//    - log DOM from being re-tagged as buttons.
//    - Do not add new live regions without marking them `aria-atomic="false"` (L183); atomic
//    - regions announce the whole thing on every change, which is noisy for streams.
//    - Do not change the scroll-pin logic (L456–463) without testing that focus inside iframes
//    - doesn't scroll the shell off-screen.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'

  // ── the LEXICON (Sum 2026-07-14): a blind user hears a GUIDE, not a filename. curated names for
  //    the chrome that matters; keyed by data-* hints and img stems. extend as cards get touched. ──
  const LEX = {
    // monaco — the pit
    minimap: 'minimap — the circuit view of the file', diff: 'diff — compare the original against your edits',
    find: 'find and replace', fix: 'Fix — the repair coder', teach: 'Teach — the tutor',
    squiggy: 'Squiggy — the code suggestor', funcs: 'function keys drawer', syms: 'symbol keys drawer',
    nums: 'number keys drawer', devtools: 'dev tools — console, C L I, preview, and problems',
    sandbox: 'open the sandbox folder', save: 'save a version for rollback', saveout: 'save the file to your device',
    preview: 'preview this file', wrench: 'Fix — the repair coder', gradcap: 'Teach — the tutor',
    gp: 'Monaco GP — the code editor', dragrace: 'diff — compare the original against your edits',
    'flag-yellow': 'save a version for rollback', 'launch preview': 'preview this file',
    // shared card chrome
    gear: 'settings', tiptap: 'Tip Tap — the writing page', learn: 'Learn — the study card',
    wellness: 'Wellness', clipboard: 'Clipboard', calendar: 'Calendar', email: 'Email', clock: 'Clock',
    injection: 'Injection — the prompt harness', woodshop: 'Woodshop', dashboards: 'Dashboards',
    fupm: 'F U P M — ways to pay Sum', monaco: 'Monaco GP — the code editor',
  }
  // ── the naming well — where a label can be drawn from, best first: lexicon → title → img → hint ──
  const hintAttrs = ['data-pit', 'data-tool', 'data-act', 'data-card', 'data-fs', 'data-collapse']
  const clean = s => String(s || '')
    .replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu, '')   // strip emoji — VoiceOver shouldn't hear "wrench emoji" first
    .replace(/\s+/g, ' ').trim()
  function labelFor(el) {
    for (const a of hintAttrs) {                                  // a curated name wins
      const v = (el.getAttribute(a) || '').trim().toLowerCase()
      if (v && LEX[v]) return a === 'data-fs' ? 'fullscreen — ' + LEX[v] : a === 'data-collapse' ? 'collapse or expand — ' + LEX[v] : LEX[v]
    }
    const img = el.querySelector('img')
    if (img) {                                                    // img stem may hit the lexicon too
      const stem = (img.getAttribute('src') || '').split('/').pop().replace(/\.(png|jpe?g|svg|webp|gif)$/i, '').replace(/[-_]+/g, ' ').trim().toLowerCase()
      if (LEX[stem]) return LEX[stem]
    }
    let t = clean(el.getAttribute('title')); if (t.length > 70) t = t.split(/ — | · /)[0]   // long tooltips → the first clause
    if (t) return t
    if (img) {
      const a = clean(img.getAttribute('alt')); if (a) return a
      const stem = (img.getAttribute('src') || '').split('/').pop().replace(/\.\w+$/, '').replace(/[-_]+/g, ' ').trim()
      if (stem) return stem
    }
    for (const a of hintAttrs) { const v = (el.getAttribute(a) || '').trim(); if (v) return v.replace(/[-_]+/g, ' ') }
    // ── the GLYPH well — last, because anything above is a curated name and outranks a convention.
    //    30 of the app's own buttons carried no name at all and showed a single glyph instead: ✕
    //    seven times, ＋ three, ‹ › four. hasText() correctly refuses to call one glyph a name — it
    //    is a PICTURE of a name — so every one of them fell through to nothing. One table fixes the
    //    whole class, where 30 markup edits would have fixed 30 buttons and not the next one.
    //    ONLY UNAMBIGUOUS GLYPHS BELONG HERE. A wrong name is worse than no name: silence makes a
    //    user look, a lie makes them act. ▶ is deliberately absent — play or next, never certain.
    //    NOT clean() — clean() exists to STRIP emoji, and ✕ (U+2715) and 🗑 sit inside the exact
    //    ranges it removes. Passing the glyph through it deleted the thing we came to look up, and
    //    the most common one in the app, ✕, silently returned nothing. Whitespace only, here.
    const g = String(el.textContent || '').replace(/️/g, '').replace(/\s+/g, ' ').trim()
    if (g.length <= 2) {
      const GLYPH = {
        '✕': 'close', '✖': 'close', '×': 'close', '⨯': 'close', '╳': 'close', '⊗': 'close',
        '＋': 'add', '+': 'add', '−': 'remove', '–': 'remove', '🗑': 'delete',
        '‹': 'previous', '←': 'previous', '›': 'next', '→': 'next',
        '…': 'more', '⋯': 'more', '⏸': 'pause', '↺': 'reset', '⟲': 'reset',
        '⇄': 'swap', '⇆': 'swap', '▲': 'up', '▼': 'down', '⌃': 'up', '⌄': 'down', '?': 'help',
      }
      if (GLYPH[g]) return GLYPH[g]
    }
    return ''
  }
  const hasText = el => (el.textContent || '').replace(/\s+/g, '').length > 1   // 1 glyph (an emoji/arrow) isn't a name

  // ── pass 1a: FIELDS — the naming pass never covered inputs, and 383 of 470 were mute ────────
  //    (Sum 2026-07-30, from the elevation audit: 183 form controls with no name at all, plus 199
  //    named ONLY by placeholder — and a placeholder is not a name. It disappears the moment you
  //    type, so the field announces itself right up until the point you are using it.)
  //
  //    The usual shape in this codebase is a visual label that is NOT programmatically attached:
  //        <div class="wg-name">Detect GPS</div>
  //        <input type="checkbox" id="loc-pref-detect">
  //    A sighted user reads those as one thing. A screen reader says "checkbox, unchecked" and
  //    Voice Control has nothing to aim at — so the control does not exist for Sum. Borrowing the
  //    neighbouring text is not a guess; it is the label, just not wired up.
  const FIELDS = 'input:not([type="hidden"]):not([type="button"]):not([type="submit"]), select, textarea'
  function fieldName(el) {
    const id = el.getAttribute('id')
    // a REAL association already works and outranks us — adding aria-label here would override it
    if (id && document.querySelector('label[for="' + CSS.escape(id) + '"]')) return ''
    if (el.closest('label')) return ''
    const hinted = labelFor(el); if (hinted) return hinted
    let sib = el.previousElementSibling                           // the visual label, one step back
    for (let i = 0; i < 2 && sib; i++, sib = sib.previousElementSibling) {
      if (sib.matches('input, select, textarea, button, a')) break
      const t = clean(sib.textContent)
      if (t && t.length <= 40) return t
    }
    const par = el.parentElement                                  // …or the cell's own heading
    const head = par && par.querySelector('.wg-name, .set-name, legend, h1, h2, h3, h4')
    if (head) { const t = clean(head.textContent); if (t && t.length <= 40) return t }
    const ph = clean(el.getAttribute('placeholder'))
    return ph || ''                                               // last resort — better than silence
  }

  // ── pass 1: NAMES — buttons + links + role=button that read as silence to AT ──
  function nameControls(root) {
    root.querySelectorAll('button, a[href], [role="button"]').forEach(el => {
      if (el.hasAttribute('aria-label') || el.hasAttribute('aria-labelledby')) return
      if (hasText(el)) return                                     // visible text IS the name
      const name = labelFor(el)
      if (name) el.setAttribute('aria-label', name)
    })
    root.querySelectorAll(FIELDS).forEach(el => {
      if (el.hasAttribute('aria-label') || el.hasAttribute('aria-labelledby')) return
      const name = fieldName(el)
      if (name) el.setAttribute('aria-label', name)
    })
    // an img inside a labelled control is decoration; a bare img gets its filename as alt
    root.querySelectorAll('img:not([alt])').forEach(img => {
      const btn = img.closest('button, a[href], [role="button"]')
      if (btn) { img.setAttribute('alt', '') ; return }
      const stem = (img.getAttribute('src') || '').split('/').pop().replace(/\.\w+$/, '').replace(/[-_]+/g, ' ')
      img.setAttribute('alt', stem || '')
    })
  }

  // ── pass 1b: CLICK-ONLY DIVS (Sum 2026-07-23, the gap the buttons pass doesn't cover) — a div/span/li
  //    styled `cursor: pointer` but wired only with addEventListener('click', ...) is invisible to the
  //    keyboard/switch: no tab stop, no name, no Enter/Space. Every card in the app has these (story
  //    tiles, list rows, chips) and there are too many hand-rolled sites to patch one by one. Instead of
  //    touching every card, this ONE pass finds them by their own visual tell (cursor:pointer) and makes
  //    each a real control: role="button", tabindex, a name (text or the same lexicon nameControls uses),
  //    and Enter/Space → a SYNTHETIC .click() (fires whatever addEventListener('click', ...) is already
  //    wired — same trick a native <button> does internally, so the existing handler needs no changes).
  //    Skips anything already interactive/labelled (never re-tags a hand-built role="link" etc — cb068ff's
  //    PSV story pattern wins over this generic one) and never nests a tab stop inside another. ──
  // heavy, high-churn DOM this pass should never walk into: Monaco repaints on every keystroke
  // (view-lines, decorations, minimap — thousands of plain divs, none of them click targets),
  // same editors/logs glyph.js's SKIP already carves out.
  const CLICKDIV_SKIP = '.monaco-editor, .mc-editors, [contenteditable], pre, code, iframe, ' +
    '.mc-console-body, .mc-cli-out, .mc-tool-log, .mc-fix-log, .mc-sq-chat-log, .convo-screen, .mc-stream-body'
  function clickableDivs(root) {
    root.querySelectorAll('div, span, li').forEach(el => {
      if (el.hasAttribute('data-a11y-auto')) return                // already handled by a prior sweep
      if (el.matches('button, a[href], [role], [tabindex], input, select, textarea, [contenteditable="true"]')) return
      if (el.closest('[role], button, a[href], [contenteditable="true"]')) return   // don't nest inside a control
      if (el.closest(CLICKDIV_SKIP)) return                         // never touch editor/log-heavy DOM (perf + it's content)
      let cur
      try { cur = getComputedStyle(el).cursor } catch (_) { return }
      if (cur !== 'pointer') return
      if (!el.children.length && !hasText(el)) return               // empty/decorative — nothing to land on
      el.setAttribute('data-a11y-auto', '1')
      el.setAttribute('role', 'button')
      el.setAttribute('tabindex', '0')
      if (!el.hasAttribute('aria-label') && !hasText(el)) {
        const name = labelFor(el)
        if (name) el.setAttribute('aria-label', name)
      }
      el.addEventListener('keydown', e => {
        if ((e.key === 'Enter' || e.key === ' ') && !e.defaultPrevented) { e.preventDefault(); el.click() }
      })
    })
  }

  // ── pass 2: LIVE REGIONS — the streams a blind user must HEAR arrive ──
  //   polite: chat logs + status tickers. (errors ride the same logs; assertive everywhere = chaos.)
  const LIVE = [
    '.convo-screen',                                   // the agent bars' chat
    '.mc-tool-log', '.mc-fix-log', '.mc-sq-chat-log',  // monaco: teach · fix · squiggy convos
    '.mc-stream-body', '.mc-console-body', '.mc-cli-out',  // monaco: stream · console · cli
    '.mc-fix-status', '.mc-tw-status', '.mc-stream-status', '.wk-status',  // status tickers
  ]
  function liveRegions(root) {
    LIVE.forEach(sel => root.querySelectorAll(sel).forEach(el => {
      if (!el.hasAttribute('aria-live')) { el.setAttribute('aria-live', 'polite'); el.setAttribute('aria-atomic', 'false') }
    }))
  }

  // ── pass 3: LANDMARK — the topbar is the nav (index.html's <main> is already a landmark) ──
  function landmarks() {
    const tb = document.getElementById('topbar')
    if (tb && !tb.hasAttribute('role')) { tb.setAttribute('role', 'navigation'); tb.setAttribute('aria-label', 'top bar') }
  }

  // ── pass 4: ARIA STATES + HEADINGS (Sum 2026-07-14, "knock off the list") — dropdowns say they open,
  //    tabs say they're picked, card titles are headings VO can jump by, card heads join the Tab walk. ──
  function ariaStates(root) {
    root.querySelectorAll('[data-lvopen]').forEach(el => {   // the ▾ level/context dropdowns
      el.setAttribute('aria-haspopup', 'menu')
      const dd = el.closest('.mc-sq-level, .mc-scope-dd, .mc-fix-leveldrop, .mc-tool-leveldrop')
      el.setAttribute('aria-expanded', dd && dd.classList.contains('open') ? 'true' : 'false')
    })
    root.querySelectorAll('.mc-ctab, .mc-tw-tab').forEach(el => {   // console + teach-window tabs
      el.setAttribute('role', 'tab')
      el.setAttribute('aria-selected', el.classList.contains('on') ? 'true' : 'false')
    })
    root.querySelectorAll('.card-title').forEach(el => { el.setAttribute('role', 'heading'); el.setAttribute('aria-level', '2') })
    root.querySelectorAll('.card-head').forEach(el => {   // a card's head = a real stop on the walk (Enter/Space toggles it)
      if (!el.hasAttribute('tabindex')) el.setAttribute('tabindex', '0')
      if (!el.hasAttribute('role')) el.setAttribute('role', 'button')
    })
  }
  document.addEventListener('keydown', e => {   // Enter/Space on a card head = the click it promises
    if (e.key !== 'Enter' && e.key !== ' ') return
    const h = document.activeElement
    if (!h || e.defaultPrevented || !h.classList || !h.classList.contains('card-head')) return
    e.preventDefault(); h.click()
  })

  // ── the sweep + the watcher — run now, re-run (debounced) as cards build + as .open/.on classes flip ──
  let _t = null
  function sweep() { try { nameControls(document); clickableDivs(document); liveRegions(document); landmarks(); ariaStates(document) } catch (_) {} }
  function schedule() { clearTimeout(_t); _t = setTimeout(sweep, 300) }
  sweep()
  try { new MutationObserver(schedule).observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['class'] }) } catch (_) {}   // class-flips re-sweep (sweep writes only aria-* → no loop)

  // ── the announcer — ONE polite live region for travel narration (grab moves, docking) ──
  let _say = null
  function say(msg) {
    if (!_say) { _say = document.createElement('span'); _say.setAttribute('aria-live', 'polite'); _say.style.cssText = 'position:fixed;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)'; document.body.appendChild(_say) }
    _say.textContent = msg
  }

  // ── the EARCONS — a felt click for grab/dock/release (visual twin = the lift/ring; deaf-safe both ways) ──
  let _ac = null
  function tick(freq) {
    try {
      _ac = _ac || new (window.AudioContext || window.webkitAudioContext)()
      const o = _ac.createOscillator(), g = _ac.createGain()
      o.frequency.value = freq; g.gain.value = 0.06
      o.connect(g); g.connect(_ac.destination)
      o.start(); g.gain.exponentialRampToValueAtTime(0.0001, _ac.currentTime + 0.09); o.stop(_ac.currentTime + 0.1)
    } catch (_) {}
  }

  // ── ⌨ THE DESK GRAB — LATCH MODE (Sum 2026-07-14: "latch mode, on all" — chords are hard; switch users
  //    can't hold). press G on a CARD'S HEAD or a docked bot bar → LATCHED · arrows dock it to a wing ·
  //    THE DESK IS THE MIDDLE (arrow away from its edge → back to the desk) · G again (or Esc) lets go. ──
  let _dgrab = null
  const EDGEK = { ArrowLeft: 'left', ArrowRight: 'right', ArrowUp: 'top', ArrowDown: 'bottom' }
  const OPP = { left: 'right', right: 'left', top: 'bottom', bottom: 'top' }
  const grabName = el => { const t = el.querySelector('.card-title, .ab-name'); return (t && t.textContent.trim()) || el.dataset.card || el.dataset.agent || 'card' }
  const dgrabRelease = quiet => { if (_dgrab) { _dgrab.classList.remove('kbd-grab'); if (!quiet) { say(`${grabName(_dgrab)} let go`); tick(440) } _dgrab = null } }
  document.addEventListener('keydown', e => {
    if ((e.key === 'g' || e.key === 'G') && !e.repeat && !e.defaultPrevented && !isEditable(document.activeElement)) {
      if (_dgrab) { e.preventDefault(); dgrabRelease(); return }   // LATCH: second G lets go
      const ae = document.activeElement
      const head = ae && ae.closest && ae.closest('.card-head, .agent-bar')
      const el = head && head.closest('.card, .agent-bar')
      if (!el || !window.OZ_DOCK) return
      _dgrab = el; el.classList.add('kbd-grab'); e.preventDefault(); tick(660)
      say(`grabbed ${grabName(el)} — arrows dock it, the desk is the middle, G again to let go`)
      return
    }
    if (_dgrab && e.key === 'Escape') { e.preventDefault(); e.stopImmediatePropagation(); dgrabRelease(); return }   // Esc = let go too
    if (_dgrab && EDGEK[e.key]) {
      e.preventDefault(); e.stopImmediatePropagation()   // the grab outranks arrow-travel
      const cur = _dgrab.dataset.edge, dir = EDGEK[e.key]
      if (cur && cur !== 'center' && dir === OPP[cur]) { window.OZ_DOCK.toDesk(_dgrab); say(`${grabName(_dgrab)} back on the desk`) }
      else { window.OZ_DOCK.toWing(_dgrab, dir); say(`${grabName(_dgrab)} docked ${dir}`) }
      tick(520)
      const h = _dgrab.querySelector('.card-head') || _dgrab
      if (h) h.focus({ preventScroll: true })            // focus rides along with the moved card
    }
  }, true)
  window.addEventListener('blur', () => dgrabRelease(true))

  // ── ? = THE KEY MAP (Sum: "key map overlay for sure") — big type, the whole travel language on one card ──
  function keymapToggle() {
    let k = document.getElementById('oz-keymap')
    if (k) { k.remove(); return }
    k = document.createElement('div'); k.id = 'oz-keymap'
    k.setAttribute('role', 'dialog'); k.setAttribute('aria-label', 'keyboard travel guide')
    k.innerHTML = `<div class="oz-keymap-box"><h2>⌖ travel keys</h2><dl>
      <dt>⌖ / F6</dt><dd>focus mode on–off (F6 lands where the mouse is)</dd>
      <dt>arrows</dt><dd>walk every control · ← goes back</dd>
      <dt>Tab</dt><dd>big hops — field to field, editor to editor</dd>
      <dt>Enter</dt><dd>dive in / press the thing</dd>
      <dt>Esc</dt><dd>pop out of a text box, then climb — box → card → desk</dd>
      <dt>G</dt><dd>grab (latch): a tool, a card, a slider — arrows move it — G lets go</dd>
      <dt>R</dt><dd>read the card I'm on out loud (R again stops)</dd>
      <dt>?</dt><dd>this guide</dd></dl>
      <p>Esc or ? closes.</p></div>`
    k.addEventListener('click', () => k.remove())
    document.body.appendChild(k)
  }
  document.addEventListener('keydown', e => {
    if (e.key === '?' && !isEditable(document.activeElement) && !e.defaultPrevented) { e.preventDefault(); keymapToggle(); return }
    if (e.key === 'Escape') { const k = document.getElementById('oz-keymap'); if (k) { e.preventDefault(); e.stopImmediatePropagation(); k.remove() } }
  }, true)

  // ── R = READ THIS TO ME (Sum: "it's free, do it") — speak the card (or surface) focus sits on; R stops. ──
  document.addEventListener('keydown', e => {
    if ((e.key !== 'r' && e.key !== 'R') || e.metaKey || e.ctrlKey || e.altKey || e.repeat || e.defaultPrevented || isEditable(document.activeElement)) return   // BARE R only — ⌘R/⌘⇧R are the browser's reload, not a request to be read to (the ears bug, 2026-07-24)
    // through the ONE voice service now (Sum 2026-07-21) — force:true so it reads even when the
    // read-aloud toggle is off (this is an explicit key press). when OZ_EAR gets a native voice, this
    // rides it for free. fall back to the raw API only if voice.js somehow didn't load.
    const V = window.OZ_VOICE
    if (V && V.hasTTS) {
      if (V.isSpeaking()) { V.hush(); say('stopped reading'); return }
    } else if (!window.speechSynthesis) return
    else if (speechSynthesis.speaking) { speechSynthesis.cancel(); say('stopped reading'); return }
    const ae = document.activeElement
    const surf = (ae && ae.closest && ae.closest('.card, .agent-bar, #topbar')) || document.getElementById('main-col')
    if (!surf) return
    const text = (surf.innerText || '').replace(/\s+/g, ' ').trim().slice(0, 4000)
    if (!text) return
    e.preventDefault()
    if (V && V.speak) V.speak(text, { force: true, rate: 1.02 })
    else { const u = new SpeechSynthesisUtterance(text); u.rate = 1.02; speechSynthesis.speak(u) }
  })

  // (export happens once at the end of the file — sweep · popOut · say · tick)

  // ── ESC POPS OUT — the no-trap rule. popOut blurs the field, lands focus on the holding surface,
  //    and FLASHES a dashed ring there (Sum: "escape isn't working" — it was, invisibly. now you SEE it). ──
  const isEditable = ae => !!ae && ae !== document.body &&
    (ae.matches('input, textarea, select, [contenteditable="true"]') || !!ae.closest('.monaco-editor'))
  function popOut(ae) {
    ae.blur()
    const card = ae.closest('.card, #topbar, .mc-body-wrap') || document.getElementById('main-col')
    if (!card) return
    if (!card.hasAttribute('tabindex')) card.setAttribute('tabindex', '-1')
    card.focus({ preventScroll: true })
    card.classList.add('a11y-popped'); setTimeout(() => card.classList.remove('a11y-popped'), 1600)
  }
  // bubble phase (always on): anything that WANTS Esc (dropdowns, dialogs, Monaco widgets) preventDefaults
  // first and we stand down. Monaco eats plain Esc → ⇧Esc is the guaranteed exit there (bound in the card).
  document.addEventListener('keydown', e => {
    if (e.key !== 'Escape' || e.defaultPrevented) return
    if (isEditable(document.activeElement)) popOut(document.activeElement)
  })

  // ── ⌨ FOCUS MODE (Sum 2026-07-14) — the topbar ⌨ toggle, up by zoom + theme. keyboard travel becomes
  //    KING: focus ring on EVERY focus (not just keyboard-detected) · Esc pops out of ANY field in CAPTURE
  //    phase (beats Monaco + widget Esc — never trapped) · Enter dives INTO a popped surface's first control. ──
  let _kbd = false; try { _kbd = localStorage.getItem('oz_kbd_mode') === '1' } catch (_) {}
  function setKbd(on) {
    _kbd = !!on
    document.body.classList.toggle('kbd-mode', _kbd)
    try { localStorage.setItem('oz_kbd_mode', _kbd ? '1' : '0') } catch (_) {}
    if (_kbd) say('focus mode on — arrows walk, left goes back, Tab hops big, Enter dives in, Escape climbs out, G grabs and lets go, R reads aloud, question mark shows the key map')
    else say('focus mode off')
  }
  if (_kbd) setKbd(true)
  window.OZ_KBD = { on: () => _kbd, toggle: () => setKbd(!_kbd), set: setKbd }
  // ── the shared tabbable walk + the live pointer (F6 lands focus where the MOUSE is) ──
  const tabbables = () => [...document.querySelectorAll('button, [href], input, select, textarea, [tabindex="0"]')]
    .filter(el => el.offsetParent !== null && !el.disabled)
  let _px = 0, _py = 0
  document.addEventListener('mousemove', e => { _px = e.clientX; _py = e.clientY }, { passive: true })
  // ── ARROWS TRAVEL (Sum: "hook it to arrows too — I want BACK") — in focus mode, outside any editable:
  //    → / ↓ = next thing · ← / ↑ = BACK. bubble phase, so the grab key + widgets that claim arrows win first. ──
  document.addEventListener('keydown', e => {
    if (!_kbd || e.defaultPrevented) return
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight' && e.key !== 'ArrowUp' && e.key !== 'ArrowDown') return
    const ae = document.activeElement
    if (isEditable(ae)) return                                   // arrows still move the caret while editing
    const all = tabbables(); if (!all.length) return
    const i = all.indexOf(ae), fwd = e.key === 'ArrowRight' || e.key === 'ArrowDown'
    const target = i < 0 ? (fwd ? all[0] : all[all.length - 1]) : all[(i + (fwd ? 1 : -1) + all.length) % all.length]
    e.preventDefault(); target.focus()
  })
  // ── F6 = THE QUASIMODE (Sum's fix for "can't edit while it's on"): tap to flip focus mode ON right
  //    where the mouse cursor sits · arrow to the new place · tap again = OFF, editors back to normal.
  //    F6 is the closest thing to an international key for "move between panes". ──
  document.addEventListener('keydown', e => {
    if (e.key !== 'F6') return
    e.preventDefault()
    setKbd(!_kbd)
    if (_kbd) {
      const el = document.elementFromPoint(_px, _py)
      const t = el && (el.closest('button, [href], input, select, textarea, [tabindex="0"]') || el.closest('.card, #topbar'))
      if (t) {
        if (!t.hasAttribute('tabindex') && !t.matches('button, [href], input, select, textarea')) t.setAttribute('tabindex', '-1')
        t.focus({ preventScroll: true })
      }
    }
    const kb = document.querySelector('.tb-kbd'); if (kb) kb.classList.toggle('active', _kbd)   // the collar-red .active, same as deck/drawer
  }, true)
  document.addEventListener('keydown', e => {   // capture: in focus mode, popping out BEATS everything
    if (!_kbd || e.key !== 'Escape') return
    const ae = document.activeElement
    if (!isEditable(ae)) return
    e.preventDefault(); e.stopImmediatePropagation()
    popOut(ae)
  }, true)
  document.addEventListener('keydown', e => {   // Enter DIVES: from a popped surface into its first control
    if (e.key !== 'Enter' || e.defaultPrevented) return
    const ae = document.activeElement
    if (!ae || ae.getAttribute('tabindex') !== '-1' || isEditable(ae)) return
    if (ae.matches('button, a[href], [role="button"]')) return
    const f = ae.querySelector('button, [href], input, select, textarea, [tabindex="0"], [contenteditable="true"]')
    if (f) { e.preventDefault(); f.focus() }
  })
  // focus mode TAB — TWO GRANULARITIES, on purpose (Sum 2026-07-14: "I liked tab and arrow doing
  // different things — handy"). Native Tab in WebKit hops COARSE (field → field, editor → editor,
  // skipping buttons — Safari's policy, kept as a FEATURE); the ARROWS are the fine walk over every
  // control. we only intervene when a TRAPPING editor (Monaco · contenteditable) would swallow Tab:
  // hop the whole editor block instead. (an earlier fully-synthetic Tab flattened the two — reverted.)
  document.addEventListener('keydown', e => {
    if (!_kbd || e.key !== 'Tab') return
    const ae = document.activeElement
    const trap = ae && (ae.closest('.monaco-editor') || ae.closest('[contenteditable="true"]'))
    if (!trap) return                                            // not in a trap → native coarse Tab, untouched
    e.preventDefault(); e.stopImmediatePropagation()
    const host = trap.closest('.mc-editors') || trap             // hop the WHOLE editor, not one inner widget
    const all = tabbables().filter(el => !host.contains(el))
    if (!all.length) return
    const pos = all.findIndex(el => host.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING)
    const target = e.shiftKey ? (pos <= 0 ? all[all.length - 1] : all[pos - 1]) : (pos < 0 ? all[0] : all[pos])
    target.focus()
  }, true)
  // Esc CLIMBS — on an already-popped surface, Esc goes up one more level (body-wrap → card → the desk →
  // the topbar), each hop flashed. you can always ladder your way OUT to open air; ⌨ itself turns the mode off.
  document.addEventListener('keydown', e => {
    if (e.key !== 'Escape' || e.defaultPrevented) return
    const ae = document.activeElement
    if (!ae || isEditable(ae) || ae.getAttribute('tabindex') !== '-1') return
    const up = ae.parentElement && ae.parentElement.closest('.card, #main-col, #topbar')
    if (!up) return
    if (!up.hasAttribute('tabindex')) up.setAttribute('tabindex', '-1')
    up.focus({ preventScroll: true })
    up.classList.add('a11y-popped'); setTimeout(() => up.classList.remove('a11y-popped'), 1600)
  })

  // ── FOCUS MEMORY (Sum 2026-07-14) — a card remembers the control you were on; reopening it puts you
  //    back there (orientation — WCAG 3.0's cognitive pillar). WeakMap → gone with the card, no leak. ──
  const _lastFocus = new WeakMap()
  document.addEventListener('focusin', e => {
    const c = e.target.closest && e.target.closest('.card, .agent-bar')
    if (c && e.target !== c) _lastFocus.set(c, e.target)
  })
  function restoreFocus(cardEl) {
    if (!_kbd) return                                    // only in focus mode — mouse users keep click-focus
    const f = _lastFocus.get(cardEl)
    if (f && cardEl.contains(f) && f.offsetParent !== null) setTimeout(() => f.focus({ preventScroll: true }), 0)
  }

  // ── the SCROLL PIN — the shell NEVER scrolls ────────────────
  // base.css says html,body{overflow:hidden} ("page never scrolls. cards do")
  // but WebKit still scrolls hidden boxes to reveal focus inside an iframe —
  // toggling clock settings walked the whole desk off-screen, topbar gone,
  // no scrollbar to come back with (Sum 2026-07-15). any silent shift on a
  // shell-level box snaps straight back; cards keep their own inner scroll.
  const _pinBoxes = () => [document.documentElement, document.body,
                           document.getElementById('zoom-root'), document.getElementById('card-stack')]
  function pinDesk() {
    if (window.scrollX || window.scrollY) window.scrollTo(0, 0)
    for (const el of _pinBoxes())
      if (el && (el.scrollTop || el.scrollLeft)) { el.scrollTop = 0; el.scrollLeft = 0 }
  }
  window.addEventListener('scroll', pinDesk, true)   // capture — container scrolls don't bubble
  setInterval(pinDesk, 1500)                          // belt & braces for shifts with no event
  pinDesk()

  window.OZ_A11Y = { sweep, popOut, say, tick, restoreFocus, pinDesk }   // shared voice + earcons + memory — beans ride the same rails
})()
