// bar-buttons.js — the two persistent bar buttons that flank the jewels, + window.OZ_HIL (the HIL queue).
//
// Sum's "last human job" made physical. On every bot bar, flanking the g/a/r jewels:
//   • 🟢 GREEN (bless) — LEFT of the jewels. ALWAYS present, DIM by default. Glows + blinks ONLY when the bot
//     is waiting on you: a permission grant above its tier, or ANY HIL ask. Press it → grant the oldest pending
//     ask (runs that one command). "press green when it glows." (built here.)
//   • 🔴 RED (stop) — RIGHT of the jewels. Dark at full stop; glows red ONLY while a run is live (something to
//     halt). "hit read if I smell smoke." (icon = cards.js mkStop; the .armed glow = desk driving + clioz.css.)
//
// window.OZ_HIL is the SHARED queue any feature posts asks to. Today clioz-loop posts its above-tier grants here
// so the bar button glows across the room (in addition to the in-panel button). ADDITIVE — self-mounts the green
// button via an observer (oz-perm.js's idiom).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   OZ_HIL — pending human-in-the-loop asks, ...... search: "OZ_HIL — pending"
//   persistence (Sum 2026-07-09) — the flashing ... search: "persistence (Sum"
//   the green bless button — reflect the queue: ... search: "the green bless button"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the green "bless" button that appears
//    **on every bot bar (left of the jewels) and the shared human-in-the-loop queue it reflects. It
//    **exports `window.OZ_HIL` (the queue API: `ask`, `resolve`, `deny`, `cancel`, `count`, `next`)
//    **and `window.OZ_HIL_refresh` (the refresh function). Any feature that needs to post a
//    **permission grant or HIL ask depends on `OZ_HIL.ask()` at line 62.
//
//    **TOUCH HERE** —
//    - Change the green button's icon → `GREEN_SVG` L16
//    - Change the button's label text or tooltip → `refresh()` L112 (the title-setting logic at
//    - L120–122)
//    - Change what happens when the button is clicked → the click handler in `mkBless()` L142
//    - Change the waiver flow (irreversible asks) → `resolve()` L77–81
//    - Change what gets persisted across reopen → the filter at L30 and the restore logic at L54–55
//    - Change the localStorage key → `PKEY` L25
//    - Change the red button's deny behavior → `deny()` L88 and the deny-armed toggle at L126
//    - Add a new field to a pending ask → update the object shape at L64–66 and the save/restore
//    - maps at L31 and L54
//
//    **TRAPS** —
//    - `PKEY` at L25 is the localStorage key; changing it orphans all saved pending asks from users
//    - who reopen the page.
//    - The shape of objects in `pending[bot]` (L19) must match what `savePending()` filters at
//    - L30–31 and what `restorePending()` reconstructs at L54–55; a mismatch silently loses data.
//    - `seq` at L20 is a global counter; it must never reset or collide with restored IDs (L53).
//    - The button is wired only once per bar (`bar._blessWired` at L137); if you change the DOM
//    - structure, `mkBless()` may fail silently and never wire the button.
//    - `barOf()` at L109 uses `data-agent` attribute; if the bar's data attribute name changes
//    - elsewhere, the button won't find its bar.
//    - `refresh()` is called after every state change (L67, L81, L83, L92, L100, L146); if you add
//    - new state, you must call `refresh()` to update the UI.
//    - The irreversible waiver persists across reopen (L81 comment); if you change the presses
//    - logic, mid-signing users will be stuck.
//
//    **DO NOT** —
//    - Do not rename `OZ_HIL` or change its API shape; other files call `OZ_HIL.ask()`,
//    - `OZ_HIL.resolve()`, etc.
//    - Do not move the `restorePending()` call at L106; it must run after `OZ_HIL` is defined and
//    - before any bar mounts.
//    - Do not change the button's CSS class name `ab-bless` (L139) without updating the selectors
//    - in `refresh()` at L116.
//    - Do not change the red button's deny logic here; the red button itself is built in cards.js
//    - (see L8 comment).
//    - Do not add timeout logic to pending asks; the design is "nothing runs till you press" (L24
//    - comment).
//    - Do not add new persistence fields without updating both the save filter (L30–31) and the
//    - restore map (L54–55).
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'

  var GREEN_SVG = '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg>'

  // ── OZ_HIL — pending human-in-the-loop asks, per bot ──────────────────────────────────────────
  var pending = {}   // botId -> [ { id, label, run, persist } ]
  var seq = 0
  function list(bot) { return pending[bot] || (pending[bot] = []) }

  // ── persistence (Sum 2026-07-09) — the flashing green light + WHAT'S BEING ASKED survive a reopen / power-outage.
  //    no timeout: nothing runs till you press, so it just keeps flashing. on press after a restart, RE-RUN the act. ──
  var PKEY = 'toto_hil_pending'
  function savePending() {
    try {
      var out = {}
      for (var bot in pending) {
        var arr = (pending[bot] || []).filter(function (e) { return e.persist })
          .map(function (e) { return { label: e.label, irreversible: !!e.irreversible, presses: e.presses || 0, persist: e.persist } })
        if (arr.length) out[bot] = arr
      }
      localStorage.setItem(PKEY, JSON.stringify(out))
    } catch (_) {}
  }
  function runGrant(p) {   // execute the granted act (the live cascade is gone after a restart) — lane wall still applies
    try {
      window.OZ_ACTOR = p.bot
      // (Sum 2026-07-09) replay the WHOLE STACK's file-writes first — write_file OVERWRITES, so it's idempotent;
      // this recovers any write that landed in memory but never flushed to disk before the power went out.
      if (p.stack && p.stack.files && window.TOOL_USE && window.TOOL_USE.write_file) {
        for (var name in p.stack.files) { try { window.TOOL_USE.write_file.run({ filename: name, content: p.stack.files[name], kind: 'code' }) } catch (_) {} }
      }
      var use = window.TOOL_USE && window.TOOL_USE[p.tool]; if (use && use.run) use.run(p.call)
    } catch (_) {} finally { window.OZ_ACTOR = null }
  }
  function restorePending() {
    try {
      var saved = JSON.parse(localStorage.getItem(PKEY) || '{}')
      for (var bot in saved) (saved[bot] || []).forEach(function (e) {
        if (!e || !e.persist) return
        var id = ++seq
        list(bot).push({ id: id, label: e.label || 'needs your OK', irreversible: !!e.irreversible, presses: e.presses || 0,
                         persist: e.persist, run: (function (p) { return function () { runGrant(p) } })(e.persist) })
      })
    } catch (_) {}
  }

  var OZ_HIL = {
    // post an ask: { label, run }. returns { id, resolve(), cancel() }. glows that bot's green bar button.
    ask: function (bot, spec) {
      var id = ++seq
      list(bot).push({ id: id, label: (spec && spec.label) || 'needs your OK', run: (spec && spec.run) || function () {},
                       deny: (spec && spec.deny) || null,   // (Sum 2026-07-09) the RED button denies → resolves the paused cascade so the bot hears "no" + responds
                       irreversible: !!(spec && spec.irreversible), presses: 0, persist: (spec && spec.persist) || null })   // (Sum) irreversible → 3-step; persist → survives reopen
      savePending(); refresh(bot)
      return { id: id, resolve: function () { OZ_HIL.resolve(bot, id) }, cancel: function () { OZ_HIL.cancel(bot, id) } }
    },
    // 2 Sep 2026 — what is waiting on a bot, labels only. For the rig's finger (hil_press) and its readback; changes nothing.
    peek: function (bot) { return list(bot).map(function (e) { return e.label }) },
    // grant an ask (default = the oldest) → RUN it, then clear the glow if that was the last one.
    resolve: function (bot, id) {
      var l = pending[bot]; if (!l || !l.length) return
      var i = id == null ? 0 : l.findIndex(function (e) { return e.id === id })
      if (i < 0) return
      var e = l[i]
      // (Sum 2026-07-09) an irreversible act SIGNS A 3-STEP MENTAL WAIVER — there's no Cmd-Z or Cmd-Q at the helm.
      if (e.irreversible && e.presses < 2) {
        e.presses++
        e.label = e.presses === 1 ? '⚠️ ARE YOU SURE? — this CANNOT be undone. press again.'
                                   : '✍️ SIGN THE WAIVER — last chance, no undo. press once more.'
        savePending(); refresh(bot); return   // the waiver step persists too — reopen mid-signing, you're still mid-signing
      }
      l.splice(i, 1); savePending(); refresh(bot)
      try { e.run() } catch (_) {}
    },
    // DENY the oldest ask (the RED button) → drop it + signal the paused cascade it was denied, so the bot
    // moves on / responds. then the NEXT ask in the queue shows (green keeps blinking if more are waiting).
    deny: function (bot, id) {
      var l = pending[bot]; if (!l || !l.length) return
      var i = id == null ? 0 : l.findIndex(function (e) { return e.id === id })
      if (i < 0) return
      var e = l.splice(i, 1)[0]; savePending(); refresh(bot)
      try { if (e.deny) e.deny() } catch (_) {}
    },
    // drop an ask WITHOUT running it (the panel went away / a bot got stripped).
    cancel: function (bot, id) {
      var l = pending[bot]; if (!l) return
      var i = id == null ? 0 : l.findIndex(function (e) { return e.id === id })
      if (i < 0) return
      l.splice(i, 1); savePending(); refresh(bot)
    },
    count: function (bot) { return (pending[bot] || []).length },
    next: function (bot) { var l = pending[bot]; return l && l[0] }
  }
  window.OZ_HIL = OZ_HIL
  restorePending()   // (Sum 2026-07-09) reopen / power-outage → the pending asks are back in the queue; each bar's mkBless(refresh) lights the green flash when it mounts

  // ── the green bless button — reflect the queue: dim at 0, glow+blink at 1+ ─────────────────────
  function barOf(bot) {
    try { var q = window.CSS && CSS.escape ? CSS.escape(bot) : String(bot).replace(/"/g, '\\"'); return document.querySelector('.agent-bar[data-agent="' + q + '"]') } catch (_) { return null }
  }
  function refresh(bot) {
    try {
      var bar = barOf(bot); if (!bar) return
      var n = OZ_HIL.count(bot), nx = OZ_HIL.next(bot)
      var b = bar.querySelector('.ab-bless')
      if (b) {
        b.classList.toggle('armed', n > 0)
        b.setAttribute('data-n', n > 1 ? String(n) : '')
        b.title = n
          ? (nx ? 'the bot wants your OK to run:\n' + nx.label : 'the bot is waiting on you — press to allow') + (n > 1 ? '   (+' + (n - 1) + ' more waiting)' : '')
          : 'nothing needs you right now'
      }
      // (Sum 2026-07-09) the RED button blinks to DENY while a green ask is pending (else it's the run's halt)
      var stop = bar.querySelector('.card-stop')
      if (stop) { stop.classList.toggle('deny-armed', n > 0); if (n > 0) stop.title = 'DENY this ask — the bot is told no + moves on' }
    } catch (_) {}
  }
  window.OZ_HIL_refresh = refresh

  function mkBless(bar) {
    try {
      if (!bar || bar._blessWired || !bar.classList || !bar.classList.contains('agent-bar')) return
      var head = bar.querySelector('.ab-head'); if (!head) return
      var bot = ''; try { bot = bar.dataset && bar.dataset.agent } catch (_) {}
      if (!bot) return
      bar._blessWired = true
      var b = document.createElement('button')
      b.className = 'ab-bless'; b.type = 'button'; b.setAttribute('data-n', ''); b.title = 'nothing needs you right now'
      b.innerHTML = GREEN_SVG
      b.addEventListener('mousedown', function (e) { e.stopPropagation() })                 // press without collapsing/dragging the bar
      b.addEventListener('click', function (e) { e.stopPropagation(); OZ_HIL.resolve(bot) }) // grant the OLDEST pending ask
      var jewels = head.querySelector('.card-jewels')                                        // sit just LEFT of the jewels
      if (jewels) head.insertBefore(b, jewels)
      else { var stop = head.querySelector('.card-stop'); if (stop) head.insertBefore(b, stop); else head.appendChild(b) }
      refresh(bot)
    } catch (_) {}
  }
  function scan() { try { document.querySelectorAll('.agent-bar').forEach(mkBless) } catch (_) {} }

  if (document.readyState !== 'loading') scan(); else document.addEventListener('DOMContentLoaded', scan)
  try { new MutationObserver(scan).observe(document.documentElement, { childList: true, subtree: true }) } catch (_) {}
})()
