// climate.js — window.OZ_CLIMATE · the per-prompt weather log. THE TAIL THAT LIVES AFTER THE CONVO:
// every prompt (from ai or human) gets stamped ONCE with the clock's time · location · weather — all
// pulled from OZ_CLOCK, never a fetch (the clock's law: never block a turn). it's a changelog of
// WHERE + WHEN, by prompt. scrubbed to {loc, t, wx} it carries no user and no words — just a reading at
// a place + time, so it FEDERATES: strip the person, keep the weather → every user's local pull, one
// global live twin (toto's world-weather map · toto-trois' micro-local channel · a goldmine for the
// people who study climate). data, not surveillance — the only shape that leaves the device is anonymous.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   THE DIARY (Sum 2026-07-21: "never this hot ... search: "THE DIARY (Sum"
//   the AUTO logger (Sum: log regardless of ...... search: "the AUTO logger (Sum:"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for `window.OZ_CLIMATE`: a per-prompt
//    **weather log that stamps each conversation turn with time, location, and current conditions.
//    **It exports `log`, `feed`, `federated`, `clear`, `daily`, and `rollUp` (L87). The federated
//    **view strips identifying data and is designed to pool anonymously across users.
//
//    **TOUCH HERE**
//    - Change what gets logged per prompt → `log()` L19, edit the object `e` at L28–35
//    - Change the rolling cap (currently 1000 prompts) → `CAP` L10
//    - Change the daily diary cap (currently 5500 days) → `DCAP` L51
//    - Change which extremes the diary tracks → `rollUp()` L53, edit the `hi()` and `lo()` calls at
//    - L59–64
//    - Change the auto-log interval (currently 15 min) → `autoTick()` L80, edit the threshold at
//    - L81 and the `setInterval` at L85
//    - Change what the federated export includes → `federated()` L42, edit the `.map()` shape
//    - Disable auto-logging entirely → comment or remove L84–85
//
//    **TRAPS**
//    - `KEY` (L10) and `DKEY` (L51) are localStorage keys; renaming them orphans all existing user
//    - data. Same for the shape of `e` (L28–35) and daily record `r` (L57): any field rename breaks
//    - old logs.
//    - `log` is reassigned at L73 to wrap `_log` and call `rollUp`; both the original and wrapper
//    - must exist and be called in that order, or daily roll-up silently fails.
//    - `rollUp()` is called inside the wrapped `log()` (L73) in a try-catch that swallows errors; a
//    - crash in `rollUp` will not surface.
//    - The federated view (L42) filters to `e.loc && (e.now || e.air)` — entries with no location
//    - or no weather/air data are dropped silently and never leave the device.
//    - `autoTick` uses `lastAuto` (L79) to throttle; if you remove that state, the interval alone
//    - will not prevent double-logging on visibility flaps.
//
//    **DO NOT**
//    - Do not rename `OZ_CLIMATE`, `KEY`, `DKEY`, or any field in the logged objects without a
//    - migration strategy for existing localStorage.
//    - Do not move the `log` reassignment (L73) or change the order of `_log` call and `rollUp`
//    - call.
//    - Do not add user identifiers, words, or IP data to the logged shape — the federated export is
//    - designed to be anonymous.
//    - Do not add a fetch or network call to this file; the design rule (L3) is "never block a
//    - turn" — all data comes from `OZ_CLOCK`.
//    - Do not change the localStorage keys or the JSON shape without a plan to migrate or discard
//    - old data.
//    - Weather widget logic, forecast, or calculated fields (sunrise, moon phase, UV curve) belong
//    - in `OZ_CLOCK`, not here.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  if (window.OZ_CLIMATE) return
  const KEY = 'toto_climate_log', CAP = 1000   // a rolling local log; the device keeps the last CAP prompts
  const load = () => { try { return JSON.parse(localStorage.getItem(KEY) || '[]') } catch (_) { return [] } }
  const save = l => { try { localStorage.setItem(KEY, JSON.stringify(l.slice(-CAP))) } catch (_) {} }

  // stamp ONE prompt. src = where it came from: 'human' (typed) or 'ai' (a bot — e.g. toto conferring).
  // THE NOW, ONLY. log what a meteorologist CAN'T recompute from lat/lon + date: the measured reading here,
  // this minute. SKIP the calculable (sunrise/sunset, moon phase, the uv-peak curve) and the forecast (7-day) —
  // those are a widget-pull away, never a log row, never a web search. that's what makes the federated set
  // gold: un-calculable ground truth. current conditions + uv-now + particulates + visibility. no feels-like.
  function log(src) {
    const c = window.OZ_CLOCK
    const wx  = (c && c.weather()) || null
    const air = (c && c.air && c.air()) || null
    let loc = null
    try {
      const g = JSON.parse(localStorage.getItem('oz_geo_manual') || localStorage.getItem('oz_geo') || 'null')
      if (g && g.lat != null) loc = { lat: g.lat, lon: g.lon }   // coarse lat/lon — no city name, no user
    } catch (_) {}
    const e = {
      t: Date.now(),                                        // machine time — sortable, dedup-able
      when: (c && c.now()) || new Date().toLocaleString(),  // the human label ("almost 3, Mon")
      src: src || 'human',                                  // ai or human — the prompt's origin
      loc,
      now: wx  ? { temp: wx.temp, code: wx.code, desc: wx.desc, humidity: wx.humidity, wind: wx.wind, pressure: wx.pressure, vis: wx.vis } : null,
      air: air ? { uv: air.uv, aqi: air.aqi, pm25: air.pm25, pm10: air.pm10, ozone: air.ozone } : null,
    }
    const l = load(); l.push(e); save(l); return e
  }

  // the FEDERATED view — the only shape that ever leaves the device: location + time + reading, nothing else.
  // no src, no order, no words. a weather data-point at a place + time, anonymized. this is what a region's
  // users pool into the live twin. (the local feed() keeps src for the changelog; it never travels.)
  const federated = () => load().map(e => ({ loc: e.loc, t: e.t, now: e.now, air: e.air })).filter(e => e.loc && (e.now || e.air))
  const feed  = () => load()           // the local changelog, with src — stays on the device
  const clear = () => save([])

  // ── THE DIARY (Sum 2026-07-21: "never this hot this humid this long — are we saving logs?") ──
  // The 15-min detail above rolls over fast (localStorage-capped). So each reading also rolls UP into a
  // DAILY-EXTREMES record — tmin/tmax, peak humidity, total precip, peak wind/UV/AQI — one row per day.
  // A decade of that is ~0.8 MB (the raw 15-min would be ~8 MB/YEAR), so the diary can span years and
  // still answer "hottest stretch since I started logging" without ballooning. Capped at ~15 years.
  const DKEY = 'toto_climate_daily', DCAP = 5500
  const loadDaily = () => { try { return JSON.parse(localStorage.getItem(DKEY) || '{}') } catch (_) { return {} } }
  function rollUp(e) {
    if (!e || !(e.now || e.air)) return
    const day = new Date(e.t).toISOString().slice(0, 10)   // YYYY-MM-DD, machine day
    const d = loadDaily()
    const r = d[day] || { day, n: 0 }
    const n = e.now || {}, a = e.air || {}
    const hi = (k, v) => { if (v != null && (r[k] == null || v > r[k])) r[k] = v }
    const lo = (k, v) => { if (v != null && (r[k] == null || v < r[k])) r[k] = v }
    hi('tmax', n.temp); lo('tmin', n.temp)
    hi('hmax', n.humidity); hi('wmax', n.wind); lo('pmin', n.pressure)   // low pressure = the storms
    hi('uvmax', a.uv); hi('aqimax', a.aqi)
    if (n.precip != null) r.precip = Math.max(r.precip || 0, n.precip)   // peak rate seen today (mm/h)
    r.n++
    d[day] = r
    // trim oldest days past the cap (keep the diary bounded)
    const keys = Object.keys(d).sort()
    while (keys.length > DCAP) { delete d[keys.shift()] }
    try { localStorage.setItem(DKEY, JSON.stringify(d)) } catch (_) {}
  }
  const _log = log
  log = function (src) { const e = _log(src); try { rollUp(e) } catch (_) {} return e }   // every log also rolls up
  const daily = () => { const d = loadDaily(); return Object.keys(d).sort().map(k => d[k]) }   // the diary, oldest→newest

  // ── the AUTO logger (Sum: log regardless of chat) — a reading every 15 min WHILE 0z is open, so the
  // diary fills even on a quiet day. (Gaps while the app is closed are honest — a true 24/7 record wants
  // an always-on device, your Pi. The daily roll-up still captures every day you have 0z open at all.) ──
  let lastAuto = 0
  function autoTick() {
    if (Date.now() - lastAuto < 14 * 60000) return   // no more than ~1/15min even across visibility flaps
    try { if (window.OZ_CLOCK && window.OZ_CLOCK.weather && window.OZ_CLOCK.weather()) { lastAuto = Date.now(); log('auto') } } catch (_) {}
  }
  setTimeout(autoTick, 60000)               // first reading a minute after boot (let the weather load)
  setInterval(autoTick, 15 * 60000)         // then every 15 minutes

  window.OZ_CLIMATE = { log, feed, federated, clear, daily, rollUp }
})()
