// clioz-loop.js — window.OZ_CLIOZ · the agentic loop that makes a bot DRIVE via CLI.
//
// Step 1 (cli-harness.js / window.OZ_CLI) parses + classifies + gates shell. THIS module closes the loop:
// it wraps window.runTurn (additively, the same trick voice.js uses — runTurn resolves to { text, error }),
// and when a CLIOZ-ENABLED bot's reply contains shell, it renders a GATED panel into that bot's stream:
//   · denied  → a red wall, no run button (the harness would refuse it anyway; we don't even offer it)
//   · read    → a ▶ run that dry-runs immediately (read + dry-run = zero blast radius)
//   · write/sharp → a ▶ run that goes through window.OZ_CLI.run WITHOUT a bound confirm, so the harness
//                   raises its "super-super-are-you-sure" ozConfirm — the human reads the exact command first.
// Then ↩ feed the transcript back to the bot (bounded by maxHops) so it continues WITH the results.
//
// STILL DRY-RUN: window.OZ_CLI has no real executor installed, so nothing touches the filesystem. This is the
// loop's shape; the real hands (the rust run_cli wall) are deferred to a supervised session. ADDITIVE — edits
// nothing; self-mounts by wrapping runTurn once (idempotent) after it exists.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   wrap runTurn ONCE (chain any prior wrap, ...... search: "wrap runTurn ONCE"
//   a completed reply from an enabled bot → run ... search: "a completed reply from"
//   boot — wrap now + retry as bars/runTurn ....... search: "boot — wrap now + retry"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the agentic loop that intercepts bot
//    **replies, extracts shell commands, gates them by permission, runs them (dry-run or real), and
//    **feeds results back to the bot. It exports `window.OZ_CLIOZ` with `config`, `onReply`,
//    **`feedBack`, `hasShell`, and test hooks `_wrap` and `_hops`.
//
//    **TOUCH HERE**
//    - The loop list DERIVES from AGENT_DATA nav (the card is the grant) — give a bot a card, it joins; jem is the one named exception
//    - Change the hop limit (runaway guard) → `config.maxHops` L25
//    - Change the shell tutorial text → `window.OZ_CLIOZ_SYSTEM` L31–38
//    - Change how a result bar looks or behaves → `resultBar()` L120–131
//    - Change the delay before feeding results back → `scheduleFeed()` L78 (the `700` ms timeout)
//    - Change what "granted" means (permission check) → `granted()` L75
//    - Add coaching/advice to a result → `runOne()` L83–95, specifically the `entry.coach`
//    - assignment L92
//
//    **TRAPS**
//    - `window.runTurn` must exist before `wrapRunTurn()` L49 is called; `boot()` L161 retries
//    - every 400ms until it does. If you change the retry logic, the loop may never start.
//    - `hops` L40 is a live object keyed by `barKey(bar, id)` L45. If you change how `barKey`
//    - constructs its string, old hop counts orphan and the guard resets per conversation.
//    - `realExec` L41 is set only by `installExecutor()` L149 and read by `hasShell()` L172. If you
//    - add a second path that should set it, both must be synchronized.
//    - `feedTimer` L76 is scoped inside `onReply()` and cleared/reset in `scheduleFeed()` L78–80.
//    - If you add async work, the debounce may fire early or leak.
//    - The `_clioz` flag L60 on `window.runTurn` prevents double-wrapping. If you remove it, the
//    - wrap will chain infinitely on reload.
//    - `transcript` L76 is a local array that accumulates results and is spliced in
//    - `scheduleFeed()` L80. If you change when it's cleared, results may duplicate or vanish.
//
//    **DO NOT**
//    - Do not rename `window.OZ_CLI`, `window.OZ_PERM`, `window.OZ_HIL`, `window.OZ_LANE`, or
//    - `window.__TAURI__` — these are injected by other modules and this file only reads them.
//    - Do not move the permission check (`granted()` L75) into a different file; it lives here
//    - because it gates the entire reply flow.
//    - Do not add new config keys without exposing them in `window.OZ_CLIOZ.config` L169; tests and
//    - the UI may read them.
//    - Do not change the shape of `transcript` entries (cmd, klass, line, coach) without updating
//    - `feedBack()` L134–145, which serializes them back to the bot.
//    - Do not add a real filesystem executor here; that belongs in the rust `run_cli` wall or in
//    - `window.OZ_CLI.setExecutor()` L154.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'

  var config = {
    // the CLIOZ loop bots — their replies are scanned for shell / oz* and gated. capability is universal (the
    // OZ_CLI wrap routes any oz* for any bot); this list decides whose replies the loop WATCHES + who gets taught.
    // each bot is taught only its OWN oz* programs (scoped clues, see buildSystem + oz-app-cli OWNERS): nurse →
    // ozprep/ozchart · wellness → ozfood/ozwell · pa → ozmail/ozcal · writer → ozdoc · tutor → ozlearn.
    // ⭐ EVERY BOT THAT HOLDS A CARD (Sum 2026-08-16: "use the maze I already built… yes I want all
    //    bots to have that"). This list gated OZ_LANE.whenWhichClue() — the two-lane guide — so 9 of
    //    the 18 carded bots got the maze and the rest were left to work it out per turn. Cardless chat
    //    bots (aoladdin, alpha, muskett, asterix) stay OFF on purpose: no tools, nothing to route.
    //    yanker is a stub. NOTE this grants clues + app-CLI + lanes only; the SHELL is `shellBots`.
    // DERIVED, not hand-kept (2026-08-21, closes SPEC-FOR-FABLE job 1). THE CARD IS THE GRANT —
    //    same law as the tool bolt (conductor.js cardsFor): every bot whose bean owns a card
    //    (non-empty nav) gets the maze automatically, next launch, no list to remember. The
    //    cardless chat bots (aoladdin, alpha, muskett, asterix, toto) fall out naturally.
    //    ⚠ jem is the ONE exception, kept by name: cardless but armed (image-gen via `also`),
    //    and it was in the old hand list — grandfathered deliberately, not drift.
    enabledBots: Object.keys(window.AGENT_DATA || {})
      .filter(id => { const a = window.AGENT_DATA[id]; return a && Array.isArray(a.nav) && a.nav.length > 0 })
      ,   // (26 Aug) the ['jem'] concat went with the bot — every carded bot already gets OZ_LANE's two-lane guide
    // ⭐ MOVED TO THE BOT'S RECORD, 26 Aug (caps: ["shell"]). WAS: shellBots: ['coder'].
    shellBots: (window.REG && window.REG.withCap) ? window.REG.withCap('shell') : [],   // who gets the FILE shell cue (cat -n / heredoc / sed)
    maxHops: 3,                            // cap emit→run→emit cycles per bar (no runaway)
    showReads: true,
    autoFeed: false                        // false = a human clicks "↩ send results"; true = auto-continue (still maxHops-bounded)
  }
  // the FILE-shell fragment engine.buildSystem prepends for a shellBot (only when the executor is live). plain bash,
  // no new grammar. the app-CLI cue cards are appended SEPARATELY + scoped per bot (buildSystem → OZ_APP_CLI.clues(id)).
  window.OZ_CLIOZ_SYSTEM =
    'You have a shell — write commands in a ```sh code block; they run sandboxed in ~/totoII/sandbox.\n' +
    'FILES (on disk): read = `cat -n path` · list = `ls -la` · search = `grep -n "text" path` · ' +
    'create/overwrite = `cat > path <<\'EOF\'` … `EOF` · quick edit = `sed -i \'\' \'s/old/new/\' path`.\n' +
    'For APP DATA (not files), use any `oz*` app commands listed below.\n' +
    'Read-only commands run on request; writes / risky commands need the human\'s OK first. ' +
    'After the commands run, read the results that come back and continue.\n' +
    '(You also still have your regular JSON tools — use whichever fits; the shell is the general path.)'

  var hops = {}                            // { barKey: count } — per-bar hop guard
  var realExec = false                     // true once rust run_cli is installed → panel says "sandboxed", not "dry-run"

  function enabled(id) { return config.enabledBots.indexOf(id) > -1 }
  function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
  function barKey(bar, id) { try { return (id || '') + ':' + ((bar && bar.dataset && bar.dataset.agent) || '') } catch (_) { return id || 'x' } }
  function log() { try { console.log.apply(console, ['[clioz]'].concat([].slice.call(arguments))) } catch (_) {} }

  // ── wrap runTurn ONCE (chain any prior wrap, e.g. voice's _voiced) ────────────────────────────────────
  function wrapRunTurn() {
    if (!window.runTurn || window.runTurn._clioz) return false
    var orig = window.runTurn
    var wrapped = function (bar, id, text, opts) {
      var p = orig(bar, id, text, opts)
      if (p && p.then) p.then(function (res) {
        try { if (res && res.text && !res.error && enabled(id) && window.OZ_CLI) onReply(bar, id, res.text) } catch (e) { log('onReply failed', e) }
      }, function () {})
      return p
    }
    for (var k in orig) { if (Object.prototype.hasOwnProperty.call(orig, k)) { try { wrapped[k] = orig[k] } catch (_) {} } }
    wrapped._clioz = true
    window.runTurn = wrapped
    return true
  }

  // ── a completed reply from an enabled bot → run its commands HEADLESS (no inline panel) ────────────────
  // Sum, 2026-07-05: killed the "silly inline cli" — an interactive widget in a LIVE-streaming convo raced the
  // stream, the accordion, and its own feed-back hops. Now: a GRANTED command runs SILENTLY; an ABOVE-tier one
  // lights the bot's GREEN bar button (OZ_HIL) to bless; each result lands as a COLLAPSED ESP bar (🧠 expands it)
  // so the convo archives the work without bloat. The interactive terminal the USER drives is the separate 🖥️ cli
  // card. Results feed back (debounced, maxHops-bounded) so the bot continues WITH them.
  function onReply(bar, id, text) {
    var planned = window.OZ_CLI.plan(text)
    if (!planned || !planned.length) return
    var perm = window.OZ_PERM
    var granted = function (p) { return p.klass !== 'denied' && (!perm || perm.grants(id, p.klass)) }
    var transcript = [], feedTimer = null

    function scheduleFeed() {   // batch a reply's results, then feed them back once (maxHops bounds the runaway)
      if (feedTimer) clearTimeout(feedTimer)
      feedTimer = setTimeout(function () { var batch = transcript.splice(0); if (batch.length) feedBack(bar, id, batch) }, 700)
    }

    function runOne(p) {
      return Promise.resolve(window.OZ_CLI.run(p.cmd, { klass: p.klass, confirmed: true, confirmedCmd: p.cmd })).then(function (rec) {
        var line = rec && rec.blocked ? '⛔ ' + (rec.reason || 'blocked')
          : rec && rec.refusedByHuman ? '↩ declined'
          : (rec && (rec.stdout || '(no output)')) + (rec && rec.dryRun ? ' · dry-run' : '')
        resultBar(bar, id, p.cmd, line)
        var entry = { cmd: p.cmd, klass: p.klass, line: line }
        // GOFAI post-run — did it land? blocked / errored / mangled → attach the "try the other lane" coaching so
        // the feed-back nudges a SWITCH instead of a re-hammer (the whole point of the two-lane maze).
        try { var ot = window.OZ_LANE && window.OZ_LANE.offTrack(p.cmd, rec); if (ot && ot.offTrack) entry.coach = ot.advice } catch (_) {}
        transcript.push(entry); scheduleFeed()
      }, function (err) { log('run failed', err) })
    }

    planned.forEach(function (p) {
      if (p.klass === 'denied') { resultBar(bar, id, p.cmd, '⛔ blocked — denylist / sandbox escape'); transcript.push({ cmd: p.cmd, klass: 'denied', line: '⛔ blocked' }); scheduleFeed(); return }
      // GOFAI pre-run — a multi-line body crammed into a fragile quoted arg (off track) must NOT run half-written.
      // hold it, and feed back the heredoc/JSON tutorial so the bot redoes it the safe way. (bounded by maxHops.)
      var lint = null; try { lint = window.OZ_LANE && window.OZ_LANE.lintCli(p.cmd) } catch (_) {}
      if (lint && !lint.ok) {
        resultBar(bar, id, p.cmd, '🧭 held — ' + (lint.issues[0] || 'off track') + (lint.tryLane ? ' · try the ' + lint.tryLane.toUpperCase() + ' lane' : ''))
        transcript.push({ cmd: p.cmd, klass: p.klass, line: '(held — not run)', coach: lint.advice }); scheduleFeed(); return
      }
      if (granted(p)) runOne(p)                                                        // within tier → runs silently
      else if (window.OZ_HIL) window.OZ_HIL.ask(id, { label: p.cmd, run: function () { runOne(p) } })   // above-tier → glow the bot's green bar button to bless
    })
  }

  function streamOf(bar) {
    try { return bar.querySelector('.msg-stream') || bar.querySelector('.convo') || bar } catch (_) { return bar }
  }

  function espOnFor(id) { try { return localStorage.getItem('toto_esp_' + id) === '1' } catch (_) { return false } }

  // append a run's result as a COLLAPSED ESP bar — matches the injection/fold bars (🧠 toggles it, click to peek),
  // so old commands + output stay in the convo without bloating it. (the command itself is already a collapsed
  // code bar from renderWithCode; this bar is its result.)
  function resultBar(bar, id, cmd, line) {
    var stream = streamOf(bar); if (!stream || !stream.appendChild) return
    var wrap = document.createElement('div'); wrap.className = 'msg msg-inj esp-bar cz-result'
    var head = document.createElement('button'); head.className = 'inj-head esp-head'
    var body = document.createElement('pre'); body.className = 'inj-body esp-body'; body.textContent = String(line); body.hidden = !espOnFor(id)
    var short = cmd.length > 48 ? cmd.slice(0, 46) + '…' : cmd
    var label = function () { head.textContent = '🖥 ' + short + (body.hidden ? '' : ' ▾') }
    head.addEventListener('click', function (e) { e.stopPropagation(); body.hidden = !body.hidden; label() })
    wrap._reLabel = label; label(); wrap.append(head, body)
    stream.appendChild(wrap)
    try { var sc = bar.querySelector('.convo-screen'); if (sc) sc.scrollTop = sc.scrollHeight } catch (_) {}
  }

  // feed the run transcript back to the bot so it continues WITH the results — bounded by maxHops.
  function feedBack(bar, id, transcript) {
    if (!transcript.length || !window.runTurn) return
    var key = barKey(bar, id)
    hops[key] = (hops[key] || 0) + 1
    if (hops[key] > config.maxHops) { log('maxHops reached for', key, '— not feeding back'); return }
    var body = '[clioz] ran:\n' + transcript.map(function (t) {
      var s = '$ ' + t.cmd + '\n' + t.line
      if (t.coach) s += '\n↪ ' + t.coach   // GOFAI: the "switch lanes / use a heredoc" tutorial rides back with the result
      return s
    }).join('\n')
    window.runTurn(bar, id, body, { echo: false })
  }

  // install the REAL executor — the rust run_cli wall IS present in the 0z-bolt-clioz build. In a browser
  // (no __TAURI__ bridge) this no-ops and OZ_CLI stays dry-run. The JS HIL gate + BOTH rust guards still apply.
  function installExecutor() {
    try {
      if (!window.OZ_CLI || !window.OZ_CLI.setExecutor) return
      var core = window.__TAURI__ && window.__TAURI__.core
      if (!core || !core.invoke) return                 // no native bridge → stay dry-run
      window.OZ_CLI.setExecutor(function (cmd) { return core.invoke('run_cli', { cmd: cmd }) }, { rustGuard: true })
      realExec = true
      log('real executor installed (rust run_cli, sandboxed)')
    } catch (e) { log('installExecutor failed', e) }
  }

  // ── boot — wrap now + retry as bars/runTurn appear (runTurn is defined in workspace.js) ───────────────
  function boot() { installExecutor(); if (!wrapRunTurn()) setTimeout(boot, 400) }
  try {
    if (typeof document !== 'undefined' && document.addEventListener) {
      if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot()
    }
  } catch (_) {}

  window.OZ_CLIOZ = {
    config: config,
    onReply: onReply,                 // exposed for tests / manual drive
    feedBack: feedBack,
    hasShell: function () { return realExec },   // true ONLY when the rust run_cli is live (native bolt); web build = false
    _wrap: wrapRunTurn,
    _hops: function () { return hops }
  }
})()
