// fs.js — the NATIVE FLOOR under the sandbox. window.SANDBOX was a plain in-memory object: fast, but wiped
// on reload (the "git floor" the comments kept promising would go native). this makes it real. ~/totoII/sandbox
// is the folder; the in-memory object stays the working cache, and a PROXY mirrors every write to disk + a
// hydrate populates it from disk on boot. ONE interception point — no card edits — so every current and future
// writer (tool strikes · monaco/tiptap autosave · attach · webview) persists for free.
//
// in a plain browser (0zhub.com, dev) the floor is IndexedDB — same choke points, same version
// rules as the native side, survives reload. (was a no-op before 2026-08-09; localStorage was
// rejected: its ~5MB wall is what crashed the old web demo on a few large images.)
// loaded FIRST (with links.js) so the proxy is live before any card writes. window.OZ_FS is the API the
// card code calls for the deliberate bits: rollback versions (🟡/🏁) and the export-a-copy panel (🏁).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the proxy — set mirrors to disk (debounced ... search: "the proxy — set mirrors"
//   hydrate on boot — write to the RAW target .... search: "hydrate on boot — write"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for persisting the in-memory
//    **`window.SANDBOX` object to disk in Tauri. It exports `window.OZ_FS` (the public API for
//    **rollback versions and exports) and `window.SANDBOX` (the cache that all card code writes
//    **to).
//
//    **TOUCH HERE**
//    - Change the debounce delay (autosave batching) → `scheduleWrite()` L33, the `250` on L39
//    - Change which file extensions are treated as documents vs. code → `ready()` L47, the array on
//    - L54
//    - Change the MIME type or `kind` field assigned to hydrated files → `ready()` L47, L55
//    - Add a new deliberate persistence API (versions, exports, etc.) → `window.OZ_FS` L60–73
//    - Change the Tauri command names (`sandbox_write`, `sandbox_load_all`, etc.) → `inv()` calls
//    - on L38, L50, L63, L65, L67, L69, L70, L72
//
//    **TRAPS**
//    - `mirrorable()` L22 is the gate: only entries passing this check write to disk. Changing it
//    - silently orphans files (e.g., removing the `data:` URL check would try to persist ephemeral
//    - image previews). The 2MB size cap L25 is a safety limit.
//    - The Tauri command names (L38, L50, L63, L65, L67, L69, L70, L72) must match the backend
//    - exactly or calls fail silently (caught in `.catch()` blocks).
//    - `target` L31 must be the raw object, not the Proxy — hydration L52 writes directly to it so
//    - disk reads don't trigger proxy writes and loop back.
//    - The `kind` and `ext` fields L54–55 are persisted in the cache; changing their shape will
//    - orphan existing entries.
//    - Load order: this file must run before any card code writes to `SANDBOX` (comment L8 says it
//    - loads with links.js first).
//
//    **DO NOT**
//    - Rename `window.SANDBOX` or `window.OZ_FS` — card code and external tools depend on these
//    - names.
//    - Rename the Tauri command strings without updating the backend.
//    - Move the Proxy setup (L41–43) or change how `set` trap calls `scheduleWrite` — this is the
//    - only interception point (comment L4).
//    - Add synchronous file I/O or blocking reads — all disk access is async via `inv()`.
//    - Implement cache eviction or deletion logic here — that belongs in the card code or a
//    - separate cache manager.
//
//
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  function core() { return (window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__)) || null }
  function inv(cmd, args) {
    const c = core()
    if (!c || !c.invoke) return Promise.reject(new Error('not in tauri'))
    return c.invoke(cmd, args)
  }
  const NATIVE = !!(window.__TAURI__ && (window.__TAURI__.core || window.__TAURI__.invoke))

  // ── the WEB FLOOR (Sum 2026-08-09, for 0zhub.com: "use better thing then local storage") ──
  // in a browser there is no disk, so IndexedDB is the floor: gigabytes, async, survives reload —
  // localStorage's 5MB wall is what crashed the old web demo on a few large images. same choke
  // points as native (scheduleWrite · hydrate · OZ_FS), so card code never knows which floor it's on.
  // shape copied from TT_STORE (oz-ttscenes.js — the display shelf): open per call, close after
  // every transaction, one explicit promise-wrapped method per verb. same house, same wiring.
  function idb() {
    return new Promise((res, rej) => {
      const r = indexedDB.open('oz-sandbox', 1)
      r.onupgradeneeded = () => { r.result.createObjectStore('files'); r.result.createObjectStore('versions') }
      r.onsuccess = () => res(r.result)
      r.onerror = () => rej(r.error)
    })
  }
  const IDB = {
    async put(store, name, val) {
      const d = await idb()
      return new Promise((res, rej) => {
        const tx = d.transaction(store, 'readwrite')
        tx.objectStore(store).put(val, name)
        tx.oncomplete = () => { d.close(); res() }
        tx.onerror = () => { d.close(); rej(tx.error) }
      })
    },
    async del(store, name) {
      const d = await idb()
      return new Promise((res, rej) => {
        const tx = d.transaction(store, 'readwrite')
        tx.objectStore(store).delete(name)
        tx.oncomplete = () => { d.close(); res() }
        tx.onerror = () => { d.close(); rej(tx.error) }
      })
    },
    async get(store, name) {
      const d = await idb()
      return new Promise((res, rej) => {
        const tx = d.transaction(store, 'readonly')
        const req = tx.objectStore(store).get(name)
        tx.oncomplete = () => { d.close(); res(req.result) }
        tx.onerror = () => { d.close(); rej(tx.error) }
      })
    },
    async all(store) {
      const d = await idb()
      return new Promise((res, rej) => {
        const out = {}
        const tx = d.transaction(store, 'readonly')
        const cur = tx.objectStore(store).openCursor()
        cur.onsuccess = () => { const c = cur.result; if (c) { out[c.key] = c.value; c.continue() } }
        tx.oncomplete = () => { d.close(); res(out) }
        tx.onerror = () => { d.close(); rej(tx.error) }
      })
    },
  }

  // which entries are REAL files we keep on disk. skip the pointers (kind 'url' = a link, 'path' = a file://
  // preview pointer) and data: URLs (images live as data URLs — ephemeral previews, not source files).
  function mirrorable(v) {
    return v && typeof v === 'object' && typeof v.data === 'string'
      && v.kind !== 'url' && v.kind !== 'path'
      && !/^data:/.test(v.data) && v.data.length < 2000000
  }

  // ── the proxy — set mirrors to disk (debounced per file, so a typing-autosave burst is one write);
  //    a DELETE is cache-only (closing a preview tab must NOT erase the file — only the wrecker does, via
  //    OZ_FS.remove). reads pass straight through (default traps), so Object.keys/entries are unchanged. ──
  const target = (window.SANDBOX && typeof window.SANDBOX === 'object') ? window.SANDBOX : {}
  const timers = {}
  function scheduleWrite(name, v) {
    if (!mirrorable(v)) return
    clearTimeout(timers[name])
    const data = v.data
    timers[name] = setTimeout(() => {
      const w = NATIVE ? inv('sandbox_write', { name, content: data }) : IDB.put('files', name, data)
      w.catch(e => console.warn('[fs] write failed', name, e))
    }, 250)
  }
  window.SANDBOX = new Proxy(target, {
    // 2 Sep 2026 — every write is noted on window.__OZ_TURN_WRITES so the conductor can RE-READ what a tool wrote
    //    this turn (yt_transcript files a lecture; the retry que could not see it — write_file was the only write it
    //    tracked). The conductor clears the set at the top of each turn. One line, the one proxy every write passes.
    set(t, k, v) { t[k] = v; if (typeof k === 'string') { scheduleWrite(k, v); try { (window.__OZ_TURN_WRITES = window.__OZ_TURN_WRITES || new Set()).add(k) } catch (_) {} } return true },
  })

  // ── hydrate on boot — write to the RAW target (not through the proxy) so reading disk doesn't echo back as
  //    writes. a file a card already seeded THIS session wins (don't clobber live work with the stale disk copy). ──
  const ready = (async () => {
    try {
      const map = NATIVE ? await inv('sandbox_load_all') : await IDB.all('files')
      Object.keys(map || {}).forEach(name => {
        if (target[name]) return
        const ext = (name.split('.').pop() || '').toLowerCase()
        const data = String(map[name])
        // a data: URI from disk is a BINARY the loader handed back base64'd (sandbox_load_all,
        // 2026-08-28 — the class folder's images/PDFs). Stamp it img so previews render it; the
        // mirror's data:-refusal still holds, so hydrating never echoes it back to disk.
        const bin = /^data:/.test(data)
        const kind = bin ? (data.indexOf('data:image/') === 0 ? 'img' : 'doc') : (['md', 'txt', 'rtf'].includes(ext) ? 'doc' : 'code')
        target[name] = { kind, ext, mime: bin ? data.slice(5, data.indexOf(';')) : '', data }
      })
    } catch (e) { console.warn('[fs] hydrate failed', e) }
  })()

  window.OZ_FS = {
    native: NATIVE,
    ready,
    dir: () => inv('sandbox_dir'),
    // "find my files" — ensure the folder skeleton + open ~/totoII/sandbox in Finder. returns the path, null in-browser.
    reveal: () => NATIVE ? inv('reveal_sandbox').catch(e => { console.warn('[fs] reveal failed', e); return '' }) : Promise.resolve(null),
    // delete a file FOR GOOD (the monaco wrecker) — disk + its rollback history. cache eviction is separate.
    remove: name => NATIVE ? inv('sandbox_delete', { name }).catch(() => {})
      : Promise.all([IDB.del('files', name), IDB.del('versions', name)]).catch(() => {}),
    // ── ⭐ THE THIRD RUNG (Sum 2026-08-25: "delete sand box files" as its own button). The other two
    //    resets only ever touch localStorage; this is the one that reaches DISK, and it is deliberately
    //    the separate press because those two facts are not the same fact. Files a human dragged in, a
    //    bot wrote, or a card saved all live in ~/totoII/sandbox and survive every localStorage wipe —
    //    which is correct, and is also why somebody eventually needs a door that does reach them.
    //    ⚠ FOR GOOD. There is no sandbox trash: OZ_FS.remove is the wrecker, disk plus rollback history.
    //    So the caller owes a count first and a second press, same as the other two.
    //    Cache and disk go together — a name left in window.SANDBOX after its file is gone is the
    //    ghosting that ate a night once (two maps of one folder).
    peekSandbox: () => Object.keys(window.SANDBOX || {}),
    wipeSandbox: async () => {
      const names = Object.keys(window.SANDBOX || {})
      for (const n of names) {
        try { await window.OZ_FS.remove(n) } catch (_) {}
        try { delete window.SANDBOX[n] } catch (_) {}
      }
      return names.length
    },
    // a deliberate rollback checkpoint (🟡 save-version · 🏁 export) — appended to .versions, capped, deduped.
    saveVersion: (name, content) => NATIVE ? inv('sandbox_save_version', { name, content }).catch(() => {})
      : IDB.get('versions', name).then(a => {
          // same shape + rules as bolts.rs sandbox_save_version: a plain array of content
          // strings, dedupe against the last, cap at 20 (VERSIONS_MAX) — the UI reads both floors.
          const v = a || []
          if (v.length && v[v.length - 1] === content) return
          v.push(content)
          return IDB.put('versions', name, v.slice(-20))
        }).catch(() => {}),
    readVersions: name => NATIVE ? inv('sandbox_read_versions', { name }).then(a => a || []).catch(() => [])
      : IDB.get('versions', name).then(a => a || []).catch(() => []),
    // 🏁 export a copy elsewhere via the native save panel → the chosen path, '' if cancelled, null in-browser.
    exportCopy: (name, content) => NATIVE ? inv('export_copy', { name, content }).catch(e => { console.warn('[fs] export failed', e); return '' }) : Promise.resolve(null),
    // 🔒 restore ONE file straight onto the floor (2026-08-29, the safe's import — cards/settings/safe.js).
    //    Deliberately NOT through the proxy: mirrorable() refuses data: URIs by design, so a restored
    //    photo album would live only until the reload. Same write the drag-drop binaries ride; the next
    //    boot's hydrate re-stamps kind/ext from the content, exactly as it does for disk binaries.
    restore: (name, content) => NATIVE ? inv('sandbox_write', { name, content }) : IDB.put('files', name, content),
  }
})()
