// oz-ttmaps.js — the traveler's TWO MAPS (Sum 2026-07-20: "two maps, two shapes").
// FOR HUMANS: the traveler's chat head grows two small illustrated buttons —
//   🗺 the TIME MAP (your journeys as a timeline, spaced by real time) and
//   🌐 the SEARCH MAP (your curiosities as a branching web). both open a
//   full-screen card; click a journey's thumbnail to travel there again (free),
//   or click a subject to send the traveler off exploring it further.
// FOR AI:
//   • TIME MAP reads tt_trips (localStorage) + TT_STORE (IndexedDB thumbs).
//     stops are placed on a centered spine, the vertical gap ∝ the years
//     between them (a long jump = a long scroll), futures after the past.
//   • SEARCH MAP reads tt_subjects — grown by TT_LOGSUBJECT, called when the
//     traveler picks up a new subject (conductor) or paints a scene (ttscenes).
//   • window.OZ_MAPS = { time(), search(), close() }. the head buttons (added
//     in workspace.js for id==='timetravel') route here by delegation.
//   • revisit(date) flips the clock itself (no model call — a revisit is free).

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   THE SEARCH-MAP LOG — a subject bumps its ...... search: "THE SEARCH-MAP LOG — a"
//   a REVISIT is free: flip the clock ............. search: "a REVISIT is free: flip"
//   NOW ⇄ TRIP toggle (Sum 2026-07-21: "toggles ... search: "NOW ⇄ TRIP toggle (Sum"
//   the overlay shell (one instance; ✕ ............ search: "the overlay shell (one"
//   TIME MAP ...................................... search: "TIME MAP"
//   WHERE YOUR INTERESTS COME FROM (Sum ........... search: "WHERE YOUR INTERESTS"
//   SEARCH MAP — the vector web (SVG) ............. search: "SEARCH MAP — the vector"
//   ZOOM + PAN (Sum 2026-07-21: "I think we ....... search: "ZOOM + PAN (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the two illustrated maps (time and
//    **search) that appear as buttons on the traveler's chat head. It exports `window.OZ_MAPS = {
//    **time: openTime, search: openSearch, close }` (line 383), `window.TT_LOGSUBJECT()` (line 28)
//    **for recording user interests, `window.TT_NOWTRIP_REFRESH` (line 102) for updating the
//    **now/trip toggle button, and the click delegation that routes the three head buttons (lines
//    **388–392).
//
//    **TOUCH HERE** —
//    - Change the time map's visual layout (spine, gaps, era headers, card content) → `openTime()`
//    - L123
//    - Change what subjects appear on the search map or how they rank → `interests()` L236
//    - Change the search map's SVG layout (node positions, branches, hub) → `openSearch()` L266
//    - Change zoom/pan behavior or add controls → `wireCamera()` L331
//    - Change what happens when you click a journey thumbnail → `fillThumbs()` L193 or the revisit
//    - call at L184
//    - Change what happens when you click a search node → `explore()` L370
//    - Change the now/trip toggle's appearance or behavior → `toggleNowTrip()` L80 and
//    - `refreshNowTrip()` L94
//    - Change the overlay shell's styling or close behavior → `shell()` L107
//    - Change how subjects are logged or capped → `window.TT_LOGSUBJECT()` L28 and the 40-subject
//    - limit at L49
//
//    **TRAPS** —
//    - `OV_ID = 'ttm-overlay'` (line 18) is the overlay's DOM id; CSS and the close logic (line
//    - 105) both depend on this exact string.
//    - `tt_trips`, `tt_subjects`, `tt-last-trip`, `clock-taxonomy`, `clock-headlines` (lines 19–20,
//    - 77, 217–218) are localStorage keys; changing them orphans saved user data.
//    - The 40-subject cap (line 49) is a memory limit; removing it may cause the map to balloon.
//    - `revisit(date)` (line 57) polls for the clock iframe up to 40 times with 200ms delays (lines
//    - 60–66); if the clock's `TIME_JUMP` API changes, revisits silently fail.
//    - `refreshNowTrip()` (line 94) reads both `atTrip()` and `lastTrip()` to decide visibility;
//    - both must stay in sync or the button will hide/show incorrectly.
//    - The search map shows only the top 14 interests (line 273); if you change this, the SVG
//    - layout math (radii, angles, stagger at lines 284–288) may need tuning.
//    - `explore(label, under)` (line 370) calls `window.ozAskBot()` (line 380); if that API is not
//    - present, the click does nothing silently.
//    - The time map's year-gap scaling uses `Math.sqrt(delta) * 24` (line 147); changing this
//    - constant changes how "long jumps" feel visually.
//
//    **DO NOT** —
//    - Do not rename `window.TT_LOGSUBJECT`, `window.TT_NOWTRIP_REFRESH`, or `window.OZ_MAPS`
//    - without updating every call site (ttscenes.js, workspace.js, and the clock iframe).
//    - Do not change the localStorage key names without a migration strategy for existing users.
//    - Do not move the click delegation (lines 388–392) to another file; it must stay here to
//    - intercept the head buttons.
//    - Do not add new map types here; that belongs in a new file with its own `open*()` function
//    - exported via `OZ_MAPS`.
//    - Do not change the SVG namespace constant `SVGNS` (line 262) or the SVG creation helper
//    - `svg()` (line 263) without checking all callers.
//    - Do not add new localStorage reads/writes without documenting them in the comments at lines
//    - 8–12.
//
//
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const OV_ID = 'ttm-overlay'
  const readTrips = () => { try { return JSON.parse(localStorage.getItem('tt_trips') || '{}') } catch (_) { return {} } }
  const readSubj = () => { try { return JSON.parse(localStorage.getItem('tt_subjects') || '{}') } catch (_) { return {} } }
  const writeSubj = s => { try { localStorage.setItem('tt_subjects', JSON.stringify(s)) } catch (_) {} }
  const el = (tag, cls, txt) => { const n = document.createElement(tag); if (cls) n.className = cls; if (txt != null) n.textContent = txt; return n }
  const esc = s => String(s == null ? '' : s)
  const yearOf = d => { const m = /^(-?\d{1,4})/.exec(String(d || '')); return m ? +m[1] : 0 }

  // ── THE SEARCH-MAP LOG — a subject bumps its frequency; a leaf (a painted scene,
  //    a closer look) hangs under it. tiny + capped: the map is a memory, not a hoard. ──
  window.TT_LOGSUBJECT = function (subject, leaf) {
    subject = String(subject || '').trim()
    const s = readSubj()
    if (subject) {
      const key = subject.toLowerCase().slice(0, 80)
      const rec = s[key] || { label: subject.slice(0, 80), n: 0, last: 0, leaves: [] }
      rec.label = subject.slice(0, 80); rec.n++; rec.last = Date.now()
      s[key] = rec
      window._ttLastSubjKey = key
    }
    leaf = String(leaf || '').trim()
    if (leaf) {
      const key = window._ttLastSubjKey || (subject && subject.toLowerCase().slice(0, 80))
      if (key && s[key]) {
        s[key].leaves = (s[key].leaves || []).filter(l => l !== leaf.slice(0, 60))
        s[key].leaves.push(leaf.slice(0, 60))
        if (s[key].leaves.length > 6) s[key].leaves = s[key].leaves.slice(-6)
      }
    }
    // keep the map to the 40 liveliest subjects (recent + frequent) so it never balloons
    const keys = Object.keys(s)
    if (keys.length > 40) {
      keys.sort((a, b) => (s[b].n + s[b].last / 1e13) - (s[a].n + s[a].last / 1e13))
      const keep = {}; keys.slice(0, 40).forEach(k => keep[k] = s[k]); writeSubj(keep); return
    }
    writeSubj(s)
  }

  // ── a REVISIT is free: flip the clock ourselves, no model call ──
  async function revisit(date) {
    close()
    try { window.toggleCard && window.toggleCard('clock', true) } catch (_) {}
    for (let i = 0; i < 40; i++) {
      const f = document.querySelector('.card[data-card="clock"]:not(.collapsed) iframe')
        || document.querySelector('.card[data-card="clock"] iframe')
      const w = f && f.contentWindow
      if (w && w.TIME_JUMP) { try { await w.TIME_JUMP.jump(date) } catch (_) {} return }
      await new Promise(r => setTimeout(r, 200))
    }
  }

  // ── NOW ⇄ TRIP toggle (Sum 2026-07-21: "toggles between current time and back to last time
  //    travel adventure — click it, it changes the clock"). One button, both directions:
  //    at a trip → home to now; at now with a saved trip → hop back to it. No model call either way. ──
  function clockWin() {
    const f = document.querySelector('.card[data-card="clock"]:not(.collapsed) iframe')
      || document.querySelector('.card[data-card="clock"] iframe')
    return f && f.contentWindow
  }
  const lastTrip = () => { try { return localStorage.getItem('tt-last-trip') || '' } catch (_) { return '' } }
  function atTrip() { try { const w = clockWin(); return w && w._ttDate ? w._ttDate : '' } catch (_) { return '' } }

  async function toggleNowTrip() {
    if (atTrip()) {                                   // currently dressed to a trip → return to the present
      try { window.toggleCard && window.toggleCard('clock', true) } catch (_) {}
      const w = clockWin()
      if (w && w.TIME_JUMP) { try { w.TIME_JUMP.back() } catch (_) {} }
      setTimeout(refreshNowTrip, 400)
      return
    }
    const d = lastTrip()
    if (d) { await revisit(d); setTimeout(refreshNowTrip, 400); return }
  }

  // the button shows where it will TAKE you — and hides entirely when neither direction is live
  // (a fresh user who has never traveled has nothing to toggle to).
  function refreshNowTrip() {
    const b = document.querySelector('.ab-nowtrip'); if (!b) return
    const here = atTrip(), last = lastTrip()
    // icon-only now (no label) — the title carries the direction, and it hides when neither way is live
    if (here) { b.hidden = false; b.title = 'back to now' }
    else if (last) { b.hidden = false; b.title = 'back to your last trip (' + last + ')' }
    else { b.hidden = true }
  }
  window.TT_NOWTRIP_REFRESH = refreshNowTrip

  // ── the overlay shell (one instance; ✕ · backdrop · Esc) ──
  function close() { const o = document.getElementById(OV_ID); if (o) o.remove(); document.removeEventListener('keydown', onEsc) }
  function onEsc(e) { if (e.key === 'Escape') close() }
  function shell(kind, title, sub, hero) {
    close()
    const ov = el('div', 'ttm-ov'); ov.id = OV_ID
    const card = el('div', 'ttm-card ' + kind)
    const head = el('div', 'ttm-head')
    if (hero) { const h = el('img', 'ttm-hero'); h.src = hero; h.alt = ''; head.appendChild(h) }
    const t = el('div', 'ttm-titles'); t.append(el('div', 'ttm-title', title), el('div', 'ttm-sub', sub)); head.appendChild(t)
    const x = el('button', 'ttm-x', '✕'); x.title = 'close'; x.addEventListener('click', close); head.appendChild(x)
    const body = el('div', 'ttm-body')
    card.append(head, body); ov.appendChild(card)
    ov.addEventListener('mousedown', e => { if (e.target === ov) close() })
    document.body.appendChild(ov); document.addEventListener('keydown', onEsc)
    return body
  }

  // ── TIME MAP ──
  function openTime() {
    const trips = readTrips()
    const dates = Object.keys(trips).sort((a, b) => (yearOf(a) - yearOf(b)) || (a < b ? -1 : 1))
    const past = dates.filter(d => !trips[d].future)
    const future = dates.filter(d => trips[d].future)
    const ordered = past.concat(future)
    const body = shell('time', 'the time map', ordered.length ? `${ordered.length} journey${ordered.length === 1 ? '' : 's'} on file` : 'no jumps yet', 'agents/timetravel/map-gen.png')
    if (!ordered.length) {
      body.appendChild(el('div', 'ttm-empty', 'the map is blank parchment.\nask the traveler to take you somewhere — a date, an era, a moment — and this fills with every place you go.'))
      return
    }
    const wrap = el('div', 'ttm-time')
    wrap.setAttribute('role', 'list')            // ADA — the journey timeline is a list of stops (Sum 2026-07-23)
    wrap.setAttribute('aria-label', ordered.length + ' journeys on the time map, oldest to newest')
    let prevYear = null, side = 0, lastEra = ''
    ordered.forEach((d, i) => {
      const m = trips[d]
      const y = yearOf(d)
      const stop = el('div', 'ttm-stop ' + (side ? 'right' : 'left') + (m.future ? ' future' : ''))
      stop.setAttribute('role', 'listitem')
      stop.setAttribute('aria-label', String(d).slice(0, 4) + (m.future ? ' — a journey not yet taken' : ' — a journey on file'))
      // gap ∝ years since the last stop (a long jump reads as a long scroll) — √-scaled + capped
      if (prevYear != null) {
        const delta = Math.abs(y - prevYear)
        stop.style.marginTop = Math.round(46 + Math.min(300, Math.sqrt(delta) * 24)) + 'px'
      } else stop.style.marginTop = '4px'
      prevYear = y
      // era header (century) when it turns — a light landmark, not a wall
      const era = m.future ? 'the future' : (String(d).slice(0, 2) + '00s')
      if (era !== lastEra) { lastEra = era; const e = el('div', 'ttm-era', era); wrap.appendChild(e) }
      stop.appendChild(el('div', 'ttm-node'))
      const box = el('div', 'ttm-card-box')
      const yr = el('div', 'ttm-year', String(d).slice(0, 4)); if (m.future) yr.appendChild(el('span', 'ttm-fut-tag', '  ✷ not yet')); box.appendChild(yr)
      // the concept — first scene caption, else the story's opening line
      const sc = (m.scenes || [])
      let concept = (sc[0] && sc[0].caption) || ''
      if (!concept && m.log && m.log.length) concept = m.log[m.log.length - 1].text.split(/[.!?\n]/)[0].slice(0, 90)
      if (concept) box.appendChild(el('div', 'ttm-concept', concept))
      // thumbnails (filled async from TT_STORE) — placeholders keep layout stable
      const thumbs = el('div', 'ttm-thumbs'); box.appendChild(thumbs)
      fillThumbs(thumbs, d, sc.length)
      // the story that came home with the trip
      if (m.log && m.log.length) {
        const full = m.log.map(l => l.text).join('\n\n')
        const story = el('div', 'ttm-story', full)
        box.appendChild(story)
        if (full.length > 220) {
          const more = el('span', 'ttm-more', 'read on ▾')
          more.setAttribute('role', 'button'); more.setAttribute('tabindex', '0'); more.setAttribute('aria-expanded', 'false')
          const toggleStory = () => { const open = story.classList.toggle('open'); more.textContent = open ? 'less ▴' : 'read on ▾'; more.setAttribute('aria-expanded', open ? 'true' : 'false') }
          more.addEventListener('click', toggleStory)
          more.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleStory() } })
          box.appendChild(more)
        }
      }
      const bits = []
      if ((m.papers || []).length) bits.push(`${m.papers.length} front page${m.papers.length === 1 ? '' : 's'}`)
      if ((m.events || []).length) bits.push(`${m.events.length} events`)
      if (m.weather) bits.push('weather on file')
      if (bits.length) box.appendChild(el('div', 'ttm-bits', bits.join('  ·  ')))
      const rev = el('button', 'ttm-revisit', '↻ travel here again')
      rev.addEventListener('click', () => revisit(d))
      box.appendChild(rev)
      stop.appendChild(box)
      wrap.appendChild(stop)
      side ^= 1
    })
    body.appendChild(wrap)
  }

  async function fillThumbs(host, date, sceneCount) {
    let recs = []
    try { recs = (window.TT_STORE && await window.TT_STORE.list(date)) || [] } catch (_) {}
    host.textContent = ''
    if (!recs.length) {
      // no painted frames — a single quiet placeholder so the row still reads
      const ph = el('div', 'ttm-thumb empty', '🖼'); host.appendChild(ph); return
    }
    recs.slice(0, 4).forEach(r => {
      const img = el('img', 'ttm-thumb'); img.src = r.thumb || r.full; img.alt = r.caption || ''
      img.title = (r.caption || 'a painted moment') + ' — click to travel here again'
      img.addEventListener('click', () => revisit(date))
      host.appendChild(img)
    })
  }

  // ── WHERE YOUR INTERESTS COME FROM (Sum 2026-07-21: "I want the interests from clock — fox or
  // bbc or blue or hope") ─────────────────────────────────────────────────────────────────────
  // The map is not a separate profile you have to fill in. Your clock already IS the profile:
  // the packs and feeds on your headline bars, and the hand-rolled lanes you left switched on.
  // Plus what you have actually asked the traveler about (tt_subjects).
  //
  // The clock PUBLISHES its taxonomy to clock-taxonomy (see lb-headlines.js). We read that
  // snapshot rather than restating the pack list here — one source of truth, no drift.
  const readTax = () => { try { return JSON.parse(localStorage.getItem('clock-taxonomy') || '{}') } catch (_) { return {} } }
  const readHL  = () => { try { return JSON.parse(localStorage.getItem('clock-headlines') || '{}') } catch (_) { return {} } }

  // branches for the hand-rolled lanes (Sum: "koans, with branches of which philo, authors,
  // spirituality"). These are SEEDS — the traveler grows real ones as you explore, and anything
  // you have actually asked about is merged in below as a live leaf.
  const LANE_BRANCH = {
    koans:       ['zen', 'taoism', 'the teachers', 'paradox'],
    quotes:      ['the authors', 'stoics', 'poets'],
    manifest:    ['the wei', 'practice', 'the writings'],
    meditations: ['breath', 'the body', 'stillness'],
    bible:       ['the prophets', 'the letters', 'the psalms'],
    devil:       ['satire', 'Bierce', 'definitions'],
    poetry:      ['the poets', 'forms', 'the moderns'],
    history:     ['the archive', 'this day', 'the papers'],
    facts:       ['science', 'the odd', 'the useful'],
  }

  // one node = { id, label, kind, n, branches[] }.  kind drives the colour.
  function interests() {
    const tax = readTax(), hl = readHL(), subj = readSubj()
    const packs = tax.packs || {}, feedName = tax.feeds || {}, laneName = tax.lanes || {}
    const out = new Map()
    const add = (id, label, kind, branches) => {
      const cur = out.get(id)
      if (cur) { cur.n++; return cur }
      const node = { id, label: label || id, kind, n: 1, branches: (branches || []).slice(0, 5) }
      out.set(id, node); return node
    }
    // — the headline bars: every pack / feed / lane you chose —
    ;(hl.bars || []).forEach(b => (b.feeds || []).forEach(f => {
      if (packs[f])          add(f, f, 'pack', packs[f].map(x => feedName[x] || x))   // blue → Guardian, NPR, NYT
      else if (feedName[f])  add(f, feedName[f], 'feed')                              // fox, bbc
      else                   add(f, laneName[f] || f, 'lane', LANE_BRANCH[f])         // koans → zen, taoism…
    }))
    // — what you have actually asked the traveler about (these carry real leaves) —
    Object.values(subj).forEach(rec => {
      const node = add('subj:' + String(rec.label).toLowerCase(), rec.label, 'asked', rec.leaves || [])
      node.n = Math.max(node.n, rec.n || 1)
      if (rec.leaves && rec.leaves.length) node.branches = rec.leaves.slice(-4)
    })
    return Array.from(out.values()).sort((a, b) => b.n - a.n)
  }

  // ── SEARCH MAP — the vector web (SVG) ──
  const SVGNS = 'http://www.w3.org/2000/svg'
  const svg = (tag, attrs) => { const n = document.createElementNS(SVGNS, tag); for (const k in attrs) n.setAttribute(k, attrs[k]); return n }
  const clip = (s, n) => { s = String(s || ''); return s.length > n ? s.slice(0, n - 1) + '…' : s }

  function openSearch() {
    const nodes = interests()
    const body = shell('search', 'the search map', nodes.length ? `${nodes.length} interest${nodes.length === 1 ? '' : 's'} · drag to pan · scroll to zoom` : 'nothing charted yet', 'agents/timetravel/globe-gen.png')
    if (!nodes.length) {
      body.appendChild(el('div', 'ttm-empty', 'your web of interests is empty.\nturn on a few feeds or lanes in the clock, or ask the traveler about anything — this map is drawn from what you actually read.'))
      return
    }
    const show = nodes.slice(0, 14)
    const W = 1100, H = 820, cx = W / 2, cy = H / 2
    const root = svg('svg', { class: 'ttm-svg', viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': `search map — your web of ${nodes.length} interest${nodes.length === 1 ? '' : 's'}, drawn from what you read` })
    root.appendChild(svg('title', {})).textContent = 'The search map — a branching web of your curiosities'
    const cam = svg('g', { class: 'ttm-cam' })              // ← everything pans/zooms inside this
    root.appendChild(cam)
    const edges = svg('g', {}), leafG = svg('g', {}), nodeG = svg('g', {})
    cam.append(edges, leafG, nodeG)
    const maxN = Math.max.apply(null, show.map(k => k.n))

    show.forEach((rec, i) => {
      const ang = (i / show.length) * Math.PI * 2 - Math.PI / 2
      // size FIRST, then push the ring out by it — a node's radius has to be part of its distance
      // from the hub or the biggest two (which sort adjacent) overlap each other.
      const r = Math.max(30, Math.min(62, 26 + Math.sqrt(rec.n / maxN) * 36))
      const rad = 235 + r + ((i * 53) % 60) - 30       // gentle stagger so it reads organic, not clock-perfect
      const x = cx + Math.cos(ang) * rad, y = cy + Math.sin(ang) * rad
      edges.appendChild(svg('line', { class: 'edge', x1: cx, y1: cy, x2: x, y2: y }))
      // the branches — what sits under this interest
      const br = (rec.branches || []).slice(0, 4)
      br.forEach((lf, j) => {
        const la = ang + (j - (br.length - 1) / 2) * 0.30
        const lr = rad + r + 78
        const lx = cx + Math.cos(la) * lr, ly = cy + Math.sin(la) * lr
        edges.appendChild(svg('line', { class: 'edge leaf', x1: x, y1: y, x2: lx, y2: ly }))
        const lg = svg('g', { class: 'leaf-node' })
        lg.appendChild(svg('circle', { cx: lx, cy: ly, r: 7 }))
        const lt = svg('text', { x: lx, y: ly + (Math.sin(la) < 0 ? -14 : 22), 'font-size': 17 })
        lt.textContent = clip(lf, 22)
        lg.append(lt)
        lg.addEventListener('click', ev => { ev.stopPropagation(); explore(lf, rec.label) })
        leafG.appendChild(lg)
      })
      const g = svg('g', { class: 'subj kind-' + rec.kind })
      g.appendChild(svg('circle', { cx: x, cy: y, r }))
      const t = svg('text', { x, y: y + 6, 'font-size': Math.max(18, Math.min(24, r / 2.4)) })
      t.textContent = clip(rec.label, r > 46 ? 14 : 11)
      g.append(t)
      g.addEventListener('click', () => explore(rec.label))
      nodeG.appendChild(g)
    })
    // the hub — you
    const hub = svg('g', { class: 'hub' })
    hub.appendChild(svg('circle', { cx, cy, r: 52 }))
    const ht = svg('text', { x: cx, y: cy + 8, 'font-size': 24 }); ht.textContent = 'you'
    hub.append(ht); nodeG.appendChild(hub)
    body.appendChild(root)
    wireCamera(root, cam, W, H)

    const hint = el('div', 'ttm-empty')
    hint.style.padding = '10px 0 2px'
    hint.textContent = 'click any node — the map closes and the traveler picks that thread up.'
    body.appendChild(hint)
  }

  // ── ZOOM + PAN (Sum 2026-07-21: "I think we need a zoom in and out and pan feature") ──
  // One transform on a camera <g>. Zoom is anchored at the POINTER, not the centre — zooming to
  // the middle when you are reading an edge node is the thing that makes web maps feel broken.
  function wireCamera(root, cam, W, H) {
    let k = 1, tx = 0, ty = 0, drag = null
    const MIN = 0.4, MAX = 4
    const apply = () => cam.setAttribute('transform', `translate(${tx} ${ty}) scale(${k})`)
    // viewBox units per client px — the map is scaled to fit, so a raw pixel delta would drift
    const unit = () => W / (root.getBoundingClientRect().width || W)
    root.addEventListener('wheel', e => {
      e.preventDefault()
      const r = root.getBoundingClientRect()
      const px = (e.clientX - r.left) * unit(), py = (e.clientY - r.top) * (H / (r.height || H))
      const nk = Math.min(MAX, Math.max(MIN, k * (e.deltaY < 0 ? 1.12 : 1 / 1.12)))
      // keep the point under the cursor fixed while k changes
      tx = px - (px - tx) * (nk / k); ty = py - (py - ty) * (nk / k)
      k = nk; apply()
    }, { passive: false })
    root.addEventListener('mousedown', e => {
      if (e.target.closest('.subj, .leaf-node, .hub')) return     // a click on a node is not a drag
      drag = { x: e.clientX, y: e.clientY, tx, ty }; root.classList.add('grabbing')
    })
    window.addEventListener('mousemove', e => {
      if (!drag) return
      tx = drag.tx + (e.clientX - drag.x) * unit()
      ty = drag.ty + (e.clientY - drag.y) * unit()
      apply()
    })
    window.addEventListener('mouseup', () => { drag = null; root.classList.remove('grabbing') })
    // an explicit control too — a trackpad is not the only way in, and neither is a mouse wheel
    const bar = el('div', 'ttm-zoom')
    const btn = (txt, fn, label) => { const b = el('button', 'ttm-zbtn', txt); b.title = label; b.addEventListener('click', fn); return b }
    const zoomTo = f => { const nk = Math.min(MAX, Math.max(MIN, k * f)); tx = W/2 - (W/2 - tx) * (nk/k); ty = H/2 - (H/2 - ty) * (nk/k); k = nk; apply() }
    bar.append(btn('−', () => zoomTo(1 / 1.25), 'zoom out'),
               btn('reset', () => { k = 1; tx = 0; ty = 0; apply() }, 'fit the whole map'),
               btn('+', () => zoomTo(1.25), 'zoom in'))
    root.parentNode.insertBefore(bar, root.nextSibling)
  }

  // Sum: "click on something, card closes and traveler knows what you want to talk about."
  // under: the parent interest, when you clicked a branch — "zen" alone is thin, "zen, under
  // koans" tells the traveler which shelf you were standing at.
  function explore(label, under) {
    close()
    window.TT_CURSUBJ = label
    try { window.TT_LOGSUBJECT(label) } catch (_) {}
    // ⚠️ never say "my map" here — the traveler owns a *time* map (its trip shelf) and will check THAT,
    // find nothing, and refuse (the GoodNews-under-hope bug, 2026-07-21). This is the USER's interest
    // web; frame it as one of THEIR feeds/curiosities and ask the traveler to actually engage it.
    const where = under ? ` — it's one of my interests, sitting under "${under}"` : ''
    const q = `Let's get into ${label}${where}. Tell me something worth knowing, or take me somewhere `
      + `if it wants a trip. If one of my feeds or cards already touches it, point me there first.`
    if (window.ozAskBot) window.ozAskBot('timetravel', q)
  }

  window.OZ_MAPS = { time: openTime, search: openSearch, close }

  // the head buttons live on a DRAGGABLE bar — swallow mousedown so a click doesn't start a drag,
  // and route the click here (delegation keeps workspace.js's edit to just adding the buttons).
  document.addEventListener('mousedown', e => { if (e.target.closest('.ab-map, .ab-glob, .ab-nowtrip')) e.stopPropagation() }, true)
  document.addEventListener('click', e => {
    if (e.target.closest('.ab-map')) { e.stopPropagation(); openTime() }
    else if (e.target.closest('.ab-glob')) { e.stopPropagation(); openSearch() }
    else if (e.target.closest('.ab-nowtrip')) { e.stopPropagation(); toggleNowTrip() }
  })
  // keep the toggle's label honest: whenever a saved trip appears, or the traveler bar comes back
  // into view, re-read where the clock is. cheap, and it means the button is right when you look.
  window.addEventListener('storage', e => { if (e && e.key === 'tt-last-trip') refreshNowTrip() })
  document.addEventListener('visibilitychange', () => { if (!document.hidden) refreshNowTrip() })
  setTimeout(refreshNowTrip, 1500)   // one delayed read once the clock iframe has had time to load
})()
