// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   THE HIGHLIGHTER (Sum 2026-07-13): its OWN ... search: "THE HIGHLIGHTER (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for Monaco's find/replace panel UI and
//    **search logic. It exports no named functions but wires up the global `openFind()`,
//    **`closeFind()`, `toggleFind()` entry points and manages the persistent state `lastQ` and
//    **`lastR` (line 13) that survive between panel opens.
//
//    **TOUCH HERE**
//    - Change the scope options (tab / tabs / sandbox) → edit `SCOPE_ICO` object (line 19) and the
//    - menu buttons in `findPanelHTML()` (lines 51–53), then update `scopeSources()` (line 206) to
//    - handle the new scope
//    - Change find flags (case, word, regex, preserve, insel) → `findFlags` object (line 11) and
//    - the flag buttons in `findPanelHTML()` (lines 57–61), then wire the handler in `wireFind()`
//    - (line 104)
//    - Change what happens when you hit Enter in the find box → `wireFind()` keydown handler (line
//    - 84)
//    - Change what happens when you hit Enter in the replace box → `wireFind()` keydown handler
//    - (line 88)
//    - Change the regex escape logic or word-boundary behavior → `buildRe()` (line 164) and
//    - `WORD_SEP` (line 9)
//    - Change how matches are highlighted in the editor → `paintHits()` (line 213)
//    - Change the case-preservation logic on replace → `applyCase()` (line 237)
//    - Change multi-cursor behavior → `multiCursor()` (line 245)
//    - Change how "replace all" works across files → `replaceAll()` (line 264), especially the
//    - `scopeSources()` loop (line 282)
//
//    **TRAPS**
//    - `lastQ` and `lastR` (line 13) are persisted between opens; renaming them breaks user data
//    - recovery. They are read in `openFind()` (lines 138–139) and written in `closeFind()` (lines
//    - 144–145).
//    - `findSelRange` (line 12) must be cleared when the find panel closes (line 146) or the ⧉
//    - button will hold a stale selection range.
//    - `findFlags.insel` is tied to a live editor selection; it is forcibly disabled in
//    - `closeFind()` (line 146) and when no text is highlighted (line 110). Changing this timing
//    - breaks the highlight-to-search workflow.
//    - `findMatches` and `findIdx` (line 12) are the source of truth for which match is "current";
//    - they must be kept in sync across `runFind()`, `stepFind()`, `paintHits()`, and
//    - `revealMatch()`. A mismatch silently breaks navigation.
//    - `WORD_SEP` (line 9) is Monaco's default; changing it affects both in-tab search (line 184)
//    - and cross-file search (line 167). Both must use the same separators or behavior diverges.
//    - The scope dropdown menu (lines 93–102) must close when you click outside it (line 103) or it
//    - will stay open and block the find input.
//    - `replaceAll()` (line 264) has two paths: tab-only (line 267) and cross-file (line 278). They
//    - use different APIs (`model.findMatches()` vs. `buildRe()`) and must both be updated if you
//    - change the search logic.
//    - `flushActiveToSandbox()` (line 196, 280) is called before cross-file operations but is
//    - defined elsewhere; if it is removed or renamed, cross-file replace will silently fail to
//    - persist changes.
//
//    **DO NOT**
//    - Do not move `wireFind()` (line 77) or change when it is called; it is idempotent (line 78)
//    - and must run exactly once per card.
//    - Do not rename `findEl()` (line 14); it is a shorthand used throughout and renaming it
//    - requires updating 20+ call sites.
//    - Do not change the HTML structure of `findPanelHTML()` (line 44) without updating the
//    - selectors in `wireFind()` (lines 81, 93, 104, 114–117) and `openFind()` (lines 132–134).
//    - Do not add new global state without clearing it in `closeFind()` (line 142) or it will leak
//    - between opens.
//    - Do not change how `editor.getModel()` or `editor.getSelection()` are called; these are
//    - Monaco API calls and will fail silently if the editor is not ready.
//    - Do not move the highlighter button logic (`hlBtnHTML()`, `syncHighlighters()`, lines 30–42)
//    - into this file; it belongs in the teach/squiggy card files that own those buttons.
//    - Do not add cross-file search features here; they belong in a separate indexing/search module
//    - if the codebase grows.
//
//
//
//    ---
//
// END IC SHIP PASS

  // ══════════════════════════════════════════════════════════════════════════
  //  FIND · REPLACE — the readable rebuild (Sum 2026-07-11). Monaco's native widget
  //  is unreadable even at max zoom AND can't reach past the current file. So we drive
  //  Monaco's find API from our OWN panel: full-size text (--fs-ui), and a SCOPE selector
  //  the native widget can't do — this tab · all tabs · whole sandbox.
  //  Banked behaviour: no X — the FIND button toggles it · click-outside closes ·
  //  the find + replace text PERSIST between opens (lastQ / lastR).
  // ══════════════════════════════════════════════════════════════════════════
  const WORD_SEP = '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?'   // Monaco's default whole-word separators
  let findScope = 'tab'                                 // tab · tabs · sandbox
  const findFlags = { case: false, word: false, rx: false, preserve: false, insel: false }
  let findMatches = [], findIdx = -1, findDecos = [], findSelRange = null
  let lastQ = '', lastR = ''                            // persist between opens (Sum)
  const findEl = sel => card && card.querySelector(sel)
  const cmpPos = (a, b) => a.lineNumber !== b.lineNumber ? a.lineNumber - b.lineNumber : a.column - b.column
  // (Sum 2026-07-11) the scope icons ARE tiny versions of the app's own tab language:
  //   tab  = the red/white racing-curb border (the active file tab) · tabs = gray/yellow overlapping chips
  //   (the overflow dock) · sandbox = the sandbox.png we already made. recognise-by-shape, not new glyphs.
  const SCOPE_ICO = {
    section: '<img class="sc-ico sc-img" src="cards/monaco/assets/find-highlighter.png" alt="">',   // 🖊 just the highlighted block
    tab:     '<span class="sc-ico sc-tab"></span>',
    tabs:    '<span class="sc-ico sc-tabs"><i></i><i></i><i></i></span>',
    sandbox: '<img class="sc-ico sc-img" src="cards/monaco/assets/sandbox.png" alt="">',
  }
  // ── THE HIGHLIGHTER (Sum 2026-07-13): its OWN toggle on Squiggy · teach · fix. ON = target the HIGHLIGHTED section;
  //    the scope buttons (tab · tabs · app) then set the LAYERS OF BACKGROUND context around it. OFF = the whole scope. ──
  const HL_ICO = '<img class="sc-ico sc-img" src="cards/monaco/assets/find-highlighter.png" alt="">'
  const mcSelText = () => { try { const s = editor && editor.getSelection(); return s && !s.isEmpty() ? editor.getModel().getValueInRange(s) : '' } catch (_) { return '' } }
  const mcHasSel  = () => !!mcSelText()
  function hlBtnHTML(on, attr) {   // the shared highlighter button — lit when on, dim + disabled with no selection
    const has = mcHasSel()
    return `<button class="mc-hl-btn${on && has ? ' on' : ''}${has ? '' : ' dim'}" ${attr}="1" title="${has ? (on ? 'highlighter ON — working on just your highlighted section (scope buttons = its background)' : 'highlighter — work on ONLY the highlighted section') : 'highlight some code first, then tap to focus on just that section'}">${HL_ICO}</button>`
  }
  // (Sum 2026-07-13) keep every highlighter button live with the selection — un-dim the instant you highlight, drop the focus if you deselect
  let _lastHasSel = null
  function syncHighlighters() {
    const has = mcHasSel()
    if (has === _lastHasSel) return   // no flip → skip the DOM work (a drag-select fires this on every change — don't churn)
    _lastHasSel = has
    if (!has) { _sqHL = false; _fixHL = false; _toolState.teach.hl = false }
    if (card) card.querySelectorAll('.mc-hl-btn').forEach(b => { b.classList.toggle('dim', !has); if (!has) b.classList.remove('on') })
  }

  function findPanelHTML() {
    return `<div class="mc-find" hidden>
      <div class="mc-find-rows">
        <div class="mc-find-row">
          <div class="mc-scope-dd">
            <button class="mc-scope-cur" title="search scope — this tab · all tabs · whole sandbox"><span class="mc-scope-cur-ico">${SCOPE_ICO.tab}</span><span class="mc-scope-caret">▾</span></button>
            <div class="mc-scope-menu">
              <button class="mc-scope-opt on" data-scope="tab">${SCOPE_ICO.tab}<span class="sc-lbl">This tab</span></button>
              <button class="mc-scope-opt"    data-scope="tabs">${SCOPE_ICO.tabs}<span class="sc-lbl">All tabs</span></button>
              <button class="mc-scope-opt"    data-scope="sandbox">${SCOPE_ICO.sandbox}<span class="sc-lbl">Sandbox</span></button>
            </div>
          </div>
          <input class="mc-find-q" placeholder="Find" spellcheck="false" autocomplete="off">
          <button class="mc-find-flag" data-flag="case"     title="Match case">Aa</button>
          <button class="mc-find-flag" data-flag="word"     title="Whole word">W</button>
          <button class="mc-find-flag" data-flag="rx"       title="Regular expression — $1 $2 groups work in Replace">.*</button>
          <button class="mc-find-flag" data-flag="preserve" title="Preserve case on replace (FOO→BAR · Foo→Bar · foo→bar)">Ab</button>
          <button class="mc-find-flag" data-flag="insel"    title="Find in selection — highlight a block first, then this">⧉</button>
          <span class="mc-find-count">No results</span>
          <button class="mc-find-step" data-step="-1" title="Previous match (⇧⏎)">↑</button>
          <button class="mc-find-step" data-step="1"  title="Next match (⏎)">↓</button>
        </div>
        <div class="mc-find-row">
          <span class="mc-scope-spacer"></span>
          <input class="mc-find-r" placeholder="Replace" spellcheck="false" autocomplete="off">
          <button class="mc-find-go mc-find-ico" data-go="one"     title="Replace this match (⏎) — swap one tire"><img src="cards/monaco/assets/find-replace-one.png" alt="replace"></button>
          <button class="mc-find-go mc-find-ico" data-go="all"     title="Replace all in scope — the whole tire stack"><img src="cards/monaco/assets/find-replace-all.png" alt="replace all"></button>
          <button class="mc-find-go mc-find-ico mc-find-cursors" data-go="cursors" title="Multi-cursor — a live caret on every match (the start-line lights), type once to edit them all"><img src="cards/monaco/assets/find-multicursor.png" alt="multi-cursor"></button>
        </div>
      </div>
    </div>`
  }

  function wireFind() {
    if (!card || card.querySelector('.mc-find')) return          // once
    const bw = card.querySelector('.mc-body-wrap'), nb = card.querySelector('.mc-namebar'); if (!bw || !nb) return   // (Sum 2026-07-14) find toggles in the space ABOVE the file name (was an editor overlay)
    bw.insertBefore(node(findPanelHTML()), nb)
    const panel = findEl('.mc-find'), q = findEl('.mc-find-q'), r = findEl('.mc-find-r')
    panel.addEventListener('mousedown', e => e.stopPropagation())   // clicks inside never start a card-drag
    q.addEventListener('input', runFind)
    q.addEventListener('keydown', e => {
      if (e.key === 'Enter') { e.preventDefault(); stepFind(e.shiftKey ? -1 : 1) }
      else if (e.key === 'Escape') { e.preventDefault(); closeFind() }
    })
    r.addEventListener('keydown', e => {
      if (e.key === 'Enter') { e.preventDefault(); replaceOne() }
      else if (e.key === 'Escape') { e.preventDefault(); closeFind() }
    })
    // the SCOPE dropdown — a compact picker in front of the find box (Sum: "one less line")
    const dd = panel.querySelector('.mc-scope-dd'), ddBtn = dd.querySelector('.mc-scope-cur'), ddMenu = dd.querySelector('.mc-scope-menu')
    ddBtn.addEventListener('click', e => { e.stopPropagation(); ddMenu.classList.toggle('open') })
    ddMenu.addEventListener('click', e => {
      e.stopPropagation()
      const b = e.target.closest('[data-scope]'); if (!b) return
      findScope = b.dataset.scope
      ddMenu.querySelectorAll('.mc-scope-opt').forEach(x => x.classList.toggle('on', x === b))
      dd.querySelector('.mc-scope-cur-ico').innerHTML = SCOPE_ICO[findScope]
      ddMenu.classList.remove('open'); runFind()
    })
    panel.addEventListener('click', e => { if (!e.target.closest('.mc-scope-dd')) ddMenu.classList.remove('open') })
    panel.querySelectorAll('.mc-find-flag').forEach(b => b.addEventListener('click', () => {
      const f = b.dataset.flag
      findFlags[f] = !findFlags[f]
      if (f === 'insel') {                                   // capture the highlighted range to search within
        const sel = editor && editor.getSelection()
        findSelRange = (findFlags.insel && sel && !sel.isEmpty()) ? sel : null
        if (findFlags.insel && !findSelRange) findFlags.insel = false   // nothing highlighted → no-op, don't light
      }
      b.classList.toggle('on', findFlags[f]); runFind()
    }))
    panel.querySelectorAll('.mc-find-step').forEach(b => b.addEventListener('click', () => stepFind(+b.dataset.step)))
    panel.querySelector('[data-go="one"]').addEventListener('click', replaceOne)
    panel.querySelector('[data-go="all"]').addEventListener('click', replaceAll)
    panel.querySelector('[data-go="cursors"]').addEventListener('click', multiCursor)
    // click OUTSIDE closes (Sum: "no x out, click outside to close") — but stay open while you work in
    // the code (editor host) or reach for the toolbox (the pit owns the find toggle).
    document.addEventListener('mousedown', e => {
      const p = findEl('.mc-find'); if (!p || p.hidden) return
      if (p.contains(e.target)) return
      if (host.contains(e.target)) return
      if (e.target.closest && e.target.closest('.mc-pit')) return
      closeFind()
    })
  }

  function openFind() {
    wireFind(); const panel = findEl('.mc-find'); if (!panel) return
    panel.hidden = false
    const slot = findEl('.mc-scope-cur-ico'); if (slot) slot.innerHTML = SCOPE_ICO[findScope]   // reflect the persisted scope
    panel.querySelectorAll('.mc-scope-opt').forEach(x => x.classList.toggle('on', x.dataset.scope === findScope))
    const q = findEl('.mc-find-q'), r = findEl('.mc-find-r')
    const sel = editor && editor.getSelection()
    const selText = sel && !sel.isEmpty() ? editor.getModel().getValueInRange(sel) : ''
    if (selText && !/\n/.test(selText) && selText.length <= 200) q.value = selText   // seed from selection (native-like)
    else q.value = lastQ
    r.value = lastR
    q.focus(); q.select(); runFind()
  }
  function closeFind() {
    const panel = findEl('.mc-find'); if (!panel || panel.hidden) return
    lastQ = (findEl('.mc-find-q') || {}).value || ''
    lastR = (findEl('.mc-find-r') || {}).value || ''
    findFlags.insel = false; findSelRange = null                          // ⧉ is tied to a live highlight — don't persist a stale range
    const ib = findEl('.mc-find-flag[data-flag="insel"]'); if (ib) ib.classList.remove('on')
    clearFindDecos(); panel.hidden = true
    if (editor) editor.focus()
  }
  function toggleFind() { const panel = findEl('.mc-find'); (!panel || panel.hidden) ? openFind() : closeFind() }
  // (Sum 2026-07-14) GO-TO-LINE lives PERMANENTLY in the name bar (no toggle, no garage). ⌃G just focuses it.
  function gotoJump() { const g = card && card.querySelector('.mc-goto-in'); const n = g && parseInt(g.value, 10); if (n > 0 && editor) { editor.revealLineInCenter(n); editor.setPosition({ lineNumber: n, column: 1 }); editor.focus() } }
  function focusGoto() { const g = card && card.querySelector('.mc-goto-in'); if (g) { g.focus(); g.select() } }
  function wireNamebarGoto() {
    const g = card && card.querySelector('.mc-namebar-goto'); if (!g) return
    g.addEventListener('mousedown', e => e.stopPropagation())
    g.querySelector('.mc-goto-go').addEventListener('click', gotoJump)
    g.querySelector('.mc-goto-in').addEventListener('keydown', e => { if (e.key === 'Enter') { e.preventDefault(); gotoJump() } else if (e.key === 'Escape') { e.preventDefault(); if (editor) editor.focus() } })
  }
  function clearFindDecos() { if (editor && findDecos.length) editor.deltaDecorations(findDecos, []); findDecos = []; findMatches = []; findIdx = -1 }

  // a JS RegExp for the cross-file string scans (in-tab uses Monaco's own findMatches)
  function buildRe(qstr) {
    if (!qstr) return null
    let src = findFlags.rx ? qstr : qstr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    if (findFlags.word) src = `\\b(?:${src})\\b`
    try { return new RegExp(src, findFlags.case ? 'g' : 'gi') } catch (_) { return null }
  }
  const isTextFile = f => f && typeof f.data === 'string' && f.kind !== 'url' && f.kind !== 'path'

  function runFind() {
    clearFindDecos()
    const countEl = findEl('.mc-find-count'), qstr = (findEl('.mc-find-q') || {}).value || ''
    if (countEl) countEl.textContent = 'No results'
    if (!qstr || !editor) return
    if (findScope === 'tab') runFindTab(qstr, countEl)
    else runFindCross(qstr, countEl)
  }
  function runFindTab(qstr, countEl) {
    const model = editor.getModel(); if (!model) return
    const scope = (findFlags.insel && findSelRange) ? findSelRange : false   // ⧉ find-in-selection restricts to the highlighted range
    let ms
    try { ms = model.findMatches(qstr, scope, findFlags.rx, findFlags.case, findFlags.word ? WORD_SEP : null, false) }
    catch (_) { if (countEl) countEl.textContent = 'bad pattern'; return }
    findMatches = ms.map(m => m.range)
    if (!findMatches.length) { if (countEl) countEl.textContent = 'No results'; return }
    const pos = editor.getPosition()
    findIdx = findMatches.findIndex(rng => cmpPos(rng.getStartPosition(), pos) >= 0)
    if (findIdx < 0) findIdx = 0
    paintHits(); revealMatch(); paintCount(countEl)
  }
  // tabs / sandbox: COUNT across every source (so the scope tabs read real) + light the OPEN file's hits.
  function runFindCross(qstr, countEl) {
    const re = buildRe(qstr); if (!re) { if (countEl) countEl.textContent = 'bad pattern'; return }
    if (editor) flushActiveToSandbox()
    window.SANDBOX = window.SANDBOX || {}
    let hits = 0, files = 0
    scopeSources().forEach(({ text }) => { re.lastIndex = 0; const n = (text.match(re) || []).length; if (n) { files++; hits += n } })
    // still light the current file's matches so there's something to see
    const model = editor.getModel()
    if (model) { try { findMatches = model.findMatches(qstr, false, findFlags.rx, findFlags.case, findFlags.word ? WORD_SEP : null, false).map(m => m.range); if (findMatches.length) { findIdx = 0; paintHits(); revealMatch() } } catch (_) {} }
    if (countEl) countEl.textContent = hits ? `${hits} in ${files} file${files === 1 ? '' : 's'}` : 'No results'
  }
  // every text source in the current scope: { name, text, tab }
  function scopeSources() {
    const out = []
    if (findScope === 'tabs') tabs.forEach(t => out.push({ name: t.filename, text: t.content || '', tab: t }))
    else Object.keys(window.SANDBOX || {}).forEach(n => { const f = window.SANDBOX[n]; if (isTextFile(f)) out.push({ name: n, text: f.data, tab: tabs.find(x => x.filename === n) || null }) })
    return out
  }

  function paintHits() {
    if (!editor) return
    findDecos = editor.deltaDecorations(findDecos, findMatches.map((r, i) => ({ range: r, options: { className: i === findIdx ? 'mc-find-hit cur' : 'mc-find-hit' } })))
  }
  function revealMatch() {
    if (findIdx < 0 || !findMatches[findIdx] || !editor) return
    const rng = findMatches[findIdx]
    editor.setSelection(rng); editor.revealRangeInCenterIfOutsideViewport(rng)
  }
  function paintCount(el) { if (el) el.textContent = findMatches.length ? `${findIdx + 1} of ${findMatches.length}` : 'No results' }
  function stepFind(dir) {
    if (findScope !== 'tab') return                       // cross-file has no single cursor (yet — brainstorm)
    if (!findMatches.length) { runFind(); if (!findMatches.length) return }
    findIdx = (findIdx + dir + findMatches.length) % findMatches.length
    paintHits(); revealMatch(); paintCount(findEl('.mc-find-count'))
  }

  // build the replacement for one hit: expand regex $1/$2/$& groups (rx on) + preserve the hit's case (Ab on)
  function replFor(matched, groups, rep) {
    let out = rep
    if (findFlags.rx && groups) out = rep.replace(/\$(\d+|&)/g, (_, k) => k === '&' ? (groups[0] || '') : (groups[+k] || ''))
    if (findFlags.preserve && matched) out = applyCase(matched, out)
    return out
  }
  function applyCase(src, rep) {
    const letters = src.replace(/[^A-Za-z]/g, ''); if (!letters) return rep
    if (letters === letters.toUpperCase()) return rep.toUpperCase()                                  // FOO → BAR
    if (src[0] === src[0].toUpperCase() && src.slice(1) === src.slice(1).toLowerCase()) return rep.charAt(0).toUpperCase() + rep.slice(1).toLowerCase()   // Foo → Bar
    if (letters === letters.toLowerCase()) return rep.toLowerCase()                                   // foo → bar
    return rep
  }
  // ❙❙❙ MULTI-CURSOR — turn every match into a live caret; type once, edit them all (Sum: "find-replace IS multi-cursor")
  function multiCursor() {
    if (findScope !== 'tab' || !findMatches.length || !editor) return
    editor.setSelections(findMatches.map(r => ({
      selectionStartLineNumber: r.startLineNumber, selectionStartColumn: r.startColumn,
      positionLineNumber: r.endLineNumber, positionColumn: r.endColumn,
    })))
    editor.focus(); closeFind()   // hand off to live editing
  }

  function replaceOne() {
    const rep = (findEl('.mc-find-r') || {}).value || '', qstr = (findEl('.mc-find-q') || {}).value || ''
    if (findScope !== 'tab') return replaceAll()          // no single "current" across files → replace all in scope
    if (findIdx < 0 || !findMatches[findIdx] || !editor) return
    const rng = findMatches[findIdx], matched = editor.getModel().getValueInRange(rng)
    let groups = [matched]
    if (findFlags.rx) { const re = buildRe(qstr); if (re) { re.lastIndex = 0; const mm = re.exec(matched); if (mm) groups = mm } }
    editor.executeEdits('mc-find', [{ range: rng, text: replFor(matched, groups, rep), forceMoveMarkers: true }])
    runFind()
  }
  function replaceAll() {
    const qstr = (findEl('.mc-find-q') || {}).value || '', rep = (findEl('.mc-find-r') || {}).value || ''
    if (!qstr || !editor) return
    if (findScope === 'tab') {
      const model = editor.getModel(); if (!model) return
      const scope = (findFlags.insel && findSelRange) ? findSelRange : false
      let ms
      try { ms = model.findMatches(qstr, scope, findFlags.rx, findFlags.case, findFlags.word ? WORD_SEP : null, true) } catch (_) { return }
      if (!ms.length) return
      editor.executeEdits('mc-find', ms.map(m => ({ range: m.range, text: replFor(model.getValueInRange(m.range), m.matches || null, rep), forceMoveMarkers: true })))
      const n = ms.length; runFind()
      const c = findEl('.mc-find-count'); if (c) c.textContent = `replaced ${n}`
      return
    }
    // all tabs / whole sandbox — rewrite each source string, sync the sandbox, reload the open editor
    const re = buildRe(qstr); if (!re) return
    flushActiveToSandbox(); window.SANDBOX = window.SANDBOX || {}
    let hits = 0, files = 0
    scopeSources().forEach(({ name, text, tab }) => {
      re.lastIndex = 0; let n = 0
      const out = text.replace(re, function (m0) { n++; return replFor(m0, Array.prototype.slice.call(arguments, 0, -2), rep) })
      if (!n) return
      files++; hits += n
      if (tab) { tab.content = out; tab.cache = out; tab.dirty = true }
      if (window.SANDBOX[name]) window.SANDBOX[name].data = out
      else window.SANDBOX[name] = { kind: 'code', ext: extOf(name), mime: '', data: out }
    })
    if (active()) loadTab(active())                        // reflect the change in the open editor
    render()
    const c = findEl('.mc-find-count'); if (c) c.textContent = hits ? `replaced ${hits} in ${files} file${files === 1 ? '' : 's'}` : 'No results'
  }

