// settings.js — the gear (⚙️). three things:
//   1. the key-gate — enter an API key to enter oz (Anthropic recommended; free tickets).
//   2. YOU — pronouns · who i am · what i'm doing · anything else.
//   3. THE BOT — a sub-bar of agents; each gets a name · pronouns · backstory · persona ·
//      model (picked from your SAVED keys) · injection (a dropdown). ＋ make one → woodshop.
// every box is a section of your CUSTOM INJECTION — change here or in the injection builder,
// change both (same localStorage keys). all browser-only — the key calls the provider directly,
// never a server of ours. save commits all.
// build phase: stored here; the live call · model lists · injection builder are next wires.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   context / memory — how a bot keeps long ...... search: "context / memory — how"
//   profile gates — deluxe = the full suite ...... search: "profile gates — deluxe"
//   the overlay controller — settings is NOT a ... search: "the overlay controller"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the settings overlay UI (the ⚙️ gear).
//    **It exports `window.OZ_SETTINGS` with `.open()`, `.close()`, and `.isOpen()` methods. It
//    **reads from and writes to `localStorage` keys prefixed `toto_*` and `oz_*`, and depends on
//    **`window.REG` (providers, models, agents from shell/registry.js), `window.OZ_PROFILE` (build
//    **profile), `window.OZ_METER` (usage receipts), and `window.ozEngines` (local model controls).
//
//    **TOUCH HERE** —
//    - Add or remove an API provider → edit `PROVIDERS` alias at line 21 (reads from
//    - `window.REG.providers`)
//    - Add or remove a built-in agent → edit `BOTS` alias at line 23 (reads from
//    - `window.REG.agents`)
//    - (an injection template picker lived here and was a dead stub — killed 26 Aug, see the note
//    - at the old INJECTIONS site. A bot's injection comes from agents/<id>/injection.json.)
//    - Add or remove a web-search provider → edit `SEARCH` array at lines 30–33
//    - Change the free/payg pricing labels → edit `free` and `payg` strings at lines 38–39
//    - Add a field to the HIL (human in the loop) tab → add `sgField()` call in the `hil` panel at
//    - lines 240–246
//    - Add a field to a bot's settings → add `sgField()` or `sgSelect()` call in `sgRenderBot()` at
//    - lines 141–148
//    - Change the context/memory fields (trim mode, threshold) → edit `sgContextFields()` at lines
//    - 84–90
//    - Change the self-check (anti-hallucination) options → edit `sgSelfCheck()` at lines 96–106
//    - Add a Monaco helper (autocomplete, Squiggy, Teach, Fix) → edit `MC_ROSTER` at lines 111–116
//    - Hide a tab for a profile (e.g., lean/googleOnly) → edit the conditional at lines 212, 231,
//    - 256
//    - Change the save behavior or validation → edit the save listener at lines 319–336
//
//    **TRAPS** —
//    - `localStorage` keys are user data. Renaming `toto_*` or `oz_*` keys orphans saved settings.
//    - The key format `toto_bot_<botId>_<field>` is read by other files (shell/search.js, the
//    - injection builder); change it in one place and it breaks silently elsewhere.
//    - `sgHasKey()` at line 16 is the gate: no key → settings opens on load (line 426) and save is
//    - blocked (line 323). Removing or weakening this check breaks the BYOK model.
//    - `commitFields()` at line 17 writes all `[data-k]` attributes to localStorage. If you add a
//    - field without a `data-k` attribute, it won't save. If you rename a `data-k`, old data is
//    - orphaned.
//    - `window.OZ_PROFILE` gates features: `deluxe` (null) vs. standalone, `googleOnly`, `lean`,
//    - `houseBot`, `agents`. Line 197 computes these; lines 201–202 filter providers based on them.
//    - A profile change here must match the build's actual profile object.
//    - `MC_ROSTER` at line 111 is Monaco's own roster (not `BOTS`). Its ids (`mc_auto`,
//    - `mc_squiggy`, etc.) are hardcoded in the engine; renaming them breaks Monaco's gear.
//    - The overlay is NOT a card (line 189 comment). It's mounted directly to `document.body` (line
//    - 397) and sized by `sgSizeBody()` (line 387). The save button closes it (line 334); if you
//    - change that flow, the overlay may not unmount.
//    - `wireSettings()` at line 271 and `wireLocation()` at line 341 are called once per open. If
//    - you add a new wiring function, call it from `wireSettings()` or it won't run.
//    - The location field writes `oz_geo_manual` (sticky) and clears `oz_geo` (auto-cache) at line
//    - 349–350. The almanac reads these; change the key names and the almanac breaks silently.
//    - `sgRenderBot()` at line 122 has a `mini` flag for Monaco. The two branches (lines 125–138
//    - vs. 140–148) render different fields. If you add a field, add it to BOTH branches or
//    - Monaco's gear will be incomplete.
//
//    **DO NOT** —
//    - Do not rename `sgGet`, `sgSet`, `sgEsc`, `sgHasKey`, `commitFields` — they are utility
//    - functions used throughout the file and in other files.
//    - Do not move or rename the `window.OZ_SETTINGS` export (lines 394–408) or the `toggleCard`
//    - override (lines 410–416) — the topbar and other cards call these.
//    - Do not change the tab names (`api`, `hil`, `bot`, `yocal`) at lines 209–212 — they are
//    - hardcoded in the panel selectors at lines 215, 238, 249, 256.
//    - Do not edit the HTML structure of the modal (lines 204–264) without updating the selectors
//    - in `wireSettings()` (e.g., `.sg-tab`, `.sg-panel`, `.sg-pill`).
//    - Do not add new localStorage keys without documenting their format and reading them elsewhere
//    - (search.js, the injection builder, the almanac, etc.). If you add a key, grep the codebase
//    - first.
//    - Do not change the model-picker logic at lines 67–79 without checking the injection builder
//    - and the live-call code — they also filter models by saved keys.
//    - Do not move the `bootGate()` function (lines 422–429) or change when it runs — it gates the
//    - entire app on first load.
//    - Do not add profile-specific UI without checking `window.OZ_PROFILE` at line 197 and the
//    - build's actual profile object. A mismatch silently hides features.
//    - Do not edit the location-search API call (line 371) without checking the almanac — it uses
//    - the same open-meteo endpoint.
//    - Do not change the meter export format (line 176) without updating any code that reads
//    - `window.OZ_METER.export()`.
//    - The injection config (💉 folder) and woodshop (🪓 axe) are separate cards — do not try to
//    - build them here. Lines 253, 314–315 only link to them.
//
//
//
//    ---
//
// END IC SHIP PASS


window.CARD_BUILDERS = window.CARD_BUILDERS || {}

function sgGet(k) { return localStorage.getItem(k) || '' }
function sgSet(k, v) { localStorage.setItem(k, v) }
function sgEsc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function sgHasKey() { return PROVIDERS.some(p => sgGet('toto_' + p.id + '_key')) }
function commitFields(scope) { scope.querySelectorAll('[data-k]').forEach(el => sgSet(el.dataset.k, el.value)) }

// the MASTER LISTS live in shell/registry.js (window.REG) — ONE source the gear, the injection
// config + the topbar all read + push to. thin aliases here keep the rest of settings unchanged.
const PROVIDERS = window.REG.providers          // buy one (Anthropic recommended) or a free ticket (Groq · Gemini)
const MODELS = window.REG.modelsByProvider      // a curated model per provider (live fetch is a later wire)
const BOTS = window.REG.agents                  // built-ins + customs (REG already merged toto_custom_agents)
// ⛔ THE INJECTION-TEMPLATE PICKER IS GONE — 26 Aug. Sum: "kills dead control, is superceded stub."
//  It rendered a <select> per bot, wrote toto_bot_<id>_injection on change, and NOTHING anywhere
//  read that key — not this card, not the injection card, not the compiler. A control the user can
//  set and no machine can hear is worse than a missing one: it teaches that the app lies.
//  SUPERSEDED BY, and this is why it is a stub rather than a bug: the 💉 injection card compiles a
//  bot's warm head from agents/<id>/injection.json, and the ROLE SHEETS (agents/roles.json) carry
//  the rules a class of bots wears. Between them there is no question left for a picker to answer.
//  This morning I "fixed" it — derived the list off the roster so it would stop leaking bot ids —
//  which made a dead control correct instead of removing it. Deriving a stub keeps the stub.
//  The code is in _recycle/settings-injection-picker.js with its full history. The line above it in
//  the file header ("Add or remove an injection template → edit INJECTIONS") is corrected too.

// web-search keys — the SAME BYOK toll as the model keys, optional. duckduckgo + wikipedia are KEYLESS (so
// search never hard-fails with nothing here); tavily (general web) wants a free key. (jina cut 2026-08-28 — hallucinates.)
// bound to toto_<id>_key — read by shell/search.js, saved by the same save button (commitFields). more boxes,
// more tolls: every key the user pastes is money to that company, paid direct — never through us. (gowf · fupm.)
const SEARCH = [
  { id: 'tavily', name: 'Tavily', url: 'https://app.tavily.com/home', ph: 'tvly-… · general live web', tag: 'web' },
  // Jina row CUT (Sum 2026-08-28: "it hallucinates too easily — cut that code out completely").
  // The engine went with it (shell/search.js); a saved toto_jina_key just sits unused.
]

function sgRow(p) {
  const tag = p.tag ? `<span class="sg-tag sg-tag-${p.tag}">${p.tag}</span>` : ''
  // the pricing chip(s) — free·limited / pay-as-you-go / both. (Sum: "we list buy payg, or free but limited.")
  const free = '<span class="sg-tag sg-tag-free">free · limited</span>'
  const payg = '<span class="sg-tag sg-tag-payg">pay as you go</span>'
  const pay = p.pay === 'free' ? free : p.pay === 'payg' ? payg : p.pay === 'both' ? free + payg : ''
  // yocal (noKey) runs on this Mac — no key, no link. say so instead of showing an empty key field that lies.
  if (p.noKey) return `<div class="sg-row">
    <div class="sg-row-top"><span class="sg-name">${p.name}</span>${tag}</div>
    <div class="sg-nokey">no key needed — runs on this Mac. start it in the 🔧 setup card.</div>
  </div>`
  return `<div class="sg-row">
    <div class="sg-row-top"><span class="sg-name">${p.name}</span>${tag}${pay}<a class="sg-get" href="${p.url}" target="_blank" rel="noopener">get a key ↗</a></div>
    <input type="password" class="sg-key" data-k="toto_${p.id}_key" placeholder="${p.ph}" value="${sgEsc(sgGet('toto_' + p.id + '_key'))}" autocomplete="off">
  </div>`
}

// a labelled field bound to a localStorage key (= one custom-injection section)
function sgField(k, label, ph, rows) {
  const ctrl = rows
    ? `<textarea data-k="${k}" rows="${rows}" placeholder="${ph}">${sgEsc(sgGet(k))}</textarea>`
    : `<input type="text" data-k="${k}" placeholder="${ph}" value="${sgEsc(sgGet(k))}">`
  return `<div class="sg-field"><label>${label}</label>${ctrl}</div>`
}

function sgSelect(k, label, options) {
  const cur = sgGet(k)
  const opts = options.map(o => `<option value="${o}"${o === cur ? ' selected' : ''}>${o}</option>`).join('')
  return `<div class="sg-field"><label>${label}</label><select class="sg-select" data-k="${k}">${opts}</select></div>`
}

// model picker — only the providers you've SAVED a key for (save first, then reopen)
function sgModelField(botId) {
  const allow = window.REG.agentProviders ? window.REG.agentProviders(botId) : null   // jem → ['gemini']
  // noKey providers (yocal · ollama) are keyless BY DESIGN — filtering on a saved key hid every local
  // model from every bot's picker here, while the injection card (which uses REG.availableModels, the
  // one that checks p.noKey) showed them fine. That split is why local looked 'missing' in one place
  // and worked in another. The checkers list below already worked around it by re-adding them by hand.
  let saved = PROVIDERS.filter(p => p.noKey || sgGet('toto_' + p.id + '_key'))
  if (allow) saved = saved.filter(p => allow.includes(p.id))   // google-only bots see only their providers (no local)
  if (!saved.length) return `<div class="sg-field"><label>model</label><div class="sg-dim">add + save a key above to unlock a model.</div></div>`
  const cur = sgGet('toto_bot_' + botId + '_model')
  const groups = saved.map(p =>
    `<optgroup label="${p.name}">${(MODELS[p.id] || []).map(m => `<option value="${m}"${m === cur ? ' selected' : ''}>${m}</option>`).join('')}</optgroup>`).join('')
  return `<div class="sg-field"><label>model</label><select class="sg-select" data-k="toto_bot_${botId}_model">${groups}</select></div>`
}

// ── context / memory — how a bot keeps long chats in budget. same keys the ✂️/🪗 bar under its chat reads;
//    the home for these in a STANDALONE (no 💉 injection page). (Sum, 2026-07-01.) ──
function sgContextFields(botId) {
  return '<div class="sg-sec-hint" style="margin-top:8px">🧠 context — how this keeps a long chat in budget (the ✂️ / 🪗 bar under its chat).</div>' +
    sgSelect('toto_inj_histmode_' + botId, 'when it fills', ['trim', 'compact']) +
    sgSelect('toto_inj_thmode_' + botId, 'measured by', ['turns', 'pct']) +
    sgField('toto_inj_turns_' + botId, 'keep last (turns)', '20') +
    sgField('toto_inj_histpct_' + botId, 'or at (% of window)', '70')
}

// (Sum 2026-07-13) SELF-CHECK — the plain (no-funny-name, no-pill) version of "Hallucinot": after it answers, it re-reads
//   its own reply and asks "do I stand by this? phone a friend (web search)? correct myself?" and fixes what it can.
//   reduces hallucinations. a BAND-AID, not a cure; OFF by default (an extra pass costs tokens). same key as the injection
//   config's Hallucinot toggle → change one, change both. (Sum: "second-gen antipsychotic" energy, admitted as a bandaid.)
function sgSelfCheck(botId) {
  // (Sum 2026-07-13) key-aware checker list: self · YOUR saved cloud models (claude, gemini…) · local models · bots.
  //   a MODEL = a COLD call (no persona/brahman) · a BOT = stacks its persona + context.
  const checkers = ['self']
  PROVIDERS.filter(p => !p.noKey && sgGet('toto_' + p.id + '_key')).forEach(p => (MODELS[p.id] || []).forEach(m => checkers.push(m)))
  ;['local', 'ollama'].forEach(pid => (MODELS[pid] || []).forEach(m => checkers.push(m)))
  ;(BOTS || []).forEach(b => checkers.push(b.id))
  return '<div class="sg-sec-hint" style="margin-top:8px"><img src="skin/bandaid.png" style="height:22px;vertical-align:-6px;margin-right:6px" alt="">anti-hallucination injection — <b>on</b> = auto-checks when idle + the manual button on the bar. A second read agrees, or flags it and the original does ONE more corrective round (web search for the facts). A band-aid, not a cure — off by default.</div>' +
    sgSelect('toto_inj_selfcheck_' + botId, 'injection', ['off', 'on']) +
    sgSelect('toto_inj_selfcheck_who_' + botId, 'checked by — a model = cold · a bot = its persona', checkers)
}

// (Sum 2026-07-13) MONACO's own bots page — the four in-editor helpers. autocomplete is LIGHT (model + how you
//   like suggestions); Squiggy · Teach · Fix each get a FULL persona + a context/prune policy. ids are card-
//   internal (mc_*); the engine already gives each its own persona (buildSystem), model (pickProvider) + trim (trimHist).
const MC_ROSTER = [
  { id: 'mc_auto',    label: 'autocomplete', light: true },
  { id: 'mc_squiggy', label: 'Squiggy' },
  { id: 'mc_teach',   label: 'Teach' },
  { id: 'mc_fix',     label: 'Fix' },
]
function sgMcSubbar(sel) {
  return `<div class="sg-subbar">${MC_ROSTER.map(h => `<button class="sg-pill${h.id === sel ? ' on' : ''}" data-bot="${h.id}">${h.label}</button>`).join('')}</div>`
}

// the fields for one bot
function sgRenderBot(card, botId, mini) {
  const k = s => 'toto_bot_' + botId + '_' + s
  // Monaco's gear (mini): the LIGHT autocomplete = model + style + preference; the three that TALK = full persona + context.
  if (mini) {
    const helper = MC_ROSTER.find(h => h.id === botId) || MC_ROSTER[0]
    card.querySelector('.sg-botfields').innerHTML = helper.light
      ? sgModelField(botId) +
        sgField(k('style'), 'style', 'terse · idiomatic · type-hinted · comments-off — how suggestions should read') +
        sgField(k('preference'), 'preference', 'what to prefer or avoid when it suggests — libraries, patterns, naming…', 2)
      : sgField(k('name'), 'name', 'optional') +
        sgField(k('pronouns'), 'pronouns', 'they/them') +
        sgField(k('backstory'), 'backstory', 'a history or context that shapes how it speaks.', 2) +
        sgField(k('persona'), 'persona', 'core personality + instructions. the most powerful field.', 4) +
        sgModelField(botId) +
        sgContextFields(botId) +
        sgSelfCheck(botId)
    return
  }
  // ⭐ LEARNER IS NOT A CHARACTER (Sum 2026-08-17). It never chats — it builds one lesson section per
  //   call. So its three voice slots hold REGISTERS, not a personality, and they are labelled as such.
  //   ONE LINE each: the voice only. Every structural law — gloss at first use, two examples from
  //   different corners, four choices with one correct, the banned phrases — lives in the ROLE SHEET
  //   (agents/roles.json 'section-builder'), which users cannot edit or delete. Same split as nurse
  //   and coder: the job is protected, the voice is yours.
  // ── CORRECTION 26 Aug: was `botId === 'learner'`. "Not a character" is a property of a bot, not
  //    of that one name — a second builder bot would need the same panel and would silently get the
  //    persona one. It is caps: ["registers"] on the record now.
  if (window.REG && window.REG.hasCap && window.REG.hasCap(botId, 'registers')) {
    card.querySelector('.sg-botfields').innerHTML =
      sgField(k('persona'), '5th grade — the house voice', 'a smart precocious 5th grader who is not sure the adult will follow, so they over-explain. lots of examples.', 3) +
      sgField(k('pronouns'), 'phd voice', 'a PhD in this subject explaining it to a PhD in interpretive dance.', 2) +
      sgField(k('backstory'), 'snippet voice', 'the answer you wanted when you googled it, before the ad and the three scrolls.', 2) +
      sgModelField(botId) +
      sgContextFields(botId) +
      sgSelfCheck(botId)
    return
  }
  card.querySelector('.sg-botfields').innerHTML =
    sgField(k('name'), 'name', 'optional') +
    sgField(k('pronouns'), 'pronouns', 'they/them') +
    sgField(k('backstory'), 'backstory', 'a history or context that shapes how it speaks.', 2) +
    sgField(k('persona'), 'persona', 'core personality + instructions. the most powerful field.', 4) +
    sgModelField(botId) +
    sgContextFields(botId) +
    sgSelfCheck(botId)
}

function sgSubbar(sel) {
  const P = window.OZ_PROFILE   // standalone → only this build's agents; deluxe (null) → the whole roster
  const list = (P && P.agents) ? BOTS.filter(b => P.agents.includes(b.id)) : BOTS
  const pills = list.map(b => `<button class="sg-pill${b.id === sel ? ' on' : ''}" data-bot="${b.id}">${b.label}</button>`).join('')
  return `<div class="sg-subbar">${pills}</div>`
}

// the HIL location field — renders the current pick (or "auto")
function sgLocationField() {
  let label = 'auto-detected from your connection'
  try { const m = JSON.parse(sgGet('oz_geo_manual') || 'null'); if (m && m.name) label = '📍 ' + m.name } catch (_) {}
  return `<div class="sg-field sg-loc">
    <label>location <span class="sg-dim">— weather · air · sun · moon</span></label>
    <div class="sg-loc-row">
      <input type="text" class="sg-loc-search" placeholder="search a city…" autocomplete="off">
      <button type="button" class="sg-loc-here" title="use my location (auto-detect)">📍</button>
    </div>
    <div class="sg-loc-results"></div>
    <div class="sg-loc-current">${label}</div>
  </div>`
}

// 📊 the receipts — what THIS device routed, per provider. local, no content/identity. the steaks-and-scotch
// number. hidden until there's something to show. (the cross-user grand total is a separate anonymous counter.)
function sgMeter() {
  const r = (window.OZ_METER && window.OZ_METER.export()) || null
  if (!r || !r.by_provider.length) return ''
  const k = n => n >= 1000 ? (n / 1000).toFixed(n >= 100000 ? 0 : 1) + 'k' : String(n)
  const rows = r.by_provider.map(p => `<div class="sg-meter-row"><span>${sgEsc(p.provider)}</span><span class="sg-meter-num">${p.requests.toLocaleString()} req · ~${k(p.tokens)} tok</span></div>`).join('')
  return `<div class="sg-meter">
    <div class="sg-sec-hint">📊 receipts — what this device routed (${r.days}d). local only · no content · no identity. your number for the table.</div>
    ${rows}
    <div class="sg-meter-row sg-meter-total"><span>total</span><span class="sg-meter-num">${r.total.requests.toLocaleString()} req · ~${k(r.total.tokens)} tok</span></div>
    <button class="sg-meter-copy" type="button">copy receipt (JSON)</button>
  </div>`
}

function buildSettings(opts) {
  // NOT a card — a full overlay over the desktop + bots (Sum: "make it not a card at all, just overlays").
  const mini = !!(opts && opts.mini)   // (Sum 2026-07-11) Monaco's gear opens a STRIPPED copy: API · HIL · yocal · choose model — no backstory/persona/injection/woodshop
  const ov = document.createElement('div')
  ov.className = 'sg-overlay' + (mini ? ' sg-mini' : '')
  const tipOpen = sgGet('toto2_byok_tip') !== 'off'
  // ── profile gates — deluxe = the full suite (OZ_PROFILE null); a standalone is an object. (Sum, 2026-07-01.)
  //   injection-config + woodshop pointers: DELUXE ONLY (keep the code, ditch the pointers in standalones).
  //   googleOnly (jem): only the Google key, no yocal tab, picker fenced to gemini — the safest PG build.
  const _P = window.OZ_PROFILE, deluxe = !_P, googleOnly = !!(_P && _P.googleOnly)
  // a browser can't run the local engines (Sum 2026-07-24: "skip yocal for newspapers") — drop the
  // noKey/local/ollama rows in lean; they only make sense in the native app.
  // (was: `const lean = !!(_P && _P.lean)`. Dead 2026-08-30 — both readers, noYocal and the
  //  apiProviders filter, moved to `!window.__TAURI__`, which is what they always meant. Dead code
  //  goes, the note stays. The prose above it is still the right explanation of WHY the rows drop.)
  // same knife as registry.js's yocal strip (Sum 2026-08-09: "no local option from website"): in a
  // plain browser the yocal tab is a lie — "runs on THIS Mac" with buttons that can only flash
  // "app only". Found leaking on the 0zcom port (29 Aug 2026): the lean gate keys off OZ_PROFILE,
  // and the web beta ships deluxe (profile null), so the tab showed. The shell is the fact here,
  // not the profile. (The safe spec seats THE SAFE where this section would sit on the url build.)
  // ⚠⚠ CORRECTION 2026-08-30 — `lean` came OUT of this expression. Was:
  //     const noYocal = googleOnly || lean || !window.__TAURI__
  //
  // STILL TRUE, all of it: a browser cannot run local engines, the yocal tab is a lie there, and
  // the 29 Aug leak on the 0zcom port was real. Only the MECHANISM was wrong — and the note
  // directly above already said so: "The shell is the fact here, not the profile."
  //
  // lean was a proxy for "this is a web newspaper" back on 2026-07-24, when the only lean build
  // WAS a web newspaper. On 30 Aug lean shipped in a NATIVE app for the first time (the toto
  // strip, a real .app with a real Electron floor) — and the proxy inverted: it hid the local
  // engines in the exact build where they work. `!window.__TAURI__` was always the honest test,
  // and it covers the web case identically, so EXTRA² and the 0zcom port are unchanged.
  const noYocal = googleOnly || !window.__TAURI__
  let apiProviders = googleOnly ? PROVIDERS.filter(p => p.id === 'gemini') : PROVIDERS
  // 2026-08-30: was `if (lean)`. Same inversion as noYocal above and the same honest test — a
  // NATIVE lean build (the toto strip) is exactly where local and keyless engines DO work, so
  // gating on the profile hid them in the one place they belong. Behaviour on the web: identical.
  if (!window.__TAURI__) apiProviders = apiProviders.filter(p => !p.noKey && p.id !== 'local' && p.id !== 'ollama')
  ov.innerHTML = `
   <div class="sg-modal" role="dialog" aria-modal="true">
    <div class="sg-modal-head"><span class="sg-modal-title"><span class="sg-modal-ic">⚙️</span> settings</span></div>
    <div class="sg-body">

      <div class="sg-tabs">
        <button class="sg-tab on" data-tab="api">API</button>
        <button class="sg-tab" data-tab="hil">HIL</button>
        <button class="sg-tab" data-tab="bot">${mini ? 'bots' : 'BOT'}</button>
        ${noYocal ? '' : '<button class="sg-tab" data-tab="yocal">yocal</button>'}
        ${mini ? '' : '<button class="sg-tab" data-tab="safe">🔒 safe</button>'}
      </div>

      <div class="sg-panel" data-panel="api">
        <div class="sg-gate">
          <div class="sg-gate-key">🔑</div>
          <!-- COPY REFRESH 2026-08-29 (Sum: "this toast got stale — it's just the keys to 0z. the
               cards work keyless, the bots need brains"). The old line was the PSV-paper pitch
               (newsie · the press · roll-your-own); what survived it: browser-direct, never our
               server, free tickets. -->
          <div class="sg-gate-copy"><b>the keys to 0z</b><br><span class="sg-dim">the cards work keyless — the bots need brains. a key wakes them up. it lives in your browser and calls the provider direct — never a server of ours. free tickets exist (Groq · Gemini).</span></div>
        </div>
        <!-- ⛴ THE FERRYMAN, 2026-08-30 — FREE BUILDS ONLY. Sum's line: "full gear, but we judge
             you silently if you are paying for tokens but not the ferryman on the river sticks."
             He asked for it "next to it on the api tab of all free versions", and this is next to
             it: under the keys note, above the providers, where somebody is about to paste a key
             they pay for.
             ⚠⚠ CORRECTION, same hour — the gate was "OZ_PROFILE.free", set on the four strips.
             WRONG TEST, and it missed the biggest free surface in the whole product: the FULL
             SUITE running in a browser off the splash logo. That build has no "free" flag because
             it is the desktop profile — and it is completely free to use.
             Sum: "I think we add ferryman to ozcom not ozweb versions · the main suite web based
             off link from logo on splash needs the ferryman bit and fupm."
             "!window.__TAURI__" IS that line, said in code: no native floor means a browser, and a
             browser build is one nobody paid for. Same honest test as the yocal gate two hundred
             lines up, which was corrected off a profile flag onto this exact check for the same
             reason. A profile describes a BUILD; only the shell knows where it is RUNNING.
             The DMG and the exe stay quiet, which is the point — never guilt somebody who paid.
             ⚠ SPELLING: he wrote "sticks". Styx here, because the joke IS the reference and a
             reader who does not land Charon gets nothing from it. His typo, my call.
             Tone stays dry: one clause, and the slot is a link, not a plea. -->
        ${!window.__TAURI__ ? `
        <div class="sg-ferryman">
          <span class="sg-ferryman-ic" aria-hidden="true">&#9204;</span>
          <span>This build is free and stays free. We judge you silently if you are paying for
          tokens but not the ferryman on the river Styx.
          <a class="sg-ferryman-link" href="#" data-fupm="1">FUPM &#8594;</a></span>
        </div>` : ''}
        <div class="sg-providers">${apiProviders.map(sgRow).join('')}</div>
        <button class="sg-info" title="about keys — click to hide / show">ⓘ</button>
        <div class="sg-tip${tipOpen ? ' open' : ''}">
          ${googleOnly
            ? `🎟️ <b>free ticket to oz</b> — grab a free key from <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">Google AI Studio</a> (no card), paste it above, and you're in. one key runs chat + pictures.`
            : `🎟️ <b>free ticket to oz</b> — most providers hand you a key free, no card:
          <a href="https://console.groq.com/keys" target="_blank" rel="noopener">Groq</a> ·
          <a href="https://aistudio.google.com/apikey" target="_blank" rel="noopener">Google AI Studio</a>.
          paste it above and you're in.<br>
          want the strongest models? <b>i recommend <a href="https://www.anthropic.com/api" target="_blank" rel="noopener">Anthropic</a></b> — it's who toto's built on.`}
        </div>
        ${googleOnly ? '' : `<div class="sg-searchkeys">
          <div class="sg-sec-hint">🔍 web search keys — optional. <b>DuckDuckGo + Wikipedia are keyless</b> and always on; add a key to unlock the others. same toll: the key calls them direct, never us.</div>
          ${SEARCH.map(sgRow).join('')}
        </div>`}
        ${sgMeter()}
        <div class="sg-factory">
          <div class="sg-sec-hint">↺ <b>factory reset</b> — puts oz back to out-of-box.
            <b>KEPT:</b> your API keys · My Music · the time-travel map · everything you authored
            (studio pools, prunes, curations, doctrines, your author roster, custom feeds, saved towns, muzzle list).
            <b>WIPED:</b> bot voices and personas, chats, card state, drafts, and the papers (My View, The Feedline, the newsie's bible and drawer, the reading log). Two presses — the first one counts.</div>
          <button class="sg-reset">↺ factory reset — keep my keys</button>
        </div>
        <div class="sg-factory">
          <div class="sg-sec-hint">🔑 <b>reset keys</b> — the exact opposite of the button above: it wipes
            <b>only</b> your API and search keys and leaves every setting, paper and pool alone.
            <b>oz cannot give a key back</b> — you re-paste it from the provider. Two presses.</div>
          <button class="sg-keys">🔑 reset keys — wipe my API keys</button>
        </div>
        <div class="sg-factory">
          <div class="sg-sec-hint">🗂️ <b>delete sandbox files</b> — the only one that reaches <b>disk</b>.
            Everything in <code>~/totoII/sandbox</code>: files you dragged in, files a bot wrote, code,
            docs, the papers. <b>There is no sandbox trash</b> — this is for good, history included.
            Settings and keys are untouched. Two presses.</div>
          <button class="sg-sandbox">🗂️ delete sandbox files — off disk, for good</button>
        </div>
      </div>

      <div class="sg-panel" data-panel="hil" hidden>
        <p class="sg-sec-hint">🧠 the human in the loop — who every bot is talking to, and where. all optional. feeds your custom injection.</p>
        ${sgField('toto_userName', 'name', 'optional')}
        ${sgField('toto_userPronouns', 'pronouns', 'they/them')}
        ${sgLocationField()}
        ${sgField('toto_userWho', 'who i am', 'background, identity, history…', 2)}
        ${sgField('toto_userLife', 'life context', 'situation, health, constraints…', 2)}
        ${sgField('toto_userDoing', "what i'm doing", 'the current mission, in a line or two.', 2)}
        ${sgField('toto_userElse', 'anything else', 'how to treat you, preferences, pet peeves — whatever helps.', 2)}
      </div>

      <div class="sg-panel" data-panel="bot" hidden>
        <p class="sg-sec-hint">${mini ? "🤖 Monaco's helpers — autocomplete, Squiggy, Teach &amp; Fix. each its OWN model + how it behaves. autocomplete is light (model + your style); the three that talk get a full persona + a context/prune policy. keys live in <b>API</b> · your local in <b>yocal</b>." : '🤖 each agent: its own name, voice, persona, model + injection. same custom injection — change one, change both.'}</p>
        ${mini ? sgMcSubbar('mc_auto') : sgSubbar(_P && _P.houseBot ? _P.houseBot : 'toto')}
        <div class="sg-botfields"></div>
        ${deluxe && !mini ? '<div class="sg-nav"><button class="sg-go" data-go="injection">💉 injection config</button><button class="sg-go" data-go="axe">🪓 woodshop</button></div>' : ''}
      </div>

      ${noYocal ? '' : `<div class="sg-panel" data-panel="yocal" hidden>
        <p class="sg-sec-hint">🔧 your local engine — yocal (words), on this Mac. no key, no cloud, nothing leaves the machine.</p>
        <div class="sg-engines"></div>
      </div>`}

      ${mini ? '' : `<div class="sg-panel" data-panel="safe" hidden>
        <!-- 🔒 THE SAFE (2026-08-29, the bow №1 lane grown to six boxes) — seated after yocal on
             desktop, where the engine section would sit on the url build (the spec's seat). The
             panel body mounts on tab-open from cards/settings/safe.js — the ozEngines renderInto
             pattern, one home for the safe's UI. -->
        <div class="sg-safe"></div>
      </div>`}

      <div class="sg-close-row"><button class="sg-close-btn" type="button">✕ close</button></div>
    </div>
    <div class="sg-foot"><button class="sg-save">save</button></div>
   </div>`
  // click the dimmed backdrop (outside the modal) to close — same "close always lets you out" as the ✕
  ov.addEventListener('click', e => { if (e.target === ov && window.OZ_SETTINGS) window.OZ_SETTINGS.close() })
  wireSettings(ov, mini)
  return ov
}

function wireSettings(card, mini) {

  // ── ↺ FACTORY RESET (Sum 2026-08-17: "reset whole app to factory and save my keys, should be an
  //    easy button for that"). shell/factory.js already did exactly this on every build change,
  //    with the keep-list already right — it just had no way to fire on purpose. This is the button.
  //    TWO PRESSES: the first says what it is about to take. Nothing irreversible on one click.
  card.addEventListener('click', e => {
    const b = e.target.closest('.sg-reset'); if (!b) return
    e.stopPropagation()
    const F = window.OZ_FACTORY
    if (!F) { b.textContent = 'factory.js not loaded — nothing done'; return }
    if (b.dataset.armed !== '1') {
      const n = F.peek().length
      b.dataset.armed = '1'
      b.textContent = `↺ press again to wipe ${n} setting${n === 1 ? '' : 's'} and the papers — keys kept`
      setTimeout(() => { if (b.dataset.armed === '1') { b.dataset.armed = ''; b.textContent = '↺ factory reset — keep my keys' } }, 6000)
      return
    }
    const n = F.reset()
    b.dataset.armed = ''
    b.textContent = `✓ reset — ${n} wiped, your keys kept. reloading…`
    setTimeout(() => { try { location.reload() } catch (_) {} }, 900)
  })
  // ── 🔑 RESET KEYS + 🗂️ DELETE SANDBOX FILES (Sum 2026-08-25: "3 separate buttons for the level of
  //    refresh you want"). Both copy the ↺ button's contract exactly — count on the first press, act on
  //    the second, auto-disarm at 6s — because three buttons that behave three ways in one panel is how
  //    a person presses the wrong one. Neither reloads: keys go quiet, files just go.
  card.addEventListener('click', e => {
    const b = e.target.closest('.sg-keys'); if (!b) return
    e.stopPropagation()
    const F = window.OZ_FACTORY
    if (!F || !F.resetKeys) { b.textContent = 'factory.js not loaded — nothing done'; return }
    if (b.dataset.armed !== '1') {
      const n = F.peekKeys().length
      if (!n) { b.textContent = '🔑 no keys saved — nothing to wipe'
                setTimeout(() => { b.textContent = '🔑 reset keys — wipe my API keys' }, 3000); return }
      b.dataset.armed = '1'
      b.textContent = `🔑 press again to wipe ${n} key${n === 1 ? '' : 's'} — you re-paste them from the provider`
      setTimeout(() => { if (b.dataset.armed === '1') { b.dataset.armed = ''; b.textContent = '🔑 reset keys — wipe my API keys' } }, 6000)
      return
    }
    const n = F.resetKeys()
    b.dataset.armed = ''
    b.textContent = `✓ ${n} key${n === 1 ? '' : 's'} wiped — paste a new one above to wake the bots`
  })
  card.addEventListener('click', async e => {
    const b = e.target.closest('.sg-sandbox'); if (!b) return
    e.stopPropagation()
    const FS = window.OZ_FS
    if (!FS || !FS.wipeSandbox) { b.textContent = 'fs.js not loaded — nothing done'; return }
    if (b.dataset.armed !== '1') {
      const n = FS.peekSandbox().length
      if (!n) { b.textContent = '🗂️ the sandbox is already empty'
                setTimeout(() => { b.textContent = '🗂️ delete sandbox files — off disk, for good' }, 3000); return }
      b.dataset.armed = '1'
      b.textContent = `🗂️ press again to delete ${n} file${n === 1 ? '' : 's'} off disk — no trash, no undo`
      setTimeout(() => { if (b.dataset.armed === '1') { b.dataset.armed = ''; b.textContent = '🗂️ delete sandbox files — off disk, for good' } }, 6000)
      return
    }
    b.dataset.armed = ''
    b.textContent = '🗂️ deleting…'
    const n = await FS.wipeSandbox()
    b.textContent = `✓ ${n} file${n === 1 ? '' : 's'} gone from ~/totoII/sandbox`
  })

  // tabs — API · HIL · BOT
  card.querySelectorAll('.sg-tab').forEach(t => t.addEventListener('click', () => {
    card.querySelectorAll('.sg-tab').forEach(x => x.classList.toggle('on', x === t))
    card.querySelectorAll('.sg-panel').forEach(p => { p.hidden = p.dataset.panel !== t.dataset.tab })
    // mount the local-engine controls when the yocal tab opens — robust to load order (the build-time mount
    // could fire before ozEngines loaded → the empty-on-first-load bug). re-render also refreshes status.
    if (t.dataset.tab === 'yocal' && window.ozEngines) { const eng = card.querySelector('.sg-engines'); if (eng) window.ozEngines.renderInto(eng, 'all') }
    // 🔒 the safe mounts the same way (cards/settings/safe.js) — re-render on each open so the
    // per-box counts are live, not the counts from the last time the tab was looked at.
    if (t.dataset.tab === 'safe' && window.OZ_SAFE) { const sf = card.querySelector('.sg-safe'); if (sf) window.OZ_SAFE.renderInto(sf) }
  }))
  wireLocation(card)
  // 📊 copy the receipt (the routed-usage JSON) — the number you bring to the table
  const mc = card.querySelector('.sg-meter-copy')
  if (mc) mc.addEventListener('click', () => { try { navigator.clipboard.writeText(JSON.stringify(window.OZ_METER.export(), null, 2)); const o = mc.textContent; mc.textContent = '✓ copied'; setTimeout(() => mc.textContent = o, 1500) } catch (_) {} })
  // the yocal tab — mount the shared local-engine controls
  const eng = card.querySelector('.sg-engines')
  if (eng && window.ozEngines) window.ozEngines.renderInto(eng, 'all')

  // close — BOTH the ✕ in the head AND the "close" above save leave WITHOUT the key-gate (save is gated;
  // close always lets you out). (the settings card is flex:1 / fills the desk, so there's nothing to resize.)
  const closeGear = () => {
    const gearBtn = document.querySelector('.tb-btn[data-card="gear"]'); if (gearBtn) gearBtn.classList.remove('active')
    if (window.toggleCard) window.toggleCard('gear', false)
  }
  card.querySelectorAll('.sg-x, .sg-close-btn').forEach(b => b.addEventListener('click', closeGear))

  // the ⓘ — click to hide / show the tip; remembered. (the light-bar / clock pattern.)
  const info = card.querySelector('.sg-info')
  const tip = card.querySelector('.sg-tip')
  info.addEventListener('click', () => sgSet('toto2_byok_tip', tip.classList.toggle('open') ? 'on' : 'off'))

  // the bot sub-bar — switch agents (commit the one you're leaving first).
  // default to this build's house bot / first agent (jem in the Jem app); the full suite still lands on toto.
  const _P = window.OZ_PROFILE
  // (Sum 2026-07-13) mini = Monaco's gear → its OWN roster (autocomplete · Squiggy · Teach · Fix), lands on autocomplete. deluxe → the house bot.
  const _firstBot = mini ? 'mc_auto' : ((_P && _P.houseBot) || (_P && _P.agents && _P.agents[0]) || 'toto')
  sgRenderBot(card, _firstBot, mini)
  card.querySelectorAll('.sg-pill[data-bot]').forEach(p => p.addEventListener('click', () => {
    commitFields(card.querySelector('.sg-botfields'))
    card.querySelectorAll('.sg-pill[data-bot]').forEach(x => x.classList.toggle('on', x === p))
    sgRenderBot(card, p.dataset.bot, mini)
  }))
  // settings leads to the injection config (💉 folder) + the woodshop (🪓 axe)
  card.querySelectorAll('.sg-go').forEach(b => b.addEventListener('click', () => {
    if (b.dataset.go === 'injection') { if (window.toggleCard) window.toggleCard('injection', true) }
    else document.querySelector('.tb-btn[data-card="axe"]')?.click()
  }))

  // save — commit every bound field (keys + you + the current bot), flash, then close.
  const save = card.querySelector('.sg-save')
  // ⭐ 2 Sep 2026 (Sum: "once a key is entered, the last entered key is the default if not picked"). Remember which
  //    key field the human typed in last; on save, if that key is non-empty it becomes toto_default_provider — the
  //    provider pickProvider() (00-providers.js) tries right after a bot's own pick. Fallback when nothing was typed
  //    this visit: the last key field whose value changed and is non-empty. Out of the box: no stamp, the old walk.
  card.querySelectorAll('.sg-key').forEach(el => el.addEventListener('input', () => { card._lastKey = el.dataset.k }))
  save.addEventListener('click', () => {
    try {
      const prov = k => (/^toto_(.+)_key$/.exec(String(k || '')) || [])[1] || ''
      const changed = Array.from(card.querySelectorAll('.sg-key')).filter(el => el.value.trim() && el.value !== sgGet(el.dataset.k)).map(el => el.dataset.k)
      const typed = card._lastKey && (card.querySelector('.sg-key[data-k="' + card._lastKey + '"]') || {}).value
      const winner = (typed && String(typed).trim()) ? card._lastKey : changed[changed.length - 1]
      if (winner && prov(winner)) sgSet('toto_default_provider', prov(winner))
    } catch (_) {}
    commitFields(card)
    if (window.pulse) window.pulse('ctx')   // context settings (trim/compact mode·threshold) → refresh the ✂️/🪗 bar now
    if (!sgHasKey()) {   // the gate is nailed to the floor — no key, no exit
      save.textContent = 'add a key to enter oz ↑'; save.classList.add('sg-saved')
      setTimeout(() => { save.textContent = 'save'; save.classList.remove('sg-saved') }, 1800)
      // EXTRA² (lean): the FIRST key hires the staff — reload so the newsie + studio walk in
      try { if (window.OZ_PROFILE && window.OZ_PROFILE.lean && sgHasKey() && !document.querySelector('.tb-btn[data-card="newsie"], .tb-btn[data-agent="newsie"]')) setTimeout(() => location.reload(), 900) } catch (_) {}
      return
    }
    save.textContent = 'saved ✓'; save.classList.add('sg-saved')
    setTimeout(() => {
      const gearBtn = document.querySelector('.tb-btn[data-card="gear"]')   // keep the topbar in sync
      if (gearBtn) gearBtn.classList.remove('active')
      if (window.toggleCard) window.toggleCard('gear', false)
    }, 450)
  })
}

// the HIL location field — auto-detect (📍) or a city search (open-meteo geocoding, free/no key).
// writes oz_geo_manual (sticky) so the almanac uses it; clears the auto-cache so it takes immediately.
function wireLocation(card) {
  const search = card.querySelector('.sg-loc-search')
  if (!search) return
  const results = card.querySelector('.sg-loc-results')
  const current = card.querySelector('.sg-loc-current')
  const refresh = () => { if (window.OZ_CLOCK) window.OZ_CLOCK.refresh() }

  function setLoc(lat, lon, name) {
    sgSet('oz_geo_manual', JSON.stringify({ lat, lon, name }))
    localStorage.removeItem('oz_geo')
    current.textContent = '📍 ' + name
    results.innerHTML = ''; search.value = ''
    refresh()
  }

  // 📍 use my location — drop the manual pick, fall back to auto-detect
  card.querySelector('.sg-loc-here').addEventListener('click', () => {
    localStorage.removeItem('oz_geo_manual'); localStorage.removeItem('oz_geo')
    current.textContent = 'auto-detected from your connection'
    refresh()
  })

  // city search — debounced geocoding (open-meteo, free/no key)
  let t = null
  search.addEventListener('input', () => {
    clearTimeout(t)
    const q = search.value.trim()
    if (q.length < 2) { results.innerHTML = ''; return }
    t = setTimeout(async () => {
      try {
        const r = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=5&language=en&format=json`)
        const hits = (await r.json()).results || []
        results.innerHTML = hits.map((p, i) =>
          `<button type="button" class="sg-loc-hit" data-i="${i}">${sgEsc(p.name)}${p.admin1 ? ', ' + sgEsc(p.admin1) : ''} <span class="sg-dim">${sgEsc(p.country_code || '')}</span></button>`).join('')
        results.querySelectorAll('.sg-loc-hit').forEach((b, i) => b.addEventListener('click', () => {
          const p = hits[i]; setLoc(p.latitude, p.longitude, p.name + (p.admin1 ? ', ' + p.admin1 : ''))
        }))
      } catch (_) { results.innerHTML = '<div class="sg-dim">search unavailable</div>' }
    }, 300)
  })
}

// ── the overlay controller — settings is NOT a card; it floats over everything (desktop, cards, bots) ──
let _sgOverlay = null, _sgResize = null
// size the scrolling body to the overlay's REAL pixel height (not `vh` — WKWebView resolves vh too big here,
// which slid the save bar off the bottom). measure the fixed overlay (= the true viewport) and subtract head + foot.
function sgSizeBody(ov) {
  if (!ov) return
  const head = ov.querySelector('.sg-modal-head'), foot = ov.querySelector('.sg-foot'), body = ov.querySelector('.sg-body')
  if (!body) return
  const avail = ov.clientHeight - 40   // overlay padding (20 top + 20 bottom)
  body.style.maxHeight = Math.max(140, avail - (head ? head.offsetHeight : 0) - (foot ? foot.offsetHeight : 0)) + 'px'
}
window.OZ_SETTINGS = {
  open(opts) {
    if (_sgOverlay) return
    _sgOverlay = buildSettings(opts); document.body.appendChild(_sgOverlay)
    requestAnimationFrame(() => sgSizeBody(_sgOverlay))
    _sgResize = () => sgSizeBody(_sgOverlay); window.addEventListener('resize', _sgResize)
    if (window.markActive) window.markActive('gear', true)
  },
  close() {
    if (_sgResize) { window.removeEventListener('resize', _sgResize); _sgResize = null }
    if (_sgOverlay) { _sgOverlay.remove(); _sgOverlay = null }
    if (window.markActive) window.markActive('gear', false)
  },
  isOpen() { return !!_sgOverlay },
}
// route every gear toggle (topbar · deck · save · ✕ · bootGate) to the overlay instead of mounting a card
;(function () {
  const orig = window.toggleCard
  window.toggleCard = function (id, on) {
    if (id === 'gear') { on ? window.OZ_SETTINGS.open() : window.OZ_SETTINGS.close(); return }
    return orig ? orig.apply(this, arguments) : undefined
  }
})()

// nail the BYOK gate to the floor — no key yet → settings opens on load.
// EXTRA² (the web paper): the FRONT PAGE is free — no key needed to READ. the key
// unlocks make-new + the newsie, gated where those live, never at the door.
// (Sum: "no key → read the scheduled editions; byok → the press is yours.")
;(function bootGate() {
  const P = window.OZ_PROFILE
  if (P && P.cards && P.cards.length === 1 && P.cards[0] === 'scroll') return   // the paper reads free
  if (sgHasKey()) return
  window.OZ_SETTINGS.open()
  const b = document.querySelector('.tb-btn[data-card="gear"]')
  if (b) b.classList.add('active')
})()

// ⛴ THE FERRYMAN'S LINK opens the FUPM CARD in THIS app, not a web page. Sum 2026-08-30: "fupm at
// end of ferryman bit, with link to open the fupm card please."
//
// DELEGATED ON document, deliberately: the settings overlay is torn down and rebuilt on every
// open, every tab switch and every skin change, so a listener bound to the anchor itself would be
// gone by the second look. One listener, bound once, survives all of it.
//
// ⚠ THIS IS WHY 'fupm' IS IN THE NEVER-GATED SET in shell/cards.js. Wiring this link is what
// found it: toggleCard('fupm') was refused in every strip, because no strip lists fupm in `cards`.
// The tip jar has to open in the give-away builds — those are the ones where the ask belongs.
document.addEventListener('click', function (e) {
  var a = e.target && e.target.closest && e.target.closest('[data-fupm]')
  if (!a) return
  e.preventDefault()
  try { if (window.OZ_SETTINGS && window.OZ_SETTINGS.close) window.OZ_SETTINGS.close() } catch (_) {}
  try { document.querySelectorAll('.sg-overlay').forEach(function (o) { o.remove() }) } catch (_) {}
  if (window.toggleCard) window.toggleCard('fupm', true)
})
