// monaco.js — ⚠ ASSEMBLED FILE. build.sh concatenates cards/monaco/parts/*.js into this file
// (build.sh is GONE, and this tree was unwired until 25 Aug 2026 — edits to parts/ never shipped.)
// before every build — EDIT THE PARTS, not this file (a direct edit here is clobbered next build).
// each part is a FRAGMENT of ONE closure: `node --check` the ASSEMBLED file, never a lone part.
//
// monaco.js — the 🏁 MONACO card. a code editor (Monaco, from CDN) on a Monaco-GP table.
// PORTED from oz4.2's monaco-card.js (Local/monaco/), IC-cleaned for toto2:
//   · server sandbox (localhost:3038/api) → window.SANDBOX (the in-browser cache, no server)
//   · the NASCAR version.png car → GP.png (the Grand Prix / Indy car); monaco-topbar.png = the bar
//   · auto-insert into #right → a CARD_BUILDERS card that RETURNS its element
//   · inline onclick → one IIFE + event delegation (no global-scope leak, no collision)
// flow: open a file (native picker → it lands in the sandbox), or pick a cached file from
// the sandbox, edit it, then 🏁 save-as with the native saver. between card toggles the
// editor resets but the sandbox holds the files — the file is the memory.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers · ~3.2k lines, IC pass 3 will chunk this file)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   tabs + recency + the dock .............. search: "editor + tab state"
//   history / rollback ..................... search: "history — rollback"
//   name bar (rename · ext · goto) ......... search: "the NAME BAR"
//   jewels + autosave + sandbox ............ search: "the jewels — SAME logic"
//   open file / import folder / wrecker .... search: "open a file: native picker"
//   save (version · disk) .................. search: "save a version"
//   ▶ RUN + console/cli/preview/problems ... search: "RUN + 🟡🟢🔴 JEWELS"
//   the CLI tab (+ serve) .................. search: "the CLI tab"
//   SQUIGGY (lint · gym · god · chat) ...... search: "SQUIGGY — leveled autofill"
//   keys drawer (ƒ · {} · 123) ............. search: "THE KEYS DRAWER"
//   find/replace + hotkeys + ⌘K palette .... search: "HOTKEYS (Sum"
//   the highlighter (🖊 scope) ............. search: "THE HIGHLIGHTER"
//   TEACH (voices · slides · practice) ..... search: "GOFAI RAILS"
//   GARAGES / wings / sliders / collapse ... search: "GARAGES (Sum"
//   ⛶ fullscreen (debug·teach·fix) ......... search: "FULLSCREEN — Debug"
//   code-in-chat fold bars ................. search: "CODE-IN-CHAT FOLD"
//   FIX (the repair-coder workspace) ....... search: "FIX = a WORKSPACE"
//   card builder + templates + pit ......... search: "the card builder"
// ══════════════════════════════════════════════════════════════════════

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   editor + tab state — one monaco card at a ..... search: "editor + tab state"
//   recency (Sum 2026-07-09): the main tab bar .... search: "recency (Sum"
//   💼 the CORPORATE templates — résumé · cover .... search: "💼 the CORPORATE"
//   tabs .......................................... search: "tabs"
//   history — rollback / forward (a snapshot is ... search: "history — rollback /"
//   render the jewel + the tab grid (no inline .... search: "render the jewel + the"
//   the NAME BAR (Sum 2026-07-09): an editable .... search: "the NAME BAR (Sum"
//   reflow (Sum 2026-07-09): the tab bar is a ..... search: "reflow (Sum"
//   the jewels — SAME logic as tiptap: 🟢 on ....... search: "the jewels — SAME logic"
//   autosave — after a typing pause, land the ..... search: "autosave — after a"
//   the sandbox (window.SANDBOX) — the ............ search: "the sandbox"
//   open a file: native picker → cache it in ...... search: "open a file: native"
//   import a whole FOLDER → copy the tree into .... search: "import a whole FOLDER →"
//   the WRECKER — clear a TAB off the table. ...... search: "the WRECKER — clear a"
//   the wrecker — CLICK to tow the active tab ..... search: "the wrecker — CLICK to"
//   🟡 save a version → the active tab's ........... search: "🟡 save a version → the"
//   🏁 save to device — the native saver, else a ... search: "🏁 save to device — the"
//   ▶ RUN + 🟡🟢🔴 JEWELS + CONSOLE (Sum ............. search: "▶ RUN + 🟡🟢🔴 JEWELS +"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — the Monaco editor card: tab state, file I/O, autosave, rollback history, the tab
//    **bar UI (main + dock), the name bar (rename/ext), jewel indicators (🟢🟡🔴), and the wrecker
//    **(tab closer). Exports `window.monacoReveal()` for the conductor to reveal sandbox edits
//    **live.
//
//    **TOUCH HERE**
//    - Change how many tabs fit in the main bar → `MAIN_MAX` L60
//    - Change the undo/rollback depth → `HISTORY_MAX` L42
//    - Change the autosave delay → `scheduleAutosaveMc()` L333 (currently 1500ms)
//    - Change which file extensions Monaco recognizes → `LANG` L45 or `EXTS` L186
//    - Change the jewel colors or logic (🟢🟡🔴 states) → `mcJewel()` L320
//    - Change the tab overflow behavior (when tabs spill to the dock) → `reflowTabs()` L257
//    - Change the wrecker's confirmation dialog → `confirmTow()` L420
//    - Change the name bar's auto-hide on scroll → `wireNamebarAutohide()` L214
//    - Change the corporate templates (résumé, cover letter, etc.) → `corporateTemplates()` L85 or
//    - `DOC_CSS` L73
//    - Change the editor theme (light/dark) → `mcTheme()` L66
//
//    **TRAPS**
//    - `activeId` (L53) and `recent` (L61) are the two sources of truth for which tab is active and
//    - in what order; `setActiveId()` L93 and `bumpRecent()` L62 must both be called together or
//    - the UI desynchronizes.
//    - `window.SANDBOX` (L339, L370, L386, L518) is the persistent file cache; the shape `{ kind,
//    - ext, mime, data }` is load-bearing — a shape change orphans user files.
//    - `t.disk` vs `t.cache` (L107) are the jewel snapshots; `t.dirty` (L106) is computed from the
//    - editor, not stored — do not persist it.
//    - `_suppress` (L129) gates the dirty flag on programmatic setValue; if you add another
//    - programmatic edit path, wrap it in `_suppress = true/false` or the jewel will lie.
//    - `_dragId` (L61) must be cleared in the drop handler (L314) or mid-drag renders will yank the
//    - dragged tab out from under the cursor.
//    - `tabById()` L55 is called in hot loops (reflowTabs L267, moveTab L289); it is O(n) — if tabs
//    - grow large, consider indexing.
//    - The tab markup (L158–174) has no inline onclick; all clicks are delegated in the event
//    - handlers wired below (search "data-mc=" to find them).
//    - `editor.saveViewState()` (L135) and `editor.restoreViewState()` (L135) are per-tab
//    - scroll/cursor memory; if Monaco version changes, the format may break silently.
//
//    **DO NOT**
//    - Do not edit the assembled file directly (L1–2); edit `cards/monaco/parts/00-deck.js` and run
//    - `build.sh`.
//    - Do not rename `window.monacoReveal` (L358) — the conductor calls it by name.
//    - Do not move the `_suppress` flag logic (L129–130) or add new setValue calls outside it.
//    - Do not change the `window.SANDBOX` shape without a migration path for existing user files.
//    - Do not add new tab state fields without updating `newTab()` L101 and `loadTab()` L131.
//    - The event delegation wiring (search "data-mc=") lives elsewhere in the file; do not
//    - duplicate it here.
//    - The Monaco CDN URL (L41) and language map (L45) are shared with other parts; changes may
//    - need coordination.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {

  const MONACO_CDN  = 'https://cdn.jsdelivr.net/npm/monaco-editor@0.45.0/min/vs'
  const HISTORY_MAX = 20

  // ext → Monaco language id
  const LANG = { js:'javascript', ts:'typescript', jsx:'javascript', tsx:'typescript',
    py:'python', java:'java', css:'css', html:'html', htm:'html', json:'json', md:'markdown',
    sh:'shell', yml:'yaml', yaml:'yaml', sql:'sql', txt:'plaintext' }
  const extOf  = n => (n.split('.').pop() || 'txt').toLowerCase()
  const langOf = e => LANG[e] || 'plaintext'
  const abbrev = n => (n.length > 14 ? n.slice(0, 12) + '…' : n)

  // ── editor + tab state — one monaco card at a time; reset on each build ──
  let editor = null, tabs = [], activeId = null, seq = 0, card = null

  const tabById = id => tabs.find(t => t.id === id)
  const active  = () => tabById(activeId)

  // ── recency (Sum 2026-07-09): the main tab bar shows the CURRENT + 2 most-recent; the DOCK holds every
  //    open file, draggable to reorder / move between the two bars. `recent` = ids, most-recent first. ──
  const MAIN_MAX = 3
  let recent = [], _dockOpen = true, _dockAuto = true, _dragId = null   // (Sum) the overflow (2nd) row shows by default when tabs spill
  function bumpRecent(id) { if (id) recent = [id, ...recent.filter(x => x !== id)] }

  // (Sum 2026-07-10) LIGHT/DARK — the editor theme FOLLOWS the skin: light 'vs' on clinical, 'vs-dark' elsewhere.
  // monaco.editor.setTheme is GLOBAL → one observer re-themes every open editor the instant the skin changes.
  function mcTheme() { return document.documentElement.dataset.skin === 'clinical' ? 'vs' : 'vs-dark' }
  try { new MutationObserver(() => { try { if (window.monaco) monaco.editor.setTheme(mcTheme()) } catch (_) {} })
        .observe(document.documentElement, { attributes: true, attributeFilter: ['data-skin'] }) } catch (_) {}

  // ── 💼 the CORPORATE templates — résumé · cover letter · memo · business plan. STOLEN from the tiptap docs
  //    (window.TIPTAP_TEMPLATES — the same oz "fever dream" content) + wrapped in a clean, print-ready HTML page,
  //    so the coder ships editable HTML DOCUMENTS, not just games. built at click-time → always in sync with tiptap. ──
  const DOC_CSS = `*{box-sizing:border-box}body{margin:0;background:#e9e9ea;padding:24px;font-family:Georgia,'Times New Roman',serif}
.doc{max-width:720px;margin:0 auto;background:#fff;color:#1a1a1a;padding:60px 72px;box-shadow:0 2px 22px rgba(0,0,0,.15);line-height:1.6;font-size:15px}
.doc h1{font-size:27px;margin:0 0 4px;letter-spacing:.4px}
.doc h2{font-size:17px;margin:26px 0 8px;border-bottom:1px solid #e0e0e0;padding-bottom:4px}
.doc h3{font-size:15px;margin:16px 0 4px}
.doc p{margin:0 0 12px}.doc a{color:#1a4d8f}.doc b,.doc strong{color:#000}
.doc ul,.doc ol{margin:0 0 12px 22px}.doc hr{border:0;border-top:1px solid #e0e0e0;margin:24px 0}
@media print{body{background:#fff;padding:0}.doc{box-shadow:none;max-width:none;padding:40px}}`
  function wrapDoc(title, bodyHtml) {
    return `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>${title}</title>\n<style>\n${DOC_CSS}\n</style>\n</head>\n<body>\n<main class="doc">\n${bodyHtml}\n</main>\n</body>\n</html>\n`
  }
  const DOC_FILE = { resume: 'resume.html', cover: 'cover-letter.html', memo: 'memo.html', plan: 'business-plan.html' }
  function corporateTemplates() {
    return (window.TIPTAP_TEMPLATES || []).map(d => ({
      key: 'doc-' + d.key, label: d.label, ai: true, ext: 'html',
      filename: DOC_FILE[d.key] || (d.key + '.html'),
      data: wrapDoc(d.name || d.key, (d.html || '').trim()),
    }))
  }
  function dropRecent(id) { recent = recent.filter(x => x !== id) }
  function setActiveId(id) { activeId = id; bumpRecent(id) }
  function mainIdSet() {                                  // the ≤3 ids that ride up top — most-recent, backfilled by tab order
    const set = new Set(recent.filter(tabById).slice(0, MAIN_MAX))
    for (const t of tabs) { if (set.size >= MAIN_MAX) break; set.add(t.id) }
    return set
  }

  // ── tabs ────────────────────────────────────────────────────────────────
  function newTab(filename, content, mode) {
    saveEditorToTab()
    const id = 'mt-' + (++seq)
    const fromDisk = (mode || 'original') === 'original'        // opened from a device file → already on disk
    tabs.push({ id, filename, content, ext: extOf(filename), mode: mode || 'original',
                dirty: false, history: [], hi: -1, autoExt: false,
                disk: fromDisk ? content : null, cache: content })   // jewel snapshots: 🟢 disk · 🟡 sandbox
    setActiveId(id)
    loadTab(active())
    render()
    sqOnFileSwitch()   // (Sum 2026-07-13) a NEW file (＋ · drop · open from sandbox) is also a file switch — reset Squiggy's chat so it reads THIS file, not the old one
    // hydrate rollback history from disk (native) — once, and only if this session hasn't built its own.
    if (window.OZ_FS && window.OZ_FS.native) {
      const t = active()
      window.OZ_FS.readVersions(filename).then(vers => {
        if (!vers || !vers.length || !t || t.history.length) return
        t.history = vers.slice(); t.hi = t.history.length - 1
        if (active() === t) render()
      })
    }
  }
  function switchTab(id) {
    if (id === activeId) return
    saveEditorToTab(); setActiveId(id); loadTab(active()); render(); sqOnFileSwitch()   // (Sum 2026-07-13) tell Squiggy's chat we moved files
  }
  function saveEditorToTab() { const t = active(); if (t && editor) { t.content = editor.getValue(); t.viewState = editor.saveViewState() } }
  // a PROGRAMMATIC setValue (load · rollback · external) must not look like the user typing — suppress the
  // dirty + autosave side effects while WE drive the editor. only real keystrokes mark a tab dirty.
  let _suppress = false
  function setVal(v) { _suppress = true; try { if (editor) editor.setValue(v) } finally { _suppress = false } }
  function loadTab(t) {
    if (!t || !editor) return
    monaco.editor.setModelLanguage(editor.getModel(), langOf(t.ext))
    setVal(t.content)
    if (t.viewState) { try { editor.restoreViewState(t.viewState) } catch (_) {} }   // (Sum 2026-07-10) reopen to the SAME line — per-tab scroll + cursor
  }

  // ── history — rollback / forward (a snapshot is taken on each save) ───────
  function pushHistory(t, content) {
    t.history.splice(t.hi + 1)
    t.history.push(content)
    if (t.history.length > HISTORY_MAX) t.history.shift()
    t.hi = t.history.length - 1
    t.dirty = false
    render()
    if (window.OZ_FS) window.OZ_FS.saveVersion(t.filename, content)   // persist the checkpoint → survives reload
  }
  function step(dir) {
    const t = active(); if (!t || !editor) return
    const next = t.hi + dir
    if (next < 0 || next >= t.history.length) return
    t.hi = next; t.content = t.history[next]; setVal(t.content); t.dirty = false; render()
  }

  // ── render the jewel + the tab grid (no inline onclick — delegated below) ─
  //  ONE markup for a tab (main bar) OR a chip (dock). the ACTIVE main tab also carries the version nav (GP car);
  //  chips + inactive tabs are just a draggable name that switches on click.
  function tabMarkup(tb, chip) {
    const dot = tb.dirty ? '<span class="mc-tab-dot">●</span>' : ''
    const isActive = tb.id === activeId
    const cls = (chip ? 'mc-chip' : 'mc-tab') + (isActive ? ' active' : '') + ' mode-' + tb.mode
    if (chip || !isActive)
      return `<div class="${cls}" draggable="true" data-mc="switch" data-id="${tb.id}"><span class="mc-tab-name">${abbrev(tb.filename)}${dot}</span></div>`
    const total = tb.history.length, idx = tb.hi
    return `<div class="${cls}" draggable="true" data-id="${tb.id}">
      <span class="mc-tab-name">${abbrev(tb.filename)}${dot}</span>
      <span class="mc-tab-ver" data-mc="vernav" title="version — click the car for the ◀ ▶ rollback nav">
        <img src="cards/monaco/assets/GP.png" class="mc-ver-car" alt="">${total ? idx + 1 + '/' + total : '0'}
        <span class="mc-ver-pop">
          <button class="mc-tab-nav" data-mc="back" ${idx <= 0 ? 'disabled' : ''}>◀</button>
          <button class="mc-tab-nav" data-mc="fwd" ${idx >= total - 1 ? 'disabled' : ''}>▶</button>
        </span>
      </span>
    </div>`
  }
  function render() {
    const bar = card.querySelector('.mc-tab-bar'); if (!bar) return
    reflowTabs()   // (Sum 2026-07-09) reflowTabs rebuilds the full top row, then spills the overflow — one source of truth
    renderNamebar()
    updateWrecker()
    mcJewel()
  }

  // ── the NAME BAR (Sum 2026-07-09): an editable [ filename . ext ] on the page — rename the active file here.
  //    ext auto-detects from the content (✨ auto), the dropdown overrides. ──
  const EXTS = ['html', 'js', 'css', 'json', 'md', 'txt', 'py', 'ts', 'jsx', 'tsx', 'svg', 'xml', 'sh', 'yaml']
  const baseOf = n => String(n).replace(/\.[^.]+$/, '')
  function detectExt(s, cur) {
    const t = (s || ''), h = t.slice(0, 4000).toLowerCase()
    if (/<!doctype html|<html|<body\b|<div\b|<span\b|<script\b/.test(h)) return 'html'
    if (/^\s*[{[]/.test(t)) { try { JSON.parse(t); return 'json' } catch (_) {} }
    if (/(^|\n)\s*#!.*\bpython|\b(def |import |elif |print\()/.test(h)) return 'py'
    if (/\b(const |let |var |function |=>|console\.|module\.exports|require\()/.test(h)) return 'js'
    if (/[.#][\w-]+\s*\{[^}]*(:|;)/.test(h) || /:\s*(#[0-9a-f]{3,6}|\d+px)\s*;/.test(h)) return 'css'
    if (/(^|\n)#{1,6}\s|\]\(|(^|\n)\s*[-*]\s/.test(t)) return 'md'
    return cur || 'txt'
  }
  function ensureExtOption(sel, ext) {
    if (ext && !Array.from(sel.options).some(o => o.value === ext)) sel.add(new Option(ext, ext))
  }
  function renderNamebar() {
    const bar = card && card.querySelector('.mc-namebar'); if (!bar) return
    const input = bar.querySelector('.mc-name-in'), sel = bar.querySelector('.mc-ext-sel')
    const t = active()
    if (!t) { input.value = ''; input.disabled = sel.disabled = true; bar.classList.add('empty'); return }
    bar.classList.remove('empty'); input.disabled = sel.disabled = false
    if (document.activeElement !== input) input.value = baseOf(t.filename)
    const ext = t.ext || extOf(t.filename); ensureExtOption(sel, ext)
    sel.value = t.autoExt ? 'auto' : ext
  }
  // (Sum 2026-07-09) the NAME BAR auto-hides on scroll: reading DOWN slides it away (reclaims the height for code),
  // scrolling UP — or landing back at the top — brings it back. wired to monaco's onDidScrollChange in loadMonaco.
  let _lastScroll = 0
  function wireNamebarAutohide() {
    // (Sum 2026-07-14) NO auto-hide — the name bar stays put; go-to-line lives here permanently now, so it must always be reachable.
    const bar = card && card.querySelector('.mc-namebar'); if (bar) bar.classList.remove('hide-on-scroll')
  }
  // rename the active tab (+ its sandbox entry + the editor language). guards against clobbering another tab.
  function renameActive(newName) {
    const t = active(); if (!t || !newName || newName === t.filename) { renderNamebar(); return }
    if (tabs.some(x => x !== t && x.filename === newName)) { renderNamebar(); return }   // name taken → revert the field
    const old = t.filename, cur = editor ? editor.getValue() : t.content
    window.SANDBOX = window.SANDBOX || {}
    const prev = window.SANDBOX[old] || {}
    window.SANDBOX[newName] = { kind: prev.kind || 'code', ext: extOf(newName), mime: prev.mime || '', data: cur }
    if (old !== newName) { try { delete window.SANDBOX[old] } catch (_) {} }
    t.filename = newName; t.ext = extOf(newName)
    if (editor && t.id === activeId) monaco.editor.setModelLanguage(editor.getModel(), langOf(t.ext))
    render()
  }
  function renameFromBar() {
    const t = active(); if (!t) return
    let base = (card.querySelector('.mc-name-in').value || '').trim().replace(/[\/\\]/g, '').replace(/\.+$/, '')
    if (!base) { renderNamebar(); return }
    let ext = t.ext || extOf(t.filename)
    const m = base.match(/^(.*)\.([A-Za-z0-9]+)$/)   // typed "Mynewbot.js" → split off the ext + stop auto
    if (m) { base = m[1]; ext = m[2].toLowerCase(); t.autoExt = false }
    renameActive(base + '.' + ext)
  }
  function setExt(val) {
    const t = active(); if (!t) return
    if (val === 'auto') { t.autoExt = true; autoDetectActive(true); return }
    t.autoExt = false; renameActive(baseOf(t.filename) + '.' + val)
  }
  // when a tab is in ✨ auto mode, re-guess the ext from the content (called on the autosave tick)
  function autoDetectActive(force) {
    const t = active(); if (!t || (!t.autoExt && !force)) return
    const guess = detectExt(editor ? editor.getValue() : t.content, t.ext)
    if (guess && guess !== t.ext) renameActive(baseOf(t.filename) + '.' + guess)
    else renderNamebar()
  }
  // the DOCK — every open file as a draggable chip. pops the first time a 4th file lands; the toggle (right of
  // the 🟡 flag) shows the open-file count and flips it after that. hides when ≤3 files are open.
  // ── reflow (Sum 2026-07-09): the tab bar is a RESPONSIVE OVERFLOW. the top row fills with as many FULL tabs
  //    as fit the width; whatever doesn't fit spills to the 2nd row as tiny chips — no repeats, always ≥1 up top.
  //    re-runs on every render + on resize (the ResizeObserver). the active tab is never the one pushed down. ──
  function reflowTabs() {
    const bar = card && card.querySelector('.mc-tab-bar'), dock = card && card.querySelector('.mc-tabdock')
    if (!bar || !dock) return
    if (_dragId != null) return                                     // mid tow — don't yank the dragged tile out from under the drag
    bar.innerHTML = tabs.map(tb => tabMarkup(tb, false)).join('')   // (Sum) ALWAYS rebuild the full top row first → idempotent, so a WIDEN pulls spilled tabs back up (no lost / duplicated tabs on resize)
    dock.innerHTML = ''
    if (bar.clientWidth < 40) { syncDockChrome(false); return }   // not laid out yet (collapsed/hidden) — don't spill everything
    let guard = 0
    while (bar.scrollWidth > bar.clientWidth + 2 && bar.children.length > 1 && guard++ < 80) {
      let victim = null
      for (let i = bar.children.length - 1; i >= 0; i--) { if (bar.children[i].dataset.id !== activeId) { victim = bar.children[i]; break } }
      if (!victim) break
      const t = tabById(victim.dataset.id); victim.remove()
      if (t) dock.insertAdjacentHTML('afterbegin', tabMarkup(t, true))   // afterbegin keeps left→right order in the overflow row
    }
    syncDockChrome(dock.children.length > 0)
  }
  function syncDockChrome(overflow) {
    const dock = card.querySelector('.mc-tabdock')
    const wrap = card.querySelector('.mc-body-wrap')
    const n = dock ? dock.children.length : 0
    overflow = n > 0                                          // (Sum) single source of truth — the toggle+row exist iff a tab actually spilled in
    if (wrap) wrap.classList.toggle('dock-on', overflow && _dockOpen)
    const tgl = card.querySelector('.mc-dock-toggle')
    if (tgl) {
      tgl.style.display = overflow ? 'inline-flex' : 'none'  // no overflow → no toggle · ≥1 spilled → it's there on the bar
      tgl.classList.toggle('lit', _dockOpen)
      tgl.textContent = (_dockOpen ? '▾ ' : '▸ ') + n        // chevron reads as an open/close toggle · the number = how many are down there
    }
  }
  // reorder the canonical `tabs` list — drag within a bar, or between the two
  function moveTab(dragId, targetId, after) {
    const from = tabs.findIndex(t => t.id === dragId); if (from < 0) return
    const [m] = tabs.splice(from, 1)
    let to = tabs.findIndex(t => t.id === targetId)
    if (to < 0) { tabs.push(m); return }
    if (after) to++
    tabs.splice(to, 0, m)
  }
  function wireTabDnD(container, inMain) {
    container.addEventListener('dragstart', e => {
      const el = e.target.closest('[data-id]'); if (!el) return
      _dragId = el.dataset.id; e.dataTransfer.effectAllowed = 'move'
      try { e.dataTransfer.setData('text/plain', _dragId) } catch (_) {}
      el.classList.add('dragging')
    })
    container.addEventListener('dragend', e => { const el = e.target.closest('.dragging'); if (el) el.classList.remove('dragging'); _dragId = null })
    container.addEventListener('dragover', e => { if (_dragId) { e.preventDefault(); e.dataTransfer.dropEffect = 'move' } })
    container.addEventListener('drop', e => {
      if (!_dragId) return
      e.preventDefault(); e.stopPropagation()
      const el = e.target.closest('[data-id]')
      if (el && el.dataset.id !== _dragId) {
        const r = el.getBoundingClientRect()
        moveTab(_dragId, el.dataset.id, e.clientX > r.left + r.width / 2)
      }
      if (inMain) bumpRecent(_dragId)     // dropped into the top strip → it earns a current+2 slot
      _dragId = null
      render()
    })
  }

  // ── the jewels — SAME logic as tiptap: 🟢 on disk · 🟡 in the sandbox · 🔴 no copy of this state ──
  function mcJewel() {
    if (!card) return
    const t = active(), cur = (editor && t) ? editor.getValue() : (t && t.content)
    const g = card.querySelector('.cj-g'), a = card.querySelector('.cj-a'), r = card.querySelector('.cj-r')
    ;[g, a, r].forEach(j => j && j.classList.remove('lit', 'blink'))
    if (!t) return
    if (t.disk != null && cur === t.disk) g && g.classList.add('lit')         // 🟢 saved to disk
    else if (t.cache != null && cur === t.cache) a && a.classList.add('lit')  // 🟡 in the sandbox cache
    else r && r.classList.add('lit')                                          // 🔴 no copy of this state
  }

  // ── autosave — after a typing pause, land the current state in the sandbox cache → 🟡 (the safety net) ──
  let mcAuto = null
  function scheduleAutosaveMc() { clearTimeout(mcAuto); mcAuto = setTimeout(autosaveMc, 1500) }
  function autosaveMc() {
    const t = active(); if (!t || !editor) return
    const cur = editor.getValue()
    if (cur === t.disk || cur === t.cache) return            // already safe (🟢/🟡) — nothing to do
    t.content = cur; t.cache = cur
    window.SANDBOX = window.SANDBOX || {}
    const prev = window.SANDBOX[t.filename] || {}
    window.SANDBOX[t.filename] = { kind: prev.kind || 'code', ext: prev.ext || t.ext, mime: prev.mime || '', data: cur }
    try { window.OZ_MAP && window.OZ_MAP.touch && window.OZ_MAP.touch(t.filename) } catch (_) {}   // (Sum 2026-07-12) re-lay THIS file's dependency arrows on every settled edit — keep the JIT map live
    mcJewel()                                                // 🔴 → 🟡
    if (t.autoExt) autoDetectActive()                        // ✨ untitled files auto-name their extension on the pause
  }

  // ── the sandbox (window.SANDBOX) — the no-server file cache ───────────────
  function sandboxFiles() {
    return Object.entries(window.SANDBOX || {})
      .filter(([, v]) => v && typeof v.data === 'string' && v.kind !== 'url' && v.kind !== 'path')   // 'path' = a preview-only file:// pointer, not editable code
      .map(([name]) => name)
  }
  function openFromSandbox(name) {
    const e = (window.SANDBOX || {})[name]; if (e) newTab(name, e.data, 'sandbox')
  }
  // the conductor's executors call this after they read/edit/write a sandbox file — monaco reveals it
  // so the human watches the bot's work land live (the scroll-follow). existing tab → refresh + focus it.
  window.monacoReveal = function (name) {
    const e = (window.SANDBOX || {})[name]; if (!e) return
    const t = tabs.find(x => x.filename === name)
    if (t) { setActiveId(t.id); t.content = e.data; t.cache = e.data; loadTab(active()); render() }
    else openFromSandbox(name)
  }

  // ── open a file: native picker → cache it in the sandbox → new tab ────────
  function onPick(input) {
    const f = input.files && input.files[0]; if (!f) return
    const r = new FileReader()
    r.onload = () => {
      window.SANDBOX = window.SANDBOX || {}
      window.SANDBOX[f.name] = { kind: 'code', ext: extOf(f.name), mime: f.type, data: r.result }   // load into the cache
      newTab(f.name, r.result, 'original')
    }
    r.readAsText(f); input.value = ''
  }
  // ── import a whole FOLDER → copy the tree into the sandbox as a project, open it (Sum 2026-07-13: "copy my codebase in") ──
  function importFolder(input) {
    const files = [...(input.files || [])]; input.value = ''
    if (!files.length) return
    const root = ((files[0].webkitRelativePath || files[0].name).split('/')[0] || 'import').replace(/[^\w.\-]+/g, '-')
    const SKIP = /(^|\/)(node_modules|\.git|\.DS_Store|dist|build|\.next|__pycache__|venv|\.venv)(\/|$)/i
    const TEXT = /\.(txt|md|html?|css|scss|less|js|mjs|cjs|jsx|ts|tsx|json|py|rb|go|rs|c|h|cpp|hpp|java|kt|swift|sh|zsh|yml|yaml|xml|svg|toml|ini|cfg|env|vue|php|sql|lua|r)$/i
    const IMG = /\.(png|jpe?g|gif|webp|bmp|ico)$/i
    const readable = files.filter(f => { const rel = f.webkitRelativePath || f.name; return !SKIP.test(rel) && f.size <= 500 * 1024 && (TEXT.test(rel) || IMG.test(rel)) })
    if (!readable.length) return
    window.SANDBOX = window.SANDBOX || {}
    let done = 0
    readable.forEach(f => {
      const rel = f.webkitRelativePath || f.name, img = IMG.test(rel), r = new FileReader()
      r.onload = () => { window.SANDBOX[rel] = { kind: img ? 'image' : 'code', ext: extOf(rel), mime: f.type, data: r.result }; if (++done === readable.length) openProject(root) }
      img ? r.readAsDataURL(f) : r.readAsText(f)
    })
  }

  // ── the WRECKER — clear a TAB off the table. closes the tab ONLY. ──
  // the file STAYS in the sandbox (and on disk, native) — reopen it anytime from the 🏎 picker or 📂 folder.
  // a wrecking ball that only clears tabs, never files — that's the joke, and it's non-destructive.
  // (it used to confirm() + delete the file off disk: the confirm got swallowed in the webview, so a click
  //  read as "the wrecker is broken", and a stray drag could nuke a real file. now it just clears the tab.)
  // ghost when there's nothing to clear; CLICK clears the active tab, DRAG onto a tab clears that one.
  function updateWrecker() {
    const w = card && card.querySelector('.mc-wrecker'); if (!w) return
    w.classList.toggle('ghost', tabs.length === 0)
  }
  function towTab(id) {
    const t = tabById(id); if (!t) return

    tabs = tabs.filter(x => x.id !== id); dropRecent(id)        // close the tab — the file is left untouched
    if (activeId === id) {                                      // hand the wheel to the next-most-recent tab
      const heir = recent.find(tabById) || (tabs.length ? tabs[tabs.length - 1].id : null)
      activeId = heir; if (heir) bumpRecent(heir)
      if (active()) loadTab(active())
      else if (editor) setVal('// MONACO — lights out to load a file\n')
    }
    render()
  }

  // (Sum 2026-07-09) the trash-can asks first — an INLINE confirm (window.confirm is swallowed in the webview),
  // with a chance to SAVE the tab (a 🟡 checkpoint to the sandbox) before it goes.
  function confirmTow(id, anchor) {
    const t = tabById(id); if (!t) return
    document.getElementById('mc-tow-confirm')?.remove()
    const m = node(`<div class="mc-tow-confirm" id="mc-tow-confirm">
      <div class="mc-tow-q">trash <b>${abbrev(t.filename)}</b>?</div>
      <button class="mc-tow-btn save" data-tow="save">💾 save &amp; close</button>
      <button class="mc-tow-btn go"   data-tow="go">🗑 close it</button>
      <button class="mc-tow-btn no"   data-tow="no">✕ keep it</button>
    </div>`)
    document.body.appendChild(m)
    const r = anchor.getBoundingClientRect()
    m.style.left = Math.min(r.left, window.innerWidth - 210) + 'px'
    m.style.top = (r.bottom + 6) + 'px'
    const close = () => { m.remove(); document.removeEventListener('mousedown', onDoc, true) }
    const onDoc = ev => { if (!m.contains(ev.target)) close() }
    setTimeout(() => document.addEventListener('mousedown', onDoc, true), 0)
    m.addEventListener('click', ev => {
      const b = ev.target.closest('[data-tow]'); if (!b) return
      ev.stopPropagation()
      const a = b.dataset.tow
      if (a === 'save') { switchTab(id); saveVersion(); towTab(id) }   // checkpoint to the sandbox, then close
      else if (a === 'go') towTab(id)
      close()
    })
  }

  // ── the wrecker — CLICK to tow the active tab (the obvious gesture); or DRAG it onto a specific tab to
  //    tow that one. (was drag-only — a plain click did nothing, so it read as "the wrecker doesn't work".) ──
  function wireWreckerDrag(wrecker) {
    wrecker.addEventListener('click', e => { e.stopPropagation(); e.preventDefault() })   // the mouseup does the work; the click just must not collapse the card
    wrecker.addEventListener('mousedown', e => {
      if (e.button !== 0 || wrecker.classList.contains('ghost')) return   // ghost → nothing to tow
      e.preventDefault(); e.stopPropagation()
      const sx = e.clientX, sy = e.clientY
      let moved = false
      document.body.style.userSelect = 'none'
      const ghost = document.createElement('img')
      ghost.src = 'cards/monaco/assets/wrecker.png'; ghost.className = 'mc-wrecker-ghost'
      ghost.style.left = sx + 'px'; ghost.style.top = sy + 'px'
      document.body.appendChild(ghost)
      const tabAt = ev => document.elementFromPoint(ev.clientX, ev.clientY)?.closest('.mc-tab, .mc-chip')   // (Sum 2026-07-09) tow a dock CHIP too, not just a main tab
      const clearMark = () => card.querySelectorAll('.mc-tab.tow-target').forEach(t => t.classList.remove('tow-target'))
      const move = ev => {
        if (Math.abs(ev.clientX - sx) > 4 || Math.abs(ev.clientY - sy) > 4) moved = true
        ghost.style.left = ev.clientX + 'px'; ghost.style.top = ev.clientY + 'px'
        clearMark()
        const t = tabAt(ev); if (t && card.contains(t)) t.classList.add('tow-target')
      }
      const up = ev => {
        document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up)
        document.body.style.userSelect = ''; ghost.remove(); clearMark()
        // (Sum 2026-07-11) a mousedown-on-wrecker + mouseup-on-tab fires a synthetic CLICK on the shared .card-head →
        //   which collapses the card. swallow that one click so the wrecker gets its "are you sure?" instead.
        if (moved) { const swallow = c => { c.stopPropagation(); c.preventDefault(); document.removeEventListener('click', swallow, true) }; document.addEventListener('click', swallow, true); setTimeout(() => document.removeEventListener('click', swallow, true), 350) }
        const t = tabAt(ev)
        if (moved && t && card.contains(t)) confirmTow(t.dataset.id, wrecker)   // DRAG → ask, then tow the tab under the cursor
        else if (!moved && activeId) confirmTow(activeId, wrecker)              // CLICK → ask, then tow the active tab
      }
      document.addEventListener('mousemove', move); document.addEventListener('mouseup', up)
    })
  }

  // ── 🟡 save a version → the active tab's rollback history (no disk write) ──
  function saveVersion() {
    const t = active(); if (!t || !editor) return
    pushHistory(t, editor.getValue())
  }

  // ── 🏁 save to device — the native saver, else a download fallback ────────
  async function saveToDevice() {
    const t = active(); if (!t || !editor) return
    const content = editor.getValue()
    // native: the file already auto-persists to ~/totoII/sandbox; 🏁 EXPORTS A COPY wherever the user picks,
    // via a real save panel through Rust (the webview has neither showSaveFilePicker nor <a download>).
    if (window.OZ_FS && window.OZ_FS.native) {
      const saved = await window.OZ_FS.exportCopy(t.filename, content)
      if (saved) { t.disk = content; pushHistory(t, content) }   // a copy is on disk + a rollback checkpoint
      return
    }
    if (window.showSaveFilePicker) {
      try {
        const h = await showSaveFilePicker({ suggestedName: t.filename })
        const w = await h.createWritable(); await w.write(content); await w.close()
        t.disk = content; pushHistory(t, content)            // 🟢 a copy is now on disk
      } catch (_) { /* the user cancelled the save dialog */ }
    } else {
      const a = document.createElement('a')
      a.href = URL.createObjectURL(new Blob([content], { type: 'text/plain' }))
      a.download = t.filename; a.click(); URL.revokeObjectURL(a.href)
      t.disk = content; pushHistory(t, content)              // 🟢 downloaded → on disk
    }
  }

  // flush the active editor content to the sandbox cache (used by the tab's launch button) → 🟡, returns the active tab
  function flushActiveToSandbox() {
    const t = active(); if (!t || !editor) return null
    const cur = editor.getValue()
    t.content = cur; t.cache = cur
    window.SANDBOX = window.SANDBOX || {}
    const prev = window.SANDBOX[t.filename] || {}
    window.SANDBOX[t.filename] = { kind: prev.kind || 'code', ext: prev.ext || t.ext, mime: prev.mime || '', data: cur }
    try { window.OZ_MAP && window.OZ_MAP.touch && window.OZ_MAP.touch(t.filename) } catch (_) {}   // (Sum 2026-07-12) re-lay THIS file's dependency arrows on every settled edit — keep the JIT map live
    mcJewel()
    return t
  }

  // ── ▶ RUN + 🟡🟢🔴 JEWELS + CONSOLE (Sum 2026-07-12): reads the file & runs it. html → the preview · py/js/sh →
  //    0z's sandboxed shell (OZ_CLI.run), stdout/stderr → the console. jewels: 🟡 edited · 🟢 running/ran-clean ·
  //    🔴 errored. click the jewels → the console; a run error opens it at the error. ──
  let _runState = 'idle'
  function setRun(s) {   // (Sum 2026-07-13) unlit = off · GREEN glows when there's something to run · RED glows while running · green restarts. No yellow.
    _runState = s
    const g = card && card.querySelector('.cj-g'), a = card && card.querySelector('.cj-a'), r = card && card.querySelector('.cj-r')
    if (g) { g.classList.toggle('lit', s === 'ok'); g.classList.remove('mc-run-pulse') }   // green jewel = ran clean (green restarts)
    if (a) a.classList.remove('lit')                              // never yellow
    if (r) { r.classList.toggle('lit', s === 'running' || s === 'error'); r.classList.remove('mc-run-pulse') }   // (Sum 2026-07-13) RED just ON while running / on a crash — NO pulse
    const go = card && card.querySelector('.mc-go'); if (go) go.classList.toggle('ready', s === 'dirty')   // the GREEN button glows when you've typed → "you can run now"
    const stop = card && card.querySelector('.card-stop'); if (stop) stop.classList.toggle('armed', s === 'running')
  }
  function mcStop() { setAutoRun(false); setRun('idle'); mcConsoleWrite('■ stopped\n', 'inf') }   // red = stop the run AND the auto loop (12s sandbox cap self-limits a runaway)
  // auto-run: yellow while you're mid-thought; the moment the line is COMPLETE (brackets balanced · ends on a newline ·
  //   the finished line isn't a continuation) and you pause → re-run → 🟢/🔴. Sum's "close bracket, enter, wait for green".
  let _autoT = null, _autoRun = false   // (Sum 2026-07-13) auto-run is GONE — running is MANUAL only (press green). _autoRun stays false forever.
  function setAutoRun(on) {   // green dome glows while the auto loop is live; hitting green turns it on, red turns it off
    _autoRun = !!on; try { localStorage.setItem('mc_autorun', on ? '1' : '0') } catch (_) {}
    const go = card && card.querySelector('.mc-go'); if (go) go.classList.toggle('on', _autoRun)
    const stop = card && card.querySelector('.card-stop'); if (stop) stop.classList.toggle('armed', _autoRun || _runState === 'running')
