// webview.js — the 👀 PREVIEW card. SIMPLE: Clappy (the clapperboard) opens a file picker; the
// picked file caches in window.SANDBOX and opens as a BLACK TAB over the curtain (name + a curtain
// close icon). closing a tab draws the curtain — removes that file from the sandbox cache. a 🖨️
// printer on the RIGHT exports the open tab: html · original · print (the native dialog handles
// pdf too — print or save-as-pdf). html runs in a sandboxed iframe; images show; else a cached note.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the preview GEAR — device width + the ....... search: "the preview GEAR"
//   the printer — export the OPEN tab. html / ... search: "the printer — export"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The preview card UI and sandbox iframe rendering. Exports
//    **`window.previewSandboxFile(name)` (line 140) to show a cached file,
//    **`window.previewRefreshFile(name)` (line 148) to re-render on edit, and registers the card
//    **builder at `window.CARD_BUILDERS.webview` (line 179).
//
//    **TOUCH HERE**
//    - Change device widths (phone/tablet/full) → `applyDevice()` L50, device buttons L200–202
//    - Change console error display → `paintErrs()` L56, error list HTML L59–62
//    - Change what file types show as what → `renderActive()` L94, the three branches L101–105
//    - Change export formats (html/original/print) → `exportAs()` L170, the three branches L173–175
//    - Change the demo file that auto-opens → `autoOpenDemo()` L251, fetch path L259, filename L255
//    - and L260–261
//    - Change the sandbox iframe attributes → line 209 `sandbox=` attribute
//    - Change error hook injected into previewed pages → `ERR_HOOK` L30–33
//
//    **TRAPS**
//    - `window.SANDBOX` is the persistent cache (lines 122, 132, 141, 171, 254, 260). Renaming it
//    - breaks `previewSandboxFile()` callers and user data already cached there.
//    - `active` (line 10) tracks the open tab name as a string key into `window.SANDBOX`. If you
//    - change how tabs are named or keyed, `renderActive()` L97 and `exportAs()` L171 will silently
//    - fail to find the file.
//    - The error hook (L30–33) must stay injected *before* the page's own `<style>` (line 38) so
//    - the dark background doesn't override user CSS. The order in `darkStage()` L35–42 matters.
//    - `_stopped` (line 14) and `errs` (line 13) are module state. `renderActive()` L96 resets
//    - both; `stopPreview()` L79 sets `_stopped = true`. If you add a third state variable, update
//    - `setJewels()` L67 to reflect it in the jewel display.
//    - The file picker (line 208) is hidden and clicked by the plus button (line 223). If you
//    - change the selector `.wv-file`, update line 229 too.
//    - `demoShown` (line 11) prevents the demo from opening twice per session. If you change the
//    - demo logic, keep this guard or it will spam-open.
//
//    **DO NOT**
//    - Don't move the error listener (lines 86–92) into the card builder; it must be a one-time
//    - global setup so all previewed pages report to the same `errs` array.
//    - Don't change `window.makeCard()` call (line 214) here; that's a different file. Same for
//    - `htmlNode()` (lines 182–209) — it's a utility.
//    - Don't add new module state variables without updating `setJewels()` L67 to display them.
//    - Don't rename `.wv-*` class names without updating the CSS file that styles them (not in this
//    - file).
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  let card = null
  let tabs = []      // file names opened here (a subset of window.SANDBOX)
  let active = null
  let demoShown = false   // reveal the demo philo page once per session, the first time PREVIEW opens
  let deviceW = 'full'    // preview gear: full · tablet (820) · phone (390) — eyeball responsive
  let errs = []           // console/runtime errors forwarded from the previewed page → the gear dot + red jewel
  let _stopped = false    // 🛑 stop halted the page (blanked the frame) — green jewel stays dark until ▶ go

  const esc  = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
  const escA = s => esc(s).replace(/"/g, '&quot;')

  // prep a previewed page for the frame. TWO fixes, both about the white void:
  //  1) LOCK the viewport. in a WKWebView subframe a page WITHOUT `maximum-scale=1, user-scalable=no`
  //     gets shrink-to-fit — WebKit scales the page down inside the frame and pads the leftover WHITE
  //     (it scales with the box, sits OUTSIDE any page CSS — that's the "buffer" you saw). colonialism
  //     ships that lock and fills; duality/snake omit it and letterbox. so we normalize EVERY page to the
  //     locked viewport → scale pinned to 1 → the page fills the frame edge to edge.
  //  2) fallback dark html bg, so a page that backgrounds only its <body> doesn't flash white in a corner.
  //     injected AFTER the viewport but a page that sets its own root bg still wins (its <style> comes later).
  // a tiny catcher injected FIRST into every previewed page: forwards runtime errors + console.error to
  // the parent (postMessage) so the gear's console dot lights red when the page throws. sandboxed frame →
  // this is the only way out. file:// (kind:'path') pages can't be injected, so they don't report (dot stays off).
  const ERR_HOOK = `<script>(function(){function s(m){try{parent.postMessage({__ozErr:String(m).slice(0,300)},'*')}catch(e){}}` +
    `addEventListener('error',function(e){s((e.message||'script error')+(e.filename?' @'+(e.lineno||0)+':'+(e.colno||0):''))});` +
    `addEventListener('unhandledrejection',function(e){s('promise: '+((e.reason&&e.reason.message)||e.reason))});` +
    `var _e=console.error;console.error=function(){s([].map.call(arguments,String).join(' '));try{_e.apply(console,arguments)}catch(x){}};})();</script>`

  function darkStage(html) {
    const vp = '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">'
    html = html.replace(/<meta\b[^>]*\bname=["']viewport["'][^>]*>/gi, '')   // drop the page's own viewport
    const inject = vp + ERR_HOOK + '<style>html{background:#0d0d12}</style>'
    if (/<head[^>]*>/i.test(html)) return html.replace(/<head[^>]*>/i, m => m + inject)
    if (/<html[^>]*>/i.test(html)) return html.replace(/<html[^>]*>/i, m => m + inject)
    return inject + html
  }

  function placeholder() {
    return `<!doctype html><body style="margin:0;height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;padding:24px;font:15px/1.6 system-ui;color:#8a8a8a;background:#0d0d12">
      <div>👀 preview<br><br>tap ＋ ↑ and pick a file —<br>it runs in a sandboxed frame.</div></body>`
  }

  // ── the preview GEAR — device width + the console dot (Sum 2026-07-10) ──
  function applyDevice(w) {
    deviceW = w
    if (card) card.style.setProperty('--wv-w', w === 'phone' ? '390px' : w === 'tablet' ? '820px' : '100%')
    const menu = card && card.querySelector('.wv-gear-menu')
    if (menu) menu.querySelectorAll('[data-dev]').forEach(b => b.classList.toggle('on', b.dataset.dev === w))
  }
  function paintErrs() {
    if (!card) return
    const gear = card.querySelector('.wv-gear'); if (gear) gear.classList.toggle('has-err', errs.length > 0)
    const list = card.querySelector('.wv-err-list')
    if (list) list.innerHTML = errs.length
      ? errs.slice(-8).map(m => `<div class="wv-err-row">⚠ ${esc(m)}</div>`).join('')
      : '<div class="wv-err-ok">no errors ✓</div>'
    setJewels()
  }
  // the jewels (Sum 2026-07-11): 🟢 solid = running clean · 🔴 = the page threw (check the gear for the log) · off = stopped.
  //   the red STOP glows .armed while a page is live. this is the wishlist: the jewels tell you if anything broke.
  function setJewels() {
    if (!card) return
    const g = card.querySelector('.cj-g'), a = card.querySelector('.cj-a'), r = card.querySelector('.cj-r'), stop = card.querySelector('.card-stop'), go = card.querySelector('.wv-go')
    const hasFile = !!(active && (window.SANDBOX || {})[active])
    const running = !_stopped && hasFile
    if (a) a.classList.remove('lit')
    if (g) g.classList.toggle('lit', running && errs.length === 0)
    if (r) r.classList.toggle('lit', errs.length > 0)
    if (stop) stop.classList.toggle('armed', running)   // red STOP glows only while a page is live to halt
    if (go) go.classList.toggle('on', hasFile)          // green glows when there's something to (re)start
  }
  // 🛑 STOP — halt the running page (blank the frame so its JS stops) + darken the jewels. ▶ go brings it back.
  function stopPreview() {
    _stopped = true
    const frame = card && card.querySelector('.wv-frame')
    if (frame) { frame.removeAttribute('src'); frame.srcdoc = '<!doctype html><body style="margin:0;height:100vh;background:#0d0d12"></body>' }
    setJewels()
  }
  // one parent-side listener for the whole session; module state (errs/card) lives in this closure.
  if (!window.__wvErrHook) {
    window.__wvErrHook = true
    window.addEventListener('message', e => {
      const d = e && e.data
      if (d && d.__ozErr != null) { errs.push(String(d.__ozErr)); errs = errs.slice(-20); paintErrs() }
    })
  }

  function renderActive() {
    const frame = card.querySelector('.wv-frame'); if (!frame) return
    _stopped = false; errs = []; paintErrs()   // ▶ render → live again + fresh error slate (the page's hook repopulates if it throws)
    const entry = active && (window.SANDBOX || {})[active]
    if (!entry || typeof entry.data !== 'string') { frame.removeAttribute('src'); frame.srcdoc = placeholder(); return }
    if (entry.kind === 'path') { frame.removeAttribute('srcdoc'); frame.src = entry.data; return }   // a real file → load via file:// (renders its own siblings/fonts accurately)
    frame.removeAttribute('src')
    if (/\.html?$/i.test(active)) frame.srcdoc = darkStage(window.bundleSandbox ? window.bundleSandbox(entry.data) : entry.data)   // inline siblings → multi-file renders; dark-stage the canvas
    else if (entry.kind === 'image' || /^data:image\//.test(entry.data))
      frame.srcdoc = `<!doctype html><body style="margin:0;height:100vh;display:grid;place-items:center;background:#111"><img src="${entry.data}" style="max-width:100%;max-height:100%;object-fit:contain"></body>`
    else
      frame.srcdoc = `<!doctype html><body style="margin:0;height:100vh;display:grid;place-items:center;font:14px system-ui;color:#9a9a9a;background:#0d0d12;text-align:center;padding:24px"><div>📄 ${esc(active)}<br><br>cached — not an html page to run.</div></body>`
  }

  function syncTabs() {
    const bar = card.querySelector('.wv-tabs'); if (!bar) return
    bar.innerHTML = tabs.map(n =>
      `<span class="wv-tab${n === active ? ' active' : ''}" data-n="${escA(n)}">
        <span class="wv-tab-name" title="${escA(n)}">${esc(n)}</span>
        <button class="wv-tab-x" data-n="${escA(n)}" title="close — draw the curtain, remove from the sandbox cache"></button>
      </span>`).join('')
  }

  function openFile(file) {
    const ext = (file.name.split('.').pop() || '').toLowerCase()
    const isImg = (file.type || '').startsWith('image/')
    const reader = new FileReader()
    reader.onload = () => {
      window.SANDBOX = window.SANDBOX || {}
      window.SANDBOX[file.name] = { kind: isImg ? 'image' : 'file', ext, mime: file.type, data: reader.result }
      if (!tabs.includes(file.name)) tabs.push(file.name)
      active = file.name
      syncTabs(); renderActive()
    }
    isImg ? reader.readAsDataURL(file) : reader.readAsText(file)
  }

  function closeTab(name) {
    try { delete (window.SANDBOX || {})[name] } catch (_) {}   // out of the sandbox cache
    tabs = tabs.filter(n => n !== name)
    if (active === name) active = tabs[tabs.length - 1] || null
    syncTabs(); renderActive()
  }

  // render a file that's ALREADY in the sandbox, by name (Monaco's 🎭 "show in preview" calls this) →
  // returns false if the preview isn't built yet, so the caller knows to open it first.
  window.previewSandboxFile = function (name) {
    if (!card || !name || !(window.SANDBOX || {})[name]) return false
    if (!tabs.includes(name)) tabs.push(name)
    active = name
    syncTabs(); renderActive()
    return true
  }
  // a write/edit changed a file — if the user is watching it here, re-render it live (no new tab).
  window.previewRefreshFile = function (name) { if (card && active === name) renderActive() }

  // ── the printer — export the OPEN tab. html / original = instant download; print = the native
  //    dialog (print to paper, or save as pdf from there). no png (the sandbox can't be canvas'd). ──
  function download(filename, data, mime) {
    let url, made = false
    if (/^data:/.test(data)) url = data
    else { url = URL.createObjectURL(new Blob([data], { type: mime || 'text/plain' })); made = true }
    const a = document.createElement('a'); a.href = url; a.download = filename
    document.body.appendChild(a); a.click(); a.remove()
    if (made) setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
  function printIt(entry) {
    const w = window.open('', '_blank')
    if (!w) return   // popup blocked — Sum's browser allows it on file://
    const isHtml = /\.html?$/i.test(active)
    w.document.open()
    w.document.write(isHtml ? entry.data
      : `<pre style="white-space:pre-wrap;font:13px/1.5 ui-monospace,monospace;padding:20px">${esc(entry.data)}</pre>`)
    w.document.close(); w.focus()
    setTimeout(() => w.print(), 300)   // let it render first
  }
  function exportAs(x) {
    const entry = active && (window.SANDBOX || {})[active]
    if (!entry || typeof entry.data !== 'string') return
    if (x === 'orig')       download(active, entry.data, entry.mime)
    else if (x === 'html')  download(active.replace(/\.[^.]+$/, '') + '.html', entry.data, 'text/html')
    else if (x === 'print') printIt(entry)
  }

  window.CARD_BUILDERS = window.CARD_BUILDERS || {}
  window.CARD_BUILDERS.webview = function buildWebview() {
    tabs = []; active = null
    // (Sum 2026-07-11) Clappy → ＋. same picker as Monaco's plus (import a file · image · screenshot into the sandbox).
    const plus  = htmlNode('<button class="wv-plus" title="import a file · image · screenshot into the sandbox">＋</button>')
    const tbar  = htmlNode('<span class="wv-tabs"></span>')
    const print = htmlNode(`<div class="wv-print-wrap">
        <button class="wv-print" title="save / print">🖨️</button>
        <div class="wv-print-menu">
          <button data-x="html">html</button>
          <button data-x="orig">original</button>
          <button data-x="print">print / pdf</button>
        </div>
      </div>`)
    // ▶ GREEN GO — start / restart: render the latest code (replaces the old refresh — Sum 2026-07-11: "green button
    //   handles it"). lives OUTSIDE .card-ctrls (added to the head below) so it survives collapse: start + stop only.
    const go = htmlNode('<button class="wv-go" title="run / restart — render the latest code + test your change"></button>')
    const gear = htmlNode(`<div class="wv-gear-wrap">
        <button class="wv-gear" title="preview settings — device width · console">${window.OZ_GEAR_SVG || '⚙'}</button>
        <div class="wv-gear-menu">
          <div class="wv-gear-sec">device width</div>
          <div class="wv-dev-row">
            <button data-dev="phone"  title="phone — 390px">📱</button>
            <button data-dev="tablet" title="tablet — 820px">📲</button>
            <button data-dev="full" class="on" title="full width">🖥️</button>
          </div>
          <div class="wv-gear-sec">console</div>
          <div class="wv-err-list"><div class="wv-err-ok">no errors ✓</div></div>
        </div>
      </div>`)
    const file  = htmlNode('<input type="file" class="wv-file" hidden>')
    const frame = htmlNode('<iframe class="wv-frame" sandbox="allow-scripts allow-forms allow-modals" referrerpolicy="no-referrer"></iframe>')
    // (Sum 2026-07-10) curtain icon BACK on the head — matches the drawer/topbar (curtain.png). the earlier
    // "curtains-on-curtains" call is reversed for the head standard: every card wears its icon in the same slot.
    // (Sum 2026-07-11) head: 🎭 curtain(icon) · ⚙ gear · ＋ plus · tabs · 🖨️ print · [▶ GREEN go · jewels · 🛑 red STOP].
    //   jewels + STOP come from makeCard; the green go is inserted just left of the jewels below (print sits left of go).
    card = window.makeCard({ id: 'webview', icon: 'cards/webview/curtain.png', title: 'PREVIEW', skin: 'p-webview', topbar: [plus, tbar, print], gear: gear, body: frame, jewels: true, stop: () => stopPreview(), bottom: 'cards/webview/assets/preview-bottom.png' })
    card.appendChild(file)
    // ▶ green go rides OUTSIDE .card-ctrls, just left of the jewels → it survives collapse (start + stop only)
    { const hd = card.querySelector('.card-head'), jw = hd && hd.querySelector('.card-jewels'); if (hd) hd.insertBefore(go, jw || null) }
    applyDevice('full')

    // controls stopPropagation so they don't start a card reorder-drag. NOT tbar — its empty curtain
    // space must reach the card head (click = collapse · drag = reorder); only real .wv-tabs are NODRAG.
    ;[plus, go, gear, print].forEach(el => el.addEventListener('mousedown', e => e.stopPropagation()))
    plus.addEventListener('click', e => { e.stopPropagation(); file.click() })
    go.addEventListener('click', e => { e.stopPropagation(); renderActive() })   // ▶ start/restart — render the latest code
    const gMenu = gear.querySelector('.wv-gear-menu'), gBtn = gear.querySelector('.wv-gear')
    gBtn.addEventListener('click', e => { e.stopPropagation(); gMenu.classList.toggle('open'); if (gMenu.classList.contains('open')) paintErrs() })
    gMenu.addEventListener('click', e => { e.stopPropagation(); const b = e.target.closest('[data-dev]'); if (b) applyDevice(b.dataset.dev) })
    document.addEventListener('click', e => { if (!e.target.closest('.wv-gear-wrap')) gMenu.classList.remove('open') })
    file.addEventListener('change', () => { if (file.files[0]) openFile(file.files[0]); file.value = '' })
    tbar.addEventListener('click', e => {
      const x = e.target.closest('.wv-tab-x'); if (x) { e.stopPropagation(); closeTab(x.dataset.n); return }
      const t = e.target.closest('.wv-tab');   if (t) { e.stopPropagation(); active = t.dataset.n; syncTabs(); renderActive(); return }
      // empty curtain space → let the click bubble to the head → collapse the card
    })
    const pMenu = print.querySelector('.wv-print-menu')
    print.querySelector('.wv-print').addEventListener('click', e => { e.stopPropagation(); pMenu.classList.toggle('open') })
    pMenu.addEventListener('click', e => {
      e.stopPropagation()
      const b = e.target.closest('button[data-x]'); if (!b) return
      pMenu.classList.remove('open'); exportAs(b.dataset.x)
    })
    document.addEventListener('click', e => { if (!e.target.closest('.wv-print-wrap')) pMenu.classList.remove('open') })

    renderActive()
    autoOpenDemo()
    return card
  }

  // when the PREVIEW card opens empty (first time this session): reveal the demo philo page (duality —
  // a real file → file://). NOTHING auto-opens on page load; you open the card first. seeds lazily.
  function autoOpenDemo() {
    if (tabs.length || demoShown) return
    demoShown = true
    window.SANDBOX = window.SANDBOX || {}
    if (window.SANDBOX['duality.html']) { if (window.previewSandboxFile) window.previewSandboxFile('duality.html'); return }
    // cache as TEXT (kind:'file' → srcdoc) so it runs through darkStage — which stamps the maximum-scale
    // lock that defeats WebKit's subframe shrink-to-fit. a kind:'path' load goes through oz:// and shrinks
    // just the same (and can't be injected). duality is self-contained, so nothing is lost off the protocol.
    fetch('cards/webview/duality.html').then(r => r.text()).then(t => {
      window.SANDBOX['duality.html'] = { kind: 'file', ext: 'html', mime: 'text/html', data: t }
      if (window.previewSandboxFile) window.previewSandboxFile('duality.html')
    }).catch(() => {})
  }
})()
