// transcript-mode.js — MULTI-SPEAKER MEETING TRANSCRIPT mode, available for ALL bots.
//
// The always-on EAR (nurse-ear.js) is a SINGLE-USER listener: it wakes to "hello nurse", accumulates one
// person's speech, and fires snippets at the nurse. THIS module is the other shape of listening — a room
// full of people, a diarizing source that tags each utterance with a speaker label (S1/S2/…), a VERBAL,
// ALL-PARTIES consent gate, and a per-speaker-change relay to a SMART bot that cleans the raw ASR into
// flowing prose live and at the end. Any registry bot can be the smart bot ("Nurse, take notes" /
// "Toto, sit in on this"). At END it persists the whole session to window.SANDBOX as markdown + JSON.
//
// ADDITIVE — touches NOTHING in nurse-ear.js / voice.js / workspace.js / conductor.js. It COOPERATES with
// OZ_EAR two ways, best-effort, without editing it:
//   1) SOURCE SHARING — it never opens a second mic. When a session starts it calls OZ_EAR.setSource with a
//      TEE adapter that (a) forwards every event to OZ_EAR's own feed (so OZ_EAR keeps working) but (b) also
//      copies every event into THIS module's feed. On end it restores OZ_EAR's auto-source.
//   2) SINGLE-USER SUSPEND — while a transcript session is live we set OZ_EAR.config.targetBot to a throwaway
//      so its snippet sends can't collide with ours, and restore it on end. (OZ_EAR has no hard "pause", so
//      we neutralize its send target rather than edit its code.)
// If OZ_EAR is absent we still run fully off OZ_TRANSCRIPT.feed(...) — the phone source can feed us directly.
//
// DIARIZATION CONTRACT: feed({ type:'final'|'partial'|'energy'|'speechstart'|'speechend', text?, level?, speaker? }).
// A 'final' whose speaker differs from the current speaker = a SPEAKER CHANGE (finalize + relay the prior turn).
// A 'final' with NO speaker label is DROPPED by default (config.trustUntaggedContinuation=false) — a diarizer
// emits null when it can't attribute a voice (often an unknown/unconsented person), so trusting it would leak.
// START/END are DIRECT-ADDRESS commands ("[Bot], take notes" / "[Bot], meeting is over"): the bot name must be
// adjacent to the phrase, so incidental mentions ("...the meeting is over budget...") never fire.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   CONFIG — every knob, sensible defaults. ....... search: "CONFIG — every knob,"
//   helpers / guards .............................. search: "helpers / guards"
//   REGISTRY: resolve a spoken BOT NAME → botId ... search: "REGISTRY: resolve a"
//   BAR RESOLVER — DOM query (window.bars is ...... search: "BAR RESOLVER — DOM"
//   THE SESSION ................................... search: "THE SESSION"
//   OZ_EAR COOPERATION — tee the shared source, ... search: "OZ_EAR COOPERATION"
//   PUBLIC: start a session targeting a bot ....... search: "PUBLIC: start a session"
//   PUBLIC: set an expected roster of names ....... search: "PUBLIC: set an expected"
//   CONSENT — parse the short verbal form, map .... search: "CONSENT — parse the"
//   RECORDING — accumulate per speaker; on ........ search: "RECORDING — accumulate"
//   FEED — the single event sink (shared source ... search: "FEED — the single event"
//   consent-line helper — feed a consent .......... search: "consent-line helper"
//   CLEANUP — hand the whole speaker-labeled ...... search: "CLEANUP — hand the"
//   PERSIST — SANDBOX markdown + JSON sibling + ... search: "PERSIST — SANDBOX"
//   END / CANCEL .................................. search: "END / CANCEL"
//   TICK — consent timeout only (recording has .... search: "TICK — consent timeout"
//   STATE snapshot ................................ search: "STATE snapshot"
//   PUBLIC API .................................... search: "PUBLIC API"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for multi-speaker meeting transcript
//    **capture with verbal consent, speaker diarization, live relay to a smart bot, and persistence
//    **to SANDBOX. It exports `window.OZ_TRANSCRIPT` with methods `start()`, `feed()`, `end()`,
//    **`cancel()`, `state()`, `roster()`, `consentLine()`, and live `config` object.
//
//    **TOUCH HERE**
//    - Change consent regex or word limits → `config` object L30–76 (consentRe L42, consentMaxWords
//    - L43, consentTimeoutMs L44, requireAllRoster L45)
//    - Change what gets relayed to the bot or how → `relayChunk()` L367, or
//    - `config.relayOnSpeakerChange` L50, `config.liveCleanup` L51
//    - Change redaction behavior (drop vs. mark unconsented speakers) → `config.redactMode` L48,
//    - `config.redactLabel` L47, and `finalizeCurrentTurn()` L336
//    - Change cleanup prompt or parsing → `config.cleanupTask` L63, `splitSummary()` L561
//    - Change where/how transcript persists → `persist()` L617, `config.persist` L54,
//    - `config.sandboxDir` L55, `config.alsoWriteJson` L56, `config.surfaceToNurseChart` L57
//    - Change bot resolution (how spoken names map to botIds) → `resolveBotFromText()` L102,
//    - `directCommand()` L118, `config.nameBlocklist` L37
//    - Change start/end/cleanup trigger phrases → `config.startPhrases` L32, `config.endPhrases`
//    - L33, `config.cleanupPhrases` L34
//    - Change spoken acknowledgments → `config.acks` L68–75
//    - Change consent timeout behavior → `tick()` L705, `config.requireAllRoster` L45
//
//    **TRAPS**
//    - `config.consentRe` (L42) is a regex that MUST capture the name in group `[1]` and the
//    - consent verb in group `[2]`; `tryConsent()` (L294) depends on this exact structure
//    - Session state machine (L172) has four states: 'consent' → 'recording' → 'finalizing' →
//    - 'idle'; `feed()` (L420) routes differently per state; changing state names breaks the
//    - routing at L440–441
//    - `S.turns[]` (L176) persists to SANDBOX as JSON (L631); adding/removing fields orphans old
//    - transcripts; if you add a field, update the safeTurns filter at L626
//    - Speaker diarization label `null` is a privacy boundary: `recordFinal()` (L389) treats null
//    - speaker as "unknown person, drop by default" (L392–402); `trustUntaggedContinuation` (L38)
//    - is the only override
//    - `_prevEarTarget` (L159) must be saved/restored in `suspendEar()` (L196) and `restoreEar()`
//    - (L215) as a pair; if OZ_EAR is absent, both are no-ops but the code must not crash
//    - `teeSource()` (L251) forwards events to BOTH OZ_EAR's emit AND `feed()` (L257); if you
//    - change the tee, OZ_EAR stops receiving events
//    - `finalizeCurrentTurn()` (L336) is called on speaker change (L411) AND at end (L676); if you
//    - add side effects, they fire twice per session
//    - `runCleanup()` (L504) returns a Promise; `persistAndFinish()` (L663) is called inside the
//    - `.then()` callback (L532); if you make cleanup synchronous, persist will fire before the bot
//    - replies
//    - `window.conduct()` (L514) is preferred over `OZ_VOICE.send()` (L543) because it captures the
//    - reply; if conduct is absent, cleanup is fire-only and `S.cleaned` stays empty (L544)
//    - Consent record (L175) and turns (L176) are both persisted; consent is the audit trail (who
//    - said what to opt in), turns are the recording; they are separate and both needed
//
//    **DO NOT**
//    - Do not add a second microphone or change how the source is acquired; that lives in
//    - `autoSharedSource()` (L223) and is intentionally minimal. If you need a different mic, that
//    - belongs in a separate module that feeds `OZ_TRANSCRIPT.feed()`.
//    - Do not edit `nurse-ear.js`, `voice.js`, `workspace.js`, or `conductor.js` to make this work;
//    - this file cooperates with OZ_EAR via `setSource()` and `config.targetBot` only (L195–202,
//    - L219).
//    - Do not move the PUBLIC API export (L743–754); it is the contract with callers.
//    - Do not change how `window.SANDBOX` is written (L622–633); that is the persistence contract
//    - with the workspace.
//    - Do not add UI affordances (buttons, modals) here; the file is intentionally headless. UI
//    - belongs in a card or toolbar module that calls `OZ_TRANSCRIPT.start()` and
//    - `OZ_TRANSCRIPT.state()`.
//    - Do not add a "pause recording" feature; the diarizer is the source of truth and this module
//    - has no way to pause it without editing the source itself.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'

  // ── CONFIG — every knob, sensible defaults. Live via window.OZ_TRANSCRIPT.config.* ────────────────────
  var config = {
    defaultBot: 'nurse',                                  // fallback smart bot if a spoken name can't resolve
    startPhrases: ['sit in on this', 'take notes', 'transcribe this', 'note this meeting'],
    endPhrases: ['meeting is over', 'end transcript', "that's a wrap"],
    cleanupPhrases: ['clean it up', 'clean this up', 'tidy this up'],   // optional mid-session full pass
    declinePhrases: ['no', "don't", 'do not', 'stop', 'cancel', 'not okay', 'i decline'],
    triggerWindow: 1,                                    // a trigger phrase must START within N words AFTER the bot name (tight direct-address: "Nurse, take notes" fires; "as nurse mentioned the meeting is over budget" does not)
    nameBlocklist: ['fully', 'hereby', 'really', 'truly', 'so', 'totally', 'absolutely', 'definitely', 'do', 'dont', 'not', 'sure', 'okay', 'yes', 'yeah', 'yep'],
    trustUntaggedContinuation: false,                    // PRIVACY: a 'final' with NO speaker label is NOT trusted as the current speaker (a diarizer emits null when it can't attribute a voice = often a NEW/unknown person). Default: drop.

    // consent: SHORT verbal form only. A long clinical/meeting sentence that merely contains 'agree'
    // mid-clause can NEVER be mistaken for consent (privacy defense).
    consentRe: /^\s*i[,]?\s+([a-z][a-z .'\-]{1,40}?)[,]?\s+(agree|consent)\b/i,
    consentMaxWords: 8,                                   // consent utterance must be short
    consentTimeoutMs: 60000,                              // wait this long for everyone to consent
    requireAllRoster: true,                               // if a roster was pre-set, all must consent before recording

    redactLabel: '[unconsented speaker]',                // non-consented turns → dropped or replaced
    redactMode: 'drop',                                  // 'drop' (omit) | 'mark' (replace text with redactLabel)

    relayOnSpeakerChange: true,                          // send each finalized turn to the smart bot as its own chunk
    liveCleanup: true,                                   // the smart bot may correct chunks into flow live (relay carries a task hint)
    echoRelay: false,                                    // OZ_VOICE.send echo flag — false = don't duplicate raw input display

    persist: true,                                       // write to SANDBOX on end
    sandboxDir: 'transcripts',                           // window.SANDBOX['transcripts/transcript-<ts>.md']
    alsoWriteJson: true,                                 // sibling .json with the structured session
    surfaceToNurseChart: true,                           // also drop a note into toto_notes (the clipboard chart)
    notesKey: 'toto_notes',
    notesFolder: 'transcripts',
    notesRolling: 24,                                    // keep at most this many transcript notes (localStorage quota guard)

    // cleanup framing handed to the smart bot at END (and on a "clean it up" ask)
    cleanupTask:
      'You are transcribing a meeting. Below is a speaker-tagged raw ASR transcript. ' +
      'Clean it into accurate, flowing prose. FIX obvious mis-hears FROM CONTEXT. Keep the [Name]: labels. ' +
      'Then add a short SUMMARY and a bulleted ACTION ITEMS list.',

    acks: {
      start: 'okay — sitting in. before we begin, everyone please say: I, your name, agree to this transcript.',
      consented: 'thanks',
      recording: 'got it — recording now.',
      declined: "okay, i won't write it down.",
      saved: 'transcript saved.',
      timeout: "i didn't hear everyone consent — i won't record."
    }
  }

  // ── helpers / guards ──────────────────────────────────────────────────────────────────────────────────
  function now() { return Date.now() }
  function norm(s) { return String(s == null ? '' : s).toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim() }
  function wordCount(s) { var n = norm(s); return n ? n.split(' ').length : 0 }
  function speak(t) { try { if (window.OZ_VOICE && window.OZ_VOICE.speak) window.OZ_VOICE.speak(t) } catch (_) {} }
  function log() { try { console.log.apply(console, ['[transcript]'].concat([].slice.call(arguments))) } catch (_) {} }

  // word-boundary phrase match — returns matched phrase or ''
  function wordMatch(text, phrases) {
    var w = ' ' + norm(text) + ' '
    for (var i = 0; i < phrases.length; i++) {
      var p = norm(phrases[i]); if (!p) continue
      if (w.indexOf(' ' + p + ' ') > -1) return phrases[i]
    }
    return ''
  }

  // ── REGISTRY: resolve a spoken BOT NAME → botId ───────────────────────────────────────────────────────
  function roster() {
    try { if (window.REG && Array.isArray(window.REG.agents)) return window.REG.agents } catch (_) {}
    try { if (Array.isArray(window.AGENTS_ROSTER)) return window.AGENTS_ROSTER } catch (_) {}
    return []
  }
  // find a bot whose id or label appears as a WHOLE WORD in the text. returns { id, matched } or null
  function resolveBotFromText(text) {
    var w = ' ' + norm(text) + ' '
    var list = roster()
    for (var i = 0; i < list.length; i++) {
      var a = list[i]; if (!a || !a.id) continue
      var names = [a.id, a.label].filter(Boolean)
      for (var j = 0; j < names.length; j++) {
        var n = norm(names[j]); if (!n) continue
        if (w.indexOf(' ' + n + ' ') > -1) return { id: a.id, matched: names[j] }
      }
    }
    return null
  }

  // a DIRECT-ADDRESS command: a bot name FOLLOWED (within triggerWindow words) by a trigger phrase. Rejects
  // incidental co-occurrence like "as nurse mentioned the meeting is over budget". Returns { botId, phrase } or null.
  function directCommand(text, phrases) {
    var toks = norm(text).split(' ').filter(Boolean)
    if (!toks.length) return null
    var list = roster()
    for (var bi = 0; bi < toks.length; bi++) {
      var botId = null
      for (var a = 0; a < list.length; a++) {
        var ag = list[a]; if (!ag || !ag.id) continue
        var names = [ag.id, ag.label].filter(Boolean)
        for (var n = 0; n < names.length; n++) { if (norm(names[n]) === toks[bi]) { botId = ag.id; break } }
        if (botId) break
      }
      if (!botId) continue
      var win = config.triggerWindow || 3
      for (var pi = 0; pi < phrases.length; pi++) {
        var pt = norm(phrases[pi]).split(' ').filter(Boolean); if (!pt.length) continue
        for (var st = bi + 1; st <= bi + 1 + win && st + pt.length <= toks.length; st++) {
          var ok = true
          for (var k = 0; k < pt.length; k++) { if (toks[st + k] !== pt[k]) { ok = false; break } }
          if (ok) return { botId: botId, phrase: phrases[pi] }
        }
      }
    }
    return null
  }

  // ── BAR RESOLVER — DOM query (window.bars is NOT exported per the map). ────────────────────────────────
  function resolveBar(botId) {
    try { if (window.bars && window.bars[botId]) return window.bars[botId] } catch (_) {}
    try {
      var el = document.querySelector('.agent-bar[data-agent="' + botId + '"]')
      if (el) return el
    } catch (_) {}
    try { if (window.getAgentBar) return window.getAgentBar(botId) } catch (_) {}
    return null
  }

  // ── THE SESSION ──────────────────────────────────────────────────────────────────────────────────────
  // states: 'idle' | 'consent' | 'recording' | 'finalizing'
  var S = null       // the live session object, or null
  var _timer = null
  var _prevEarTarget = null      // saved OZ_EAR.config.targetBot to restore on end
  var _earSuspended = false
  var _ownSource = null          // a source WE start (browser/dev path) when the ear isn't already listening

  function newSession(botId, opts) {
    opts = opts || {}
    var ts = now()
    return {
      id: 'transcript-' + ts.toString(36),
      title: opts.title || 'Meeting transcript',
      startedAt: new Date(ts).toISOString(),
      endedAt: null,
      botId: botId,
      state: 'consent',
      roster: [],           // [{ name, speaker }] — filled by consent (or a pre-set roster())
      preRoster: Array.isArray(opts.roster) ? opts.roster.slice() : [],   // expected names (optional)
      consent: [],          // [{ name, line, ts, speaker }]
      turns: [],            // [{ name, speaker, text, ts, raw }]
      cleaned: '',
      summary: '',
      actions: [],
      // live accumulation of the CURRENT speaker's utterance
      curSpeaker: null,
      curName: null,
      curText: '',
      curStartTs: 0,
      consentUntil: ts + config.consentTimeoutMs
    }
  }

  // ── OZ_EAR COOPERATION — tee the shared source, suspend single-user send (best-effort, additive) ──────
  function suspendEar() {
    try {
      var earOn = false
      try { earOn = !!(window.OZ_EAR && window.OZ_EAR.isOn && window.OZ_EAR.isOn()) } catch (_) {}
      // neutralize OZ_EAR's single-user target so its snippet sends can't collide with the meeting relay
      if (window.OZ_EAR && window.OZ_EAR.config && !_earSuspended) {
        _prevEarTarget = window.OZ_EAR.config.targetBot
        window.OZ_EAR.config.targetBot = '__transcript_suspend__'
        _earSuspended = true
      }
      if (earOn && window.OZ_EAR.setSource) {
        // the ear is ALREADY listening → tee its live source into us (never a 2nd mic)
        window.OZ_EAR.setSource(teeSource(autoSharedSource()))
      } else if (!_ownSource) {
        // ear off/absent → WE own a source so button/programmatic starts actually capture. (The real deployment
        // feeds via OZ_TRANSCRIPT.feed() from the phone over the pair pipe; this covers the browser/dev path.)
        _ownSource = autoSharedSource()
        try { _ownSource.start(function (evt) { try { feed(evt) } catch (_) {} }) } catch (_) {}
      }
    } catch (e) { log('suspendEar failed', e) }
  }
  function restoreEar() {
    try {
      if (_ownSource) { try { _ownSource.stop && _ownSource.stop() } catch (_) {} _ownSource = null }
      if (!window.OZ_EAR || !window.OZ_EAR.config) { _earSuspended = false; _prevEarTarget = null; return }
      if (_prevEarTarget != null) window.OZ_EAR.config.targetBot = _prevEarTarget
      _prevEarTarget = null
      _earSuspended = false
      // hand OZ_EAR back a clean auto-source (drop our tee)
      if (window.OZ_EAR.setSource) window.OZ_EAR.setSource(autoSharedSource())
    } catch (e) { log('restoreEar failed', e) }
  }
  // build the same auto-source OZ_EAR would (ozMic → SpeechRecognition → no-op). Kept minimal + guarded.
  function autoSharedSource() {
    try { if (window.ozMic) return window.ozMic } catch (_) {}
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (SR) {
      var rec = null
      return {
        start: function (emit) {
          try {
            rec = new SR(); rec.continuous = true; rec.interimResults = true; rec.lang = 'en-US'
            rec.onresult = function (e) {
              var interim = '', finals = ''
              for (var i = e.resultIndex; i < e.results.length; i++) {
                var r = e.results[i]; if (r.isFinal) finals += r[0].transcript; else interim += r[0].transcript
              }
              if (finals.trim()) emit({ type: 'final', text: finals })
              if (interim.trim()) emit({ type: 'partial', text: interim })
            }
            rec.onend = function () { try { rec && rec.start() } catch (_) {} }
            rec.onerror = function () {}
            rec.start()
          } catch (_) {}
        },
        stop: function () { try { if (rec) rec.stop() } catch (_) {} rec = null }
      }
    }
    return { start: function () {}, stop: function () {} }
  }
  // a TEE adapter: forwards every event to OZ_EAR's own feed AND mirrors it into OZ_TRANSCRIPT.feed.
  function teeSource(base) {
    return {
      start: function (emit) {
        try {
          base.start(function (evt) {
            try { emit(evt) } catch (_) {}          // OZ_EAR still gets it
            try { feed(evt) } catch (_) {}          // and so do we
          })
        } catch (e) { log('tee start failed', e) }
      },
      stop: function () { try { base.stop && base.stop() } catch (_) {} }
    }
  }

  // ── PUBLIC: start a session targeting a bot ───────────────────────────────────────────────────────────
  function start(botId, opts) {
    try {
      if (S && S.state !== 'idle') { log('a session is already live; ignoring start'); return false }
      var id = botId || config.defaultBot
      // if given a spoken phrase instead of an id, try to resolve a name
      if (id && !roster().find(function (a) { return a.id === id })) {
        var r = resolveBotFromText(id); if (r) id = r.id; else id = config.defaultBot
      }
      S = newSession(id, opts)
      suspendEar()
      startTimer()
      speak(config.acks.start)
      log('session started →', id, S.id)
      return true
    } catch (e) { log('start failed', e); return false }
  }

  // ── PUBLIC: set an expected roster of names (optional; enables require-all-consent) ───────────────────
  function rosterNames(names) {
    try {
      if (!S) return false
      S.preRoster = (names || []).map(String).filter(Boolean)
      return true
    } catch (_) { return false }
  }

  // ── CONSENT — parse the short verbal form, map speaker→name, add to roster ────────────────────────────
  // Returns the captured name or '' if not a valid consent.
  function tryConsent(text, speaker) {
    var t = String(text == null ? '' : text)
    if (wordCount(t) > config.consentMaxWords) return ''         // long sentence → never consent
    var m = config.consentRe.exec(t)
    if (!m) return ''
    var name = (m[1] || '').trim().replace(/\s+/g, ' ')
    if (!name) return ''
    // reject filler/adverb captures ('I fully agree' → 'fully', 'I hereby consent' → 'hereby') — not real names
    if (config.nameBlocklist && wordCount(name) === 1 && config.nameBlocklist.indexOf(norm(name)) > -1) return ''
    // tidy capitalization
    name = name.split(' ').map(function (w) { return w ? w[0].toUpperCase() + w.slice(1) : w }).join(' ')
    // record consent + tie the CURRENT diarization speaker label to this name (voice sample)
    S.consent.push({ name: name, line: t.trim(), ts: now(), speaker: speaker || null })
    if (!S.roster.find(function (r) { return r.name === name })) {
      S.roster.push({ name: name, speaker: speaker || null })
    } else if (speaker) {
      // update the mapping if the same name reconsents with a clear label
      var ex = S.roster.find(function (r) { return r.name === name }); if (ex && !ex.speaker) ex.speaker = speaker
    }
    return name
  }

  // is a diarization speaker label consented? (mapped to a roster name)
  function speakerConsented(speaker) {
    if (speaker == null) return null           // unknown label — treated as continuation, decided by caller
    var r = S.roster.find(function (x) { return x.speaker === speaker })
    return r ? r.name : null
  }

  // have all expected roster members consented? (gate for recording start)
  function allConsented() {
    if (!config.requireAllRoster) return S.consent.length > 0
    if (S.preRoster && S.preRoster.length) {
      return S.preRoster.every(function (nm) {
        return S.roster.some(function (r) { return norm(r.name) === norm(nm) })
      })
    }
    // no pre-set roster → proceed as soon as at least one person consents; others gated per-speaker at record time
    return S.consent.length > 0
  }

  // ── RECORDING — accumulate per speaker; on speaker change, finalize + relay the prior turn ────────────
  function finalizeCurrentTurn() {
    if (!S) return
    var text = (S.curText || '').trim()
    if (!text) { S.curText = ''; return }
    var speaker = S.curSpeaker
    var name = speakerConsented(speaker)

    var turn = {
      speaker: speaker || null,
      name: name || null,
      text: text,
      ts: S.curStartTs || now(),
      raw: text,
      consented: !!name
    }
    S.turns.push(turn)

    // REDACT unconsented speakers before any relay
    if (!name) {
      if (config.redactMode === 'mark') {
        turn.redacted = true
        relayChunk(config.redactLabel)   // note the redaction, no content (single-bracketed, matches the persisted form)
      }
      // 'drop' → say nothing to the bot
    } else {
      relayChunk('[' + name + ']: ' + text)
    }
    S.curText = ''
  }

  // fire-and-continue relay to the smart bot (never blocks the mic, never waits for the reply)
  function relayChunk(labeled) {
    if (!config.relayOnSpeakerChange) return
    try {
      var bar = resolveBar(S.botId)
      var id = S.botId
      if (bar && bar.dataset && bar.dataset.agent) id = bar.dataset.agent
      var payload = labeled
      if (config.liveCleanup) {
        // a light task hint so a live bot can correct the chunk into flow; kept short to not bloat context
        payload = labeled
      }
      if (bar && window.runTurn) {
        window.runTurn(bar, id, payload, { echo: config.echoRelay })   // honor echoRelay (OZ_VOICE.send forces echo:true)
      } else if (bar && window.OZ_VOICE && window.OZ_VOICE.send) {
        window.OZ_VOICE.send(bar, id, payload)     // fallback — fire and continue
      } else {
        log('no bar / OZ_VOICE — relay dropped:', payload)
      }
    } catch (e) { log('relay failed', e) }
  }

  // handle a diarized 'final' during recording
  function recordFinal(text, speaker) {
    var t = String(text == null ? '' : text).trim()
    if (!t) return
    if (speaker == null) {
      // PRIVACY: an untagged 'final' (no diarization label) is NOT trusted as the current speaker — a real
      // diarizer emits null exactly when it can't attribute a voice, which is often a NEW/unknown person.
      // Attributing it to the current consented speaker would leak a bystander under a real name → drop by default.
      if (config.trustUntaggedContinuation && S.curSpeaker != null && speakerConsented(S.curSpeaker)) {
        S.curText = S.curText ? (S.curText + ' ' + t) : t
        if (!S.curStartTs) S.curStartTs = now()
      } else {
        log('dropped untagged final (no speaker label)')
      }
      return
    }
    if (S.curSpeaker == null) {
      // first speaker
      S.curSpeaker = speaker; S.curName = speakerConsented(speaker); S.curText = t; S.curStartTs = now()
      return
    }
    if (speaker !== S.curSpeaker) {
      // SPEAKER CHANGE — finalize + relay the prior speaker, open the new one
      finalizeCurrentTurn()
      S.curSpeaker = speaker; S.curName = speakerConsented(speaker); S.curText = t; S.curStartTs = now()
      return
    }
    // same speaker continues
    S.curText = S.curText ? (S.curText + ' ' + t) : t
  }

  // ── FEED — the single event sink (shared source tees here; phone source feeds here directly) ──────────
  function feed(evt) {
    try {
      if (!evt || !evt.type) return
      if (evt.type === 'energy' || evt.type === 'speechstart' || evt.type === 'speechend') return
      if (evt.type !== 'final') return          // partials don't commit; consent + turns fire on finals

      var text = String(evt.text == null ? '' : evt.text)
      var speaker = evt.speaker == null ? null : evt.speaker
      if (!norm(text)) return

      // IDLE: a START trigger — DIRECT ADDRESS "[Bot], <start phrase>" — begins a session, targeting that bot.
      if (!S || S.state === 'idle') {
        var startCmd = directCommand(text, config.startPhrases)
        if (startCmd) start(startCmd.botId)
        return
      }

      // GLOBAL: an END trigger — "[Bot], <end phrase>" — ends the meeting from any state (direct-address only)
      if (directCommand(text, config.endPhrases)) { end(); return }

      if (S.state === 'consent') return handleConsent(text, speaker)
      if (S.state === 'recording') return handleRecording(text, speaker)
    } catch (e) { log('feed error', e) }
  }

  function handleConsent(text, speaker) {
    // a spoken decline ends the session without recording
    if (wordCount(text) <= config.consentMaxWords && wordMatch(text, config.declinePhrases)) {
      speak(config.acks.declined); cancel(); return
    }
    var name = tryConsent(text, speaker)
    if (name) {
      speak(config.acks.consented + ', ' + name + '.')
      if (allConsented()) {
        S.state = 'recording'
        S.curSpeaker = null; S.curName = null; S.curText = ''; S.curStartTs = 0
        speak(config.acks.recording)
      }
    }
    // a non-consent utterance during consent is ignored (not recorded) — privacy default
  }

  function handleRecording(text, speaker) {
    // mid-session full cleanup ask (bot name + clean phrase) — run a pass, keep recording
    if (directCommand(text, config.cleanupPhrases)) { runCleanup(false); return }
    // LATE CONSENT — a joiner who wasn't in the room at consent time can still opt in with the short
    // verbal form. It's parsed as consent (mapping speaker→name), NOT recorded as a spoken turn. This is
    // how a no-pre-roster meeting brings each additional speaker on board without dropping them forever.
    if (!speakerConsented(speaker)) {
      var name = tryConsent(text, speaker)
      if (name) {
        // a late consent closes any in-progress turn from a DIFFERENT speaker cleanly
        if (S.curSpeaker != null && S.curSpeaker !== speaker) finalizeCurrentTurn()
        speak(config.acks.consented + ', ' + name + '.')
        return
      }
    }
    recordFinal(text, speaker)
  }

  // ── consent-line helper — feed a consent utterance by hand (tests / a UI button) ──────────────────────
  function consentLine(text, speaker) {
    try {
      if (!S) return ''
      if (S.state !== 'consent') return ''
      return tryConsent(text, speaker) || ''
    } catch (_) { return '' }
  }

  // ── CLEANUP — hand the whole speaker-labeled raw transcript to the smart bot ───────────────────────────
  function buildRawTranscript() {
    var lines = []
    for (var i = 0; i < S.turns.length; i++) {
      var t = S.turns[i]
      if (!t.consented) {
        if (config.redactMode === 'mark') lines.push(config.redactLabel)
        continue                       // 'drop' omits entirely
      }
      lines.push('[' + (t.name || t.speaker || '?') + ']: ' + t.text)
    }
    return lines.join('\n')
  }

  // run the full cleanup pass. atEnd=true persists after. Returns a promise.
  function runCleanup(atEnd) {
    var raw = buildRawTranscript()
    if (!raw.trim()) { if (atEnd) persistAndFinish(); return Promise.resolve(null) }
    var prompt = config.cleanupTask + '\n\n----- RAW TRANSCRIPT -----\n' + raw + '\n----- END -----'

    // Prefer window.conduct (returns the reply text per the map); fall back to OZ_VOICE.send (fire-only).
    var bar = resolveBar(S.botId)
    var id = S.botId
    if (bar && bar.dataset && bar.dataset.agent) id = bar.dataset.agent

    if (window.conduct) {
      var ctrl = null
      try { ctrl = (typeof AbortController !== 'undefined') ? new AbortController() : null } catch (_) {}
      var ui = silentUI(bar)
      return Promise.resolve(
        window.conduct(id, prompt, ui, ctrl && ctrl.signal, 'ai')
      ).then(function (res) {
        try {
          if (res && res.text) {
            S.cleaned = String(res.text)
            var parsed = splitSummary(S.cleaned)
            S.summary = parsed.summary
            S.actions = parsed.actions
            if (parsed.body) S.cleaned = parsed.body
          } else if (res && res.error) {
            log('cleanup conduct error:', res.error)
          }
        } catch (e) { log('cleanup parse failed', e) }
        if (atEnd) persistAndFinish()
        return res
      }).catch(function (e) {
        log('cleanup conduct threw', e)
        if (atEnd) persistAndFinish()
        return null
      })
    }

    // no conduct — fall back to a fire-only send; the cleaned version lands in the bot's chat.
    try {
      if (bar && window.OZ_VOICE && window.OZ_VOICE.send) window.OZ_VOICE.send(bar, id, prompt)
      S.cleaned = ''       // we couldn't capture the reply; raw is persisted + a note explains
      log('cleanup sent via OZ_VOICE (reply not captured); persisting raw')
    } catch (e) { log('cleanup send failed', e) }
    if (atEnd) persistAndFinish()
    return Promise.resolve(null)
  }

  // a no-op UI sink for conduct (narration discarded; we only want the returned text)
  function silentUI(bar) {
    return {
      turn: function () { return { push: function () {}, seal: function () {} } },
      note: function () {},
      openCard: function () {}
    }
  }

  // best-effort split of a cleaned reply into { body, summary, actions[] }
  function splitSummary(txt) {
    var out = { body: txt, summary: '', actions: [] }
    try {
      var lines = String(txt).split(/\r?\n/)
      var mode = 'body', body = [], summary = [], actions = []
      for (var i = 0; i < lines.length; i++) {
        var ln = lines[i]
        var head = norm(ln)
        if (/^#{0,3}\s*summary\b/i.test(ln) || head === 'summary') { mode = 'summary'; continue }
        if (/^#{0,3}\s*action\s*items?\b/i.test(ln) || /^action items?$/i.test(head)) { mode = 'actions'; continue }
        if (mode === 'body') body.push(ln)
        else if (mode === 'summary') { if (ln.trim()) summary.push(ln.trim()) }
        else if (mode === 'actions') {
          var m = ln.replace(/^[\s\-\*•\d.\)]+/, '').trim()
          if (m) actions.push(m)
        }
      }
      out.body = body.join('\n').trim() || txt
      out.summary = summary.join(' ').trim()
      out.actions = actions
    } catch (_) {}
    return out
  }

  // ── PERSIST — SANDBOX markdown + JSON sibling + optional nurse-chart note ──────────────────────────────
  function markdown() {
    var lines = []
    lines.push('# ' + (S.title || 'Meeting transcript'))
    lines.push('')
    lines.push('- **Date:** ' + S.startedAt + (S.endedAt ? ' → ' + S.endedAt : ''))
    lines.push('- **Smart bot:** ' + S.botId)
    lines.push('- **Roster:** ' + (S.roster.map(function (r) { return r.name + (r.speaker ? ' (' + r.speaker + ')' : '') }).join(', ') || '—'))
    lines.push('')
    lines.push('## Consent record')
    if (S.consent.length) {
      S.consent.forEach(function (c) { lines.push('- ' + c.name + (c.speaker ? ' [' + c.speaker + ']' : '') + ': "' + c.line + '" — ' + new Date(c.ts).toISOString()) })
    } else { lines.push('- (none)') }
    lines.push('')
    lines.push('## Transcript')
    if (S.cleaned && S.cleaned.trim()) {
      lines.push(S.cleaned.trim())
    } else {
      lines.push(buildRawTranscript() || '(no consented turns)')
      lines.push('')
      lines.push('> _(raw ASR — the smart bot did not return a cleaned version; raw preserved.)_')
    }
    lines.push('')
    if (S.summary && S.summary.trim()) { lines.push('## Summary'); lines.push(S.summary.trim()); lines.push('') }
    if (S.actions && S.actions.length) {
      lines.push('## Action items')
      S.actions.forEach(function (a) { lines.push('- ' + a) })
      lines.push('')
    }
    return lines.join('\n')
  }

  function persist() {
    if (!config.persist) return
    var base = config.sandboxDir + '/' + S.id
    var md = markdown()
    try {
      if (window.SANDBOX) {
        window.SANDBOX[base + '.md'] = { kind: 'doc', ext: 'md', mime: 'text/markdown', data: md }
        if (config.alsoWriteJson) {
          // PRIVACY: the .json hits disk — redact BEFORE serializing (never persist unconsented turns; drop 'raw').
          var safeTurns = S.turns.filter(function (t) { return t.consented }).map(function (t) {
            return { name: t.name, speaker: t.speaker, text: t.text, ts: t.ts, consented: true }
          })
          var json = JSON.stringify({
            id: S.id, title: S.title, startedAt: S.startedAt, endedAt: S.endedAt, botId: S.botId,
            roster: S.roster, consent: S.consent, turns: safeTurns, cleaned: S.cleaned, summary: S.summary, actions: S.actions
          }, null, 2)
          window.SANDBOX[base + '.json'] = { kind: 'doc', ext: 'json', mime: 'application/json', data: json }
        }
        log('persisted →', base + '.md')
      } else { log('no SANDBOX — transcript not persisted to disk') }
    } catch (e) { log('SANDBOX write failed', e) }

    // also surface into the nurse's chart (toto_notes), rolling-window guarded
    if (config.surfaceToNurseChart) {
      try {
        var notes = []
        try { notes = JSON.parse(localStorage.getItem(config.notesKey) || '[]') } catch (_) { notes = [] }
        notes.push({
          folder: config.notesFolder,
          name: S.id,
          display: (S.title || 'Transcript') + ' — ' + new Date().toLocaleString(),
          on: false,
          body: md,
          owner: 'transcript-mode'
        })
        // rolling window: keep only the newest N transcript-folder notes
        var mine = notes.filter(function (n) { return n && n.folder === config.notesFolder })
        if (mine.length > config.notesRolling) {
          var drop = mine.slice(0, mine.length - config.notesRolling)
          notes = notes.filter(function (n) { return drop.indexOf(n) === -1 })
        }
        localStorage.setItem(config.notesKey, JSON.stringify(notes))
      } catch (e) { log('nurse-chart note failed (quota?)', e) }
    }
  }

  function persistAndFinish() {
    try { persist() } catch (e) { log('persist failed', e) }
    speak(config.acks.saved)
    var done = S
    teardown()
    log('finished', done && done.id)
  }

  // ── END / CANCEL ──────────────────────────────────────────────────────────────────────────────────────
  function end() {
    try {
      if (!S || S.state === 'idle' || S.state === 'finalizing') return false
      // flush the in-progress speaker's turn first
      finalizeCurrentTurn()
      // nothing consented → no artifact, no wasted conduct call: treat end as cancel
      if (!S.turns.some(function (t) { return t.consented })) {
        log('end with no consented turns → cancel (no junk transcript)')
        return cancel()
      }
      S.state = 'finalizing'
      S.endedAt = new Date().toISOString()
      stopTimer()
      restoreEar()
      // run the full cleanup pass, then persist inside the callback
      runCleanup(true)
      return true
    } catch (e) { log('end failed', e); try { persistAndFinish() } catch (_) {} return false }
  }

  function cancel() {
    try {
      if (!S) return false
      stopTimer(); restoreEar()
      log('cancelled', S.id)
      teardown()
      return true
    } catch (e) { log('cancel failed', e); teardown(); return false }
  }

  function teardown() { S = null; stopTimer() }

  // ── TICK — consent timeout only (recording has no auto-flush; speaker-change drives turns) ────────────
  function tick() {
    try {
      if (!S) return
      if (S.state === 'consent' && now() > S.consentUntil) {
        // if nobody consented → abort; if some did and requireAll is off → proceed to recording
        if (S.consent.length && !config.requireAllRoster) {
          S.state = 'recording'; speak(config.acks.recording)
        } else {
          speak(config.acks.timeout); cancel()
        }
      }
    } catch (e) { log('tick error', e) }
  }
  function startTimer() { stopTimer(); try { _timer = setInterval(tick, 500) } catch (_) {} }
  function stopTimer() { if (_timer) { try { clearInterval(_timer) } catch (_) {} _timer = null } }

  // ── STATE snapshot ────────────────────────────────────────────────────────────────────────────────────
  function stateSnapshot() {
    if (!S) return { state: 'idle', session: null }
    return {
      state: S.state,
      id: S.id,
      botId: S.botId,
      roster: S.roster.slice(),
      consentCount: S.consent.length,
      turns: S.turns.length,
      curSpeaker: S.curSpeaker,
      session: S
    }
  }

  // NOTE (2026-07-04): the old 📝 top-bar affordance button is REMOVED. Clicking it called start(), which spoke
  // the ack out loud ("mac started talking") and surprised Sum. Transcript is now a deliberate TOOL CARD
  // (cards/transcript/, 🗒️ in the deck) for pasted text — Summarize · Take notes · Make transcript. Live
  // multi-speaker meeting mode still begins from the SPOKEN trigger or a programmatic OZ_TRANSCRIPT.start(botId).
  // No auto-mounted button, no boot/scan/observer (they existed only to mount that button).

  // ── PUBLIC API ────────────────────────────────────────────────────────────────────────────────────────
  window.OZ_TRANSCRIPT = {
    start: start,                 // start(botId|spokenName, opts?) — begin a session
    roster: rosterNames,          // roster(names[]) — set expected participants (enables require-all-consent)
    feed: feed,                   // feed(evt) — push a diarized event { type, text?, speaker? }
    consentLine: consentLine,     // consentLine(text, speaker) — feed a consent utterance by hand
    end: end,                     // end() — finalize: cleanup + persist + "transcript saved"
    cancel: cancel,               // cancel() — abort, no persist
    state: stateSnapshot,         // → { state, roster, turns, session, ... }
    config: config,               // live knobs
    _resolveBot: resolveBotFromText,   // exposed for tests
    _session: function () { return S } // exposed for tests/inspection
  }
})()