// nurse-ear.js — the always-on NURSE EAR: a pluggable, backend-agnostic voice state machine bolted onto
// the nurse bar. It evolves the always-on-mic prototype (voice/oz-always-on-mic.html) into a real listener:
// ASLEEP (wake-word only, noise-gated) → AWAKE (accumulate + VAD-pause auto-send) → CONSENT (both parties
// say yes before it transcribes a conversation) → TRANSCRIBING. It flushes DISTINCT SNIPPETS as SEPARATE
// turns (each OZ_VOICE.send → runTurn queues via bar._turnQ), never blocking the mic while the bot thinks.
// A context-aware KIND-INTERRUPT reads the live per-bot meter (defensively) + an utterance timer, and —
// when it must — waits for a micro-pause and gently asks to "get this in" rather than hard-cutting.
//
// ADDITIVE: touches NOTHING in workspace.js / conductor.js / voice.js. It self-mounts a 👂 toggle next to
// the 🎤/🔈 controls (same MutationObserver spirit as voice.js) and drives everything through window.*
// globals (window.OZ_VOICE.send/speak, window.bars, window.engineHist, window.compileChart, window.ctxWindow).
//
// BACKEND-AGNOSTIC SOURCE: the ozbolt host (WKWebView) has NO SpeechRecognition + NO mic. The real STT is a
// FUTURE native whisper bridge exposed as window.ozMic. So the machine runs over a PLUGGABLE source adapter
// { start(emit), stop() } that emits {type:'partial'|'final'|'energy'|'speechstart'|'speechend', ...}. We
// auto-select ozMic → SpeechRecognition → no-op(mock), and OZ_EAR.feed(evt) lets tests push events by hand.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   CONFIG — every knob, sensible defaults. ....... search: "CONFIG — every knob,"
//   small guards / helpers ........................ search: "small guards / helpers"
//   LIVE CONTEXT READ — safe, ..................... search: "LIVE CONTEXT READ"
//   NURSE BAR RESOLVER — the ...................... search: "NURSE BAR RESOLVER"
//   SOURCE ADAPTERS ............................... search: "SOURCE ADAPTERS"
//   the emit sink — every source event lands ...... search: "the emit sink — every"
//   per-state handlers ............................ search: "per-state handlers"
//   transitions ................................... search: "transitions"
//   SEND — the CORE. flush current buffer as a .... search: "SEND — the CORE. flush"
//   the TICK — pause/auto-send, kind-interrupt, ... search: "the TICK"
//   lifecycle ..................................... search: "lifecycle"
//   TOGGLE UI — self-mount a 👂 near the 🎤/🔈, ...... search: "TOGGLE UI — self-mount"
//   PUBLIC API .................................... search: "PUBLIC API"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the always-on voice state machine that
//    **listens for wake words, accumulates speech into snippets, and sends them to the nurse bot.
//    **It exports `window.OZ_EAR` (line 499) with methods `start`, `stop`, `toggle`, `feed`,
//    **`send`, `setSource`, `startConversation`, `state`, and `config`. It depends on
//    **`window.OZ_VOICE.send/speak`, `window.bars`, `window.engineHist`, `window.compileChart`, and
//    **`window.ctxWindow` — but touches none of them.
//
//    **TOUCH HERE** —
//    - Change wake/sleep/send/transcribe trigger phrases → `config` object L21–43
//    - Change pause duration before auto-send → `config.pauseMs` L30
//    - Change idle timeout before sleep → `config.idleSleepMs` L31
//    - Change consent window duration → `config.consentTimeoutMs` L32
//    - Change interrupt leash or context meter threshold → `config.interruptAfterMs` L33,
//    - `config.contextWarnPct` L34
//    - Change bot voice responses (greeting/signoff/consent prompts) → `config` strings L38–42
//    - Change which bot receives snippets → `config.targetBot` L22
//    - Inject a mock/native STT source for testing → `OZ_EAR.setSource(adapter)` L446
//    - Manually send buffered text → `OZ_EAR.send()` L441
//    - Read live state (buffer, elapsed time, context %) → `OZ_EAR.state()` L453
//    - Start/stop listening or toggle → `OZ_EAR.start/stop/toggle()` L411, 421, 431
//    - Programmatically enter consent flow → `OZ_EAR.startConversation()` L435
//    - Push events by hand (tests) → `OZ_EAR.feed(evt)` L204
//
//    **TRAPS** —
//    - `ON_KEY` (L45) is persisted in localStorage; renaming it orphans user's saved on/off state.
//    - `M.state` (L124) must be one of exactly four strings: `'asleep'`, `'awake'`, `'consent'`,
//    - `'transcribing'`. The state machine in `onFinal()` (L234) and `tick()` (L350) hardcodes
//    - these; adding a state requires edits in both places.
//    - `config.targetBot` (L22) must match a real `data-agent` value in the DOM and a key in
//    - `window.bars`; if it doesn't exist, `resolveBar()` (L108) returns null and `flush()` (L309)
//    - silently drops the snippet (L334).
//    - `feed()` (L204) is the only entry point for STT events; if the source adapter never calls
//    - it, nothing happens.
//    - `tick()` (L350) runs every 250ms (L407); all timing logic (pause auto-send, idle sleep,
//    - interrupt leash, consent timeout) depends on this interval. Changing the interval breaks all
//    - durations.
//    - `flush()` (L309) calls `openFresh()` (L343) immediately after sending; if you remove that
//    - call, the buffer never clears and every send duplicates.
//    - `M.lastVoiceAt` (L129) and `M.lastActivityAt` (L130) are updated in `feed()` (L218) and
//    - `accumulate()` (L284); if you change when they're set, idle-sleep and pause detection break.
//    - `isAffirmative()` (L89) uses word-boundary matching AND a 4-word limit to prevent clinical
//    - sentences from triggering consent; both checks are load-bearing for privacy.
//    - `strip()` (L81) uses a regex to remove trigger phrases; if you call it with a phrase
//    - containing special regex chars, it will fail silently (the regex escape at L83 handles this,
//    - but only if you pass the phrase directly).
//
//    **DO NOT** —
//    - Do not rename `window.OZ_EAR` or its exported methods; external code (chips, hotkeys,
//    - voice.js) calls them by name.
//    - Do not move the `boot()` call (L481–496) or the `document.addEventListener` logic; it must
//    - run on page load to honor the persisted on/off state.
//    - Do not change the source adapter contract `{ start(emit), stop() }` without updating all
//    - three adapters: `noopSource()` L142, `ozMicSource()` L148, `srSource()` L169.
//    - Do not add state transitions outside `enterAwake()` L289, `enterConsent()` L294, `goSleep()`
//    - L300, or the inline assignments in `handleConsent()` L256; the state machine is fragile.
//    - Do not call `flush()` from inside `flush()` or `openFresh()`; it will recurse.
//    - Do not change the shape of `M` (L122) without updating `stateSnapshot()` L453 and any code
//    - that reads `M.*` directly.
//    - Do not add new global dependencies; this file must remain additive and not touch
//    - workspace.js, conductor.js, or voice.js.
//    - Do not move the `paintToggles()` no-op (L468) or the retired `addToggle()` (L470); they are
//    - intentionally stubbed out per the 2026-07-10 note.
//
//
//
//    ---
//
// END IC SHIP PASS

(function () {
  'use strict'

  // ── CONFIG — every knob, sensible defaults. Tweak live via window.OZ_EAR.config.* ──────────────────
  var config = {
    targetBot: 'nurse',                                             // which agent bar the snippets fire into
    wakePhrases: ['hello nurse', 'hey nurse', 'ok nurse'],          // ASLEEP → AWAKE
    sleepPhrases: ['thanks nurse', 'goodbye nurse', "that's all nurse"],
    sendPhrases: ['send that', 'send it now', 'okay send', 'nurse send'],   // manual flush (distinct from consent!)
    transcribePhrases: ['transcribe', 'take notes', 'write this down', 'record this', 'note this conversation'],
    affirmatives: ['yes', 'i agree', 'go ahead', 'sure', 'okay', 'yep', 'yeah', 'we do', 'i do'],

    noiseFloor: 0.06,                                               // energy below this = ignore partial/final (VAD gate)
    pauseMs: 2500,                                                  // silence gap that auto-sends the buffer (2000–3000)
    idleSleepMs: 45000,                                             // no activity this long → sleep
    consentTimeoutMs: 15000,                                        // wait for a yes before transcribing a convo
    interruptAfterMs: 30000,                                        // hard elapsed leash on one monologue
    contextWarnPct: 0.75,                                           // meter fraction that also trips the kind-interrupt
    flowGapMs: 1200,                                                // partials arriving faster than this = "good copy", extend
    leashBackoffMs: 8000,                                           // when flow is hot, how long to extend the leash
    mergeWindowMs: 0,                                               // 0 = distinct snippets; >0 = coalesce back-to-back sends
    greeting: "i'm here.",
    signoff: 'okay — i\'ll be here.',
    consentAsk: 'are you both okay with me writing this down? say yes.',
    consentDecline: "okay, i won't write it down. just us then.",
    interruptLine: 'buddy — let me get this in, pause a sec'
  }

  var ON_KEY = 'toto_ear_on'                                       // persisted 👂 on/off (default OFF; honor if left ON)

  // ── small guards / helpers ─────────────────────────────────────────────────────────────────────────
  function now() { return Date.now() }
  function lsGet(k) { try { return localStorage.getItem(k) } catch (_) { return null } }
  function lsSet(k, v) { try { localStorage.setItem(k, v) } catch (_) {} }
  function norm(s) { return String(s == null ? '' : s).toLowerCase().replace(/[^\w\s]/g, ' ').replace(/\s+/g, ' ').trim() }
  function wordCount(s) { var n = norm(s); return n ? n.split(' ').length : 0 }
  function speak(t) { try { if (window.OZ_VOICE && window.OZ_VOICE.speak) window.OZ_VOICE.speak(t) } catch (_) {} }

  // does normalized text CONTAIN any of the phrases (fuzzy-ish substring). returns the matched phrase or ''
  function firstMatch(text, phrases) {
    var n = norm(text)
    for (var i = 0; i < phrases.length; i++) { if (n.indexOf(norm(phrases[i])) > -1) return phrases[i] }
    return ''
  }
  // does normalized text contain any phrase on WORD boundaries (no mid-word/substring false hits, e.g.
  // 'yes' inside 'yesterday', or 'goodbye nurse' buried in a longer clinical sentence). returns matched phrase or ''
  function wordMatch(text, phrases) {
    var w = ' ' + norm(text) + ' '
    for (var i = 0; i < phrases.length; i++) {
      var p = norm(phrases[i]); if (!p) continue
      if (w.indexOf(' ' + p + ' ') > -1) return phrases[i]
    }
    return ''
  }
  // is a phrase present as a TRAILING/standalone command (for send-phrases we don't want mid-sentence false hits)
  function trailingMatch(text, phrases) {
    var n = norm(text)
    for (var i = 0; i < phrases.length; i++) {
      var p = norm(phrases[i]); if (!p) continue
      if (n === p || n.slice(-p.length - 1) === ' ' + p || n.slice(-p.length) === p) return phrases[i]
    }
    return ''
  }
  // strip the first occurrence of a phrase from text (used to peel the wake/send phrase out of the buffer)
  function strip(text, phrase) {
    if (!phrase) return text
    var re = new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+'), 'i')
    return text.replace(re, ' ').replace(/\s+/g, ' ').trim()
  }
  // affirmatives must be WORD-boundary matched (so 'the patient said yesterday' doesn't consent via 'yes'),
  // AND — for the privacy-sensitive consent gate — the utterance must be SHORT (a real answer, not a clinical
  // sentence that merely contains 'yes'/'sure'/'okay'). Long sentences never count as consent.
  function isAffirmative(text) { return wordCount(text) <= 4 && !!wordMatch(text, config.affirmatives) }

  // ── LIVE CONTEXT READ — safe, private-snapshot-free (per the map's "SAFEST APPROACH") ───────────────
  function readBotContext(botId) {
    try {
      var model = lsGet('toto_bot_' + botId + '_model') || ''
      var hist = []
      if (window.engineHist && window.engineHist.load) { try { hist = window.engineHist.load(botId) || [] } catch (_) {} }
      if (!hist.length) { try { hist = JSON.parse(lsGet('toto_hist_' + botId) || '[]') } catch (_) { hist = [] } }
      var histChars = hist.reduce(function (a, m) { return a + ('' + (m && m.content || '')).length }, 0)
      var sysChars = 0; try { sysChars = window.compileChart ? window.compileChart(botId).length : 0 } catch (_) {}
      var tok = Math.ceil((histChars + sysChars) / 4)
      var win = (window.ctxWindow ? window.ctxWindow(model) : 128000) || 128000
      var pct = Math.min(1, tok / win)
      return { tok: tok, win: win, pct: pct, ok: true }
    } catch (_) { return { tok: 0, win: 128000, pct: 0, ok: false } }   // degrade to timer-only
  }

  // ── NURSE BAR RESOLVER — the .agent-bar[data-agent="nurse"], guard if not mounted ────────────────────
  function resolveBar(botId) {
    botId = botId || config.targetBot
    try { if (window.bars && window.bars[botId]) return window.bars[botId] } catch (_) {}
    try {
      var el = document.querySelector('.agent-bar[data-agent="' + botId + '"]')
      if (el) return el
    } catch (_) {}
    return null
  }

  // ═══════════════════════════════════════════════════════════════════════════════════════════════════
  //  THE STATE MACHINE
  //  states: 'asleep' | 'awake' | 'consent' | 'transcribing'
  // ═══════════════════════════════════════════════════════════════════════════════════════════════════
  var M = {
    on: false,                    // is the ear enabled (👂)
    state: 'asleep',
    buf: '',                      // committed finals in the current snippet
    partial: '',                  // latest interim (not yet final)
    lastEnergy: 1,                // most recent loudness (default 1 = "audible" when no energy stream)
    haveEnergy: false,            // did the source ever send energy? (gate only applies if so)
    lastVoiceAt: 0,               // last time we saw voiced text/partial
    lastActivityAt: 0,            // last time anything happened (for idle-sleep)
    uttStartAt: 0,                // when the current monologue began (for the interrupt leash)
    leashUntil: 0,                // extended interrupt deadline when flow is hot
    consentUntil: 0,             // consent window deadline
    consentAsked: false,
    lastSendAt: 0,                // for mergeWindowMs coalescing
    source: null,                 // active adapter
    _timer: null                  // the pause/idle tick
  }

  // ── SOURCE ADAPTERS ─────────────────────────────────────────────────────────────────────────────────
  // Contract: { start(emit), stop() }. emit({type, ...}). We normalize whatever backend into this shape.
  function noopSource() {
    return { start: function () { try { console.log('[nurse-ear] no STT backend — mock-only (feed events via OZ_EAR.feed)') } catch (_) {} }, stop: function () {} }
  }

  // wrap a raw window.ozMic. It MAY already match the contract (ozMic.start(emit)/stop), or be a rawer object
  // exposing onpartial/onfinal/onenergy callbacks or an addEventListener surface. Adapt defensively.
  function ozMicSource(mic) {
    return {
      start: function (emit) {
        try {
          // best case: it already speaks our contract
          if (typeof mic.start === 'function' && mic.start.length >= 1) { mic.start(emit); return }
          // callback surface
          mic.onpartial = function (t) { emit({ type: 'partial', text: t }) }
          mic.onfinal = function (t) { emit({ type: 'final', text: t }) }
          mic.onenergy = function (l) { emit({ type: 'energy', level: l }) }
          mic.onspeechstart = function () { emit({ type: 'speechstart' }) }
          mic.onspeechend = function () { emit({ type: 'speechend' }) }
          if (typeof mic.start === 'function') mic.start()
          else if (typeof mic.listen === 'function') mic.listen()
        } catch (e) { try { console.log('[nurse-ear] ozMic start failed', e) } catch (_) {} }
      },
      stop: function () { try { if (typeof mic.stop === 'function') mic.stop() } catch (_) {} }
    }
  }

  // wrap SpeechRecognition/webkitSpeechRecognition into the contract (continuous, interim). No energy stream.
  function srSource(SR) {
    var rec = null
    return {
      start: function (emit) {
        try {
          rec = new SR(); rec.continuous = true; rec.interimResults = true; rec.lang = 'en-US'
          rec.onresult = function (e) {
            var interim = '', finals = ''
            for (var i = e.resultIndex; i < e.results.length; i++) {
              var r = e.results[i]
              if (r.isFinal) finals += r[0].transcript
              else interim += r[0].transcript
            }
            if (finals.trim()) emit({ type: 'final', text: finals })
            if (interim.trim()) emit({ type: 'partial', text: interim })
          }
          rec.onspeechstart = function () { emit({ type: 'speechstart' }) }
          rec.onspeechend = function () { emit({ type: 'speechend' }) }
          rec.onend = function () { try { if (M.on) rec.start() } catch (_) {} }   // keep it always-on
          rec.onerror = function () {}
          rec.start()
        } catch (e) { try { console.log('[nurse-ear] SR start failed', e) } catch (_) {} }
      },
      stop: function () { try { if (rec) rec.stop() } catch (_) {} rec = null }
    }
  }

  function autoSource() {
    try { if (window.ozMic) return ozMicSource(window.ozMic) } catch (_) {}
    var SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (SR) return srSource(SR)
    return noopSource()
  }

  // ── the emit sink — every source event lands here ────────────────────────────────────────────────────
  function feed(evt) {
    if (!evt || !evt.type) return
    if (evt.type === 'energy') { M.lastEnergy = +evt.level || 0; M.haveEnergy = true; return }
    if (evt.type === 'speechstart') { return }
    if (evt.type === 'speechend') { return }   // we drive pauses off the timer, not solely VAD hints

    if (evt.type === 'partial' || evt.type === 'final') {
      var text = String(evt.text == null ? '' : evt.text)
      // NOISE GATE: if energy is available and the latest sample is below the floor, drop it.
      if (M.haveEnergy && M.lastEnergy < config.noiseFloor) return
      // ignore empty / 1-word noise while ASLEEP (wake needs a real phrase); once awake, keep everything.
      if (M.state === 'asleep' && wordCount(text) < 2 && !wordMatch(text, config.wakePhrases)) return

      M.lastActivityAt = now()
      if (norm(text)) M.lastVoiceAt = now()

      if (evt.type === 'partial') { M.partial = text; onPartial(text) }
      else { M.partial = ''; onFinal(text) }
    }
  }

  // ── per-state handlers ────────────────────────────────────────────────────────────────────────────────
  function onPartial(text) {
    // partials keep the leash alive & feed flow detection; only committed on 'final'.
    if (M.state === 'awake' || M.state === 'transcribing') {
      // if a send-phrase shows up mid-partial we still wait for the final to actually flush (avoid double)
    }
  }

  function onFinal(text) {
    switch (M.state) {
      case 'asleep':   return handleAsleep(text)
      case 'consent':  return handleConsent(text)
      case 'awake':    return handleAwake(text)
      case 'transcribing': return handleAwake(text)   // same accumulation; TRANSCRIBING just labels intent
    }
  }

  function handleAsleep(text) {
    var wake = wordMatch(text, config.wakePhrases)
    if (!wake) return
    // WAKE
    M.uttStartAt = now(); M.leashUntil = 0
    var rest = strip(text, wake)                                    // peel the wake phrase out of the buffer
    // did they immediately ask to transcribe a conversation?
    if (firstMatch(rest, config.transcribePhrases)) { enterConsent(); return }
    enterAwake()
    if (norm(rest)) accumulate(rest)                               // whatever followed the wake word starts the buffer
  }

  function handleConsent(text) {
    if (isAffirmative(text)) {
      M.state = 'transcribing'; M.consentUntil = 0
      M.uttStartAt = now(); M.leashUntil = 0
      speak('thanks — writing it down now.')
      return
    }
    // any clear negative or timeout is handled in tick(); a non-yes utterance here just keeps waiting.
  }

  function handleAwake(text) {
    // MANUAL SEND phrase? (trailing/standalone only, distinct from consent affirmatives)
    var sendCmd = trailingMatch(text, config.sendPhrases)
    if (sendCmd) {
      var body = strip(text, sendCmd)
      if (norm(body)) accumulate(body)
      flush('manual')                                              // fire NOW; fresh buffer opens immediately
      return
    }
    // SLEEP phrase? Use TRAILING/standalone match (like send-phrases): 'we should say goodbye nurse to the
    // paper charts' must NOT sleep — only a real trailing 'goodbye nurse'/'thanks nurse' command does.
    if (trailingMatch(text, config.sleepPhrases)) { flush('sleep'); goSleep(); return }
    // otherwise accumulate this final into the current snippet
    accumulate(text)
  }

  function accumulate(text) {
    var t = String(text == null ? '' : text).trim()
    if (!t) return
    M.buf = M.buf ? (M.buf + ' ' + t) : t
    M.lastVoiceAt = now()
    if (!M.uttStartAt) M.uttStartAt = now()
  }

  // ── transitions ─────────────────────────────────────────────────────────────────────────────────────
  function enterAwake() {
    M.state = 'awake'; M.buf = ''; M.partial = ''
    M.uttStartAt = now(); M.leashUntil = 0; M.lastVoiceAt = now(); M.lastActivityAt = now()
    speak(config.greeting)
  }
  function enterConsent() {
    M.state = 'consent'; M.buf = ''; M.partial = ''
    M.consentUntil = now() + config.consentTimeoutMs; M.consentAsked = true
    M.lastActivityAt = now()
    speak(config.consentAsk)
  }
  function goSleep() {
    if (M.state === 'asleep') return
    M.state = 'asleep'; M.buf = ''; M.partial = ''
    M.uttStartAt = 0; M.leashUntil = 0; M.consentUntil = 0; M.consentAsked = false
    speak(config.signoff)
  }

  // ── SEND — the CORE. flush current buffer as a DISTINCT SNIPPET (its own turn), then open a fresh buffer
  //    IMMEDIATELY and keep listening. Never blocks the mic on the bot's reply. ──────────────────────────
  function flush(reason) {
    var text = (M.buf || '').trim()
    // fold in any live partial so an in-progress word isn't lost on a manual/interrupt send
    if (M.partial && M.partial.trim() && (reason === 'manual' || reason === 'interrupt')) {
      text = (text + ' ' + M.partial.trim()).trim()
    }
    // strip a stray trailing send/wake phrase defensively
    text = strip(text, trailingMatch(text, config.sendPhrases))
    if (!text) { openFresh(); return false }

    // optional coalescing: if mergeWindowMs>0 and we JUST sent, append instead of a new turn (off by default)
    if (config.mergeWindowMs > 0 && (now() - M.lastSendAt) < config.mergeWindowMs) {
      // best-effort merge is intentionally a no-op beyond the window guard here; distinct-snippet is the norm.
    }

    var bar = resolveBar(config.targetBot)
    var id = config.targetBot
    if (bar) { try { if (bar.dataset && bar.dataset.agent) id = bar.dataset.agent } catch (_) {} }

    var sent = false
    try {
      if (bar && window.OZ_VOICE && window.OZ_VOICE.send) {
        window.OZ_VOICE.send(bar, id, text)                        // → runTurn(...,{echo:true}) → queues via bar._turnQ
        sent = true
      } else {
        try { console.log('[nurse-ear] no nurse bar / OZ_VOICE — dropping snippet:', text) } catch (_) {}
      }
    } catch (e) { try { console.log('[nurse-ear] send failed', e) } catch (_) {} }

    M.lastSendAt = now()
    openFresh()                                                    // FRESH buffer + reset leash — keep talking
    return sent
  }

  function openFresh() {
    M.buf = ''; M.partial = ''
    M.uttStartAt = now(); M.leashUntil = 0
    M.lastVoiceAt = now(); M.lastActivityAt = now()
  }

  // ── the TICK — pause/auto-send, kind-interrupt, consent timeout, idle-sleep ──────────────────────────
  function tick() {
    if (!M.on) return
    var t = now()

    // CONSENT timeout → decline, drop to single-user AWAKE (no transcription)
    if (M.state === 'consent') {
      if (t > M.consentUntil) { speak(config.consentDecline); enterAwake() }
      return
    }

    // IDLE → sleep
    if ((M.state === 'awake' || M.state === 'transcribing')) {
      if (!M.buf && !M.partial && (t - M.lastActivityAt) > config.idleSleepMs) { goSleep(); return }
    }

    if (M.state === 'awake' || M.state === 'transcribing') {
      var gap = t - M.lastVoiceAt
      var haveBuf = !!(M.buf && M.buf.trim())

      // KIND-INTERRUPT check (elapsed leash OR context meter). Never mid-word: only at a micro-pause.
      // The two triggers are DISTINCT and must not share the hot-flow leash:
      //  • TIME leash — they're mid-good-copy; if flow is hot, extend the leash (give them slack).
      //  • CONTEXT pressure — extending the leash does NOTHING to relieve context; steady speech would keep
      //    it extended forever and it would never fire. So context is a HARD trigger: it fires at the very
      //    next micro-pause regardless of flow (still never mid-word).
      var elapsed = M.uttStartAt ? (t - M.uttStartAt) : 0
      var ctx = readBotContext(config.targetBot)
      var overTime = elapsed > config.interruptAfterMs
      var overCtx = ctx.ok && ctx.pct >= config.contextWarnPct
      var atPause = gap >= 300                                     // at a micro-pause, not mid-word

      // CONTEXT: hard trigger — fire at the next micro-pause, never leash-extended by hot flow.
      if (overCtx && haveBuf && atPause) {
        speak(config.interruptLine)
        flush('interrupt')
        return
      }
      // TIME: soft leash — if partials still arrive steadily (hot flow), extend; else interrupt at a pause.
      if (overTime && haveBuf) {
        var hotFlow = gap < config.flowGapMs
        if (hotFlow) {
          M.leashUntil = t + config.leashBackoffMs                 // keep listening; re-check next tick
        } else if (t >= (M.leashUntil || 0) && atPause) {
          speak(config.interruptLine)
          flush('interrupt')
          return
        }
      }

      // PAUSE auto-send: silence ≥ pauseMs with a non-empty buffer → send snippet, open fresh, keep listening
      if (haveBuf && gap >= config.pauseMs) {
        flush('pause')
        return
      }
    }
  }

  function startTimer() { stopTimer(); M._timer = setInterval(tick, 250) }
  function stopTimer() { if (M._timer) { clearInterval(M._timer); M._timer = null } }

  // ── lifecycle ─────────────────────────────────────────────────────────────────────────────────────────
  function start() {
    if (M.on) return
    M.on = true; M.state = 'asleep'; M.buf = ''; M.partial = ''
    M.lastActivityAt = now(); M.lastVoiceAt = now()
    lsSet(ON_KEY, '1')
    M.source = autoSource()
    try { M.source.start(feed) } catch (e) { try { console.log('[nurse-ear] source start failed', e) } catch (_) {} }
    startTimer()
    paintToggles()
  }
  function stop() {
    if (!M.on) return
    M.on = false
    try { if (M.source && M.source.stop) M.source.stop() } catch (_) {}
    M.source = null
    stopTimer()
    M.state = 'asleep'; M.buf = ''; M.partial = ''
    lsSet(ON_KEY, '0')
    paintToggles()
  }
  function toggle() { M.on ? stop() : start() }
  function isOn() { return M.on }

  // explicitly begin a consent-gated conversation transcription (e.g. from a chip)
  function startConversation() {
    if (!M.on) start()
    enterConsent()
  }

  // public send() — manual flush from a chip / hotkey; fires immediately, fresh buffer, keep listening.
  function publicSend() {
    if (M.state === 'asleep') return false                        // nothing buffered when asleep
    return flush('manual')
  }

  function setSource(adapter) {
    // swap the source adapter (mock/native). if running, restart onto the new one.
    try { if (M.source && M.source.stop) M.source.stop() } catch (_) {}
    M.source = adapter || noopSource()
    if (M.on) { try { M.source.start(feed) } catch (_) {} }
  }

  function stateSnapshot() {
    return {
      on: M.on, state: M.state, buffer: M.buf, partial: M.partial,
      elapsed: M.uttStartAt ? (now() - M.uttStartAt) : 0,
      context: readBotContext(config.targetBot)
    }
  }

  // ── TOGGLE UI — self-mount a 👂 near the 🎤/🔈, MutationObserver like voice.js ──────────────────────────
  function paintOne(btn) {
    if (!btn) return
    btn.textContent = M.on ? '👂' : '🚫'
    btn.classList.toggle('on', M.on)
    btn.title = M.on ? 'nurse ear ON — say "hello nurse"' : 'nurse ear OFF — click to always-listen for the wake word'
  }
  function paintToggles() { /* (Sum 2026-07-10) no-op — the head ear is retired; must NOT repaint voice.js's bottom-strip .ab-ear */ }

  function addToggle(bar) {
    // (Sum 2026-07-10) RETIRED — the nurse's always-on "Hello Nurse" wake-word ear used to mount a SECOND 👂 in the
    // HEAD, redundant with the universal 👂 push-to-talk ear voice.js already puts in every bot's bottom strip
    // (.ctx-voice) → "the nurse has two ears." it's non-functional in this webview anyway (no mic; needs the future
    // native whisper bridge, window.ozMic). the state machine + OZ_EAR/OZ_VOICE globals below still load
    // (transcript-mode depends on them) — only the redundant button is gone. TNG: fold the wake-word INTO the one
    // bottom-strip ear when the native mic lands, so there's a single 👂 that does push-to-talk AND always-on.
    return
  }

  function scan() { try { document.querySelectorAll('.agent-bar').forEach(addToggle) } catch (_) {} }
  function boot() {
    scan()
    var desk = document.getElementById('desk')
    if (desk && window.MutationObserver) {
      try { new MutationObserver(function () { scan() }).observe(desk, { childList: true, subtree: true }) } catch (_) {}
    }
    // honor the persisted toggle — if the user left the ear ON, auto-start always-listening on boot.
    if (lsGet(ON_KEY) === '1') { try { start() } catch (_) {} }
  }
  // boot only in a browser; under node-test there's no document, and the module stays feed()-drivable.
  try {
    if (typeof document !== 'undefined' && document.addEventListener) {
      if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot)
      else boot()
    }
  } catch (_) {}

  // ── PUBLIC API ────────────────────────────────────────────────────────────────────────────────────────
  window.OZ_EAR = {
    start: start,
    stop: stop,
    toggle: toggle,
    isOn: isOn,
    send: publicSend,
    setSource: setSource,
    feed: feed,
    startConversation: startConversation,
    state: stateSnapshot,
    config: config,
    _machine: M                                                    // exposed for tests/inspection (not for prod use)
  }
})()
