// lb-time.js — THE TIME-TOOLS BAR (Sum 2026-07-20: "time functions get their own bar")
// FOR HUMANS: one bar for the clock's time tools — the NEXT alarm, any countdowns to a date,
//   running timers, and a stopwatch. It shows one at a time, ticks it live every second, and
//   rotates through the ones you've toggled on. Tap a timer or the stopwatch to start/pause it.
// FOR AI:
//   1. reads localStorage: clock-alarms · clock-countdowns · clock-timers (built by cs-time.js)
//      + clock-time-on (which kinds show) + clock-timer-run / clock-stopwatch (live state here).
//   2. renders into #time-wrap with the shared .hl-bar look; gated by clock-widgets.time.
//   3. the ALARM here only DISPLAYS the next one — the firing engine + wake screen are #16.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   span a duration of ms into a human clause ... search: "span a duration of ms"
//   a countdown shown in whichever UNITS the .... search: "a countdown shown in"
//   the NEXT alarm across all that are on ....... search: "the NEXT alarm across"
//   build the live cards (one per toggled-on, ... search: "build the live cards"
//   TIMERS — a sequence of durations that can ... search: "TIMERS — a sequence of"
//   THE PHASE MACHINE — ONE source of truth, .... search: "THE PHASE MACHINE — ONE"
//   the bar — a rotating READOUT line; tap a .... search: "the bar — a rotating"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the live time-tools bar (alarms,
//    **countdowns, running timers, stopwatch). It exports `window.TIMER_ENGINE` (L185) and
//    **`window.TT_STOPTONE` (L119), and reads/writes localStorage keys: `clock-alarms`,
//    **`clock-countdowns`, `clock-timers`, `clock-timer-run`, `clock-stopwatch`, `clock-time-on`,
//    **`clock-time-every`, `clock-widgets`.
//
//    **TOUCH HERE** —
//    - Change which time tools display → `on()` L22 (reads `clock-time-on` from localStorage)
//    - Change how a countdown formats its remaining time → `inUnits()` L39 (consumes `c.units` or
//    - `c.unit` from countdown object)
//    - Change timer phase structure or add fields → `phases()` L98 (normalizes `tm.seq`, `tm.unit`,
//    - `tm.tone`, `tm.plays`)
//    - Change what sound plays at phase end → `ping()` L107 or `beep()` L203
//    - Change bar rotation speed → `every` variable L245 (reads `clock-time-every` from
//    - localStorage, in seconds)
//    - Change how time displays on the bar (font size, format) → `paint()` L217
//    - Change what happens when you tap a timer/alarm/countdown/stopwatch → click handler L226
//    - Change how often the bar updates → `setInterval` calls L235, L236, L244, L250
//
//    **TRAPS** —
//    - `lastPing` (L124) is a string key that prevents double-beeping; renaming it breaks the dedup
//    - logic at L146–147.
//    - Timer run state shape `{ startedAt, phase, pausedAt?, order? }` is persisted in
//    - `clock-timer-run` (L126, L143–144, L165–169, L177–182); changing field names orphans running
//    - timers.
//    - `phases()` (L98) normalizes both new `seq` format and legacy `dur`/`unit`/`tone` fields;
//    - removing legacy support breaks old timers.
//    - `orderOf()` (L104) must be called *before* using `run.order` to handle shuffle; L142
//    - re-shuffles each loop — order of operations matters.
//    - Pause logic (L131–133, L167, L181) freezes the clock at `pausedAt` and shifts `startedAt` on
//    - resume; the math at L134–135 depends on this shape.
//    - `timerState()` (L125) is called every frame by both the bar (L78) and the timer card; it
//    - advances the run and pings — both callers must run it to stay in sync.
//    - `rebuild()` (L216) is called every 5 seconds (L250) and on storage events (L251); if you add
//    - a new card kind, add it to `cards()` (L67) *and* to the click handler (L226).
//    - The bar's `aria-live="polite"` (L213) requires `srcEl` and `txtEl` to be updated together in
//    - `paint()` (L217–224) for screen readers.
//
//    **DO NOT** —
//    - Do not change the localStorage key names (`clock-*`) — they are the contract with cs-time.js
//    - and the settings card.
//    - Do not move the `window.TIMER_ENGINE` export (L185) or change its shape — the timer card
//    - depends on it.
//    - Do not change `P()` (L120) or the try/catch around `parent` — it handles iframe vs. window
//    - context for CHIPTUNE.
//    - Do not add new card kinds without updating both `cards()` (L67) and the click handler
//    - (L226).
//    - Do not change the `#time-wrap` element ID (L15) — it is the contract with the HTML.
//    - Do not move alarm-firing logic here — L9 says the firing engine is in #16 (a different
//    - file).
//    - Do not change how `J()` and `S()` work (L12–14) — they are the safe localStorage read/write
//    - primitives used everywhere.
//
//
//
//    ---
//
// END IC SHIP PASS


;(function () {
  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const S = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }
  const wrap = document.getElementById('time-wrap')
  if (!wrap) return
  try { if (JSON.parse(localStorage.getItem('clock-widgets') || '{}').timetools === false) { wrap.style.display = 'none'; return } } catch (_) {}

  const pad = n => String(n).padStart(2, '0')
  const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  const on = () => { const v = J('clock-time-on', 'null'); return Array.isArray(v) ? v : ['alarm', 'countdown', 'timer', 'stopwatch'] }   // stopwatch BACK (2026-07-21) — the readout rides here, the buttons live on its own card
  const h12 = d => { const h = d.getHours() % 12 || 12; return `${h}:${pad(d.getMinutes())} ${d.getHours() < 12 ? 'AM' : 'PM'}` }

  // ── span a duration of ms into a human clause ──
  function span(ms) {
    if (ms < 0) ms = 0
    const s = Math.floor(ms / 1000), d = Math.floor(s / 86400), h = Math.floor(s % 86400 / 3600), m = Math.floor(s % 3600 / 60), ss = s % 60
    if (d > 0) return `${d}d ${h}h ${m}m`
    if (h > 0) return `${h}:${pad(m)}:${pad(ss)}`
    return `${m}:${pad(ss)}`
  }

  // ── a countdown shown in whichever UNITS the user toggled (Sum 2026-07-20) — a breakdown from
  //    the largest chosen unit down, consuming the remainder (years+seconds → "2 years, 5,300,000
  //    seconds"). a legacy single unit still works; none picked → the smart span. ──
  const ORDER = ['years', 'months', 'weeks', 'days', 'hours', 'minutes', 'seconds']
  const UNIT_MS = { years: 31557600000, months: 2629800000, weeks: 604800000, days: 86400000, hours: 3600000, minutes: 60000, seconds: 1000 }
  function inUnits(ms, c) {
    const units = Array.isArray(c.units) ? c.units : (c.unit && c.unit !== 'auto' ? [c.unit] : [])
    const sel = ORDER.filter(u => units.includes(u))
    if (!sel.length) return span(ms)
    let rem = ms; const parts = []
    sel.forEach((u, i) => {
      const val = i === sel.length - 1 ? Math.round(rem / UNIT_MS[u]) : Math.floor(rem / UNIT_MS[u])
      rem -= val * UNIT_MS[u]
      parts.push(val.toLocaleString() + ' ' + (val === 1 ? u.replace(/s$/, '') : u))
    })
    return parts.join(', ')
  }

  // ── the NEXT alarm across all that are on — soonest future fire ──
  function nextAlarm() {
    const now = new Date(); let best = null
    J('clock-alarms', '[]').filter(a => a.on !== false).forEach(a => {
      const [h, m] = String(a.time || '0:0').split(':').map(Number)
      const push = d => { if (d > now && (!best || d < best.when)) best = { when: d, label: a.label } }
      if (a.date) push(new Date(`${a.date}T${pad(h)}:${pad(m)}:00`))
      else if (a.days && a.days.length) {
        for (let i = 0; i < 8; i++) { const d = new Date(now); d.setDate(now.getDate() + i); d.setHours(h, m, 0, 0); if (a.days.includes(d.getDay())) { push(d); break } }
      } else { const d = new Date(now); d.setHours(h, m, 0, 0); if (d <= now) d.setDate(d.getDate() + 1); push(d) }
    })
    return best
  }

  // ── build the live cards (one per toggled-on, populated item) ──
  function cards() {
    const out = [], kinds = on()
    if (kinds.includes('alarm')) {
      const n = nextAlarm()
      if (n) out.push({ kind: 'alarm', tap: true, src: 'next alarm ▸', live: () => `${h12(n.when)} · ${DAYS[n.when.getDay()]} ${MON[n.when.getMonth()]} ${n.when.getDate()}${n.label ? ' — ' + n.label : ''} · in ${span(n.when - Date.now())}` })
    }
    if (kinds.includes('countdown')) J('clock-countdowns', '[]').forEach(c => {
      const t = new Date(c.target + 'T' + (c.time || '00:00') + ':00')
      out.push({ kind: 'countdown', id: c.id, tap: true, src: 'countdown ▸', live: () => { const left = t - Date.now(); return left > 0 ? `${inUnits(left, c)} to ${c.label || c.target}` : `${c.label || c.target} — here` } })
    })
    if (kinds.includes('timer')) J('clock-timers', '[]').forEach(tm => {
      out.push({ kind: 'timer', id: tm.id, tap: true, src: 'timer ▸', live: () => timerText(tm) })
    })
    // STOPWATCH — a READOUT only (Sum: "take the button off the bar, just readout, buttons on cards").
    // the sealed stopwatch card publishes { running, since, banked } to clock-stopwatch; we derive the
    // live time from it. tapping the bar opens that card.
    if (kinds.includes('stopwatch')) out.push({ kind: 'stopwatch', tap: true, src: 'stopwatch ▸', live: () => {
      const s = J('clock-stopwatch', 'null')
      const ms = s ? (s.banked || 0) + (s.running ? Date.now() - s.since : 0) : 0
      return `${fmtHun(ms)}${s && s.running ? ' · running' : ms ? ' · paused · tap to open' : ' · tap to open'}`
    } })
    return out
  }
  const swRunning = () => { const s = J('clock-stopwatch', 'null'); return !!(s && s.running) }

  // ── TIMERS — a sequence of durations that can loop (Sum: "90, or 90 30 90") ──
  //    run state in clock-timer-run: { <id>: { startedAt, phase } } · tap toggles run/pause.
  // seq is [{n: name, d: duration}] — named phases (Sum: lunges/squats/rest, or poach an egg)
  // each phase carries its OWN unit + tone now; backfill from the old timer-level fields for legacy.
  // tone is an ARRAY now (several tones play in turn at the phase end); a legacy single tone
  // normalises up. `plays`: 'once' or 'repeat' (rings till dismissed).
  const phases = tm => (tm.seq || [{ n: '', d: tm.dur || 60 }]).map(p => (typeof p === 'number' ? { n: '', d: p } : p)).map(p => ({
    n: p.n || '', d: p.d, unit: p.unit || tm.unit || 'sec', plays: p.plays || 'once',
    tone: Array.isArray(p.tone) ? p.tone : [p.tone || tm.tone || 'beeps'],
  }))
  function seqMs(tm) { return phases(tm).map(p => p.d * (p.unit === 'min' ? 60000 : 1000)) }
  // shuffle → a run-order over the phase indices (Sum: "shuffle, that would be fun")
  function orderOf(tm, run) { if (run.order && run.order.length === phases(tm).length) return run.order; const o = phases(tm).map((_, i) => i); if (tm.shuffle) for (let i = o.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[o[i], o[j]] = [o[j], o[i]] } return o }
  // play a phase's tones in turn. 'repeat' loops the final one until stopTone() — any button on
  // the timer card calls that, so "till dismissed" means till you touch it.
  function ping(ph) {
    try {
      const t = P().CHIPTUNE || window.CHIPTUNE
      const tones = (ph && ph.tone) || []
      if (!t || !tones.length) return beep()
      tones.forEach((tone, i) => setTimeout(() => {
        const last = i === tones.length - 1
        try { t.play(tone, (last && ph.plays === 'repeat') ? { loop: true } : {}) } catch (_) {}
      }, i * 700))
    } catch (_) { try { beep() } catch (__) {} }
  }
  function stopTone() { try { (P().CHIPTUNE || window.CHIPTUNE).stop() } catch (_) {} }
  window.TT_STOPTONE = stopTone
  const P = () => { try { return parent } catch (_) { return window } }
  // ── THE PHASE MACHINE — ONE source of truth, shared by the bar and the timer CARD.
  //    It ADVANCES the run (rolls through elapsed phases, pings each turn) and returns structured
  //    state. Both callers run it every frame, so the ping is keyed to avoid a double beep.
  let lastPing = ''
  function timerState(tm) {
    const ph = phases(tm), run = J('clock-timer-run', '{}')[tm.id]
    const order0 = ph.map((_, i) => i)
    if (!run) return { running: false, done: false, paused: false, ph, step: 0, order: order0, total: ph.length, left: seqMs(tm)[0] || 0 }
    const seq = seqMs(tm), total = seq.length
    let order = orderOf(tm, run)
    // PAUSE (Sum 2026-07-21: "I need to grab water, ok 23 more seconds of my 1 minute plank").
    // A paused run freezes its clock at pausedAt, so `left` stops moving and the roll-forward
    // below can't fire. Resume shifts startedAt by the time you stood still — wall-clock, no drift.
    const nowT = run.pausedAt || Date.now()
    let step = run.phase || 0, left = seq[order[step]] - (nowT - run.startedAt)
    while (left <= 0) {
      step++
      if (step >= total) {
        if (!tm.loop) { clearRun(tm.id); return { running: false, done: true, paused: false, ph, step: total - 1, order, total, left: 0 } }
        step = 0; run.order = null
      }
      order = step === 0 ? orderOf(tm, {}) : order       // re-shuffle each loop
      const rr = J('clock-timer-run', '{}'); rr[tm.id] = { startedAt: Date.now(), phase: step, order }
      S('clock-timer-run', rr); run.startedAt = Date.now(); run.order = order
      left = seqMs(tm)[order[step]]
      const key = tm.id + ':' + step + ':' + run.startedAt
      if (lastPing !== key) { lastPing = key; ping(ph[order[step]]) }
    }
    return { running: !run.pausedAt, done: false, paused: !!run.pausedAt, ph, step, order, total, left }
  }
  function timerText(tm) {
    const st = timerState(tm)
    if (!st.running && !st.done) {
      const show = st.ph.map(p => (p.n ? p.n + ':' : '') + p.d + (p.unit === 'min' ? 'm' : 's')).join('·')
      return `${tm.label || 'timer'} — ${show}${tm.shuffle ? ' · shuffle' : tm.loop ? ' · loop' : ''} · tap to open`
    }
    if (st.done) return `${tm.label || 'timer'} — done ✓`
    const p = st.ph[st.order[st.step]], name = p && p.n ? p.n + ' — ' : ''
    return `${tm.label ? tm.label + ': ' : ''}${name}${fmtHun(st.left, true)}${st.total > 1 ? ` (${st.step + 1}/${st.total})` : ''}${tm.shuffle ? ' · shuffle' : tm.loop ? ' · loop' : ''}`
  }
  function clearRun(id) { const r = J('clock-timer-run', '{}'); delete r[id]; S('clock-timer-run', r) }
  // start · PAUSE · resume. (It used to `delete r[id]`, which threw your position away — stop
  // mid-plank and you came back to phase 1, full time. That was the whole bug behind "pause".)
  function toggleTimer(id) {
    const r = J('clock-timer-run', '{}'), run = r[id]
    if (!run) r[id] = { startedAt: Date.now(), phase: 0 }
    else if (run.pausedAt) { run.startedAt += Date.now() - run.pausedAt; delete run.pausedAt }   // resume
    else run.pausedAt = Date.now()                                                              // pause
    S('clock-timer-run', r)
  }
  // JUMP to the top of an interval — delta -1 · 0 (restart this one) · +1. Sum's rule: the run
  // state is preserved. Running keeps running from the top; paused stays paused so you can line
  // up the right interval and then hit go.
  function stepTimer(id, tm, delta) {
    const r = J('clock-timer-run', '{}')
    const total = phases(tm).length
    const run = r[id] || { startedAt: Date.now(), phase: 0, pausedAt: Date.now() }   // not started → land paused
    const next = Math.max(0, Math.min(total - 1, (run.phase || 0) + delta))
    run.phase = next
    run.startedAt = Date.now()
    if (run.pausedAt) run.pausedAt = run.startedAt        // paused: full interval showing, clock frozen
    r[id] = run; S('clock-timer-run', r)
  }

  window.TIMER_ENGINE = { phases, seqMs, timerState, toggleTimer, stepTimer, clearRun, fmt: (ms, f) => fmtHun(ms, f) }

  // AUTO UNITS — the same ladder the stopwatch card uses (Sum 2026-07-21): hundredths under an
  // hour, drop them at hours, drop seconds at days. No setting to keep in sync.
  function fmtHun(ms, forceCs) {
    ms = Math.max(0, ms)
    const total = Math.floor(ms / 1000)
    const d = Math.floor(total / 86400)
    const h = Math.floor((total % 86400) / 3600)
    const m = Math.floor((total % 3600) / 60)
    const s2 = total % 60
    if (d >= 1) return `${d}d ${pad(h)}:${pad(m)}`   // 'd' or a day reads exactly like an hour
    if (h >= 1) return `${h}:${pad(m)}:${pad(s2)}`
    return `${pad(m)}:${pad(s2)}` + (forceCs !== false ? '.' + pad(Math.floor(ms / 10) % 100) : '')
  }

  // a soft speaker beep for a timer phase end (WebAudio — no asset)
  let AC = null
  function beep() {
    AC = AC || new (window.AudioContext || window.webkitAudioContext)()
    const o = AC.createOscillator(), g = AC.createGain()
    o.frequency.value = 880; o.connect(g); g.connect(AC.destination)
    g.gain.setValueAtTime(0.0001, AC.currentTime); g.gain.exponentialRampToValueAtTime(0.3, AC.currentTime + 0.02)
    g.gain.exponentialRampToValueAtTime(0.0001, AC.currentTime + 0.4)
    o.start(); o.stop(AC.currentTime + 0.42)
  }

  // ── the bar — a rotating READOUT line; tap a timer to start/pause ──
  wrap.innerHTML = `<button class="hl-bar" aria-live="polite"><span class="hl-src">…</span><span class="hl-text">time tools</span></button>`
  const bar = wrap.querySelector('.hl-bar'), srcEl = wrap.querySelector('.hl-src'), txtEl = wrap.querySelector('.hl-text')
  let pool = [], idx = 0
  function rebuild() { pool = cards(); if (idx >= pool.length) idx = 0 }
  function paint() {
    if (!pool.length) { srcEl.textContent = ''; txtEl.textContent = 'no time tools yet — add one in ⚙ settings'; bar.dataset.tap = ''; return }
    const it = pool[idx]
    srcEl.textContent = it.src
    const t = it.live()
    txtEl.textContent = t
    txtEl.style.fontSize = t.length <= 48 ? '' : t.length <= 100 ? '24px' : '20px'   // '' = token default; shrink only long lines
    bar.dataset.tap = it.tap ? '1' : ''
  }
  bar.addEventListener('click', () => {
    const it = pool[idx]; if (!it) return
    if (it.kind === 'timer') { try { window.TM_CARD && window.TM_CARD.open(it.id) } catch (_) {} }   // the big card, right here in the clock
    else if (it.kind === 'alarm') { try { window.AL_CARD && window.AL_CARD.open() } catch (_) {} }
    else if (it.kind === 'countdown') { try { window.CD_CARD && window.CD_CARD.open(it.id) } catch (_) {} }
    else if (it.kind === 'stopwatch') { try { window.SW_CARD && window.SW_CARD.open() } catch (_) {} }   // the big card, right here in the clock
  })

  rebuild(); paint()
  setInterval(paint, 1000)                       // the shown item ticks live (alarms/countdowns)
  setInterval(() => {                            // fast tick — a running timer's countdown / the stopwatch
    const it = pool[idx]; if (!it) return
    if (it.kind === 'timer' && J('clock-timer-run', '{}')[it.id]) txtEl.textContent = it.live()
    else if (it.kind === 'stopwatch' && swRunning()) txtEl.textContent = it.live()
  }, 60)
  // ROTATE — the interval is a setting now (clock-time-every, seconds). Checked each tick rather
  // than baked into setInterval, so changing it in settings takes effect without a reload.
  let rotAt = Date.now()
  setInterval(() => {
    const every = Math.max(3, J('clock-time-every', '8')) * 1000
    if (Date.now() - rotAt < every) return
    rotAt = Date.now()
    if (pool.length > 1) { idx = (idx + 1) % pool.length; paint() }
  }, 500)
  setInterval(rebuild, 5000)                     // pick up new alarms/timers from settings
  window.addEventListener('storage', e => { if (e.key && e.key.indexOf('clock-') === 0) { rebuild(); paint() } })
})()
