// scroll-radio.js — THE PLUG. A newspaper with a soundtrack (Sum 2026-07-22).
//
// A self-contained tuner bean. One persistent <audio> (a JS object — NOT a DOM child,
// so the paper's render loop can't wipe it mid-song, per the dropped-clicks lesson), a
// genre dial of FREE, legal, https internet-radio streams (we TUNE a licensed
// broadcaster the way you'd pipe in local live radio — we host not one note), plus a
// LOCAL slot: paste your own town's station stream, the ultra-free dial.
//
// Doctrine (IC "the sync"): state lives in localStorage only (scroll-radio-*), no
// parent runtime is touched, and every glyph is drawn SVG — an svg crosses the native
// line, a codepoint gambles. Copy-clean for the port.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   the dial — name → a free, legal, https ...... search: "the dial — name → a"
//   drawn glyphs, no emoji (currentColor so ..... search: "drawn glyphs, no emoji"
//   the one persistent player (a JS object, ..... search: "the one persistent"
//   the dock — one node, bottom-left; content ... search: "the dock — one node,"
//   THE TUNER (Sum 2026-07-23 redesign): the .... search: "THE TUNER (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The radio tuner UI and playback engine for the Scroll newspaper. Owns the
//    **persistent `<audio>` element (line 68), the station dial (STATIONS, line 22), the My Music
//    **collection (stored as `scroll-radio-collection` in localStorage), and exports
//    **`window.SF_RADIO` (line 431) with methods `open()`, `tune(id)`, `stop()`, and `stations()`.
//
//    **TOUCH HERE**
//    - Add or remove a station → `STATIONS` array L22–45
//    - Change the volume curve (parabolic taper) → `volSlider()` L73 and the squaring at L367
//    - Change play modes (normal/repeat/shuffle) → `MODES` array L88
//    - Change the UI layout or add a button → `playerHTML()` L219 or `overlayHTML()` L266
//    - Change what happens on a click → the delegated handler at L318–361
//    - Change localStorage keys (e.g. `scroll-radio-*`) → search and replace all occurrences; they
//    - are load-bearing
//    - Hide/show the dock from outside → `applyHidden()` L426 (reads `scroll-radio-hidden`)
//    - Let another script tune the radio → call `window.SF_RADIO.tune(id)` L433
//
//    **TRAPS**
//    - `localStorage` keys are persisted user state: `scroll-radio-last` (current station),
//    - `scroll-radio-collection` (My Music tracks), `scroll-radio-vols` (volume slider position),
//    - `scroll-radio-mode` (play mode). Renaming or changing the shape of `scroll-radio-collection`
//    - entries will orphan existing playlists.
//    - The `audio` object (L68) is NOT a DOM child — it lives in JS only so the render loop cannot
//    - wipe it mid-song. Never move it into the DOM or into `dock.innerHTML`.
//    - `paint()` (L303) is the only place the UI redraws. It must be called after every state
//    - change or the UI will not update.
//    - `CUR` (L75) holds the current station ID; it must match a key in `STATIONS`, or be `'mine'`
//    - or `'local'`, or `byId()` (L162) will return null and `tune()` will fail silently.
//    - The volume is stored as slider position `s` in `scroll-radio-vols` but played as `s²` (L367,
//    - L74). If you change the curve, both places must change together.
//    - `COLL` and `CIDX` (L76) are the My Music playlist and track index. If you delete a track at
//    - index `i` while `i === CIDX`, you must call `stop()` and reset `CIDX` (see L347–348).
//    - Drag-to-trash uses `DRAGN` (L78) to arm the delete; the confirm bar only appears if
//    - `PENDING_DEL >= 0` (L273). The file is not actually deleted until "trash it" is clicked
//    - (L343).
//    - `OV` (L207) controls which overlay is shown (`''`, `'stations'`, or `'playlist'`). It does
//    - not auto-close on outside click (L412–414); only the close bar (L288, L300) or `closeov`
//    - action (L336) closes it.
//
//    **DO NOT**
//    - Do not add DOM nodes to `dock` directly; always rebuild via `paint()` and `innerHTML`.
//    - Do not store state outside `localStorage` or the module's local variables; the render loop
//    - will wipe it.
//    - Do not rename `window.SF_RADIO` or its exported methods without updating the seam comment
//    - (L430).
//    - Do not change the SVG icon strings in `ICO` (L48–65) without testing in the actual skin
//    - (they use `currentColor`).
//    - Do not add new localStorage keys without documenting them in the header comment (L9).
//    - Do not move the `audio` event listeners (L186–189, L396–404) or the delegated click handler
//    - (L318) into `paint()`; they must persist across repaints.
//    - CSS, HTML structure, and the dock's role/aria attributes belong in a separate stylesheet and
//    - should not be hardcoded here.
//    - The Tauri integration (`window.parent.__TAURI__`) for file picking and folder scanning
//    - (L126, L139) is platform-specific; do not assume it exists (see the guards at L127, L140).
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  if (window.SF_RADIO) return

  const J = (k, d) => { try { const v = JSON.parse(localStorage.getItem(k)); if (v != null) return v } catch (_) {}
                        try { return typeof d === 'string' ? JSON.parse(d) : d } catch (_) { return d } }   // accepts a STRING default ('[]') or a VALUE default ([]) — never throws
  const esc = s => { const d = document.createElement('div'); d.textContent = String(s == null ? '' : s); return d.innerHTML }

  // ── the dial — name → a free, legal, https stream (a tuner, not a host) ──
  // classical · oldies · show-tune-ish lounge (Sum's asks), plus americana/ambient/eclectic.
  const STATIONS = [
    { id: 'classical', name: 'Classical', by: 'Classical MPR',           url: 'https://cms.stream.publicradio.org/cms.mp3' },
    { id: 'oldies',    name: 'Oldies',    by: 'SomaFM · Left Coast 70s', url: 'https://ice1.somafm.com/seventies-128-mp3' },
    { id: 'lounge',    name: 'Lounge',    by: 'SomaFM · Illinois St.',   url: 'https://ice1.somafm.com/illstreet-128-mp3' },
    { id: 'americana', name: 'Americana', by: 'SomaFM · Boot Liquor',    url: 'https://ice1.somafm.com/bootliquor-128-mp3' },
    { id: 'ambient',   name: 'Ambient',   by: 'SomaFM · Groove Salad',   url: 'https://ice1.somafm.com/groovesalad-128-mp3' },
    { id: 'eclectic',  name: 'Eclectic',  by: 'Radio Paradise',          url: 'https://stream.radioparadise.com/mp3-128' },
    // the non-trad shelf (Sum 2026-07-22: "add more non-trad channels")
    { id: 'spy',       name: 'Spy Jazz',  by: 'SomaFM · Secret Agent',   url: 'https://ice1.somafm.com/secretagent-128-mp3' },
    { id: 'space',     name: 'Deep Space', by: 'SomaFM · Deep Space One', url: 'https://ice1.somafm.com/deepspaceone-128-mp3' },
    { id: 'eighties',  name: 'Under. 80s', by: 'SomaFM · Underground 80s', url: 'https://ice1.somafm.com/u80s-128-mp3' },
    { id: 'beats',     name: 'Beats',     by: 'SomaFM · Fluid',          url: 'https://ice1.somafm.com/fluid-128-mp3' },
    { id: 'reggae',    name: 'Reggae',    by: 'SomaFM · Heavyweight',     url: 'https://ice1.somafm.com/reggae-128-mp3' },
    { id: 'mellow',    name: 'Mellow',    by: 'Radio Paradise · Mellow', url: 'https://stream.radioparadise.com/mellow-128' },
    // electronica shelf (Sum 2026-07-22: "electronica, drum and bass or jungle") — free https SomaFM streams
    { id: 'idm',       name: 'IDM',       by: 'SomaFM · cliqhop',        url: 'https://ice1.somafm.com/cliqhop-128-mp3' },
    { id: 'dubstep',   name: 'Dubstep',   by: 'SomaFM · Dub Step Beyond', url: 'https://ice1.somafm.com/dubstep-128-mp3' },
    { id: 'downtempo', name: 'Downtempo', by: 'SomaFM · Beat Blender',   url: 'https://ice1.somafm.com/beatblender-128-mp3' },
    { id: 'proghouse', name: 'Prog House', by: 'SomaFM · The Trip',       url: 'https://ice1.somafm.com/thetrip-128-mp3' },
    { id: 'dnb',       name: 'Drum & Bass', by: 'BassDrive (http)',         url: 'http://ice.bassdrive.net/stream' },
    // (Bandcamp + Archive split-stations were CUT 2026-07-23 with 0z Curated — Sum's Plug redesign: the
    //  Plug is licensed streams + My Music, not a browse-out doorway. "browse + own" belongs in the PSV,
    //  the ads studio carries the "pay the artists" pitch now.)
  ]

  // ── drawn glyphs, no emoji (currentColor so they take the skin) ──
  const ICO = {
    plug: '<svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true"><path fill="currentColor" d="M12 1.3c-2.8 2.1-4.3 5.2-4.3 8.6 0 3.7 1.8 6.4 4.3 6.4s4.3-2.7 4.3-6.4c0-3.4-1.5-6.5-4.3-8.6z"/><g fill="rgba(0,0,0,.24)"><rect x="8.8" y="7.2" width="6.4" height="1" rx=".5"/><rect x="8.3" y="9.8" width="7.4" height="1" rx=".5"/><rect x="8.8" y="12.4" width="6.4" height="1" rx=".5"/></g><rect x="11.1" y="14.6" width="1.8" height="6.2" rx=".9" fill="currentColor"/><ellipse cx="12" cy="21" rx="4" ry="1.3" fill="currentColor"/></svg>',
    play:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7z"/></svg>',
    pause: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor" aria-hidden="true"><rect x="6" y="5" width="4" height="14"/><rect x="14" y="5" width="4" height="14"/></svg>',
    stopbtn: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="1.5"/></svg>',
    speaker: '<svg viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true"><path fill="currentColor" d="M4 9v6h4l5 4V5L8 9H4z"/><path fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" d="M15.5 9.2a4 4 0 0 1 0 5.6M18 7a7.2 7.2 0 0 1 0 10"/></svg>',
    trash: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 7h16M9 7V4.5A1.5 1.5 0 0 1 10.5 3h3A1.5 1.5 0 0 1 15 4.5V7M6.5 7l1 13h9l1-13"/><path d="M10 11v6M14 11v6"/></svg>',
    prev:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M7 5v14h2V5H7zm3 7l9 7V5l-9 7z"/></svg>',
    next:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M15 5v14h2V5h-2zM5 19l9-7-9-7v14z"/></svg>',
    shuffle: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 5h3.5l9 14H20M16.5 5H20M4 19h3.5l3-4.7"/><path d="M17.5 3 20 5l-2.5 2M17.5 17l2.5 2-2.5 2"/></svg>',
    loop:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12a6 6 0 0 1 6-6h8M4 12a6 6 0 0 0 6 6h8"/><path d="M15.5 3 18 6l-2.5 3M8.5 21 6 18l2.5-3"/></svg>',
    loop1: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12a6 6 0 0 1 6-6h8M4 12a6 6 0 0 0 6 6h8"/><path d="M15.5 3 18 6l-2.5 3M8.5 21 6 18l2.5-3"/><path d="M11.2 10.2l1.6-1v6" stroke-width="2"/></svg>',
    through: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 12h13M12 6l4.5 6L12 18"/><path d="M20.5 5v14"/></svg>',
    tune:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M4 12h4l3-7 3 14 3-7h3"/></svg>',
    mini:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><path d="M5 15h14"/></svg>',
    full:  '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 9l6 6 6-6"/></svg>',
    close: '<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M6 6l12 12M18 6 6 18"/></svg>',
  }

  // ── the one persistent player (a JS object, immune to the render loop) ──
  const audio = new Audio()
  audio.preload = 'none'
  // the PARABOLIC volume (Sum 2026-07-23: "curve sensitivity towards more adjustable soft — loud can
  // just be loud"): the SLIDER position s is what we store; the real volume is s² — half the slider's
  // travel covers the quiet quarter of loudness, so soft is fine-grained and loud is coarse.
  const volSlider = () => { let s = J('scroll-radio-vols', null); if (s == null) s = Math.sqrt(Math.min(1, Math.max(0, J('scroll-radio-vol', 0.7)))); return Math.min(1, Math.max(0, s)) }
  audio.volume = Math.pow(volSlider(), 2)
  let CUR = null, STATE = 'off'   // STATE: off · tuning · air · lost
  let COLL = [], CIDX = 0          // MY MUSIC — the owned collection played as a playlist
  let VOLPOP = false, SEEKING = false
  let PENDING_DEL = -1, DRAGN = -1   // drag-a-track-to-the-trash (with the are-you-sure step)

  // MY MUSIC (Sum 2026-07-22: "plus on plug just adds music to your custom station" — buy it, own it,
  // play it). local files (however you got them) served through oz://__local__; a playlist, not a stream.
  const AUDIO_EXT = /\.(mp3|m4a|aac|wav|ogg|oga|opus|flac)$/i
  const localMediaUrl = p => 'oz://localhost/__local__/' + String(p).replace(/^\//, '').split('/').map(encodeURIComponent).join('/')
  const collection = () => { try { const c = JSON.parse(localStorage.getItem('scroll-radio-collection') || '[]'); return Array.isArray(c) ? c : [] } catch (_) { return [] } }
  const myMusicStation = () => { const c = collection(); return { id: 'mine', name: 'My Music', by: c.length ? c.length + ' track' + (c.length === 1 ? '' : 's') + ' · yours' : 'empty — tap ＋ to add', collection: c } }
  // the PLAY MODE (Sum 2026-07-23 redesign): one dropdown — normal (play through, stop at the end) ·
  // repeat all · repeat one · shuffle. one key, scroll-radio-mode; old shuffle/loop keys migrate once.
  const MODES = [['normal', 'play through'], ['all', 'repeat all'], ['one', 'repeat one'], ['shuffle', 'shuffle']]
  function playMode() {
    try {
      let m = localStorage.getItem('scroll-radio-mode')
      if (!m) {   // migrate the old two-key state
        m = localStorage.getItem('scroll-radio-shuffle') === '1' ? 'shuffle'
          : localStorage.getItem('scroll-radio-loop') === '1' ? 'all' : 'normal'
        localStorage.setItem('scroll-radio-mode', m)
      }
      return MODES.some(x => x[0] === m) ? m : 'normal'
    } catch (_) { return 'normal' }
  }
  function playColl() {
    if (!COLL.length) { STATE = 'off'; paint(); return }
    const it = COLL[CIDX % COLL.length]
    CUR = 'mine'; STATE = 'tuning'; try { localStorage.setItem('scroll-radio-last', 'mine') } catch (_) {}
    audio.src = localMediaUrl(it.path || it)
    const p = audio.play(); if (p && p.catch) p.catch(() => { STATE = 'lost'; paint() })
    paint()
  }
  // next/back honor the mode. auto (track ended): one = replay, shuffle = random, all = wrap,
  // normal = stop at the end. a MANUAL next always moves (shuffle random, else step + wrap).
  function nextTrack(auto) {
    if (!COLL.length) return
    const m = playMode()
    if (auto && m === 'one') { playColl(); return }
    if (m === 'shuffle' && COLL.length > 1) { let n; do { n = Math.floor(Math.random() * COLL.length) } while (n === CIDX); CIDX = n }
    else if (CIDX + 1 >= COLL.length) { if (auto && m === 'normal') { STATE = 'off'; try { audio.pause() } catch (_) {} paint(); return } CIDX = 0 }
    else CIDX++
    playColl()
  }
  function prevTrack() {
    if (!COLL.length) return
    if (audio.currentTime > 3) { try { audio.currentTime = 0 } catch (_) {} return }
    CIDX = (CIDX - 1 + COLL.length) % COLL.length
    playColl()
  }
  async function addMusic() {
    const P = window.parent, t = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__)
    if (!t || !t.invoke) { flashSlot(); return }
    let paths = []; try { paths = await t.invoke('pick_files') } catch (_) {}
    paths = (paths || []).filter(p => AUDIO_EXT.test(p))
    if (!paths.length) return
    const c = collection()
    paths.forEach(p => { if (!c.some(x => (x.path || x) === p)) c.push({ path: p, name: (p.split('/').pop() || p).replace(AUDIO_EXT, '') }) })
    try { localStorage.setItem('scroll-radio-collection', JSON.stringify(c)) } catch (_) {}
    COLL = c; CIDX = c.length - paths.length; playColl()   // start on the first of what was just added
  }
  // scan the default music folder — "the one the plug plays from" (Sum 2026-07-23): ~/Music/0z-jams.
  // every audio file found is merged into the collection (deduped by path). native only. returns #added.
  async function scanFolder(silent) {
    const P = window.parent, t = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__)
    if (!t || !t.invoke) { if (!silent) flashSlot(); return 0 }
    let found = []
    try { found = await t.invoke('list_audio', { path: '' }) } catch (_) { return 0 }
    found = (found || []).filter(x => x && x.path)
    let c = collection(); let added = 0
    // PRUNE first (Sum curates by deleting files): an entry in a scanned folder whose file is gone, goes.
    const foundSet = new Set(found.map(x => x.path))
    const dirs = new Set(found.map(x => x.path.slice(0, x.path.lastIndexOf('/'))))
    const before = c.length
    c = c.filter(y => { const p = y.path || y; const d = String(p).slice(0, String(p).lastIndexOf('/')); return !dirs.has(d) || foundSet.has(p) })
    found.forEach(x => { if (!c.some(y => (y.path || y) === x.path)) { c.push({ path: x.path, name: String(x.name || '').replace(AUDIO_EXT, '') }); added++ } })
    if (added || c.length !== before) { try { localStorage.setItem('scroll-radio-collection', JSON.stringify(c)) } catch (_) {} COLL = c; if (CIDX >= c.length) CIDX = 0 }
    return added
  }

  const localStation = () => {
    const u = (localStorage.getItem('scroll-radio-local') || '').trim()
    if (!/^https?:\/\//i.test(u)) return null
    return { id: 'local', name: localStorage.getItem('scroll-radio-localname') || 'Your Station', by: 'local · the ultra-free dial', url: u }
  }
  // (0z Curated — a YouTube-playlist-as-a-channel — was CUT 2026-07-23: Sum "this is an orphan." the Plug
  //  is owned music + licensed streams, not a youtube tuner; a set list belongs in the PSV, not here.)
  const byId = id => id === 'local' ? localStation() : id === 'mine' ? myMusicStation() : STATIONS.find(s => s.id === id) || null

  function tune(st) {
    if (!st) return
    if (st.collection) {   // MY MUSIC — the owned collection, played as a playlist. an EMPTY collection
      // just tunes there quietly (dialing past must never pop the file picker — add via the playlist overlay).
      CUR = 'mine'; try { localStorage.setItem('scroll-radio-last', 'mine') } catch (_) {}
      if (!st.collection.length) { stop(); return }
      COLL = st.collection; CIDX = 0; playColl(); return
    }
    if (!st.url) return
    CUR = st.id; STATE = 'tuning'
    try { localStorage.setItem('scroll-radio-last', st.id) } catch (_) {}
    audio.src = st.url
    const p = audio.play()
    if (p && p.catch) p.catch(() => { STATE = 'off'; paint() })   // autoplay blocked → wait for a click
    paint()
  }
  function stop() { STATE = 'off'; try { audio.pause() } catch (_) {}; audio.removeAttribute('src'); paint() }
  function toggle() {
    if (STATE === 'air' || STATE === 'tuning') return stop()
    const st = byId(CUR) || byId(localStorage.getItem('scroll-radio-last') || '') || STATIONS[0]
    tune(st)
  }
  audio.addEventListener('playing', () => { STATE = 'air'; paint() })
  audio.addEventListener('waiting', () => { if (STATE !== 'off') { STATE = 'tuning'; paint() } })
  audio.addEventListener('error',   () => { if (audio.src) { STATE = 'lost'; paint() } })
  audio.addEventListener('ended',   () => { if (CUR === 'mine' && COLL.length) nextTrack(true) })   // My Music → next (shuffle/loop-aware)

  // ── the dock — one node, bottom-left; content re-paints on ACTIONS only (never in a loop) ──
  const dock = document.createElement('div')
  dock.id = 'sf-radio'
  dock.setAttribute('role', 'region')
  dock.setAttribute('aria-label', 'The Plug — radio')

  const nowName = () => {
    if (CUR === 'mine' && COLL.length) { const it = COLL[CIDX % COLL.length]; return (it && (it.name || it.path)) || 'My Music' }
    const st = byId(CUR); return st ? st.name : ''
  }
  const statusLine = () => STATE === 'air' ? 'on air' : STATE === 'tuning' ? 'tuning…' : STATE === 'lost' ? 'signal lost — try another' : 'off air'

  // ── THE TUNER (Sum 2026-07-23 redesign): the PLAYER is the whole base state — "vibe is tuning old
  //    school radio." ◀ ▶ step the dial; the station NAME opens the one OVERLAY (all stations — or the
  //    playlist when you're on My Music); pick → it's gone; click outside → it's gone. no top bar, no
  //    mini/full toggle (the old top bar pushed off screen — the thing that killed it). ──
  let OV = ''   // '' · 'stations' · 'playlist'
  const dial = () => {   // the tuning order: My Music first, then the streams, then your local slot
    const d = [myMusicStation(), ...STATIONS]
    const loc = localStation(); if (loc) d.push(loc)
    return d
  }
  function stepStation(dir) {
    const d = dial()
    let i = d.findIndex(s => s.id === CUR); if (i < 0) i = 0
    else i = (i + dir + d.length) % d.length
    tune(d[i])
  }
  function playerHTML() {
    const playing = STATE === 'air' || STATE === 'tuning'
    const onMine = CUR === 'mine'
    const st = byId(CUR)
    const stName = onMine ? 'My Music' : (st ? st.name : 'The Plug')
    // row 1 — the dial: ◀ [station name] ▶ (the name opens the overlay: playlist on My Music, all stations otherwise)
    const dialRow = `<div class="sf-rad-dialrow">
        <button class="sf-rad-ico sf-rad-icobtn" data-act="collapse" aria-label="Shrink to just the plug">${ICO.plug}</button>
        <button class="sf-rad-tbtn" data-act="stepdown" aria-label="Previous station">${ICO.prev}</button>
        <button class="sf-rad-stname" data-act="openlist" aria-label="${onMine ? 'Open the My Music playlist' : 'See all stations'}">${esc(stName)}</button>
        <button class="sf-rad-tbtn" data-act="stepup" aria-label="Next station">${ICO.next}</button>
        <span class="sf-rad-status" data-air="${STATE === 'air'}">${esc(statusLine())}</span>
      </div>`
    // row 2 — the transport: stations = play/pause + volume; My Music = back·play·next·stop + mode + volume
    // the play mode is ONE cycle button of universal symbols (Sum 2026-07-23: "replace play through,
    // repeat 1, repeat all with universal symbols") — tap steps through → ⟳ ⟳¹ ⤨, like every deck.
    const mode = playMode()
    const MODE_ICO = { normal: ICO.through, all: ICO.loop, one: ICO.loop1, shuffle: ICO.shuffle }
    const modeName = (MODES.find(m => m[0] === mode) || MODES[0])[1]
    const modeSel = `<button class="sf-rad-tbtn sf-rad-modebtn${mode !== 'normal' ? ' on' : ''}" data-act="modecycle" aria-label="Play mode: ${modeName} — click to change" title="${modeName}">${MODE_ICO[mode] || ICO.through}</button>`
    // TWO BARS (Sum 2026-07-23): the HORIZONTAL bar is TRACK POSITION (seek, My Music only — a stream
    // has no position); VOLUME is a NUMBER BOX → click → a VERTICAL slider pops (drag or click), click
    // anywhere else hides it. parabolic taper: soft end fine-grained, loud is just loud.
    const volPct = Math.round(audio.volume * 100)
    const volBox = `<span class="sf-rad-volwrap">
        <button class="sf-rad-volnum" data-act="volpop" aria-label="Volume — ${volPct} percent, opens the slider" aria-expanded="${VOLPOP}">${ICO.speaker}<span class="sf-rad-volnum-n">${volPct}</span></button>
        ${VOLPOP ? `<span class="sf-rad-volpop"><input class="sf-rad-vvol" type="range" min="0" max="1" step="0.01" value="${volSlider()}" aria-label="Volume" aria-orientation="vertical"></span>` : ''}
      </span>`
    const seek = `<input class="sf-rad-seek" type="range" min="0" max="${audio.duration && isFinite(audio.duration) ? audio.duration : 0}" step="0.5" value="${isFinite(audio.currentTime) ? audio.currentTime : 0}" aria-label="Track position">`
    const song = onMine && COLL.length ? `<div class="sf-rad-song" title="the playing track">${esc(nowName())}</div>` : ''
    const rows = onMine
      ? `<div class="sf-rad-transport">
           <button class="sf-rad-tbtn" data-act="prev" aria-label="Previous track">${ICO.prev}</button>
           <button class="sf-rad-play" data-act="toggle" aria-label="${playing ? 'Pause' : 'Play'}">${playing ? ICO.pause : ICO.play}</button>
           <button class="sf-rad-tbtn" data-act="next" aria-label="Next track">${ICO.next}</button>
           <button class="sf-rad-tbtn" data-act="stop" aria-label="Stop">${ICO.stopbtn}</button>
           ${modeSel}${volBox}
         </div>
         <div class="sf-rad-transport sf-rad-modrow">${seek}</div>`
      : `<div class="sf-rad-transport">
           <button class="sf-rad-play" data-act="toggle" aria-label="${playing ? 'Stop' : 'Play'}">${playing ? ICO.pause : ICO.play}</button>
           <span class="sf-rad-now">${esc(statusLine())}</span>${volBox}
         </div>`
    return `<div class="sf-rad-panel sf-rad-player">${dialRow}${song}${rows}</div>`
  }
  // the ONE overlay — all stations, or the My Music playlist. pick → gone; outside click → gone.
  // it floats ABOVE the player, so the player's tools never hide (Sum: "doesn't hide its tools").
  function overlayHTML() {
    if (OV === 'playlist') {
      const rows = COLL.length
        ? COLL.map((it, i) => `<button class="sf-rad-track${i === CIDX % Math.max(1, COLL.length) ? ' on' : ''}" role="option" aria-selected="${i === CIDX % Math.max(1, COLL.length)}" data-act="track" data-i="${i}" draggable="true"><span class="sf-rad-tnum">${i + 1}</span><span class="sf-rad-tname">${esc(it.name || it.path || 'track ' + (i + 1))}</span></button>`).join('')
        : `<div class="sf-rad-foot">no tracks yet — add some below.</div>`
      // drag a track onto the can → the ARE-YOU-SURE bar → the file moves to the macOS Trash
      // (recover, never rm) and leaves the playlist. keep = nothing happens.
      const del = PENDING_DEL >= 0 && COLL[PENDING_DEL]
      const trashRow = del
        ? `<div class="sf-rad-delbar" role="alertdialog" aria-label="Confirm removal">
             <span class="sf-rad-deltxt">trash “${esc((COLL[PENDING_DEL].name || COLL[PENDING_DEL].path || '').slice(0, 34))}”? the file goes to the Trash.</span>
             <button class="sf-rad-set sf-rad-delyes" data-act="delyes">trash it</button>
             <button class="sf-rad-set" data-act="delkeep">keep it</button>
           </div>`
        : `<div class="sf-rad-trash" aria-label="Drop a track here to remove it">${ICO.trash} drag a track here to remove it</div>`
      return `<div class="sf-rad-ov" role="dialog" aria-label="My Music playlist">
          <div class="sf-rad-list" role="listbox" aria-label="My Music tracks">${rows}</div>
          ${trashRow}
          <div class="sf-rad-dial">
            <button class="sf-rad-chip sf-rad-add" data-act="addmusic" aria-label="Add music to My Music"><b>＋ add music</b><span>own it · from a file</span></button>
            <button class="sf-rad-chip sf-rad-add" data-act="scanfolder" aria-label="Load your music folder"><b>⟳ my folder</b><span>~/Music/0z-jams</span></button>
          </div>
          <button class="sf-rad-ovclose" data-act="closeov" aria-label="Close the playlist">${ICO.full} close the playlist</button>
        </div>`
    }
    const chips = dial().map(s =>
      `<button class="sf-rad-chip${s.id === CUR ? ' on' : ''}" data-act="tune" data-id="${s.id}"><b>${esc(s.name)}</b><span>${esc(s.by)}</span></button>`).join('')
    return `<div class="sf-rad-ov" role="dialog" aria-label="All stations">
        <div class="sf-rad-dial">${chips}</div>
        <div class="sf-rad-slot">
          <input class="sf-rad-url" type="url" inputmode="url" placeholder="paste your local station's stream…"
                 aria-label="Local station stream URL" value="${esc(localStorage.getItem('scroll-radio-local') || '')}">
          <button class="sf-rad-set" data-act="setlocal">tune it</button>
        </div>
        <button class="sf-rad-ovclose" data-act="closeov" aria-label="Close the stations">${ICO.full} close the stations</button>
      </div>`
  }
  function paint() {
    // COLLAPSED (Sum 2026-07-23: "click the plug icon, shrink to just that, keep playing or stay
    // quiet") — the whole plug folds to one small icon; the on-air pulse rides it when sound is on
    // (the glow from the old card), so you always know where the music's coming from.
    if (localStorage.getItem('scroll-radio-min') === '1') {
      const playing = STATE === 'air' || STATE === 'tuning'
      dock.innerHTML = `<button class="sf-rad-minicon" data-act="expand" aria-label="Open The Plug${playing ? ' — now playing ' + nowName() : ''}">${ICO.plug}${playing ? '<span class="sf-rad-air" aria-hidden="true"></span>' : ''}</button>`
      dock.dataset.state = STATE
      return
    }
    dock.innerHTML = (OV ? overlayHTML() : '') + playerHTML()
    dock.dataset.state = STATE
  }

  // one delegated handler — no per-node rebinding to leak across re-paints
  dock.addEventListener('click', e => {
    const t = e.target.closest('[data-act]'); if (!t) return
    const act = t.dataset.act
    if (act === 'volpop') { VOLPOP = !VOLPOP; paint() }
    else if (act === 'modecycle') {
      const order = MODES.map(m => m[0]); const next = order[(order.indexOf(playMode()) + 1) % order.length]
      try { localStorage.setItem('scroll-radio-mode', next) } catch (_) {}
      paint()
    }
    else if (act === 'collapse') { OV = ''; VOLPOP = false; try { localStorage.setItem('scroll-radio-min', '1') } catch (_) {} paint() }
    else if (act === 'expand') { try { localStorage.setItem('scroll-radio-min', '0') } catch (_) {} paint() }
    else if (act === 'stepdown') stepStation(-1)
    else if (act === 'stepup') stepStation(1)
    else if (act === 'openlist') { OV = (CUR === 'mine' ? 'playlist' : 'stations'); paint() }
    else if (act === 'toggle') toggle()
    else if (act === 'prev') prevTrack()
    else if (act === 'next') nextTrack(false)
    else if (act === 'stop') stop()
    else if (act === 'closeov') { OV = ''; PENDING_DEL = -1; paint() }
    else if (act === 'delkeep') { PENDING_DEL = -1; paint() }
    else if (act === 'delyes') {
      const i = PENDING_DEL; PENDING_DEL = -1
      if (i >= 0 && COLL[i]) {
        const entry = COLL[i]
        const P = window.parent, tt = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__)
        if (tt && tt.invoke && entry.path) { tt.invoke('trash_file', { path: entry.path }).catch(() => {}) }
        const c = collection().filter(y => (y.path || y) !== (entry.path || entry))
        try { localStorage.setItem('scroll-radio-collection', JSON.stringify(c)) } catch (_) {}
        COLL = c
        if (i === CIDX) { stop(); CIDX = 0 }
        else if (i < CIDX) CIDX--
      }
      paint()
    }
    else if (act === 'track') { const i = parseInt(t.dataset.i, 10); if (!isNaN(i) && COLL.length) { CIDX = i; playColl() } }   // overlays STAY open (Sum: better than spec) — the close bar ends them
    else if (act === 'tune') { const st = byId(t.dataset.id); if (st) tune(st) }                                               // surf the dial; close when settled
    else if (act === 'addmusic') { addMusic() }
    else if (act === 'scanfolder') { scanFolder(false).then(() => { CUR = 'mine'; COLL = collection(); paint() }) }
    else if (act === 'setlocal') {
      const inp = dock.querySelector('.sf-rad-url'), u = (inp && inp.value || '').trim()
      try { u ? localStorage.setItem('scroll-radio-local', u) : localStorage.removeItem('scroll-radio-local') } catch (_) {}
      paint(); const nl = localStation(); if (nl) { OV = ''; tune(nl) }
    }
  })
  dock.addEventListener('input', e => {
    if (e.target.classList.contains('sf-rad-vvol')) {
      // parabola: slider position s → volume s². the number box updates by TEXT NODE only —
      // never a repaint mid-drag (the render-loop law; a rewrite would eat the drag).
      const s = Math.min(1, Math.max(0, parseFloat(e.target.value) || 0))
      audio.volume = s * s
      try { localStorage.setItem('scroll-radio-vols', JSON.stringify(s)); localStorage.setItem('scroll-radio-vol', JSON.stringify(audio.volume)) } catch (_) {}
      const n = dock.querySelector('.sf-rad-volnum-n'); if (n) n.textContent = Math.round(audio.volume * 100)   // the inner NUMBER only — never wipe the speaker icon
    }
    if (e.target.classList.contains('sf-rad-seek')) {
      SEEKING = true
      const v = parseFloat(e.target.value)
      if (isFinite(v) && isFinite(audio.duration)) { try { audio.currentTime = v } catch (_) {} }
    }
  })
  dock.addEventListener('change', e => { if (e.target.classList.contains('sf-rad-seek')) SEEKING = false })
  // drag-a-track-to-the-trash — the drop arms the confirm; nothing is touched until "trash it"
  dock.addEventListener('dragstart', e => {
    const t = e.target.closest && e.target.closest('.sf-rad-track')
    if (t) { DRAGN = parseInt(t.dataset.i, 10); try { e.dataTransfer.setData('text/plain', String(DRAGN)) } catch (_) {} }
  })
  dock.addEventListener('dragover', e => {
    const z = e.target.closest && e.target.closest('.sf-rad-trash')
    if (z) { e.preventDefault(); z.classList.add('hot') }
  })
  dock.addEventListener('dragleave', e => {
    const z = e.target.closest && e.target.closest('.sf-rad-trash')
    if (z) z.classList.remove('hot')
  })
  dock.addEventListener('drop', e => {
    const z = e.target.closest && e.target.closest('.sf-rad-trash')
    if (z && DRAGN >= 0) { e.preventDefault(); PENDING_DEL = DRAGN; DRAGN = -1; paint() }
  })
  // the position bar rides timeupdate — VALUE writes only, one element, never a repaint
  audio.addEventListener('timeupdate', () => {
    if (SEEKING) return
    const s = dock.querySelector('.sf-rad-seek'); if (!s) return
    if (isFinite(audio.duration) && Math.abs(parseFloat(s.max) - audio.duration) > 1) s.max = audio.duration
    s.value = audio.currentTime || 0
  })
  audio.addEventListener('loadedmetadata', () => {
    const s = dock.querySelector('.sf-rad-seek'); if (s && isFinite(audio.duration)) s.max = audio.duration
  })
  // click anywhere off the volume popover → it hides (Sum: "click anywhere else to hide")
  document.addEventListener('click', e => {
    if (VOLPOP && !(e.target.closest && e.target.closest('.sf-rad-volwrap'))) { VOLPOP = false; paint() }
  }, true)
  dock.addEventListener('change', e => {
    if (e.target.classList.contains('sf-rad-mode')) { try { localStorage.setItem('scroll-radio-mode', e.target.value) } catch (_) {} }
  })
  // ONE close convention (Sum 2026-07-23): overlays stay open — surf stations / browse the playlist
  // while it plays — and close ONLY via their close bar. (outside-click close was cut; the accident
  // that wouldn't close beat the spec, then became the spec.)
  function flashSlot() { OV = 'stations'; paint(); const s = dock.querySelector('.sf-rad-url'); if (s) { s.focus(); s.classList.add('nudge'); setTimeout(() => s.classList.remove('nudge'), 600) } }

  // boot: the player, tuned to the last dial, never autoplaying.
  CUR = localStorage.getItem('scroll-radio-last') || 'mine'
  paint()
  document.body.appendChild(dock)
  // auto-load the music folder on first run so My Music isn't empty out of the box (Sum: "the one plug
  // plays from"). only when the collection is empty — after that, ＋ and the folder chip manage it.
  ;(async () => { try { if (!collection().length) { const n = await scanFolder(true); if (n) paint() } } catch (_) {} })()

  // the gear can hide the whole dock (scroll-radio-hidden), live via the storage bus
  function applyHidden() { dock.hidden = localStorage.getItem('scroll-radio-hidden') === '1' }
  applyHidden()
  window.addEventListener('storage', e => { if (e.key === 'scroll-radio-hidden') applyHidden() })

  // the seam — the newsie (or any hand) can tune the paper's soundtrack from chat later
  window.SF_RADIO = {
    open: () => { OV = 'stations'; paint() },   // raise the all-stations overlay
    tune: id => { const st = byId(id); if (st) tune(st) },
    stop,
    stations: () => STATIONS.map(s => ({ id: s.id, name: s.name })),
  }
})()
