// ─────────────────────────────────────────────────────────────────────────────
// THE PORT SIDE VIEW — its OWN COPY of the canon's curated public-domain shelf.
//
// SYNC, NOT LEAN (IC.md "borrow a copy, own it at the port"; Sum 2026-07-26: "standalone app needs a
// COPY — look, copy, and tweak reuse, no leaning on. this is what keeps breaking: 'access to'"). the
// paper is a standalone unit and must NEVER reach into ../clock at runtime. so the clock's proven
// curated arrays (lb-headlines-lanes.js PACKS) + Alexa N. Dria's canon stacks (~/Local/0z-desk/canon/:
// kjv-bible.txt, gita, qur'an, tao…) are COPIED here, verbatim, and OWNED by the scroll card.
//
// keep the copies in step by re-copying when the shelf grows — a build step, never a live import.
// Sum 2026-07-26: "we had a ton of bible and other verses in clock… everything from clock but time
// tools, even app paper got them." here they are, on the paper's own shelf.
// ─────────────────────────────────────────────────────────────────────────────

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   SCRIPTURE + WISDOM TRADITIONS → the spirit ... search: "SCRIPTURE + WISDOM"
//   short quotes → the quote lane (the author .... search: "short quotes → the"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for `window.SF_CANON`, a two-lane object
//    **(`spirit` and `quote`) that feeds the scroll card's display. The spirit lane concatenates
//    **eight wrapped tradition arrays; the quote lane wraps a ninth. Nothing else in the codebase
//    **should duplicate these arrays.
//
//    **TOUCH HERE**
//    - Add a verse to an existing tradition → edit the array directly (e.g., `bible` L19–35,
//    - `torah` L36–43, `quran` L44–50, `vedas` L51–57, `gita` L58–64, `thelema` L65–72,
//    - `freethought` L73–80, `manifest` L81–96, `quotes` L99–106).
//    - Add a new tradition lane → create a const array, then add a `wrap(newArray, 'display name')`
//    - call inside the `spirit` concatenation at L109–117.
//    - Change a tradition's display name (the "kicker") → edit the second argument to `wrap()` at
//    - L110–117.
//    - Add a verse with custom metadata (like the James 1:1 egg at L122) → add an object literal
//    - directly to the `spirit` array at L121–124 instead of using `wrap()`.
//
//    **TRAPS**
//    - `window.SF_CANON` (L108) is the load-bearing export name. Renaming it breaks the scroll card
//    - at runtime.
//    - The `wrap()` function (L15) transforms each string into `{ title, src }`. If you add a verse
//    - as a raw string instead of wrapping it, it will render as `[object Object]`.
//    - The James 1:1 object at L122 has a malformed `body` field (`'ed's trans': [sic]"Hi"[sic]'`).
//    - This appears intentional (a house footnote marker); do not "fix" it without checking the
//    - scroll card's render logic.
//    - The `spirit` array order (L109–125) determines lane rotation. Reordering the `wrap()` calls
//    - changes which tradition appears first.
//    - Line 126 wraps `quotes` with an empty string `''` as the source, not a tradition name. This
//    - is deliberate (byline rides elsewhere). Do not add a source name here.
//
//    **DO NOT**
//    - Import these arrays from `../clock` or any other file at runtime. The comment at L4–12 is
//    - explicit: this is a standalone copy. If the clock's canon changes, manually re-copy here; do
//    - not add a live dependency.
//    - Rename `bible`, `torah`, `quran`, `vedas`, `gita`, `thelema`, `freethought`, `manifest`, or
//    - `quotes` — they are only referenced once each (at their `wrap()` call), but the names are
//    - semantic anchors for maintainers.
//    - Change the IIFE wrapper (L14, L128) or the `wrap()` function signature. Both are structural.
//    - Add runtime logic, conditionals, or imports. This file is a data shelf, not a logic file.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  const wrap = (arr, src) => arr.map(t => ({ title: t, src }))

  // ── SCRIPTURE + WISDOM TRADITIONS → the spirit lane (short form, one line each; the reference rides
  //    in the text, the tradition rides the kicker). copied from the clock's theology shelf. ──
  const bible = [   // KJV — public domain (US)
    'To every thing there is a season, and a time to every purpose under the heaven. — Ecclesiastes 3:1',
    'The Lord is my shepherd; I shall not want. — Psalm 23:1',
    'Be still, and know that I am God. — Psalm 46:10',
    'Let there be light. — Genesis 1:3',
    'Love thy neighbour as thyself. — Leviticus 19:18',
    'Blessed are the peacemakers: for they shall be called the children of God. — Matthew 5:9',
    'Ask, and it shall be given you; seek, and ye shall find. — Matthew 7:7',
    'And ye shall know the truth, and the truth shall make you free. — John 8:32',
    'Vanity of vanities, saith the Preacher; all is vanity. — Ecclesiastes 1:2',
    'A soft answer turneth away wrath: but grievous words stir up anger. — Proverbs 15:1',
    'Pride goeth before destruction, and an haughty spirit before a fall. — Proverbs 16:18',
    'Whatsoever thy hand findeth to do, do it with thy might. — Ecclesiastes 9:10',
    'Greater love hath no man than this, that a man lay down his life for his friends. — John 15:13',
    'Consider the lilies of the field, how they grow; they toil not, neither do they spin. — Matthew 6:28',
    'For what shall it profit a man, if he shall gain the whole world, and lose his own soul? — Mark 8:36',
  ]
  const torah = [
    'Hear, O Israel: The LORD our God, the LORD is one. — Deuteronomy 6:4',
    'In the beginning God created the heaven and the earth. — Genesis 1:1',
    'Justice, justice shalt thou pursue. — Deuteronomy 16:20',
    'Be strong and of a good courage; fear not. — Deuteronomy 31:6',
    'Thou shalt not follow a multitude to do evil. — Exodus 23:2',
    'And thou shalt love thy neighbour as thyself. — Leviticus 19:18',
  ]
  const quran = [
    'In the name of God, the Most Gracious, the Most Merciful. — Qur\'an 1:1',
    'Indeed, with hardship comes ease. — Qur\'an 94:6',
    'God does not burden a soul beyond what it can bear. — Qur\'an 2:286',
    'Whoever saves one life, it is as if he had saved mankind entirely. — Qur\'an 5:32',
    'So remember Me; I will remember you. — Qur\'an 2:152',
  ]
  const vedas = [
    'Truth is one; the wise call it by many names. — Rig Veda 1.164.46',
    'Lead me from the unreal to the real. Lead me from darkness to light. Lead me from death to immortality. — Brihadaranyaka Upanishad 1.3.28',
    'Thou art that. — Chandogya Upanishad 6.8.7',
    'The Self is not born, nor does it ever die. — Katha Upanishad 1.2.18',
    'From joy all beings are born; by joy they live. — Taittiriya Upanishad 3.6',
  ]
  const gita = [
    'You have a right to your actions, but never to the fruits of your actions. — Bhagavad Gita 2.47',
    'The soul is neither born, nor does it ever die. — Bhagavad Gita 2.20',
    'Whenever righteousness declines and unrighteousness rises, I manifest myself. — Bhagavad Gita 4.7',
    'Better one\'s own duty, though imperfect, than another\'s duty well performed. — Bhagavad Gita 3.35',
    'Evenness of mind in success and failure — such evenness is called yoga. — Bhagavad Gita 2.48',
  ]
  const thelema = [
    'Do what thou wilt shall be the whole of the Law. — Aleister Crowley, The Book of the Law',
    'Love is the law, love under will. — Aleister Crowley, The Book of the Law',
    'Every man and every woman is a star. — Aleister Crowley, The Book of the Law',
    'One should strive to act with compassion and empathy toward all creatures. — The Satanic Temple, First Tenet',
    'The freedom of others should be respected, including the freedom to offend. — The Satanic Temple, Fourth Tenet',
    'Beliefs should conform to one\'s best scientific understanding of the world. — The Satanic Temple, Fifth Tenet',
  ]
  const freethought = [
    'The hands that help are better far than lips that pray. — Robert G. Ingersoll',
    'The time to be happy is now, and the place to be happy is here. — Robert G. Ingersoll',
    'The stupid are cocksure while the intelligent are full of doubt. — Bertrand Russell',
    'Extraordinary claims require extraordinary evidence. — Carl Sagan',
    'Is God willing to prevent evil, but not able? Then he is not omnipotent. — attributed to Epicurus',
    'It ain\'t what you don\'t know that gets you into trouble. It\'s what you know for sure that just ain\'t so. — attributed to Mark Twain',
  ]
  const manifest = [   // traditional woo, played straight — the "woo/wook" Sum asked back
    'Ask the universe. Be specific. The universe loves details.',
    'What you think about, you bring about.',
    'Gratitude is the frequency. Tune to it and abundance can hear you.',
    'Visualize it done. The feeling is the magnet.',
    'You are a magnet. Like attracts like. Choose your charge.',
    'Write it down as if it already happened. The pen is a wand.',
    'Raise your vibration and the right people find you.',
    'The universe rearranges itself to match your energy.',
    'Speak it aloud. Words are spells. That is why they call it spelling.',
    'Release the how. Your job is the what. Delivery is handled.',
    'The full moon releases. The new moon receives. Plan accordingly.',
    'Trust the timing. Nothing is late. Nothing is early.',
    'Protect your energy. Not everyone gets a ticket to your show.',
    'You did not find this line by accident.',
  ]

  // ── short quotes → the quote lane (the author rides the kicker via bylineOf). ──
  const quotes = [
    'The impediment to action advances action. What stands in the way becomes the way. — Marcus Aurelius',
    'The barn burned down — now I can see the moon. — Mizuta Masahide',
    'An old pond. A frog jumps in. The sound of water. — Bashō',
    'No man ever steps in the same river twice. — Heraclitus',
    'Fall seven times, stand up eight. — Japanese proverb',
    'The best time to plant a tree was twenty years ago. The second best time is now. — proverb',
  ]

  window.SF_CANON = {
    spirit: [].concat(
      wrap(bible, 'the Bible · KJV'),
      wrap(torah, 'the Tanakh'),
      wrap(quran, "the Qur'an"),
      wrap(vedas, 'the Vedas'),
      wrap(gita, 'the Bhagavad Gita'),
      wrap(thelema, 'the left-hand path'),
      wrap(freethought, 'the freethought shelf'),
      wrap(manifest, 'the manifestation shelf'),
      // THE GREATEST HITS — in the crate, benched by the rotation, one tap from the front (Sum 2026-07-26:
      // "leave John and James, toggled off but always available"). James 1:1 carries the ed's trans' egg:
      // the whole grand salutation, translated. $ is the house asterisk; "ed's trans'" the house footnote.
      [
        { title: 'James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad, greeting. — James 1:1', src: 'the Bible · KJV', body: 'ed’s trans’: [sic]"Hi"[sic]' },
        { title: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. — John 3:16', src: 'the Bible · KJV' }
      ]
    ),
    quote: wrap(quotes, ''),
  }
})()
