// scroll-radar.js — RADAR off the weather ear (Sum's witness recipe, ported into 0z).
//
// The learning (2026-07-21): RainViewer radar tiles cap at ZOOM 6 — z7+ returns a
// "not supported" placeholder. So this stays at z6 (regional; the witness proved a
// z6 wide view catches the cell). In 0z (oz://localhost) <img> tiles load — no
// file:// referer block — so no baking; live past-2h + nowcast, scrubbable.
//
// frames: api.rainviewer.com/public/weather-maps.json → radar.past + radar.nowcast.
// tile: {host}{path}/256/{z}/{x}/{y}/4/1_1.png (color 4 = smooth). base = OSM.
// A tighter local view (z8 base + upscaled z6 radar) is the next pass — noted.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   MAP INTERACTION (Sum 2026-07-24: "scroll to ... search: "MAP INTERACTION (Sum"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for the radar overlay UI and interaction.
//    **It exports `window.SF_RADAR` with `open` and `close` methods (line 108).
//
//    **TOUCH HERE**
//    - Change the radar source or tile URL format → `radURL()` L32
//    - Change the default location (SLC) or fallback geo source → `GEO`, `LAT`, `LON`, `CITY`
//    - L15–17
//    - Change the regional tile grid size (currently 3×3) → `N` L16
//    - Change the time display format → `show()` L44, specifically line 50
//    - Change the "now" / "past" / "nowcast" label text → `show()` L44, specifically line 52
//    - Change zoom limits or zoom speed → `zoomAt()` L85, specifically lines 86 and 88
//    - Change the auto-play interval (currently 650ms) → `play()` L55
//    - Change the city name shown in the title → `CITY` L17 or the template at line 63
//
//    **TRAPS**
//    - `F.nowIdx` (set at line 30, used at lines 52 and 105) marks the boundary between past and
//    - nowcast frames. If you change how `frames()` builds the list, this index must stay correct
//    - or the "now" label will point to the wrong frame.
//    - `scale`, `panX`, `panY` (line 80) are local state inside `open()`. They reset on close (line
//    - 56 clears `ov`), so they are not persisted — but the snap-to-home logic at line 88 depends
//    - on the exact threshold `1.001`.
//    - The `rd-*` class names (lines 60, 62–72) are load-bearing: CSS elsewhere depends on them.
//    - Renaming them here breaks styling silently.
//    - `localStorage.getItem('scroll-geo')` and `'geo-cache'` (line 15) are shared keys with other
//    - files. Changing them orphans stored user locations.
//    - The RainViewer API URL (line 24) and tile host path (line 32) are external contracts. If
//    - RainViewer changes their schema, `frames()` will return `null` and the radar will show
//    - "unreachable" (line 103) — this is the intended graceful failure.
//
//    **DO NOT**
//    - Do not move the `frames()` async call (line 102) earlier; it must run after the DOM is built
//    - and event listeners are attached, or the UI will not respond to the data.
//    - Do not change the zoom level `Z = 6` (line 16) without understanding that RainViewer tiles
//    - do not exist above z6 (documented at line 3).
//    - Do not add persistence of `scale`, `panX`, `panY` here; that belongs in a separate
//    - state-management file if needed.
//    - Do not change the tile fetch logic; if you need a different tile source or caching strategy,
//    - that is a separate concern outside this file.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  'use strict'
  // the reader's OWN town — the PSV's own 'scroll-geo' first (Sum 2026-07-22: independent PSV location),
  // then the clock's shared 'geo-cache' ({lat,lon,city}); SLC is the final fallback.
  const GEO = (() => { try { return JSON.parse(localStorage.getItem('scroll-geo') || 'null') || JSON.parse(localStorage.getItem('geo-cache') || 'null') } catch (_) { return null } })() || {}
  const LAT = GEO.lat != null ? GEO.lat : 40.72, LON = GEO.lon != null ? GEO.lon : -111.9, Z = 6, N = 3   // regional · 3×3 tiles
  const CITY = GEO.city || 'Salt Lake City'
  const lon2x = (lon, z) => Math.floor((lon + 180) / 360 * Math.pow(2, z))
  const lat2y = (lat, z) => { const r = lat * Math.PI / 180; return Math.floor((1 - Math.log(Math.tan(r) + 1 / Math.cos(r)) / Math.PI) / 2 * Math.pow(2, z)) }
  const cx = lon2x(LON, Z), cy = lat2y(LAT, Z), x0 = cx - (N >> 1), y0 = cy - (N >> 1)
  const baseURL = (x, y) => `https://tile.openstreetmap.org/${Z}/${x}/${y}.png`

  async function frames() {
    const url = 'https://api.rainviewer.com/public/weather-maps.json'
    let j
    try { j = await (await fetch(url)).json() } catch (_) {
      try { const P = window.parent, c = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__); j = JSON.parse(await c.invoke('fetch_page', { url })) } catch (e) { return null }
    }
    const past = (j.radar && j.radar.past) || [], now = (j.radar && j.radar.nowcast) || []
    return { host: j.host, list: past.concat(now), nowIdx: past.length - 1 }
  }
  const radURL = (host, path, x, y) => `${host}${path}/256/${Z}/${x}/${y}/4/1_1.png`

  let ov, F = null, idx = 0, playing = true, timer = null

  function grid() {
    let h = ''
    for (let dy = 0; dy < N; dy++) for (let dx = 0; dx < N; dx++) {
      const x = x0 + dx, y = y0 + dy
      h += `<div class="rd-cell"><img class="rd-base" src="${baseURL(x, y)}" alt="" onerror="this.style.opacity=0" data-x="${x}" data-y="${y}"><img class="rd-rad" src="" alt="" onerror="this.style.opacity=0" data-x="${x}" data-y="${y}"></div>`
    }
    return h
  }
  function show(i) {
    if (!F || !F.list.length) return
    idx = (i + F.list.length) % F.list.length
    const f = F.list[idx]
    ov.querySelectorAll('.rd-rad').forEach(im => { im.style.opacity = ''; im.src = radURL(F.host, f.path, +im.dataset.x, +im.dataset.y) })
    const t = new Date(f.time * 1000)
    ov.querySelector('#rd-stamp').textContent = t.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })
    const sub = ov.querySelector('#rd-sub')
    sub.textContent = idx > F.nowIdx ? 'nowcast — the next hour' : idx === F.nowIdx ? 'now' : Math.round((F.nowIdx - idx) * 10) + ' min ago'
    ov.querySelector('#rd-scrub').value = idx
  }
  function play(on) { playing = on; ov.querySelector('#rd-play').textContent = on ? '⏸' : '▶'; if (timer) clearInterval(timer); if (on) timer = setInterval(() => show(idx + 1), 650) }
  function close() { if (timer) clearInterval(timer); if (ov) ov.remove(); ov = null }

  async function open() {
    if (ov) return
    ov = document.createElement('div'); ov.className = 'rd-ov'
    ov.innerHTML = `
      <div class="rd-panel">
        <div class="rd-head"><span class="rd-title">radar · ${CITY}</span>
          <span class="rd-zooms"><button class="rd-zoom" id="rd-zout" aria-label="zoom out">−</button><button class="rd-zoom" id="rd-zin" aria-label="zoom in">＋</button></span>
          <button class="rd-x" aria-label="close">✕</button></div>
        <div class="rd-stage"><div class="rd-grid">${grid()}</div><div class="rd-dot"></div><div class="rd-cred">RainViewer · past 2h + nowcast · z6 (regional)</div></div>
        <div class="rd-bar">
          <button id="rd-play" class="rd-play">⏸</button>
          <div class="rd-stamps"><div id="rd-stamp">loading…</div><div class="rd-sub" id="rd-sub">reaching the radar…</div></div>
          <input id="rd-scrub" class="rd-scrub" type="range" min="0" max="0" value="0" step="1">
        </div>
      </div>`
    document.body.appendChild(ov)
    ov.addEventListener('mousedown', e => { if (e.target === ov) close() })
    ov.querySelector('.rd-x').addEventListener('click', close)
    // ── MAP INTERACTION (Sum 2026-07-24: "scroll to zoom on cursor, or drag the screen") — the SAME
    //    tiles, scaled + panned (no re-fetch; RainViewer caps at z6). scroll-zoom is cursor-centred, drag
    //    pans, the +/− buttons zoom on the middle, and 1× snaps back to the town. pixels blow up past 1×. ──
    const stage = ov.querySelector('.rd-stage'), gridEl = ov.querySelector('.rd-grid'), dot = ov.querySelector('.rd-dot')
    let scale = 1, panX = 0, panY = 0
    const applyT = () => {
      gridEl.style.transform = `translate(-50%, -50%) translate(${panX}px, ${panY}px) scale(${scale})`
      if (dot) dot.style.opacity = (scale === 1 && !panX && !panY) ? '' : '0'   // the town mark is true only in the home view
    }
    function zoomAt(factor, sx, sy) {   // sx,sy = the fixed point, relative to the stage centre
      const ns = Math.max(1, Math.min(8, scale * factor)), r = ns / scale
      panX = sx * (1 - r) + panX * r; panY = sy * (1 - r) + panY * r; scale = ns
      if (scale <= 1.001) { scale = 1; panX = 0; panY = 0 }
      applyT()
    }
    const atCentre = e => { const b = stage.getBoundingClientRect(); return [e.clientX - (b.left + b.width / 2), e.clientY - (b.top + b.height / 2)] }
    ov.querySelector('#rd-zin').addEventListener('click', () => zoomAt(1.5, 0, 0))
    ov.querySelector('#rd-zout').addEventListener('click', () => zoomAt(1 / 1.5, 0, 0))
    stage.addEventListener('wheel', e => { e.preventDefault(); const [sx, sy] = atCentre(e); zoomAt(e.deltaY < 0 ? 1.2 : 1 / 1.2, sx, sy) }, { passive: false })
    let drag = null
    stage.addEventListener('pointerdown', e => { drag = { x: e.clientX, y: e.clientY }; try { stage.setPointerCapture(e.pointerId) } catch (_) {} stage.style.cursor = 'grabbing'; e.preventDefault() })
    stage.addEventListener('pointermove', e => { if (!drag) return; panX += e.clientX - drag.x; panY += e.clientY - drag.y; drag.x = e.clientX; drag.y = e.clientY; applyT() })
    const endDrag = () => { drag = null; stage.style.cursor = '' }
    stage.addEventListener('pointerup', endDrag); stage.addEventListener('pointercancel', endDrag)
    ov.querySelector('#rd-play').addEventListener('click', () => play(!playing))
    ov.querySelector('#rd-scrub').addEventListener('input', e => { play(false); show(+e.target.value) })
    F = await frames()
    if (!F || !F.list.length) { ov.querySelector('#rd-sub').textContent = 'radar unreachable — try again in a moment'; return }
    ov.querySelector('#rd-scrub').max = F.list.length - 1
    show(F.nowIdx); play(true)
  }

  window.SF_RADAR = { open, close }
})()
