// scroll-search.js — SEARCH THE NAMED SOURCES (Sum 2026-07-21, from the web-search gripe research).
//
// WHY THIS EXISTS. The 2026 complaints about web search are all one complaint: you no longer know
// who is talking. 68% of US searches end without a click; ~52% of new articles are machine-written
// filler; people literally append "reddit" to queries to claw their way back to a human. The fix
// people ask for is small and boring — no ads, no tracking, a NAMED source, and a date.
//
// So this does not crawl the web and it does not rank it. It asks a short list of corpora that
// have a librarian, and it puts the librarian's name on every card:
//   · Wikipedia   — encyclopedia (CORS ok, queried direct)
//   · Wikinews    — journalism, human-written (CORS ok, queried direct)
//   · arXiv       — preprints, named authors (NO CORS → the fetch_page bolt, i.e. the metal)
//
// ⚠️ NO api.allorigins.win here, unlike the clock's older ladder. A third-party proxy can rewrite
// any response it relays, and search results are exactly the thing you must not let a stranger
// edit. Direct or the metal; if neither works, that source reports itself down and says so.
//
// FOR AI: results reuse scroll.js's card() through window.SF — do NOT re-implement the card, and
//   do NOT build result HTML by hand. card() escapes via textContent, which is what keeps a hostile
//   result title from becoming markup. Same lesson as the clock's headline overlay.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   one fetcher per source. each returns .......... search: "one fetcher per source."
//   run every source in parallel; a source that ... search: "run every source in"
//   SURF THE WEB — the mode toggle (Sum ........... search: "SURF THE WEB — the mode"
//   the bar, mounted in the masthead .............. search: "the bar, mounted in the"
//   the ＋ door (Sum 2026-07-22: "psv gets a ....... search: "the ＋ door (Sum"
//   THE WAKE + THE CURATE BOX (Sum 2026-07-25: .... search: "THE WAKE + THE CURATE"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — This file is the single source of truth for search UI and result fetching from
//    **three named sources (Wikipedia, Wikinews, arXiv) plus DuckDuckGo web search. It exports
//    **`window.SF_SEARCH(term, useSurf)` (line 290) for external callers and `window.SF_HOME` (line
//    **187) for navigation. It also owns the search bar mounted in the masthead, the wake (search
//    **history), and the curate box (pinned results).
//
//    **TOUCH HERE** —
//    - Add or remove a named source → edit `SOURCES` array (line 22), `KICK` object (line 23), and
//    - add a fetcher to `FETCH` (line 41)
//    - Change how a source's results are formatted → edit the `.map()` in that source's fetcher
//    - (e.g., Wikipedia at line 45, Wikinews at line 54, arXiv at line 66)
//    - Change the search bar's placeholder text or button labels → edit `box.innerHTML` (line 137)
//    - and the toggle logic in `resetBar()` (line 174) and the surf click handler (line 168)
//    - Change how results are displayed on the page → edit `runSearch()` (line 236), specifically
//    - the `rows.forEach()` at line 279
//    - Change the wake or curate box appearance → edit `drawWake()` (line 203)
//    - Change DuckDuckGo parsing or fallback behavior → edit `duckSearch()` (line 106)
//
//    **TRAPS** —
//    - `window.SF` (line 132) and `window.SF.card()` (line 280) must exist; results are rendered
//    - via `SF.card(r)`, not hand-built HTML. Do not build result HTML by hand (line 18–20).
//    - `sessionStorage` keys `'sf-wake'` and `'sf-pins'` (lines 195–196, 205) are persisted across
//    - page reloads within a session. Changing the shape of `{q, links}` or `{t, u}` will orphan
//    - existing user data.
//    - `localStorage.getItem('scroll-surf')` (lines 167, 295) is the mode flag. Renaming or
//    - removing it breaks the surf edition's auto-start.
//    - `_snap` and `_snapY` (line 166) hold the pocketed paper state. `surfBack()` (line 181) must
//    - restore both or fall back to `SF.render(true)` (line 185).
//    - `KICK` object (line 23) keys must match `SOURCES` array (line 22) exactly, or `search()`
//    - will fail silently at line 266.
//    - The round-robin interleaving in `search()` (lines 93–98) depends on `byName` being keyed by
//    - source name. Changing the merge order changes result ranking.
//    - `looksLikeLink()` (line 149) is called by both `openInPortal()` (line 150) and the form
//    - submit handler (line 311). Changing it affects both paths.
//
//    **DO NOT** —
//    - Do not rename `window.SF`, `window.SF_SEARCH`, `window.SF_HOME`, `window.OZ_READER`, or
//    - `window.parent.OZ_READER` — these are the contract with the Portal and parent frame.
//    - Do not hand-build result HTML; always use `SF.card()` (line 280). The card escapes via
//    - `textContent`, which prevents hostile titles from becoming markup (line 18–20).
//    - Do not add a third-party proxy mirror for named sources (Wikipedia, Wikinews, arXiv). The
//    - header (lines 14–16) forbids it; use `metalFetch()` (line 26) or direct CORS only.
//    - Do not move the `mount()` function or the IIFE wrapper — the DOMContentLoaded hook (line
//    - 315) depends on it.
//    - Do not change the result object shape `{lane, kickOverride, src, title, body, link, credit}`
//    - without updating all three fetchers and `runSearch()`.
//    - Styling, CSS class names, and the masthead integration belong in the CSS file, not here.
//    - The Portal integration (`R.read()`, `R.surf()`) belongs in the reader, not here.
//
//
//
//    ---
//
// END IC SHIP PASS

;(function () {
  const SOURCES = ['wikipedia', 'wikinews', 'arxiv']
  const KICK = { wikipedia: 'Wikipedia', wikinews: 'Wikinews', arxiv: 'arXiv' }

  // the metal: the native bolt, for sources that send no CORS header
  async function metalFetch(url) {
    const P = window.parent, c = P && P.__TAURI__ && (P.__TAURI__.core || P.__TAURI__)
    if (!(c && c.invoke)) throw new Error('no bolt')
    const t = await c.invoke('fetch_page', { url })
    if (!t) throw new Error('empty')
    return t
  }
  async function grab(url, direct) {
    if (direct) { try { const r = await fetch(url); if (r.ok) return r.text() } catch (_) {} }
    return metalFetch(url)   // no third-party mirror — see the header
  }

  const strip = s => String(s || '').replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()

  // ── one fetcher per source. each returns [{title, body, link, src, kickOverride, lane}] ──
  const FETCH = {
    async wikipedia(q) {
      const u = `https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&origin=*&srlimit=6&srsearch=${encodeURIComponent(q)}`
      const d = JSON.parse(await grab(u, true))
      return (d.query?.search || []).map(r => ({
        lane: 'found', kickOverride: KICK.wikipedia, src: 'Wikipedia',
        title: r.title, body: strip(r.snippet),
        link: 'https://en.wikipedia.org/wiki/' + encodeURIComponent(r.title.replace(/ /g, '_')),
      }))
    },
    async wikinews(q) {
      const u = `https://en.wikinews.org/w/api.php?action=query&list=search&format=json&origin=*&srlimit=6&srsearch=${encodeURIComponent(q)}`
      const d = JSON.parse(await grab(u, true))
      return (d.query?.search || []).map(r => ({
        lane: 'found', kickOverride: KICK.wikinews, src: 'Wikinews',
        title: r.title, body: strip(r.snippet),
        credit: r.timestamp ? new Date(r.timestamp).toLocaleDateString() : '',
        link: 'https://en.wikinews.org/wiki/' + encodeURIComponent(r.title.replace(/ /g, '_')),
      }))
    },
    async arxiv(q) {
      // Atom, not JSON — and arXiv sends no CORS, so this always rides the bolt
      const u = `https://export.arxiv.org/api/query?max_results=6&search_query=all:${encodeURIComponent(q)}`
      const xml = await grab(u, false)
      const doc = new DOMParser().parseFromString(xml, 'text/xml')
      return Array.from(doc.getElementsByTagName('entry')).map(e => {
        const g = t => e.getElementsByTagName(t)[0]?.textContent || ''
        const who = Array.from(e.getElementsByTagName('author')).map(a => strip(a.textContent)).slice(0, 3).join(', ')
        return {
          lane: 'found', kickOverride: KICK.arxiv, src: 'arXiv',
          title: strip(g('title')), body: strip(g('summary')).slice(0, 320),
          credit: [who, g('published').slice(0, 10)].filter(Boolean).join(' · '),
          link: g('id').replace(/^http:/, 'https:'),   // arXiv hands back http; don't take the plain hop
        }
      })
    },
  }

  // ── run every source in parallel; a source that fails says so instead of vanishing ──
  async function search(q, onSource) {
    const hits = []
    await Promise.all(SOURCES.map(async name => {
      try {
        const rows = await FETCH[name](q)
        hits.push({ name, rows })
        onSource(name, rows.length, null)
      } catch (e) {
        hits.push({ name, rows: [] })
        onSource(name, 0, e.message || 'unreachable')
      }
    }))
    // round-robin so one chatty source can't own the top of the page
    const out = [], byName = Object.fromEntries(hits.map(h => [h.name, h.rows]))
    for (let i = 0; ; i++) {
      const before = out.length
      SOURCES.forEach(n => { const r = byName[n]; if (r && r[i]) out.push(r[i]) })
      if (out.length === before) break
    }
    return out
  }

  // ── SURF THE WEB — the mode toggle (Sum 2026-07-22). the named-sources search is a walled garden on
  //    purpose; surf is the deliberate step OUTSIDE it. DuckDuckGo html via the metal bolt (no CORS, no
  //    tracking cookie on the wire); we decode the uddg redirect to the real URL, and each result opens
  //    CLEAN in the Portal (route() → openPortal → OZ_READER at the reader's strip level). ──
  async function duckSearch(q) {
    const du = 'https://html.duckduckgo.com/html/?q=' + encodeURIComponent(q)
    let html = ''
    try { html = await metalFetch(du) }
    catch (_) { try { const r = await fetch(du); if (r.ok) html = await r.text() } catch (__) {} }
    // the WEB paper has no metal — OUR psv-mirror rides third (our account, origin-locked; the
    // no-third-party law in the header stands: this worker is the same trust domain as the paper)
    if (!html) try { const r = await fetch('https://psv-mirror.sumbhodi.workers.dev/?url=' + encodeURIComponent(du)); if (r.ok) html = await r.text() } catch (__) {}
    if (!html) return []
    const doc = new DOMParser().parseFromString(html, 'text/html')
    const out = [], seen = {}
    doc.querySelectorAll('a.result__a').forEach(a => {
      let href = a.getAttribute('href') || ''
      const m = /[?&]uddg=([^&]+)/.exec(href); if (m) { try { href = decodeURIComponent(m[1]) } catch (_) {} }
      if (!/^https?:\/\//i.test(href) || seen[href]) return
      seen[href] = 1
      const res = a.closest('.result, .result__body, .web-result') || a.parentElement
      const snip = res && res.querySelector('.result__snippet')
      let host = ''; try { host = new URL(href).host.replace(/^www\./, '') } catch (_) {}
      out.push({ lane: 'found', kickOverride: host || 'the web', src: host, title: strip(a.textContent), body: snip ? strip(snip.textContent) : '', link: href })
    })
    return out.slice(0, 14)
  }

  // ── the bar, mounted in the masthead ──
  function mount() {
    const SF = window.SF
    const head = document.querySelector('.sf-masthead')
    if (!head || !SF || document.getElementById('sf-search')) return
    const box = document.createElement('form')
    box.id = 'sf-search'; box.className = 'sf-search'
    box.innerHTML = `
      <button class="sf-plus" type="button" title="open ANYTHING in the Portal — a link, a saved .html, a video, an image, a local file — cleaned">＋</button>
      <button class="sf-surf" type="button" aria-pressed="false" title="surf the open web (DuckDuckGo) — results open clean in the Portal">surf</button>
      <input class="sf-q" type="search" placeholder="search the named sources… or paste a link / file" aria-label="search the named sources, or paste any link or file path to open it in the Portal">
      <button class="sf-go" type="submit">search</button>
      <button class="sf-back" type="button" hidden>← the feed</button>`
    head.appendChild(box)
    const q = box.querySelector('.sf-q'), back = box.querySelector('.sf-back'), surf = box.querySelector('.sf-surf'), plus = box.querySelector('.sf-plus')

    // ── the ＋ door (Sum 2026-07-22: "psv gets a plus, look at anything in portal") — open any link or
    //    local file (a saved .html strips clean, a video/image/audio plays) in the Portal. Enter is smart:
    //    a link OPENS, words SEARCH. ──
    const looksLikeLink = v => /^(https?|file):/i.test(v) || /^\//.test(v) || /^[\w.-]+\.[a-z]{2,}(\/|$|\?)/i.test(v)
    function openInPortal(v) {
      v = String(v || '').trim()
      if (!v) {   // empty ＋ → open SURF HOME (the blank browser: address bar + your recents)
        const R = (window.parent && window.parent.OZ_READER) || window.OZ_READER
        if (R && R.surf) { R.surf(); return }
        q.placeholder = 'paste a link or a file path — opens in the Portal'; q.focus(); return
      }
      if (!/^(https?|file):/i.test(v)) v = /^\//.test(v) ? 'file://' + v : 'https://' + v   // path → file://, bare domain → https
      const R = (window.parent && window.parent.OZ_READER) || window.OZ_READER
      if (R && R.read) R.read(v); else if (window.open) window.open(v, '_blank')
    }
    plus.addEventListener('click', () => openInPortal(q.value))

    // THE SURF edition (Sum 2026-07-25) sets scroll-surf → the board starts waxed: surf mode on,
    // the bar focused, the whole open sea behind the same Portal checkpoint + teleport.
    let surfOn = false
    let _snap = null, _snapY = 0   // the paper's own nodes, pocketed on the first dive off it (listeners intact)
    try { if (localStorage.getItem('scroll-surf') != null) { surfOn = true; surf.classList.add('on'); surf.setAttribute('aria-pressed', 'true'); q.placeholder = 'surf the open web…' } } catch (_) {}
    surf.addEventListener('click', () => {
      surfOn = !surfOn
      surf.classList.toggle('on', surfOn); surf.setAttribute('aria-pressed', surfOn ? 'true' : 'false')
      q.placeholder = surfOn ? 'surf the open web…' : 'search the named sources…'
      q.focus()
    })
    function resetBar() {
      back.hidden = true; q.value = ''
      if (surfOn) { surfOn = false; surf.classList.remove('on'); surf.setAttribute('aria-pressed', 'false'); q.placeholder = 'search the named sources…' }
    }
    // ← BACK (Sum 2026-07-27: "the feed took me back to top of feed not back to U"). re-attach the pocketed
    // paper exactly where it was; if we never pocketed one, fall back to a fresh render. NOT a page-1 reset —
    // that's the boat. wired to the masthead ← the feed AND an in-page ← back drawn at the top of results.
    function surfBack() {
      resetBar()
      const feed = SF.feed
      if (_snap) { feed.innerHTML = ''; feed.appendChild(_snap); _snap = null; if (SF.resume) SF.resume(); try { window.scrollTo(0, _snapY) } catch (_) {} }
      else { SF.render(true); try { window.scrollTo(0, 0) } catch (_) {} }
    }
    window.SF_HOME = surfBack
    back.addEventListener('click', surfBack)
    // the boat pinged home (page 1, handled in scroll.js) — just tidy this bar + drop the pocketed paper.
    window.addEventListener('storage', e => { if (e.key === 'oz-boat-home') { resetBar(); _snap = null } })

    // ── THE WAKE + THE CURATE BOX (Sum 2026-07-25: "column right is a list of links from previous
    //    searches, scrollable back, resets each session; drag a search to right to curate a few
    //    tabs; curate box stacks ABOVE history"). session-scoped on purpose — a wake dissolves. ──
    const jGet = (k, d) => { try { const v = JSON.parse(sessionStorage.getItem(k) || 'null'); return v == null ? d : v } catch (_) { return d } }
    const jSet = (k, v) => { try { sessionStorage.setItem(k, JSON.stringify(v)) } catch (_) {} }
    const escT = s => { const d = document.createElement('div'); d.textContent = String(s == null ? '' : s); return d.innerHTML }
    function logWake(term, rows) {
      const wake = jGet('sf-wake', []).filter(w => w.q !== term)
      wake.unshift({ q: term, links: rows.slice(0, 8).map(r => ({ t: r.title, u: r.link })) })
      jSet('sf-wake', wake.slice(0, 20))
    }
    function drawWake() {
      const rail = SF.rail; if (!rail) return
      const pins = jGet('sf-pins', []), wake = jGet('sf-wake', [])
      rail.innerHTML = `
        <div class="sf-widget sf-pinzone"><h3>The Curate Box</h3>
          ${pins.length ? pins.map((p, i) => `<div class="sf-wake-link"><a href="${escT(p.u)}" data-wopen="${escT(p.u)}">${escT(p.t || p.u)}</a><button type="button" class="sf-unpin" data-unpin="${i}" aria-label="unpin ${escT(p.t || 'this tab')}">✕</button></div>`).join('')
                       : '<p class="sf-pin-hint">drag a result here — a few tabs worth keeping</p>'}
        </div>
        <div class="sf-widget"><h3>The Wake</h3>
          ${wake.length ? wake.map(w => `<div class="sf-wake-run"><b class="sf-wake-q" data-wq="${escT(w.q)}" role="button" tabindex="0">${escT(w.q)}</b>${w.links.map(l => `<div class="sf-wake-link"><a href="${escT(l.u)}" data-wopen="${escT(l.u)}">${escT(l.t || l.u)}</a></div>`).join('')}</div>`).join('')
                       : '<p class="sf-pin-hint">your past searches settle here — the wake clears when you sail off</p>'}
        </div>`
      const zone = rail.querySelector('.sf-pinzone')
      zone.addEventListener('dragover', e => { e.preventDefault(); zone.classList.add('over') })
      zone.addEventListener('dragleave', () => zone.classList.remove('over'))
      zone.addEventListener('drop', e => {
        e.preventDefault(); zone.classList.remove('over')
        try {
          const d = JSON.parse(e.dataTransfer.getData('text/plain'))
          if (!d || !/^https?:/i.test(d.u || '')) return
          const cur = jGet('sf-pins', []).filter(p => p.u !== d.u)
          cur.unshift({ t: d.t, u: d.u }); jSet('sf-pins', cur.slice(0, 6)); drawWake()
        } catch (_) {}
      })
      rail.querySelectorAll('[data-wopen]').forEach(a => a.addEventListener('click', e => { e.preventDefault(); openInPortal(a.getAttribute('data-wopen')) }))
      rail.querySelectorAll('[data-unpin]').forEach(b => b.addEventListener('click', () => { const cur = jGet('sf-pins', []); cur.splice(+b.getAttribute('data-unpin'), 1); jSet('sf-pins', cur); drawWake() }))
      rail.querySelectorAll('.sf-wake-q').forEach(b => {
        const go = () => runSearch(b.getAttribute('data-wq'), surfOn)
        b.addEventListener('click', go)
        b.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); go() } })
      })
    }
    // the search body, extracted so the newsie's psv_search hand can drive it via window.SF_SEARCH.
    async function runSearch(term, useSurf) {
      term = String(term || '').trim()
      if (!term) return
      if (typeof useSurf === 'boolean' && useSurf !== surfOn) {   // a caller can set the mode (named ↔ surf)
        surfOn = useSurf; surf.classList.toggle('on', surfOn); surf.setAttribute('aria-pressed', surfOn ? 'true' : 'false')
        q.placeholder = surfOn ? 'surf the open web…' : 'search the named sources…'
      }
      q.value = term
      back.hidden = false
      SF.stop()                       // the feed steps aside; the grid reshapes (center wide, rail = the wake)
      drawWake()
      const feed = SF.feed
      if (!_snap) { _snap = document.createDocumentFragment(); _snapY = window.scrollY || 0; while (feed.firstChild) _snap.appendChild(feed.firstChild) }   // pocket the paper on the FIRST dive so ← back = back to where you were
      else feed.innerHTML = ''        // already surfing → just clear the last results
      const inBack = document.createElement('button')   // an in-page ← back, right where the eye is (Sum: "surf needs an in-page back button somewhere")
      inBack.type = 'button'; inBack.className = 'sf-more sf-inpage-back'; inBack.textContent = '← back to the paper'
      inBack.setAttribute('aria-label', 'back to the paper, where you were'); inBack.style.cssText = 'margin:2px 0 14px'
      inBack.addEventListener('click', surfBack); feed.appendChild(inBack)
      const status = document.createElement('div')
      status.className = 'sf-found-head'
      status.textContent = surfOn ? `surfing the open web for “${term}”…` : `searching ${SOURCES.length} named sources for “${term}”…`
      feed.appendChild(status)

      let rows
      if (surfOn) {
        rows = await duckSearch(term)
        status.textContent = rows.length ? `the open web · ${rows.length} results — each opens clean in the Portal ↪` : ''
      } else {
        const said = {}
        rows = await search(term, (name, n, err) => {
          said[name] = err ? `${KICK[name]} unreachable` : `${KICK[name]} ${n}`
          status.textContent = SOURCES.map(s => said[s] || `${KICK[s]}…`).join('   ·   ')
        })
      }
      if (!rows.length) {
        const none = document.createElement('div')
        none.className = 'sf-empty'
        none.textContent = surfOn
          ? `the web came back empty for “${term}” (or the surf channel’s down) — try again, or flip back to the named sources.`
          : `nothing for “${term}”.\nthese are libraries, not the whole web — try the surf button, or a plainer word.`
        feed.appendChild(none)
        return
      }
      rows.forEach(r => {
        const c = SF.card(r)
        if (r.link) {   // a result is a tab you might keep — draggable into the curate box
          c.draggable = true
          c.addEventListener('dragstart', e => { try { e.dataTransfer.setData('text/plain', JSON.stringify({ t: r.title, u: r.link })) } catch (_) {} })
        }
        feed.appendChild(c)
      })
      logWake(term, rows)
      drawWake()
    }
    window.SF_SEARCH = (term, useSurf) => runSearch(term, useSurf)   // the newsie's psv_search seam
    // THE SURF REPORT (Sum 2026-07-25: "a different surf topic on each edition and just hit
    // fire — surf opens with fresh links each hour"). the surf edition auto-paddles out: the
    // topic of the hour, real live results, every wave through the Portal checkpoint.
    try {
      if (localStorage.getItem('scroll-surf') != null) {
        const SETS = ['james webb telescope latest images', 'new species discovered', 'deep sea creatures',
          'archaeology discovery', 'trending open source projects', 'robotics breakthrough',
          'solar power innovation', 'national park hidden gems', 'street art around the world',
          'jazz history', 'vintage computing', 'typography design', 'citizen science projects',
          'volcano eruption latest', 'mars rover news', 'urban gardening ideas',
          'woodworking craftsmanship', 'surprising word origins', 'old maps cartography',
          'independent film gems', 'board game design', 'rare bird sightings',
          'northern lights forecast', 'ocean cleanup progress']
        runSearch(SETS[new Date().getHours() % SETS.length], true)
      }
    } catch (_) {}
    // Enter is smart: paste a link (or a file path) → it OPENS in the Portal; type words → it SEARCHES.
    box.addEventListener('submit', e => {
      e.preventDefault()
      const v = q.value.trim()
      if (!surfOn && looksLikeLink(v)) openInPortal(v); else runSearch(v, surfOn)
    })
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount)
  else mount()
})()
