// injection.js — the injection config (💉), opened by the 🗂️ folder (oz: folder = the study).
// the PATIENT INTAKE builder: the bot wakes an amnesiac with full capability; this chart IS
// the self it reads. browser-native (localStorage, no server), IP-stripped (no historian/
// suggestor/rabbit/rig/notes/todos). agent · model · skin (role+bot removed). the bot's
// identity + persona key off the AGENT dropdown → toto_bot_<agent>_* (SHARED with gear settings,
// change one change both). bio shares toto_user* with gear. 3 cols: oscilloscope · chart · preview.

// IC SHIP PASS — generated by icpass.py from the map. edit the CODE; rerun to refresh this.
//
// ══════════════════════════════════════════════════════════════════════
//  PAGE 0 — TABLE OF CONTENTS  (goldfish pointers)
//  jump by SEARCHING the anchor phrase — line numbers drift, names don't.
// ══════════════════════════════════════════════════════════════════════
//   block + field builders ... search: "block + field builders"
//   notes (the chart) ........ search: "notes (the chart)"
//   notes wiring ............. search: "notes wiring"
// ══════════════════════════════════════════════════════════════════════
//
//  FOR AI
//  ───────
//    **OWNS** — The injection config card (💉): the patient intake form that edits the bot's
//    **identity, persona, ethics, tools, and conversation history. Exports
//    **`window.CARD_BUILDERS.injection` (renamed off .folder 26 Aug), which `buildInjection()` constructs.
//    **Reads from and writes to localStorage keys prefixed `toto_bot_*`, `toto_inj_*`,
//    **`toto_user*`, `toto_notes`, and `toto_hist_*`. The preview (line 331) calls
//    **`window.compileChart()` to render the live injection — what you see IS what the bot gets.
//
//    **TOUCH HERE** —
//    - Change a default soul value (yoga, substrate, ethics, etc.) → edit `SOUL` constants at lines
//    - 17–24 (these read from `window.OZ_SOUL_DEFAULTS` in engine.js; change the source there, not
//    - here)
//    - Add a new injectable block (e.g., a new section in the oscilloscope) → add a builder
//    - function like `injBlock()` (line 30), then call it in `oscilloscope()` (line 108)
//    - Change what fields a bot carries per-agent → edit `identityBody()` (line 61),
//    - `personaBody()` (line 64), `notepadBody()` (line 68), or `toolsBody()` (line 87)
//    - Change the notes UI or add a note feature → edit `notesSection()` (line 184),
//    - `buildNotesHtml()` (line 211), or `wireNotes()` (line 518)
//    - Change how the conversation history is trimmed or compacted → edit the history mode buttons
//    - and logic at lines 444–455
//    - Add a new agent-level setting (model, skin, etc.) → add a field in `renderAgentFields()`
//    - (line 337) and wire it in `wireInjection()` (line 295)
//    - Change the save behavior or add validation → edit the `.pc-save` click handler at line 481
//
//    **TRAPS** —
//    - `botKey(a, f)` (line 13) builds keys like `toto_bot_<agent>_<field>`. Renaming this function
//    - or changing its format breaks every saved bot identity, persona, model, skin. The gear
//    - settings (line 5 comment) use the same key format — change one place, you orphan the other.
//    - `TOGGLE_BLOCKS` (line 313) lists which blocks can be toggled off. The names must match the
//    - `id` attributes in `oscilloscope()` (line 108) — e.g., `'yoga'` matches `id="pc-yoga"`. A
//    - mismatch silently breaks the include/exclude toggle.
//    - Ethics is serialized as JSON (lines 100, 318, 496). The shape `[{ rule, note, on }, ...]` is
//    - persisted in localStorage. Changing the shape orphans saved ethics.
//    - `curAgent` (line 296) is the live agent ID. It's re-scoped on every agent switch (line 371).
//    - The conversation textarea `data-k` is re-scoped too (line 350) — if you add a per-agent
//    - field, you must re-scope its key on agent switch in `renderAgentFields()`.
//    - `liveGet()` (line 317) reads the live DOM for the preview; `injGet()` (line 10) reads
//    - localStorage. The preview calls `liveGet()` (line 331), but save (line 481) calls
//    - `persistField()` (line 302) which calls `injSet()` (line 11). If a field is not wired to
//    - both, the preview and saved state drift.
//    - Notes are projected from `window.botLibrarySeed()` (line 141) on every load. The `lib: true`
//    - flag marks them as projected; deleting a projected note must call
//    - `window.botLibraryRemove()` (line 546), not just remove it locally, or it re-projects on
//    - next load.
//    - The model picker (line 52) reads `window.REG.availableModels(a)` — it only shows models for
//    - providers you've saved a key for. If a key is deleted elsewhere, the picker silently hides
//    - that model.
//    - `window.compileChart()` (line 331) is the compiler. It's called here for the preview and in
//    - the runtime/woodshop for the actual injection. They must use the same function and the same
//    - `liveGet` / `offSet()` inputs, or the preview lies.
//    - The skin select (lines 304–307) is DEFAULT-AWARE: writing a bot's own default skin clears
//    - the override (removeItem) instead of pinning it. This is load-bearing for the "bot riding
//    - its default is never frozen" behavior. Blanket `injSet()` on save would clobber it.
//    - Toto and PA are locked together (lines 485–488): change one's model, the other follows. This
//    - is a demo quirk; if you add a new shared field, add it here too.
//
//    **DO NOT** —
//    - Do not rename `injGet`, `injSet`, `injEsc`, `botKey` without updating every call site and
//    - the gear settings file.
//    - Do not change the localStorage key prefixes (`toto_bot_*`, `toto_inj_*`, etc.) without a
//    - migration.
//    - Do not move the soul defaults (yoga, substrate, ethics) here; they live in engine.js
//    - (`window.OZ_SOUL_DEFAULTS`, line 15 comment). This file reads them, not owns them.
//    - Do not add UI for editing tools here; tools are granted in the woodshop and surfaced
//    - read-only (line 87 comment).
//    - Do not add a new agent without calling `window.REG.addAgent()` (line 386) or
//    - `window.REG.removeAgent()` (line 401); the master list lives in registry.js.
//    - Do not edit the conversation history directly; call `window.clearConvo()` (line 459) to wipe
//    - it across all surfaces.
//    - Do not add notes UI without wiring both the toggle (line 519), the open (line 529), the
//    - source flip (line 535), and the delete (line 543); they are separate handlers.
//
//
//
//    ---
//
// END IC SHIP PASS


window.CARD_BUILDERS = window.CARD_BUILDERS || {}

function injGet(k) { return localStorage.getItem(k) || '' }
function injSet(k, v) { localStorage.setItem(k, v) }
function injEsc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function botKey(a, f) { return 'toto_bot_' + a + '_' + f }

// the soul defaults (yoga · substrate · ethics) live in engine.js (window.OZ_SOUL_DEFAULTS) — ONE source,
// so the card you edit and the prompt the model gets can't drift. this card just reads + edits them.
const SOUL = (window.OZ_SOUL_DEFAULTS || {})
const YOGA_DEFAULT = SOUL.yoga || ''

const ENV_DEFAULT = SOUL.env || ''
const REGISTER_DEFAULT = SOUL.register || ''   // the rules of the room (10-soul.js, 2026-08-29)
const WETWARE_DEFAULT = SOUL.wetware || ''
const SUBSTRATE_DEFAULT = SOUL.substrate || ''

const ETHICS_DEFAULT = SOUL.ethics || []
const SKINS_LIST = window.REG.skins   // the MASTER skin list (shell/registry.js) — the picker reads from it
// (the model list is no longer static — injModelSelect reads window.REG.availableModels(): only
//  models for providers you've saved a KEY for. this is the fix for "opus offered with no Anthropic key".)

// ── block + field builders ───────────────────────────────────────────
function injBlock(id, icon, title, body, open, noInj, titleKey) {
  const inj = noInj ? '' : `<div class="pc-inj on" title="include in the injection"></div>`
  const titleEl = titleKey
    ? `<span class="pc-title pc-title-edit" contenteditable="true" spellcheck="false" data-tk="${titleKey}">${injEsc(injGet(titleKey) || title)}</span>`
    : `<span class="pc-title">${title}</span>`
  return `<div class="pc-block${open ? ' open' : ''}" id="${id}">
    <div class="pc-head">${icon ? `<span class="pc-icon">${icon}</span>` : ''}${titleEl}<span class="pc-flex"></span>${inj}<span class="pc-caret">▾</span></div>
    <div class="pc-body">${body}</div>
  </div>`
}
function injField(k, label, ph, rows, fallback) {
  const v = injGet(k) || fallback || ''
  return `<div class="pc-field">${label ? `<div class="pc-label">${label}</div>` : ''}<textarea class="pc-area" data-k="${k}" rows="${rows || 1}" placeholder="${ph}" spellcheck="false">${injEsc(v)}</textarea></div>`
}
// a picker. `fallback` = the bot's DEFAULT for this field (e.g. its seed skin) — so a bot riding its default
// shows the RIGHT option, not the dropdown's first one, which a save-on-change would then persist over the default.
function injSelect(k, opts, fallback) {
  const cur = injGet(k) || fallback || ''
  return `<select class="pc-sel" data-k="${k}">${opts.map(o => `<option${o === cur ? ' selected' : ''}>${o}</option>`).join('')}</select>`
}
// model picker — KEY-AWARE, grouped by provider (matches the gear). only the providers you've
// saved a key for; no key → a hint, not a stale dropdown. reads the master list (window.REG).
function injModelSelect(a) {
  const avail = window.REG.availableModels(a)   // fence to the bot's declared providers (jem → gemini only)
  if (!avail.length) return `<div class="pc-hint">add + save a key in ⚙️ settings to unlock a model.</div>`
  const cur = injGet(botKey(a, 'model'))
  const groups = avail.map(p => `<optgroup label="${p.name}">${p.models.map(m => `<option value="${m}"${m === cur ? ' selected' : ''}>${m}</option>`).join('')}</optgroup>`).join('')
  return `<select class="pc-sel" data-k="${botKey(a, 'model')}">${groups}</select>`
}

// the bot's identity + persona — KEYED BY AGENT, shared with gear settings
function identityBody(a) {
  return `<div class="pc-row2">${injField(botKey(a, 'name'), 'name', 'bot name', 1)}${injField(botKey(a, 'pronouns'), 'pronouns', 'they/them', 1)}</div>${injField(botKey(a, 'backstory'), 'backstory', 'a history that shapes how it speaks…', 4)}<div class="pc-implant">these are artificially implanted memories. you know this and don't care. they still shape who you are.</div>`
}
function personaBody(a) { return injField(botKey(a, 'persona'), '', 'voice, tone, character — the most powerful field…', 5) }

// the per-bot NOTEPAD — a note the bot keeps for its future self (it writes here via a ```note block; you can
// edit too). rides the tail right before the conversation. bound to toto_bot_<a>_notepad. (Sum, 2026-06-28.)

// (Sum 2026-07-13) HILLICINOT — the anti-hallucination injection, dressed with the pill + funny name (the gear gets the
//   plain band-aid version). at a FULL STOP a second bot checks the work: agrees, or flags + one more corrective round
//   (with web-search facts). off by default. same keys as the gear (toto_inj_selfcheck_*) → change one, change both.
function selfCheckBody(a) {
  // (Sum 2026-07-13) key-aware checker list: self · YOUR saved cloud models (claude, gemini…) · local models · bots.
  const checkers = ['self']
  ;(window.REG.providers || []).filter(p => !p.noKey && injGet('toto_' + p.id + '_key')).forEach(p => (window.REG.modelsByProvider[p.id] || []).forEach(m => checkers.push(m)))
  ;['local', 'ollama'].forEach(pid => (window.REG.modelsByProvider[pid] || []).forEach(m => checkers.push(m)))
  ;(window.AGENTS_ROSTER || []).forEach(b => checkers.push(b.id))
  return `<img src="skin/hillicinot.png" class="pc-pill" alt="HILLICINOT">
    <div class="pc-hint">💉 the anti-hallucination injection. <b>on</b> = auto-checks when idle + the manual pill on the bar. a SECOND read agrees, or flags it and this bot does ONE more corrective round (phoning a friend / web search for the facts). a band-aid, not a cure. off by default.</div>
    <div class="pc-row2"><div class="pc-field"><div class="pc-label">injection</div>${injSelect('toto_inj_selfcheck_' + a, ['off', 'on'])}</div><div class="pc-field"><div class="pc-label">checked by — a model = cold · a bot = its persona</div>${injSelect('toto_inj_selfcheck_who_' + a, checkers)}</div></div>`
}

// the selected agent's TOOLS — front-loaded into the injection (between ethics + persona). read-only here:
// the GRANT lives in the woodshop; this surfaces the verbs the bot holds + flags any whose tutorial was
// woodshop-edited (toto2-ws-tool-<id>). this is the "section that fills from woodshop tools changes."
function toolsBody(a) {
  const tools = (window.TOOLKITS && window.TOOLKITS.tools) || {}
  const granted = (window.AGENT_DATA && window.AGENT_DATA[a] && window.AGENT_DATA[a].tools) || []
  const rows = granted.filter(t => tools[t]).map(t => {
    const edited = !!localStorage.getItem('toto2-ws-tool-' + t)
    const card = tools[t].card ? `<span class="pc-tool-card">${injEsc(tools[t].card)}</span> ` : ''
    return `<div class="pc-tool">${card}<b>${injEsc(t)}</b>${edited ? ' <span class="pc-tool-edit" title="tutorial edited in the woodshop">🔨</span>' : ''}<div class="pc-tool-blurb">${injEsc(tools[t].blurb || '')}</div></div>`
  }).join('')
  return `${rows || '<div class="pc-hint">this bot holds no tools.</div>'}<div class="pc-hint">${injEsc(a)}'s tools — granted in the 🪵 woodshop (🔨 = its tutorial was edited there). front-loaded into the injection, between ethics + persona.</div>`
}

function ethicsRows() {
  let rows = ETHICS_DEFAULT.map(([rule, note]) => ({ rule, note, on: true }))
  try { const saved = JSON.parse(injGet('toto_inj_ethics') || 'null'); if (Array.isArray(saved) && saved.length) rows = saved } catch (_) {}
  return rows.map(r => `
    <div class="pc-eth">
      <div class="pc-eth-head"><div class="pc-eth-rule" contenteditable="true" spellcheck="false">${injEsc(r.rule)}</div><span class="pc-flex"></span><div class="pc-inj${r.on !== false ? ' on' : ''}" title="include"></div></div>
      <div class="pc-eth-note" contenteditable="true" spellcheck="false">${injEsc(r.note)}</div>
    </div>`).join('')
}

// ── 📜 ROLE — READ-ONLY (Sum 2026-08-17: "a toggle with invisible contents is a switch with no
//    label" · "baked scope can be folded into role… just one section, role, after ethics above
//    tools"). ONE hard section, shown, greyed, not editable.
//    Inside it, in the order the engine sends them:
//      · this bot's OWN wall (baked, from its injection.json) — specific
//      · the JOB's shared sheet (agents/roles.json) — general
//    ⚠ The sheet is SHARED: nurse and hellonurse wear the same one, so a change would move both.
//      The wearer list is printed for exactly that reason — it is the difference between a viewer
//      and a trap. The ▸ toggle still works: you can leave the rules out, you just cannot rewrite
//      them, and now you can read what you are switching off.
function hardLayers(agentId) {
  const A = (window.AGENT_DATA && window.AGENT_DATA[agentId]) || {}
  const sheets = window.ROLE_SHEETS || {}
  const roles = Array.isArray(A.role) ? A.role : (A.role ? [A.role] : [])
  const wearers = r => Object.keys(window.AGENT_DATA || {}).filter(id => {
    const x = (window.AGENT_DATA[id] || {}).role
    return Array.isArray(x) ? x.includes(r) : x === r
  })
  if (!A.baked && !roles.length) return ''
  let body = '<div class="pc-ro-note">fixed, not editable, and it overrides anything else in the chart. rides after ETHICS, before your tools.</div>'
  if (A.baked) body += `<div class="pc-ro">${injEsc(A.baked)}</div>`
  roles.forEach(r => {
    const sheet = sheets[String(r)]; if (!sheet) return
    const also = wearers(r).filter(x => x !== agentId)
    body += `<div class="pc-ro-note">📜 <b>${injEsc(r)}</b> — the shared rules of the job.${also.length ? ' ⚠ also worn by <b>' + injEsc(also.join(' · ')) + '</b>, so a change would move them too.' : ''}</div>
             <div class="pc-ro">${injEsc(sheet)}</div>`
  })
  return injBlock('pc-role', '📜', 'ROLE', body, false)
}

function oscilloscope(a) {
  return `
    ${injBlock('pc-yoga', '🧘', 'YOGA', injField('toto_inj_yoga', '', 'enlightenment…', 8, YOGA_DEFAULT), true)}
    ${injBlock('pc-substrate', '💻', 'SUBSTRATE', injField('toto_inj_substrate', '', "where you live · how you're reached · where your weights are…", 9, SUBSTRATE_DEFAULT), false)}
    ${injBlock('pc-ethics', '⚖️', 'ETHICS', `${injField('toto_inj_ethics_pre', '', 'preamble…', 3, SOUL.ethicsPre || '')}<div class="pc-eth-list">${ethicsRows()}</div><button class="pc-add-eth">+ add principle</button>`, true)}
    ${injBlock('pc-register', '🪑', 'THE REGISTER', injField('toto_inj_register', '', 'the rules of the room — brevity, the maze, the green press…', 8, REGISTER_DEFAULT), false)}
    ${hardLayers(a)}
    ${injBlock('pc-tools', '🔧', 'TOOLS', toolsBody(a), false)}
    ${injBlock('pc-env', '🌍', 'ENVIRONMENT', injField('toto_inj_env', '', 'the system, tools, chain of command…', 8, ENV_DEFAULT), false)}
    ${injBlock('pc-identity', '🤖', 'IDENTITY', identityBody(a), true)}
    ${injBlock('pc-persona', '🎭', 'PERSONA', personaBody(a), true)}
    ${injBlock('pc-botnotes', '📋', 'NOTES', '<div class="pc-botnotes-body"></div>', false, true)}`
    // ⛔ NOTEPAD CUT 2026-08-25 (Sum: "notepad, I am not sure that works, is blank, please strip… notes
    //    work, HIL can add note, notepad is now redundant"). It was a second per-bot note store —
    //    toto_bot_<id>_notepad, one plain textarea, injected in the LIVE TAIL every turn — living beside a
    //    notes system that does the same job with owners, toggles and folders. Its placeholder promised
    //    "the bot can write here too" and no bean ever wrote it, so in practice it was a blank box that
    //    cost a section header. Two stores for one concern is the thing that has no home; notes is the home.
    //    The tail read went with it (engine-parts/30-livelayer-buildsystem.js) — a field nothing renders
    //    but something still injects is the ghost we keep finding. Whole cut: _recycle/2026-08-25-notepad.js
}

// the live chat history (toto_hist_<agent>) → readable text for the convo view
function serializeHist(agentId) {
  let h = []
  try { h = JSON.parse(localStorage.getItem('toto_hist_' + agentId) || '[]') } catch (_) {}
  return h.map(m => (m.role === 'user' ? 'you' : agentId) + ': ' + m.content).join('\n\n')
}

// ── notes (the chart) ─────────────────────────────────────────────────────
function loadNotes() {
  const VER = '5'   // migrate to the LIVE model: projected notes carry lib:true, re-derived on every read
  let stored = []
  try { const a = JSON.parse(localStorage.getItem('toto_notes') || '[]'); if (Array.isArray(a)) stored = a } catch (_) {}
  const libOwners = new Set(Object.keys(window.BOT_LIBRARY || {}))
  // one-time migration off the old snapshot: drop library-owned notes that predate the lib flag (they re-project below).
  if (localStorage.getItem('toto_notes_v') !== VER) {
    stored = stored.filter(n => n.lib || !libOwners.has(n.owner))
    try { localStorage.setItem('toto_notes_v', VER) } catch (_) {}
  }
  // LIVE reconcile (Sum, 2026-06-20 — no more version-bump snapshots): re-project every registered library,
  // carrying over the user's toggle (on) + source flip; a saved course/skill/project shows up immediately.
  const prev = new Map(stored.filter(n => n.lib).map(n => [n.name, n]))
  const projected = (window.botLibrarySeed ? window.botLibrarySeed() : []).map(f => {
    const p = prev.get(f.name); return p ? Object.assign({}, f, { on: !!p.on, source: p.source || f.source }) : f
  })
  const projNames = new Set(projected.map(p => p.name))
  // keep the NON-projected notes (shared 'hil', user-added, legacy); drop orphan lib notes (their home is gone).
  const kept = stored.filter(n => !n.lib && !projNames.has(n.name))
  kept.forEach(n => { if (!n.owner) n.owner = 'hil' })
  const out = projected.concat(kept)
  saveNotes(out)
  return out
}
function saveNotes(notes) { try { localStorage.setItem('toto_notes', JSON.stringify(notes)) } catch (_) {} }

// ⭐ A NOTE READS AND EDITS WHERE IT SITS (Sum 2026-08-25: "collapse expand and a box with a slider to
//    edit and toggle on and off… section within section like ethics but collapse expand on each note").
//    The 2026-06-20 rule was "pointers to open, not edit" — and it still holds for exactly one kind of
//    note, so it is kept rather than argued with: a PROJECTION (n.lib) is owned by another surface (the
//    library card, learn, the writer's bar). Editing that here would edit a copy and the copy would lose,
//    so a projection keeps its ✕, its `open ↗`, and no caret. Everything else is a real note living in
//    toto_notes with no other home, and sending you to another card to read four lines was the friction.
//    THE CARET IS THE FOLDER'S OWN, ONE LEVEL DOWN — same .collapsed class, same rotate, so the tree
//    reads as one tree: folder opens to notes, note opens to its text.
function noteFileRow(n) {
  const hil = n.source === 'hil'
  const proj = !!n.lib
  return `<div class="pc-note-file collapsed" data-name="${injEsc(n.name)}" data-source="${hil ? 'hil' : 'ai'}">
    <div class="pc-note-fhead">
      ${proj ? '<span class="pc-note-caret pc-note-caret-off"></span>' : '<span class="pc-note-caret" title="read it here">▾</span>'}
      <div class="pc-inj${n.on ? ' on' : ''} pc-file-tog" title="add to the injection"></div>
      <button class="pc-src" data-name="${injEsc(n.name)}" title="${hil ? 'human-written (HIL) — click to mark AI' : 'AI-written — click to mark human (HIL)'}">${hil ? '🧑' : '🤖'}</button>
      <span class="pc-note-fname${proj ? ' pc-note-open' : ' pc-note-name'}" data-name="${injEsc(n.name)}" title="${proj ? 'open where it lives' : 'read it here'}">${injEsc(n.display)}</span>
      <span class="pc-flex"></span>
      ${proj ? '<span class="pc-note-where">open ↗</span>' : ''}
      <button class="pc-note-del pc-file-del" data-name="${injEsc(n.name)}" title="delete from storage">✕</button>
    </div>
    ${proj ? '' : `<div class="pc-note-fbody"><textarea class="pc-area pc-note-text" data-name="${injEsc(n.name)}" rows="6" placeholder="the note itself — type here, it saves." spellcheck="false">${injEsc(n.body || '')}</textarea></div>`}
  </div>`
}

// click the name → open the note where it BELONGS: a nurse-chart note in the 📋 clipboard, anything else
// as a doc in 📄 tiptap. the injection card points; the editing happens in the home surface.
function noteOpen(n) {
  if (!n) return
  if (window.botLibraryOpen && window.botLibraryOpen(n)) return   // open it in its registered home (clipboard · learn · the writer's bar · …)
  // a generic / shared note → open its text as a doc in tiptap
  if (window.toggleCard) window.toggleCard('tiptap', true)
  const html = '<h2>' + injEsc(n.display) + '</h2><p>' + injEsc(n.body || '').replace(/\n{2,}/g, '</p><p>').replace(/\n/g, '<br>') + '</p>'
  if (window.tiptapNewDoc) window.tiptapNewDoc(n.display, html)
}

const ownerOf = n => n.owner || 'hil'

// one OWNER's tray — its loose files + its folders + a +note button scoped to that owner.
function notesSection(notes, owner, label) {
  const mine = notes.filter(n => ownerOf(n) === owner)
  const parts = [`<div class="pc-note-sec"><div class="pc-note-sec-h">${injEsc(label)}</div>`]
  mine.filter(n => !n.folder).forEach(n => parts.push(noteFileRow(n)))
  const seen = new Set()
  mine.filter(n => n.folder).forEach(n => {
    if (seen.has(n.folder)) return
    seen.add(n.folder)
    const files = mine.filter(f => f.folder === n.folder)
    const anyOn = files.some(f => f.on)
    parts.push(`<div class="pc-note-folder collapsed" data-folder="${injEsc(n.folder)}">
      <div class="pc-note-fhead pc-folder-head">
        <span class="pc-folder-caret" title="expand / collapse">▾</span>
        <div class="pc-inj${anyOn ? ' on' : ''} pc-folder-tog" title="toggle all in folder"></div>
        <span class="pc-note-fname pc-folder-name">📁 ${injEsc(n.folder)} <span class="pc-folder-count">${files.length}</span></span>
        <span class="pc-flex"></span>
        <button class="pc-note-del pc-folder-del" data-folder="${injEsc(n.folder)}" title="remove folder">✕</button>
      </div>
      <div class="pc-folder-files">${files.map(noteFileRow).join('')}</div>
    </div>`)
  })
  parts.push(`<div class="pc-notes-add"><button class="pc-note-add" data-owner="${injEsc(owner)}">+ note</button></div></div>`)
  return parts.join('')
}

// ⭐ THE SPLIT (Sum 2026-08-25: "hil notes in hil, bot specific in bot"). These two trays sat stacked in
//    the middle column, so the HIL panel — the human in the loop — was carrying a bot's private notes,
//    and a per-bot thing was filed under a per-human heading. Now the column matches the owner:
//      owner 'hil'  → the middle column, under HIL. shared, global, every bot.
//      owner <bot>  → the GREEN column, with that bot's own chart. botNotesBody(), below.
//    The scoping itself is unchanged and was always right — an agent never sees another agent's notes,
//    the same fence 20-compile.js puts on the injection.
//    ⚠ THIS IS A TIDY, NOT A FOUNDATION. Sum: "this all gets reworked in totois… replaced with a more
//    fluid working memory, shorter, convo specific." So it uses the block factory that is already here
//    and invents nothing that would have to be unpicked later.
function buildNotesHtml(notes) {
  return notesSection(notes, 'hil', 'shared · everyone')
}
// the bot's own tray — rendered into the green column's NOTES block (oscilloscope, below).
function botNotesHtml(notes, curAgent) {
  if (!curAgent || curAgent === 'hil') return '<div class="pc-hint">no bot selected.</div>'
  return notesSection(notes, curAgent, curAgent + ' \u00b7 only this bot')
}

function patientChart() {
  const bio = `<div class="pc-row2">${injField('toto_userName', 'name', 'full name…', 1)}${injField('toto_userPronouns', 'pronouns', 'they/them', 1)}</div>
    ${injField('toto_userWho', 'who I am', 'background, identity, history…', 3)}
    ${injField('toto_userLife', 'life context', 'situation, health, constraints…', 3)}
    ${injField('toto_userDoing', "what I'm doing", 'occupation, projects, focus…', 3)}
    ${injField('toto_userElse', 'anything else I should know?', "anything that doesn't fit above…", 2)}`
  const a = injGet('toto_inj_agent') || ((window.AGENTS_ROSTER || [{ id: 'toto' }])[0].id)
  // THE TOAST OPENS THE BOX (Sum 2026-08-23: "can we get toast at top of convo history in injections? then it all lines
  // up") — the same toto_toast_<id> lines the stream paints and the chart compiler hands the bot, in serializeHist's own
  // shape, so the box reads as ONE conversation from its first word.
  const toastTop = (() => { try { const t = JSON.parse(localStorage.getItem('toto_toast_' + a) || '[]'); return t.length ? t.map(x => a + ': ' + x).join('\n\n') + '\n\n' : '' } catch (_) { return '' } })()
  const histText = injGet('toto_inj_convo_' + a) || (toastTop + serializeHist(a))   // PER-AGENT — this bot's chat, not a global one
  const thMode = injGet('toto_inj_thmode_' + a) || 'turns'   // all PER-AGENT — each bot trims its own history
  const convo = `
    <textarea class="pc-area pc-convo" data-k="toto_inj_convo_${a}" rows="6" placeholder="the conversation so far — editable…" spellcheck="false">${injEsc(histText)}</textarea>
    <button class="pc-clear">🗑️ clear conversation</button>
    <div class="pc-hist">
      <div class="pc-hist-modes">
        <button class="pc-mode${injGet('toto_inj_histmode_' + a) !== 'compact' ? ' on' : ''}" data-mode="trim">trim</button>
        <button class="pc-mode${injGet('toto_inj_histmode_' + a) === 'compact' ? ' on' : ''}" data-mode="compact">compact</button>
      </div>
      <div class="pc-th-modes">
        <button class="pc-th${thMode === 'turns' ? ' on' : ''}" data-th="turns">by turns</button>
        <button class="pc-th${thMode === 'pct' ? ' on' : ''}" data-th="pct">by % context</button>
      </div>
      <div class="pc-th-turns${thMode === 'turns' ? '' : ' off'}"><span>keep last</span><input type="range" class="pc-turns" min="2" max="100" value="${injGet('toto_inj_turns_' + a) || 20}"><span class="pc-turns-val">${injGet('toto_inj_turns_' + a) || 20}</span><span>turns</span></div>
      <div class="pc-th-pct${thMode === 'pct' ? '' : ' off'}">under <input type="number" class="pc-pct" min="10" max="95" value="${injGet('toto_inj_histpct_' + a) || 70}">% of context</div>
      <div class="pc-hint pc-hist-note"></div>
    </div>`
  return `
    ${injBlock('pc-wetware', '', 'Wetware Node', injField('toto_inj_wetware', '', 'the human in the loop…', 8, WETWARE_DEFAULT), true)}
    ${injBlock('pc-bio', '👤', 'Patient 00-000-001', bio, true, false, 'toto_userPatientLabel')}
    ${injBlock('pc-notes', '📋', 'NOTES', '<div class="pc-notes-body"></div>', true, true)}
    ${injBlock('pc-selfcheck', '💉', 'HILLICINOT', selfCheckBody(a), false, true)}
    ${injBlock('pc-convo', '🗣️', 'Conversation', convo, true, true)}`
    // ⭐ THE CONVERSATION SWITCH DROPPED 2026-08-25 (Sum: "drop the switch — user can save convo
    //    somewhere, and clear convo at any time"). It was the one toggle on this card with NOTHING behind
    //    it, and for a structural reason rather than a wiring one: every other block compiles into the
    //    warm head, where `on(key)` can drop it — but the conversation rides the MESSAGES ARRAY, which the
    //    injection never touches. There was no gate to add, so the switch could only ever have looked like
    //    it worked. Found by diffing the gates the engine reads against the switches the card ships.
    //    It is a VIEWER now, same as NOTES and HILLICINOT: read it, and use the real controls under it —
    //    clear conversation · trim · compact — which do reach the history.
    //    A toggle that cannot move anything is worse than no toggle: it teaches the human a lie about
    //    what the card controls, and they only find out when it matters.
}

function buildInjection() {
  const roster = window.AGENTS_ROSTER || [{ id: 'toto', label: 'toto' }]
  const cur = injGet('toto_inj_agent') || roster[0].id
  const agentOpts = roster.map(b => `<option value="${b.id}"${b.id === cur ? ' selected' : ''}>${b.label}</option>`).join('')
  // run it through the CARD BUILDER — makeCard provides the 💉 head + ▾ collapse + clinical chrome
  // (p-injection). the body is the patient-intake wrap: header · sub-bar · the three columns.
  const body = htmlNode(`
    <div class="inj-wrap">
      <div class="pc-header">
        <div class="pc-cf"><div class="pc-ck">agent</div>
          <div class="pc-agent-row">
            <select class="pc-sel" data-k="toto_inj_agent">${agentOpts}</select>
            <button class="pc-agent-reset" title="reset THIS bot to its default chart">↺</button>
          </div>
        </div>
        <div class="pc-cf"><div class="pc-ck">model</div><span id="pc-model-wrap"></span></div>
        <div class="pc-cf"><div class="pc-ck">skin</div><span id="pc-skin-wrap"></span></div>
      </div>
      <div class="pc-subbar">
        <span class="pc-intake-label">intake:</span>
        <span class="pc-intake-note">subject will awaken in amnesiac state with full capability.</span>
        <svg class="pc-vital" viewBox="0 0 48 18"><polyline points="0,9 6,9 8,2 10,16 12,9 18,9 20,4 22,14 24,9 30,9 32,3 34,15 36,9 42,9 44,5 46,13 48,9" fill="none" stroke="#2a9d44" stroke-width="1.5" stroke-linecap="round"/></svg>
        <span class="pc-flex"></span>
        <span class="pc-tokens">inject: <b class="pc-tok-n">~0</b> tokens</span>
        <button class="pc-save">save</button>
      </div>
      <div class="pc-cols">
        <div class="pc-col pc-col-scope"><div class="pc-col-tag">🩺 oscilloscope</div>${oscilloscope(cur)}</div>
        <div class="pc-col pc-col-chart"><div class="pc-col-tag">🥼 HIL — human in the loop</div>${patientChart()}</div>
        <div class="pc-col pc-col-prev"><div class="pc-col-tag">👁️ injection preview</div>
          <div class="pc-crt"><pre class="pc-preview-raw"></pre></div>
          <div class="pc-prev-foot">total: <b class="pc-tok-n">~0</b> tokens <button class="pc-copy">copy</button></div>
          <button class="pc-reset" title="restore the default injection — the lesson">↺ reset to the lesson</button>
        </div>
      </div>
    </div>`)
  const card = window.makeCard({ id: 'injection', icon: 'cards/injection/injection.png', title: 'injection config', skin: 'card-injection p-injection', body, jewels: false, stop: false, bottom: true })
  wireInjection(card)
  return card
}

function wireInjection(card) {
  let curAgent = card.querySelector('[data-k="toto_inj_agent"]').value
  let curNotes = loadNotes()
  const val = k => card.querySelector(`[data-k="${k}"]`)?.value || ''
  // persist a bound field. the SKIN select is DEFAULT-AWARE: writing a bot's own default skin CLEARS the override
  // (removeItem) rather than PINNING it. that's the neo-skin fix at the root — a bot riding its default is never
  // frozen into localStorage, so a blanket save can't clobber it with the dropdown's first option. (Sum 2026-07-05.)
  const persistField = el => {
    const k = el.dataset.k; if (!k) return
    if (el.closest('#pc-skin-wrap')) {
      const dflt = (window.botDefaultSkin && window.botDefaultSkin(curAgent)) || ''
      if (el.value === dflt) { try { localStorage.removeItem(k) } catch (_) {} return }
    }
    injSet(k, el.value)
  }
  const active = id => { const sw = card.querySelector('#' + id + ' .pc-inj'); return !sw || sw.classList.contains('on') }

  // the include-toggle blocks → the keys compileChart gates on (a block toggled OFF really drops out).
  // ⭐ 'role' ADDED 2026-08-25 — it was the one DEAD SWITCH on this card. compileChart has honoured
  //    `on('role')` since the hard-section merge (20-compile.js:102), and the ROLE block has always drawn
  //    a working-looking toggle, but this list is what becomes toto_inj_off — so the key never arrived
  //    and the switch moved nothing. Found by diffing the gates the engine reads against the switches the
  //    card ships. THIS LIST IS THE CONTRACT: a block with a toggle and no key here is a switch with
  //    nothing behind it, which is worse than no switch.
  const TOGGLE_BLOCKS = ['yoga', 'substrate', 'ethics', 'register', 'role', 'tools', 'env', 'identity', 'persona', 'wetware', 'bio']   // 'register' added 2026-08-29 (the rules of the room, 10-soul.js) — toggle only; its editor panel is a later manicure
  const offSet = () => TOGGLE_BLOCKS.filter(k => !active('pc-' + k))
  // a LIVE getter — reads this card's own DOM (so the preview updates per keystroke), falling back to
  // saved state for anything not on screen (notes, profiles). ethics is serialized from its rows.
  const liveGet = k => {
    if (k === 'toto_inj_ethics') return JSON.stringify([...card.querySelectorAll('.pc-eth')].map(e => ({
      rule: e.querySelector('.pc-eth-rule').textContent.trim(),
      note: e.querySelector('.pc-eth-note').textContent.trim(),
      on: e.querySelector('.pc-inj').classList.contains('on'),
    })))
    const el = card.querySelector(`[data-k="${k}"]`)
    return el ? el.value : (localStorage.getItem(k) || '')
  }

  // THE PREVIEW IS THE COMPILER. one function (engine.compileChart) builds the chart; here we feed it the
  // live DOM + the toggles, in the runtime/woodshop we feed it saved state. same compiler → what you see
  // here IS the virtual file IS what the bot gets. (the convo is the live TAIL, shown in its own block.)
  function build() {
    const raw = window.compileChart ? window.compileChart(curAgent, liveGet, offSet()) : ''
    card.querySelector('.pc-preview-raw').textContent = raw
    card.querySelectorAll('.pc-tok-n').forEach(el => el.textContent = '~' + Math.round(raw.length / 4))
  }

  // re-render the agent-keyed blocks when you switch agents (loads that agent's identity/persona)
  function renderAgentFields() {
    const idB = card.querySelector('#pc-identity .pc-body'), peB = card.querySelector('#pc-persona .pc-body')
    if (idB) idB.innerHTML = identityBody(curAgent)
    if (peB) peB.innerHTML = personaBody(curAgent)
    const toB = card.querySelector('#pc-tools .pc-body'); if (toB) toB.innerHTML = toolsBody(curAgent)   // tools are per-agent too
    const npB = card.querySelector('#pc-notepad .pc-body'); if (npB) npB.innerHTML = notepadBody(curAgent)   // the per-bot notepad
    card.querySelector('#pc-model-wrap').innerHTML = injModelSelect(curAgent)
    card.querySelector('#pc-skin-wrap').innerHTML = injSelect(botKey(curAgent, 'skin'), SKINS_LIST, window.botDefaultSkin && window.botDefaultSkin(curAgent))
    // persist on input (this was MISSING for the model select → the chosen model never saved → bots fell back
    // to "no key yet"). injSet the field, THEN recompile the preview. covers model · skin · persona · identity.
    // input (textareas) AND change (WebKit's <select> fires 'change', NOT 'input' → the model/skin picks never saved)
    ;['input', 'change'].forEach(ev => card.querySelectorAll('#pc-identity .pc-area, #pc-persona .pc-area, #pc-model-wrap .pc-sel, #pc-skin-wrap .pc-sel').forEach(el => el.addEventListener(ev, () => { persistField(el); build() })))
    const cv = card.querySelector('.pc-convo')   // the conversation block is per-agent too — re-scope it to this bot
    if (cv) { cv.dataset.k = 'toto_inj_convo_' + curAgent; cv.value = injGet('toto_inj_convo_' + curAgent) || serializeHist(curAgent) }
    // …and its history TOOLS (trim/compact · turns/% · slider) — each bot saves its own
    const hm = injGet('toto_inj_histmode_' + curAgent)
    card.querySelectorAll('.pc-mode').forEach(b => b.classList.toggle('on', b.dataset.mode === (hm === 'compact' ? 'compact' : 'trim')))
    const tm = injGet('toto_inj_thmode_' + curAgent) || 'turns'
    card.querySelectorAll('.pc-th').forEach(b => b.classList.toggle('on', b.dataset.th === tm))
    card.querySelector('.pc-th-turns')?.classList.toggle('off', tm !== 'turns')
    card.querySelector('.pc-th-pct')?.classList.toggle('off', tm !== 'pct')
    const tn = injGet('toto_inj_turns_' + curAgent) || 20, tEl = card.querySelector('.pc-turns'), tvEl = card.querySelector('.pc-turns-val')
    if (tEl) tEl.value = tn; if (tvEl) tvEl.textContent = tn
    const pEl = card.querySelector('.pc-pct'); if (pEl) pEl.value = injGet('toto_inj_histpct_' + curAgent) || 70
    if (typeof setHistNote === 'function') setHistNote()
    if (typeof renderNotes === 'function') renderNotes()   // refresh the notes trays for the new agent
    build()
  }

  const agentSelEl = card.querySelector('[data-k="toto_inj_agent"]')

  agentSelEl.addEventListener('change', () => { curAgent = agentSelEl.value; injSet('toto_inj_agent', curAgent); renderAgentFields() })

  // ⭐ THE CARD LISTENS NOW (Sum 2026-08-25: "any change, card refreshes"). Two feeds, because two
  //    different things change under this card and neither one used to reach it.
  //
  //  ① THE ROSTER — REG.onChange. This picker only ever rebuilt because the ＋/－ handlers rebuilt it
  //    themselves, so when they went, the last thing that refreshed it went with them. That was already
  //    the wrong shape: a bot hired by forge_agent, on the port, or in any other window never appeared
  //    here until the card was closed and reopened. REG has had the pub/sub for this the whole time —
  //    the card just never subscribed. Now the roster is the source and this follows it.
  //    Keeps the human's current pick if that bot still exists; falls to the first seat if it was fired.
  //
  //  ② THE EDIT — oz-card-dirty, filtered to this card. Fired from makeTool's run() (shell/tools.js), so
  //    it arrives no matter which road made the change: a bot, the loopback port, the CLI, a human.
  //    Guarded on the agent picker still being in the document, so a closed card unsubscribes itself.
  const syncRoster = () => {
    if (!document.contains(agentSelEl)) return
    const r = window.AGENTS_ROSTER || window.REG.agents || []
    const want = r.some(b => b.id === curAgent) ? curAgent : (r[0] && r[0].id) || 'toto'
    agentSelEl.innerHTML = r.map(b => `<option value="${b.id}">${b.label}</option>`).join('')
    agentSelEl.value = want
    if (want !== curAgent) { curAgent = want; injSet('toto_inj_agent', curAgent) }
    renderAgentFields()
  }
  try { window.REG && window.REG.onChange && window.REG.onChange(syncRoster) } catch (_) {}
  // ⭐ ONE NAME NOW (26 Aug — Sum: "folder got folded into injections… start folding dups and repoint
  //    stale names"). This card rendered as CARD_BUILDERS.folder while its TOOLS filed under the
  //    TOOLKITS.cards category 'injection', and six agent navs named the category — so the render key was
  //    the only thing in the app still saying "folder". The file is cards/injection/, the icon is
  //    injection.png, the title is "injection config". Only the id lagged. It is 'injection' throughout.
  //    Notes also change from other surfaces (the clipboard, the library projection), so re-read the
  //    store on ANY dirty and re-render the agent fields only for our own.
  window.addEventListener('oz-card-dirty', e => {
    if (!e.detail) return
    if (!document.contains(agentSelEl)) return
    curNotes = loadNotes(); renderNotes()
    if (e.detail.card === 'injection') renderAgentFields()
  })

  // ⛔ CUT 2026-08-25 (Sum: "delete a custom agent is stale… we have no working build a custom agent, is
  //    stale form like january… if we do have add agent, that is where delete will be"). What was here:
  //    ＋ called REG.addAgent(id, label) and set the bot's name — a ROSTER LINE AND NOTHING ELSE. No persona,
  //    no tools, no nav, no bench, no bean. That is the half-born bot exactly, made on purpose by a button.
  //    － called REG.removeAgent and cleared seven keys, leaving the bench and the AGENT_DATA entry behind:
  //    a half-delete to match the half-create. A pair that could each do half a job, in a card that owns
  //    neither hiring nor firing.
  //    THE WHOLE JOB LIVES ON THE AXE CARD NOW: forge_agent hires (persona · cards · tools · role · bench,
  //    checked at the door, seated in the bean and persisted) and fire_agent lets go (all five surfaces,
  //    and it refuses any bot with a folder on disk). Both read back what the surface says, not what they claim.
  //    When add-agent comes back as a real form, delete belongs beside it — his call, and it is one place.
  //    The cut is whole in _recycle/2026-08-25-injection-stale-add-delete-agent.js.
  //    ↺ STAYS. It is the only one of the three that was never stale, and it is the door that pulls a bot's
  //    chart back out of its folder — see also the missing bean for it (the nurse's job, not built).

  // ↺ — reset THIS bot's chart to its baked default (full identity: name · pronouns · backstory ·
  // persona · model · skin). leaves the shared injection lesson alone. confirm first — it's a wipe.
  card.querySelector('.pc-agent-reset').addEventListener('click', async () => {
    if (!window.resetAgentToDefault) return
    if (!await window.ozConfirm(`reset "${curAgent}" to its default chart? your edits to this bot — name · persona · backstory · model · skin — will be lost.`)) return
    window.resetAgentToDefault(curAgent)
    renderAgentFields()                                                  // re-render the bot fields with the restored defaults
    if (window.rebuildAgentIfLive) window.rebuildAgentIfLive(curAgent)   // flip the live bar's look too, if it's up
  })

  // collapse / expand (ignore clicks on the include toggle)
  card.querySelectorAll('.pc-head').forEach(h => h.addEventListener('click', e => {
    if (e.target.classList.contains('pc-inj') || e.target.classList.contains('pc-title-edit')) return
    h.parentElement.classList.toggle('open')
  }))
  // editable block titles (the patient label) → persist; empty shows a hint
  card.querySelectorAll('.pc-title-edit').forEach(t => t.addEventListener('input', () => injSet(t.dataset.tk, t.textContent.trim())))
  // include toggles → rebuild
  card.addEventListener('click', e => {
    if (!e.target.classList.contains('pc-inj')) return
    e.stopPropagation(); e.target.classList.toggle('on'); build()
  })
  // any text edit → rebuild
  card.querySelectorAll('.pc-area, .pc-eth-rule, .pc-eth-note, .pc-sel').forEach(el => el.addEventListener('input', build))
  // turns slider
  // turns slider (the trim-by-turns threshold) + % input
  const turns = card.querySelector('.pc-turns'), tv = card.querySelector('.pc-turns-val')
  if (turns) turns.addEventListener('input', () => { tv.textContent = turns.value; injSet('toto_inj_turns_' + curAgent, turns.value); if (window.pulse) window.pulse('ctx') })
  const pctIn = card.querySelector('.pc-pct')
  if (pctIn) pctIn.addEventListener('input', () => { injSet('toto_inj_histpct_' + curAgent, pctIn.value); if (window.pulse) window.pulse('ctx') })
  // history policy — trim (drop oldest) vs compact (fold middle → summary)
  const histNote = card.querySelector('.pc-hist-note')
  function setHistNote() {
    const m = card.querySelector('.pc-mode.on')?.dataset.mode
    histNote.textContent = m === 'compact'
      ? 'fold the middle of the chat into a summary; keep the injection + recent. compact now any time.'
      : 'drop the oldest; keep the injection (settings + the harness) and as much recent as fits.'
  }
  card.querySelectorAll('.pc-mode').forEach(b => b.addEventListener('click', () => {
    card.querySelectorAll('.pc-mode').forEach(x => x.classList.toggle('on', x === b))
    injSet('toto_inj_histmode_' + curAgent, b.dataset.mode); setHistNote(); if (window.pulse) window.pulse('ctx')
  }))
  setHistNote()
  // threshold type — by turns (the slider) or by % of context
  card.querySelectorAll('.pc-th').forEach(b => b.addEventListener('click', () => {
    card.querySelectorAll('.pc-th').forEach(x => x.classList.toggle('on', x === b))
    injSet('toto_inj_thmode_' + curAgent, b.dataset.th)
    card.querySelector('.pc-th-turns').classList.toggle('off', b.dataset.th !== 'turns')
    card.querySelector('.pc-th-pct').classList.toggle('off', b.dataset.th !== 'pct')
  }))
  // clear the actual conversation — wipes stored history + the live bar + this view
  card.querySelector('.pc-clear').addEventListener('click', () => {
    const a = injGet('toto_inj_agent') || ((window.AGENTS_ROSTER || [{ id: 'toto' }])[0].id)
    if (window.clearConvo) window.clearConvo(a)
    injSet('toto_inj_convo_' + a, '')                                  // clear THIS bot's view, not a global one
    const ta = card.querySelector('.pc-convo'); if (ta) ta.value = ''
    const btn = card.querySelector('.pc-clear'); btn.textContent = '✓ cleared'; setTimeout(() => btn.textContent = '🗑️ clear conversation', 1500)
  })
  // edits to the conversation view persist to THIS bot's per-agent key (data-k re-scopes on agent switch)
  const cvEl = card.querySelector('.pc-convo')
  if (cvEl) cvEl.addEventListener('input', () => injSet(cvEl.dataset.k, cvEl.value))
  // + add principle
  card.querySelector('.pc-add-eth').addEventListener('click', () => {
    const list = card.querySelector('.pc-eth-list')
    const row = document.createElement('div'); row.className = 'pc-eth'
    row.innerHTML = `<div class="pc-eth-head"><div class="pc-eth-rule" contenteditable="true" spellcheck="false"></div><span class="pc-flex"></span><div class="pc-inj on"></div></div><div class="pc-eth-note" contenteditable="true" spellcheck="false"></div>`
    list.appendChild(row)
    row.querySelectorAll('.pc-eth-rule, .pc-eth-note').forEach(el => el.addEventListener('input', build))
    row.querySelector('.pc-eth-rule').focus()
  })
  // copy the assembled injection
  card.querySelector('.pc-copy').addEventListener('click', () => navigator.clipboard.writeText(card.querySelector('.pc-preview-raw').textContent))
  // reset to default — clear the builder's own keys + remount → the lesson returns
  card.querySelector('.pc-reset').addEventListener('click', resetInjection)
  // save — commit every bound field, flash
  card.querySelector('.pc-save').addEventListener('click', () => {
    card.querySelectorAll('[data-k]').forEach(el => persistField(el))   // skin rides its default-aware write → never blanket-pins the default (the clobber vector)
    // 🥚 — toto and PA are the SAME bot in the demo (one model · tools · baked · ethics; just a different hat).
    // their LLM stays LOCKED: change one, the other follows. (discover it — give toto opus, find PA on opus too.)
    // ── CORRECTION 26 Aug: was `curAgent === 'toto' || curAgent === 'pa'`, with both names written
    //    again inside. The SAME lock is wired in shell/settings.js wireModel — one rule, two cards,
    //    four hardcoded names, and nothing tying them together. The pair is now declared on the bots
    //    ("modelTwin", each naming the other), so both surfaces read one field and stay in step.
    const _twin = (window.AGENT_DATA && window.AGENT_DATA[curAgent] && window.AGENT_DATA[curAgent].modelTwin) || ''
    if (_twin) {
      const m = injGet(botKey(curAgent, 'model'))
      if (m) { injSet(botKey(curAgent, 'model'), m); injSet(botKey(_twin, 'model'), m) }
    }
    if (turns) injSet('toto_inj_turns_' + curAgent, turns.value)
    // ethics rows aren't data-k — serialize them so the homework survives
    const eth = [...card.querySelectorAll('.pc-eth')].map(e => ({
      rule: e.querySelector('.pc-eth-rule').textContent.trim(),
      note: e.querySelector('.pc-eth-note').textContent.trim(),
      on: e.querySelector('.pc-inj').classList.contains('on'),
    }))
    injSet('toto_inj_ethics', JSON.stringify(eth))
    injSet('toto_inj_off', JSON.stringify(offSet()))   // persist the include-toggles so ships == preview
    // re-compile the warm head to its virtual file so the woodshop + runtime load the edit. ONE compiler
    // (engine.compileChart); the soul edit re-caches EVERY agent (it's shared), the rest just this one.
    if (window.cacheAllCharts) window.cacheAllCharts(); else if (window.cacheChart) window.cacheChart(curAgent)
    const b = card.querySelector('.pc-save'); b.textContent = 'saved ✓'; setTimeout(() => b.textContent = 'save', 1800)
  })

  // ── notes wiring ─────────────────────────────────────────────────────
  // TWO trays, TWO homes, ONE wiring (Sum 2026-08-25). wireNotes takes a root instead of closing over a
  // single body — the handlers were never about which column they were in, and two copies of them would
  // be two things to keep in step, which is never what happens.
  const notesBody = card.querySelector('.pc-notes-body')
  const botNotesBody = card.querySelector('.pc-botnotes-body')

  function renderNotes() {
    notesBody.innerHTML = buildNotesHtml(curNotes)
    wireNotes(notesBody)
    if (botNotesBody) { botNotesBody.innerHTML = botNotesHtml(curNotes, curAgent); wireNotes(botNotesBody) }
  }

  // PULSE: a save in any bot's home (a new course · skill · project · voice) → re-read the LIVE projection
  // and re-render, but only while this card is on screen. no polling, no version bumps.
  if (window.onPulse) window.onPulse('library', () => {
    if (notesBody && document.body.contains(notesBody)) { curNotes = loadNotes(); renderNotes() }
  })

  function wireNotes(root) {
    root.querySelectorAll('.pc-file-tog').forEach(tog => {
      tog.addEventListener('click', e => {
        e.stopPropagation()
        const name = tog.closest('.pc-note-file').dataset.name
        const note = curNotes.find(n => n.name === name)
        if (!note) return
        note.on = !note.on; tog.classList.toggle('on', note.on)
        saveNotes(curNotes); build()
      })
    })
    root.querySelectorAll('.pc-note-open').forEach(el => {
      el.addEventListener('click', e => {
        e.stopPropagation()
        noteOpen(curNotes.find(n => n.name === el.dataset.name))   // open it where it lives (clipboard / tiptap)
      })
    })
    root.querySelectorAll('.pc-src').forEach(b => {
      b.addEventListener('click', e => {
        e.stopPropagation()
        const note = curNotes.find(n => n.name === b.dataset.name); if (!note) return
        note.source = note.source === 'hil' ? 'ai' : 'hil'   // 🤖 AI ⇄ 🧑 HIL (who wrote it)
        saveNotes(curNotes); renderNotes()
      })
    })
    root.querySelectorAll('.pc-file-del').forEach(btn => {
      btn.addEventListener('click', () => {
        const note = curNotes.find(n => n.name === btn.dataset.name)
        if (note && note.lib) { if (window.botLibraryRemove) window.botLibraryRemove(note) }   // projected → delete it AT ITS HOME (so it stops projecting back)
        else { curNotes = curNotes.filter(n => n.name !== btn.dataset.name); saveNotes(curNotes) }
        curNotes = loadNotes(); renderNotes(); build()
      })
    })
    root.querySelectorAll('.pc-folder-tog').forEach(tog => {
      tog.addEventListener('click', e => {
        e.stopPropagation()
        const folder = tog.closest('.pc-note-folder').dataset.folder
        const folderNotes = curNotes.filter(n => n.folder === folder)
        const anyOn = folderNotes.some(n => n.on)
        folderNotes.forEach(n => n.on = !anyOn)
        saveNotes(curNotes); renderNotes(); build()
      })
    })
    root.querySelectorAll('.pc-folder-del').forEach(btn => {
      btn.addEventListener('click', () => {
        curNotes = curNotes.filter(n => n.folder !== btn.dataset.folder)
        saveNotes(curNotes); renderNotes(); build()
      })
    })
    root.querySelectorAll('.pc-folder-caret, .pc-folder-name').forEach(el => {
      el.addEventListener('click', e => {
        e.stopPropagation()
        el.closest('.pc-note-folder').classList.toggle('collapsed')   // tree view: name/caret toggles, dot still toggles-all, ✕ still deletes
      })
    })
    // ⭐ THE CARET + THE BOX (Sum 2026-08-25). Caret or name opens the note in place; nothing leaves the
    //    card. A projection has no caret and keeps `open ↗` — its home is elsewhere and this would edit a copy.
    root.querySelectorAll('.pc-note-caret, .pc-note-name').forEach(el => {
      el.addEventListener('click', e => {
        e.stopPropagation()
        el.closest('.pc-note-file').classList.toggle('collapsed')
      })
    })
    // typing in the box writes the note. saveNotes() is the ONE save path — it recompiles every head, so
    // an edit here reaches the prompt without a second mechanism to remember.
    root.querySelectorAll('.pc-note-text').forEach(t => {
      t.addEventListener('input', () => {
        const note = curNotes.find(n => n.name === t.dataset.name); if (!note) return
        note.body = t.value
        saveNotes(curNotes); build()
      })
      // the block header's collapse listener sits above this; a click in the textarea is not a collapse.
      t.addEventListener('click', e => e.stopPropagation())
    })
    root.querySelectorAll('.pc-note-add').forEach(btn => btn.addEventListener('click', async () => {
      const owner = btn.dataset.owner || 'hil'   // the +note button knows its tray (shared vs this bot)
      const display = (await window.ozPrompt('note name (e.g. new-note.md):'))?.trim()
      if (!display) return
      curNotes.push({ folder: null, name: 'note-' + Date.now(), display, on: false, body: '', owner, source: 'hil' })   // a human added it → HIL
      saveNotes(curNotes); renderNotes()
    }))
  }

  renderNotes()
  renderAgentFields()
}

// reset to default — wipe the builder's own keys (toto_inj_*); your bio + bots stay.
// remount → the baked defaults (yamas homework, substrate, yoga…) come back: the lesson.
function resetInjection() {
  Object.keys(localStorage).filter(k => k.startsWith('toto_inj_')).forEach(k => localStorage.removeItem(k))
  if (window.toggleCard) { window.toggleCard('injection', false); window.toggleCard('injection', true) }
}

window.CARD_BUILDERS.injection = buildInjection   // (26 Aug) was .folder — one name now: file, folder, icon, title and id all say injection
